### ISSUE TITLE
Distorted view on Moto G (1st gen)

### ISSUE THREAD

**Issue by matzon** [koush/vysor.io#1]
Connects fine, but get a distorted image:

![image](https://cloud.githubusercontent.com/assets/2757333/9461183/a11e5142-4b0c-11e5-9594-04b09a7f45f4.png)

**Comment by koush** [comment]
make sure hardware webgl is enabled in chrome.

**Comment by matzon** [comment]
[Output from chrome://gpu](https://drive.google.com/file/d/0B_ytw_6QA1WJeWZmVEZHdVdDRlk/view?pli=1)
Should be enabled, however it does mention Video Encode to be software only?

**Comment by urbels** [comment]
It`s for Desktop. :)

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/3

**Comment by koush** [comment]
And yes, desktop chrome output.

**Comment by matzon** [comment]
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated

However I am seeing a:
Log Messages
WARNING: Hardware acceleration is unavailable.

Which may or may not be related to:
Disable use of Direct3D 11 on older AMD drivers: 402134
Applied Workarounds: disable_d3d11

I will double check when I get home, so assume that it's a end-user problem and not the app itself (which might want to add a warning of some sorts though).

**Comment by koush** [comment]
```
Canvas: Software only, hardware acceleration unavailable
```

I'll need to detect this and warn...

**Comment by koush** [comment]
fixed with warning notification if webgl is busted
