### ISSUE TITLE
Allow direct connections to a device over TCP or UDP

### ISSUE THREAD

**Issue by The-MAZZTer** [koush/vysor.io#10]
Normally, probably a terrible idea from a bandwidth/lag perspective if you're on WiFi (since in my experience USB is faster). But a small number of devices have ethernet (or a virtual network if you are using an android emulator) so it could be useful.

**Comment by mralext20** [comment]
you can already do this if you have adb installed.

use your adb binary to connect to the networked device, and it will show up.

adb connect ip:port

**Comment by The-MAZZTer** [comment]
So it does. I guess I wasn't connected when I first launched the app.

**Comment by The-MAZZTer** [comment]
Though on second thought, I'll leave this open. I am sure other users might appreciate UI for this.

**Comment by koush** [comment]
there's a button that lets you type in an ip now.
