### ISSUE TITLE
Allowing sharing from a machine that's headless and/or with old version of chrome, or no 3D

### ISSUE THREAD

**Issue by marcmerlin** [koush/vysor.io#100]
If you'd like to connect to a device connected to an old machine in a closet, do you have a simple low level client that just does enough work to adb and forward the bits to the remote display client  that's running an up to date version of chrome with WebGL?

**Comment by koush** [comment]
Requires a Chrome app at the moment. No headless version.

**Comment by koush** [comment]
Also, I'll only be supporting the most recent version of Chrome (and deprecating older ones, even if they worked before). Chrome platform moves pretty fast, can't invest the time in legacy support.

**Comment by marcmerlin** [comment]
Thanks for your answers, I appreciate it.
On my side, I found that this should solve my problem:
https://play.google.com/store/apps/details?id=com.vmlite.vncserver&hl=en

**Comment by marcmerlin** [comment]
ok, in case others care  @koush you likely already knew that, the vncserver option works fine on a headless server, but it's slow.
@koush really did a great job making his solution fast in comparison. 
Now I just have to see or wait until I can make it work for the server side only (not the remote client displaying the result) without a recent X/chrome, and if not vncserver will have to do.

**Comment by marcmerlin** [comment]
I was able to get local X to run on that machine (without 3D/GPU), and get google-chrome-beta --disable-gpu to work too.
vyzor of course has broken display in that case, but my only goal was to share that display to my laptop which has working WebGL.
In other words, I got things working, but please don't remove the option to run vyzor without WebGL since in the remote display case, it's ok if local display isn't working due to lack of WebGL support.
Thanks for the great work.

**Comment by koush** [comment]
This is coming. There will be standalone desktop apps.

**Comment by koush** [comment]
Standalone desktop versions available.
