### ISSUE TITLE
login in Visor on a new Mac m1 pro and google account not working with Safari

### ISSUE THREAD

**Issue by JoacimWall** [koush/vysor.io#1009]
When I try with Safari I get this 
<img width="803" alt="Screenshot 2022-01-11 at 08 32 48" src="https://user-images.githubusercontent.com/9278908/148899940-e42aec6f-6c83-4153-848c-f27a268dec6a.png">
if I do the same with Google Chrome it's works.

**Comment by koush** [comment]
You need to paste the token in. It's blank in your screenshot. Works fine here on my M1.

**Comment by JoacimWall** [comment]
Thanks cheated by placeholder :)
