### ISSUE TITLE
Android: [Question] Cannot see my device until I use USB cable

### ISSUE THREAD

**Issue by kossa** [koush/vysor.io#1014]
Hello,

There is a way to connect to my phone(Samsung) without USB cable, directly using WIFI?

Thanks

**Comment by koush** [comment]
not possible

**Comment by kossa** [comment]
FYI I fixed it by fixing IP for my phone and connect via network

![image](https://user-images.githubusercontent.com/1175584/150190565-9b50c288-6997-4aa3-b4dc-aff8c844829a.png)

**Comment by koush** [comment]
yes that works if the phone has not rebooted.
