### ISSUE TITLE
Can't reinstall Vysor on windows 11 after uninstall it

### ISSUE THREAD

**Issue by rifanip** [koush/vysor.io#1015]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. install vysor desktop
2. Connect android and iOS
3. uninstall vysor on android & desktop
4. install again (see attach)

**Expected behavior**
Successfully installation

**Screenshots**
![image](https://user-images.githubusercontent.com/3964885/150245670-fc49d0f0-aad0-4ab1-8032-9ea0d22a6875.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Android (please complete the following information):**
 - Device: [Xiaomi Redmi Mi5]
 - OS: [Android 8]
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**
here's the log
[SquirrelSetup.log](https://github.com/koush/vysor.io/files/7901544/SquirrelSetup.log)

**Comment by rifanip** [comment]
case closed
deleted folder vysor in AppData
![image](https://user-images.githubusercontent.com/3964885/150247671-3608b375-f0e9-4654-a547-6d559ec248e9.png)

**Comment by koush** [comment]
restart and delete this

`'C:\Users\akuan\AppData\Local\vysor\`
