### ISSUE TITLE
Payment screen not getting mirrored, just a black screen is shown

### ISSUE THREAD

**Issue by dhana-r** [koush/vysor.io#1017]
Hi, I am using vysor app and with Samsung pay, and I see a black screen while entering so payment card information(both scanning the card or entering manually). This behaviour is inconsistent as subsequent card screens it is rendering properly. can you check and let me know if some settings have to be changed? Note: I am using Mac and Vysor.

**Comment by koush** [comment]
yes screens with sensitive information can not be mirrored.

**Comment by DripMicro** [comment]
Hello, is this issue still not resolved?
