### ISSUE TITLE
iOS: When performing screen rotation, the saved recording presents video issues.

### ISSUE THREAD

**Issue by softvision-raul-bucata** [koush/vysor.io#1019]
**You must attach a Vysor Bug Report Link**

https://user-images.githubusercontent.com/75027050/151559911-2aad73f4-45bc-4aca-9e7e-dceb0cbb1e06.mp4

**To Reproduce**

1. Start the recording option via the Vysor App in Windows.
2. Go to 'youtube.com' using Firefox on an iOS device.
3. Click on 'any video.'
4. Play the video in full-screen mode and rotate the screen.
5. Observe.

**Expected behavior**
The screen recording saved into the Windows PC presents no issues when played.

**Actual behavior**
The screen recording presents video issues.

**Desktop :**
 - OS: [Windows 10x64]

**iOS (please complete the following information):**
 - Device: [Iphone SE]
 - OS: [iOS 15.3]

**Comment by koush** [comment]
This can't be fixed because mp4 does not support resolution change mid stream.

**Comment by koush** [comment]
Start the video in the intended resolution.
