### ISSUE TITLE
Feature Request: Back mouse button

### ISSUE THREAD

**Issue by asheroto** [koush/vysor.io#1020]
Hi, not a bug report but a feature request.

On my mouse I have a button to go "back" and a button to go "forward"... typical uses involve a web browser. If I press the "back" mouse button it will go back to the previous page.

I'd like to see this available on Vysor so I can press "back" on my mouse and it will tap the back arrow on Android.

I am a subscriber.

Thanks!

**Comment by koush** [comment]
vysor supports keybindings, please read the wiki/documentation on Customize Vysor.
