### ISSUE TITLE
Android: Some application aren't displayed 

### ISSUE THREAD

**Issue by Herve-Epp** [koush/vysor.io#1023]
https://gist.github.com/0e86e84a3c9861f97e7d34c5d481e0e9

**To Reproduce**
When opening some application like Credit Mutuel or MobilePASS+
The mirrored screen only display a part of the sceen (for MobilePASS+) or a black screen (for Credit Mutuel). 
On the android device for credit Mutuel the login page is displayed but not on the mirrored screen.

**Expected behavior**
Apps screens should be displayed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS (Version 97.0.4692.102 (Build officiel) (64 bits)). using the Linux vysor app.

**Android (please complete the following information):**
 - Device: Samsung galaxy A10
 - OS: Android 11
 - Vysor Bug Report Link: https://gist.github.com/0e86e84a3c9861f97e7d34c5d481e0e9

**Additional context**

**Comment by koush** [comment]
correct, some sensitive applications disallow screen recording for security.
