### ISSUE TITLE
iOS: Vysor application is not opening on Test Flight

### ISSUE THREAD

**Issue by Shtibel** [koush/vysor.io#1025]
Vysor application is not opening on Test Flight
I get error:
"Vysor" Beta has expired

Please help
![Skype_Picture_2022_02_06T14_55_38_500Z](https://user-images.githubusercontent.com/24429607/152686732-ec6e74ce-36f9-4f83-bdf0-3591161f4c64.jpeg)

**Comment by Baotao0928** [comment]
The Vysor is not available now on Test Flight.

**Comment by Shtibel** [comment]
> The Vysor is not available now on Test Flight.

When will it be back ?

**Comment by NSGangster** [comment]
Please please PLEASE get this beta back up. Just got a new iPad I'd like to screen mirror on a windows and really don't want to explore other options been a long time user of vysor.

**Comment by JimHume** [comment]
The release version of the software finally made it to the app store. It can be downloaded as a legitimate application at this point.

**Comment by Shtibel** [comment]
> The release version of the software finally made it to the app store. It can be downloaded as a legitimate application at this point.

Hi @JimHume 
I can't find the app on App store
Can you please share the link ?

**Comment by Shtibel** [comment]
@koush 
We can't find the app on App store
Please share a link to install

**Comment by NSGangster** [comment]
https://apps.apple.com/us/app/vysor/id1577813680 Here y’all go. Works ok for a v1 noticed a screenshot orientation issue but I’ll maybe open a seperate ticket.

**Comment by koush** [comment]
app has been officially released. locking this issue
