### ISSUE TITLE
Lifetime License not recognized

### ISSUE THREAD

**Issue by Save36** [koush/vysor.io#1026]
Hi, I have a lifetime Pro license, but since the last update for desktop app (4.1.103) it is not recognized.
It's a Chrome Web Store License, but when I paste the generated code it's not recognised from Vysor.

What should I do?

**Comment by bensmiley** [comment]
I also have the same problem. I bought a license but it is no longer recognized. I've emailed support multiple times but no reply.

**Comment by koush** [comment]
are you both chrome licenses? those are deprecated, and google may turn them off at any moment. wondering if they finally did that. I'd double check the email on your receipt matches your login on vysor.

**Comment by Save36** [comment]
Yes, mine was a chrome license on the account Save36@gmail.com

**Comment by Rook25** [comment]
Same issue here. Have assumed this is a scam. I paid via paypal and have made sure to be signed in using the correct gmail account but my lifetime license isn't found.

I tried to get in contact months ago but my issue was just closed with no comments.

**Comment by koush** [comment]
Chrome licenses must log in with the secondary Chrome app. In any case, Chrome web store purchases were subsetted like 5 years ago, and Google may stop honoring them at any moment. Nothing I can do about this. https://chromeunboxed.com/google-announces-timeline-for-the-end-of-chrome-apps-on-chromebooks/
