### ISSUE TITLE
iOS: The only way to use this was in testflight and now that is gone, are we past Beta yet so we can use a released version?

### ISSUE THREAD

**Issue by 4Goose** [koush/vysor.io#1028]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
A short description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 11.4.10]

**iOS (please complete the following information):**
 - Device: [e.g. iPhone 12 Pro]
 - OS: [e.g. iOS 14.1]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**iOS Bluetooth Issues (optional):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**

**Comment by mfoleyshift** [comment]
Just noticed this today myself.   Eager to see what the plans are moving forward.

**Comment by scheng924** [comment]
same, would love to understand when we can join

**Comment by Seidak** [comment]
same here 👀

**Comment by koush** [comment]
it's in review now

**Comment by Shtibel** [comment]
Any update ?

**Comment by mril** [comment]
hello,
 no updates?
there's no other way to have iOS stream with vysor besides testflight ?

**Comment by koush** [comment]
everyone should keep asking for updates, it's something that's totally within my control

**Comment by Loveqauser** [comment]
hello, may we know by when we can expect vysor available for IOS? unable to use it's beta version anymore
