### ISSUE TITLE
Black screen, "android screen is unavailable"

### ISSUE THREAD

**Issue by Jspoor** [koush/vysor.io#103]
Your universal ADB driver installed
using adb over network, latest android SDK kit

Android version 5.1.1

bacground log
Vysor version 1.0.6.4
uglify.js:2 Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
uglify.js:1 gcm registration APA91bF9w9eUZ0w9wAfwhw9OxUy-2gzurjqmMi_AEAw0w6ynAlywb1LuWODBL8_e-Z_3AXhN5IG0IuimscL8Pxk5UUY0ZYX_IU1oBCfNEm0j9-uhfXfpvKgTcmBdtHe2KPoOr3i4X4ahHAsuXSPKaMTSuBDXEnw5Vg
uglify.js:2 protocol version: vysor-io-12
uglify.js:2 using /system/bin/app_process32
uglify.js:2 got main socket Socket
uglify.js:2 set password 
uglify.js:2 protocol version: vysor-io-12
uglify.js:2 using /system/bin/app_process32
uglify.js:2 got main socket Socket {socketId: 63211, pendingLength: 4}
uglify.js:2 set password 

screen log
increasing TOTAL_MEMORY to 67108864 to be compliant with the asm.js spec (and given that TOTAL_STACK=5242880)
avc-codec.js:1 pre-main prep time: 2 ms
uglify-screen.js:1 init
uglify-screen.js:1 WebSocket connection to 'ws://127.0.0.1:53516/input' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
uglify-screen.js:1 input websocket failed, retrying. attempt 1 out of 5
uglify-screen.js:1 input websocket opened
uglify-screen.js:1 {"type":"displaySize","screenWidth":800,"screenHeight":600,"nav":true}
uglify-screen.js:1 new window dimensions: 590x442.5
uglify-screen.js:1 adb client socket path
uglify-screen.js:1 received socket Socket
uglify-screen.js:1 notification: Your Android screen is unavailable right now. This can sometimes be resolved by rebooting your Android.
uglify-screen.js:1 init
uglify-screen.js:1 WebSocket connection to 'ws://127.0.0.1:53517/input' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
uglify-screen.js:1 input websocket failed, retrying. attempt 1 out of 5
uglify-screen.js:1 input websocket opened
uglify-screen.js:1 {"type":"displaySize","screenWidth":800,"screenHeight":600,"nav":true}
uglify-screen.js:1 new window dimensions: 590x442.5
uglify-screen.js:1 adb client socket path
uglify-screen.js:1 received socket Socket
uglify-screen.js:1 notification: Your Android screen is unavailable right now. This can sometimes be resolved by rebooting your Android.

**Comment by Jspoor** [comment]
crhome version Version 47.0.2526.80 m
on windows 2012 R2

**Comment by Jspoor** [comment]
vysor version 1.0.6.4

**Comment by arslan70** [comment]
Still getting the same issue with a genymotion VM. I understand VM is different than an actual device but i'll appreciate any help to trouble shoot this issue.

**Comment by koush** [comment]
Will not be supporting genymotion. What's the point?

**Comment by Elakkiyan** [comment]
Your Android screen is unavailable right now. This can sometimes be resolved by rebooting your Android....
What should i dooo????
