### ISSUE TITLE
iOS: Landscape Mode

### ISSUE THREAD

**Issue by luisbroleze** [koush/vysor.io#1034]
Even thought I subscribed the app, it is impossible to go on Landscape mode on IOS. The app doesn't rotate on the pc and the image get squished into vertical mode.

Im using an iPhone 11 into the Windows 11 OS.

**Comment by rkrmpg** [comment]
Concur this is happening in Vysor mirroring
iPhone 11 running iOS 15.1 on a Windows 10 machine and Vysor version 4.1.104 (runtime 4.1.77)

Also happening with same phone and Mac running version 4.1.104 (runtime 4.1.77)

Using Landscape mode on a iPad Air (4th gen) with iOS version 15.4 is displaying fine on Windows 10 and Mac with Vysor version 4.1.104 (runtime 4.1.77)

**Comment by Lemnic** [comment]
Hi, also not able to rotate the screen on Mac (from androïd) with vysor.annual subscription. Please help

<img width="1440" alt="Capture d’écran 2022-03-28 à 12 37 26" src="https://user-images.githubusercontent.com/102519931/160380782-b876fd6d-076e-4c9d-b599-25a294e77037.png">
.

**Comment by Lemnic** [comment]
Thanks Koush ! Paid annual suscription but Zéro service ! 3 weeks to respond that I have to use another app to get landscape mode. Then close immediately the thread without my feed back. Unbelievable. Disgrace ! I signal you.

**Comment by koush** [comment]
it's a duplicate that I'm working on. get a grip.
