### ISSUE TITLE
Android Overlays

### ISSUE THREAD

**Issue by coolloop61** [koush/vysor.io#1037]
Loving the program!! I use it for work everyday so I hope you can help. I do trainings using my devices either live or recorded with Vysor up on the display. Is there anyway to make the application show screen overlays? For example, when I pull my stylus out I get little float bubbles on the screen but they do not show on vysor. Another example would be if I use Android Screen Recording the menu doesn't show up on Vysor but it does on the phone. 

I am using a bunch of different Motorola Phones just so you are aware.

It is strange but the Overlayed Float Bubbles do show up on the moto g stylus(2021) on Android 10 but not any other stylus devices I use.

Hoping a future update has an Overlay capablity or a quick toggle maybe?

Thanks!!

**Comment by coolloop61** [comment]
Sorry to open this up again but I wanted to give you a better image for context. Is there anyway to make overlays such as the ones on my phone screen showup on Vysor? As you can see in my picture, I am showing off the phone but viewers cannot see the floating bubbles on Vysor!
![floatbubbles!](https://user-images.githubusercontent.com/69646433/156438822-bf46d0d7-42fa-4271-a66a-ee6923d70ebd.png)

**Comment by koush** [comment]
ahh I see. seems android doesn't let you capture that. might be on a different layer/surface that cant be grabbed.
