### ISSUE TITLE
Android: Black screen but mouse seems to work

### ISSUE THREAD

**Issue by jtrogdon-pre** [koush/vysor.io#1041]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Just connect and I get a black screen. Screenshot uploaded.

**Expected behavior**
I can connect to the Android device but the screen is black.  I can click my mouse and it will run an icon on the Android screen but I can't see on the PC.  Since my screen if black on the PC, the icon I click is random since I can't see where my mouse is on the Android device. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Screenshot uploaded.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 11.4.10]

**Android (please complete the following information):**
 - Device: [TETON P8303]
 - OS: [Android 5]
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**
![2022-03-01 10_09_54-New Issue · koush_vysor io — Mozilla Firefox](https://user-images.githubusercontent.com/62569075/156196041-c0406a2f-803e-4303-9a64-0b4c4c83a78d.jpg)
[264d6334381ecc03f444e8d18072221e-e87db0d6697d979b0ac01e37b17df95d0db19a5f.zip](https://github.com/koush/vysor.io/files/8162621/264d6334381ecc03f444e8d18072221e-e87db0d6697d979b0ac01e37b17df95d0db19a5f.zip)

**Comment by jtrogdon-pre** [comment]
BTW, the desktop version should be Windows 10.

**Comment by koush** [comment]
android 5 not supported.
