### ISSUE TITLE
Not able to buy Monthly/Anual license.

### ISSUE THREAD

**Issue by Gixar** [koush/vysor.io#1042]
Hello,
I know is not the place, but I been looking and did not find where to go for this issue,
I just want to upgrade to an Anual license, but when I click on upgrade to pro it only show this :

![image](https://user-images.githubusercontent.com/10732967/156861532-0203d2e7-41f9-4f7c-95f2-43d11c0f8087.png)

No link at all, to pay or buy, same with the monthly, spomeone knows where I can contact someone please let me know.
I can pay the lifetime but I just want to test if the app work as I want with pro.

**Comment by koush** [comment]
click the sign up button.
