### ISSUE TITLE
Subscription is incomplete. Initial payment failed. Please update your card.Android: Short Description of Issue

### ISSUE THREAD

**Issue by vdegenne** [koush/vysor.io#1044]
Where Am I supposed to complain when I have a Subscription Issue, not even a button "Contact the team" or I don't know, something that will not make me completely sweating about my credit card information not being updated properly ???
It tells me to update my card which I did like 10 times now within 2 hours but my account still display this message and there is no sign of proper functioning.  
I don't want to wait more, if there is something wrong with the paying method then how can I reject the subscription attempt and do it again.  
I need to use Vysor on the wireless network asap...

**Comment by vijay21p** [comment]
i have the same issue. I am unable to pay and all it says is update the payment card. I have done that in stripe and gpay but problem is that the pay amount says $0.00. Please help ASAP so we can complete the purchase.

**Comment by koush** [comment]
the cards likely got rejected due to fraud protection.
