### ISSUE TITLE
Using Vysor with Philips Hue App

### ISSUE THREAD

**Issue by HarryStamper1** [koush/vysor.io#1045]
Hello,

Since several updates of the Philips Hue App, I encounter issues to use it with Vysor. It's impossible to navigate to the left or to the right inside the application Hue. To be sure, I tried with Teamviewer and all is OK. I also tried to modify Vysor's parameters, without results. Please, can you check and fix the problem, it would be great ? Thanks, best

Samsung A51 5G Android 11

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/982
