### ISSUE TITLE
Android: Unable to connect to control socket on Pro version 4.1.104

### ISSUE THREAD

**Issue by spam-min** [koush/vysor.io#1046]
I can no longer mirror my phone screen to my laptop. 

**Steps to reproduce the behavior:**
1. Plug in device to laptop via USB cable.
2. Allow access to phone
3. Open Vysor and click on play to start mirroring.
4. See error.

**Expected behavior**
I should be able to mirror immediately as soon as I click on the play/start button.

**Desktop (please complete the following information):**
 - MacOS 10.15.7
 - Vysor Pro Version 4.1.104

**Android (please complete the following information):**
 - Device: Samsung Galaxy Note 20
 - OS: Android 11
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/cf7672748266c51860999b4798c06618

**Comment by koush** [comment]
Your adb is crashing for some reason. Might try to kill/restart it or the PC.
