### ISSUE TITLE
iOS: no longer able to record video after cancelling video recording file save prompt

### ISSUE THREAD

**Issue by tomdwp** [koush/vysor.io#1047]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. launch Vysor 
2. connect an iOS device (using lightening to USB-C cable)
3. on the Vysor main screen, click on the 'View Device' button for your iOS device 
4. on the Vysor's iOS device screen, click on the 'Record Screen' icon
5. wait a moment or two (the 'Record Screen' icon should turn red and start to spin)
6. click on the 'Record Screen' icon again to stop the recording
7. when prompted to save the screen recording file, click the cancel button
8. click on the 'Record Screen' icon again (to create a new screen recording)
9. (notice the 'Record Screen' icon turn red and start to spin again)
10. click on the 'Record Screen' icon to stop the recording

**Expected behavior**
* after clicking to stop the recording, you should be again prompted to save the recording

**Actual behavior**
* after clicking to stop the recording, the 'Record Screen' icon turns back to white and stops spinning, but there's no screen recording anywhere

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.1

**iOS (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.3.1
 
**iOS Bluetooth Issues (optional):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**
After rebooting or repeatedly restarting Vysor, I am able to record iOS screens again, but as soon as I click 'cancel' on the screen-recording save file dialog, I am not able to make any further iOS screen recordings.

**Comment by tomdwp** [comment]
since developer doesn't seem to look at these, I'm closing

**Comment by morygonzalez** [comment]
Same here. But I have never cancelled a recording. From the first time I tried to record the screen, I could not record (the prompt has never appeared).

**Comment by sanjay937** [comment]
After Latest Mac and iOS update I can not record at all. and the version of iOS app install is worst than the beta version.
I will appreciate if you provide the beta version app  installation link

**Comment by koush** [comment]
I'm working on resolving the Mac issues now with the new M1 support.

**Comment by koush** [comment]
ok I got this sorted out, its an issue with Monterey. screen capture api call no hangs on Monterey, and the process hangs. causes issues, I presume, with stopping the recording.

**Comment by koush** [comment]
will publish another prerelease tonight.

**Comment by tomdwp** [comment]
> will publish another prerelease tonight.

Where can one pick up a pre-release from?   (I've looked around the website and this github page, but didn't see where they were available)

**Comment by koush** [comment]
https://github.com/koush/vysor.io/releases

**Comment by koush** [comment]
released
