### ISSUE TITLE
My Android device not support screen recording. What can I do??

### ISSUE THREAD

**Issue by kchacon** [koush/vysor.io#105]
Hi,

I have this problem, in my PC appears this message:
"Your android screen is unavailable right now. This can sometimes be resolved by rebooting your Android"

But in my android device appears this message:
"This Android device may not support screen recording. Vysor may not work properly"

How can I enable the screen recording feature??

I hope you can help me!!

Thanks in advanced.

**Comment by BuYanLi** [comment]
我也是这样的情况
