### ISSUE TITLE
iOS: Bluetooth to MacBook Air NO Longer Allowed by iOS

### ISSUE THREAD

**Issue by wx1996-1** [koush/vysor.io#1053]
**You must attach a Vysor Bug Report Link**
1. Try to Bluetooth connect iPhone to MacAir  - the iPhone gets an error Unsupported Device.  
2. iOS - iPhone 13 Pro with 15.4.1. 
3. MacBookAir M1 processor MacOS Monterey 12.3.1.
4. Apple Support advised that as of iOS 15.4 direct Bluetooth connection no longer allowed, as AirDrop and ScreenCast should be used.
5. Tested in Apple store and verified with clean systems.  Works on iOS 15.3.1 but not 15.4.
6. How do you connect Vysor to new system?

![image](https://user-images.githubusercontent.com/103451143/162803291-4dd4a463-9116-4deb-afcb-71ffda5e8782.png)

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/978
