### ISSUE TITLE
Wireless mirroring disconnected after locking phone | Unable to connect wirelessly to device when screen locked

### ISSUE THREAD

**Issue by njm3dl0ck** [koush/vysor.io#1055]
https://gist.github.com/VysorLogs/c2cc7d2721f10103d7836c2400d56a8c

**To Reproduce**
1. Lock your device.
2. From Windows 10, open Vysor and try to wireless connect... it fails.
3. Unlock your phone and try to connect wirelessly with Vysor... it succeeds.
4. Lock device and Vysor disconnects again and displays "Mirroring Disconnected Error: stream ended during read for minimum 4 bytes"
5. Wake device again and unlock it, click "Retry" and successfully reconnect.

**Expected behavior**
Lock and unlock device wireless without losing connection.

**Screenshots**

**Desktop (please complete the following information):**
Device name	....
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	3730E423-B667-47D5-9960-279A2EAA415E
Product ID	00330-52776-34018-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Android (please complete the following information):**
 - OnePlus 9
 - OS: OOS 12 c47 (did not have this problem on OOS 11, fyi)
- https://gist.github.com/VysorLogs/c2cc7d2721f10103d7836c2400d56a8c

**Additional context**
Wired USB connection does not have this problem
_(I have a LogCat and screen shot but its not allowing me to attach it. Let me try and submit this issue and go back and re-add)_

**Comment by njm3dl0ck** [comment]
For some reason it won't let me attach a screenshot (png) or text file (txt). Any ideas?

**Comment by njm3dl0ck** [comment]
For some reason it won't let me attach a screenshot (png) or text file (txt). Any ideas?

**Comment by njm3dl0ck** [comment]
[LogCat.txt](https://github.com/koush/vysor.io/files/8500561/LogCat.txt)
[2022-04-16-124651](https://user-images.githubusercontent.com/103854923/163689569-11d26745-cd91-4291-82b8-15d0e7ab3ea3.png)

Those links work... lmk if they don't?

Thanks in advance for your help...!

**Comment by njm3dl0ck** [comment]
[LogCat.txt](https://github.com/koush/vysor.io/files/8500561/LogCat.txt)
[2022-04-16-124651](https://user-images.githubusercontent.com/103854923/163689569-11d26745-cd91-4291-82b8-15d0e7ab3ea3.png)

Those links work... lmk if they don't?

Thanks in advance for your help...!

**Comment by njm3dl0ck** [comment]
Good morning, just curious if there has been any movement on this issue I'm facing? Can I help troubleshoot at all? Thank you...!

**Comment by njm3dl0ck** [comment]
Good morning, just curious if there has been any movement on this issue I'm facing? Can I help troubleshoot at all? Thank you...!

**Comment by njm3dl0ck** [comment]
Hello, has this been reviewed by chance?
Is there anyway that I can help troubleshoot this with the devs?

**Comment by njm3dl0ck** [comment]
Hello, has this been reviewed by chance?
Is there anyway that I can help troubleshoot this with the devs?

**Comment by njm3dl0ck** [comment]
Hello, would it be possible to get some assistance with this?

**Comment by koush** [comment]
The phone might be turning off wifi or adb wifi when the screen is turned off. I do not see this on my pixel devices.

**Comment by koush** [comment]
lots of phones do weird power saving stuff.
