### ISSUE TITLE
Android: Connection Error: Vysor installation on Android failed

### ISSUE THREAD

**Issue by sfederici** [koush/vysor.io#1056]
Managing the android device via Vysor on the same network works flawlessly. Instead, trying to manage it via device link in the browser or choosing to open Vysor raises a  Connection Error.

**To Reproduce**
1. Share device link in Vysor
2. Insert device link in browser address bar
3. Choose "Open in Browser" or "Launch Vysor"
4. It goes up to "Connecting to Vysor on Android..." but this message stays forever, with no actual connection to the device

**Expected behavior**
Remote control device via shared link

**Desktop (please complete the following information):**
 - MacOS 11.6.1
- Chrome 100.0.4896.88, Firefox 99.0.1,  Safari 14.1.2 

**Android (please complete the following information):**
 - Device: Fire TV Stick Lite
 - OS: Fire OS 7.2.7.3
 - Vysor Bug Report Link:

**Comment by pabloc97** [comment]
I have same problem than you. It works on local on first time, then after share link, it stuck on both sides. hope it fixed asap

**Comment by sfederici** [comment]
To me it keeps working on Vysor locally. But it doesn't from shared link. I found an "alternative" solution, by installing TeamViewer on a local PC -that I can then access remotely- where I installed Vysor. It works, but you need a local device always close to the firestick

**Comment by pabloc97** [comment]
for me i cant do this because i share link with differents person

**Comment by sfederici** [comment]
> for me i cant do this because i share link with differents person

TeamViewer can be used by many people to access the same device. The problem, as I said, is having a local device to control the fire stick where to install TeamViewer that can be accessed by all people that must be able to access the fire stick remotely.

**Comment by cwages46** [comment]
I am having the same issue, however, I am using android USB debugging to connect on my Chromebook. I have been getting very frustrated by this since my phone's screen is broken so I have to rely on Vysor to use my phone, but it started not completing the connection process and just says, as stated above, "Connecting to Vysor on Android. . ."

**Comment by cwages46** [comment]
![Screenshot 2022-04-19 7 31 04 PM](https://user-images.githubusercontent.com/56073200/164117878-6cc55ad8-a3c8-45bf-ae41-08a5e2bd3a04.png)
This is all I see every time and it's annoying.

**Comment by cwages46** [comment]
So it's bugged for USB Device and Shared Device, this needs to be looked into.

**Comment by wavedriver** [comment]
Oh I just wrote a post with the same issue... :( sorry. I have the same problem. Connecting to Vysor on Android. It seems to work on some devices and not on others. The device I have that doesn't work has android 7. Before the update it worked perfectly.

**Comment by koush** [comment]
fire stick is not supported.
also missing the bug report link.

**Comment by sfederici** [comment]
> fire stick is not supported

I have found instructions for the remote control of firestick in a two-years old video. And, at least locally, it works.

> also missing the bug report link.

There is no bug. It simply doesn't work as expected (message "Connecting to Vysor on Android. . ." going on forever)

**Comment by pabloc97** [comment]
> fire stick is not supported. also missing the bug report link.


This is not only with firestick. I dont have it. Its bugged with everything. Every phone and android version(from at least 7 to 12)

**Comment by koush** [comment]
need bug report link

**Comment by cwages46** [comment]
Yeah, I agree, it's affected everything. We all just need to hope and pray that they fix it.

**Comment by koush** [comment]
I believe this was fixed. I am presuming you are/were on the beta channel, as that had a buggy release.

**Comment by sfederici** [comment]
> I believe this was fixed. I am presuming you are/were on the beta channel, as that had a buggy release.

I installed it from [https://www.vysor.io/download/](https://www.vysor.io/download/)

**Comment by cwages46** [comment]
I think I was on the Dev channel, but yes it's been fixed.

**Comment by sfederici** [comment]
> I think I was on the Dev channel, but yes it's been fixed.

So, where should I be able to download the fixed version?

**Comment by cwages46** [comment]
Just go to the Vysor website and download it, it's just a regular fix
update.
