### ISSUE TITLE
No iOS devices are connected

### ISSUE THREAD

**Issue by brou0040** [koush/vysor.io#1063]
I'm using free Vysor from https://www.vysor.io/download/ for windows 10.
I have the VKLSVAN ESP32 that appears to be flashed properly, vysor app says ESP32 Vysor Dongle found.
Using iPad Pro (10.5").  I'd prefer to use my iPad mini 2, but the app doesn't support that model.
I launch vysor on the iPad, connect via lighting to a USB hub connected to another USB hub connected to the PC (I tried connecting the lightning USB directly to PC, but that had no impact).
Open vysor app on windows 10 PC, I cannot get anything other than No iOS devices are connected.
I tried switching to the Beta channel via the advanced tab, but that had no impact.
I can connect and control an android tablet with no issues.
I'd like to be able to control both an android and an iOS tablet simultaneously.

**Comment by koush** [comment]
You may need apple mobile device framework installed. Follow the instructions.

**Comment by gesm1s** [comment]
Having the same issue - trying to connect iphone 13 pro with usb-cable to win10 pc. Have installed Apple mobile device framevork, trusted computer, restarted phone and laptop etc.. Still no reaction and Vysor not detecting the phone. Any ideas? Have connected an android phone and that works just fine.

**Comment by rathahin** [comment]
I have the same issue. I connect iphone 13 mini, however nothing show on the computer.

**Comment by duyunderdog** [comment]
author fucking carre
