### ISSUE TITLE
iOS: save screen recording

### ISSUE THREAD

**Issue by aaronwllms** [koush/vysor.io#1065]
**To Reproduce**
1. Connect to your iOS device
2. Click on the Record Screen button
3. Click the Record Screen again to stop the recording
4. observe that no prompt to save the recording comes up

**Expected behavior**
Expected a prompt to save the recording and select location to save

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 (Monterey)

**iOS (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 14.8
 - Vysor Bug Report Link: (https://gist.github.com/e0e3a66e756f1fbad0a37e363d5b9097)

**iOS Bluetooth Issues (optional):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**
screen shot saving worked one time (wasn't able to get it to work again), but screen record does not prompt to save.

**Comment by koush** [comment]
This is fixed in the beta channel with the prerelease build (available in the releases section of this GitHub repo)

**Comment by LeoJHarris** [comment]
@koush Also noticed same thing. Unable to save videos from mac....
