### ISSUE TITLE
iOS: Screen flickers black and Quality changes

### ISSUE THREAD

**Issue by Caalun** [koush/vysor.io#1067]
Hello. I have the issue that when I specifically use a game (in this example Fate/Grand Order) while the application is open the screen randomly turns black and the quality changes to low and after a few second it does it again and the quality is high.

Changing the Encoder only changes the speed of when this occurs sometimes its slower and high quality for longer on other options it just constantly switches between the 2 qualities.

This happens after upgrading to pro and buying an official Apple USB cable as well. From what I noticed it also only happens in games.

**Comment by koush** [comment]
It might be the the game is taxing the CPU and the video encoding slows down as a result. Not fixable, as this is an apple issue.
