### ISSUE TITLE
Question About Disable The Share Devices Function

### ISSUE THREAD

**Issue by tonychong8** [koush/vysor.io#1069]
Hi Koush, just updated my vysor to latest version which 4.1.77 (pervious was 2.1.0). Noticed that the share devices function is available for free version as well. Due have some reason, I'll try disable or # the share devices function. May i know where is the location to do that? or it's possible? A pologies if this question to disturb your time. Many Thanks.

Tony.

**Comment by koush** [comment]
Simply do not click it.
