### ISSUE TITLE
Unable to install vyzor on Linux

### ISSUE THREAD

**Issue by stefdelec** [koush/vysor.io#1070]
After copy pasting code from your website I got:

Err:1 https://github.com/koush/vysor.io/releases/download/v4.1.77 ./ vysor 4.1.77
  401  Unauthorized [IP: 185.199.109.133 443]

**Comment by rajuaryan21** [comment]
me too

**Comment by MegisMake** [comment]
Getting the same issue. 

`sudo apt install vysor`             
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  vysor
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 65,3 MB of archives.
After this operation, 245 MB of additional disk space will be used.
Err:1 https://github.com/koush/vysor.io/releases/download/v4.1.77 ./ vysor 4.1.77
  401  Unauthorized [IP: 185.199.111.133 443]
E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/40577005/35154b89-1d85-4e66-8dbe-cdbaa5045c16?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=******************************/20220526/us-east-1/s3/aws4_request&X-Amz-Date=20220526T112925Z&X-Amz-Expires=300&X-Amz-Signature=2*********************************************************&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=40577005&response-content-disposition=attachment; filename=Vysor-linux-4.1.77.deb&response-content-type=application/octet-stream  401  Unauthorized [IP: 185.199.111.133 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by tomvdyck** [comment]
Same here ...

**Comment by Anthaullus** [comment]
Same here, unathorized access apparently of some sort... I really dont wont to go to windows to access my Android phone (Android is based on Linux...)
