### ISSUE TITLE
Android: Mirroring Disconnected Error 

### ISSUE THREAD

**Issue by idiscoverch** [koush/vysor.io#1073]
**You must attach a Vysor Bug Report Link**
![Untitled 6](https://user-images.githubusercontent.com/95019403/168263968-f082e21a-15dd-4020-9ad7-9cdfb302bc40.png)

**Desktop (**
 - OS: macOS Monterey 12.3.1
 - MacBook Pro M1 

**Android (please complete the following information):**
 - Device: Infinix X652C
 - OS: Android 10
 - Vysor Bug Report Link: error 500 when creating a bug repair.

constantly gets disconnected, unable to use - suddenly, worked fine before on the same M1 MacBook Pro

**Comment by koush** [comment]
try creating a bug report without the logical and reopening.

**Comment by idiscoverch** [comment]
just uploaded the bug report:
https://gist.github.com/VysorLogs/0f08dbedb0e3f91e52ab2a686370fa87#file-10c2265d-5871-4e96-8486-21c220768eca-txt

**Comment by koush** [comment]
I don't see a disconnect in this log

**Comment by idiscoverch** [comment]
Daemon error Error: stream ended during read for minimum 1 bytes
Mirroring Disconnected Error: stream ended during read for minimum 4 bytes
### PII license 117362486199275832757 croth53@gmail.com
Checking License...

https://gist.github.com/VysorLogs/6b210da5431a23669cc6cd551559c6ca#file-0a18b571-3ed0-4a9a-9725-5290fc4d8fff-txt

**Comment by koush** [comment]
this looks like a faulty usb or adb on the phone. I'd try using adb wifi or another phone. if another phone works fine, it's not a Vysor issue.
