### ISSUE TITLE
Connection Failed for OnePlus Two

### ISSUE THREAD

**Issue by kirpal06391** [koush/vysor.io#108]
The device is shown in the device list but connection fails after initial connecting phase. Also changed from MTP to PTP and rebooted the device but with no respite.

Chrome Version         : 47.0.2526.106 (64-bit)
OS Version                 : OS X El Capitan (10.11.2)
Android Device Model: OnePlus Two
Android OS Version    : 5.1.1
Vysor Version             : 1.0.6.4
Is Android Rooted       : Yes

background_log: http://pastebin.com/G4iX5rS2
screen_log: http://pastebin.com/Ae5yZV5W

**Comment by V3r0x** [comment]
also have something like this in ptp mode:
![image](https://cloud.githubusercontent.com/assets/1812767/12553543/6b511f74-c378-11e5-8d98-710290c324c4.png)

LG G4
Chrome Version : 47.0.2526.111 m
OS Version :  Win10
Android Device Model: LG G4 815
Android OS Version : 6.0
Vysor Version : 1.0.6.4
Is Android Rooted : No

**Comment by kirpal06391** [comment]
Seems in my case there was a issue because of conflict with DNS service, system started working fine after I switched off WiFi (and there was no ethernet through thunderbolt). So I recommend the developer to check how to avoid conflict with DNS.
