### ISSUE TITLE
my windows lags and want to reduce the taskbar size 

### ISSUE THREAD

**Issue by rjl1234** [koush/vysor.io#1081]
![Screenshot (20)](https://user-images.githubusercontent.com/70075805/171079125-be196351-4328-4386-aa82-c66ce7fd96fe.png)

**Expected behavior**
A short description of what you expected to happen.

1)
I have a lag that is slow to the point that it isn't usable
 
2)
i want to ask how the taskbar or toolbar can be sized to my preference 

Desktop 
 - OS: windows 10 

Android
 - Device: s7 tab
 - OS:  Android 12

**Additional context**
another problem

wireless mode is not working

**Comment by koush** [comment]
not possible to resize those
