### ISSUE TITLE
iOS: Short Description of Issue

### ISSUE THREAD

**Issue by YuliyaKhilko** [koush/vysor.io#1088]
it's actually bug on the website, but there is no such a category to post it. 

There is a problem with "Update payment info", I can not do it, server returns 500 error for the request
![image](https://user-images.githubusercontent.com/47117103/174046584-67b49a01-c8a5-4d09-a7ff-00614539c9a7.png)

**Comment by koush** [comment]
will investigate

**Comment by koush** [comment]
fixed
