### ISSUE TITLE
Android: Hangs on "Connecting to Vysor on Android..." screen if initially in Portrait mode.

### ISSUE THREAD

**Issue by rkrmpg** [koush/vysor.io#1093]
**To Reproduce**
1. Connect phone using USB cable while phone is in _**Portrait mode**_ orientation.
2. Open Vysor on computer.
3. Select the "View Device" icon under Android Devices
4. New window opens with "Connecting to Vysor on Android". It hangs on this screen.
5. Rotate phone to landscape mode and then it connects and phone screen is displayed. Rotate back to Portrait and it is still displayed. 

**Expected behavior**
Expected to see and control Android screen in Portrait mode on initial start.

**Screenshots**
![Vysor](https://user-images.githubusercontent.com/17733842/176425880-e59f1aae-f6a9-442c-be7a-719b3c8320c6.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Apple OS 12.5
 - Vysor Version: 4.2.4

**Android (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13 - Beta 3.3 - Build number TPB3.220617.002
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/3dafc28c3d06b3e5f5c100b458bef3e5
 - Logcat: [Logcat.txt](https://github.com/koush/vysor.io/files/9010037/Logcat.txt)

**Additional context**
This had previously worked with Android 13 - Beta 3 when starting in Portrait mode.
No issue using Android running Android 11

**Comment by koush** [comment]
investigating

**Comment by koush** [comment]
fixed

**Comment by granthouston44** [comment]
I'm getting the same issue above, also a pixel 6 running Android 13 with September 2023 security update.
Also MacOS Ventura.
My old Huawei mate 20 pro still works as expected

**Comment by Tushar1805** [comment]
I'm using Realme C1 2019 model number: RMX1811, vysor is connected perfectly gestures are working but the screen stucked on the above screenshot it is unable to view the screen on vysor. Please help me
