### ISSUE TITLE
Android: Vysor stuck at "Connecting to Vysor on Android"

### ISSUE THREAD

**Issue by shenoy008** [koush/vysor.io#1094]
Hello, I have a Pixel 5 device that is running Android 13 Beta 3.3, and I recently discovered that I am unable to view my phone through my Mac laptop. I've already turned on USB debugging and restarted my phone and laptop. I keep getting the following error message:

OS: MacOS Catalina 10.15.7
Device: Pixel 5
Android 13 Beta 3.3
Vysor Version 4.1.77
Vysor Bug Report Link: https://gist.github.com/VysorLogs/dadcf4caa85c90eccb4b466018bc79ab

**Comment by rkrmpg** [comment]
Workaround that i found is to turn to landscape mode and then back to portrait mode. Make sure Auto-rotate is on.
See https://github.com/koush/vysor.io/issues/1093

**Comment by koush** [comment]
fixed

**Comment by shenoy008** [comment]
Thank you for the workaround, @rkrmpg. I hadn't tried it yet. However, many thanks to @koush for fixing it, as the issue is no longer reproducible with the **latest version 4.2.3**. 
Thank you so much, you guys are amazing.

**Comment by dturant** [comment]
Hi @koush. The same problem occurs on Windows. 

OS: Windows 10 Pro
Device: Samsung Galaxy S21 
Android 13 (no issues before updating to 13)
Vysor Version 4.1.77

PS The workaround suggested by rkrmpg works
