### ISSUE TITLE
Website issue, Update payment details not working

### ISSUE THREAD

**Issue by Robyn-P** [koush/vysor.io#1095]
**You must attach a Vysor Bug Report Link**
https://gist.github.com/VysorLogs/12965a7b4d1a53d1794621399419e447 - app log, though I doubt it will help only used the app to access the webpage.

**To Reproduce**
1. Go to 'Vysor Monthly Subscription' - https://billing.clockworkmod.com/subscription/stripe/manage/koushd@gmail.com/vysor.monthly/
2. Click on 'Update Payment Info' *Edit: Right click, there is no link attached to the button as you will see.*
3. See error, as in nothing happens. 

**Expected behavior**
That it would lead to the update payment information page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 19044.1766

Also attempted to do this on a Samsung s22 ultra and galaxy tab s6, it worked on neither leading me to think its an issue with the website, slightly problematic as now i cannot use vysor due to the lack of payment.

**Comment by koush** [comment]
fixed please confirm

**Comment by Robyn-P** [comment]
Fixed
