### ISSUE TITLE
Android: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by wavedriver** [koush/vysor.io#1096]
Hi, after the new update I get this message in vysor web client:

![image](https://user-images.githubusercontent.com/104057528/176611792-15f94341-2fee-4b86-8c27-1b731f121744.png)

 - OS: windows 10. Chrome.
 - Device: Iqoo Z1
 - OS: Android 12

Please fix it.

Thank you.

**Comment by koush** [comment]
need a bug report

**Comment by wavedriver** [comment]
I posted a screenshot with the bug:

_Error Connecting to Android Device TypeError: Object(...) is not a function_

Thank you.

**Comment by koush** [comment]
I need a generated bug report.
