### ISSUE TITLE
Android: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by wavedriver** [koush/vysor.io#1097]
Hi again and sorry

Here is the bug report:

https://gist.github.com/d7e071ba019e9d9b899716e69324d416

And this is the error message i get:

![image](https://user-images.githubusercontent.com/104057528/176619519-4f8ec392-5b0c-43bc-b6e1-87374d849ff7.png)

Issue with vysor web client. I got this error since last update.

PC: windows 10 - Chrome
Device: android 12 - Iqoo Z1

Thank you very much.

**Comment by koush** [comment]
apk is failing to install. try installing this manually. https://github.com/koush/release/tree/master/Vysor/release

**Comment by wavedriver** [comment]
Worked like a charm.

Thank you!!

**Comment by VASH0805** [comment]
I am still facing the issue of the error Android: TypeError: Object(...) is not a function
Device Google Pixel 5- Android
PC- Google Chrome book
