### ISSUE TITLE
Phone Freeze Galaxy S2

### ISSUE THREAD

**Issue by Roshak** [koush/vysor.io#11]
I have a galaxy s2 with the latest cyanogen mod, as soon as the "Vysor is connected" splash screen appears, the phone freezes requiring me to do a hard reboot...

it there anything i can give you as additional information?

**Comment by koush** [comment]
that's a really old phone. only supporting phones that stock kitkat roms.

**Comment by Roshak** [comment]
sad to listen, but thanks for the answer
