### ISSUE TITLE
Waiting for decoder

### ISSUE THREAD

**Issue by SouravBasu** [koush/vysor.io#1102]
Ever since Chrome has been updated to 103.x, my Vysor Pro now shows "Waiting for decoder". I think Google has disabled NaCl and pNaCl in Chrome, so not sure if that affects this.

My setup which used to work before:
a) ADB over WiFi
b) Device is available on Vysor's list of Android Devices.
c) Clicking on a device opens a new window which looks like:
<img width="1000" alt="Screen Shot 2022-07-06 at 11 22 33 PM" src="https://user-images.githubusercontent.com/153128/177705767-bcf035ae-aac7-4f90-86f9-b3a40ed0f47f.png">

**Comment by koush** [comment]
Will check

**Comment by Vall0n** [comment]
Hey @koush, 
I got the same issue with a google pixel 5 with android 12 (since Build-No: SQ3A.220605.009.A1).
Adb connected via usb.

Btw thanks a lot for this great tool!
Best regards,
Josef

**Comment by yasin-ashraf** [comment]
Getting the same error with chrome version 103.0.5060

**Comment by koush** [comment]
I checked on Chrome 103 with Pixel 5 on latest beta, and it works fine.

**Comment by koush** [comment]
Closing this issue because it did not use the issue template and is incomplete.

**Comment by koush** [comment]
Vysor doesn't use pnacl/nacl anymore by default anyways. Use any of the other decoders.

**Comment by Jiks19** [comment]
Resetting the Vysor works for me.

Advanced Option in Vysor --> click on Reset vysor.
