### ISSUE TITLE
Android: Short DescriptioError: No refresh tokenn of Issue

### ISSUE THREAD

**Issue by Hubertusfan** [koush/vysor.io#1103]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Start VYSOR
2. Click on 'Login'
3. SignOn to 'https://app.vysor.io/#/login_firebase?client_id=64148182473-pfjnqf7htsrfdpk7vf9ureugs04s0sio.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fvysor-1026.firebaseapp.com%2F__%2Fauth%2Fhandler&response_type=code&state=%7B%22port%22%3A%2254197%22,%22source%22%3A%22electron%22%7D&access_type=offline&prompt=consent'
4. Copy Code
5. Insert Code on VYSOR in Window "Vysor Sign-In"
6. Error "no refresh token" occurs

**Expected behavior**
Signe in at VYSOR 

**Screenshots**
attached

**Desktop (please complete the following information):**
MS WIN10 21H2

**Android (please complete the following information):**
 - Device: Pisel 4a
 - OS: Android 12
 - Vysor Bug Report Link: attached

**Additional context**
[000003.log](https://github.com/koush/vysor.io/files/9065527/000003.log)

![VYSOR_A](https://user-images.githubusercontent.com/17131336/177818968-9387e418-19c1-460a-af0d-c52cf0f05db6.png)

**Comment by koush** [comment]
there's no code pasted in that screenshot. what you see is just a placeholder. paste the code in.
