### ISSUE TITLE
iOS: Cannot get out of mirror only mode

### ISSUE THREAD

**Issue by justingiffard-impact** [koush/vysor.io#1114]
**To Reproduce**
1. Connect iphone to mac
2. try to calibrate mouse 
3. nothing happens

**Expected behavior**
Should show an iOS cursor so that I can calibrate properly and also should allow me to interact with the UI on the iPhone

**Screenshots**
<img width="454" alt="Screenshot 2022-08-01 at 13 46 26" src="https://user-images.githubusercontent.com/108737155/182149898-353871c4-4527-4930-9f45-c101d0dde487.png">

**Desktop (please complete the following information):**
 - OS:  MacOS 12.5

**iOS (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.4.1
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]
 
 Its not generating a bug report link, I get the red banner saying "Generating the Vysor report, please wait..." it vanishes and then nothing. I thought maybe the link would be in my clipboard but this is whats in my clipboard
 "undefined"

**iOS Bluetooth Issues (optional):**
 - Mac/Computer Model: Macbook Pro 16" 2021
 - Other devices connected with computer via Bluetooth: None
 - Other devices connected with iOS via Bluetooth: None

**Additional context**

Please note I have enabled assistive touch on the iPhone. 
I read about the Vysor Dongle and on your page it says ["The Vysor Dongle can also be used on Mac and Linux for improved bluetooth performance, but it is not required"](https://github.com/koush/vysor.io/wiki/Vysor-Dongle#:~:text=The%20Vysor%20Dongle%20can%20also%20be%20used%20on%20Mac%20and%20Linux%20for%20improved%20bluetooth%20performance%2C%20but%20it%20is%20not%20required.). I am using a Macbook as stated above so shouldn't need the dongle

**Comment by koush** [comment]
everything after Monterey requires a dongle. apple broke/closed off the bluetooth api that allowed it to work before.

**Comment by justingiffard-impact** [comment]
Maybe add that to the docs?

**Comment by emoonadev** [comment]
If buying the dongle, the touching will work?

**Comment by almaz010891** [comment]
Please update app and documantation, I was frustrating whent tried to set up this feature on MacOS 13.2

**Comment by tnortman-jabra** [comment]
Even with an ESP32 dongle, I'm finding it won't work
