### ISSUE TITLE
black screen on netflix video only

### ISSUE THREAD

**Issue by draben33** [koush/vysor.io#1115]
everything mirrors ok except the actual netflix video. Controls, sound, even the little preview window on the scroll bar shows up fine. But the screen is just black. I did everything in the support troubleshooter about black screens and it's good, although the pnacl demos website is saying I need chrome 31, when I have 104. Idk what's up with that, but manually checking everything is fine in chrome.

**Comment by koush** [comment]
that's Netflix DRM preventing screen capture.

**Comment by Mortuous** [comment]
The app doesn't work with Netflix, Star, Prime or other streaming apps, you don't make this clear anywhere before instaling or paying pro.
