### ISSUE TITLE
Vysor software issue , i paid lifetime but the software is not recognizing my license anymore

### ISSUE THREAD

**Issue by beso4u** [koush/vysor.io#1129]
Vysor software issue , i paid lifetime but the software is not recognizing my license anymore

**Comment by koush** [comment]
invalid bug report

**Comment by beso4u** [comment]
ok.. i already reported the case to PayPal to get the refund .. it looks your app is fraud
i paid for a life time license & you are not fixing, or returning my money 
i will keep flowing this issue, until its fixed or my money back

**Comment by koush** [comment]
how am I supposed to respond when you provided no email, name, or credit card info you goofus. those are all contained in the bug report you refused to fill out.
