### ISSUE TITLE
Linux APT Repository 404

### ISSUE THREAD

**Issue by demib72** [koush/vysor.io#1133]
Error: https://nuts.vysor.io/apt ./ Packages
  404  Not Found
Error: https://nuts.vysor.io/apt ./ Translation-en
  404  Not Found
Error: https://nuts.vysor.io/apt ./ Translation-zh_CN
  404  Not Found

I have been getting these errors for awhile. Did you drop development on ubuntu-based systems?

**Comment by koush** [comment]
It should work, I fixed it a few months ago and check it regularly.

**Comment by koush** [comment]
maybe `apt update` or run the apt installer script again from Vysor.io
