### ISSUE TITLE
Vysor : Payment Cancellation Issue

### ISSUE THREAD

**Issue by wannaBeNerd23** [koush/vysor.io#1134]
After canceling the subscription, it is still getting deducted from the bank account, for the past 2 years. Please initiate the refund for the same.

I have messaged you over Twitter as well. And the email address for billing doesn't exist. Please check and initiate the refund.

**Comment by koush** [comment]
email?

**Comment by wannaBeNerd23** [comment]
> email?

Email Tried: billing@vysor.io

**Comment by wannaBeNerd23** [comment]
> > email?
> 
> Email Tried: [billing@vysor.io](mailto:billing@vysor.io)

Closed it by mistake. Reopening it.

**Comment by koush** [comment]
What is your email I mean?

**Comment by wannaBeNerd23** [comment]
Here you go.
Email: lajeet.adhikary123@gmail.com

**Comment by koush** [comment]
lajeet@getmyparking.com

**Comment by wannaBeNerd23** [comment]
Yeah this was my work email address, back then.

**Comment by koush** [comment]
cancelled
