### ISSUE TITLE
Android: french keyboard support

### ISSUE THREAD

**Issue by NHA-GH** [koush/vysor.io#1135]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Use SMS application
2. Type one french character such as : é à è ê etc.

**Expected behavior**
The key pressed should input the right character

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 11.4.10]

**Android (please complete the following information):**
 - Device: Huawei PRA LX1
 - OS: Android 8
 
**Additional context**

**Comment by koush** [comment]
International keyboard is supported. Enable it.
