### ISSUE TITLE
Refund request email address doesn't exist

### ISSUE THREAD

**Issue by huttarl** [koush/vysor.io#1136]
https://support.vysor.io/billing/refund/ says,
"First time purchases are refundable within 24 hours of purchase. Please contact [billing@vysor.io](mailto:billing@vysor.io) from your purchasing email account to request a refund. You must provide the following details: the account email for your purchase or an order/receipt number."

I emailed billing@vysor.io and got this bounce message:
"550 5.1.1 The email account that you tried to reach does not exist.
Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser h15-20020ac8514f000000b0031f0e223061sor10364856qtn.27 - gsmtp"

I tried twice and got the same result. I see from other issues (#1134) that I'm not the first one to tell you about this problem.

You really should fix either the mailbox or the refund request instructions. As it is, you're risking accusations of fraud.

**Comment by koush** [comment]
Fixed the broken email. Card expired yesterday and Google Domains started bouncing. This is a duplicate issue, so closing and following up on the other.

**Comment by huttarl** [comment]
OK. Glad to know this isn't going to be an ongoing issue.
