### ISSUE TITLE
Refund request

### ISSUE THREAD

**Issue by huttarl** [koush/vysor.io#1137]
I bought Vysor Pro in order to get audio mirroring. (Otherwise I could keep using scrcpy.)

I had clicked on the headphone icon at the top of the Vysor Mac App, and it said that audio mirroring was a Vysor Pro feature.

So I purchased the lifetime license. Then I tried audio mirroring, and it didn’t work.
Then I tried technical support on the Vysor web site, and found out it consisted of a choice of three categories, none applicable.

I have read pages and pages of notes here on github issues looking for a solution, and found none that helped.
Several audio-related github issues are closed as “duplicate” with no indication of which issue is considered to be the live one regarding audio mirroring problems.

I could go into full detail and file a bug report, but since your refund policy seems to be limited to the first 24 hours after purchase, and it looks unlikely that the problem will be fixed in 24 hours, I’m requesting a refund now.

According to https://support.vysor.io/billing/refund/
	"First time purchases are refundable within 24 hours of purchase. Please contact [billing@vysor.io](mailto:billing@vysor.io) from your purchasing email account to request a refund. You must provide the following details: the account email for your purchase or an order/receipt number.”

I emailed that address and it bounced with a message that the address did not exist. So I'm putting my refund request here.

I used the following email address for my purchase: lars AT ...
I'll put the rest into the next comment, so that I don't start getting spam at that address.
I did not receive an order/receipt number, but the invoice number is ch_3Lf8EEIX57f4SV6L1Pq24uaL.

**Comment by huttarl** [comment]
The rest of my email address is 100fold DOT org.

**Comment by koush** [comment]
Hi, did you try Android 10 audio mirroring? Is it an android 10 device?

**Comment by huttarl** [comment]
I'm willing to answer questions about what went wrong, in hopes that it will help somebody, but my request for refund still stands.

Yes, I tried with and without Android 10 audio mirroring. It's an Android 11 device, an "onn" tablet model 10026191.

When I click the headphones icon to toggle audio, the device has a popup saying "Start recording or casting with Vysor?" I always press "Start now". Then I switch to an app and play a video with audio. But the audio continues to be played only on the device, and not on my computer.

**Comment by huttarl** [comment]
Here's the bug report template:

**You must attach a Vysor Bug Report Link**
1. First, trigger the bug. 
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost. (OK)
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues. (I clicked the Bug Report button. A dialog appeared. I pressed "Create." A red "Generating ... please wait" dialog appeared. Soon it closed. Now what?)
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app. (If it was supposed to generate a file, there's no indication that it did so. Where do you want me to find the bug report?)


**To Reproduce**
Steps to reproduce the behavior:
1. Start an app on the device, which plays a video with audio
2. Click the headphones icon at the top of the Vysor window to toggle audio
3. The device shows a popup saying "Start recording or casting with Vysor?" Press "Start now".
4. Switch back to app and play a video with audio.

**Expected behavior**
A short description of what you expected to happen.
- The audio continues plays on my computer, not just on the device.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1

**Android (please complete the following information):**
 - Device: onn 100026191
 - OS: Android 11
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging] Tell me where to find such a bug report once it's generated.

**Additional context**
Add any other context about the problem here.

**Comment by huttarl** [comment]
FYI, I tried audio mirroring using two other Android devices.

- One device is a RedMi 9A, running Android 10 QP1A. 190711.020. Vysor has Android 10 Audio Mirroring turned on. The result was the same as above: toggling audio mirroring has no effect. Audio plays only on the phone, not the computer.

- The other device is a Samsung A50 (SM A505U), running Android 11. On this phone, with Vysor's Use Android 10 Audio Mirroring **turned off**, Toggle Audio sends me to the Cast screen, where Vysor Audio Output is available as a device. Selecting this device causes audio mirroring to work!

So I have one device that works with audio mirroring, and two that don't.

**Comment by koush** [comment]
Can you try disabling Android 10 mirroring on the ones that don't work? That will use the legacy audio option.

**Comment by huttarl** [comment]
Yes, as stated above, I tried it without Android 10 audio mirroring on the onn tablet. And it still didn't work.

I also tried it without Android 10 mirroring on the RedMi. In this scenario, when I toggle audio mirroring, it sends me to the Cast screen, on which there is one option: Wireless display. This option has an on/off switch which is off. Tapping the on/off switch or the Wireless Display option have no effect. Audio doesn't mirror to the computer.

**Comment by huttarl** [comment]
OK, I tried again on the onn tablet, with Android 10 audio mirroring turned off. This time, when toggling audio mirroring took me to the cast screen, there was an option for Vysor Audio Output. Selecting this device causes audio mirroring to work!

So now it has worked on 2 out of 3 devices. Though I'm not ready to assume that it will work on the onn when it's time for a conference presentation, since it has usually not worked.

**Comment by huttarl** [comment]
I was able to get mirroring to work successfully on the onn tablet a second time. So I'm beginning to be convinced about that device.

But audio mirroring still doesn't work on the Redmi. I noticed that the phone has its own "Cast" setting, which is currently off. But this seems to be a full app for casting the screen directly to a TV over WiFi -- not a device that Vysor can use. (It also requires that I agree to let my location and other private data be collected -- something I'm not willing to do.)

**Comment by koush** [comment]
The redmi probably doesn't support the official android 10 audio capture OR the chromecast integration that  I use as an unofficial capture method.
The official capture API also requires that an app allows audio capture. https://developer.android.com/guide/topics/media/av-capture#capture_audio_playback

The unofficial chromecast emulation implementation doesn't have that limitation but may not be supported by all phones.

**Comment by huttarl** [comment]
It would be very helpful to know that such limitations (e.g. the app must support audio capture) exist via some Vysor documentation, especially since a user can't test whether Vysor's audio mirroring works in a particular scenario without purchasing a license.

**Comment by huttarl** [comment]
I got audio mirroring working on another device, a Samsung Galaxy A11 running Android 11.

At this point I'm willing to **CANCEL MY REFUND REQUEST**.

I wish Vysor worked more easily, on more devices. But I think I have it working enough to meet my needs, to the point that I'd rather keep the bird that's in the hand, than keep beating the bushes for another solution.

**Comment by huttarl** [comment]
Since I've been listing devices on which audio mirroring did and didn't work, I'll add two more for completeness:

- Didn't work: BLU CSL 2020. Android 8. Android 10 audio mirroring is turned off. When we get to the "Cast" screen, sometimes there are no devices listed ("No nearby devices were found."). Other times, Vysor Audio Output shows up, but when you tap on it, you just get a "Connecting" message, and never succeed in connecting.
- Worked fine: Vankyo S30 tablet. Android 9. Android 10 audio mirroring is turned off.
