### ISSUE TITLE
Removing as administrator in vysor enterprise

### ISSUE THREAD

**Issue by mirrorme66** [koush/vysor.io#1138]
I’m the current administrator of the vysor enterprise account  . I’m wanting to make another user the administrator. I added him but he still cannot login to see the same screen I'm on. Do I need to remove myself before he tries to login?

**Comment by koush** [comment]
If they look in the top bar dropdown, they can change the org they are managing.

**Comment by mirrorme66** [comment]
Hello,

I cannot see any top bar dropdown. In the below screenshot, Vignesh has been added as an administrator but cannot login. Do I Zane need to remove myself before Vignesh logs in?

***@***.***

Zane van Onselen | Telefonica UK Limited
Project Manager/Coordinator | QA and AO2
M +44 (0) 7919659506
***@***.******@***.***>
***@***.***

Next Leave : 08-09 September
                       10-11 October
                        11,14 November

**Comment by mirrorme66** [comment]
Could you send me some screenshots of where the top down drop bar is. Where on the below image is the drop bar

![image](https://user-images.githubusercontent.com/93708842/190122841-95ba9469-14fe-4e6d-b594-8f2b7cb0d6ba.png)

**Comment by koush** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/73924/190191416-6a60e808-0b2c-468d-9c85-ae8288c51147.png">

**Comment by koush** [comment]
This drop-down is only visible to the user that is a secondary admin

**Comment by vigneshmvm** [comment]
Hi, I'm the secondary admin and I can't see any drop down. Please find the screenshot that I see
![image](https://user-images.githubusercontent.com/113617591/190434991-6e6fe347-44ba-4a63-bb95-5d4e7a712e27.png)

**Comment by koush** [comment]
please note that email addresses are case technically case sensitive. in practice, they are not, but by spec they can be. please enter the email exactly as seen in the previous screenshot.

**Comment by koush** [comment]
replace the admin with the all lowercase version in the admin list.

**Comment by vigneshmvm** [comment]
Hi, We have replaced the admin user with all lowercase version and checked. We could still see the same screenshot that I shared first and there is no change. Could you please kindly take a look?
