### ISSUE TITLE
Vysor installation failing

### ISSUE THREAD

**Issue by mildhotsauce** [koush/vysor.io#1144]
New to github, just made an account for help with launching vysor. Recently I took my laptop to friends house to install vysor (i have no wifi) and upon my return home, I attempted to run vysor and it prompts me with “Installation has failed.” “There was an error installing the application. Check the setup log for more info etc etc…” after checking the setup log, and found what i believe is the issue but don’t know how to fix: “The process cannot access the file ‘C:\Users\dayto\AppData\SquirrelTemp\RELEASES’ because it is being used by another process.”

**Comment by koush** [comment]
You might be able to fix this by restarting the computer.

**Comment by mildhotsauce** [comment]
> You might be able to fix this by restarting the computer to release the lock on the file

I had a windows update as well and did that and it also restarted the computer and it fixed. Thank you
