### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by trippme** [koush/vysor.io#1153]
**You must attach a Vysor Bug Report Link**
Nothing comes up when I click on bug report

**To Reproduce**
Setup: Install on PC (working on my Pixel 6) and plug in new phone (Pixel 7 Pro)
1) Plug in phone
2) Let it run it and it runs through the steps and fails to connect at the end (looks like it times out)

**Expected behavior**
Should connect to phone

**Screenshots**
Attached
Video on YouTube: https://youtube.com/shorts/e0HE_DNjENo?feature=share

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19044 Build 19044

**Android (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13 TD1A.220804.009.A2
 - Vysor Bug Report Link: there was none

**Additional context**

**Comment by skalpakoff** [comment]
I just received my pixel7. Same issue i posted right above you. Hope it gets resolved fast.

**Comment by koush** [comment]
Already fixed

**Comment by koush** [comment]
pixel 7 issue was fixed I mean

**Comment by trippme** [comment]
How do I get the update?  I installed everything fresh yesterday.

**Comment by koush** [comment]
click reload

**Comment by trippme** [comment]
Yup that worked!  Thank you for the quick turnaround!
