### ISSUE TITLE
android pixel 7 can't connect to control socket

### ISSUE THREAD

**Issue by skalpakoff** [koush/vysor.io#1154]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
A short description of what you expected to happen. i expected it to mirror, no issues with pixel 2 and pixel 4

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10 pro

**Android (please complete the following information):**
 - Device: [e.g. Pixel 7
 - OS: [e.g. android 13
 - Vysor Bug Report Linkhttps://vysor.io/server#105622484722087153234

**Additional context**
i have als, paralyzed but mind is fine. I use eyegaze to control my surface pro and mirroring my phone is very important to me, please help.

**Comment by michaelstonis** [comment]
I am experiencing the same issue with the Pixel 7. Works great using a Pixel 5 running Android 13. Tried toggling USB debugging on and off to see if maybe was an authorization issue, but that doesn't seem to be the case. I am able to debug apps using the same device on an m1 mac using Android Studio and Visual Studio.

**Comment by chadallen87** [comment]
We got 2 pixel 7 pro's and they both have the same control socket error

**Comment by michaelstonis** [comment]
Switching to the beta/preview channel resolved the issue for me. I believe that there will be a stable release soon with the same fix.

**Comment by koush** [comment]
Released to stable channel a bit ago.
