### ISSUE TITLE
Android: java.lang.exception: Encoder Error

### ISSUE THREAD

**Issue by cipherachintya** [koush/vysor.io#1155]
Hello,

We are using Samsung Galaxy A7 Tablet with Android Version - 10
Vysor Pro Version - 4.2.6

We are logged in with pro account. When we are try to change the **Resolution** to ‘Original’ or when we set **Presets** to ‘Max’ we get ‘java.lang.Exception: Encoder Error’. 

But the error does not appear when I connect my OnePlus phone, so probably the hardware of tablet is not competent to support these settings.

So my question is what is the minimum hardware requirement to use these settings?

Thanks in advance.

**Comment by koush** [comment]
The android encoder may not support that full resolution. There's no hardware requirement on the PC side, this is a limitation of your android.
