### ISSUE TITLE
new version does not recognize phone 

### ISSUE THREAD

**Issue by NHA-GH** [koush/vysor.io#1156]
Hello,
I have seen that Vysor / Mac OSX has been updated to : vysor Pro 4.2.7 runtime 4.2.3
Now Vysor/Mac OSX does not see my Android phone (connected with USB cable) anymore...
Why ?

**Comment by koush** [comment]
Try rebooting maybe? Might just be a hiccup. There were no major changes, the build had been in beta for some time.
