### ISSUE TITLE
Keyboard accents not working.

### ISSUE THREAD

**Issue by VitorLuizC** [koush/vysor.io#116]
I am Brazilian and many words in Portuguese use accents so it is quite difficult to write with the computer keyboard as the Vysor does not interpret accents in some cases it adds spacing and others just do not write the letters.

_My keyboard is ABNT2 format._

**Comment by anawim** [comment]
There is still no support for non-english characters and it's main problem using Vysor for me since the very first release, but saddly @koush hasn't done anything about that yet.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/4
