### ISSUE TITLE
Android: Caanot find the Wireless device

### ISSUE THREAD

**Issue by Felixtesttest** [koush/vysor.io#1161]
**To Reproduce**
1. Login the account from destop
2. Install the Vysor software in mobile
3. Unplug the USB cable 

**Expected behavior**
1. Since I am already in Vysor Pro, it is supposed that I can find the devices even no physical USB plugin when both the destop and mobile device are under same Wifi network.

**Screenshots**
![image](https://user-images.githubusercontent.com/93514712/198946259-fe3631ff-0f53-43fb-a420-a38dbadce9c3.png)
I can only find this device when there is physical USB connection

When unplug the USB , no device can be found
![image](https://user-images.githubusercontent.com/93514712/198946561-aede2656-c307-463f-942f-bc2f46d1c5b0.png)

**Desktop (please complete the following information):**
 - Window 10

**Android (please complete the following information):**
 - Device: Samsung S21 / Google Pixel 3A
 - OS: Android 12

**Comment by koush** [comment]
Correct. Wireless connection must be initiated from a usb connection.

**Comment by JimH44** [comment]
That is a nuisance. A lot of the benefit of paying for WiFi connection is not having to disconnect my phone from the charger and connect it to the computer. Why would I then change to WiFi connection and compete with the other devices connecting to hotspots in our building?
I hope there is a plan to enable WiFi connection without first connecting with a USB cable?
