### ISSUE TITLE
Android: no clear way to make android device connectable wirelessly

### ISSUE THREAD

**Issue by wchristian** [koush/vysor.io#1163]
> **You must attach a Vysor Bug Report Link**

**I can't.** The problem is it's not connecting, so without a device the vysor pc program doesn't make a bug report.

Background: My USB port is physically damaged and has a loose connection, so i try to use it as little as possible.

**To Reproduce**
1. Connect phone to PC via USB and connect successfully via Vysor apps
2. Restart phone and PC
3. Ensure it's connected to wifi, and using the right up
4. Start Vysor app on phone, scroll around in it
5. Start Vysor app on PC, try to connect to phone IP
6. Vysor phone app fails to indicate it is connectable, nor under what ip/port
7. Vysor PC app fails to connect.

**Expected behavior**
Vysor PC app should connect. Vysor phone app should indicate visibly that it is connectable and under what ip/port

**Screenshots**
![image](https://user-images.githubusercontent.com/175467/198985452-fa09271b-8100-40f5-9e54-3335b0165646.png)
![image](https://user-images.githubusercontent.com/175467/198985473-35427693-5319-40d8-9e6b-f23496b54b00.png)
![image](https://user-images.githubusercontent.com/175467/198985509-f6dcf5a5-ffd1-4037-8ca6-63a3c0cda4f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Android (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Vysor Bug Report Link: can't

**Additional context**
Please make more debug info available to the user in both apps. Trying to troubleshoot why the fuck it isn't connecting feels like waggling a fucking dousing rod.

**Comment by koush** [comment]
Wireless connections must be initiated from a usb connection and don't persist through reboot.

**Comment by wchristian** [comment]
That should be documented in the apps then.
