### ISSUE TITLE
Refund requested within 1 hour; no reply. WTF?

### ISSUE THREAD

**Issue by oroboros** [koush/vysor.io#1168]
I've contacted you via https://support.vysor.io/billing/manage/ and by email a couple times and even here: https://github.com/koush/vysor.io/issues/1160

This is totally unprofessional.

**Comment by Renari** [comment]
You realize this program is made by 1 person, this is not a company.

**Comment by oroboros** [comment]
> You realize this program is made by 1 person, this is not a company.

Then perhaps @koush needs to hire people to help. 

This is a business which sells services and products. When he takes the money and doesn't offer the service, this is being unprofessional.

I'm still waiting to receive my refund after one month of requesting it.

**Comment by koush** [comment]
email address?

**Comment by oroboros** [comment]
> email address?

How can I send you my email address without posting it here publicly? I've already written multiple requests via email to billing@clockworkmod.com and billing@vysor.io . What's the email address you want me to write to so I can get this refund? 

Thanks in advance

**Comment by koush** [comment]
Sure, send another email. Maybe it will arrive this time.

**Comment by oroboros** [comment]
I just sent an email to those two addresses. If you still don't receive
it, please let me know an email address to contact you at. Thanks in
advance for letting me know.



--

**Comment by oroboros** [comment]
> cancelled and refunded

I don't seem to see this as being refunded. Could you please doublecheck this and send me proof via email? Thanks in advance.

**Comment by oroboros** [comment]
@koush Please follow up, thanks
