### ISSUE TITLE
Cannot sign in to https://billing.clockworkmod.com/

### ISSUE THREAD

**Issue by duffpod** [koush/vysor.io#1171]
Hello. I can't sign in to [https://billing.clockworkmod.com/](https://billing.clockworkmod.com/) – it keeps running in circles. Sign In with Google (and Sign In with Apple too) leads to Sign In page.

**Comment by koush** [comment]
This seems to be a safari bug in 16.1. Can you try another browser to confirm?

https://github.com/firebase/firebaseui-web/issues/977

**Comment by koush** [comment]
I'll port the workaround if that is the issue.

**Comment by koush** [comment]
should be fixed

**Comment by duffpod** [comment]
@koush it is fixed, thank you!
