### ISSUE TITLE
Can't unsubscribe, what should I do?

### ISSUE THREAD

**Issue by haoxing49** [koush/vysor.io#1173]
Can't unsubscribe from [here](https://support.vysor.io/billing/manage/), what should I do?

**Comment by koush** [comment]
email address?

**Comment by oroboros** [comment]
> email address?

@koush I had requested a refund within less than an hour - this was weeks ago - and even brought this to your attention here: https://github.com/koush/vysor.io/issues/1168

Could you or someone reply please? It's actually quite disappointing since I've been following your work for years.

**Comment by haoxing49** [comment]
已收到，谢谢!

**Comment by oroboros** [comment]
Actually, I'm still waiting for refund and proof of refund for months. I
agree, it would be great to actually close this issue.
