### ISSUE TITLE
Unable to download/Upgrade latest version of vysor

### ISSUE THREAD

**Issue by mujahed121** [koush/vysor.io#1176]
Hi,
I tried upgrading my Vysor app as it is throwing an error while using few Pixel Devices. I tried upgrading the app to the latest one but it is still blocking my installation. Kindly have a look. Currently I am using Linux Debian matchine.

![Screenshot from 2022-11-18 01-14-26](https://user-images.githubusercontent.com/24740876/202666113-935219bb-34ce-4ef6-af45-fe670d64b6dc.png)
![Terminal_screen](https://user-images.githubusercontent.com/24740876/202666122-a1d332e0-53c7-4e18-95ee-9cc8e593d4a9.png)

**Comment by koush** [comment]
Can download the deb manually. Not sure why this isn't working for you.

**Comment by mujahed121** [comment]
Can you please share me the procedure to download and install manually for Linux debian?

**Comment by koush** [comment]
top level readme on this repository.
