### ISSUE TITLE
ADB becomes unresponsive while Vysor is on.

### ISSUE THREAD

**Issue by SebasHollow** [koush/vysor.io#118]
Usually it takes only a few ADB commands before ADB stops responding to any commands, while throwing errors like:
"ADB I/O Error: Connection refused: connect"
This makes vysor unusable for development involved activities.

I think I have been having this problem ever since the introduction of a feature which attempts to reconnect to disconnected devices.

**Comment by koush** [comment]
are you using Vysor's ADB server or the ADB binary? I'd recommend using the ADB binary. Vysor will tell you which is being used in the status window.
