### ISSUE TITLE
Cannot retrieve Lifetime License

### ISSUE THREAD

**Issue by nrvous82** [koush/vysor.io#1186]
I purchased the Lifetime license years old but now it won't retrieve the license.  I can provide my email if needed.

**Comment by dranger003** [comment]
Same issue.

**Comment by koush** [comment]
Are these chrome licenses?

**Comment by nrvous82** [comment]
It was purchased the chrome web store.

**Comment by elgefe** [comment]
Having the same issue and yes, probably a Chrome License, but I can't really remember since it was on May 31, 2020.

**Comment by koush** [comment]
Are these Chrome payments? Those were deprecated by Google. https://developer.chrome.com/docs/webstore/cws-payments-deprecation/

**Comment by elgefe** [comment]
Are you saying we no longer have our licenses instead of migrating us?

**Comment by koush** [comment]
I don't have access to the Chrome payment history anymore, so I have no way of verifying any purchases for migration.

**Comment by HauLuu** [comment]
This is wrong, delegating the responsibility to Google is not a good way to treat your customer. They paid a lifetime Pass not a "Google Liability Pass"

I understand that you can't access the chrome store history but what are you going to do when your user has proof of their purchase? Ignoring them?

**Comment by manulele81** [comment]
same problem for me... Anyone has a solution?
I don't want to pay again to have the same problem in the future with another issue. Lifetime can't be lesser than the life of my computer! ;-)

**Comment by nrvous82** [comment]
https://scrcpy.org/

I've switched to SCRCPY.  I highly recommend it.
