### ISSUE TITLE
Instagram Stories with Vysor

### ISSUE THREAD

**Issue by ChoNenYocho** [koush/vysor.io#1190]
Hi there,

I use vysor to create instagram stories. The matter is that I cannot reduce some objects.

For example, if I resize a photo, then there is no problem.
If I try to shrink a hashtag, gif, sticker, or other object, I can't shrink it below the standard size.

I change the size of objects in this way: with the help of alt I put a dot on the object. Next, I drag the mouse cursor.

Maybe I'm doing something wrong or is there another way to resize objects

I am using Pixel 4.

Thank you!

**Comment by koush** [comment]
Some apps may not support simulated multitouch input.
