### ISSUE TITLE
Android 11 - The connected device screen is green. 

### ISSUE THREAD

**Issue by montanbam** [koush/vysor.io#1192]
**To Reproduce**
Connected the Android device via Ethernet/IP. 
Device is listed in Vysor, select view device.
Device connects and I can select apps etc. by randomly using my mouse in the mirrored window.
Screen is green when the mirrored screen is displayed on the PC. 

**Expected behavior**
Should be able to see a proper mirrored screen of the device., 

**Screenshots**
![image](https://user-images.githubusercontent.com/121570019/209844984-26133712-c27f-4d14-a6e3-cb91397aee2b.png)
![image](https://user-images.githubusercontent.com/121570019/209845349-c4761193-b787-4e46-86d8-d003717a42e3.png)

**Desktop (please complete the following information):**
Windows 10 Home 21H2 / 19044.2364

**Android (please complete the following information):**
 Android 11 - Rockchip 

**Additional context**
I also tries this on an Android 10 device that previously worked and the screen is black.
Vysor Pro Version: 4.2.7 / 4.1.77.
Reinstalled ADB Drivers

I have no idea where the bug report is located after creation within the Vysor application.  (logcat/email selected).

**Comment by koush** [comment]
Decoder error. Lower resolution.

**Comment by haggie333** [comment]
Hello, having the same issue as above. Have tried all the lower resolutions with no success.

This only started happening after I downloaded todays update.

**Comment by koush** [comment]
@haggie333 try setting the codec to the various webcodec or web assembly. Let me know if one of those works.
