### ISSUE TITLE
java.lang.Exception: Encoder Error

### ISSUE THREAD

**Issue by Thisisallnewtome** [koush/vysor.io#1196]
The phone cannot connect when View Device is clicked.  It gives a java.lang.Exception: Encoder Error and stops trying to connect.

**Screenshots**
![Vysor error](https://user-images.githubusercontent.com/93796338/211102930-1f6f3d20-421d-4995-b679-d08379d47c82.PNG)

 - OS: Windows 10

 - Device: OnePlus DE2117
 - OS: Android 12
 - Vysor Bug Report Link: Bug report generated 1/6/23 16:20 EST but I cannot find where to get it

**Additional context**
USB debugging has been activated.  Factory reset of the phone, as well as downloading the Vysor APK direct did nothing to help.

**Comment by koush** [comment]
no bug report link. try a lower resolution maybe.

**Comment by Thisisallnewtome** [comment]
Lower resolution? the phone or the computer?  I cannot log into the phone through Vysor to change any of the viewers settings.

**Comment by koush** [comment]
Vysor settings on pc

**Comment by Thisisallnewtome** [comment]
Thanks, I got it to work by changing the resolution to 75%.
