### ISSUE TITLE
Chrome Lifetime License not recognized

### ISSUE THREAD

**Issue by jackson970711** [koush/vysor.io#1197]
Hi, I have a lifetime Pro license, and it's a Chrome Web Store License, when i click the retrieve chrome license and the link is invalid.  Vysor version (4.2.7)

What should I do?

**Comment by koush** [comment]
chrome payments andgoogle payments (and oob login) were all deprecated by google. I have no historical records of this payments due to them.

**Comment by jackson970711** [comment]
Do you have any redeem code for me to redeem and access the lifetime
license pro version? Here is my proof of purchase since you are unable to
access the record of this payment.
