### ISSUE TITLE
Wireless mouse on OSX host not detected by Vysor-hosted Android device

### ISSUE THREAD

**Issue by bobcov** [koush/vysor.io#1201]
I don't have a bug report.  
 3 Identical Xiaomi Redmi Note 4 phones. 2 with Android 7.0 do not react to any mouse inputs, 1 with Android 12 works as expected and responds to mouse actions. The mouse is a wireless mouse which the Vysor program reacts to normally. I'm looking for a usb mouse to see i that makes a difference, but since the wireless is seen by one of the phones, I don't hold much hope that a non-wireless mouse is the answer.  The host OS is OSX 10.12.6

**Comment by koush** [comment]
Xiaomi phones need to enable adb input. Search the wiki.
