### ISSUE TITLE
Cannot retrieve Lifetime License

### ISSUE THREAD

**Issue by nrvous82** [koush/vysor.io#1203]
I purchased the Vysor Lifetime License through the Chrome Store but I'm no longer able to access the license from the Vysor app.  How can I retrieve a license?

**Comment by koush** [comment]
Chrome store payments are no longer available because Google deprecated them.

**Comment by Stuie** [comment]
That's not what "lifetime" means when it comes to your product though.

**Comment by HauLuu** [comment]
@koush Your answer is not good enough for us. We paid for a Lifetime Pass, please remember that. I know that you now don't have access to Chrome Store history anymore but at least when your customer can provide proof of purchasing, do something to help them out. Refund, or give them redeem code to restore their license. 

@Stuie , @nrvous82 
I was able to hack my way to restore my Pro version but I don't think it will hold up when Vysor is updated to a newer version.
I have 2 MacBooks. The old one is using Vysor Pro and the Web Chrome license was cached. so on old mac:
1. Go to "~/Library/Application Support/vysor"
2. Copy everything in "vysor" folder

Then on the mac that you installed the Vysor app:
1. Go to "~/Library/Application Support/vysor"
2. paste everything into "vysor" folder
4. Reload the Vysor app and your Pro license is restore.

You can transfer the content in "vysor" folder between 2 Macbooks using share folder or Google Drive, anything of your choice.

The process might work on windows. You just need to find the cache of your old Vysor app.
