### ISSUE TITLE
iOS:  Notifications being suppressed.  Only available in Notifications Center

### ISSUE THREAD

**Issue by mfoleyshift** [koush/vysor.io#1206]
I've tried looking through the documentation and the open issues however I'm unable to determine if this is a feature or a bug.  If it's a feature, please point me to the documentation that allows me to NOT suppress notifications on iOS.

**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**_Bug Report Failed:  Request failed with status code 500__**  (See screenshot attached)

**To Reproduce**
1. Invoke Vysor to broadcast
2. Verify screen is streaming in Vysor on Windows desktop
3. Trigger a push notification to the device
4. Notification is suppressed and is only viewable by dragging down the notification center.

**Expected behavior**
Notification drops down from the top of the screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**iOS (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.3
 - Vysor Bug Report Link: Unable to generate Bug Report.  Vysor application presents a error code 500

![image](https://user-images.githubusercontent.com/95516309/214670664-ec002aa7-1ef5-4f7e-bc84-1d021cbfe9b2.png)

**Additional context**

**Comment by koush** [comment]
This is a byproduct of broadcasting the screen, iOS automatically suppresses notifications during the broadcast.
