### ISSUE TITLE
Sound from video plays on iMac speakers even though headphones are plugged in

### ISSUE THREAD

**Issue by bobcov** [koush/vysor.io#1209]
Not sure why, but when I played a video in Telegram, the sound came through the speakers of the iMac instead of the headphones. Clicking "Toggle audio" does not change this unwanted behavior. I also unchecked the audio setting related to not running Android 10.  I removed the headphones and put the volume to 0 and the speakers on mute and still sound plays from the video over the iMac speakers. In this situation, Vysor is overriding the host settings without the host permission. OSX 10.12.6, Android 7.0, Telegram 8.8.4

**Comment by koush** [comment]
does closing/reopening vysor fix it?

**Comment by bobcov** [comment]
No, but not being an idiot and confusing sound from the phone's speaker certainly fixes it.  Please accept my apologies and close/delete this.  I thought I was certain the sound was NOT from the phone's speakers, but I tried it again and put the phone under the table and yeah, there's no issue here.  Very sorry.

**Comment by bobcov** [comment]
Hi,
   I resolved my problem by switching to the international keyboard after finding that solution on github, but before that, I asked Google's Bard why I couldn't paste text containing umlauts.  The reply might be as funny to you as it was to me.
 
 

>  
> The issue you are experiencing with Vysor and German characters with an umlaut is likely due to a bug in Vysor. The Vysor development team is aware of this issue and is working on a fix.
>  
> 
 
Go, Team!
BTW, thanks for a great utility. This is the best.
 
-Bob

> 
>  GMessage ID: ***@***.***>
>
