### ISSUE TITLE
Unlock Pattern not Showing up on PC 

### ISSUE THREAD

**Issue by VA-RedWings** [koush/vysor.io#1214]
**Expected behaviour**
When Vysor is open on the PC and I click the home button on the phone using my mouse, if the screen is locked it would show the unlock pattern.  It just shows a black screen on the PC until I unlock it using the phone.

**Screenshots**

**Desktop (please complete the following information):**

OS: Windows 10 Pro
Version 21H2
Installed on 8/10/2021
OS build 19044.2486
Windows Feature Experience Pack 120.2212.4190.0

**Android (please complete the following information):**

Device: Galaxy S22+
OS: Android 13

**Comment by koush** [comment]
Yes, that screen is "protected" and can't be mirrored after android 12 onwards.

**Comment by VA-RedWings** [comment]
Thanks for the quick feedback.  I guess I'll look for a way to force the screen to stay 'unlocked' when using Vysor.

**Comment by koush** [comment]
There is a keep screen on option while connected, should work

**Comment by VA-RedWings** [comment]
I know there is a keep screen on, dim, or off option.  But after a while the phone will still lock by default.  Is there a different option in Vysor to keep it from locking?

**Comment by koush** [comment]
oh maybe need to add an option, will see if that is possible.

**Comment by JosephReidNZ** [comment]
Hey,

You can still be able to unlock your phone, al you have do is
'mirror/guess' where the unlock code numbers are on the blank screen.

Joseph Reid - Motivational Speaker

**Comment by VA-RedWings** [comment]
> you can still be able to unlock your phone, al you have do is 'mirror/guess' where the unlock code numbers are on the blank screen.

I was doing that but my guessing was just not good enough.  It became a pain in the butt after a while.  In android's developer options you can enable the option to keep the phone unlocked while charging.  I ended up just using a 3rd party app that puts an icon in the notification drop down menu that will toggle an option to keep the screen awake.

**Comment by NoHandsRequired** [comment]
VA

> > you can still be able to unlock your phone, al you have do is 'mirror/guess' where the unlock code numbers are on the blank screen.
> 
> I was doing that but my guessing was just not good enough. It became a pain in the butt after a while. In android's developer options you can enable the option to keep the phone unlocked while charging. I ended up just using a 3rd party app that puts an icon in the notification drop down menu that will toggle an option to keep the screen awake.

Gday VA 
Do you have the app ?   I tried the screen shot thing but I still couldn't get it drives me nuts u have to get a carer to unlock my phone every time I plug it in. once I  get it open I open sudoku app and that doesn't close. Still wish I could unlock it from start I  used to be able to.

Windows 11
S20
Vyser pro V 5.0.46(runtime5.7  )
