### ISSUE TITLE
Black screen on login and several apps

### ISSUE THREAD

**Issue by Brinzer** [koush/vysor.io#1217]
Hello,
I saw another post about the login screen but I wanted to amplify the issue and explain another issue I've found.  I have this same login issue and it happens with several apps too. CashApp, Venmo, and a few dating apps weirdly [Facebook Dating for a while, and now, as of a week ago, Feeld]. I also have a physical disability and a workaround is absolutely paramount! 

My current solution is to use a webcam to see about where I have to click, then guess, but this is a very bad issue that needs a fix immediately! Please!

Thank you!

**Comment by koush** [comment]
Do not open duplicate issues to "amplify" them. https://github.com/koush/vysor.io/issues/1215#issuecomment-1442704362

The issue has been explained in the original bug.
