### ISSUE TITLE
Screen problem on Nexus 6

### ISSUE THREAD

**Issue by huanchunye2015** [koush/vysor.io#122]
The screen is black and white and the icons are scrambled. Attached is a screenshot of Vysor on Nexus 6 with Android 6.0.1.

![vysor_on_nexus_6](https://cloud.githubusercontent.com/assets/14958620/13186353/bd3282ac-d6fa-11e5-8b57-72d989f19329.png)

**Comment by pierrre** [comment]
Enable webgl in Chrome
