### ISSUE TITLE
Android: Camera Plugin for Google Meet

### ISSUE THREAD

**Issue by cliveleehere** [koush/vysor.io#1231]
Does the Camera Plugin work for Google Meet or other VC software? Or does it just work for Zoom?

Some people have mentioned it in the [issue 935](https://github.com/koush/vysor.io/issues/935), but I haven't gotten it to work. 

Thank you for the awesome app. Upgraded to Pro this past week.

**Comment by koush** [comment]
It should, but does not work in Safari on Mac due to security.
