### ISSUE TITLE
WebGL enabled and working, but Vysor fails to detect and use it. 

### ISSUE THREAD

**Issue by bruor** [koush/vysor.io#124]
I have webGL running, and have verified that the chrome webGL experiments load as expected. 
![image](https://cloud.githubusercontent.com/assets/454516/13256705/c76decf8-da19-11e5-8663-94312acee2fd.png)

However,  when I run vysor it looks like this and says webgl is disabled: 
![image](https://cloud.githubusercontent.com/assets/454516/13256741/e83bc02c-da19-11e5-959b-f51fe73f77f1.png)

The card is an Intel HD 4000 graphics with 2GB of ram.

**Comment by bruor** [comment]
Found this in the screen.html console logs.  Other logs are clean when this happens. 
![image](https://cloud.githubusercontent.com/assets/454516/13257423/ac38df44-da1c-11e5-8fb3-782fbb4cceee.png)

**Comment by bruor** [comment]
background page log
![image](https://cloud.githubusercontent.com/assets/454516/13257465/d97a968c-da1c-11e5-8607-f7caca80f074.png)

**Comment by bruor** [comment]
I've just loaded up Kubuntu on the same computer and vysor works using the same hardware.  Here's the chrome://gpu results. 

![image](https://cloud.githubusercontent.com/assets/454516/13331051/af8883b2-dbc9-11e5-9377-3a218ed44305.png)

**Comment by bruor** [comment]
The latest changes surrounding the codec drama and the new subscription option, vysor now works on my intel HD 4000 graphics card under windows.

**Comment by koush** [comment]
oh neat.
