### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by emironat** [koush/vysor.io#1240]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
A short description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 11.4.10]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application erro
[17420b34bd950b0e37e408f2d6e94be2-1ae620fdba6c3c3c2bb27728266c497ca5d3ad6c.zip](https://github.com/koush/vysor.io/files/11305551/17420b34bd950b0e37e408f2d6e94be2-1ae620fdba6c3c3c2bb27728266c497ca5d3ad6c.zip)
rs and logging]

**Additional context**

Whenever I play a movie or some other content my screen fades to black (FireStick 4K MAX on Windows 11)
How do I fix this
I am using the Vysor app
I have the Pro Version 4.3.12

**Comment by koush** [comment]
Those apps are DRM protected and can't be screen recorded.
