### ISSUE TITLE
FireStick remote screen fades to black when view movies or other live media

### ISSUE THREAD

**Issue by emironat** [koush/vysor.io#1241]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
Navigate an play live media or any other movie

**Expected behavior**
See remote video, not a black screen - controls still work.

**Screenshots**
![image](https://user-images.githubusercontent.com/47586270/233879711-21b7c5e3-42cf-4db7-b6bb-9c2c3a103a52.png)

![image](https://user-images.githubusercontent.com/47586270/233879763-975f109a-60e1-406a-a76c-19853dd2a3b5.png)

[ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip](https://github.com/koush/vysor.io/files/11305586/ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip)

**Desktop (please complete the following information):**
Windows 11 10.0.22621 Build 22621

**Android (please complete the following information):**
 - Fire TV Stick 4K Max
 - Fire OS 7.6.3.3
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

[ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip](https://github.com/koush/vysor.io/files/11305588/ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip)

**Additional context**
[ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip](https://github.com/koush/vysor.io/files/11305589/ea1011e6adbc3c3c68e0565ee35f0511-d10057deed0e5251a499b16e47954b8e17604278.zip)

**Comment by koush** [comment]
DRM. Can't record those screens.

**Comment by emironat** [comment]
I use scrcpy-win64-v2.0 and it works ...?
