### ISSUE TITLE
Phone Connected & Confirmed connection but No screen Shared

### ISSUE THREAD

**Issue by thinkingbob** [koush/vysor.io#125]
Using VF695 from TCL used as testing phone for android on MacBook Pro (Retina, 15-inch, Mid 2015).

Chrome Version 49.0.2623.75 (64-bit)

Phone is listed on app and connected to (after USB debugging enabled).

Confirmed on phone for debugging

When connecting through app phone shows.
![screenshot_2016-03-07-16-39-04](https://cloud.githubusercontent.com/assets/5691144/13576459/b60a569c-e485-11e5-8df8-79cbf07b81bc.png)

However on app shows.
![screen shot 2016-03-07 at 16 39 07](https://cloud.githubusercontent.com/assets/5691144/13576470/c0d4c12a-e485-11e5-8f56-4580cff43efd.png)

Then notification
<img width="365" alt="screen shot 2016-03-07 at 16 39 10" src="https://cloud.githubusercontent.com/assets/5691144/13576476/c75c7772-e485-11e5-855c-a86daf31dcc5.png">

**Comment by surendarchellappa** [comment]
having the exact same issue when connecting to mac mini.
