### ISSUE TITLE
Yesterday Vysor updated himself to version 5.0.16 (Runtime 5.0.7) and no longer works

### ISSUE THREAD

**Issue by huck62** [koush/vysor.io#1259]
https://gist.github.com/VysorLogs/e1b273a4007b9e01ae9683bce323097b

Yesterday Vysor updated himself to version 5.0.16 (Runtime 5.0.7) and no longer works.
"Waiting for decoder" appears on the PC screen and remains waiting. You can see on the "Error 404" screen it seems that it cannot connect to the link for decoders. What should I do?

![Immagine 2023-05-20 100549](https://github.com/koush/vysor.io/assets/48919792/134edd73-8068-4e08-964e-025f26f47ccf)

**Comment by koush** [comment]
Please disable any firewalls and vpn and such, and reset vysor form the menu.
