### ISSUE TITLE
Vysor QHD/UHD resolution update.. 

### ISSUE THREAD

**Issue by tandefelt** [koush/vysor.io#126]
Hi,
I have a Sony Xperia Z5 Premium, not rooted, was able to reso switch it regardles to QHD (1440x2560), or, when needed, UHD (2160x3840), for VR/3D purposes.  Regardless, the Vysor screen on Mac OSX does not.. update itself to the related correct higher resolution, stays in 1920x1080 it appears... Not sure if the program can "scale" itself in the macbook screen accordingly in portrait mode so that the entire Xperia Z5 premium screen could be seen (now it has larger parts to the right and bottom, cut out).
Naturally the macbook screen is not sufficient to show vertical 2160x3840, but.. 

1) Q: Is this a possible glitch, or.. a limit of the current version of Vysor, or some other issue..? Easily fixable?.. It would be great to be able to work, as I work with the highest resolution/fastest Macbook Pro Retina Touch, actively, and need to stay in the UHD/QHD mode most of the time.. to be productive.

2) Is some type of scaling/at least showing the entire screen area of the phone, on the macbook, possible (even at lower scaled resolutions)?

Thank you for a GREAT app... a real real lifesaver.. changed my life, after scanning for various other (not good solutions)!!

Best,

Marko, NYC.

**Comment by koush** [comment]
resolution is fixed on vysor at the moment
