### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by wavedriver** [koush/vysor.io#1260]
Hello,
Bug report
https://gist.github.com/VysorLogs/28a9d80bddba87a803cc49b723d4bb23

![image](https://github.com/koush/vysor.io/assets/104057528/a0e426e4-adce-4090-a319-2b999f84af30)

I use browser client (I can't use desktop). Seems that after the new version, i get the error message:
Error connecting to android device TypeError: Object(...) is not a function

Iqoo Z1
Android 12

Thank you.

**Comment by koush** [comment]
APK is failing to install. Try installing manually from here:

https://github.com/koush/vysor.io
