### ISSUE TITLE
Android: Unable to connect to control socket using Android 14

### ISSUE THREAD

**Issue by delcroix-ga** [koush/vysor.io#1263]
**You must attach a Vysor Bug Report Link**

https://gist.github.com/VysorLogs/4806f99bbc43f7c2e00f373abbfc0482

**To Reproduce**
1. Start Vysor and connect to your device

**Expected behavior**
It should connect unfortunately I get Unable to connect to control socket
![Screenshot 2023-05-30 13 44 40](https://github.com/koush/vysor.io/assets/77860080/7e760cd3-cb06-4eb9-a13d-bef3f3618bb5)
![Screenshot 2023-05-30 13 44 10](https://github.com/koush/vysor.io/assets/77860080/43856c8c-d7bd-46e8-94b1-d8ae8eeb736a)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS Version 114.0.5735.84 (Official Build) beta (64-bit)

**Android (please complete the following information):**
 - Device: Any
 - OS: Android 14
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/4806f99bbc43f7c2e00f373abbfc0482
 
**Additional context**

**Comment by koush** [comment]
adb is failing, try restarting the computer or adb server

**Comment by koush** [comment]
you're also seemingly running an old vysor, please update

**Comment by delcroix-ga** [comment]
Same same using beta version https://gist.github.com/VysorLogs/33f83d4bbe0c2406ae6a7cd857e68f5c
And I have ADB access working to the device
