### ISSUE TITLE
Video mirroring hangs after a while and resumes as soon as I click on the PC Vysor window

### ISSUE THREAD

**Issue by mrfrank74** [koush/vysor.io#127]
When I mirror a video played back on the Android phone (HTC One Max) with Vysor, without interacting with Vysor/phone, after a while the mirroring stops and a still image remains on PC screen. If I click on the Vysor window on the PC (windows 7), mirroring resumes straight away.

Other then that the video mirroring is very smooth over USB 3.0.

Any way I can log this within Chrome and share some logs?

**Comment by kacey69** [comment]
I have exactly the same problem on Chrome/Windows 10. After a short while, the mirrored Android screen hangs and only jumps back into life when clicked on. Happy to provide whatever you need to diagnose/fix - just let me know.

**Comment by koush** [comment]
Is the window simply out of focus, or is it in the background, obscured?

**Comment by kacey69** [comment]
In my case neither. I connect my phone via usb; open the app via Chrome; select my phone in the app; confirm the connection on my phone. Once the black screen starts to mirror my phone, I then do everything on my phone/touchscreen - the PC is simply showing/mirroring what I am doing on my phone. After a short while the mirrored screen will 'hang' / stop updating and will stay like this until I use the PC mouse to click somewhere on the mirrored screen. The mirrored image on the PC will then immediately 'jump' to whatever is being displayed on my phone. Hope this helps.

**Comment by mrfrank74** [comment]
Yes...same behaviour for me. It stops after a while even if the window is on focus and I keep moving the mouse over it. Need to click to resume playback once stopped.

**Comment by koush** [comment]
What version of Chrome are you on?

**Comment by mrfrank74** [comment]
ok, it is not happening anymore on latest Chrome and Vysor (free) at least on my new HTC A9:
Chrome 51.0.2704.106 m
Vysor 1.1.1.3
Android SDK ADB binary

**Comment by kacey69** [comment]
I have Version 51.0.2704.106 m of Chrome but I was using Vysor 1.1.1.0.
I see that 1.1.1.4 is now downloaded so I will try again to see if the fault has been fixed for me.
Thanks

**Comment by kacey69** [comment]
I still have the same problem unfortunately. I have used my video camera to record the problem happening. If that would help, please let me know how to send you the file because it is much to big to attach here.

**Comment by kacey69** [comment]
I have had another go at this, whilst video recording the screen from my camera and it seems that, if you leave it long enough (maybe 15-20 seconds) the Vysor screen on my PC will 'catch up' with my phone and it's not always necessary to click on the window to wake it up. Again, I can send you the video file if it would help.

**Comment by koush** [comment]
Youtube the video if you can, that will help

**Comment by kacey69** [comment]
Do you have a gmail account. If so, I could load it to my Google Drive and share it with you.

**Comment by koush** [comment]
should be fixed, purging decoder frames that are too old and requesting a sync frame.

**Comment by blaZofgold** [comment]
I'm experiencing the exact same issue that the OP has stated on the newest build. Is there any way you can look into this? Thanks~

**Comment by MADV360** [comment]
I got exactly the same issue
