### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by Ravn7** [koush/vysor.io#1271]
Everything was fine for a week and then it asked to be allowed to control the device. And again and again. But my devices (a phone and a tablet) get disconnected after a short time (1-3s), they disappear from the Vysor main screen and reappear after a while, but the window with the device screen freezes and can't be used anymore. I can hear the sound of USB device connecting and disconnecting on my computer. Tried resetting and changing many options, installed ADB drivers, but nothing helps. Can you help me with that somehow? 

My log:
https://gist.github.com/VysorLogs/59caa37add0ce5e11b6e99e84659cc14

At the end there's this:
"Uncaught Error
Uncaught Error: Tracker socket close
adb tracker failure"

**Comment by koush** [comment]
Sounds like a faulty usb cable or something wrong with your PC. Try restarting both pc, phone, and swapping cable.

**Comment by Ravn7** [comment]
I tried two different cables.

**Comment by koush** [comment]
You might have a conflicting adb from something else. Not a Vysor issue, something is causing your adb to start/stop.
