### ISSUE TITLE
Android: Socket Error on Android 14 Beta 3.

### ISSUE THREAD

**Issue by optimizatormk8** [koush/vysor.io#1286]
**To Reproduce**
1. Standart connection to device **via wire**

**Expected behavior**
successful session start

**Screenshots**
![image](https://github.com/koush/vysor.io/assets/79090762/8dea7cd8-4825-4b91-8cf2-c3ba353e2820)

**Desktop (please complete the following information):**
 - OS: Win 10 19044

**Android (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14 Beta 3 UP3.230519.008
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/e0b3ea1af015b7a8fe90937ac433d02c

**Comment by koush** [comment]
Fixed in beta channel

**Comment by optimizatormk8** [comment]
Thank you, switched to beta channel
I've accidentally missed the 3 weeks old duplicate issue, sorry
