### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by CarstenVA** [koush/vysor.io#1292]
Hello, i´m Carsten

https://gist.github.com/VysorLogs/01f59d7da8186e7fc3fafdd1c1a862f2

To repoduce the issue:
- connect an android tablet to PC (Windows)
- launch Vysor on PV (View Device)
- tablet is connected
-
![Bild1](https://github.com/koush/vysor.io/assets/138129386/341282d7-be7d-4606-9691-aeb0a1d1acbd)

-press "view device"
-a new window opened
- message: "installing Vysor APK"

PC (Windows 10)
Device: Trimble (android based)
Android version 9

i use a pro version of Vysor

Thanks in advance

**Comment by koush** [comment]
install this manually 

https://app.vysor.io/Vysor-release.apk

**Comment by gittac** [comment]
How do submit my problem or question? I tried on git but have not seen my
question show up.  I encountered a newer Android phone without USB
Debugging.
