### ISSUE TITLE
Android 13 Update Causes Mirroring to Fail (SEEMS TO BE WORKING NOW. DON'T KNOW WHAT CHANGED.)

### ISSUE THREAD

**Issue by kmazziotta** [koush/vysor.io#1293]
Android 13 update causes Vysor to stop connecting.
I cycled the USB Debugging Mode, but it didn't help.
It tries to connect, but fails.
The phone shows up in the list of found phones in Vysor.

**To Reproduce**
1. Connect phone to Windows 10 PC
2. Phone appears in list of phones found.
3. It attempts to connect but gets "Connection Error" after a few seconds
4. Error Message: "Connection Error: Error Connecting to Android Device Error: Unable to connect to control socket."

**Desktop (please complete the following information):**
 - Windows 10 Pro Version 10.0.19045 Build 19045

**Android (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 13 
 - Vysor Bug Report Link:  https://gist.github.com/VysorLogs/2aef216b28416d59844d31554d5a0a73

**Comment by koush** [comment]
Fixed in beta channel. Duplicate issue.
