### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by hIUG** [koush/vysor.io#1302]
https://gist.github.com/VysorLogs/8e65160b5e6aa3c777d596329ccfa250
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Go to main Vysor screen
2. Click on Upgrade to Pro
3. Click on Retrieve License
4. See No License Found with error: "Chrome Web Store license not found: The provided authorization grant (eg., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."

**Expected behavior**
The previously purchased lifetime chrome web store license should be retrieved

**Screenshots**
<img width="1025" alt="image" src="https://github.com/koush/vysor.io/assets/7053310/2829782e-f056-420d-816e-4bb250db4011">
![image](https://github.com/koush/vysor.io/assets/7053310/549676a4-7b1e-443a-b6f4-95443cb02296)

**Desktop (please complete the following information):**
 - OS: MacOS 12.3 (21E230)

**Android (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by JAgostoniCEI** [comment]
Did you ever get this resolved? I have the exact same issue

**Comment by hIUG** [comment]
No, still the same @JAgostoniCEI ... Please help @koush, I haven't been able to use my Pro license in over 6 months

**Comment by Inrego** [comment]
Just wanted to chime in that I have the same issue

**Comment by hIUG** [comment]
I've been having this issue for the past 1 year and seems like there's only one person who can resolve it, so, hoping @koush  at some point helps

**Comment by itsymbal** [comment]
@koush will not help. He will ignore you. You can try emailing him but he will still ignore you koushd@gmail.com
you can switch to https://github.com/Genymobile/scrcpy
or buy a new license then dispute the transaction through your credit card company

**Comment by koush** [comment]
As mentioned in other issues, Chrome apps were removed:
https://support.google.com/chrome/a/thread/162025638/how-long-will-the-chrome-web-store-be-supported?hl=en#:~:text=Chrome%20Web%20Store%20has%20already,hope%20this%20information%20is%20useful.

Chrome web store payments have also been removed:
https://developer.chrome.com/docs/webstore/cws-payments-deprecation

Google has created a situation where its not possible for Chrome app authors to check licenses anymore because they have totally end of lifed both the platform and payment service.
