### ISSUE TITLE
Android: java error after update to latest Vysor version

### ISSUE THREAD

**Issue by jachonko** [koush/vysor.io#1308]
Hi. I have an instrument that uses an older version of Android and Vysor was a great tool to show the display/Gui.

The forced update broke something.

Is it possible to go back to the older working version?

**To Reproduce**
1.Connect to android resource
2. Click on connect

**Expected behavior**
I would expect to see a reproduction of the device display on my computer. Instead, the screen says "connecting" and then throws a red error box along the top title line that says "java,lang.Exception.Encoder error"

During the initial plug in, the Vysor application said "Older APK found. Updating APK" and then the error showed up. 

Individual screenshots do work, so the communications path seems ok.

**Screenshots**

![image](https://github.com/koush/vysor.io/assets/140842386/a75d4310-adce-4819-8a69-b9df795e1ede)

**Desktop (please complete the following information):**
 - OS: Win 10

**Android (please complete the following information):**
 - Device: Lake Shore M81
 - OS: Android 4.1.1
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

[d8563078c1032901f9d6e23dd1ea4f96-a77646012e0aee96086dbc34abd5e4cdf8551dc5.zip](https://github.com/koush/vysor.io/files/12196778/d8563078c1032901f9d6e23dd1ea4f96-a77646012e0aee96086dbc34abd5e4cdf8551dc5.zip)

**Comment by Greg-777** [comment]
Same problem here.

I love(d) using Vysor.

Please address this, or allow us folks with 'older' Androids a chance to re-install the old version of Vysor.

Desktop: Linux Mint
Android: Android 4.4 on Samsung Mini S4

**Comment by guymanley** [comment]
Same issue on Android 4.4.2, HTC Desire 510, Windows 10. Logcat dump: https://gist.github.com/VysorLogs/a32ef2a99228c4bebb7013a27bcb6b77

**Comment by abdulkaderanwar** [comment]
Same issue here. any suggestion or fix would be appreciable

**Comment by koush** [comment]
Might be fixed with the update I pushed just now. Unsure why this would have stopped working.

**Comment by Greg-777** [comment]
Sorry to ask what is (probably) a silly question.  Where is this 'pushed update'?  Google play?  Linux repositories?  A direct download?

**Comment by Greg-777** [comment]
THANK YOU!

Now if I could only get my Delete key to work.  _(Backspace works fine, but my motor memory likes using Delete.)_

**Comment by jachonko** [comment]
Thank you! 
That fixed the issue I was seeing. I just started Vysor on a computer with a live internet connection. It asked to update. I accepted and a few minutes later VIOLA!

Greatly appreciate the effort and fast work.
