### ISSUE TITLE
Cancellation of subscription for inaccessible corporate email.

### ISSUE THREAD

**Issue by en-archx** [koush/vysor.io#1322]
I would like to apologize in advance because this is not a technical issue. I have a long running subscription from my corporate account that I forgot to cancel last 2018 until now. I tried reaching out to you, but I cant find any avenue where I can talk to a human other than here. Please feel free to transfer me to other channel.

**Comment by koush** [comment]
Email?

**Comment by en-archx** [comment]
Hello, sorry for replying late, here is the email novo.dimaporo@fullspeedtechnologies.com

**Comment by koush** [comment]
Done

**Comment by en-archx** [comment]
Thank you, koush!
