### ISSUE TITLE
Access blocked: Vysor’s request is invalid

### ISSUE THREAD

**Issue by mikeparkie** [koush/vysor.io#1323]
Attempting to retrieve my licence after reinstalling, which I've done numerous times previously. 

Google Sign In > Access blocked: Vysor’s request is invalid > Error 400: invalid_request

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

Please advise?

**Comment by koush** [comment]
screenshot?

**Comment by mikeparkie** [comment]
initial sign in looks ok, but it's when I attempt to retrieve my pro licence that I get the error. 

[![20230906-083526-704x862.png](https://i.postimg.cc/mkD1ySfw/20230906-083526-704x862.png)](https://postimg.cc/vgJmQfmg)

[![20230906-083554-704x827.png](https://i.postimg.cc/KzQgTHVj/20230906-083554-704x827.png)](https://postimg.cc/XGGJSQn6)

**Comment by mikeparkie** [comment]
initial signin looks ok, but it's when I attempt to retrieve 

[![20230906-083526-704x862.png](https://i.postimg.cc/mkD1ySfw/20230906-083526-704x862.png)](https://postimg.cc/vgJmQfmg)

[![20230906-083554-704x827.png](https://i.postimg.cc/KzQgTHVj/20230906-083554-704x827.png)](https://postimg.cc/XGGJSQn6)

**Comment by arcao** [comment]
Same issue. I am not able to retrieve my lifetime license.

**Comment by itsymbal** [comment]
thumbs up - same issue here

**Comment by boxer188** [comment]
My pro access is blocked because of failure to retrieve Chrome License

**Comment by bfjeje** [comment]
Hi @koush , could you help me retrieving my license too?
I have the same problem.
![IMG_20230927_112925](https://github.com/koush/vysor.io/assets/4103952/dae4f1d8-e512-42e3-977e-fb51ecb0f021)
![IMG_20230927_112943](https://github.com/koush/vysor.io/assets/4103952/4142a6a2-5a8a-4014-b625-62e52b0e7365)

**Comment by itsymbal** [comment]
@koush Could you fix this issue please? It's been open for a number of months, you've got screenshots and explanations how to fix it. People paid money for the product, (myself included) - we'd like to be able to use it. Thank you

**Comment by natanprog** [comment]
same issue here 😞
![msedge_sPP9eEJQYX](https://github.com/koush/vysor.io/assets/1367981/a0a287b6-90ad-4d06-ac6a-291c114559b1)

**Comment by itsymbal** [comment]
I'm going to create a new monthly subscription, but use a credit card number that expires after 5 days so can't be charged again. We'll see if the monthly continues after the first month. 

If you charge money for a product, you need to let people use the product, or else refund the money. This developer has ignored all requests to fix his broken system, both here and on his Discord.

**Comment by mikeparkie** [comment]
@koush, still broken 😔. Any update plans to fix this?

**Comment by henti** [comment]
I've switched to https://github.com/Genymobile/scrcpy

**Comment by hIUG** [comment]
@itsymbal , did the monthly work? I've been unable to use my pro license for over a year

**Comment by hIUG** [comment]
I've been waiting for a response for a while also https://github.com/koush/vysor.io/issues/1302

**Comment by itsymbal** [comment]
No, it didn't really work. After a while the thing reverted to basic version (although I think I allowed it to update itself which I shouldn't have).
I've switched to scrcpy, as @henti mentioned above
You could also try to purchase a new pro license, then dispute the charge through your credit card company. I think that's a legit reason to have the charge reversed. 
You could try email koushd@gmail.com but he's just going to ignore you. Right, @koush? 

Koush is kind of a jerk if you ask me. He took your money and refused to give you what you paid for.

**Comment by koush** [comment]
> Same issue after clicking on Upgrade to Pro -> at the bottom Retrieve Chrome license -> Sign In.
> 
> Seems Google block OOB OAuth since January 31, 2023: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration
> 
> @koush You have to replace OOB with callback page which receive code and retrieve token, which will shown to user to copy back to Vysor,

the Chrome app authorization only allows callbacks to the OOB uri or to a chrome app uri (which no longer exists). Google has removed authorization with chrome apps. Chrome app authors (apps, which no longer exists) are simply no longer able to validate past purchases any longer.

**Comment by mikeparkie** [comment]
What are you doing about people that have paid money to you @koush, will you be offering a refund or another way of obtaining a valid so we can use the application we've paid for, considering you clearly used a workaround that Google has now removed!?

**Comment by billmote** [comment]
What is the resolution for those of us that have purchased a lifetime license?
