### ISSUE TITLE
Samsung edge screen

### ISSUE THREAD

**Issue by kriskast** [koush/vysor.io#134]
First of all thanks for this amazing piece of software.

I just bought a samsung s6 edge and the screen is split into three partitions I believe (left edge + main screen + right edge).

Vysor only picks up the first 2 and leaves the right edge out (see attached). Nothing important but thought you should know :P

![c1ad1b31b435a72557a26b43e6e64174](https://cloud.githubusercontent.com/assets/12373559/14021765/36ea5244-f1dd-11e5-893d-237da6bdf847.png)

**Comment by koush** [comment]
hahaha gosh... Samsung...

**Comment by koush** [comment]
Is this still present on Chrome 50?

**Comment by kriskast** [comment]
Nope its fixed :) thanks
