### ISSUE TITLE
Stuck on connecting to vysor on android and after ERROR Unable to connect to control socket vysor

### ISSUE THREAD

**Issue by marianpapara** [koush/vysor.io#1364]
Stuck on connecting to vysor on android and after ERROR Unable to connect to control socket vysor

 - OS: Windows 11 

**Android (please complete the following information):**
 - Device: Oneplus 10 PRo
 - OS: Android 14
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/eee02b856e12e00216d9a82acbbd894c

![Erorr 1 - Vysor](https://github.com/koush/vysor.io/assets/143722478/be83093a-7e73-443b-ae26-7d46a7d2ff73)
![Erorr - Vysor](https://github.com/koush/vysor.io/assets/143722478/c1f7e136-5c98-4339-a23a-80e4b4318c09)

Stuck on connecting to vysor on android and after ERROR Unable to connect to control socket vysor

**Comment by spidei** [comment]
Hi! I have the same error on the same device (OnePlus 10 Pro with Android 14) but on MacOS. Vysor Pro version 5.0.46

**Comment by jiritomanek85** [comment]
I have same problem. I think there is problem with android 14.

**Comment by Berenpootje** [comment]
Same issue but on Oneplus 11 Pro with android 14, and pc with windows 10

**Comment by zebrasoftpm** [comment]
Same issue ...
OS: Windows 10
Device: Pixel 6 Pro
OS: **Android 14**, 5 Dec 2023 security update
Vysor Pro version 5.0.46
(It works on my other device Galaxy S9+ on Android 10)

**Comment by Gadg3tTree** [comment]
Same issue:

OS: Windows 10
Device: Samsung Galaxy 23
OS: 14

**Comment by dridihaythem** [comment]
Same issue with Android 14. 
It was working fine with Android 13 ,  the problem emerged after the upgrade.

**Comment by snishimura1** [comment]
Same issue post Android 14.

**Comment by punkuotukas** [comment]
Same issue

OS: macOS Sonoma 14.3
Mobile device: Samsung Galaxy S21 FE 5G
Mobile OS: Android 14

**Comment by ivaylopenevmg** [comment]
Same issue immediately after updating to Android 14 on OnePlus Nord 2T 5G. **For sure Android 14 related**.

**Comment by ricard-v** [comment]
Hello.

I can confirm I have the same issues on both Mac OS 14 and Windows 11 for my following devices:
- OnePlus Pro 10 (Android 14)
- OnePlus Pad (Android 14).

I strongly believe this issue is related to Android 14 as my OnePlus Pad was running with Android 13 and I had no issues with Vysor until I updated the tablet to Android 14.

I tried switching to the beta channel to see if a fix is underwork, but to no avail.

Since I am a pro user that paid for a lifetime pro account, I wish that issue can be fixed asap. Thank you.

**Comment by koush** [comment]
seeing this
> failed to connect control socket: did not receive adb socket client okay: FAIL


Does adb work?

**Comment by ricard-v** [comment]
> seeing this
> 
> > failed to connect control socket: did not receive adb socket client okay: FAIL
> 
> Does adb work?

On my side it does. I can compile and execute apps on both my phone and tablet. However, I tried using the screen recorder from Android Studio and it exited with error code 139. Googling it did not yield concrete results other than SIGSEV... However, screen capture from log cat did work. 
In the meantime, I have switched to scrcpy but it is very sub-par compared to Vysor

**Comment by koush** [comment]
I think the only way I'll be able to fix this is if someone is able to share a vysor server with a one plus attached. I do not have one of their devices on hand. as long as adb works I can use the remote adb connection to diagnose the problem.

even better if you can provide a host/vm with the device attached + ssh access.

**Comment by ricard-v** [comment]
> I think the only way I'll be able to fix this is if someone is able to share a vysor server with a one plus attached. I do not have one of their devices on hand. as long as adb works I can use the remote adb connection to diagnose the problem.
> 
> even better if you can provide a host/vm with the device attached + ssh access.

I am ready to help in any way I can. How should I proceed to do so ?

**Comment by dridihaythem** [comment]
> I think the only way I'll be able to fix this is if someone is able to share a vysor server with a one plus attached. I do not have one of their devices on hand. as long as adb works I can use the remote adb connection to diagnose the problem.
> 
> even better if you can provide a host/vm with the device attached + ssh access.

It's not related to OnePlus only. I have the same issue on Oppo Reno.

It was working fine on Android 13, but after upgrading to Android 14, the problem occurred.

**Comment by koush** [comment]
can you email me at chorale_mantis0x@icloud.com

**Comment by ricard-v** [comment]
> > I think the only way I'll be able to fix this is if someone is able to share a vysor server with a one plus attached. I do not have one of their devices on hand. as long as adb works I can use the remote adb connection to diagnose the problem.
> > even better if you can provide a host/vm with the device attached + ssh access.
> 
> It's not related to OnePlus only. I have the same issue on Oppo Reno.
> 
> It was working fine on Android 13, but after upgrading to Android 14, the problem occurred.

Oppo and OnePlus are pretty much the same company insofar the operating systems are very close, right ?

**Comment by ricard-v** [comment]
> chorale_mantis0x@icloud.com

Thanks. I Have just sent you en email.

**Comment by ricard-v** [comment]
So I tried with the emulator, running Api 34 (Android 14) with the recommended image on Windows, and Vysor had no issues to connect. So, maybe this issue is indeed related to OnePlus / Oppo devices or other similar devices ?

**Comment by koush** [comment]
Fix/workaround published. OnePlus broke Looper.loop from command line. Other stuff may be broken but the core screen mirroring should work now.

**Comment by dridihaythem** [comment]
same, i can confirm it' works now on Android 14 , Oppo Reno

thank you

**Comment by punkuotukas** [comment]
just downloaded the app for macOS - issue remains.

**Comment by Srineesh-tide** [comment]
samsung device running android 14 and the issue is still present

**Comment by Xola11** [comment]
@koush the issue still occurs I am using S22 Ultra

**Comment by andreacona96** [comment]
just downloaded the app for macOS and the issue is still present.
