### ISSUE TITLE
Android: ON RECENT UPDATE - paste functionality from device to MAC broken - worked before the update

### ISSUE THREAD

**Issue by omri-kooply** [koush/vysor.io#1379]
EASY REPRODUCE  - BASIC FUNCTIONALITY BROKEN - LOGCAT ATTACHED AT THE BOTTOM - PLEASE FIX

Preconditions:
Android phone connected to MAC

Steps:
1. While the phone is connected to the vysor, Copy a text from the phone
2. Paste on the PC

Actual result:
No text is pasted

Expected result:
Text copied in phone pasted on MAC

**Desktop (please complete the following information):**
 macOS Monterey
Version 12.0.1

**Android (please complete the following information):**
 - Device: Samsung A127F
 - OS: Android 13 & Android 12 - tested with 2 phones (same model different android version)
 
 INTERNAL LOG CAT:
https://docs.google.com/document/d/1Yel_0aCST-1-pO_fpYZvRYl3UHNj7dxRxekS9WiAAaM/edit?usp=sharing

**Comment by dieskim** [comment]
Same issue here..

**Comment by iamscottweber** [comment]
Same issue as well

**Comment by andy-pi** [comment]
Same for me as well. Is it possible to add an option to disable auto updates? It would be helpful if we could just roll back to a previous version when these kind of bugs crop up. Thanks

**Comment by carlosgdelvalle** [comment]
Same here; shared clipboard stopped working in both directions. Tested in:

- MacOS Sonoma + Android 11
- Windows 11 ARM + Android 11
- Windows 10 x64 + Android 11

**Comment by softvision-raul-bucata** [comment]
Fails when trying to copy/paste from a Vysor connected device, to another Vysor connected device (Android to Android)

**Comment by dieskim** [comment]
Looks like @koush fixed it now. Thanks

**Comment by carlosgdelvalle** [comment]
Yep, it's working over here too. Thanks @koush
