### ISSUE TITLE
Screen size problem

### ISSUE THREAD

**Issue by stefanoromanello** [koush/vysor.io#138]
Hi, i'm using an LG G2 but on Windows I have a problem on the right and bottom border.
The images show how they look (Look at the hour and navigation buttons).

![before](https://cloud.githubusercontent.com/assets/4083715/14215620/5da16b58-f844-11e5-9fb3-aebf3e2569b7.png)
![after](https://cloud.githubusercontent.com/assets/4083715/14215621/60f9b9b8-f844-11e5-87d2-4cbfd8958c74.png)

**Comment by dopt** [comment]
Same thing happen to my Note 3, any solution?

**Comment by RC-3** [comment]
I have the same problem, as do a [dozen](https://plus.google.com/108501175914477466419/posts/hzSVCwbwmdt) other [people](https://plus.google.com/+WilliamWarm/posts/PWDao5zxjwy). I uploaded my diagnostic information to Google+ [as instructed by Koush](https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp).

Please +1 either or both of those threads, and submit your diagnostic information as well!

**Comment by koush** [comment]
are you all on windows? i suspect it is an issue related to Windows adding a border, and this messing with the size calculations

**Comment by RC-3** [comment]
Win10 64bit, yes. Not sure about the others.
Thank you!

**Comment by koush** [comment]
Supposedly this was fixed for others on Chrome 50. Please confirm?

**Comment by dopt** [comment]
It has been fixed for my Note 3 mirroring in WIndows 10, @koush , Thanks a lot.
