### ISSUE TITLE
New Vysor Update has caused the Vysor not to work on my devices.

### ISSUE THREAD

**Issue by umisayz** [koush/vysor.io#1383]
https://github.com/koush/vysor.io/assets/65961837/f908b8dc-3e9b-4f7b-8fc3-4c3f57c7d127

**You must attach a Vysor Bug Report Link**

**To Reproduce**
1. Tap on the update banner and reload cta.
2. Launch the Vysor app again.
3. Tap on the update banner and reload cta again.
4. Tap the play cta.
5. Observe the error. 

**Expected behavior**
The device(s) will be mirrored successfully.
**Screenshots**
I have attached a video clip of the issue.
Macbook with OS Sonomoa 14.1.1

**Comment by mkotyk** [comment]
Experiencing this as well.

**Comment by jasonbmitchell** [comment]
I'm having the exact same issue... it goes through the connection process and ultimately ends in this connection error: 
https://share.zight.com/Jru5DdEq

**Comment by toxict2** [comment]
yep I'm having this exact same problem, I use vysor as an accessibility aid so now I can't use my phone at all (Pixel 5)

**Comment by koush** [comment]
Checking

**Comment by umisayz** [comment]
This is reproducible on iOS as well. On iOS, it gets stuck on "Connecting to Vysor" screen....

**Comment by umisayz** [comment]
<img width="417" alt="OutOfRange" src="https://github.com/koush/vysor.io/assets/65961837/962a74da-7844-48e9-859e-66fa5a64cf29">

**Comment by koush** [comment]
should be fixed

**Comment by umisayz** [comment]
It works on Android now.
