### ISSUE TITLE
Android: Encoder Error

### ISSUE THREAD

**Issue by Manish-7799** [koush/vysor.io#1384]
I am running Vysor Pro Version 5.0.68 (Runtime 5.0.7) in my macOS device and whilst trying to mirror my Pixel 7 device, I keep getting **java.lang.Exception: Encoder Error** (image attached). 

![Screenshot 2024-02-20 at 11 19 18 am](https://github.com/koush/vysor.io/assets/133948269/081eb428-f11e-4fb0-b3bd-1ffd25838ff4)

I have tried to reboot the device and try again, turned off/on developer options. Nothing has worked so far. 

Any help is appreciated.

Thank you

**Comment by koush** [comment]
fixed
