### ISSUE TITLE
Vysor is not behaving correct

### ISSUE THREAD

**Issue by sagarnayak** [koush/vysor.io#142]
i have used this on mac and my windows 10. android device name- micromax aq5001 . the adb comes checked when i start vysor on mac and windows . the device gets detected . but when i connect it then the android device screen becomes smaller and goes to top left corner and start flickering . it becomes 1 4th of original size and flickers. and the mac and windows shows green screen on vysor window. any suggestion on this ?

**Comment by juancalmet** [comment]
what was the solution for this?
