### ISSUE TITLE
nut.vysor.io certificate expired

### ISSUE THREAD

**Issue by mariocarro** [koush/vysor.io#1430]
apt update prints the following error message:

W: Failed to fetch https://nuts.vysor.io/apt/./InRelease  Certificate verification failed: The certificate is NOT trusted. The revocation or OCSP data are old and have been superseded. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 50.219.188.186 443]

The certificate has validity: not after Sat, 13 Jul 2024 17:08:07 GMT

Thank you

**Comment by koush** [comment]
taking a look

**Comment by koush** [comment]
fixed
