### ISSUE TITLE
Starting chromium with no proxy solves my issue (BlackScreen not related to h264)

### ISSUE THREAD

**Issue by esorven** [koush/vysor.io#145]
Hello,
Asus zenfone 2 (ze551ml), stock rom (5.0) without root.
Was having blackscreen on chromium with proxy (enterprise) : 
Started chromium without proxy (for example command line chromium-browser --no-proxy-server) and no more blackscreen for my case.
Vysor working great.
Thanks

**Comment by koush** [comment]
interesting, ok.
