### ISSUE TITLE
Will not reconnect if connected when laptop removed from Dock

### ISSUE THREAD

**Issue by jmattdayton** [koush/vysor.io#146]
I use this on my work laptop and connect via USB to a docking station. I've noticed if i have Vysor running and connected to my phone when i remove my laptop from the dock, i cannot get the phone to reconnect once i re-dock my laptop. It tries to connect but never establishes a connection. The first window shows the phone detected, but connection is never made again. Restarted the phone and still could not reconnect. Restarted the laptop and then connection works again. Possibly something is remaining running in the background when the phone is suddenly disconnected?

Using windows 7 and Android Marshmallow on an HTC M8 One.

**Comment by koush** [comment]
did you try restarting vysor chrome app?
