### ISSUE TITLE
Share device functionality of vysor is not working with latest version of chrome 

### ISSUE THREAD

**Issue by rvchanchlani** [koush/vysor.io#147]
I am not able to share my device using vysor. This feature is working fine in chrome 49 version. But version 50 onward this feature is not working

**Comment by koush** [comment]
This feature is still in beta. The TURN servers I am hosting seem to randomly seg fault and die. When that happens, only local network sharing will work, and requires a manual restart. I need to use a process watcher that restarts these services when that happens, or wait for an upstream TURN fix.

**Comment by rvchanchlani** [comment]
Hi Koushik, Thanks for the reply. When can we expect the next release with this fix.

**Comment by koush** [comment]
should be fixed in 1067

**Comment by koush** [comment]
please confirm

**Comment by rvchanchlani** [comment]
Ya its working fine in 1067. Thanks
