### ISSUE TITLE
[URGENT]Connected in the device, but only shows connecting in the desktop app

### ISSUE THREAD

**Issue by StephanieTania** [koush/vysor.io#148]
hey there, I was wondering if you can help with my case. I used the app this afternoon and it worked perfectly, but now it doesn't at all. my device tells me that it's connected but the desktop view is stuck at connecting. I tried using screenshot from the app and it shows exactly what my phone shows, not what the desktop app shows.
can you please look into this problem fast? I really need it to be running without any sort of problem in less than two days for a final presentation.
my phone is S5, Android 5.0, USB Debugging always on, ADB Driver installed and started, my laptop is acer with 32-bit OS

**Comment by StephanieTania** [comment]
Thank you for NOT helping at all, buddy. You won't even bother to comment what the heck is going on, HUH!?

**Comment by koush** [comment]
Follow the instructions in the app, pal.

https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

**Comment by Naturally-Delicious** [comment]
I am having the same exact problem...
