### ISSUE TITLE
First connection does not show welcome screen

### ISSUE THREAD

**Issue by The-MAZZTer** [koush/vysor.io#15]
When I connected my first PC to my phone, everything worked great but the android app did not launch. When I connected my phone to a SECOND PC and ran the Chrome app, the android app launched and displayed a welcome screen, which I assumed was supposed to happen the first time as well.

There may be some sort of race condition where the app is not yet installed so can't be launched?

**Comment by JasonM77** [comment]
Also noticed this. It showed up when I connected a second time on the same computer.

**Comment by koush** [comment]
strange, thanks for the heads up

**Comment by whisdol** [comment]
Yes, same behavior for me. The welcome screen isn't showing when you "first" connect the device, i.e. when the app is being installed. If the app has already been installed, it works.

**Comment by koush** [comment]
fixed
