### ISSUE TITLE
Idea: Send Device Sound over usb too

### ISSUE THREAD

**Issue by mitch8198** [koush/vysor.io#150]
I have a Windows 10 tablet mounted in my car, Vysor allows me to use the Google Navigation and GPS antenna on my phone and view the directions on the big tablet. What an amazing product, well done. 
Would be great if the sound was sent to the tablet too so the commands come through the car speakers. Touch screen swipe support would be nice too. Thanks Mitchell

**Comment by koush** [comment]
Can't implement this yet, system limitation.
