### ISSUE TITLE
Vysor adb server encounterd an unknown adb command

### ISSUE THREAD

**Issue by UserAndy** [koush/vysor.io#151]
hello, In the Windows 10,Why have a loop tips (Vysor adb server encounterd an unknown adb command.
You may wat to close Vysor and start your adb binary manually),Thanks

**Comment by bestfc** [comment]
I have the same error

**Comment by UserAndy** [comment]
I try reboot Vysor is ok,but I don't know reason

**Comment by wangxujie** [comment]
I have the same error. and,  where can I find the logs. where can i deal with the error

**Comment by koush** [comment]
What command? Can you get me logs please?

**Comment by UserAndy** [comment]
Sorry,I don't know what command,  This is you need logs?  ![error](http://www.andyqian.com/img/android/vysor/githubIssuse.png)

**Comment by koush** [comment]
thanks, this is great.

**Comment by OlorinMedas** [comment]
Before I installed the Universal ADB drivers, that error kept looping. After installing the drivers, that error disappeared. One day Vysor seemed updated (UI changed but it was auto-updated so I'm not sure) and the error looped again. I tried reinstall the drivers but it didn't help. It still used Vysor built-in adb drivers. Finally, I noticed the "Reload Vysor" button and clicked on it, it worked! It seems that something is wrong with Vysor built-in adb drivers and it loads built-in adb drivers as default. BTW, Vysor is a great app! Thanks!

**Comment by koush** [comment]
host:deviceinfos is not a valid adb host command. Not sure what is sending that.

**Comment by xiaocaiyidie** [comment]
i have the same error, what is  wrong?

**Comment by abcdGJJ** [comment]
i have the same error, what is wrong?
