### ISSUE TITLE
vysor chrome app is deleted from the play store

### ISSUE THREAD

**Issue by pandaguojian** [koush/vysor.io#152]
Hi Koush,

Just found out last night that all of the vysor.io link to the chrome extension and the app on the chrome play store are deleted. could you please check?

Thanks,
Jenks Guo

**Comment by LeeXGreen** [comment]
This was intentional, see [this G+ posting](https://plus.google.com/u/0/110558071969009568835/posts/717zTopZSWf) (quoted below)

> Vysor is no longer available - h264 licensing
>
> I voluntarily unpublished the Chrome app just now. Some MPEG-LA folks got in touch with me about licensing the broadway.js decoder (the Android h264 decoder translated to js using emscripten) that is packaged in Vysor to do the real time decoding. $0.20 per download/user or something.
> 
> Will see if I can get this figured out, but no sense running up a massive bill on a free app.﻿

**Comment by pandaguojian** [comment]
Thanks LeeXGreen, I would totally want to pay for the app. It is very useful to me.

**Comment by pjc123** [comment]
Bummer.

**Comment by koush** [comment]
It's back. https://plus.google.com/u/0/110558071969009568835/posts/1J4gUhgw9a4
