### ISSUE TITLE
v1.0.7.1 Video feed lags behind

### ISSUE THREAD

**Issue by KevDoy** [koush/vysor.io#155]
On OS X, when I put the window of a connected device out of focus, and lay another chrome window on top of it, it appears to just pause the feed. My phone screen can be off by the time I bring the window forward again and when I do it will unpause the feed and needs to get caught up with real time - the feed will show the screen still on and it proceeds to show me everything that happened from when I opened something else to the time the screen turned off and I have to wait for everything to play out before I can continue to use Vysor again. Really frustrating as this wasn't an issue before. I will gladly pay for a previous version, but this new version is very buggy.

**Comment by tentypwtk** [comment]
+1. Doesn't keep up with the syncing. Users don't mind paying for a good product but it's not usable at the moment.

**Comment by koush** [comment]
Yeah, I'll fix this. It seems related to the Chrome app suspending and coming back and trying to catch up.

**Comment by KevDoy** [comment]
Cheers.

**Comment by koush** [comment]
Fixed in 1073. If the app is backgrounded, it will start dropping the frames that are not shown, rather than try to replay them when put back into the foreground.
