### ISSUE TITLE
Would be useful if working with smartglasses too

### ISSUE THREAD

**Issue by ilariotruppa** [koush/vysor.io#156]
Hello,

I'm Ilario Truppa, Jr. Software Developer at OC LAB (www.oclab.it/en/). We work on Augmented Reality using smartglasses, and we really apreciate your software and how it works. Unfortunatly we are unable to make it work with the smarglasses. The most interesting smartglasses at the moment are the Vuzix M100 (specs: https://www.vuzix.com/Products/m100-smart-glasses).

Trying to use your software we get this error message: 
_Error installing APK:
pkg: /data/local/tmp/
vysor1463489026475.apk
Failure
[INSTALL_FAILED_OLDER_SDK]_

Could you please solve this issue?

Best regards,

Ilario Truppa

![schermata da 2016-05-17 14-44-01](https://cloud.githubusercontent.com/assets/13014794/15359596/5a025ae4-1d0a-11e6-8cea-bac921f0653d.png)

**Comment by koush** [comment]
Update the Android OS version on your smartglass...

**Comment by ilariotruppa** [comment]
Hello,

unfortunatly this products cannot be update by the customers. Vuzix, in this case, released the M100 with android 4.0.4. It would be great if your software would be able to work with this Android version.

**Comment by koush** [comment]
i'm not a magician. it won't work on that version because the necessary APIs are not there. If i could have made it work on old android versions, I would have.

**Comment by farrukhnajmi** [comment]
@koush Vysor used to work for me on Ubuntu Linux 19.x. Then I updated vysor using instructions here:

https://github.com/koush/vysor.io/issues/242#issuecomment-552096588

and pulling latest bits from git repos.

After this I started seeing the [INSTALL_FAILED_OLDER_SDK] error. My device is running API 18. Can you please tell me which is the latest commit or tag for Vysor supports API 18?
