### ISSUE TITLE
Google Play license purchasing

### ISSUE THREAD

**Issue by KevDoy** [koush/vysor.io#157]
Is there a way you can add a feature to purchase the license on Google Play instead of Google Chrome Web Store? I know it seems a tad backwards, but going back and forth between work and home really throws this off. I'm not able to purchase anything on the web store with my work account.

**Comment by koush** [comment]
Hm, it's unlikely, as all the code and license checking is in the Chrome app...

**Comment by koush** [comment]
I've had one other person request something similar.

I am not sure I can charge for the app on Play Store, as their terms require that any apk distribution through the play store much be charged through play store. They may make me take down the Chrome payment version.

**Comment by KevDoy** [comment]
So it's either - or? Bummer. Any other way you can address this?
Assign a key to all purchases that you can write down/paste into your other email's window? Ideally for you, you'd purchase it twice but like I said, what if someone has multiple accounts for testing or like myself can't buy it. I'm curious to see **IF** there even is a solution

**Comment by dsspence** [comment]
I'd be interested in alternative licensing but I'm sure the chrome store isn't as full featured as the play store.  Also could we have Vysor on the Google Apps Marketplace (work, nonprofit ... ) to support entire domains of users?

**Comment by koush** [comment]
@dsspence I'm not familiar with Google Apps Marketplace? What does that have that the typical Chrome store does not?

**Comment by dsspence** [comment]
I believe it is only accessible if your organization/business uses Google Apps for Work.  I know a lot of universities and other businesses that use this service at least for company wide Gmail, Drive, and other products.  I'm not sure how open it is to 3rd party developers but presumably you could sell to whole groups of developers on a team.

**Comment by koush** [comment]
@dsspence I recently added enterprise billing. Would that work out for you? Can license an entire org that way.

**Comment by KevDoy** [comment]
I feel that this could be closed with the new license purchasing.
