### ISSUE TITLE
Inputs sent but screen remains black - screenrecord works

### ISSUE THREAD

**Issue by AdamGalt** [koush/vysor.io#158]
Reproducible every time.

Connection is established and control inputs all work correctly but no display is fed back to PC, only black screen.

![image](https://cloud.githubusercontent.com/assets/595586/15389669/f5ec8894-1daf-11e6-975d-987fefc4966a.png)

Testing screenrecording, it records fine and the file plays back fine too.

![image](https://cloud.githubusercontent.com/assets/595586/15389657/e62d1996-1daf-11e6-9b12-69781f47203a.png)

Vysor worked on same setup since v. 1.0.6.8 and before.

Happy to provide additional info if required, just let me know.

**Comment by AdamGalt** [comment]
Just tested on some other machines. 

I have the same phone/vysor configuration working on my Linux machines also running the latest version (1.0.7.3 at time of writing).

Seems this must be a Window environment issue.

**Comment by tentypwtk** [comment]
I'm experiencing the same in OSX 10.11.3. Vysor 1.0.7.6 (tried on Chrome and Chromium). Phone is Htc One (A 5.1). It used to work ok (temporarily making the phone to crash and screen go blue) but now every time I connect it it's black screen. Input being sent.

**Comment by AdamGalt** [comment]
Interesting! So not just Windows then. I wonder why Linux isn't affected but OSX is...
I'm running 6.0.1 TW on a Samsung Galaxy Note 3. Not getting crashes like you, but black screen with working inputs is the same.

Can you use screenrecord from terminal on the device or using adb and playback the clip to make sure it is working?

**Comment by tentypwtk** [comment]
Just tested screenrecord from adb shell - video looks fine.

**Comment by AdamGalt** [comment]
Well that's good. Sounds very much like the same issue.
Just tested 1.0.7.6 on Windows box and still same symptoms.
I will test on Linux tonight after work to confirm it is still working with new version too.

**Comment by AdamGalt** [comment]
Still working on Linux  after update to version 1.0.7.6

![koush-vysor](https://cloud.githubusercontent.com/assets/595586/15479289/69de9bec-2117-11e6-8a6a-88a0defdf36e.png)

**Comment by tentypwtk** [comment]
This is strange – Vysor is still showing 1.0.7.6 but this morning it also popped up with a window saying it's been turned off because of more permissions required. Once I allowed it, it now seems to work fine. Will keep you posted.

**Comment by AdamGalt** [comment]
No such luck on my windows box. I've tried removing and reinstalling Vysor, restarting Chrome and even rebooted the system. I'm still seeing the same interactive black screen after it connects.

**Comment by koush** [comment]
Thanks for the report, but this isn't the troubleshooting/support forum. More info would be helpful:
https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

My first guess is that your graphics drivers are not completely up to date, and native client's graphics 3d is crashing.

Check if this site works:
https://gonativeclient.appspot.com/demo/cube

**Comment by AdamGalt** [comment]
Thanks Koush,

Turned out to be that Chrome hardware acceleration was off for some reason.
All sorted now :+1: 

Thank you for the links! 

Closing this issue.

**Comment by nokite** [comment]
Try turning on PTP mode on the device (for transferring pictures).

**Comment by masme** [comment]
Hi guys what ended up working for me was really weird. So, for some reason Vysor only works through one of my laptops USB ports so i recommend thinking of which port it is plugged into

**Comment by koush** [comment]
@masme what laptop?

**Comment by bktowett** [comment]
not working on my macbook air - I am running on Sierra v10.12.3, my chrome is Version 57.0.2987.133 (64-bit). I can take screenshots but the screen display on vysor is black.

**Comment by koush** [comment]
@bktowett are you using an external monitor or anything?

**Comment by bktowett** [comment]
@koush no - just using my normal screen

**Comment by delcasda** [comment]
the chrome hardware acceleration solved my problem, thanks @AdamGalt

**Comment by mrioqueiroz** [comment]
Enabling the Chrome Hardware Acceleration worked for me.
Thank you, @AdamGalt

**Comment by jacklh9** [comment]
The following resolved the issue for me on Linux (debian flavor):
+ Install and use the Vysor app in "Chrome Browser" and NOT in chromium-browser. (Flash plug-in is automatically supported in former and not latter.) 
+ On phone, ensure "PTP mode" for the USB debugging connection type.
+ Ensure cable is a data cable (and not just a power cable). My ASUS tablet's proprietary USB connector was strictly power-only (fail!), but my Google Pixel USB-C was data (huzzah!).
