### ISSUE TITLE
Vysor doesn't load when connected to Fire TV stick

### ISSUE THREAD

**Issue by lsale** [koush/vysor.io#159]
Hi,

I use Vysor to connect to Fire TV all the time but when connected to Stick via USB it can't load the screen and shows an error asking to reboot the device. 
With Fire TV it works all the time
With Fire TV Stick never (I've tried with different devices too)

**Comment by koush** [comment]
will take a look on my fire stick

**Comment by koush** [comment]
Fire TV stick is not supported. Actually, most devices without a camera are not supported, as they often do not have a functional h264 encoder.
