### ISSUE TITLE
Swipe gestures don't seem to work properly

### ISSUE THREAD

**Issue by jmattdayton** [koush/vysor.io#160]
Two Issues
- Screen tends to freeze/lag after a period of time using the desktop interface. Mostly happens if i minimize the phone window on the computer and then bring it back. desktop screen is non-responsive but the commands go through to the phone. After a period of time, screen will start up again and go through all of the actions from the phone that took place during the freeze.
- Scrolling lags and sticks. When panning between android screens, the phone sticks between the two screens. Clicking one more time finishes the scroll over to the next screen. Attempting to scroll immediately results in unsuccessful repetition of the partial scrolling between the first and second screen. Also noticed the same effect with scrolling banners on a website.

Using HTC M8 One, Marshmallow, and Windows 7 PC

**Comment by KevDoy** [comment]
@jmattdayton I believe the first issue was fixed. I was just about to report the second one. It appears @koush has turned off the touch screen extending outside of the window like it used to. I am now unable to unlock the phone with Vysor as I can't swipe up on N or dismiss notifications. Swiping from homescreen to homescreen is difficult, too.

**Comment by koush** [comment]
1) was fixed
2) this is a weird one i've noticed too. i see it on the lock screen a lot. I have an idea what hte issue may be.

**Comment by ibrahima** [comment]
It seems like gestures that go off the screen don't get terminated correctly? Experiencing this a lot with swiping notifications off screen or spinning Pokestops in Pokemon Go lol.

**Comment by koush** [comment]
Yeah, thats what I was thinking too. Will need to investigate further.

**Comment by akent** [comment]
Any update on this one? Still a bit of a dealbreaker issue.

**Comment by inaroom** [comment]
any update on this issue? i bought the license straight away, but can't unlock my devices..mouse swipe doesn't work, sometimes it unlocks with the space bar, but 80% of the time it doesn't...any ideas?

**Comment by KevDoy** [comment]
I personally haven't noticed it lately.

**Comment by KevDoy** [comment]
I haven't noticed this lately, though it is possible that I have just gotten used to it.

**Comment by inaroom** [comment]
So is there some other ways to unlock the device via PC? The space bar almost never work for me..Motorola moto g2 with latest lineageos build and Huawei p9 on stock MM...

On Feb 23, 2017 7:23 PM, KevDoy <notifications@github.com> wrote:

I haven't noticed this lately, though it is possible that I have just gotten used to it.

**Comment by KevDoy** [comment]
I didn't realize the space bar was a feature. Works for me. I usually swipe up though and let go before I go off screen.

**Comment by koush** [comment]
F1 button also reliably unlocks the screen

**Comment by inaroom** [comment]
f1 behaving as the space bar: almost never unlocks. swiping and letting go before going off screen seems to work better than spacebar and f1 for me, but still a big isssue, i have to swipe on the phone almost all the time...also some other small issues like some setting not being saved after 2 or 3 reboot and then star working even if if did disable that option in the meanwhile( i'm thinking about always on top feature)..nice app anyway, keep up the good job! i bought 1 year licence, but i will most likely be buying the lifetime license at the end of the year

**Comment by ekunuke** [comment]
Any update on this issue? Still exists in latest build.

**Comment by bthomas312** [comment]
Any update on this, in the app I test on, it required you to swipe from the right side of the screen to open a menu to get to options, but nothing seems to allow me to swipe from the right side of the screen.

**Comment by mateusfccp** [comment]
This is still happening, why the issue was closed?

**Comment by ScottSusman** [comment]
I'm still encountering this as well.  Can you please reopen the issue?

**Comment by koush** [comment]
> I'm still encountering this as well. Can you please reopen the issue?

please open a separate bug, as this one is dated to version prior to the rewrite of the app.
