### ISSUE TITLE
Cannot buy pro.

### ISSUE THREAD

**Issue by ENunn** [koush/vysor.io#162]
Hey I can't buy pro. When I select my plan the window freezes and I can't click on anything. :/
![bandicam 2016-05-19 18-50-35-9112](https://cloud.githubusercontent.com/assets/19480682/15630586/b01577b8-2507-11e6-94f7-0f01a12b8dd3.jpg)

Any help?

**Comment by koush** [comment]
uhh, what chrome version? are you logged into chrome? once you get to that point that you are at, that's already in Google's payment flow and out of my hands.

**Comment by shusain93** [comment]
I would blur the card image because the last four can be used for identity theft, especially with a cross used username

**Comment by ENunn** [comment]
I got it fixed now. I think I had to wait a bit.

**Comment by koush** [comment]
how did you fix it @enunn?
