### ISSUE TITLE
Device not shown

### ISSUE THREAD

**Issue by bruor** [koush/vysor.io#163]
I have been using vysor with several devices including GSM galaxy Nexus.  However, a CDMA galaxy Nexus running the same build of cyanogenmod won't show up in the device list, even though I can see and work with it over ADB.

Is this a device compatibility issue? 
Is there a list of supported devices somewhere?

**Comment by koush** [comment]
galaxy nexus is probably too old to work. I think i might be filtering out old devices that do not support screenrecord, but i forget.

**Comment by bruor** [comment]
I actually got this working tonight,  the one I was trying to work with was on CM10 (really old).  Once upgraded the device showed in the list and worked really well.

**Comment by koush** [comment]
oh cool
