### ISSUE TITLE
Not able to use the share feature even after purchasing the Vysor Pro

### ISSUE THREAD

**Issue by ushasreek** [koush/vysor.io#164]
Hi,

I have purchased Vysor pro but when i click on share option i'm getting below error even though i logged into Google account.
![image](https://cloud.githubusercontent.com/assets/10368884/15598241/ca8fa4f0-23f5-11e6-9c32-5686e7f98c66.png)

**Comment by ushasreek** [comment]
Hi, 
I've billed successfully for the Vysor Pro version. Still i'm gettting the error.

**Comment by koush** [comment]
Are you online and logged into the Chrome app? What country are you in?

**Comment by ushasreek** [comment]
yes, I'm logged into Chrome app. I'm trying from India.

**Comment by ushasreek** [comment]
I'm completely blocked from last week. Could you please fix it ASAP and also is there an mail account to get in touch with you for quick response.

**Comment by koush** [comment]
You still having an issue? Please go to the trouble shooting page linked in the app and send me the logs there. That will have more info on your billing/subscription status.

**Comment by koush** [comment]
Can you right click that screen and press inspect and send me the logs?

**Comment by mariopce** [comment]
Vysor PRO - When I want share screen with my client - they get notification that they need pay too. 
I would like share ( mirror) my screen with them to show my application. I don't want force them to pay.

**Comment by koush** [comment]
@mariopce You can use single Shares to a client, and they will not need to pay. Share All is not available to clients.
