### ISSUE TITLE
Vysor whitelist Save button is apparently not working

### ISSUE THREAD

**Issue by droca** [koush/vysor.io#165]
Vysor version: 1.7.0.8

I'm trying to use the Vysor Whitelist functionality but apparently the `Save` button is not working, since I click it and no feedback is provided (the windows does not close, I do not see any message or anything).

Also I do not know what to do with that functionality: how should I actually fill this Whitelist? With google accounts?

**Comment by koush** [comment]
Huh, can you get me some logs of the whitelist.html page please? It should save and then close the window.

**Comment by bruor** [comment]
I have the same issue here on version 1.0.8.2.

I opened the developer mode tool for whitelist.html and it shows the following:

whitelist.js:2 Uncaught ReferenceError: getWhitelist is not defined

![capture2](https://cloud.githubusercontent.com/assets/454516/15950556/f1c4301c-2e7d-11e6-917b-62a94e219ec2.PNG)

**Comment by bruor** [comment]
Content of whitelist.js

`$(document).ready(function() {
  getWhitelist(function(whitelist) {
    var text = '// enter one email per line';
    $.each(Object.keys(whitelist), function(index, email) {
      text += '\n' + email;
    })
    
    $('textarea').text(text);
  })
  
  $('#save').click(function(e) {
    var text = $('textarea')[0].value;
    var newList = {};
    var lines = text.split('\n');
    $.each(lines, function(index, line) {
      line = line.trim();
      if (line.startsWith('//') || !line.length)
        return;
      newList[line] = true;
    })
    saveWhitelist(newList, function() {
      chrome.app.window.current().close();
    })
  });
})`

**Comment by bruor** [comment]
Tested this on Windows 10,  10 preview, and Ubuntu Linux.

**Comment by koush** [comment]
Well I'm a doofus, let me double check and fix this. Thanks for the report.

**Comment by koush** [comment]
Fixed in 1.0.8.4

**Comment by bruor** [comment]
on 1.0.8.6 clicking share all devices doesn't even present a whitelist option anymore.   Is the feature to share all device removed for now?

**Comment by koush** [comment]
@bruor can you send me logs of background page?

**Comment by bruor** [comment]
Absolutely,  couldn't see anything out of place at first to send.  But you pointed me in the right direction I think. 
![capture2](https://cloud.githubusercontent.com/assets/454516/16019618/d6ae9b9e-3177-11e6-8472-31ef47c8478e.PNG)

**Comment by koush** [comment]
Rolling out a fix shortly.
