### ISSUE TITLE
Video plugin not loading

### ISSUE THREAD

**Issue by persechini** [koush/vysor.io#167]
I get this loading error when I use Vysor on Windows 10 64bit. The image doesn't load but clicking and typing works. I have another computer with Windows 7 and the same version of Chrome and it works fine

![captura de tela 2016-06-02 09 41 41](https://cloud.githubusercontent.com/assets/12979552/15745173/c29649c4-28a6-11e6-920f-debaf7d733a5.png)

**Comment by koush** [comment]
Go to the troubleshooting page linked in the app, the potential solutions are there. How did you find this issues area anyways? I want to remove all references to it.

**Comment by persechini** [comment]
Hey, thanks, hardware acceleration was turned off for some reason. I found here just googling the issue, actually.
