### ISSUE TITLE
No Device Found.

### ISSUE THREAD

**Issue by omoprodigi** [koush/vysor.io#168]
In Summary, Android Studio recognizes my phone. I use it to debug. Droid@Screen recognizes it too. Works pretty well (in its own sluggish nature). But Vysor doesn't !! .

Is there something else i have to install or fix that these other two do not require ???
![capture](https://cloud.githubusercontent.com/assets/6082331/15801917/b44e5842-2a9b-11e6-86df-e7329d1ff403.PNG)

**Comment by koush** [comment]
It should work. Please send logs and use this support site:

https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp
