### ISSUE TITLE
1.0.8.2 - Random slow downs

### ISSUE THREAD

**Issue by SuperEvenSteven** [koush/vysor.io#169]
**Host OS:** Ubuntu 14.04
**Device Model:** SM-G920I
![settings](https://cloud.githubusercontent.com/assets/460548/15882639/f0314b2c-2d83-11e6-853b-807679378c66.png)

**Symptom:**
Getting random slow downs where the Vysor screen update can take 5+ seconds to update. All input sent to the device is being detected by instantly though.

**I've tried:** 
- restarting my PC and Phone
- reconnecting the USB cable
- tried a different cable
- restarted Vysor

Is anyone else experiencing this issue?

**Comment by koush** [comment]
Does this happen at a lower bitrate?

Is this happening after Vysor comes back from the background?

**Comment by SuperEvenSteven** [comment]
Yes after resuming from background. Yes reducing the setting resolves the speed issue at the cost of screen quality. Normally 2Mb quality streams perfect so it'd be great and I'd love to keep it at that setting. 

PC has 16GB ram and an 8 core Xeon cpu.

**Comment by koush** [comment]
Purging old frames and requesting a sync frame now.
