### ISSUE TITLE
Black screen after enabling render list flag

### ISSUE THREAD

**Issue by LootenPlunder** [koush/vysor.io#17]
Moto X 2013 (xt1053) unrooted, Win10. Was able to find the phone and launch the remote window, but the video lag increased over time to the point that it was about 30 seconds behind, touch remained fine. Read here that I should enable the 'override software rendering list' flag, which I did. After that I would launch the remote window and the spinning wheel would go away quickly, after 1 or 2 seconds, and I'd be left with a black screen with no input or output.

I tried different combinations is the override software rendering list flag and the enable gpu rasterization flag (on a whim) in a different install of canary, all with the same result as above. I also turned the override flag off and rebooted the PC, same result.

**Comment by LootenPlunder** [comment]
Here is my gpu output in case it's needed:

Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Rasterization: Software only. Hardware acceleration disabled
Threaded Rasterization: Enabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
Driver Bug Workarounds
clear_uniforms_before_first_program_use
exit_on_context_lost
scalarize_vec_and_mat_constructor_args
texsubimage2d_faster_than_teximage2d
use_current_program_after_successful_link
Problems Detected
Always call glUseProgram after a successful link to avoid a driver bug: 349137
Applied Workarounds: use_current_program_after_successful_link
Some drivers are unable to reset the D3D device in the GPU process sandbox
Applied Workarounds: exit_on_context_lost
TexSubImage2D() is faster for full uploads on ANGLE
Applied Workarounds: texsubimage2d_faster_than_teximage2d
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
Accelerated rasterization has been disabled, either via about:flags or command line.
Disabled Features: rasterization
Version Information
Data exported	8/25/2015, 10:39:24 AM
Chrome version	Chrome/44.0.2403.157
Operating system	Windows NT 10.0
Software rendering list version	10.8
Driver bug list version	8.19
ANGLE commit id	709dc46cbd06
2D graphics backend	Skia
Command Line Args	Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --enable-tab-audio-muting --try-supported-channel-layouts --flag-switches-end
Driver Information
Initialization time	86
Sandboxed	false
GPU0	VENDOR = 0x10de, DEVICE= 0x0fd1
Optimus	false
AMD switchable	false
Desktop compositing	Aero Glass
Driver vendor	NVIDIA
Driver version	10.18.13.5560
Driver date	8-6-2015
Pixel shader version	5.0
Vertex shader version	5.0
Max. MSAA samples	8
Machine model name	
Machine model version	
GL_VENDOR	Google Inc.
GL_RENDERER	ANGLE (NVIDIA GeForce GT 650M Direct3D11 vs_5_0 ps_5_0)
GL_VERSION	OpenGL ES 2.0 (ANGLE 2.1.709dc46cbd06)
GL_EXTENSIONS	GL_OES_element_index_uint GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_OES_rgb8_rgba8 GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_NV_pixel_buffer_object GL_OES_mapbuffer GL_EXT_map_buffer_range GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_float GL_OES_texture_float_linear GL_EXT_texture_rg GL_EXT_texture_compression_dxt1 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_sRGB GL_ANGLE_depth_texture GL_EXT_texture_storage GL_OES_texture_npot GL_EXT_draw_buffers GL_EXT_texture_filter_anisotropic GL_EXT_occlusion_query_boolean GL_NV_fence GL_EXT_robustness GL_EXT_blend_minmax GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_pack_reverse_row_order GL_OES_standard_derivatives GL_EXT_shader_texture_lod GL_EXT_frag_depth GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source
Disabled Extensions	
Window system binding vendor	Google Inc. (adapter LUID: 00000000000125da)
Window system binding version	1.4 (ANGLE 2.1.709dc46cbd06)
Window system binding extensions	EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_KHR_create_context EGL_EXT_device_query
Direct rendering	Yes
Reset notification strategy	0x8252
GPU process crash count	0
Diagnostics
0
b3DAccelerationEnabled	true
b3DAccelerationExists	true
bAGPEnabled	true
bAGPExistenceValid	true
bAGPExists	true
bCanRenderWindow	true
bDDAccelerationEnabled	true
bDriverBeta	false
bDriverDebug	false
bDriverSigned	false
bDriverSignedValid	false
bNoHardware	false
dwBpp	32
dwDDIVersion	12
dwHeight	1080
dwRefreshRate	60
dwWHQLLevel	0
dwWidth	1920
iAdapter	0
lDriverSize	15627520
lMiniVddSize	0
szAGPStatusEnglish	Enabled
szAGPStatusLocalized	Enabled
szChipType	GeForce GT 650M
szD3DStatusEnglish	Enabled
szD3DStatusLocalized	Enabled
szDACType	Integrated RAMDAC
szDDIVersionEnglish	12
szDDIVersionLocalized	12
szDDStatusEnglish	Enabled
szDDStatusLocalized	Enabled
szDXVAHDEnglish	Supported
szDXVAModes	ModeMPEG2_A ModeMPEG2_C ModeVC1_C ModeWMV9_C
szDescription	NVIDIA GeForce GT 650M
szDeviceId	0x0FD1
szDeviceIdentifier	{D7B71E3E-4C91-11CF-A261-7F191CC2C735}
szDeviceName	\\.\DISPLAY1
szDisplayMemoryEnglish	4095 MB
szDisplayMemoryLocalized	4095 MB
szDisplayModeEnglish	1920 x 1080 (32 bit) (60Hz)
szDisplayModeLocalized	1920 x 1080 (32 bit) (60Hz)
szDriverAssemblyVersion	10.18.13.5560
szDriverAttributes	Final Retail
szDriverDateEnglish	8/7/2015 05:07:03
szDriverDateLocalized	8/7/2015 5:07:03 AM
szDriverLanguageEnglish	English
szDriverLanguageLocalized	English
szDriverModelEnglish	WDDM 2.0
szDriverModelLocalized	WDDM 2.0
szDriverName	nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
szDriverNodeStrongName	oem35.inf:0f066de3d6a0b0c5:Section027:10.18.13.5560:pci\ven_10de&dev_0fd1&subsys_397217aa
szDriverSignDate	
szDriverVersion	10.18.0013.5560
szKeyDeviceID	Enum\PCI\VEN_10DE&DEV_0FD1&SUBSYS_397217AA&REV_A1
szKeyDeviceKey	\Registry\Machine\System\CurrentControlSet\Control\Video\{D901E9C8-6438-4BDE-AEA6-5655F15308B1}\0000
szManufacturer	NVIDIA
szMiniVdd	n/a
szMiniVddDateEnglish	n/a
szMiniVddDateLocalized	n/a
szMonitorMaxRes	
szMonitorName	AOC D2369
szNotesEnglish	No problems found.
szNotesLocalized	No problems found.
szOverlayEnglish	Supported
szRankOfInstalledDriver	00D10001
szRegHelpText	
szRevision	
szRevisionId	0x00A1
szSubSysId	0x397217AA
szTestResultD3D7English	Not run
szTestResultD3D7Localized	Not run
szTestResultD3D8English	Not run
szTestResultD3D8Localized	Not run
szTestResultD3D9English	Not run
szTestResultD3D9Localized	Not run
szTestResultDDEnglish	Not run
szTestResultDDLocalized	Not run
szVdd	n/a
szVendorId	0x10DE
1
b3DAccelerationEnabled	true
b3DAccelerationExists	true
bAGPEnabled	true
bAGPExistenceValid	true
bAGPExists	true
bCanRenderWindow	true
bDDAccelerationEnabled	true
bDriverBeta	false
bDriverDebug	false
bDriverSigned	false
bDriverSignedValid	false
bNoHardware	false
dwBpp	32
dwDDIVersion	12
dwHeight	1080
dwRefreshRate	60
dwWHQLLevel	0
dwWidth	1920
iAdapter	1
lDriverSize	15627520
lMiniVddSize	0
szAGPStatusEnglish	Enabled
szAGPStatusLocalized	Enabled
szChipType	GeForce GT 650M
szD3DStatusEnglish	Enabled
szD3DStatusLocalized	Enabled
szDACType	Integrated RAMDAC
szDDIVersionEnglish	12
szDDIVersionLocalized	12
szDDStatusEnglish	Enabled
szDDStatusLocalized	Enabled
szDXVAHDEnglish	Supported
szDXVAModes	ModeMPEG2_A ModeMPEG2_C ModeVC1_C ModeWMV9_C
szDescription	NVIDIA GeForce GT 650M
szDeviceId	0x0FD1
szDeviceIdentifier	{D7B71E3E-4C91-11CF-A261-7F191CC2C735}
szDeviceName	\\.\DISPLAY2
szDisplayMemoryEnglish	4095 MB
szDisplayMemoryLocalized	4095 MB
szDisplayModeEnglish	1920 x 1080 (32 bit) (60Hz)
szDisplayModeLocalized	1920 x 1080 (32 bit) (60Hz)
szDriverAssemblyVersion	10.18.13.5560
szDriverAttributes	Final Retail
szDriverDateEnglish	8/7/2015 05:07:03
szDriverDateLocalized	8/7/2015 5:07:03 AM
szDriverLanguageEnglish	English
szDriverLanguageLocalized	English
szDriverModelEnglish	WDDM 2.0
szDriverModelLocalized	WDDM 2.0
szDriverName	nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
szDriverNodeStrongName	oem35.inf:0f066de3d6a0b0c5:Section027:10.18.13.5560:pci\ven_10de&dev_0fd1&subsys_397217aa
szDriverSignDate	
szDriverVersion	10.18.0013.5560
szKeyDeviceID	Enum\PCI\VEN_10DE&DEV_0FD1&SUBSYS_397217AA&REV_A1
szKeyDeviceKey	\Registry\Machine\System\CurrentControlSet\Control\Video\{D901E9C8-6438-4BDE-AEA6-5655F15308B1}\0001
szManufacturer	NVIDIA
szMiniVdd	n/a
szMiniVddDateEnglish	n/a
szMiniVddDateLocalized	n/a
szMonitorMaxRes	
szMonitorName	AOC D2369
szNotesEnglish	No problems found.
szNotesLocalized	No problems found.
szOverlayEnglish	Supported
szRankOfInstalledDriver	00D10001
szRegHelpText	
szRevision	
szRevisionId	0x00A1
szSubSysId	0x397217AA
szTestResultD3D7English	Not run
szTestResultD3D7Localized	Not run
szTestResultD3D8English	Not run
szTestResultD3D8Localized	Not run
szTestResultD3D9English	Not run
szTestResultD3D9Localized	Not run
szTestResultDDEnglish	Not run
szTestResultDDLocalized	Not run
szVdd	n/a
szVendorId	0x10DE
Log Messages
GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.

**Comment by LootenPlunder** [comment]
Can't really reproduce the fix (something with installing android SDK to get ADB, since universal driver didn't work, restarting all the components and connecting with adb via command line) but the black screen problem is done so I'm going to close. I still have awful draw lag (click is instant, and webgl is enabled). Will make a separate issue, happy to host a remote session.

**Comment by koush** [comment]
tag me in a post on Google+ and i can intiiate a hangout session to debug further
