### ISSUE TITLE
Vysor adb server encountered an unknown adbcommand

### ISSUE THREAD

**Issue by wangxujie** [koush/vysor.io#170]
I hava an unknown error on vysor. My OS is win10.  The vysor can show the device list. the connecting screen is looping always. help me .please!  thks

**Comment by koush** [comment]
Need logs.

**Comment by wangxujie** [comment]
Excuse me. Where  can I find the logs. I just find the notify dialog looping always. (vysor adb server encounterd an unknown adb command.
You may wat to close Vysor and start your adb binary manuall)

**Comment by koush** [comment]
https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp

**Comment by wangxujie** [comment]
thks. I will check all matters soon.

**Comment by wangxujie** [comment]
oh, My gosh .i update 2 the lastest version. connect success. but comes black screen. i will fix the issue by myself.  thks  again.
