### ISSUE TITLE
Black Screen On PC App: Device Found and Can Start Apps With Mouse.

### ISSUE THREAD

**Issue by badhorky** [koush/vysor.io#171]
<H3>Versions</H3>
* <B>Vysor</B>: Version 1.0.8.2 (<I>Free version</I>).
* <B>Device</B>: Motorola Moto G 1st gen, XT1032.
* <B>Android</B>: 5.1.
* <B>PC</B>: Win 7.
* <B>Chrome</B>: 51.0.2704.84 (Official Build) m (32-bit).

<H3>Settings</H3>
* <B>Start automatically</B>: no.
* <B>Image Quality</B>: 500Kbps (fast, low quality).
* <B>Share all devices</B>: no.

<H3>Observed Behaviour</H3>
1. Find device with Vysor app.
* Connect to it.
* Device window pops up.
* Window black.
* Clicking with mouse starts apps etc.
* "Input Panel": pressing buttons at bottom works, but screen still black (but activity as expected on phone).

Vysor worked fine in this setup before the latest surge of changes.

**Comment by koush** [comment]
Head here please, i'll need logs.

https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp

**Comment by mjmuheirwe** [comment]
I am having this issue as well. Some Activities cant be shown. It shows on the phone but not on the computer view screen for vysor

**Comment by jackyli-work** [comment]
the test web site mentioned by the link [https://support.vysor.io/support/technical/black/](url) is also malfunction.
is it related to this problem as well?

**Comment by jackyli-work** [comment]
It turns out that the app on chrome is already obsolete.
sorry for the fuss.
<img width="344" alt="screenshot" src="https://user-images.githubusercontent.com/54344547/83706793-fcf61d80-a64a-11ea-9707-90192d577a30.PNG">
This issue should be resolved once using desktop version
@mjmuheirwe FYI. If you are still experiencing this issue.
