### ISSUE TITLE
Unable to use landscape mode

### ISSUE THREAD

**Issue by gridchin** [koush/vysor.io#172]
I'm getting squashed and rotated portrait (vertical) preview on landscape (horizontal) mode when using Camera app.

**Comment by koush** [comment]
Which phone and android version

**Comment by gridchin** [comment]
Phone: Nexus 6 with Android 6.0.1
Desktop: Mac OS Yosemite 10.10.5

**Comment by jasonleung2020** [comment]
I've got the same problem on both of my two PCs
Phone: LG V10 (Android 6.0)
Desktop: Windows 7 & 10

**Comment by koush** [comment]
@gridchin ok, I'll take a look on my Nexus 6 and Mac. Did not see this issue myself last I checked.

**Comment by mykolaj** [comment]
I'm having the same issue.
Desktop: Windows 10
Tablet: ALCATEL P330X One Touch POP 7S
Android version: 4.3
![p330x](https://cloud.githubusercontent.com/assets/4711153/17659510/b211c780-62db-11e6-9b08-7128278651c9.jpg)

**Comment by mykolaj** [comment]
It's can be fixed the tablet is rotated to its natural screen orientation which is the landscape for this particular tablet.

**Comment by gridchin** [comment]
@koush can you please give as an ETA of this this issue's fix?

**Comment by koush** [comment]
I didn't see this issue on any device I own.

**Comment by dharmendra794** [comment]
vysor change my Device(Device Name: Moto G4 Plus, Version: 7.0) orientation from vertical to Horizontal now i am not able do it again in portrait mode.

**Comment by guruitengineer** [comment]
Hi, I'm also having same issue with camera app. Could you please check?

**Comment by luissantiagodev** [comment]
Did this issue got fixed? I'm presenting the same issue

**Comment by weboost-fr** [comment]
Same problem here, it's preventing me from buying it (I need landscape mode for video mirroring)

**Comment by RadoDeMan** [comment]
Me too, using windows 10 and Xiaomi pocophone
![image](https://github.com/koush/vysor.io/assets/157962056/95e96759-e0af-4adc-affb-3dbe361ebada)
So dumb
