### ISSUE TITLE
How can I purchase?

### ISSUE THREAD

**Issue by matheusborgest** [koush/vysor.io#173]
Every time that I click in purchase the Vysor Pro, the message appears: " Chrome Web Store Unavable.
I was loging in the gogole chrome, but the issue persist. 
![capturar1](https://cloud.githubusercontent.com/assets/19862352/15976100/2d34e50c-2f27-11e6-81af-b0f6aa0a0084.PNG)

**Comment by koush** [comment]
please right click that window to inspect and send me the logs

**Comment by matheusborgest** [comment]
I 'm clicking but don't show the option "inspect".

**Comment by koush** [comment]
Open chrome://extensions/ in your Chrome browser.
Enable developer mode.
Disable and enable Vysor to force the app to reload
Then use Vysor so it breaks, then grab the Chrome logs as follows:
From the extension list, inspect Vysor's purchase.html and grab the console logs.

**Comment by matheusborgest** [comment]
This logs that you need?
![captura2](https://cloud.githubusercontent.com/assets/19862352/15976542/d2db5660-2f29-11e6-8347-482047e502ee.PNG)

**Comment by koush** [comment]
Go to the console tab in your above screenshot and get me the logs.

**Comment by koush** [comment]
Right now you are in the element tab, click one tab over "Console".

**Comment by matheusborgest** [comment]
Oh, sorry. 
![capturar3](https://cloud.githubusercontent.com/assets/19862352/15977006/9a698434-2f2c-11e6-9b29-56b7c2a9343a.PNG)

**Comment by koush** [comment]
I need the purchase.html logs, not background page.

**Comment by jeremykirkup** [comment]
I have the same issue, any resolution?

**Comment by koush** [comment]
Please let me know your Country (some countries do not support Chrome web store) and ensure you are on Chrome STABLE and logged into Chrome. @jeremykirkup

**Comment by dcostinett** [comment]
Hi Koush -- I'd like to purchase several copies for myself and my coworkers, but I'm unable to figure out how to send my boss a link to pay for them. He's not able to use Google Wallet or Pay Pal, can you let me know how I can purchase several licenses for several developers?

Thanks.

**Comment by koush** [comment]
@dcostinett hey, there's no way to do that yet. But I literally just started working on Stripe integration today. That will let you enter a company card and pay per seat. Hopefully will have that finished by mid next week.

**Comment by jeremykirkup** [comment]
I tried to purchase the full product several times but PayPal keeps timing out (tried it 5 times)
This has got to be one of the most difficult products I have ever tried to purchase ;-)
Please help :-)

Error: Server ErrorThe server encountered an error and could not complete your request.Please try again in 30 seconds.

Date: Fri, 17 Jun 2016 14:42:31 -0700

**Comment by koush** [comment]
@jeremykirkup let me look at the logs, one moment. PayPal was just recently added as an option.

**Comment by koush** [comment]
@jeremykirkup ok, i see the error in the server logs. paypal is 404ing me on approval of the transaction. lemme figure out what is up.

**Comment by koush** [comment]
@jeremykirkup ok, mind giving it a shot again? server side bug should be fixed.

**Comment by dcostinett** [comment]
Awesome, thank you. I look forward to it!

**Comment by jeremykirkup** [comment]
Hi Koush,
Any update on this?
Kind regards

From: jeremykirkup@hotmail.com
To: reply@reply.github.com; vysor.io@noreply.github.com
Subject: RE: [koush/vysor.io] How can I purchase? (#173)
Date: Sat, 18 Jun 2016 07:49:27 +0100




I tried to purchase the full product several times but PayPal keeps timing out (tried it 5 times)
This has got to be one of the most difficult products I have ever tried to purchase ;-)
Please help :-)

Error: Server ErrorThe server encountered an error and could not complete your request.Please try again in 30 seconds.

**Comment by koush** [comment]
@jeremykirkup Yes, this should be fixed. See my previous comment.

**Comment by koush** [comment]
Purchase options are now available in the Chrome Web Store and via Paypal.

**Comment by PandRAAP** [comment]
Can i pay it with google voucher?
