### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by tomxu93** [koush/vysor.io#175]
Signed up for 7 days free trial and tried out today. However it's not what I'm looking for. How can I unsubscribe?

**Comment by tomxu93** [comment]
Chrome ID a569027851@gmail.com

**Comment by koush** [comment]
Go to your Google Wallet, and look in the Bills section. You can unsubscribe there.

**Comment by craab13** [comment]
I have been trying to find the way to unsubscribe to Vysor, but it is not under my "Google Wallet Bills section". I don't want the pro version anymore, but it keeps charging me a monthly subscription.

**Comment by craab13** [comment]
Chrome ID a569027851@gmail.com

**Comment by Inkdrinkr** [comment]
I found it under https://payments.google.com/

**Comment by craab13** [comment]
It is not listed under this link for me...

On Apr 11, 2017 9:11 PM, "Inkdrinkr" <notifications@github.com> wrote:

I found it under https://payments.google.com/

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/koush/vysor.io/issues/175#issuecomment-293452209>, or mute
the thread

**Comment by craab13** [comment]
Is there an alternate place I could unsubscribe?

**Comment by Inkdrinkr** [comment]
Make sure you're logged into the same Gmail that you used to purchase the subscription. Mine wasn't labeled specifically as Vysor, just "Monthly Subscription"
http://imgur.com/gobgG8D

**Comment by craab13** [comment]
Yeah, I'm logged in under the same email, but it is still not showing up...
Any other place you might guess I could go to. Do you know if there is a
number I could call? Also, thanks so much for the help

**Comment by Inkdrinkr** [comment]
I'm out of ideas. Sorry.

**Comment by craab13** [comment]
Are you the founder of Vysor or the person who posted on the github for
clarification?

**Comment by Inkdrinkr** [comment]
I am just another user. The creator of the app is @koush

**Comment by craab13** [comment]
I found another way. Thanks!

**Comment by madanivly** [comment]
What way you found?

**Comment by koush** [comment]
Unsubscribe here:

https://plus.google.com/u/0/110558071969009568835/posts/ZYU9dED8DPG
