### ISSUE TITLE
Vysor share, remote device won't load/connect

### ISSUE THREAD

**Issue by bruor** [koush/vysor.io#176]
I'm not sure how to get you the information you need to troubleshoot this one.  I don't see any errors in the output when I try to debug any of the vysor pages when this happens.  Tell me what you need and how to get it and I'll send it over to you. 

I can plug a device into either one of my computers and vysor works locally without an issue. 

However if I do the following: 
1. connect device to computer A, and share
2. access the link with computer B (either a single device share, or a "share all devices" link) 
(computers are on the same network using the same google account)

The following happens: 
1. Vysor launches automatically with a pop up saying that it's connecting to a remote android device(s). 
2. The Vysor window shows "No devices found, make sure adb debugging is enabled" 

If I launch a single device share link on computer B from an incognito window,  a tab pops up that shows the vysor interface but it just hangs on "connecting" and never shows the remote device.

**Comment by koush** [comment]
you on google hangouts or something? would be good to debug this real time with me trying to access your device.

**Comment by bruor** [comment]
I am,  as well as screen hero (I can invite you).

**Comment by koush** [comment]
what is your email? I'll send you a hangout message

**Comment by koush** [comment]
or if you post in the Vysor G+ page, I can send you a hangout from there too.

**Comment by bruor** [comment]
adrien.carlyle@gmail.com

**Comment by koush** [comment]
did we resolve this? i recall messaging you.

**Comment by krokmobile** [comment]
@koush Hey Koush. I am having the exactly same bug on my enterprise plan. Sent you the debug report to support@. Could be please fix it asap? I am ready for real-time operation.

**Comment by harishvishwakarma** [comment]
Hey @koush , same issue on paid account. Haven't been able to remote debug even once.

**Comment by Cililing** [comment]
Same here.

After 2-3h of playing with various configurations and phones  I was able to see device with name "(" and serial "(" - on guest device (I passed server url in app via "connect to network device").
Trying to connect ends with "no debugging allowed" error.

And I hope it doesn't require being in the same network.
