### ISSUE TITLE
plugin not supported

### ISSUE THREAD

**Issue by c3ph3us** [koush/vysor.io#179]
plugin not supported is this PPAPI ??

     Chromium Version 51.0.2704.79 
     built on Debian stretch/sid, running on Debian  stretch/sid (64-bit)

     Adobe Flash Player - Version: 21.0.0.242
     Shockwave Flash 21.0 r0

 dpkg -l | grep pepperflash

     ii  browser-plugin-freshplayer-pepperflash 0.3.5-1                           
     amd64        PPAPI-host NPAPI-plugin adapter for pepperflash

     ii  pepperflashplugin-nonfree              1.8.2+nmu1                           
     amd64        Pepper Flash Player - browser plugin

**Comment by koush** [comment]
It uses PNaCL. PNaCL comes with Google Chrome Stable. It's not in Chromium, which is what i think Ubuntu distributes.

**Comment by c3ph3us** [comment]
for anyone interested in support for PNaCL in Chromium:

https://www.chromium.org/nativeclient/pnacl/building-pnacl-components-for-distribution-packagers

**Comment by ssprakhar** [comment]
saved my life.

**Comment by WuerfelDev** [comment]
Can someone explain how I get this running?
Did I understand it right that i have to build Chromium myself? What have i to do?

**Comment by Johncy1997** [comment]
Can anyone tell how to solve this problem?Am using ubuntu 16.04..I cant view my screen in vysor
![screenshot from 2018-03-02 12-24-04](https://user-images.githubusercontent.com/25324938/36886936-c05edd96-1e14-11e8-9164-2d3b8251c8ae.png)

**Comment by a1s123** [comment]
I have same problem.

**Comment by jacek3107** [comment]
I have the same problem !!! What I have to do?

**Comment by setiodewo** [comment]
Is there any solution for this problem?

**Comment by Kangburra** [comment]
I have this in Chromium and Vivaldi, not happy that it requires a specific browser, it's like we're back in 1998!

**Comment by tellwap** [comment]
i have faced the same problem

**Comment by HesseSummer** [comment]
I faced the same problem, and I fixed it in the following two ways:
1. Now there's a distribution for Linux, and it works well on my Ubuntu.
2 Using Vysor on Chrome browser

**Comment by AshikAzeez** [comment]
Download AppImage file from [here](https://github.com/koush/vysor.io/releases/download/continuous/Vysor_2.1.7.AppImage)
->Make file executable
->double click to install

**Comment by logaraj82** [comment]
enable webgl --> refer: https://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu
