### ISSUE TITLE
Feature Request: Link to share all devices

### ISSUE THREAD

**Issue by Redth** [koush/vysor.io#18]
It would be incredibly useful to be able to send a link to someone that will share all connected (currently and in the future) devices.

The motivation for this would be to connect many devices to a single server, and share all of them with multiple developers that could then choose to connect to devices as needed.  Even for solo developers it would be useful to keep my desk of devices plugged in and be able to more easily connect to them from the couch.

**Comment by koush** [comment]
yeah, i meant to do this but the app was leaked so i had to release without that feature. it's coming.

**Comment by koush** [comment]
done
