### ISSUE TITLE
Window resizing broken on 1.1.1.2

### ISSUE THREAD

**Issue by KevDoy** [koush/vysor.io#181]
![screen shot 2016-06-30 at 1 59 00 pm](https://cloud.githubusercontent.com/assets/11251011/16504069/ef4e0cc4-3eca-11e6-8aea-5c6e6bd757a7.png)
You used to be able to resize the window, and the image/video size would automatically adjust. Now it just crops the image instead of resizing it when shrinking the window.

**Comment by koush** [comment]
fixed in 1113
