### ISSUE TITLE
Can't paste into Vysor, OSX

### ISSUE THREAD

**Issue by braco** [koush/vysor.io#184]
Just downloaded and paid for Vysor, disappointed this feature doesn't work.

Samsung Edge 6, newest OS releases of OSX and Android

**Comment by koush** [comment]
Works fine for me. Just press CTRL-V to paste.

**Comment by anawim** [comment]
NO CTRL+V doesn't work on Windows too most of the times, depending on what's been copied, typically multiple lines.
