### ISSUE TITLE
Black Screen on Note 5

### ISSUE THREAD

**Issue by alimerii** [koush/vysor.io#185]
I used Vysor last week on my Galaxy Note 5 but few days later my computer crashed and I had to reinstall windows fresh. 
No Vysor connects to my phone and I can control it but the screen is black.

-The cube website doesn't work
- this page : chrome://nacl/ shows nacl enabled
- this page: chrome://components/ show nacl Version: 0.45.33.8390

I have windows 10 and android 6.0.1
ADB installed

**Comment by mboutell** [comment]
I have the same exact issue on my Nexus 5x running Android 6.0.1 on my PC with Windows 7. I can control the phone, but the mirrored screen is black.

**Comment by koush** [comment]
https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp
