### ISSUE TITLE
Black screen with some apps

### ISSUE THREAD

**Issue by denper76** [koush/vysor.io#186]
Vysor in general works well, but when this app https://play.google.com/store/apps/details?id=chat.anti is running, I have the black screen. Mouse and keyboard works and also the popups generated by this app are visible.

Window 7
Motorola Moto G
Lollipop 5.02
vysor version 1.1.1.9
phone is rooted

**Comment by koush** [comment]
Some apps are protected from screen recording and screenshots. This is one of them.

**Comment by turkeyphant** [comment]
I accidentally got round the screen protection once immediately after installing the app but haven't been able to find steps to reproduce this since.
