### ISSUE TITLE
Support to buy Vysor in India

### ISSUE THREAD

**Issue by Testpanasonic** [koush/vysor.io#188]
Need to know whether it is possible to buy a single user licence in India by paying 2$. Need support to buy a single user license of Vysor Pro.

**Comment by koush** [comment]
Yeah, Paypal and Chrome store should both be supported in India.

**Comment by Testpanasonic** [comment]
I am able to see the Paypal option only for the Lifetime Pass option . For the others options (Monthly , Annual and Life time -(INR) ) I See only Google Wallet as available option as shown in the below link.
Request you to share the URL to make payment in India for Buying a single user license .

![vysopayoptions](https://cloud.githubusercontent.com/assets/18413250/16980469/b855867a-4e83-11e6-811d-9db988f5e67f.jpg)

**Comment by koush** [comment]
There is no $2 monthly option for PayPal.
