### ISSUE TITLE
Error installing APK

### ISSUE THREAD

**Issue by bb-noob** [koush/vysor.io#189]
I have a Samsung Galaxy S6 and am running Windows 7 with the Universal ADB driver.  I can connect to my phone using Vysor but after a few seconds it crashes and I see a message that says "Error installing APK".  Any advice to fix this?

**Comment by koush** [comment]
head here please:

https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

**Comment by Tiverty** [comment]
Hey bb-noob, did you ever find a resolution to this issue?

**Comment by Calvin159** [comment]
I to em having this issue on my LG G4

**Comment by thetroublemaker** [comment]
I'm having the same issue on my Galaxy S7. I'm running Windows 10 with the universal ADB. It connects but then says Error installing APK.

**Comment by Tiverty** [comment]
It ended up being my cable. Double check it's ability to charge and transfer data. The cable was charging my phone and it showed up on my computer, but it lacked the data throughput ability that apparently was necessary.

**Comment by thetroublemaker** [comment]
My cable is fine. Windows 10 can see my phone and file transfer. Now I'm getting 30 seconds of connection then crash.

**Comment by zocreativeinc** [comment]
I was having an issue with Vysor and it could not install the APK. I had a Hard Drive Connected to the computer via USB. As soon as I disconnected it. Vysor started working perfectly. FYI I am on the Ad Supported version. I am using my Charging USB cable it works fine. I am on a Samsung Galaxy S8+. I hope this helps someone.
