### ISSUE TITLE
No feedback on first connection if device not authorized for adb

### ISSUE THREAD

**Issue by whisdol** [koush/vysor.io#19]
If the device is not already authorized to connect via adb, Vysor doesn't show any reaction after choosing the device from the "Find Devices"-list. The screen-window only opens after the fingerprint is approved on the device and the device name isn't added to the device list in the main window either, so my first reaction was "huh, it doesn't work" - which is obviously not the case.

Nexus 5, M Preview 3.

**Comment by koush** [comment]
oops derp will fix

**Comment by koush** [comment]
Fix released, rolling out now. Notification will be shown.

**Comment by whisdol** [comment]
Works for me with 10.0.3.9.
