### ISSUE TITLE
Stays on Connecting... Screen

### ISSUE THREAD

**Issue by BossC** [koush/vysor.io#191]
I have been trying to figure out the problem for a few hours now. After making sure that I had my debug enabled on my phone, adding the ADB, and getting a message from my phone saying that Vysor was connected and requesting to share the screen, the program will only have the Connecting... message appear with the GIF of the three bars. Here is an image of what it looks like.

![image](https://cloud.githubusercontent.com/assets/13923436/17045243/cc44a202-4f95-11e6-9a77-03611f3c4f49.png)

I am on a Galaxy S5, and it seems that everything is working besides that. I have double-checked that my Java was updated and both my laptop and my phone have been restarted several times. Here is an image of the Vysor main tab when this is happening.

![image](https://cloud.githubusercontent.com/assets/13923436/17045269/0a2bc474-4f96-11e6-975b-422c25aab5a8.png)

Also note that at times, when I try to restart Vysor by closing the tabs, it does not want to restart at all. I do not seem to find the process anywhere in the Task Manager (with the 20 Google Chrome-related processes not seeming to relate with this). This doesn't bother me that much, even though I have to restart my computer to relaunch it since trying to start it after this error does not bring it back up.

**Comment by koush** [comment]
Please go here to submit a bug report. There are further instructions on the information I'll need to debug this issue.

https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

Also, see that Support link on the bottom of your second screenshot? Use that!
