### ISSUE TITLE
Even when logged in to chrome I am prompted to log in

### ISSUE THREAD

**Issue by mdownplane** [koush/vysor.io#192]
When I try to purchase I am sent to the Chrome login screen in a new window, which then says I am already on that machine.  I never get past this step and am never prompted to purchase.  I just get to my google search home page

**Comment by koush** [comment]
Are you on Chrome stable? Not Chromium.

**Comment by mdownplane** [comment]
Yes

Michael Mittelman
Principal, Downplane Consulting

**Comment by koush** [comment]
How are you trying to purchase? Paypal or chrome store?
