### ISSUE TITLE
LG G4 Black Screen

### ISSUE THREAD

**Issue by godaidgo** [koush/vysor.io#194]
I am completely new to all of this and trying to get my phone screen on my PC so that I can capture the screen and record things on it. When I open up the app it allows for me to click on things.  However, as the below screen shot shows, the display on the PC is only black. Any direction I can go to get this fixed?

![lgg4snip](https://cloud.githubusercontent.com/assets/20750653/17275224/f0a83f6e-56c5-11e6-8969-3aecd1f04978.PNG)

**Comment by koush** [comment]
Use the support link in the app. There's a resolution to this issue. Where did you find this issue tracker anyways?
