### ISSUE TITLE
Vysor OBS Capture // h.264 recording

### ISSUE THREAD

**Issue by Tidomann** [koush/vysor.io#195]
I recently have been using Vysor with OBS in order to record my phone to my computer. Howerever, Chrome cannot be captured in the latest versions using OBS while hardware acceleration is enabled. To work around this I was using older version of Chrome. I believe chrome versions before 50 allowed programs like Xsplit and OBS to window capture while hardware acceleration was enabled.

With the newest versions of Vysor being released requiring Chrome 51+ I am now unable to stream any captured devices.

Is there any way to have Vysor functions without hardware acceleration? Or am I able to use older versions of vysor still? When trying to install old crx versions to the old versions of Chrome I get a "This application must be installed from the store" message.

A way around this is to use monitor capture, but I am unable to use that method because my computer is an nvidia laptop, and selecting the intel GPU causes the stream to lag when the lid is closed.

I hate laptops and windows 10.

_____________________________________________________

My second questions has to do with Cyanogen android's and vysor. Currently I don't get a black screen, but instead a static kind of image using software encoding

http://imgur.com/TmW47Ps

Doing some light research I could see that it may be an issue with the h.264 which you've recently had to stop using. Are there any ways around this? Is this a feature that may be accessible to pro users?

**Comment by koush** [comment]
What was the latest compatible version of Chrome?

**Comment by koush** [comment]
As for the second question, what device?

**Comment by koush** [comment]
Man I'm of half the mind to make a Chrome based competitor to OBS. Could just design and program stream overlays in HTML/Javascript then.

**Comment by koush** [comment]
![snapsink-38](https://cloud.githubusercontent.com/assets/73924/17505823/b4602f90-5db8-11e6-9742-703ec1857bcb.png)
Seems to be working for me on Mac. Is this a Windows only thing?

**Comment by Tidomann** [comment]
It might be a Windows thing. I'm using open broadcaster studio on Windows 10

The last version to work was chrome 49 I believe, something changed in chrome 50 and nobody in the obs forums really knows what changed.

The device I was using is a Samsung Galaxy s4, sgh-I337m. It was working fine when I was using lollipop with the stock os (Canada Bell). I'm trying to find a way to get the stock os working again since my restore file for it isn't working anymore unfortunately.

**Comment by koush** [comment]
https://twitter.com/vysorapp/status/764568975518801920
