### ISSUE TITLE
Can't install apk

### ISSUE THREAD

**Issue by barol86** [koush/vysor.io#197]
Hello i have a problem with my Xiaomi Mi4C and Vysor. I have enabled usb debugging and when i try to connect to my phone, it says installing vysor apk... and then: apk installation failed. I tried installing it manually from google play but it doesnt work. Please help.

**Comment by koush** [comment]
Please use the support link within the app and provide the log.

**Comment by marcus2207** [comment]
Hello,
I have same problem to barol86 with my Mi4S phone. Phone is visible througt file explorer, and Vysor see it too. When I click connect it Vysor says apk installation failed.

I use vysor pro. 
When i use it with SGS 4 there was no problem. Week ago I bought Xiaomi Mi4S. Vysor worked perfectly until I updated my rom to xiaomi.eu_multi_MI4s_6.9.8_v8-5.1.zip (MiUi ver 8, before i have ver 7.2.5).
I gladly send any logs but I need instructions how to provide them.

I have latest ADB drivers, USB drivers, and usb debuging ON.
