### ISSUE TITLE
Scrambled Screen

### ISSUE THREAD

**Issue by alicecodes** [koush/vysor.io#199]
Hi, 

Using Vysor with Nexus 7 (Andriod 4.4.2) and Mac Chrome (52.0.2743.116) and the screen is scrambled as seen below. Any thoughts on how to fix this? Thanks!

![screen shot 2016-08-19 at 1 08 56 pm](https://cloud.githubusercontent.com/assets/1619724/17822830/1a537a2a-660e-11e6-812b-b77ab6ca319d.png)

**Comment by koush** [comment]
Please use the support forum. There's a template to report bugs and provide logs.
