### ISSUE TITLE
will not connect to andorid wear device

### ISSUE THREAD

**Issue by mralext20** [koush/vysor.io#20]
i am using ubuntu 15.04, chrome version 44.0.2403.157, vysor version 1.0.4.0.

connected to watch via nexus 6, bluetooth debugging is enabled, and i can get a shell on the watch.

vysor installs its stub app and connects eventually, but only a black screen shows up.
![image](https://cloud.githubusercontent.com/assets/4016295/9482140/683bd756-4b3d-11e5-92f4-3abe64d35dd8.png)

**Comment by koush** [comment]
yep, known issue. android wear doesn't support screen recording, but i have another idea to fix it.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/2

**Comment by rekire** [comment]
I cannot enable visor on my watch since the button is not visible. Can you change that?

**Comment by BeniGal** [comment]
We subscribed to this great service today, but this limitation of Android Wear is really hindering us. Can you please prioritize to address it?
@rekire I can confirm that the button on the Vysor application screen is really not visible on the watch (Sony SmartWatch 3, 320 × 320 pixel screen).
It is true that screen recording is not working properly on the watch. However, I managed to get some limited quality screencasting with this [GitHub project, Android Projector](https://github.com/anthonylai/android-projector). So there is definitely some workaround for Android Wear.
