### ISSUE TITLE
Share not working

### ISSUE THREAD

**Issue by moiboy22** [koush/vysor.io#201]
I noticed the share function giving me the frown face of death every time someone connected to my share link. Is there a fix for this?

**Comment by koush** [comment]
Only one person can view a screen using Vysor at a time. If you are sharing, close your viewer window.

I may be able to fix this in the future, but right now, it's one at a time.

**Comment by koush** [comment]
Sharing and viewing not supported at the same time. Fixed UI to reflect this.
