### ISSUE TITLE
Black Screen after Update to Pro Version

### ISSUE THREAD

**Issue by Op3r4t0r** [koush/vysor.io#202]
Wow, i used this about for a long time and really loved it. 

Today i decided to give the Dev's something back and bought the Pro Version. 

Since the Pro Version is registered i cannot use Vysor anymore. Got the Black Screen Issue.. 
Im just speechless about this behavior....

tried every suggestion on the black screen support list...
please tell me  how to unsubscribe or delete my subscription, i want to have the working free version back!

**Comment by koush** [comment]
Open an issue on the support forum please.

**Comment by koush** [comment]
If you changed any of the pro settings, you may want to reset them to default btw.
