### ISSUE TITLE
Vysor - error instaling app see also issue #197

### ISSUE THREAD

**Issue by marcus2207** [koush/vysor.io#203]
Hello,
I have same problem to barol86 with my Mi4S phone. Phone is visible througt file explorer, and Vysor see it too. When I click connect it Vysor says apk installation failed.

I use vysor pro. 
When i use it with SGS 4 there was no problem. Week ago I bought Xiaomi Mi4S. Vysor worked perfectly until I updated my rom to xiaomi.eu_multi_MI4s_6.9.8_v8-5.1.zip (MiUi ver 8, before i have ver 7.2.5).
I gladly send any logs but I need instructions how to provide them.

I have latest ADB drivers, USB drivers, and usb debuging ON.

Last weekend I saw there is an option - Install applications throught USB - I enable it but it wont help.

**Comment by Calvin159** [comment]
Im also having this issue with my LG G4 have Vysor Pro as well.....

**Comment by mironiasty** [comment]
You have to disable MIUI optimization in phone developer settings.
Here are more details: https://github.com/facebook/react-native/issues/6499#issuecomment-229319822
