### ISSUE TITLE
Feature Request: Keyboard Mapping On Screen

### ISSUE THREAD

**Issue by kuswanto** [koush/vysor.io#204]
This is a view from a typical users and how Vysor can be an ultimate mirroring app for gamer. Right now Vysor can be really usefull to play point and click games, best response time than other mirroring apps.

Is there any plans to remap keyboard shortcuts overlay on screen, usually to control movement (key AWSD) or key shortcuts for skills.

**Comment by koush** [comment]
Implemented

https://github.com/koush/vysor.io/issues/211
