### ISSUE TITLE
Vysor shows a blank screen when using apps that block screenshots

### ISSUE THREAD

**Issue by the4ndy** [koush/vysor.io#205]
I have a large number of "secure" apps on my phone that disallow the ability to take a screenshot. It appears as though they also break the functionality of Vysor.

Example Apps:
Signal Messenger - https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en
Wickr - https://play.google.com/store/apps/details?id=com.mywickr.wickr2&hl=en
Blockchain - https://play.google.com/store/apps/details?id=piuk.blockchain.android&hl=en

**Comment by koush** [comment]
Yes, this is correct. Some apps can choose to enable a DRM flag that prevents system capture of the screen.
