### ISSUE TITLE
Linux: Automatic window resizing causes flicker with a tiling WM

### ISSUE THREAD

**Issue by krisdages** [koush/vysor.io#206]
Using i3 as a window manager, the edge of the Vysor window flickers every couple of seconds, moving buttons and interrupting interaction with the Settings UI.  

Depending on the width of the window, it's either the horizontal or vertical edge, and looks like it's continually trying to shrink the window to the size of the screen image.

**Comment by koush** [comment]
hm i thought i fixed this. I'll look again.

**Comment by koush** [comment]
is i3 trying to forcibly size the window to some gridlines or somethng?

**Comment by krisdages** [comment]
I don't think so. I had a terminal window open and vysor popped up in its own window (split to the right) the moment I connected with adb.  I just drag resized the window from there.

**Comment by krisdages** [comment]
I'm restoring apps on my phone after the Nougat upgrade right now but I can try a couple other test cases in a bit if it would help.  I have a Nexus 6p btw, Not sure if that makes a difference.  Thanks!

**Comment by koush** [comment]
Any chance you can make a video of this issue?

**Comment by krisdages** [comment]
Sure

**Comment by krisdages** [comment]
[vysor-issue206.mp4.zip](https://github.com/koush/vysor.io/files/486683/vysor-issue206.mp4.zip)

**Comment by koush** [comment]
Yeah, it looks like your window manager is trying to force it to fit specific dimensions. That's annoying. Vysor is fighting with it, trying to enforce the aspect ratio of the screen.

**Comment by ohli** [comment]
@krisdages Enabling the floating window mode in i3 solves this.
(I have no video because of missing chrome plugins, but that's another story).

**Comment by Rokemon** [comment]
I am using Vysor on Ubuntu. Could you suggest how to resolve the flicker problem on that ? 
Ubuntu Verson 16.04, Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by efi-mk** [comment]
Hi, having exactly the same problem as @Rokemon mentioned. A pro user

**Comment by koush** [comment]
Right now, don't dock the window against the edges of the screen. I haven't figured out how to detect/fix this.
