### ISSUE TITLE
Black Screen issues

### ISSUE THREAD

**Issue by ahboy99** [koush/vysor.io#207]
can you help for this problem?
i don't know why my vysor is black screen but i reset completely on my phone then i don't know is my GPU problem or not i try at PNaCI cube but load failed(or my ADB conflicted or not?)

here is my specs on my PC and my phone
PC:ASUS STRIX R7370 2G(AMD CC 15.201(ASUS Version))
Google Chrome:53.0.2785.116 m (64-bit)(Hardware accelerated Enabled)
Windows 10 Anniversary Update x64

Phone:
Samsung Galaxy Note 2 (GT-N7100)
CM12.1
Rooted(SuperSU+Xposed)

help is appreciated thanks~

**Comment by koush** [comment]
use the support link, there's more info on this issue there.
