### ISSUE TITLE
Feature request: Hardware buttons, keyboard shortcuts & menus

### ISSUE THREAD

**Issue by JasonM77** [koush/vysor.io#21]
I know I can hit right mouse button to go home, etc but on a MacBook Air to go "home" I need to hit Fn+LeftArrow. Kind of clunky.

Can we have a menu option for Android Keys > Home, Back, Recent, Menu?

Some kind of floating button bank with representations of the buttons would be cool too.

**Comment by koush** [comment]
right click is back
middle click is home

**Comment by anawim** [comment]
@koush I've seen you implemented copy & paste in 1.0.4,8 and marked ny issue as closed but I still cannot figure out how to perform copy and paste (and cut?) operations across devices

**Comment by koush** [comment]
here's a demo.

https://www.youtube.com/watch?v=ANUGETm2Cmg&feature=youtu.be

**Comment by anawim** [comment]
Really I don't know how can be that fast for you, my experience is very slow. Also it's not clear from the video how do you select the text, with mouse movement (not ideal) or with Ctrl-Shift-End (much much preferred but not working for me)

**Comment by koush** [comment]
i just double click the text and adjust the sliders.

**Comment by thorpj** [comment]
Don't forget that many laptops can't middle click. Or at least, my macbook running windows can't.

**Comment by anawim** [comment]
"i just double click the text and adjust the sliders" OK this is not ideal as I never use this way on computer plus it's too slow to have control it's so much better to be able to use Ctrl+shift keyboard combination. Can you add it?

**Comment by koush** [comment]
no, thats not how android's copy and paste works.

**Comment by anawim** [comment]
It's not about copy but about text selection! But actual vysor shortcuts get in the way

**Comment by djpeinado** [comment]
What about PgUp and PgDn to fast scrolling?

**Comment by koush** [comment]
Custom keybindings can let you do whatever you want now.
https://github.com/koush/vysor.io/issues/211
