### ISSUE TITLE
Vysor kills running ADB

### ISSUE THREAD

**Issue by SgtSeppel** [koush/vysor.io#210]
Hi Koush, 

until a few days ago I could use Vysor together with an already running ADB instance. 
I'm often using port forwards (adb forward tcp: ...) to connect to an SSH server or proxy on my phone.
Vysor then either showed that it's using the internal ADB or the ADK one ...

Today I noticed that I could not connect to the servers on my phone anymore after Vysor started.
As soon as I re-enable the port forward, I can see the "adb server is out of date. killing ..." message.
Vysor then immediately reloads and kills my adb - and port forwards - again.

Is there a solution to that? Can I switch back to an already running ADB?

**Comment by koush** [comment]
Which Vysor? Desktop or Chrome version?

**Comment by SgtSeppel** [comment]
Seems to happen on the desktop version only,  now that you mention it.

**Comment by koush** [comment]
Are you running an older version adb on your system? Vysor ships with the latest (last I checked), and that will restart older adb servers automatically.

**Comment by koush** [comment]
Fixed. The windows version came with an ancient ADB accidentally.
