### ISSUE TITLE
Customize Vysor

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#211]
Customizing Vysor allows you to change how key events are mapped from your desktop PC to your Android device. You can also modify the navigation bar along the bottom bar of your Vysor screen to add or remove buttons.

![snapsink-3](https://cloud.githubusercontent.com/assets/73924/19336615/ca634f8e-90c1-11e6-9ab1-99cab91fa9e4.png)

# Defaults
Here are the default settings that Vysor uses:

```json
{
  "keydown": {
    "ArrowDown": "KEYCODE_DOWN",
    "ArrowLeft": "KEYCODE_LEFT",
    "ArrowRight": "KEYCODE_RIGHT",
    "ArrowUp": "KEYCODE_UP",
    "Backspace": "KEYCODE_DEL",
    "Delete": "KEYCODE_FORWARD_DEL",
    "Enter": "KEYCODE_ENTER",
    "Escape": "KEYCODE_BACK",
    "F1": "KEYCODE_MENU",
    "F2": "VYSOR_SHOW_TITLE_BAR",
    "Home": "KEYCODE_HOME",
    "Tab": {
      "keyevent": "KEYCODE_TAB",
      "shiftKey": true
    }
  },
  "navigationBar": {
    "buttons": [
      {
        "class": "fa fa-lg fa-chevron-left",
        "event": "KEYCODE_BACK",
        "title": "Back"
      },
      {
        "class": "fa fa-lg fa-circle-o",
        "event": "KEYCODE_HOME",
        "title": "Home"
      },
      {
        "class": "fa fa-lg fa-navicon",
        "event": "KEYCODE_APP_SWITCH",
        "title": "Recent Tasks"
      }
    ]
  },
  "devices": {
    "example-device-serial": {
      "keydown": {
        "F3": "KEYCODE_BACK"
      },
      "navigationBar": {
        "buttons": [
          {
            "class": "fa fa-lg fa-circle-o",
            "event": "KEYCODE_HOME",
            "title": "Home"
          }
        ]
      }
    }
  }
}
```

# keydown entry

This entry maps a JavaScript [KeyboardEvent.key or KeyboardEvent.keycode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) to an [Android KeyEvent Keycode value](https://developer.android.com/reference/android/view/KeyEvent.html).

The syntax for an entry is as follows:
```
[Keycode Number|Key String]: [KeyEvent String|Key Event Object]
```

A Key Event Object is:
```
{
[keycode|keyevent]:[number|string],
shiftKey:[true|false|undefined]
}
```

Here, an "ArrowDown" in JavaScript is mapped to a "KEYCODE_DOWN" in Android:
```json
"ArrowDown": "KEYCODE_DOWN",
```

The "shift" modifier can also be sent to the key event. Instead of mapping to a string, map to an object as such. For example, to move between controls on Android, map the Tab Key, with the shift modifier, to KEYCODE_TAB:
```json
"Tab": {
  "keyevent": "KEYCODE_TAB",
  "shiftKey": true
}
```

**Comment by koush** [comment]
Saved

**Comment by koush** [comment]
Saved

**Comment by Mogster** [comment]
Say I wanted to map Windows' Back button (mouse button 4 or Alt + Left Arrow) to KEYCODE_BACK. What string would I use?

**Comment by koush** [comment]
Hm, let me see. I hadn't thought about alt-modifier.

**Comment by rajthampi** [comment]
Hey koush, how do I map the send button? I am mostly using vysor to chat from computer & it's kinda frustrating that I have to use the mouse to click send button, as I don't prefer using Enter key for the send.

**Comment by koush** [comment]
@rajthampi this is fixed in the latest version of Vysor. Make sure you are on 1.6.3 and then just reset your key bindings.

**Comment by rajthampi** [comment]
@koush Can you please tell me which key I have to use for "Send" on screen button?

**Comment by rajthampi** [comment]
@koush I am using 1.6.3 Desktop Pro client btw.

**Comment by koush** [comment]
"Enter": "KEYCODE_ENTER",

**Comment by rajthampi** [comment]
@koush Well, then I need to change the app setting to consider Enter as send :), which I am not planning to. Instead I would like to map the "Send" on screen button to one of the physical keyboard keys. Is it possible?

**Comment by koush** [comment]
no

**Comment by trufae** [comment]
How about ^C?

**Comment by koush** [comment]
I actually got the default IME action working in a recent patch. There was a bug.

**Comment by motocross79** [comment]
What about ruusian language support ? i can tape only english

**Comment by harimau99** [comment]
Hi im using my OSX 10.11 but i can't control the display image that shown in vysor.
How do i setup or calibrate? 

This is are the setting found inside.. (seems looks like default).
`{
  "devices": {
    "example-device-serial": {
      "keydown": {
        "F3": "KEYCODE_BACK"
      },
      "navigationBar": {
        "buttons": [
          {
            "class": "fa fa-lg fa-circle-o",
            "event": "KEYCODE_HOME",
            "title": "Home"
          }
        ]
      }
    }
  },
  "keydown": {
    "ArrowDown": "KEYCODE_DPAD_DOWN",
    "ArrowLeft": "KEYCODE_DPAD_LEFT",
    "ArrowRight": "KEYCODE_DPAD_RIGHT",
    "ArrowUp": "KEYCODE_DPAD_UP",
    "Backspace": "KEYCODE_DEL",
    "Delete": "KEYCODE_FORWARD_DEL",
    "Enter": "KEYCODE_ENTER",
    "Escape": "KEYCODE_BACK",
    "F1": "KEYCODE_MENU",
    "F2": "VYSOR_SHOW_TITLE_BAR",
    "Home": "KEYCODE_HOME",
    "Tab": {
      "keyevent": "KEYCODE_TAB",
      "shiftKey": true
    }
  },
  "mousedown": {
    "1": "KEYCODE_HOME",
    "2": "KEYCODE_BACK"
  },
  "navigationBar": {
    "buttons": [
      {
        "class": "fa fa-lg fa-chevron-left",
        "event": "KEYCODE_BACK",
        "title": "Back"
      },
      {
        "class": "fa fa-lg fa-circle-o",
        "event": "KEYCODE_HOME",
        "title": "Home"
      },
      {
        "class": "fa fa-lg fa-navicon",
        "event": "KEYCODE_APP_SWITCH",
        "title": "Recent Tasks"
      }
    ]
  }
}`

**Comment by EmotionalRonanyg** [comment]
@harimau99  you should turn on  Install via USB  and  USB debugging(Security settings)  in Developer options.

**Comment by Altairr** [comment]
im using andriod note4 . and when im playing my games. why cant i control it using my laptop ? anyone please help

**Comment by Altairr** [comment]
is anyone here to help ?
