### ISSUE TITLE
BlackScreen with PNACL installed and enabled

### ISSUE THREAD

**Issue by JuneLeGency** [koush/vysor.io#212]
Hey guys,my vysor not work in both windows 7 and windows 10.I cant figure the reason.
Vysor Version 1.5.0 chrome extension and standalone app both not work.

I've already tried the solution from here https://plus.google.com/u/0/110558071969009568835/posts/BGUH6yojfSf
still not fixed.

System:
```
CPU: i7 4770K
GPU:GTX770
OS:Windows10 64 & Windows7

```
chrome nacl tab view
```
NaCl plugin C:\Program Files (x86)\Google\Chrome\Application\53.0.2785.143\internal-nacl-plugin 

Portable Native Client (PNaCl) Enabled 
PNaCl translator path C:\Users\legency\AppData\Local\Google\Chrome\User Data\pnacl\0.45.33.8390\_platform_specific\x86_64 
PNaCl translator version 04818d4a4324228e5491c143c264e8e20c86d928 

Native Client (non-portable, outside web store) Enabled by flag '--enable-nacl' 
```

screen.html Log:
```
docReady
uglify-screen.js:1 connectionReady
uglify-screen.js:1 init
uglify-screen.js:1 input websocket failed, retrying. attempt 1 out of 5
uglify-screen.js:1 input websocket opened
uglify-screen.js:1 event from phone {"type":"password"}
uglify-screen.js:1 event from phone {"type":"displaySize","screenWidth":1080,"screenHeight":1920,"nav":true}
uglify-screen.js:1 event from phone {"type":"encodeSize","encodeWidth":540,"encodeHeight":960}
uglify-screen.js:1 received socket r {device: n, localId: 20, remoteId: 18, pendingWrite: null}
screen.html:1 NativeClient: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)
```

When I try visit https://gonativeclient.appspot.com/demo/cube
the following log also apper.
```
started
index.html:1 NativeClient: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)
```

But the extension Native Client SDK seems works fine.
I'm quite confused.

**Comment by koush** [comment]
reinstall chrome. (use the support forum please)
also, as that post states, don't open bugs for this issue. there is no other listed solution. your chrome install is busted.

**Comment by koush** [comment]
Go ahead and open an issue on the standalone app though. That doesn't use PNacl. That may be a totally different bug.

Read this thread regarding your chrome issue:
https://groups.google.com/forum/#!topic/native-client-discuss/xe6ojaQo44A

**Comment by JuneLeGency** [comment]
reinstall chrome fixed
