### ISSUE TITLE
Can't Retrieve License with Standalone Desktop App

### ISSUE THREAD

**Issue by vnreview** [koush/vysor.io#216]
I can Retrieve License with Chrome Apps Version but Can't Retrieve License with Standalone Desktop App. Please fix this. My acount is vnreview.test@gmail.com

Here is my screenshot:

https://goo.gl/DkC2hT (vysor chrome apps)

https://goo.gl/Xw5dwV (vysor desktop apps)

**Comment by koush** [comment]
use the support link please.
