### ISSUE TITLE
Mobile screen shattered and Vysor giving error : Could not access the package manager. Is the system running ?

### ISSUE THREAD

**Issue by namitasantwani** [koush/vysor.io#217]
Hi,
My mobile phone's screen is completely shattered and unusable. I am trying to use it through Vysor but it is giving the error  "Could not access the package manager. Is the system running ?"
Please help me with this. This is very urgent.

Note : Mobile is Moto X and PC runs Windows 10

TIA
Namita.

**Comment by rishabh135** [comment]
@koush I am also facing the same issue , did you happen to solve this in any way ?
