### ISSUE TITLE
can't recognize my Oneplus one

### ISSUE THREAD

**Issue by gluke** [koush/vysor.io#22]

**Comment by koush** [comment]
install the universal adb driver, turn on adb, enable PTP mode.

You on windows 10? in which case, use the android sdk drivers.

**Comment by koush** [comment]
try these drivers and instructions.


https://www.youtube.com/watch?v=Ucs34BkfPB0

**Comment by parthmistry19** [comment]
Not working. Tried both. The message which came in your Nexus 6 in the video about Authorization message for the PC is not coming in the first place. Although my PC is recognizing the phone and I am able to transfer files, the vysor app is not detecting it.
![f50bd4c8-4cd3-11e5-95f3-06ae3a862128](https://cloud.githubusercontent.com/assets/14011498/9540807/1ba4bb0c-4d80-11e5-8520-ddb9a431e9bd.png)

**Comment by parthmistry19** [comment]
Done!!
Check out this video and update the drivers as mentioned in the video. https://youtu.be/kpUiIfAUNVU

You'll have to get adb command prompt from 
http://forum.xda-developers.com/showthread.php?t=2317790

**Comment by koush** [comment]
Did you need to run the adb command on the prompt before vysor started working?

**Comment by parthmistry19** [comment]
Yup. But that was just to check whether it shows the device connected properly and whether adb detection is there or not. One can directly install the new drivers and it will work.

**Comment by Ozibaldone** [comment]
Most of phone can't enbale PTP mode since Android 4.4.4

**Comment by koush** [comment]
I've updated Universal ADB drivers.
http://download.clockworkmod.com/test/UniversalAdbDriverSetup.msi

Please download and install, then in the start menu, go to clockworkmod -> universal adb drivers -> start adb server.

**Comment by Cludoo** [comment]
parthmistry19 - You da man. Thanks for sharing, I followed the steps in the video and its working fine now on my One Plus 1, Windows 10.

**Comment by parthmistry19** [comment]
Thanks for the appreciation Cludoo :)

**Comment by gluke** [comment]
THX I finally did it
