### ISSUE TITLE
Multiple devices connected and masking each other

### ISSUE THREAD

**Issue by campaign-block** [koush/vysor.io#220]
I got the Vysor Pro, but when i started testing could see only some of my devices. Turned out low-end chinese handsets do come with the same serial number "1234567890ABCDEF" pre-baked in their sysfs.
Now the devices seem to jump on each other's places and Vysor is not certain which device to run.
I know the issue is related to the way ADB enumerates devices. Is there a possible better way to get the devices connected to USB and not relying solely on the serial number. And i don't mean just adding the device name, because i also have identical devices( like 1:1) running different tests, so they will duplicate as well in that case. Maybe getting the IMEI from the adb shell.

I'm running Windows for this particular setup, but i know linux/macos's implementation of adb returns the USB bus identifier along the device location. Is Vysor taking that into account yet and do i try migrating to posix-like arch or rather wait?

**Comment by koush** [comment]
Oh... uh. I can't really fix this. All the ADB commands are routed through serial numbers.
