### ISSUE TITLE
Lifetime License Purchase Question

### ISSUE THREAD

**Issue by cliedwar** [koush/vysor.io#222]
Hi,
I've searched all the vysor support forums on G+, read the FAQ, and still can't find an answer to this question.

I want to purchase a lifetime license. I have an Android phone and two computers (one for work and one for fun). Will a lifetime license cover using vysor on both computers? When I upgrade or my computers, will the license transfer to those new devices? I basically want to know if I have to pay $40 or $80 to use my phone on both machines along with what happens when I upgrade equipment. I'm only asking about the lifetime license because I don't care for subscription plans.

Thanks in advance for your help!

**Comment by koush** [comment]
$40. It's linked to your google account. Not to a machine.
