### ISSUE TITLE
Device not bootable anymore after using vysor the first time!

### ISSUE THREAD

**Issue by shoutcool** [koush/vysor.io#225]
I just purchased vysor for trying it on my galaxy s6. Then i tried different settings for resolution and dpi to improve the streaming quality. Suddenly all my Icons on the mobile phone were very big and vysor showed a message like "not able to retrieve the mobile phones ui. try rebooting your phone". So i rebootet my phone and now i **cannot start it anymore!**  

The Samsung logo is showing. But then a small window says me "System UI stopped".
You just crashed my phone!! 

WTF is your crappy software doing??

**Comment by koush** [comment]
Sorry, please try to reset display settings (Defaults).

**Comment by nenti** [comment]
I have the same issue now. How can I reset my display settings? Don't tell me to reset my phone and loose all my data please.
