### ISSUE TITLE
Black screen on Mac Sierra 

### ISSUE THREAD

**Issue by sergani** [koush/vysor.io#227]
Hi there, it's been a while since I last used Vysor, and today I was unable to use it through Google Chrome. I tried reinstalling, but got the following error from Chrome:
![screen shot 2016-12-06 at 5 28 53 pm](https://cloud.githubusercontent.com/assets/16868767/20931375/8af6a452-bbd9-11e6-907d-8c41e1ae4ee5.png)
I then discovered there is a standalone Mac version, and downloaded instantly, but again I'm getting the black screen, nothing else:
![screen shot 2016-12-06 at 5 30 12 pm](https://cloud.githubusercontent.com/assets/16868767/20931414/a9423566-bbd9-11e6-8471-30c13b56e5d3.png)
To be honest, I am able to click and control the phone from Vysor, but I'm seeing nothing on the computer screen.

Is this a known bug?

I'm using a Sony Xperia Z5 Premium. Android 6.0.1.

Thanks
//M

**Comment by koush** [comment]
Read the sticky post in the support link for this issue.

**Comment by sergani** [comment]
Hi Koush, thank you very much for your feedback.
I checked the FAQ on the support link and followed all steps, still nothing works. 

Regardless, my question is this, does the standalone Mac app require anything from Google Chrome to work independently? Because basically, it's giving the black screen too. 

Thanks
//M

**Comment by yamasnax** [comment]
Hi, I have been experience same issue. Is this an existing issue? If not, appreciate if someone points me to the solution. Thanks

**Comment by ntaloventi** [comment]
is webgl still need on stand alone app?

**Comment by koush** [comment]
yeah. the app runs on electron.

**Comment by olushi** [comment]
still showing black screen. Can u please walk me through how to set up so it actually mirrors my device, this black screen is very frustrating. 

P.S. I've done everything on the support page

**Comment by aakash29** [comment]
I have been experience same issue.
