### ISSUE TITLE
wanna buy lifetime license but cannot get visor to work?

### ISSUE THREAD

**Issue by NikosEfthias** [koush/vysor.io#228]
Hi I love the idea and there are really few things like this so I wanted to buy lifetime license so I could wireless connect to my phone from my PC but I always get the error cannot install apk from vysor whenever I try to connect is there a solution to this 
I'm using ubuntu 16.4 weird thing is that this worked fine on another computer using windows

**Comment by iiPostMaster** [comment]
Last time I got the error saying it couldn't install the APK, I already had it installed. Upon uninstalling the APK and running the service again, it worked. Hope I could help!

**Comment by koush** [comment]
It's because you're running and older version of Vysor on the desktop. You may be able to trigger the update by clicking Reload. Or, uninstall the Vysor APK from Android.

**Comment by NikosEfthias** [comment]
of course i was running old version it was dec 2016
