### ISSUE TITLE
Trying out Vysor, but it won't connect with my tablet

### ISSUE THREAD

**Issue by Syl0pt** [koush/vysor.io#233]
I'm having trouble getting Vysor to recognize my device. I did everything the description said. Enabled USB debugging, installed ADB drivers, etc. But when i plug in my tablet Vysor does nothing. I can't even find the place where i can have Vysor manually finding my device." Both the computer and the tablet do nothing. The tablet tells me it's "Connected as a USB device" and "USB debugging enabled." But other than that nothing pops up.

I'm hoping this is an easy fix even though i don't see where I went wrong.

**Comment by koush** [comment]
use the support forum troubleshooting link.
