### ISSUE TITLE
Enter Key Behaves Incorrectly

### ISSUE THREAD

**Issue by seanfrisbey** [koush/vysor.io#234]
The "Enter" key puts a new line and then a space when in Google Messages.  Not only is that strange behavior for a new line, but the Enter key should send the message, right?

**Comment by koush** [comment]
Are you using custom key mappings? Can you reset your key bindings and then reopen the vysor window?

Also, is international keyboard enabled?

**Comment by seanfrisbey** [comment]
This is on a fresh install of the app, fresh install of the Chrome
extension, and I have already reset the key bindings.

**Comment by seanfrisbey** [comment]
Sorry, replying from the email was kinda gross-looking.  As for the international keyboard...my system is set to UK English, but my keyboard is in US English using GBoard.

**Comment by seanfrisbey** [comment]
If it helps, I'm on a Pixel XL running 7.1.2 beta.  Hangouts works.

**Comment by koush** [comment]
You're not using the Vysor "International Keyboard" Feature though? It is unchecked in the main window? Just trying to determine how to reproduce this issue.

**Comment by inaroom** [comment]
i can suggest, in any messaging app, when you want to send your written message just press the right arrow on your keyboard. you should see the send arrow gets selected in your text box/msg app, you can then press enter to send the message. when searching, for example in the browser adress bar, the enter key works as expected. that's the only quick fix i found for now, and i can live with it. one major issue i got though, is when disconnecting the device the input method isn't set back automatically to android keyboard, and i have to set it manually in settings>input and languages. i saw this happening only on a moto g2 with lineageos 14.1 (7.1.1 N), as i havn't got time to check other devices behavior on this issue

**Comment by seanfrisbey** [comment]
International keyboard is unchecked.

**Comment by seanfrisbey** [comment]
Koush, I can even do a screen share with you if you'd like, remotely control my computer controlling my phone, haha.  Anything to help you debug the issue (short of sending you my hardware!).

**Comment by Arvalon** [comment]
Yes, it would be good if the popular instant messengers could be configured to send messages via Ctrl+Enter for example.

**Comment by koush** [comment]
Hi all, thanks for the bug report. Please provide the following so I have detailed instructions and I'll investigate this further on my end:

```
Android Application(s) this is occurring
Host operating system (Windows, Mac, Linux)
Standalone or Chrome Vysor app
International Keyboard Enabled or Disabled
```

**Comment by koush** [comment]
I only really use hangouts, and it works fine on that.

**Comment by inaroom** [comment]
just wanted to report that now enter key works as expected in my messaging app(sms and whatsapp mainly)

**Comment by jwhipp** [comment]
I'm having this same issue.   Enter key in most apps does a return + space.

It's really annoying in Termux because I get two lines like I hit enter twice.

**Comment by koush** [comment]
@jwhipp https://github.com/koush/vysor.io/issues/211

**Comment by moobsen** [comment]
I am facing a similar (the same?) issue in Telegram. The Enter key works as expected (new line). Yet Ctrl+Enter, which should send the message, results in two new lines. Also I am using a German keyboard and Umlaute (e.g. üöä) don't work, not matter if I check international keyboard or not. But that's something else I guess.

**Comment by evilblade666** [comment]
Also facing the problem with the enter key. Did some experimentations and that's what I found out so far...
When a line "Enter": "KEYCODE_ENTER" is present - the enter key makes a new line and then a spacebar. However! in a JuiceSSH app it behaves like twice the enter key was pressed making 2 new lines on a remote shell. (or executing a command and then making a new line afterwards for that matter)
But if I remove this line ("Enter": "KEYCODE_ENTER") or change it to "Enter": "KEYCODE_DPAD_CENTER" - then the enter key makes just a space instead of a new line in most apps and to make a new line I have to press control+enter. But in this case in JuiceSSH it works just like an enter key normally should making new line or executing command or entering folder in mc, etc..
International keyboard is checked. Without it enter seems to work fine, but an on-screen keyboard always pops-out, plus I can't switch to russian.. which I need to do :)
Would be much grateful if anyone can tell me if there's a workaround to it.

**Comment by gmB2k1** [comment]
I also have the issue with the enter key in several apps.
I tried "FLAG_EDITOR_ACTION" and "KEYCODE_DPAD_CENTER" to no avail.

**Comment by bobomb** [comment]
I've got the same issue. Samsung Galaxy Note 8 using Google Keyboard. Tried FLAG_EDITOR_ACTION and KEYCODE_DPAD_CENTER to no avail.

**Comment by kimhgx** [comment]
I'm now experiencing the same issue. Samsung Galaxy Note 10+ and international keyboard feature is on. Pressing enter key on my keyboard sometimes gives a new line with one blank space, or even two new lines. All workarounds suggested above was not working.
My current workaround is removing key mapping for "Enter" and using Ctrl+Enter on my keyboard to give a new line. This is annoying a bit but at least works as I intended.

**Comment by AlbinoGeek** [comment]
For any user of this issue,

Have you tried using "Shift+Enter" to submit a message, vs "Ctrl+Enter" to add a new line?
