### ISSUE TITLE
Vysor - Able to see screen, Cannot control

### ISSUE THREAD

**Issue by mmaslati** [koush/vysor.io#236]
Hello,
I've updated my Device OS (Xioami Redmi Note 3).

After setting back to developer, enabled USB DEBUGGING and allowed "Install apps through USB", I'm able to connect and view the screen. However, I cannot control anything else.
Not the keys (volume, Home, Back ect) or the touch screen.

Tried reinstalling adb driver.
Please help...
Mor

**Comment by Venkat5694** [comment]
Hi @mmaslati ,
I own the same device and faced the above said issues.
I could get it to work by enabling USB Debugging (Security Settings) in my phone.
This is different from the usual USB debugging that you see under developer options.
This option is available right below Install via USB option in Developer Options

**Comment by mmaslati** [comment]
Fixed it! Simple as that...
You @Venkat5694  are awesome! I really appreciate the help...

**Comment by janamsoni** [comment]
thanks a lot

**Comment by giogziro95** [comment]
@Venkat5694's solution worked but I had to go through [some additional steps](https://stackoverflow.com/questions/46020237/install-app-via-usb-the-device-is-temporarily-restricted/47735264#47735264) to enable the setting because it kept saying "The device is temporarily restricted".

**Comment by hk1313** [comment]
> Hi @mmaslati ,
> I own the same device and faced the above said issues.
> I could get it to work by enabling USB Debugging (Security Settings) in my phone.
> This is different from the usual USB debugging that you see under developer options.
> This option is available right below Install via USB option in Developer Options

Very very thanks, i did try various forums for two hours.

**Comment by mochadwi** [comment]
> Hi @mmaslati ,
> I own the same device and faced the above said issues.
> I could get it to work by enabling USB Debugging (Security Settings) in my phone.
> This is different from the usual USB debugging that you see under developer options.
> This option is available right below Install via USB option in Developer Options

awesome, this is the accepted answer :D

**Comment by Hassanshin** [comment]
For me, I enable "USB Debugging (Security Settings)". In it works

**Comment by indragunawan82** [comment]
> Hi @mmaslati , I own the same device and faced the above said issues. I could get it to work by enabling USB Debugging (Security Settings) in my phone. This is different from the usual USB debugging that you see under developer options. This option is available right below Install via USB option in Developer Options

Not working for me

**Comment by chagai95** [comment]
I'm not able to see the screen, but can control it... I can only see the initial screen (not a black screen) and when I click on stuff the clicks are mapped (I can see on the phone screen) but on vysor it's stuck on the first screen I see.

**Comment by bryannbarbosa** [comment]
I have found a solution, it's not an update or a config for solving the bug, but is an alternative way to see the android screen on PC.

1. Install the app Screen Stream Mirroring on your Android.
2. Then, on Menu Local Transmission, select the option Browsers and go to screen transmission link, and it works!

**Comment by Hopekz** [comment]
Paco X3 Pro here

To add to this:
The steps in @vnktram 's solution worked for me except I had to do an additional step:
Reboot the device.

It just wouldn't work for me at all no matter what I tried until a full reboot.
Thank you!

**Comment by jovyllebermudez** [comment]
Thanks Thanks.  it worked.

> Hi @mmaslati , I own the same device and faced the above said issues. I could get it to work by enabling USB Debugging (Security Settings) in my phone. This is different from the usual USB debugging that you see under developer options. This option is available right below Install via USB option in Developer Options
