### ISSUE TITLE
Control enable, but it is Black Screen

### ISSUE THREAD

**Issue by h93910** [koush/vysor.io#237]
It is only happen of my HUAWEI P7-L00, mouse and keyboard is enable,but black screen
I try Vysor on other about 3 phones, all is well

Is there any problem with my ROM? I use the MIUI, no the original HUAWEI UI-EMUI
It is enable in my other Huawei phone of EMUI

OS: Window7 x64
Vysor:  Version 1.7.2
Device: HUAWEI P7-L00 in MIUI 
Android: 4.4.2 rooted

**Comment by h93910** [comment]
i try to screen and records
screens is work,but record File is not empty,black screen too

**Comment by koush** [comment]
Only supporting 5.0+ at this time. 4.4 may work, but usually doesn't. Only works on 4.1-4.4 Nexus devices.

**Comment by h93910** [comment]
i
