### ISSUE TITLE
Android TV Box support

### ISSUE THREAD

**Issue by clintonshanewright** [koush/vysor.io#238]
Hi Koush, I was excited about this project but then soon realised that I cannot use this to control my android TV box as it simply does not have a micro USB connector to connect with to my laptop in order to add the device to my Chrome Vysor app. So I cannot seem to connect to the device to get Vysor installed on to it, to have the device listed in my Chrome app. Is there not another way you can make this possible for Android TV boxes to be added as a device without having to connect the device to the computer via a USB cable. Please advise. Thank you

**Comment by koush** [comment]
Try adb wifi maybe. You may be out of luck though.
