### ISSUE TITLE
my screen is going black

### ISSUE THREAD

**Issue by sat63veer** [koush/vysor.io#240]
it is controlled but screen is black after restarting both device as well as  pc
windows 7 professional
![vysor](https://cloud.githubusercontent.com/assets/26871055/24607491/b7f339a8-188f-11e7-9ee2-2c4471cd7f13.png)

**Comment by kiaheyrati038** [comment]
HTC Desire 500
![capture](https://user-images.githubusercontent.com/29219050/27494020-4d2fc444-5861-11e7-8dfe-b1aa2b32744d.PNG)
