### ISSUE TITLE
This plugin is not yet supported.

### ISSUE THREAD

**Issue by noraj1337** [koush/vysor.io#243]
I successfully installed Vysor on Vivaldi browser and connected to phone via adb. I'm under ArchLinux.
The app is working I can control my phone, but I'm blind, I don't see the phone screen but can control it. Instead the message `This plugin is not yet supported.` is displayed.

**Comment by noraj1337** [comment]
Others issue may be related:

https://github.com/koush/vysor.io/issues/240
https://github.com/koush/vysor.io/issues/237

**Comment by noraj1337** [comment]
+ PC OS : Manjaro
+ Vivaldi: 1.7.735.46 (Stable channel) (64-bit) - b5bc5a3efa32f49a389ebf766e3aa3c5215b6a20
+ JavaScript : V8 5.6.329
+ Vysor :  1.7.6
+ Device : Elephone P7000
+ Android : 5.0 (kernel 3.10.61)

**Comment by koush** [comment]
Not sure what that OS is, and am not going to offer support for it. Try Ubuntu.

**Comment by noraj1337** [comment]
@koush Manjaro is an ArchLinux, I won't change my OS just for your bad software. If your software should support Linux (kernel) it should support all Linux distributions. I think you don't know what you are doing.

**Comment by noraj1337** [comment]
@koush And of course you are too quick to close issues.

**Comment by koush** [comment]
I'm the one that created this software, and you're the one here asking for free support on a distributionI don't support. But yes, I'm the one that doesn't know what I'm doing.
