### ISSUE TITLE
Greenish glitches in rendering on i.MX6 tablet

### ISSUE THREAD

**Issue by omerjerk** [koush/vysor.io#244]
Hi,

I'm using Vysor on a i.MX6 tablet. I'm getting the following output in vysor. It has Android KitKat.
![sc](http://i.imgur.com/ygvlTtc.png)

It's a developer board which we use. I've been trying to fix this issue but unable to do so. Any idea what could have been wrong?

I also wrote an Android app to stream the display to web browser and then render using BroadwayJS, same issue in that too.

Any help would be really appreciated.

**Comment by koush** [comment]
Bug in your device firmware.

**Comment by omerjerk** [comment]
@koush Thanks for your reply.

Just one more thing I would like your advice on is - do you have any idea which component in the firmware is most likely to be broken for this bug to appear? This will just give me a head start.

Thanks in advance.

**Comment by koush** [comment]
h264 encoder.

**Comment by koush** [comment]
private omx blobs. unlikely to be fixable without manufacturer help.
