### ISSUE TITLE
vysor for 64bit windows machine

### ISSUE THREAD

**Issue by ngabria** [koush/vysor.io#248]
The download executable for vysor is 32 bit. Please provide vysor for windows machine that is 64 bit.

**Comment by koush** [comment]
why does it matter?

**Comment by ngabria** [comment]
Hello Koushik, I ave a 64bit machine and this is the response I get when I
try to run the executable that i downloaded from the vysor website(which is
32 bit)

Response
[image: Inline image 1]


*Kind regards*

*Brian Nganzi Ntare*
*Health Information Systems-UG*
*Information Systems Developer **(DHIS2 implementer)*
P.O. Box 194 Kampala, Uganda
Email: bntare@hispuganda.org | ngabria@icloud.com
Tel: +256790575813

Do everything you can to make it around the system, over the system, or in
the system. – Tupac Shakur

**Comment by ngabria** [comment]
Hello Koushik, I ave a 64bit machine and this is the response I get when I try to run the executable that i downloaded from the vysor website(which is 32 bit)

Response

![vysor](https://cloud.githubusercontent.com/assets/25955335/25841253/163ddff2-34a8-11e7-9192-a6ac2665c36e.JPG)

**Comment by koush** [comment]
http://www.thewindowsclub.com/this-app-cant-run-on-your-pc

**Comment by Chaguala** [comment]
What Vysor for for win7 64bit.
Can i use Vysor with 32bit for win 64bits?
