### ISSUE TITLE
Copy & paste

### ISSUE THREAD

**Issue by anawim** [koush/vysor.io#25]
Copy & paste between computer and android device would be awesome, necessary to be really productive at work

**Comment by koush** [comment]
done

**Comment by anawim** [comment]
great

**Comment by koush** [comment]
https://www.youtube.com/watch?v=ANUGETm2Cmg&feature=youtu.be

**Comment by thebookflipper** [comment]
I can't get this to work on a Mac, copying from my device to my desktop.  Any advice?

**Comment by ColtonIdle** [comment]
I swear this used to work and it must have broke semi recently. I'm not sure if this project is dead, but it'd be perfect if I could just get that to work.

**Comment by koush** [comment]
@ColtonIdle broken from android to PC or PC to android?

**Comment by ColtonIdle** [comment]
Not working in either direction. I'm on macOS.

I looked up to see if scrcpy has the same issue and it looks like they patched an issue recently on Android 10. https://github.com/Genymobile/scrcpy/commit/8b33c6c1087a183c7e8a7d45445eb0673b50e458

Mostly just asking if this is/seems to be an issue that could still possibly be fixed. I paid for vysor but I understand that if the project has reached EOL then that's fine. Just want to know if I'm barking up the wrong tree.

**Comment by yuis-ice** [comment]
not working for non-alphabetical languages like Japanese. 

If you use third party one like Anydesk and clipboard sharing for all languages available. Actually on Airdroid, you can paste the texts instantly while remote desktop. HOWEVER, on Vysor, the clipboard sharing by third party one blocked. Since so, **I suggest "disable" feature for this feature.**

**Comment by koush** [comment]
@ColtonIdle This was fixed a few releases ago. Project is not EOL. Big update coming soon actually.

**Comment by erawhctim** [comment]
@koush I'm seeing the same issue in Vysor pro 3.0.95; copy paste doesn't work in either direction (on macOS 10.15.6, Android 10)

**Comment by koush** [comment]
@erawhctim are you using International Keyboard? Can you open a separate bug so I can get a generated bug report?

**Comment by erawhctim** [comment]
Sorry for the misleading post @koush - this issue seems to have resolved itself in the latest version? 🤔 Might be related to the device specifically.

I'll keep an eye out and report back if I experience the same issue with any sort of repeated frequency
