### ISSUE TITLE
Transfer my license to another email

### ISSUE THREAD

**Issue by gustavokeia** [koush/vysor.io#252]
Hello, is it possible to transfer my license to another email? I had to create another Google account.

**Comment by sjrawlins** [comment]
Same here.   The account I originally used to purchase Vysor has been shutdown by my G Suite administrator so I cannot get back to it.  My year subscription has not yet elapsed.

**Comment by koush** [comment]
email me at billing@vysor.io and I can transfer the sub. Will need your original emails as well.

**Comment by husyn** [comment]
I email 4 days ago and still no response. I have the same issue can you please check my case.

**Comment by drstranges** [comment]
My first email was on July 4 2019, second - 3 days ago, third - just now.
I have exactly the same case with G Suite and my account will be closed soon. Could you help me, please!
