### ISSUE TITLE
Screenshots not Saving

### ISSUE THREAD

**Issue by Grippn** [koush/vysor.io#253]
Is there a way to take multiple screenshots at once and save it to the device. I ran into the issue of taking one screenshot then going to something else and saving the first one. It saves the current screen and not what pops into my web browser. I know I can use a video but it's a lot more convenient to take a screenshot then more on to the next thing and take another one.

**Comment by drallieiv** [comment]
I have the same need, maybe the key bind can be used to reproduce the action to take a screenshot (Power + volume down on my phone) ?

**Comment by koush** [comment]
Hm, ok so you want a way to trigger device side screenshots? save to device?

**Comment by Grippn** [comment]
Since screenshot are captures of the screen at the time I press the button on vysor couldn't it also save that to a directory on my machine as well.

**Comment by koush** [comment]
@Grippn It saves immediately to your browser's download folder now (as of 1.7.9).
