### ISSUE TITLE
Vysor in a Raspberry Pi

### ISSUE THREAD

**Issue by janpolo** [koush/vysor.io#258]
Good morning!

I am trying to use Vysor in a Raspberry Pi with Raspbian. I execute Vysor with electron-chrome but when it starts it shows me a message ADB is not running. ADB is running, when I put "adb devices" shows my telephone. 

I have an USB cable DATA
I have enabled USB debug
I put my telephone in charge only

Do you know what can I do?

Thanks.

**Comment by koush** [comment]
sorry, not supporting this. if you get it working, great.

**Comment by ejmalsi** [comment]
ceck on google theres a ton of ways
