### ISSUE TITLE
Possible to connect Remix OS to Vysor?

### ISSUE THREAD

**Issue by Naturally-Delicious** [koush/vysor.io#259]
If so how?

**Comment by koush** [comment]
i have no idea what that is

**Comment by Naturally-Delicious** [comment]
It is possible, Remix os is android modified to work better with pc. I am havi g problems trying to connect, vysor says it has detected the android but i keep getting stuck at connecting.

**Comment by Naturally-Delicious** [comment]
Thanks for closing sir.
