### ISSUE TITLE
More shortcuts

### ISSUE THREAD

**Issue by anawim** [koush/vysor.io#26]
More shortcuts are needed starting with screenshot acquisition and copy and paste

**Comment by LTAcosta** [comment]
It's nice that some of the standard Android keyboard shortcuts work (Menu + _), but I agree that few more global shortcuts would be nice.

Shortcuts that would be helpful to me: Show notifications, Recent Apps, Go to App Drawer, Kill App

**Comment by koush** [comment]
can only do shortcuts that correspond to hardware/keyboard keys.

duplicate of issue:
https://github.com/koush/vysor.io/issues/21
