### ISSUE TITLE
OBS BrowserSource showing up transparent

### ISSUE THREAD

**Issue by iiPostMaster** [koush/vysor.io#263]
(I'm a paid user.) When I paste the stream link into the OBS BrowserSource window, and set the size scale to my screen's ratio, it shows up completely transparent. I've tried practically everything to solve this, even multiple solutions that don't actually have to do with my issue specifically. Nothing has worked. I need to get my YouTube video out by 7:30 PM Eastern Standard Time on Friday, July 21st, so I need this to be fixed as soon as possible. My fans expected me to post a mobile video last week as well, and they got nothing except a twitter post saying I was having some issues.

**Comment by koush** [comment]
read the manual please. you didn't set it up right.

**Comment by koush** [comment]
Use a Media Source. Not a Browser source. Check the manual. 
![vysor](https://user-images.githubusercontent.com/73924/28444498-7a0531fe-6d72-11e7-8aa4-9d4bb0f8bc12.png)

https://plus.google.com/110558071969009568835/posts/hbpfhg9CFmU
