### ISSUE TITLE
Cannot go wireless

### ISSUE THREAD

**Issue by NikosEfthias** [koush/vysor.io#268]
I click the link icon and type the local ip of my phone but cannot go wireless

**Comment by koush** [comment]
read the vysor manual.
https://plus.google.com/110558071969009568835/posts/8Ka2hG5acNu

**Comment by NikosEfthias** [comment]
![](https://i.imgur.com/R9O2rBv.png)
it gives me this unreadable half error message why have you closed the issue before it is resolved ?

**Comment by NikosEfthias** [comment]
@koush is this a bug or something ?

**Comment by koush** [comment]
Given the repro steps you provided, you were using the wrong button to go wireless. The link icon is not for wireless connectivity. It's for connecting to network devices that are already adb enabled.
