### ISSUE TITLE
Cannot go wireless

### ISSUE THREAD

**Issue by NikosEfthias** [koush/vysor.io#269]
As you ignore the other bug report and close it i reopen this issue because the bug is not solved and th only reason i purchased vysor is still not working 

This happens when i press the button you offer and i cannot even read the error message 
![](https://i.imgur.com/R9O2rBv.png)

**Comment by koush** [comment]
I need a bug report. Please use the support forum, as instructions are there on how to report issues.

**Comment by koush** [comment]
I see you already have a post there.
