### ISSUE TITLE
Forward audio

### ISSUE THREAD

**Issue by Phaestion** [koush/vysor.io#27]
Hi there

This is a bit of a feature request. Is it possible to forward the audio from the device through ADB to the Vysor app?
Does Vysor have a public repo? I would love to contribute.

**Comment by koush** [comment]
not possible to capture audio without root yet

**Comment by anawim** [comment]
wouldn't be possible to make use of BT for that?

**Comment by Phaestion** [comment]
Of course it would, but that might not be a good solution as the phone would have to connect to the PC as an audio source and the PC must then be a audio sync. It becomes an OS issue.

What may be a solution is that the chrome app handles the bluetooth connection, this could sort out the OS specific issues. The question here is, do chrome apps have a bluetooth API? Looks like it. :)

**Comment by koush** [comment]
its a bluetooth socket api. can't turn the vysor app into a bluetooth receiver using those apis.

**Comment by Phaestion** [comment]
Ah ok. Sad day. :'(

**Comment by robmonte** [comment]
@koush so is it possible to have vysor capture audio for those of us that do have root?

**Comment by koush** [comment]
@robmonte yeah, but i'm not going to build that.

**Comment by koush** [comment]
still can't due this without root, closing until its possible.

**Comment by radvansky-tomas** [comment]
But can you add this feature for rooted devices ?

**Comment by koush** [comment]
no
