### ISSUE TITLE
Any change in Mirror window cause it to slowly expand to fill the screen.

### ISSUE THREAD

**Issue by patmar74** [koush/vysor.io#271]
Using Windows 10 x64, with the windows client.

Any changes in the window size result in a very slow expansion of the window until it reaches the bottom of the screen. 
Reproduction Steps:
1) Connect to a device
2) Start mirroring the screen
3) Stretch the mirroring window a little bit
4) Observe window behavior.

**Comment by koush** [comment]
are you docked or anything?

**Comment by Barokai** [comment]
i encounter this behaviour too, 
i plugin the device via micro-usb, start vysor for windows and click on "view" - after connecting, the window keeps increasing the window size for each second until the height of the window is the displays height.

I've attached a short gif to explain it better :)
![vysorpro_window-size-increasing](https://user-images.githubusercontent.com/2293949/29530461-2bfa42d8-86a4-11e7-84c1-6508a4795db0.gif)

**Comment by koush** [comment]
is your vysor window docked against the edge of the desktop here?

**Comment by Barokai** [comment]
no, it is opened in the middle of the screen, with space above and below and left/right

**Comment by Barokai** [comment]
but maybe it is worth saying that i work on 2 displays, one fullhd with scaling 100%, the other one with 4k and scaling 150%.
But the resizing happens on both

**Comment by koush** [comment]
which device?

**Comment by Barokai** [comment]
htc one m8 with lineageos 14.1 (android 7.1.2)
but the same happend with a yotaphone 2 with android 6 too

**Comment by koush** [comment]
What resolutions are your displays using (and what scaling options?)

**Comment by koush** [comment]
I see:
1920x1080@100%
Specifically, what is the reosolution of the 4k display? (4k tends to use various values)

**Comment by Barokai** [comment]
exactly, 1920x1080@100%
and 3840x2160@150%

**Comment by sins07** [comment]
Same thing happens to me. I think it might have something to do with Nvidia drivers that were updated on August 27th

**Comment by Barokai** [comment]
I don't think this is driver related (at least not related to the version
from 27.08.), as I had the problems already more than 2 weeks ago

Am 31.08.2017 18:42 schrieb "sins07" <notifications@github.com>:

**Comment by creayt** [comment]
Same thing is happening for me, rendering it very annoying to use. I'm on 3x 4k monitors and just want to make the window not use the entire height. Whenever I do so it does the step by step expansion until it uses the full height, which is intense on a 43" monitor ( p4317q ). Device is Pixel XL 2.

Text is also blurry and responsiveness is slow despite being Pro and increasing bitrate to 3 Mb as well as connecting directly w/ a USB-C cable. If you fix this I'll be so, so happy! Thanks.

<img width="596" alt="vysorisshas" src="https://user-images.githubusercontent.com/1832685/33106807-53debe92-cef1-11e7-868a-ae698f071610.PNG">

**Comment by koush** [comment]
If anyone is still encountering this issue, please provide the following info:

Host OS
Display resolution
scaling setting

**Comment by fmikowski** [comment]
![image](https://user-images.githubusercontent.com/34735161/34245042-1b680faa-e620-11e7-819b-a3b13cec21ef.png)

**Comment by fmikowski** [comment]
I have this issue for a year now, Pro user, sometimes switching apps on the android device makes it stop, sometimes rotating the device screen makes it stop, but not always.

**Comment by fmikowski** [comment]
Also, does not happen in the Chrome Extension.

**Comment by Pileot** [comment]
I have been using Vysor pro for a long time, no problems

Today I reset my PC (rogue extensions clogging my system, easier to reset than track em down and kill em)

Fresh install of Windows. Same hardware I've always used. Same phones, same monitors. I back up all my drivers so I installed the same drivers for monitors, graphics cards, etc. Same install package for ADB.

I was using Vysor right until I reset my PC, no problems. Reinstall my PC and I'm having the same errors as above. I did download the standalone PC installer, and like fmikowski said it does not happen in the Chrome extension. 


Windows 10 Pro
Version 1709
Build 16299.125
All windows updates as of today, Jan 3 2018

Display scaling is at 150% (recommended and auto set by windows) on my main monitor (4k) and 100% on my second monitor.

**Comment by Pileot** [comment]
FIXED! (Sort of)

I uninstalled the current version and used a backup installer I had. File version 1.5.2.0 (the one I downloaded today had file version 1.8.2.0). With the older installer I no longer have any problems. 

Here is a copy of the old installer. Not sure what is causing the problem but for now this is a bandaid fix. 
https://drive.google.com/file/d/1xQQxzeNvPbq0cgvYpz31g21BIEkj-UI7/view?usp=sharing

**Comment by robaca** [comment]
Downgrading to 1.5.2 didn't help for me. It also seems to update parts of the app from the internet - the status page shows "Vysor Pro Version 1.8.3" regardless of the installed binary.

Windows 10 Pro
Pixel 2 XL
Resolution: Original
Size and density: Recommended

It starts resizing in small steps to full high immediately after connecting. After manual resizing, it starts again.

**Comment by Pileot** [comment]
You are right, after a little more playing I found the problem persisted. I ended up making myself an autoit script to resize the window to exact sizes so they didn't creep to fill my screen. A bandaid fix, hopefully this problem can be resolved soon.

Its weird, tho, because before reinstalling my PC it all worked fine. I didnt check the version of Vysor because why would I, but with the same hardware at the same settings now Im having issues. I wonder if there are any dependencies we should be installing to correct this?

**Comment by fmikowski** [comment]
This issue is here for a loooong time, I don't think there is an active development of this product anymore.

**Comment by kazthehack** [comment]
Still bugged even with the recent vysor update.
 
Window 10  64-bit Build 162999

1366 x 768

**Comment by rippi** [comment]
Same problem on Windows 10 x64 (Build 16299) with 2560x1440@125%.
Docked Android device is a OnePlus 3 with Android 8.0.0 and 1080x1920

**Comment by JAgostoni** [comment]
Same problem here.  Actually, not just happening in Vysor.  For example, in Google Play Music Desktop Player (an Electron app) when I pop-out the mini-player it does the same thing.

3840x2160 (150%)
2560x1600 (150%)

Windows 10 Enterprise 1709 (Build 16299.309)

**Comment by rippi** [comment]
I think I found a workaround: For me this problem won't occur, if i switch from hardware decoding to software decoding (which is recommended and default btw)

**Comment by jeffski13** [comment]
bump, vysor pro, win10 app, pixel 2, same problem. Stops when it hits the edge of the screen, but tries to resize slowly when in the middle of the screen
