### ISSUE TITLE
Cannot cancel subscription: none of my accounts found. 

### ISSUE THREAD

**Issue by vanyadymousky** [koush/vysor.io#274]
Please, help with subscription to vysor (2.5$/mo). Tried both of my accounts and failed. Cannot unsubscribe, while money keep leaking from my card.

**Comment by koush** [comment]
email or order number?

**Comment by vanyadymousky** [comment]
@koush dymouskyia@gmail.com or idymousky@edmunds.com, I don't remember exactly. If it does not work, can you please try to search 'dymousky'?

**Comment by koush** [comment]
Nothing matches those 3 searches. What's your first/last name on the card?

**Comment by vanyadymousky** [comment]
Hey,

It's IVAN DYMOUSKY

Thanks,


On 19 Sep 2017 8:24 a.m., "Koushik Dutta" <notifications@github.com> wrote:

Nothing matches those 3 searches. What's your first/last name on the card?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/koush/vysor.io/issues/274#issuecomment-330432889>, or mute
the thread

**Comment by koush** [comment]
I see nothing with that name either. Do you have a receipt or anything? Email me at billing@vysor.io.

**Comment by vanyadymousky** [comment]
Dear Koushik,

I've mailed to billing@vysor.io but got no response. Can you please take a
look in it?

Thanks, Ivan

**Comment by Rafael48cy** [comment]
Please help me, i cannot unsubscribe.
When i click https://billing.clockworkmod.com/ and then Manage Subscription nothing happens.

**Comment by vanyadymousky** [comment]
Hello, It's still getting happening. I'm tired for paying money for product
I don't use. I'll block my card if you won't do anything. Please, help.

**Comment by koush** [comment]
please contact billing@vysor.io for billing issues. this is a feature tracking page.

**Comment by nickstryr** [comment]
Please help! I have the same problem, I can not find the subscription on any google account.  How do I cancel?

**Comment by bionicrocky** [comment]
I am having the same issue.  No way to cancel.  I've gone ahead and registered a complaint with Google through the app store form as well.
