### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Simon-Chase** [koush/vysor.io#276]
Using the Chrome app, I selected my device. However, the window just shows this. What am I doing wrong?
![screenshot 2017-09-29 09 32 02](https://user-images.githubusercontent.com/20926909/31041087-d5c28c76-a55d-11e7-8136-158f2fd08b53.png)

**Comment by pirhof** [comment]
Same :(

**Comment by erlinux** [comment]
See this: https://plus.google.com/110558071969009568835/posts/BGUH6yojfSf

And check if Google Chrome is turning on hardware acceleration.

I opened it and switched to solve the problem.
