### ISSUE TITLE
Connection with the phone breaks occasionally

### ISSUE THREAD

**Issue by Shurasik** [koush/vysor.io#278]
Hi,

I upgraded to pro recently. Every now and then I pull up the vysor window and it shows the same "dead phone" image that you get if you were to simply unplug the phone. Here's the log: https://gist.github.com/anonymous/9f3f344402c4536547668e360e672f79

Please let me know if you need anything else from me.

Thanks!
Sasha

**Comment by koush** [comment]
I think I fixed this with an adb update.
