### ISSUE TITLE
Customise color nav bar

### ISSUE THREAD

**Issue by Sydney-o9** [koush/vysor.io#279]
Hi Team,

Great app which I have purchased.

How can one change the color of the navbar from blue to black?

![screen shot 2017-11-01 at 3 24 37 pm](https://user-images.githubusercontent.com/1480617/32260007-e9c43ba0-bf18-11e7-961d-a1cc2157f383.png)

**Comment by koush** [comment]
good idea. have also had requests to change the nav/title bar height as well.
