### ISSUE TITLE
Vysor install

### ISSUE THREAD

**Issue by pjm53** [koush/vysor.io#28]
after following install proceedure vysor fails to find my samsung galaxy s5 although it shows up in search box as galaxy
https://cloud.githubusercontent.com/assets/12208855/9490169/057c589c-4bde-11e5-89a9-75fe533c02a7.png
I'm assuming that its because vysor is still in beta

**Comment by koush** [comment]
windows 10?

**Comment by koush** [comment]
also go to PTP mode

**Comment by pjm53** [comment]
windows 8

**Comment by koush** [comment]
did you try PTP mode?

**Comment by pjm53** [comment]
I have a micro SD Card in my Galaxy s5 so i think my computer is recognising it as a media device not a camera phone.I may have to remove the SD Card to access PTP mode as i cant find an option to switch back from MTP as i have debugging mode enabled....

**Comment by koush** [comment]
windows 10 + chrome issue, reequires the latest universal adb drivers. i updated the download here:

http://koush.com/post/universal-adb-driver
