### ISSUE TITLE
can we custom map keyboard keys to type numbers when they appear on the lock screen or applock.using the mouse kind of defeats the purpose..

### ISSUE THREAD

**Issue by 02adi** [koush/vysor.io#280]
![screenshot-1509549953352](https://user-images.githubusercontent.com/33289527/32282245-1c615772-bf47-11e7-99a6-a43c2c86eac2.jpg)
i mean this lockpad..if we can then please do tell how. thanks a lot in advance. :) love vysor

**Comment by koush** [comment]
I unlock with the keyboard. If you can't on your phone, then the lock screen of your phone is set up odd.
