### ISSUE TITLE
I cannot pay for vysor  by  AliPay   in China

### ISSUE THREAD

**Issue by XiangyuShi** [koush/vysor.io#283]

**Comment by XiangyuShi** [comment]
If I choose Monthly Subscription or Annual , i cannot use AliPay.
![image](https://user-images.githubusercontent.com/18180233/32873442-14e651b0-cac7-11e7-8e0f-221fad89d1ab.png)
If I choose LifeTime ,  i can use AliPay. 
![image](https://user-images.githubusercontent.com/18180233/32873554-9b96d5ea-cac7-11e7-886d-da26bbf3b253.png)

**Comment by koush** [comment]
Alipay is no longer supported (they stopped allowing digital purchases on Stripe), I will be removing that payment option.

**Comment by XiangyuShi** [comment]
What a pity
