### ISSUE TITLE
Multitouch

### ISSUE THREAD

**Issue by ghost** [koush/vysor.io#284]
It would be really nice to be able to pinch zoom. For this some kind of multitouch input would be really useful. Is it possible to set up controls like this currently? If not, is it planned to implement it?

**Comment by hendrawd** [comment]
I need this feature as well, because I need pinch zoom an application that I use and it is very inconvenience if I should do it directly to the device every time. It will be more inconvenience if the device is far away from my place. I could do pinch zoom easily with android emulator that come from android studio by holding command key and mouse scroll.

**Comment by blackheart01** [comment]
This would be huge for me. I tried playing with the Key Bindings. I was trying to bind KEYCODE_ZOOM_OUT to the ArrowUp, but didn't work.

**Comment by Pwalex** [comment]
Bumping this again. Really really need pinch-to-zoom to be added somehow. Even a clumsy version would be better than nothing!

**Comment by JoshCraft3D** [comment]
I would also like to see this added. In other software a modifier is used for the click, like Ctrl+mouseclick, which causes the click to be multitouch. When you drag the cursor out, it drags another touch in the opposite direction, and vice versa.

**Comment by Samuel-Oliveira** [comment]
Why are you closing all issue with out a minimal response?
We Paid for this.

**Comment by Heretushi** [comment]
> 
> 
> Why are you closing all issue with out a minimal response?
> We Paid for this.

https://github.com/koush/vysor.io/issues/412#issuecomment-576904407

**Comment by RocketRider** [comment]
Are there any plans to support this?

**Comment by lhchar2** [comment]
still not able to zoom in zoom out 
google map is not able to use

**Comment by koush** [comment]
Can you all explain how you are getting multitouch through a mouse? it might be possible ,but i have no way of testing it.

**Comment by RocketRider** [comment]
It should be done like in the Android emulator. By pressing cmd/Ctrl and then keeping the left mouse pressed to zoom in and out.
https://stackoverflow.com/questions/10023554/not-able-to-pinch-zoom-on-emulator

**Comment by koush** [comment]
Ok will take a look

**Comment by Heretushi** [comment]
If I could make a suggestion, it would probably be more user friendly and less confusing to use the mouse wheel to control the zoom level. Ex.: Ctrl+Mouse Wheel up/down to zoom in/out at mouse coordinates.

**Comment by koush** [comment]
@Heretushi I very much prefer the mouse wheel to scroll up and down on a device, but that could may be turned into a configurable setting.

**Comment by Heretushi** [comment]
@koush Of course, normal mouse wheel should be binded to scrolling up and down on the device. :)

The suggestion was to use the combination of Ctrl and the mouse wheel to zoom. But anything is better than nothing in this case. No need to implement five different ways in priority. :)

**Comment by koush** [comment]
@Heretushi oh i didn't notice you said ctrlmouse. yeah that makes sense.

**Comment by MaximMikhisor** [comment]
+1

**Comment by koush** [comment]
Progress, it works with Google Photos
![Pixel_4](https://user-images.githubusercontent.com/73924/81462059-ca98f380-9164-11ea-9f7f-969a99903ee6.png)

It doesn't seem to work with Google Maps though. Unsure why.

**Comment by koush** [comment]
Released https://twitter.com/vysorapp/status/1259224506188460032
