### ISSUE TITLE
billing: no way for a user whose google account has been canceled to unsubscribe

### ISSUE THREAD

**Issue by larawarman** [koush/vysor.io#285]
I left a company where I was using Vysor. I used my company email address for auth, and a personal credit card. My company has rightfully closed my google account, but my vysor account still charges my card without a way for me to cancel. I need to cancel my account, as I don't use vysor anymore.

Why a github issue? There is no way to contact the developer via the website to get account help.

**Comment by koush** [comment]
You're at the feature tracking page. The app has links to support instructions, which also direct you to billing@vysor.io
