### ISSUE TITLE
Size and density messed up the phone display

### ISSUE THREAD

**Issue by Bingxinn** [koush/vysor.io#289]
Hi, I was playing around with the size and density and my screen on the device shrank to very tiny. However, I cannot just reset display settings. I restarted the phone and since then I've been stuck with a message "System UI has stopped". Neither can I turn on debugging because I don't see it pops up. the background is just empty. so I don't have any access to anything on the device. Can you please help me with this? Many Thanks!

**Comment by koush** [comment]
I'm removing this setting, as too many people keep ignoring the warning and playing with it.

**Comment by koush** [comment]
You'll need to hard reset.
