### ISSUE TITLE
Play Games has reverse mousewheel scrolling

### ISSUE THREAD

**Issue by oarking** [koush/vysor.io#29]
In the app and in-game achievements screen the scrolling is reversed (e.g. wheel up scrolls down).

**Comment by anawim** [comment]
that happens also in other apps like Telegram, not sure if it's a bug or a feature

**Comment by koush** [comment]
some apps seem to handle the scroll event vysor sends in reverse.... not sure why this is.

**Comment by anawim** [comment]
Ideally you should replicate the scroll by finger which is never reversed... (in my company reverse mouse input happened to us when remote connecting through VNC, solved upgrading libs, but that's another story)

**Comment by KevDoy** [comment]
@koush Not a vysor issue. Hooked up a bluetooth mouse. The Google Play Games app responds the same. Guess it's just what those devs preferred. No standard in place?

**Comment by koush** [comment]
can't fix this, it's a weird play games behavior.
