### ISSUE TITLE
how to discontinue my monthly payment?

### ISSUE THREAD

**Issue by Elen-Shan** [koush/vysor.io#290]
I have used Vysor from various colleague systems and made a one time payment to use. But I see recurring charges for all those and like to cancel all those subscriptions. Can you help?

**Comment by koush** [comment]
https://plus.google.com/u/0/110558071969009568835/posts/ZYU9dED8DPG

**Comment by Elen-Shan** [comment]
I am still seeing recurring charges in my card twice a month. can you please help me to cancel the subscription.
