### ISSUE TITLE
How can I change my email address for Vysor pro.

### ISSUE THREAD

**Issue by Neotrixsx** [koush/vysor.io#292]
Hi,
I want to change the vysor registered email address, Please help me.

**Comment by meecha** [comment]
I have the same problem,
I want to change my primary email

**Comment by meecha** [comment]
I found there is a closed issue with same problem here 
https://github.com/koush/vysor.io/issues/252

**Comment by meecha** [comment]
Hi,
It's been a while,
I already email to billing@vysor.io
but didn't get any reply from you yet.

**Comment by koush** [comment]
Hi, if you emailed billing@vysor.io the auto response talks about license transfers.
