### ISSUE TITLE
Shake gesture?

### ISSUE THREAD

**Issue by EskelCz** [koush/vysor.io#294]
Please would it be possible include a shake gesture button? It's the only thing I'm missing. React Native devs need the gesture very frequently to bring up dev tools.

Anyway, thanks for a great app! Bought Pro, great value.

**Comment by sinapcs** [comment]
I need it too

**Comment by EskelCz** [comment]
I figured out the dev tools can be opened by the 'menu' button as well, so it's not that pressing anymore. :)
Maybe there are other uses though.

**Comment by koush** [comment]
Check out the custom key bindings, basically you wanna send something like this:

```
adb shell input keyevent 82
```

**Comment by koush** [comment]
TL;DR it's possible, just with a little tweaking on your end:

https://github.com/koush/vysor.io/issues/211

**Comment by koush** [comment]
Now that i look at it, I think you can just press F1 on your keyboard.
