### ISSUE TITLE
Black Screen on OS X 10.10.5 and Nvidia Shield TV

### ISSUE THREAD

**Issue by Bboy486** [koush/vysor.io#296]
I turned on adb over wifi and installed Vysor as an app on mac. 

Vysor found my Shield and pushed the apk. 

I can connect and move using my MAC keyboard but the screen on the MAC is black. Restarted Vysor a few times. 

https://gonativeclient.appspot.com/demo/cube - doesnt load on the MAC in Chrome. 

About NaCl
Google Chrome 63.0.3239.132 () 
OS Mac OS X 

NaCl plugin /Applications/Google Chrome.app/Contents/Versions/63.0.3239.132/Google Chrome Framework.framework/Internet Plug-Ins/internal-nacl-plugin 

Portable Native Client (PNaCl) Enabled 
PNaCl translator path /Users/carmenpines/Library/Application Support/Google/Chrome/pnacl/0.57.44.2492/_platform_specific/x86_64 
PNaCl translator version 5dfe030a71ca66e72c5719ef5034c2ed24706c43 

Native Client (non-portable, outside web store) Disabled 

Chrome Hardware accel is on. 

https://gist.github.com/925977d277571a905ff43396697a3c07

**Comment by Bboy486** [comment]
Any support is appreciated

**Comment by koush** [comment]
If the cube demo doesn't work, it's an issue with your computer and/or graphics card. Not a Vysor issue.

**Comment by koush** [comment]
You'll need to sort that out yourself. My guess is the mac is too old.
