### ISSUE TITLE
Vysor is removing ADB connection

### ISSUE THREAD

**Issue by erhanbicer** [koush/vysor.io#299]
this app constantly removes my adb links. I can not access the phone again after the connection is disconnected. I lost a lot of time because of this problem.

**Comment by koush** [comment]
adb links?

**Comment by ecomaven** [comment]
I am experiencing this problem.

I installed Android Studio on my windows 10 system and Vysor stopped working as it is now seeing the adb of the Android Studio. 

I downloaded the Universal ADB Drivers you recommended and installed it.

Now what happens is that when I connect the phone Vysor initially detects it using the universal adb. However, after a few seconds it then disconnects it with the adb now changing to the Android SDK version

**Comment by erhanbicer** [comment]
@ecomaven Try 'scrcpy' application both free and more beautiful.

**Comment by HaiLe** [comment]
i am seeing the same issue, has this been resolved?

**Comment by blazegawlikamc** [comment]
I had this issue as well after updating Android Studio. I had to uninstall and stop using Vysor. I noticed the issue when I couldn't install an APK to Fire TV using ADB.

Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by ecomaven** [comment]
Hi, I think have figured out what why the Vysor adb connection kept getting disconnected.

I was going through my PC task manager and discovered that a different adb.exe was persistently running. I noticed it was linked to the Sync Software of my HTC phone. I uninstalled the HTC Sync Software entirely and boom! Vysor now connects instantly without issues. 

Hope this helps...

**Comment by plapic** [comment]
Searching contact addresses from your phonebook in AA
![screendump - 2023-04-19-13_08_37](https://user-images.githubusercontent.com/45576029/234691102-21307ffa-c62e-4ab9-9d62-b458df95f29d.png)

The first result is from my phonebook. The second result is from google places. 
![screendump - 2023-04-19-13_06_54](https://user-images.githubusercontent.com/45576029/234691472-9cc4a146-b0c3-4ea5-a0c7-c009d6510aff.png)

Waze doesn't seem to recognise GPS addresses from contacts in your phonebook 
![screendump - 2023-04-19-13_07_32](https://user-images.githubusercontent.com/45576029/234692116-77c6596f-f459-49f4-8438-17bf6c37d640.png)

Of course from Google places works fine.
![screendump - 2023-04-19-13_07_57](https://user-images.githubusercontent.com/45576029/234692341-9cc7adb3-94a5-4eb8-a898-d3dc0049ef58.png)

The problem occurs with any phonebook contact addresses.
