### ISSUE TITLE
Enable WebGL: graphics are distorted, or super slow

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#3]
![proxy](https://cloud.githubusercontent.com/assets/73924/9463305/bd04cfb2-4ad0-11e5-8696-f94d088907f5.png)

**Comment by koush** [comment]
Make sure chrome is using hardware accelerated webgl.
http://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu/299346#299346

**Comment by koush** [comment]
chrome command line args can also forcibly disable it.
 Check chrome://gpu
https://twitter.com/gm3d2/status/636091247204003840

**Comment by The-MAZZTer** [comment]
Some of us do not have the option to use WebGL (eg work PC which has it disabled via group policy). It would be nice to have a fallback.

**Comment by koush** [comment]
@The-MAZZTer The software fallback is ridiculous slow.

**Comment by The-MAZZTer** [comment]
I was afraid of that. Ah, well.

**Comment by anawim** [comment]
experiencing artifacts when fast scrolling with mouse wheel like Telegram chats or others.
My chrome://gpu/ shows everything is hw accelerated but it also reports this strange (to me) messages

Log Messages
[10440:12648:0826/095717:ERROR:gl_surface_egl.cc(485)] : eglInitialize D3D11 failed with error UNKNOWN, trying next display type
[7136:11148:0826/095925:ERROR:gl_surface_egl.cc(485)] : eglInitialize D3D11 failed with error UNKNOWN, trying next display type
GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.

**Comment by LootenPlunder** [comment]
I have 1.0.4.0 installed and webgl enabled but the video is still 5-10 seconds behind what's happening on the local screen. Comp is an i7-3630QM laptop with nvidia 650M, intel graphics are disabled (no optimus). Phone is moto x 2013 (xt1053) with 5.1

**Comment by koush** [comment]
fixed with warning notification if webgl is busted.

**Comment by djfdat** [comment]
Try enabling chrome://flags/#enable-webgl-draft-extensions. That seemed to work for me.

**Comment by anawim** [comment]
Any appreciable performance gain?

**Comment by lukehutch** [comment]
With WebGL disabled, the pixels are all there, just tiled wrong. What about getting the pixels tiled correctly requires WebGL? (I have to disable WebGL on Linux due to a Chrome bug.)

**Comment by GCTWorks** [comment]
I am having the same problem as The-MAZZTer above.  The policy is set to:
 chrome://policy/ - Disable3DAPIs

**Comment by MiaShopgal** [comment]
Version 45.0.2454.93 (64-bit) isn't working 
Chrome Canary 47.0.2509.0 canary (64-bit) is working

**Comment by Aravind-Rajendran** [comment]
not working for me.please help

**Comment by yelzoghby** [comment]
Vysor is repeating device screen on desktop, so I could not recognize how to work?

**Comment by yelzoghby** [comment]
![vysor](https://cloud.githubusercontent.com/assets/15964850/11322842/08714a8a-9107-11e5-9e28-0c72cdc613fe.jpg)

as attached
device screen is too small and repeated .... kindly help me to fix

**Comment by toseefawan** [comment]
device screen is repeated and too small here on windows 10.
![snap2](https://cloud.githubusercontent.com/assets/10118302/11325053/7da81214-913b-11e5-91b2-4b105abda43b.PNG)

**Comment by dr2009** [comment]
enable hardware acceleration
not WebGL

**Comment by kizer8** [comment]
I am running google chrome v48 64-bit, I have to enable hardware acceleration to get vysor to work and not be distorted, but then website streaming videos do not play.  To get the videos to play I have to disable hardware acceleration, but then vysor does not work.  Any ideas how to get both working?

**Comment by henti** [comment]
I'm having a similar issue, but mine seems to be that something stops working. I have to restart chrome completely and it starts working again. restarting vysor does not work. It seems to break when I unplug USB while connected to vysor.

**Comment by dshope44** [comment]
Has anyone made any progress on the repeated device screen issue (noted above by yelzoghby and toseefawan)?  I cannot seem to get around it, and have tried the suggestions I see above.  I have Chrome 49.0.2623.112.  Can anyone confirm what steps resolve this? 
![p](https://cloud.githubusercontent.com/assets/18617855/14746730/f9e9b174-087e-11e6-93ec-14ee3e48a3b6.png)

**Comment by diegobill** [comment]
Same problem :+1:

**Comment by MiaShopgal** [comment]
try Chrome Canary

**Comment by Parrou** [comment]
I fix this Problem by activating the "**Use hardware acceleration when available**"

![01](https://cloud.githubusercontent.com/assets/9146991/15003818/d86c458e-11a7-11e6-8225-f29364895f40.png)

![02](https://cloud.githubusercontent.com/assets/9146991/15003822/de567f3c-11a7-11e6-8e46-087028615d2c.png)

![03](https://cloud.githubusercontent.com/assets/9146991/15003824/e48971b6-11a7-11e6-84f6-fa3cf63ea422.png)
