### ISSUE TITLE
Japanese input not working through keyboard

### ISSUE THREAD

**Issue by jpuser123** [koush/vysor.io#302]
After the most recent update, Japanese input does not work through the keyboard any more. (Using Google Japanese Input from the Play Store.) 

When trying to type in alphabet (for example susi to type sushi), it doesn't output sushi (すし) in Japanese but instead moyumute (もゆもて). It seems like now each keyboard key is assigned to one hiragana character instead of the previous romaji input.

**Comment by koush** [comment]
try using the international keyboard option in the vysor desktop where you select/view the device.
