### ISSUE TITLE
LG E610 Black screen (dead-mac.png) problem

### ISSUE THREAD

**Issue by LukaszCzerwinski** [koush/vysor.io#304]
Hello,

I have the Vysor Pro and I need connect to my LG E610. I  installed the ADB Drivers, but I still can't see my phone screen (it showing deed-mac.png). However, I can upload files by Drag&Drop. When I try to make a screenshot then Chrome open 127.0.0.1 with HTTP ERROR 404.

**System info:**

- [ ] Windows 10 (64bit), NVIDIA QADRO K610M. 
- [ ] Chrome 64.0.3282.186.
- [ ] Android 4.1.2.

I attached screenshots below. How fix it? 
![screenshot_1](https://user-images.githubusercontent.com/3521742/36901323-110c6eea-1e27-11e8-9284-3e73e70185a6.png)
![screenshot_4](https://user-images.githubusercontent.com/3521742/36901325-1128061e-1e27-11e8-9965-47e1a5fe3843.png)
![screenshot_3](https://user-images.githubusercontent.com/3521742/36901326-114527ee-1e27-11e8-8c52-7d64a41b3c3e.png)
![screenshot_2](https://user-images.githubusercontent.com/3521742/36901327-115efd0e-1e27-11e8-9471-b16b2c0ee85a.png)

**Comment by FlickerSoul** [comment]
I have the same problem. Have you solved the problem yet? 
I tried two devices, and one of them are able to connect while another one is not.
