### ISSUE TITLE
Fullscreen do not work in Linux

### ISSUE THREAD

**Issue by fastslack** [koush/vysor.io#305]
Linux Ubuntu Server Xenial
Version 61.0.3163.79 (Official Build) (64-bit)
Vysor Pro Version 1.8.4

When i press on fullscreen button, it return a message saying "Fullscreen must to be enabled in settings". 

Please help.

**Comment by laloch** [comment]
I can confirm the issue in Chrome 67.0.3393.4 (Official Build) dev (64-bit) running on Arch Linux.

**Comment by Rokemon** [comment]
Issue still exists.

On Ubuntu 16.04.02 LTS.

A prompt response would be appreciated

**Comment by mtcporto** [comment]
same here.

Ubuntu 18.10 (64-bit)
Vysor Pro 2.0.8

When i press on fullscreen button, it return a message saying "Fullscreen must to be enabled in settings".

**Comment by junebug12851** [comment]
I have Windows 10 and Vysor says that, a lot of stuff doesn't work in Vysor for me. audio doesn't work and keeps bringing up Chromecast Home App over any work I'm doing, and bottom portion is always cut off even after removing navigation bar causing me to have to manually re-size it.

But yea the fullscreen is among them that does the same thing others on here mention which is "Fullscreen must to be enabled in settings" message.

Really theres not much I can do in vysor correctly and the app half works but I'd love to see it fully work one day.

**Comment by Maxence** [comment]
Same here, fullscreen don't work.
Any chance to get some news about it ?
