### ISSUE TITLE
the screen is zoomed in and i cant do any thing

### ISSUE THREAD

**Issue by shirboman** [koush/vysor.io#306]
in this you will see the issue i cant fix it
so i cant edit or do any thing completely stuck with this
![mob1](https://user-images.githubusercontent.com/22734419/37304204-99735356-2639-11e8-9b7b-d672fdd025de.png)
![mob 2](https://user-images.githubusercontent.com/22734419/37304234-ab3ce156-2639-11e8-8cb9-1941ab36141e.png)

bug error
https://gist.github.com/86dc0258bf525e9291227465024f023f

**Comment by Alb305** [comment]
Did you find a fix?...I'm dealing with the same problem

**Comment by Alb305** [comment]
Were you able to find a solution

**Comment by woojoo666** [comment]
why is this issue closed without any details?

**Comment by RegisStGelais** [comment]
The dev closed all issues without any explanations and is not answering messages.

**Comment by woojoo666** [comment]
for anybody else who gets here, I found a solution: use `adb shell wm density 480` to manually set the screen resolution to 480, which should help. I found that setting even lower values, like `360`, made it zoom out even further.

**Comment by woojoo666** [comment]
I also recommend checking out [scrcpy](https://github.com/Genymobile/scrcpy), a free and open-source software that does everything Vysor does, and the devs are a lot more helpful (they guided me to the `adb shell wm density 480` solution)
