### ISSUE TITLE
Chrome - instalation not possible - WebGL is not enabled

### ISSUE THREAD

**Issue by senpl** [koush/vysor.io#308]
In current version of chrome (Version 65.0.3325.146 (Official Build) (64-bit) on Ubuntu 16.04.
I try installing app from https://chrome.google.com/webstore/detail/vysor/gidgenkbbabolejbgbpnhbimgjbffefm
it says WebGL is not supported. Is there any simple method to make it work?
I tried turn on WebGL Draft Extensions in chrome://flags/ but this not solve that issue.

**Comment by kszicsillag** [comment]
Try enable "Override software rendering list" in chrome://flags/

**Comment by senpl** [comment]
Thanks, not it works for me.

**Comment by arya6000** [comment]
when I  enable "Override software rendering list" Chrome won't let me install Vysor anymore. Chrome will say "Not Compatible" "This application is not supported on this computer. Installation has been disabled. The following problems are detected:
This app uses 3D graphics and needs WebGL"

**Comment by hacker20182019** [comment]
If enabling "override software rendering list" in chrome://flags/ does not work then disable it again and try enabling "hardware acceleration" from Google Chrome's settings. That was what fixed it for me.

**Comment by atuldpatil** [comment]
Inspite of turning all WebGL related options in Chrome as mentioned in video, I was still getting "WebGL is not supported" when I was trying to add extension Vysor. Finally I chosen to go https://app.vysor.io/ and  then click on CONNECT USB DEVICE (make sure you connected Android phone with Usb Debugging on). This worked like charm!!! Now I can see device screen in Chrome tab. (Adding extension and launching Desktop application of Vysor, both are still not working on my PC)
