### ISSUE TITLE
Remove screen timeout option

### ISSUE THREAD

**Issue by Lenadar** [koush/vysor.io#313]
I've seen this on another similar system to vysor (though I ultimately find Vysor much much better).  When connected to your phone, give vysor an option to override the screen timeout on your phone (or create some small action to simulate constant activity to your phone).  It's a great product but I wish I didn't have to keep unlocking my phone or remove unlocking just so I can use it without having to unlock manually for the day.

**Comment by 7starsone** [comment]
right... at the moment you need to "Find devices" again and reconnect....it's boring and a waste of time. Hope they fix it soon

**Comment by 7starsone** [comment]
unless this is an issue with the chrome plugin...I still need to try the desktop app...will do it

**Comment by DragShot** [comment]
You can always go to Developer options and check "Keep active - the screen will never be left inactive while the device is charging". That works for me.
