### ISSUE TITLE
How to hide title bar

### ISSUE THREAD

**Issue by sethlanss** [koush/vysor.io#319]
Hello guys

I wanted to know how to modify the settings in order to hide the title bar, I use vysor with games in my cellphone, and its kinda annoying that every time i switch screens, you get the blue title bar in the screen, I need to wait until it goes to click on something within the game. If I pin the title bar, its a workaround solution, but Ill rather to hide it as I don't really use any of the functions in here.

**Comment by syedrakib** [comment]
Using vysor on mac. I went to settings and UNCHECKED the "Pin title bar" checkbox. Problem is, now i can't find the title bar at all. Is keeping the title bar "pinned" the **ONLY** way to use the title bar?
