### ISSUE TITLE
Unable to connect to phone, No Serial Number

### ISSUE THREAD

**Issue by Cludoo** [koush/vysor.io#32]
Having issues getting Vysor to work with my OnePlus One (Android Version 5.0.2)

I've enabled ADB on my phone, I've also made sure the device is in PTP mode (I have also tried MTP) nothing seems to work.
![image](https://cloud.githubusercontent.com/assets/13994855/9515408/f50bd4c8-4cd3-11e5-95f3-06ae3a862128.png)

Once I select the device it does nothing. 
I'm using Windows 10, with ADB Drivers (also tried on a 2nd personal PC with no luck, Windows 7)
Thanks.

**Comment by TheWint** [comment]
I have the same issue with my Xiaomi Mi4w
![capture](https://cloud.githubusercontent.com/assets/13995423/9516136/574f3352-4caf-11e5-8300-4789545b9d38.JPG)

**Comment by Cludoo** [comment]
Somebody found a fix, which worked for me. Follow this video;
https://youtu.be/kpUiIfAUNVU

You'll have to get adb command prompt from 
http://forum.xda-developers.com/showthread.php?t=2317790
