### ISSUE TITLE
Zoom support

### ISSUE THREAD

**Issue by goamn** [koush/vysor.io#322]
Hi, I use Vysor on a daily basis and I was wondering if it's possible to zoom in and out?

**Comment by Pwalex** [comment]
I want to add a voice to this request. I purchased the app and use it almost daily, but the lack of ability to pinch-to-zoom is driving me crazy!

**Comment by iaankrynauw** [comment]
third this.

**Comment by RomualdLewandoski** [comment]
For the people how read this because they can't zoom:
Alt + left click allow you to enter multitouch (you can now zoom by pinch)
Alt + left click again to disable multitouch

**Comment by redreinard** [comment]
> For the people how read this because they can't zoom:
> Alt + left click allow you to enter multitouch (you can now zoom by pinch)
> Alt + left click again to disable multitouch

Can I get some clarification on that? When I Alt + left click, i get a red dot... now what? 

Can we just get some simple pinch zoom in/out like by holding alt and scrolling the mouse wheel?

**Comment by nerlins** [comment]
This is not a proper solution. If the developer thinks it is, then more information needs to be provided on how this is supposed to be used. Pressing Alt + left click only leaves a red target, and I have no idea how to make the Zoom function work. I have paid for Vysor, so I feel I am in my right to request further information and support on this topic.

**Comment by koush** [comment]
use the alt click to "plant" a finger.
use the mouse to simulate movement with a second finger.

**Comment by redreinard** [comment]
> use the alt click to "plant" a finger. use the mouse to simulate movement with a second finger.

Unfortunately absolutely nothing happens when I move the mouse after planting the red dot "finger".

**Comment by nerlins** [comment]
> use the alt click to "plant" a finger. use the mouse to simulate movement with a second finger.

Just like @redreinard, this does nothing for me.

**Comment by mruac** [comment]
> use the alt click to "plant" a finger. use the mouse to simulate movement with a second finger.

Same, either more support is needed, there is something wrong, or I am doing something wrong.


https://user-images.githubusercontent.com/19784752/206657087-4a91fe29-d948-40c2-8694-5097e1a9d35c.mp4

**Comment by HoundDogTech** [comment]
I still can't figure this out? Any chance we can get more support on this? 

I'm Vysor Pro, I rarely go premium but wanted to support your work since I was using Vysor for years prior so I paid for it to support, never needed help but this is the one rare time I'm reaching out for assistance
