### ISSUE TITLE
vysor for 64bit windows machine

### ISSUE THREAD

**Issue by thehutgy3** [koush/vysor.io#324]
You closed https://github.com/koush/vysor.io/issues/248 and your reply is to go over and read http://www.thewindowsclub.com/this-app-cant-run-on-your-pc

But does not work, I am using PRO version and does not even work on windows 7 64bit machine.

I have no choice but to use 32bit old laptop and it really Sucks, I hope you have solution for win64 win7 because I paid for the PRO version

**Comment by LafinJack** [comment]
My Vysors are also 32 bit. Vysor Pro v 1.9.1, OS Name Microsoft Windows 10 Pro, Version: 10.0.15063 Build 15063

**Comment by LafinJack** [comment]
?
