### ISSUE TITLE
International Keyboard is not working on Android

### ISSUE THREAD

**Issue by byzheng** [koush/vysor.io#327]
I am using the latest version Vysor 1.9.1 on Windows 7 and Huawei P10 (Android version 8.0.0).

When the International Keyboard is enabled, the phone switches to Vysor keyboard, but doesn't accept any typing for my keyboard in the laptop.

**Comment by HiCubee** [comment]
mee too

**Comment by rkachach** [comment]
Same here with vysor 2.4.1 .. no way to get the keyboard working

**Comment by z226** [comment]
Same with me, the backspace work but the letters don't

**Comment by airstarh** [comment]
I confirm.
After a connection and disconnection  Android's keyboard has stopped appear. Reload helps. Today it interrupted me to call taxi. What if I need an ambulance? Please, fix it or let us know a way for a workaround.
Win 10/ Xiaomi Mi 5 + MUI 10
Thanks!
