### ISSUE TITLE
Fails to connect on Linux

### ISSUE THREAD

**Issue by indivisible** [koush/vysor.io#33]
Fails to connect on 64 bit Debian. Phone is Lenovo S750 with 4.2.2. adb connection works from the command line and the phone is switched to PTP mode. Phone shows in the "Find devices" list, but the error pops up as soon as I click "Select."

Is there any way to get more information on how it failed?

**Comment by koush** [comment]
requires android 4.4+

**Comment by pegordo** [comment]
I have a 4.4.2 and I'm also having problems.
Everything seems to work fine expect vysor's window keeps showing "the wheel".
How can I get some logs or debug info to help?

**Comment by koush** [comment]
If you open up chrome://extensions

enable developer mode

then click the background page and screen.html and get me the logs.

@pegordo open a different issue please, with the aforementioned information.

**Comment by koush** [comment]
should be fixed
