### ISSUE TITLE
GUI For key mapping to on screen buttons

### ISSUE THREAD

**Issue by tsgsOFFICIAL** [koush/vysor.io#336]
I have no idea how to map my asdw keys to move around in games but I would love to be able to still edit them. I think there should be an easy to use GUI with little anchor points to set the different keys to press different places on the screen !

**Comment by tsgsOFFICIAL** [comment]
@koush

**Comment by Kuntal-Das** [comment]
yes I wanna do that too as i can't find the "KeyEvent_String" or "Android_Event_Object" or "Vysor_Event_String" for any in game controls.
Key-map Profiling could be a great addition ( Like key-maps for different apps which can be switched by the user )

**Comment by songoten28** [comment]
I think this keymapping not enough for game. E.x PUGB . Because you need turn around or turn left, turn right by move mouse.

**Comment by rjbeswin** [comment]
Hoping this would be implemented. Im playing Marvels Future Fight and found out that WASDE keys are for my skills.
