### ISSUE TITLE
Vysor Screen Freezes, then Resumes upon Click

### ISSUE THREAD

**Issue by tudousimu** [koush/vysor.io#337]
I am experiencing the same issue as the following:

https://github.com/koush/vysor.io/issues/127

I would like to reopen the issue if possible, or any other way of bringing it to attention. Thanks!

**Comment by Zunfire** [comment]
Have that issue as well..

**Comment by MADV360** [comment]
The same thing

**Comment by saurabove** [comment]
Having same issue, makes the app unusable

**Comment by Bratpitt** [comment]
Have had this issue long as i can remember, solved it with script that keeps reactivate the window but its not a good solution and give me other problems when trying to use other windows!

Would like to see it been solved.
Am using the window vysor app and W10.

**Comment by koush** [comment]
Is this on a USB or Wifi connection?

My guess is that the device falls asleep, and stops sending data over. Clicking the window sends a wake event to the device. You could try enabling "keep device awake while charging" option that's hidden somewhere in Android's settings.

**Comment by Bratpitt** [comment]
Its on USB, had forgotten about that option, had tested it before, but i did try it again now and unfortunately it didn't solve the issue. 

But it is like you write, it feels like "device falls asleep, and stops sending data"

**Comment by koush** [comment]
The screen on while charging did not work? I'll see if there's a network wake lock I need to use.

**Comment by koush** [comment]
Can you try the new progressive web app beta here:
https://app.vysor.io
I want to verify this is fixed.

Native apps coming soon.

**Comment by koush** [comment]
Closing cause I think this is fixed. Please open another bug if this continues to be an issue.
