### ISSUE TITLE
Black screen in a particular mobile, Screenshots work.

### ISSUE THREAD

**Issue by ExTaCy1337** [koush/vysor.io#344]
Hello guys!
One of my devices has a Black Screen, my other device (Xiaomi redmi note 3) Works perfectly!
Screenshots also work perfectly!
So it is the Phone problem.
Problem is I use vysor because the screen in this phone is dead too!
Is there any fix? Maybe some setting in the phone? Or maybe an old Vysor version?
Tried everything on the Black Screen Issues in the google+, and as I said my main phone works perfectly.

Windows 10
Radeon 18.5.1
Turbo-X Pi
Android 4.3
Vysor 1.9.5
No root
https://gist.github.com/VysorLogs/fb19493a9cc2775d1c00757ceb725d30

**Comment by senpl** [comment]
Same here. 
Ubuntu 18.04 
Huawei P8 Lite / Android 6
Vysor 2.0.9
No root
