### ISSUE TITLE
Support remote adb host capabilities

### ISSUE THREAD

**Issue by odexcide** [koush/vysor.io#35]
If possible, add support for specifying the -H <host> option for adb. This feature was available for ChromeADB but seems to be hidden or omitted from Vysor.

**Comment by koush** [comment]
I'm not clear what that does?

**Comment by odexcide** [comment]
A command line option for adb is -H which allows you to specify the hostname/ip of the adb server host (default: localhost). On your version of ChromeADB before there was an option on the top right corner to change the host or port to connect to. This way Vysor can connect to a remote host running adb that has devices connected to it.

http://androidxref.com/5.1.1_r6/xref/system/core/adb/commandline.c#101

**Comment by koush** [comment]
Oh, ChromeADB isn't my app. I build ADB for Chrome. I understand what -H is now, forgot about that.

**Comment by mirwin90** [comment]
This functionality really does need to be added.
