### ISSUE TITLE
APK error when switching to wireless

### ISSUE THREAD

**Issue by polymathmath** [koush/vysor.io#351]
I can successfully connect via USB, but switching to wireless gives me an 'Error Installing APK:' message.

Running Vysor Pro Version 2.0.0 with an Oculus Go

![screen shot 2018-09-26 at 6 32 19 pm](https://user-images.githubusercontent.com/43626970/46118264-87ba2000-c1ba-11e8-8aa9-4ff5e897c9c8.jpg)

**Comment by wendyk2015** [comment]
I am running into the same error as well.  

Running Vysor Pro version 2.0.6 on a Pixel 2, Android version 9

**Comment by hydrazine1209** [comment]
Same here. any updates about this problem?
