### ISSUE TITLE
An error occurred while connecting to the Android device.

### ISSUE THREAD

**Issue by pkkid** [koush/vysor.io#352]
I am able to open Vysor in Chrome and it does see my device in the list. However, upon trying to connect I get the message `An error occurred while connecting to the Android device`.

Ubuntu 18.04
Google Pixel 2XL running Android P

**Comment by pkkid** [comment]
I was able to get this working. Even though I already had USB debugging enabled on my phone, I also had to change the USB Preferences from "Charging this Device" to "File Transfer".

**Comment by pzanco** [comment]
Xiaomi Redmi Note 5 - you need to change "Select USB Configuration" option to MTP (Media Transfer Protocol)

**Comment by lusweti-david** [comment]
Still getting the same error

**Comment by bilal811** [comment]
still getting the same error

**Comment by Izdhar** [comment]
i had the same error ? what do
 i work now??

**Comment by koush** [comment]
https://vysor.io/download and download the desktop version.

**Comment by inialdan** [comment]
Have you try to chek Developer Options on Debugging?, make sure Install via USB and USB debugging (Security settings) is enabled
