### ISSUE TITLE
Audio mirroring not working

### ISSUE THREAD

**Issue by Guernegor** [koush/vysor.io#354]
Hello,
When I click on the headphone icon, the oculus browser goes to the Google Home install page. Why is that?
Kind regards,

**Comment by yulolimum** [comment]
Same issue, different context. 
Using Android 9, clicking on the headphone icon goes to the Google Home install page. After installing Google Home and clicking on the headphone icon, Google Home opens and that's it.

**Comment by gui-balde** [comment]
I could make it work with the following steps:
1- Make sure you have the Cast option available from your quick-settings panel; in the notifications curtain
2- click on the audio mirror option on the Vysor app
3- Now quickly pull down the notification curtain and click on 'Cast'
4- You should find a 'Vysor audio output' or similar - just click on it.

That's it. There's a good 5 seconds lag though, and there's a light crackling in the streamed audio.

**Comment by sjrawlins** [comment]
Interesting feature, but I could not get it to work on an Android Nougat 7.2 device.    Following the helpful directions given by gui-balde, I was able to Cast to Vysor ("Vysor Audio Output" appeared as an option on the Cast Setting)

But the Cast could not function properly.  I had the device plugged-in to my laptop via USB cable, but the audio was terribly garbled.  The feature did, indeed, silence the Android handheld device, but the resultant quality on my Win10 PC was choppy and indecipherable, like a barrel of chipmunks.

**Comment by koush** [comment]
I've basically rewritten the audio mirroring to fix implementation issues. Please try again.

There's still some outstanding bugs around automating the Google Home casting (so vysor can capture the audio). If it doesn't automate properly after clicking the headphone button, you have around 20 seconds to open google home, and mirror the audio output to "Vysor Audio Capture".

**Comment by angad305** [comment]
audio casting still doesnt work on mac

**Comment by SkilledAlpaca** [comment]
Still unable to cast on Android 9.0 using desktop app on Windows 10. It brings up the Google Home screen and acts like it wants to cast but the app doesn't cast.

**Comment by atsoares** [comment]
Just bought the pro version and I can't figure out how to use the mirror audio function. PLEASE, someone help! I tried the cast option with google home as you guys said but I keep getting the "Vysor Audio Accessibility is not running. Please ensure its enable." it asks also to restart my phone.

**Comment by shaynem** [comment]
<img width="430" alt="vysor-block-android-q" src="https://user-images.githubusercontent.com/118681/56939895-75d49d00-6b4e-11e9-8b7b-ebcd712c0439.png">

Unable to get this to work on Mac with Android Q or 9

The above error comes up after trying to turn on Audio casting from within the Visor application

**Comment by mlodziaszka** [comment]
Xiaomi mi 9, Android 9

I also have a problem with audio casting. It seems that Google Home finds audio device, but instantly after connection I'm getting this message:

"Casting screen to Vysor Audio Output has ended."

... and it disconnect.

**Comment by r3tr013** [comment]
You need to go to your account page on GOOGLE HOME and scroll down until you find "Mirror device" a window will open up then press cast video/audio, and it will fix the audio problem.
![sdf](https://user-images.githubusercontent.com/50875578/58101311-16ffc200-7be8-11e9-9d95-cfae93d43a6d.png)

**Comment by gdmtplays** [comment]
I don't see that option for me. The Google home settings page. Huawei P30 Pro EMUI 9.1 and audio cast ain't working as well. Tried both Mac and windows and nothing. It shows nothing upon pressing the button in the app.

**Comment by NirBY** [comment]
Very Nice feature - tested with SM-J600G successfully.
There are several issues with this feature:
1. Microphone is not working - also try https://support.google.com/chromecast/answer/6279392?hl=en
2. Call Audio is not transferred.

**Comment by callum09** [comment]
My samsung s10+ plus is connects succesfully when attempting to mirror the devices audio via google home to "Vysor Audio Output" - however I'm picking up no sound on from the desktop app on my windows 10 laptop.

**Comment by sumanapearl** [comment]
Hi ...I am also facing same issue as that of callm09... Sound is not getting recorded...please resolve

**Comment by otidh** [comment]
> You need to go to your account page on GOOGLE HOME and scroll down until you find "Mirror device" a window will open up then press cast video/audio, and it will fix the audio problem.
> ![sdf](https://user-images.githubusercontent.com/50875578/58101311-16ffc200-7be8-11e9-9d95-cfae93d43a6d.png)

Thanks! This solution works for me. Tested on Google Pixel - Android 9 and MacOS.

**Comment by ToxicXender** [comment]
So it seems that Audio Casting Only works for the browser version of Vysor, the Windows Standalone version just disconnects after 2 seconds of being connected! That is really an annoying problem,

**Comment by PreciseAsteroid** [comment]
what's the purpose of the headphones icon? when I click on it I am redirected to the google home app on the tablet, but I find there no "mirror device" option. 
BTW, I am using a Mac.
Can you please provide a step by step instructions ?

**Comment by ari1010** [comment]
It just doesn't work. I'm using windows and it's very frustrating as mirroring both screen and audio was what I need.

**Comment by FargenDog** [comment]
Can't connect via WiFi and audio casting isn't working in Google Home.  Can't seem to find any support contact info either.  After spending hours online trying to figure this out it looks like quite a few people are having issues....

**Comment by EliasRanz** [comment]
So this took me a bit to resolve, but here's the process that I took to get it working...

1. **Make sure your computer is on the same wifi as your phone** -> chromecast works over wifi on the same connection, if you're not connected to the same wifi then you won't be able to discover the `Vysor Audio Output` device. 

2. Make sure that you have the `Screen Cast` button on your quick settings panel. If you don't have it then click on the pencil icon, locate `Screen Cast` and then tap/hold the icon and drag it to one of the top 9 items (that'll make it so you can just expand it and have the ability to select it quickly.
<img src="https://user-images.githubusercontent.com/1493142/71908750-9375ef80-313c-11ea-8f3e-1354823cbfc8.png" width="300"/>

3. If you click on `Screen Cast` now you should start searching for devices, but it won't immediately appear, this is fine...
<img src="https://user-images.githubusercontent.com/1493142/71909441-0fbd0280-313e-11ea-8df7-4706cb10f1db.png" width="300"/>

4. click on the headphone icon on the Vysor app running on your computer.

![image](https://user-images.githubusercontent.com/1493142/71909647-70e4d600-313e-11ea-9c6e-4a3a8cbffe53.png)

5. Now you should see Vysor come into the picture...
<img src="https://user-images.githubusercontent.com/1493142/71909865-d769f400-313e-11ea-9b15-db870d336c3f.png" width="300"/>

6. Clicking on the `Vysor Audio Output` should result in a popup mentioning data exposed during casting., you should be able to just select `Start now`.
<img src="https://user-images.githubusercontent.com/1493142/71910041-2879e800-313f-11ea-9784-1517aaaef9c8.png" width="300"/>

7. If it's successfully casting then you'll see a chromecast icon filled in. If that's the case then you should be able to adjust your volume through Vysor and it shouldn't adjust the audio on your phone.

![image](https://user-images.githubusercontent.com/1493142/71910359-c40b5880-313f-11ea-8738-15a38bf7fd05.png)

**Comment by gdmtplays** [comment]
Okay so it worked if one uses chromecast to cast said device. But what if it were done via the cable or just plain casting through wifi? Were you able to find a workaround? Been trying endlessly and cant get the audio to work with Vysor when in cable mode.

**Comment by EliasRanz** [comment]
I haven't found a workaround for this yet. I will update if I do.

**Comment by koush** [comment]
Hello all. Answering a couple questions:

Audio mirroring requires a wifi connection. There's no way around it. The phone will stream the data through the USB, but the wifi connection is required for it to be discoverable as an audio cast device.

I'm going to remove the automation attempts for audio, and include manual instructions on how to do it. The automation is simply too unreliable.

**Comment by EliasRanz** [comment]
@koush is PTP limited to just video capture and not audio hence the requirement for doing it over casting? Or are there other blockers? 

I do recall reading somewhere that people were using 3.5mm aux cables that allowed you to plug it into line-in on the computer. In that scenario for phones that are USB-C only would something like a USB-C to USB-C/3.5mm aux splitter work and allow you to transfer the audio over the hardware?

**Comment by gittac** [comment]
It was working for me. Now I can't see mirroring anywhere on the google home app. It was such a nice feature for audiobooks and meditation audio. I have a severe physical disability and it made life easier. Did you go home app change some how? Yes, I am on the same wi-fi network. vysor audio output just doesn't show up.  Is it something on the computer side of the program? I have a Moto Z4, but like I said this feature was working.

**Comment by gittac** [comment]
Audio Mirroring it is now working for me after that update 20 hours ago. 
Here are instructions https://github.com/koush/vysor.io/issues/426

**Comment by koush** [comment]
Please test Vysor 2.2.2. https://github.com/koush/vysor.io/issues/426

**Comment by dizney4j** [comment]
So it's not working, and every "Solution isn't working either.

I'm trying to stream a game. The phones audio is coming through the phone. Vysor doesn't pick up the audio.

When you click the headphones, I go through the motions. All the way to "Vysor Audio Output" and I cast device and the Chromecast pops up yet I still get audio from the phone coming FROM the phone's speaker and NOT vysor. 

The other option people say is you have to be on the same network. My phone is on wifi and my PC is hardwired. Connected directly to my router via ethernet. Still on the same network though.

I've seen people say to search through screen cast. I have a Galaxy 9 and dont have that. I have something similar named Smart View but that doesn't do anything about transfering audio.

Very frustrating.

**Comment by Bahal** [comment]
Xiaomi Mi9 Android 10. Couldn't get it to work.
Tapping the headphones brings up Wireless Display and then nothing is found.
I have also a Cast option on my phone. Tried from there too. Nothing found.
Neither with Chromecast-based apps.

**Comment by nurashidnm** [comment]
Connected my phone both via wired and wireless, everytime I clink the audio logo, and at the Cast option, there is no Vysor Audio Cast, it can see my other Android TV device, but no Vysor Audio.

**Comment by koush** [comment]
I have a working solution for Android 10 that does not rely on Cast. Are any of you on Android 10 now? I can put you onto a beta.

**Comment by gittac** [comment]
I have Android 10, but I am not having problems with cast. I am wondering
if cast can be made to work for audio on a phone call?

**Comment by Ceddini** [comment]
@koush I'm on Android 10. Would like to test it out if it's not too late

**Comment by koush** [comment]
@Ceddini I will roll out the change and let you know how to activate the hidden setting.

**Comment by gdmtplays** [comment]
@koush Kindly include me in your beta please. Still cant figure out how to make audio mirroring work. Huawei P30 Pro here.

**Comment by Ceddini** [comment]
@koush Awesome, thanks! 
I'm also able to test it on all platforms if there's any need for that. 
And I saw that I had my email hidden. Feel free to shoot me one if you don't want to make hidden settings public.

**Comment by thoiruddin** [comment]
@koush I'm using Android 10 and will to know how to cast the audio from my Huawei device. Include me on your beta too.

**Comment by rlucho** [comment]
Hi, can i try that beta version? I'm having issues with the internal audio from phone, after a few minutes is not longer working and i need to re-toggle the audio for it to work again...

**Comment by OlegNovosad** [comment]
Hey, is it possible to have an audio mirroring with VPN? I mean my device is far away from me and the only way to connect is via VPN (imagine some device farm that QC are willing to test on). And we require an audio mirroring. Is it somehow possible?

**Comment by ghoedev** [comment]
Hi audio mirroring is okay except when it is a phone call. Is this a feature or a bug in my case?
