### ISSUE TITLE
Can't purchase Vysor - Infinite loop between Google Log in & Success code

### ISSUE THREAD

**Issue by JWj2** [koush/vysor.io#355]
Get "Success Code", but Google account is not set so can complete my purchase.

**Comment by JWj2** [comment]
I’ve tried to buy Vysor, but since I have more than one gmail/google addresses (for personal & business), I get stuck in an infinite loop being sent back and forth between choosing my google account, logging in [with my default Chrome account], receiving a "Success code", & then being told to sign in again, which I’m unable to do because that tab doesn’t respond to any clicks on the “Sign in”. 

I've "Reset Vysor", but had no greater success.  [I'm using Windows 8.1 with the latest Chrome browser.]

If I go to the pop-up window with the purchase options, there’s **no  account** assigned so I can’t go any further.  So frustrating! 

"SuccessCode" tab URL has the following [editted]:
https://accounts.google.com/o/oauth2/approval/v2/approvalnativeapp?auto=false&response=code… email%2520profile%2520https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%2520https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%2520https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchromewebstore.readonly&hl=en&approvalCode=…

Example "Success Code" tab.
![snap3](https://user-images.githubusercontent.com/44943754/48313308-a5720600-e5fd-11e8-8a82-d0605dd879f0.jpg)

Example "no account" Purchase pop-up.  Continuing gives an error message.
![sc 01](https://user-images.githubusercontent.com/44943754/48313325-0699d980-e5fe-11e8-8403-06944aed0631.jpg)

Please help.

**Comment by TommyFen** [comment]
Me too, any idea?

**Comment by avadhbsd** [comment]
@koush you keep closing these and provide no detail whatsoever why we can't purchase it? if you can't manage it better close it so no one wastes their time going through the rabbit hole. 

Vet irresponsible and unprofessional
