### ISSUE TITLE
refund

### ISSUE THREAD

**Issue by SchafferXu** [koush/vysor.io#358]
I have purchased a lifetime subscription (less than 24 hours) and I want to have refund of service as the product did not meet my expectation especially on Audio aspect.

I tried to send a refund request email to billing@vysor.io, and did not receive any reply.

I would like to have a refund of purchase, Thanks.

pay with visa  , and my gmail is : schafferxu@gmail.com

**Comment by KhurramAziz1** [comment]
This is in regards to the purchase I made on 17-Nov-2021 I did not find it useful for me also the Audio Toggle is not working for me. Purchased and cancelled the same day.. Sent many email on billing@vysor.io but no response from them even after 3 days.
I am requesting for a refund. My email is rana.khurram.aziz@gmail.com
