### ISSUE TITLE
International keyboard notification makes phone beep constantly

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#361]
Hi! :)

Bought Vysor a couple weeks ago, used it for all this time with my Samsung Galaxy S8. Bought a Pixel 3 today. Installed Vysor app / Chrome app / ADB combo. It's working great.

I activated the International Keyboard. Now, everytime I click inside and outside of a text field, the notification "Vysor is hiding your keyboard" is summoned and the phone beep to indicate it has a new notification.

I can't disable the notification because I need it to select my Android Keyboard back when I unplug my phone. 

I plug/unplug my phone multiple times per hour, I can't go dig in the settings every time to replace the proper keyboard.

I also need international keyboard, because, you know : àéuïç. 👍 

Thanks for any advice and please, if you need ANY information, don't hesitate.

Google Pixel 3, fresh new, right out of the box phone (although fully set up).
Vysor on Android, fresh install.
Vysor Extension on Chrome, fresh install.
Universal ADB drivers, fresh install.
International Keyboard is ON.

**Comment by Heretushi** [comment]
Is there any chances I will get official support from the vendor here ? I don't feel like it's being monitored at all.

**Comment by Heretushi** [comment]
Still no answer from official sources. Disappointing...

**Comment by paulo-apoloni** [comment]
The only way i found to have sanity back is muting the notifications from Vysor.
I would like an official fix for it too.

**Comment by xijicisema** [comment]
For notification, you can disable it and then install 3rd party keyboard switcher, has its own notification or shortcut.

**Comment by shasderias** [comment]
Long press on notification, details, tap Vysor (under categories, don't toggle the switch, press the bar itself), tap notification type, tap silent.

Tested on S8+, I think it's available on any recent Android version though.

My system language is currently set to Japanese, some of the above labels might be inaccurate.

**Comment by Heretushi** [comment]
Still no support from official source.

**Comment by Heretushi** [comment]
shasderias, thanks for the tips!

I bet this works for Samsung users.


For Google Pixel 3 users, here is the fix I found, inspired by shasderias comment :


1. Go in the setting (drag down from the top two times to make the drawer fully extended, then click the cogwheel at the bottom right of the drawer).

2. Choose "Apps & Notifications".
3. Find and select "Vysor".

4. Choose "Notifications".

5. At the bottom of the page, there is the "Advanced" section. Tap on it to open.

6. Slide off the "Allow notification dot" slider.


Ok, so. I did this now and tested I get the notification sound from an incoming email, but I don't have when switching pages and having the Vysor notification popping in and out.


My main problem is that I can't have the Vysor sound come back so I can't test that this is the solution for everyone. I would have liked to be able to have the sound on and off at will to make sure this is the correct solution, but Vysor is ... awkward at best.


If this solution works for you, please report back.
