### ISSUE TITLE
Remote share doesn't work in different networks

### ISSUE THREAD

**Issue by aswingokul** [koush/vysor.io#362]
I'm using Vysor Pro 2.0.9. When I try to open the shared link in another PC connected to another network,(both are logged into same vysor pro account), the phone shows offline in the PC Vysor. This is 1 scenario or the shared link opens but keeps on loading for a very very long time.

**Comment by krokmobile** [comment]
Same here. Does anybody knows how to fix it?

**Comment by iimuro** [comment]
Same with me too.
On Javascript console, you get "uglify-screen.js:1 Uncaught (in promise) Error: Timeout waiting for RTC Connection".

**Comment by iimuro** [comment]
On my chrome's WebRTC Internals, it says:

addIceCandidate (host)
sdpMid: 0, sdpMLineIndex: 0, candidate: candidate:3367527005 1 udp 2122260223 192.168.11.16 63098 typ host generation 0 ufrag yQut network-id 1 network-cost 10

192.168.11.16 is a host side's local IP, not global.
