### ISSUE TITLE
the screen is zoomed in and i cant do anything

### ISSUE THREAD

**Issue by Alb305** [koush/vysor.io#364]
I connected my phone to my pc today and this is all I could see...Does anyone know a fix please?

![screen 1](https://user-images.githubusercontent.com/47505797/52538477-ad466100-2d38-11e9-93c2-a42aef6a61e2.png)
![screen 2](https://user-images.githubusercontent.com/47505797/52538478-ad466100-2d38-11e9-84ca-f4a3ad3bb842.png)

**Comment by woojoo666** [comment]
for anybody else who gets here, I found a solution: use `adb shell wm density 480` to manually set the screen resolution to 480, which should help. I found that setting even lower values, like `360`, made it zoom out even further.

**Comment by woojoo666** [comment]
I also recommend checking out [scrcpy](https://github.com/Genymobile/scrcpy), a free and open-source software that does everything Vysor does, and the devs are a lot more helpful (they guided me to the `adb shell wm density 480` solution)
