### ISSUE TITLE
OSX Mojave (unsupported mac) -   assert !context_->is_null()

### ISSUE THREAD

**Issue by teolemon** [koush/vysor.io#366]
I recently updated my os to OSX Mojave on a mac that wasn't meant to (using: http://dosdude1.com/mojave/)

When attempting to use mirroring on Vysor, I'm now getting the following error: Graphics Card   assert !context_->is_null()
Is there a similar workaround to the one mentioned for Windows ?
![image](https://user-images.githubusercontent.com/1689815/52780432-68793d80-304a-11e9-934d-7d60f7f74882.png)

**Comment by teolemon** [comment]
Intel HD Graphics 3000
![image](https://user-images.githubusercontent.com/1689815/52780605-d45ba600-304a-11e9-95e1-5a7615146aba.png)

**Comment by boyfox** [comment]
I have same issue, I also have Intel HD Graphics 300 worth.

**Comment by juanfeorar** [comment]
I have same issue with macOS High Sierra
![Screen Shot 2019-04-24 at 7 59 27 AM](https://user-images.githubusercontent.com/1591202/56661659-dbfd8380-6667-11e9-9146-9cf598ea97e0.png)
![Screen Shot 2019-04-24 at 8 03 04 AM](https://user-images.githubusercontent.com/1591202/56661661-dbfd8380-6667-11e9-95d9-39cab8711207.png)

**Comment by mig82** [comment]
I have the same issue, on Mojave also.

**Comment by mig82** [comment]
@koush could you please comment on why you have closed the ticket without commenting on the issue, cause or resolution?

**Comment by jmhunter** [comment]
Same issue for me (High Sierra on genuine Macbook 13", no hackery involved).

I'm a first-time user of Vysor; or at least, I was hoping to be.. All I get is a blank screen and this error message.

(My Mac has "Intel HD Graphics 3000 512 MB", in case that makes a difference)

**Comment by koush** [comment]
Intel graphics 3000 isn’t supported due to lack of acceleration, but I’m gonna switch to a decoder that doesn’t require acceleration.

**Comment by griveiro** [comment]
Same issue for me (Optiplex 3010) Ubuntu 19.10

Graphics:
 Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: 
 Dell driver: i915 v: kernel bus ID: 00:02.0 
 Display: x11 server: X.Org 1.20.5 
 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
 OpenGL: renderer: Mesa DRI Intel Sandybridge Desktop v: 3.3 Mesa 19.2.8 direct render: Yes

**Comment by koush** [comment]
Can you try the new progressive web app beta here:
https://app.vysor.io
I want to verify this is fixed.

Native apps coming soon.

**Comment by koush** [comment]
Native apps are available. Need confirmation that the WebAssembly decoder fixes this issue.
