### ISSUE TITLE
Disable Auto-update Windows

### ISSUE THREAD

**Issue by timeakesmarky** [koush/vysor.io#367]
How can I disable autoupdate of windows version?

**Comment by 1valdis** [comment]
@koush closing without response? I'd like to know that too.

**Comment by mridul120** [comment]
https://www.youtube.com/watch?v=msdVKaJ2u8o 
you can check it hopefully this will be helping you

**Comment by koush** [comment]
uhh sorry I thought I closed this as a duplicate, there is another issue for this.

https://github.com/koush/vysor.io/issues/686
