### ISSUE TITLE
Error installing apk: success

### ISSUE THREAD

**Issue by torchick11** [koush/vysor.io#368]
I have no idea why this keeps happening, i've done everything that the "[guide](https://www.youtube.com/watch?v=Ucs34BkfPB0)" told me to do (even if he does something off screen and doesn't tell us what to do). It just keeps showing that popup with the message "Error installing apk: success".

**Comment by djangofan** [comment]
For me it says "file is being opened on the device"  but nothing happens and I can't find the .apk when i use the Files app to browse to it.   So, I am not sure where it is even copying the file to.

**Comment by rejoicewilson** [comment]
Go to Settings - Permissions - Install via USB: Uncheck your App if it's listed.
Go to Settings -Additional Settings -Privacy: Check the Unknown Sources option.
Finally go to Settings -Additional Settings - Developer options: Check the Install via USB option.

**Comment by NamesJoeyWheeler** [comment]
I get this issue as well and have not found a working solution.

**Comment by JohannBlake** [comment]
Using the browser app to connect to the my Android 10 device. The browser hangs on installing the APK. Even if I manually install the APK, the browser app uninstalls it.
