### ISSUE TITLE
dead-mac.png error

### ISSUE THREAD

**Issue by timleg002** [koush/vysor.io#370]
So my friend got a phone which got BROKEN LCD and the screen. He cant access it. So I somehow managed to enable USB debugging, started Vysor and it worked. Then I opened a game (Brawl Stars) and it got dead-mac.png error. Then I couldnt access the phone (it was partly because of the cable), but somehow I managed to fix it, but every time I access the Vysor app it works for a while and then it displays dead-mac.png error.

**Comment by Dyor1** [comment]
Were you able to fix it, if so can you send the procedure
