### ISSUE TITLE
Vysor Crashes when video turns to landscape. Please REOPEN until actually resolved.

### ISSUE THREAD

**Issue by ReolandH** [koush/vysor.io#371]
As stated in title, Vysor crashes and needs to be disconnected and reconnected physically to regain it's connection.

The only time this ever happens is when the video itself forces the window to change to landscape mode.

Any help?

**Comment by ReolandH** [comment]
Closed without not as much as a response?

**Comment by koush** [comment]
Please provide a logcat. Closed all issues because I didn’t set up a template that gets the necessary info for a bug report.

**Comment by koush** [comment]
@ReolandH ping

**Comment by koush** [comment]
Closing due to no logcat.
