### ISSUE TITLE
Graphics Error with Win10 17134.706 / Intel HD630

### ISSUE THREAD

**Issue by rippi** [koush/vysor.io#373]
Since updating to Win10 x64 Build 17134.706 I get a "Graphics Error: assert !context_->is_null()".
The following popup occurs:
![image](https://user-images.githubusercontent.com/9192583/56114347-e2ea0f00-5f60-11e9-8de6-6af436d0b883.png)

I updated the display drivers of the Intel HD630 graphics card, nothing changed. The tutorial from the [Support Page](https://support.vysor.io/support/technical/graphics/) didn't help either.

**Comment by LuisChat** [comment]
Hello

Did you try to install version 1.8.3? it worked for me only when closing the application it is updated and shows the same error.
