### ISSUE TITLE
Show cursor on device

### ISSUE THREAD

**Issue by WesleyM77** [koush/vysor.io#374]
It would be cool to show the cursor on the android device itself. I have my android device docked between monitors and would like to just look directly at the device when I'm using Vysor to control it. It would help immensely just to see where the cursor is so I don't have to look at the computer and can instead opt to use the device's screen.

**Comment by Heretushi** [comment]
Good suggestion. 

Sadly, I don't think the author even see this page at all. I don't even think he is interested in the product anymore. I had no answer to any of my help requests, here or on twitter.

**Comment by WesleyM77** [comment]
That's rather unfortunate. I started using this since I couldn't get DeskDock to work.

**Comment by Heretushi** [comment]
Let's hope I'm wrong and your issue gets some views or even an answer from
the developer.
