### ISSUE TITLE
input (mouse and keyboard) are not working with xiaomi mi 9

### ISSUE THREAD

**Issue by luziusalbin** [koush/vysor.io#383]
morning everyone

i'm using vysor pro some years now and it worked great all the time! now, with my new xiaomi mi 9, it's **not responding to any mouse or keyboard input**. any idea, what that issue could be?

thanks in advance!

**Comment by luziusalbin** [comment]
that was quick - just found out that i've had to activate the "**usb debugging (security settings)**" for the usb input method.

*case closed  :-)

**Comment by xijicisema** [comment]
> that was quick - just found out that i've had to activate the "usb debugging (security settings)" for the usb input method.
> *case closed  :-)

That's encouraging but can you be more specific. Where is the "usb debugging (security settings)".

I don't see anything under developer or debugging options. Is it under settings for Input method - Vysor keyboard? 

I see Visor keyboard there but I can't click on the options (just arrow pointing right), clicking on it crashes the settings so the settings for Vysor won't show up. 

I tried even to enable and disable Vysor keyboard in hope the setting you mention comes up but it doesn't.

I'm on Android 9. Looking around it doesn't seem like a common issue. 

Just want to confirm if the setting you mention is in fact in the Wysor keyboard settings.

**Comment by luziusalbin** [comment]
> I don't see anything under developer or debugging options. Is it under settings for Input method - Vysor keyboard?

it's in the android-settings on your phone:
Settings >> Additional Settings >> Developer Options: and here you activate the "usb debugging (security settings)"
