### ISSUE TITLE
error message when connecting

### ISSUE THREAD

**Issue by yossi321** [koush/vysor.io#39]
hi,
when i choose my device nothing happens. while using another app call Mobizen there's a black screen with error message (attached).
i have galaxy s3. windows 7, adb and PTP checked.
![hbhb](https://cloud.githubusercontent.com/assets/14034946/9564837/54832e66-4eb3-11e5-929c-be06bf48fb8a.png)

**Comment by koush** [comment]
phone is too old. may add support for phones older than kitkat in a later version of vysor.
