### ISSUE TITLE
mirrored android screen black linux

### ISSUE THREAD

**Issue by iamthevoid** [koush/vysor.io#393]
Can't see mirrored screen, but touches works (tried to press something and clicks happens on real phone. I see this in terminal

`/opt/vysor/node_modules/electron/dist/electron --type=ppapi --enable-features=SharedArrayBuffer --no-sandbox --ppapi-flash-args --lang=en-US --service-request-channel-token=16779745543845794557: symbol lookup error: /home/iam/.config/ElectronChrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm/app-2.1.7.crx-unpacked/native/linux/video_decode.so: undefined symbol: _ZN2pp3VarC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

my hardware is
[iam@thevoid ~]$ inxi -Fxxz

> System:    Host: thevoid Kernel: 4.19.45-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.3.0 
> 
> Desktop: Deepin 15.10.1 
>            tk: Qt 5.12.3 wm: DeepinWM dm: LightDM Distro: Manjaro Linux 
> 
> Machine:   Type: Laptop System: GIGABYTE product: P56X v: N/A serial: <filter> 
>            Mobo: GIGABYTE model: P56X serial: <filter> UEFI: American Megatrends v: FA09 date: 07/24/2018 
> 
> Battery:   ID-1: BAT1 charge: 91.2 Wh condition: 91.2/91.2 Wh (100%) volts: 12.5/11.4 model: GIGABYTE P56X serial: <filter> 
>            status: Full 
> 
> CPU:       Topology: Quad Core model: Intel Core i7-7700HQ bits: 64 type: MT MCP arch: Kaby Lake rev: 9 L2 cache: 6144 KiB 
>            flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44944 
>            Speed: 1200 MHz min/max: 800/3800 MHz Core speeds (MHz): 1: 1118 2: 1135 3: 1150 4: 1127 5: 1141 6: 1111 7: 1125 
>            8: 1115 
> 
> Graphics:  Device-1: Intel HD Graphics 630 vendor: Gigabyte driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:591b 
>            Device-2: NVIDIA GP104M [GeForce GTX 1070 Mobile] vendor: Gigabyte driver: N/A bus ID: 01:00.0 chip ID: 10de:1ba1 
>            Display: x11 server: X.Org 1.20.4 driver: intel resolution: 3840x2160~60Hz 
>            OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) v: 4.5 Mesa 19.0.4 compat-v: 3.0 
>            direct render: Yes 
> 
> Audio:     Device-1: Intel CM238 HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a171 
>            Device-2: iRiver type: USB driver: snd-usb-audio bus ID: 1-1:11 chip ID: 4102:1214 
>            Sound Server: ALSA v: k4.19.45-1-MANJARO 
> 
> Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8168 v: 8.047.01-NAPI 
>            port: d000 bus ID: 03:00.0 chip ID: 10ec:8168 
>            IF: enp3s0 state: down mac: <filter> 
>            Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: d000 bus ID: 04:00.0 chip ID: 8086:24fd 
>            IF: wlp4s0 state: up mac: <filter> 
>            IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
> 
> Drives:    Local Storage: total: 2.29 TiB used: 1.39 TiB (61.0%) 
>            ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 PRO 512GB size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 
>            serial: <filter> 
>            ID-2: /dev/sda vendor: Seagate model: ST2000LM015-2E8174 size: 1.82 TiB speed: 6.0 Gb/s serial: <filter> 
> 
> Partition: ID-1: / size: 367.96 GiB used: 223.06 GiB (60.6%) fs: ext4 dev: /dev/nvme0n1p2 
> 
> Sensors:   System Temperatures: cpu: 66.0 C mobo: 29.8 C 
>            Fan Speeds (RPM): N/A 
> 
> Info:      Processes: 270 Uptime: 6h 09m Memory: 15.54 GiB used: 11.35 GiB (73.0%) Init: systemd v: 242 Compilers: gcc: 8.3.0 
>            Shell: bash v: 5.0.7 running in: deepin-terminal inxi: 3.0.34 

Vysor version is 2.1.7 PRO

**Comment by miyalys** [comment]
Had the same error, and I was using the _release version_ AppImage of 2.1.7 at 66.1 MiB.
But it works now that I use the latest _continuous build_ instead, also 2.1.7, but at 80.8 MiB
