### ISSUE TITLE
Vysor mac crash at startup after recent update

### ISSUE THREAD

**Issue by dzsonni** [koush/vysor.io#398]
![image](https://user-images.githubusercontent.com/6988242/60963425-6a091200-a319-11e9-85a6-365a53ac8413.png)

[VysorCrash.txt](https://github.com/koush/vysor.io/files/3377097/VysorCrash.txt)

Trying to log in gives me 400, and pro license is not recognized either. Somehow the app functions after the error but with basic quality only

**Comment by koush** [comment]
Can you reset + reinstall?
