### ISSUE TITLE
non english keyboards don't work.

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#4]

**Comment by koush** [comment]
initial investigation indicates needing to install an IME to support this, setting that as the preferred IME, and providing key events.

**Comment by hamidsafdari** [comment]
Aren't there any workarounds to this? I mean is this not possible at all?
I can change the keyboard language on the phone and then wouldn't there be a way of identifying this with vysor and send keys in that language to the device?

I guess this is an android problem, right?

**Comment by anawim** [comment]
This is a bummer that prevents adoption as a serious tool by all the non-english devs. I'm still waiting for a solution.

**Comment by andreldm** [comment]
I'm using Vysor again and now there's an option called "International Keyboard" in Settings that has been working smoothly so far.

**Comment by anawim** [comment]
I don't have any option like that as I'm stuck to latest version working on Chrome v44

**Comment by koush** [comment]
Implemented international keyboard.

**Comment by anawim** [comment]
@koush it's not implemented in the only version I'm forced to use on Chrome v44

**Comment by koush** [comment]
update chrome, sorry.

**Comment by anawim** [comment]
I can't, those assholes at Google removed support for NPAPI that's necessary for too much company stuff
