### ISSUE TITLE
Stop asking for duplicate screen or audio

### ISSUE THREAD

**Issue by Heywir** [koush/vysor.io#402]
Hello,
Even though "Mute Android and Mirror Audio automatically" is checked, google home keep popping up on my android screen everytime i do something else.
Ok, audio mirroring doesn't work with my phone, but can i deactivate it completely ?

**Comment by RareSnack** [comment]
I have the same issue. I don't care for audio mirroring, yet I constantly see this notification "Vysor Audio Output Requires the Google Home application" just before the Play Store launches to the Google Home app.
