### ISSUE TITLE
Graphics Error: assert !context_->is_null() MacOS Sierra

### ISSUE THREAD

**Issue by juanfeorar** [koush/vysor.io#403]
Hi,
I have this issue.

Help me please

Thanks

![error_vysor](https://user-images.githubusercontent.com/1591202/61477288-84b03c00-a954-11e9-94fb-d77ba16c03e4.png)

**Comment by mig82** [comment]
I have the exact same issue in Mojave. It just came out of nowhere. One day it was working fine and then it wasn't. The Vysor support page for `!context_->is_null()` is specific to Windows. It says nothing about Mac.
