### ISSUE TITLE
Uninstall Vysor Android App

### ISSUE THREAD

**Issue by MarkSmz** [koush/vysor.io#405]
Ladies and Gentleman,

I had Vysor installed on my PC to mirror the screen of my smartphone to the PC screen. Now I don't need Vysor anymore and uninstalled it on my computer. I uninstalled the app on my smartphone as well. But I still see it in my app overview with the comment : Not installed for users.
![Screenshot_20190814_103537](https://user-images.githubusercontent.com/49169537/63019586-16e82900-be9c-11e9-8d7a-533b4995173d.png)
 How can I uninstall the app without leaving any residue?

In German:
Ich hatte auf meinem PC Vysor installiert, um den Bildschirm meines Smartphones auf den PC Bildschirm zu spiegeln. Nun brauche ich Vysor nicht mehr, und habe es auf meinem Computer deinstalliert. Da auf dem Smartphone eine entsprechende App installiert wurde habe ich diese auch deinstalliert. Ich sehe diese aber immer noch in meiner Appübersicht mit dem Kommentar : Nicht für Nutzer installiert. Wie kann ich die App deinstallieren, ohne das irgendwelche Rückstände übrigbleiben.

**Comment by MarkSmz** [comment]
Sorry, I already found the problem. Since the app was automatically installed on my smartphone by the program on my computer, it was installed directly for all users, including the guest user. All you have to do is switch to the guest user's account and uninstall the app there.

**Comment by IvanKonst** [comment]
Hello, I have the same problem, how did you fixed it last time?
