### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by anawim** [koush/vysor.io#41]
I don't know why but Vysor is not auto updating on my work computer just like other Chrome apps (e.g. Pushbullet) do

**Comment by koush** [comment]
Does it give notifications at least?

**Comment by anawim** [comment]
No, never seen any notifications of Vysor updates even on my other machine

**Comment by koush** [comment]
What version is your vysor? I added update notificatiosn around v1045

yuck. try uninstalling and reinstalling it from the chrome store.

**Comment by anawim** [comment]
I always have the latest 1501 but I had to force update removing and installing again

**Comment by anawim** [comment]
In case of buggy release there should be an option to skip update and eventually roll back to previous version

**Comment by koush** [comment]
you can prevent autoupdating in google chrome i think.

**Comment by anawim** [comment]
Oh really, so please provide instructions because I'm stuck with a buggy release and have no idea to get back to working 1.0.5.5
