### ISSUE TITLE
Black screen even though test website works

### ISSUE THREAD

**Issue by TitusLabienus** [koush/vysor.io#412]
When I start Vysor and connect to a device the screen stays black. The linked test website on [Fixing Black Screen](`https://support.vysor.io/support/technical/black/`) works without issues.

The [submit an issue](https://plus.google.com/110558071969009568835/posts/JLuG3yqRdSH) link does not work anymore, as it says Google+ would be no more available for private users.

I've tried both the installed and the Chrome plugin version with the same result, and with and without optirun. 

[ConsoleOutput.txt](https://github.com/koush/vysor.io/files/3638796/ConsoleOutput.txt)
[journalctl.txt](https://github.com/koush/vysor.io/files/3638809/journalctl.txt)

Please let me know, whether/which further logs you need.

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel  / nvidia
Kernel: 5.2 vanilla

**Comment by AlbinoGeek** [comment]
Hello @TitusLabienus ,

It is rather unfortunate the developer has not gotten back to you, as it has already been nearly a month! I hope you are not a paying user and experiencing these issues :( .

As per your log, the only thing I can see that would be related is:

```
/opt/vysor-git/node_modules/electron/dist/electron --type=ppapi --enable-features=SharedArrayBuffer --no-sandbox --ppapi-flash-args --lang=en-US --service-request-channel-token=5193311830202011061: symbol lookup error: /home/vbm/.config/ElectronChrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm/app-2.1.7.crx-unpacked/native/linux/video_decode.so: undefined symbol: _ZN2pp3VarC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

The only problem is, this is a pretty common error message; something I see even when Vysor is functioning correctly. Have you verified that this works via the Chrome app "Vysor", versus the stand-alone version (which it appears you are trying to use here.)

**Comment by TitusLabienus** [comment]
@AlbinoGeek Thank you very much for your reply. Yes, having the pro version, I cannot use Vysor because of this bug, unfortunately. I have tried it both in the Chrome app and in the stand-alone version. For both cases I have the same result of a black screen, but the phone reacts to mouse inputs.

**Comment by TitusLabienus** [comment]
@koush: You are the Vysor developer, right? I bought the full version of Vysor, couldn't use the software at all, took the time to run the test software as described to verify my system was configured correctly, tried to report the issue on the designated Google+ group, which had been closed in the meantime, and having no other means of contact, I instead took the time to report the issue here. You haven't answered my bug report for nearly two months, and now you simply close the ticked with no comment whatsoever? And also you close dozens of other tickets of customers as well, just like that within one hour?? ( e.g. #404, #410, #411, and many more)

**Comment by koush** [comment]
Sorry closed all issues without templates cause the issue tracker was filled with spam.

**Comment by koush** [comment]
Can you try the new progressive web app beta here:
https://app.vysor.io
I want to verify this is fixed.

Native apps coming soon.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues
