### ISSUE TITLE
Vysor not copying with usb type c

### ISSUE THREAD

**Issue by wincelee** [koush/vysor.io#413]
Vysor is not copying anything from the android to the computer when using usb type c

**Comment by wincelee** [comment]
when you copy from an android that is using usb type c it doesnt update the computers clipboard unlike old version of usbs

**Comment by AlbinoGeek** [comment]
Hello @wincelee 

Please tell me what you mean by "Copying". I have a Google Pixel 2 which connects to the computer using a generic "Male-Male C to A" USB cable. I am able to connect to the device fine (for the most part, when it is working.) I am also able to paste (via "Ctrl+V" shortcut) to the device, as long as "Vysor" is selected as my current keyboard.

If you are expecting different functionality, or the above is not working as described, please clarify that.

**Comment by RegisStGelais** [comment]
I have the same issue. Samsung Galaxy Tap (2017) with USB type C connector. I can copy from the computer and past to the device. But copying from the device and pasting to the computer does not work.

**Comment by RegisStGelais** [comment]
I use the original USB cable coming with the device.

**Comment by wincelee** [comment]
Yeah especially phones with type c connector its really frustrating

**Comment by RegisStGelais** [comment]
I was about to buy the perpetual license but copy and past not working is a show stopper for me :-(

**Comment by RegisStGelais** [comment]
The PC side is running on Windows 10

**Comment by RegisStGelais** [comment]
Why did you close this issue?. It is still an issue.
