### ISSUE TITLE
I cannot cancel my subscription, and it keeps charging me

### ISSUE THREAD

**Issue by Fluffyrox4** [koush/vysor.io#414]
I have tried for months on end now to cancel my subscription to your service but for some reason it keeps charging me! I believe there was one occasion (after I THOUGHT I had already cancelled the stupid thing mind you) where the subscription became past due, and it told me via email that the subscription would be automatically cancelled if I didn’t have enough money in my account the next time it attempted to bill.
Funnily enough, I didn’t have enough money in my account when it attempted a week or so later, but it did not cancel, and still charged me the month after! I’m getting sick of this! I don’t normally do this but I demand a refund, I’m legitimately very upset with your crappy service.

The email I used to sign up is realfluffyrox4@gmail.com 

I believe the subscription may have cancelled itself by now, but either way, I still want to money back. I contacted the billing support email but judging by other responses I've seen in this area they're probably going to do bugger all.

**Comment by AlbinoGeek** [comment]
Oof, that's a bit of a legality issue and less a bug in the codebase itself.

If the developer has not contacted you directly about supporting this issue, I am rather worried.

Otherwise, please close this issue if you have been helped (which would show me their support is contacting members about important issues like this, and make me feel better as a current paying customer.)

**Comment by Fluffyrox4** [comment]
Sadly I've recieved no help as of yet. Not looking too good. I'll try and keep you filled in if you like :)

**Comment by koush** [comment]
You were charged for 2 months and then it was successfully cancelled. I'm not sure what you are referring to when you said you have tried to cancel for months? Did you set up multiple accounts and forgot?

![Dashboard_–_ClockworkMod_–_Stripe](https://user-images.githubusercontent.com/73924/69180886-eaf3c980-0ac2-11ea-8958-c49c29531b0c.png)

**Comment by Fluffyrox4** [comment]
I didn’t subscribe for the second month, that’s the problem.

Sent from Mail for Windows 10

**Comment by dyc1978** [comment]
Hi Koush, I already clicked to cancel for my subscription. But the app is still trying to charge me. i logged in again and click cancel. but i cant verify if its really cancelled. can you please verify it for me. and it doesnt have an option to remove my card details. please include. i dont want to get charge on something im not using anymore. Thanks,
