### ISSUE TITLE
Where to get support

### ISSUE THREAD

**Issue by DannyDeLoach** [koush/vysor.io#416]

**Comment by DannyDeLoach** [comment]
I need help connecting wirelessly. But for now, I'm simply asking where I can go to receive support from the owner of Vysor. Support for this software appears to be extremely limited. I can understand having limited support available for free software, but I was expecting a higher level of support for paid software.
Where can I go to find answers for my questions about using Vysor? Thanks.

**Comment by RegisStGelais** [comment]
I'm in the same boat. I never get any reply from support@clockworkmod.com

**Comment by thiagorpinto** [comment]
I'm also having issues with wireless connection. And also having a hard time to get support. 
@koush , can you help us here?

Thanks.

**Comment by koush** [comment]
Fixed.
