### ISSUE TITLE
annual subscription vanished

### ISSUE THREAD

**Issue by whommy** [koush/vysor.io#420]
I've bought an annual subscription on oct 3 2019 via chrome web store.
I'm correctly logged on chrome app and desktop app, I've tryed everithing on your supporto site but today my license Is not reconized 
I've proof of payment on my Google account

**Comment by TitusLabienus** [comment]
I have the same issue. The licence for the Chrome version is simply missing.

**Comment by fsw0422** [comment]
these guys should be sued for fraud. i claimed a refund the day i bought it and they're just ignoring

**Comment by koush** [comment]
Chrome web store and the Chrome app is phased out and not even supported by Google anymore. That option only exists for past users that purchase with Chrome store. https://www.google.com/search?q=chrome+app+deprecated&oq=chrome+app+deprecated&aqs=chrome.0.0l5.4000j0j4&sourceid=chrome&ie=UTF-8
