### ISSUE TITLE
Screen is Zoomed In

### ISSUE THREAD

**Issue by woojoo666** [koush/vysor.io#423]
Screen is super zoomed in, unable to do much. I noticed that somebody filed [a similar issue](https://github.com/koush/vysor.io/issues/306) but it got closed without any details. Can somebody provide an answer before closing this issue?

<img width="449" alt="chrome_2019-12-18_04-23-23" src="https://user-images.githubusercontent.com/2776751/71088618-ac017400-2153-11ea-9bef-28e874e42944.png">

**Comment by RegisStGelais** [comment]
The dev closed all issues without any explanations and is not answering messages.

**Comment by RegisStGelais** [comment]
https://www.linkedin.com/in/koushik-dutta-3a55175/

**Comment by koush** [comment]
Check the screen density.

@RegisStGelais All prior issues were closed because this was never meant to be a place to report issues. It's just the Vysor website, and I left issue tracking on. So I closed them, and created a proper bug report template.

**Comment by Heretushi** [comment]
@koush If this place is not the proper place to report issues on Vysor in itself, where is ? :) I would participate in the proper channel.

Thanks.

**Comment by koush** [comment]
@Heretushi This is fine now, since users are using it. I just closed all the issues because there was no template set up, and most of them had insufficient information.

**Comment by koush** [comment]
screen density option has been removed, so closing this.
