### ISSUE TITLE
Sharing works for 30 seconds and then dies

### ISSUE THREAD

**Issue by asyschikov** [koush/vysor.io#424]
I bought Pro version, hoping that some pro settings would help but they didn't.
The sharing works for like 10-30 seconds perfectly then I see that dead PC icon.
The phone shows as connected in the list of devices and if I close the screen window and click View again it works again for a bit and so on.

Thanks!

**Comment by koush** [comment]
Will investigate.

**Comment by koush** [comment]
Is this Vysor to Vysor, or Vysor to browser sharing?

**Comment by asyschikov** [comment]
@koush thanks for looking into this. I am using Vysor app on Mac (a Desktop app, cable and debug mode). I am not sure what is Vysor to browser and how to test it.

**Comment by koush** [comment]
When you are sharing, are you sharing to another computer with Vysor installed? Or is the person viewing the share viewing it in a browser (Vysor lets you share to another Vysor user OR to simply a Chrome user).

**Comment by asyschikov** [comment]
@koush The first one. I have Vysor app installed on my Mac.

**Comment by koush** [comment]
I see, there's some confusion. You're not talking about Vysor Share, which lets you share your Android screen with another user of the internet. You're saying the main use case, mirroring your Android to your Mac, fails after 30 seconds.
