### ISSUE TITLE
Error Installing APK

### ISSUE THREAD

**Issue by bmmy9f** [koush/vysor.io#425]
I keep randomly getting "error installing APK" when using Vysor in windows 10.  I never got the error with the exact same setup in windows 7.  Sometimes it works all day, sometimes it errors out every 2 minutes.  

What I have tried to fix it:
- Reinstall Vysor.
- Delete all temporary files.
- Kill ADB server and restart.
- Different USB ports and cables.

I have vysor pro and this issue is very frustrating.  Any help would be appreciated!

**Comment by koush** [comment]
Can you check Vysor 2.2.2?
