### ISSUE TITLE
Vysor Audio Output Instructions

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#426]
1. Click the Headphones button in the Vysor window in the desktop application.
2. (optional: may open automatically) Pull down the notification shade on the Vysor Android device.
3. (optional: may open automatically) Click Screen Cast
4. Click Vysor Audio Output in the list of Cast Devices

![Pixel_4](https://user-images.githubusercontent.com/73924/72673280-eabd6f00-3a1c-11ea-8268-a3e2a98e19e2.png)

![screenshot-1579399332690](https://user-images.githubusercontent.com/73924/72673275-dd07e980-3a1c-11ea-9138-95b3e8245e85.jpg)

![screenshot-1579399341970](https://user-images.githubusercontent.com/73924/72673287-00329900-3a1d-11ea-9683-f74e9cd8b20e.jpg)

**Comment by pakorn269** [comment]
Don't show Vysor Audio output!!

**Comment by KomOmOtE** [comment]
Instead of the notification pop up, I got a menu that is for screen mirroring called "smart view" and when I connect to Vysor Audio output, it didn't work, is there a way to fix this?

**Comment by iamgritt** [comment]
> Instead of the notification pop up, I got a menu that is for screen mirroring called "smart view" and when I connect to Vysor Audio output, it didn't work, is there a way to fix this?

I had the same problem. I also can't connect via wifi. It says error installing apk

**Comment by ComradeAaditya** [comment]
It's not working on my Samsung Galaxy A20. I get an error saying 'Casting screen to Vysor audio output has ended'.

I'm using a wire to mirror my phone on my PC (running Windows 10 Pro) but the audio is not being mirrored. The video works fine, however. I'm trying to cast via the Smart Things pop up. Why is this thing going south?

**Comment by iamgritt** [comment]
> It's not working on my Samsung Galaxy A20. I get an error saying 'Casting screen to Vysor audio output has ended'.
> 
> I'm using a wire to mirror my phone on my PC (running Windows 10 Pro) but the audio is not being mirrored. The video works fine, however. I'm trying to cast via the 'Smart Things' app pop up. Why is this thing going south?

I have the same problem. Made a separate thread for this one too. Hope this gets fixed to I can start streaming mobile games. If you're not gonna give me any refund.

**Comment by ComradeAaditya** [comment]
> > It's not working on my Samsung Galaxy A20. I get an error saying 'Casting screen to Vysor audio output has ended'.
> > I'm using a wire to mirror my phone on my PC (running Windows 10 Pro) but the audio is not being mirrored. The video works fine, however. I'm trying to cast via the 'Smart Things' app pop up. Why is this thing going south?
> 
> I have the same problem. Made a separate thread for this one too. Hope this gets fixed to I can start streaming mobile games. If you're not gonna give me any refund.

I have had no luck until now... Drop a comment here if you happen to find a way around this issue.

**Comment by AdvaitKale01** [comment]
I see the Vysor Audio Output but it keeps on saying Connecting and not gets connected. Device - POCO F1 Android 10

**Comment by yuis-ice** [comment]
"no nearby devices found" on the setting screen. not working.

**Comment by sunlei1989** [comment]
wow i need it!

**Comment by iamgritt** [comment]
> wow i need it!

It doesnt work dude. Audio does not work. I made a separate thread specifically for this issue. I wish this gets fixed because they're not responding to refunds or any email correspondence.

**Comment by ComradeAaditya** [comment]
Now I'm thinking Vysor to be a fraud.

**Comment by koush** [comment]
@ComradeAaditya The main issue here is that Samsung devices hide cast devices from their UI. And I'm unsure how to open cast mirroring on Samsung devices now. Investigating. Definitely use the splitter if you still have a 3mm jack.

**Comment by ComradeAaditya** [comment]
I do have the 3mm headphone jack but not the splitter. And it's not easily available where I live and they aren't doing online deliveries because of this lockdown.

**Comment by gittac** [comment]
Sometimes it doesn't work for me also.  Make sure USB is a data cable and
you are not connected through wi-fi to start..  Sometimes I have to close
my phone screen on my computer and then hit the earphone symbol again and
then sometimes there are drop outs of audio and then again you have to
close the phone screen on the computer and start it again.  I have gotten
audio through wi-fi but I'm not sure the circumstance that happens except
after it is through USB and after the phone on the computer is closed and
then started again on the wi-fi.

**Comment by selibio718** [comment]
Hello guys,
I have purchased a pro version of this software. At first, I have problems installing audio to sync with the screen share. I have found out that you need to go to google playstore and install the screen cast app. Once you installed it in your phone you can then use the vysor audio casting. That's it guys. Try it. mine here works. I am happy now sharing online videos using my phone including audio to it. :)

**Comment by selibio718** [comment]
Let me know if it works on your phone too.

**Comment by koush** [comment]
@selibio718 
can you tell me if you're using the native app or app.vysor.io?

**Comment by selibio718** [comment]
@koush I am using the vysor pro 2.3.0 for android and HP.

**Comment by ComradeAaditya** [comment]
> Let me know if it works on your phone too.

It's not working. I tried it yesterday but in vain.

**Comment by ComradeAaditya** [comment]
> @selibio718
> can you tell me if you're using the native app or app.vysor.io?

I'm also using the native Vysor applications for both PC and Android.

**Comment by ComradeAaditya** [comment]
> @koush I am using the vysor pro 2.3.0 for android and HP.

I too have an HP. Now I'm wondering if this issue is among HP and Samsung pair only..

**Comment by pikangie** [comment]
This is not really working for me either, on Nexus 6P. At least, on my phone's end, the sound is muted as it should... but as for my PC, there is no sound coming out no matter how high I turn the volume of both the PC and phone up.

**Comment by Bagogo2** [comment]
Hello, 
I have just purchased the app but the audio isn't working on my windows laptop. can't follow the instruction (android phone). when I press on the earphones icon the app asks me to follow the instruction and then it's open this "multi screen interaction" window on my phone which I can enable only if I turn on the wifi but still nothing shows there. It's a real shame as well as after setting the quality of mirroring to max it is still pretty low quality video and display plus the audio that didn't work.
Be happy to fix it, cause by now I'm really not happy with the software. I have just downloaded the software from the main web (file: Vysor-win32-ia32) and installed the recommended drivers. waiting for your replay. thank you

**Comment by selibio718** [comment]
You need to download screencast and use it. Then use USB debugging to make
fully functional. Try the earphone again and it will work. I have been
using it and find no problem in my laptop the audio from the phone is
clearly heated in my PC.

**Comment by Bagogo2** [comment]
Thank you for your reply. Download screencast to my phone or laptop? Do you have a link of a preferred one and free? I've seen that there are many screencast apps

**Comment by koush** [comment]
> This is not really working for me either, on Nexus 6P. At least, on my phone's end, the sound is muted as it should... but as for my PC, there is no sound coming out no matter how high I turn the volume of both the PC and phone up.
> Really a shame since the main reason I bought the Pro version was to stream mobile music games that I cannot play properly on the emulator, but that is pointless if I cannot stream any sound since they're music games specifically.

Can you try the version at app.vysor.io?

**Comment by pikangie** [comment]
@koush 
I just tried it now, but it is giving an error when I press view, saying: "SecurityError: Access Denied."
Does it require rooting? I cannot do that because the games I wanted to stream will not launch at all when the phone is rooted since the games block rooted devices. >.<

**Comment by koush** [comment]
@pikangie Are you on Linux? Can you make sure your udev rules are set up properly? There's instructions on the site. Please open another bug if you continue having issues, trying to keep this on topic.
