### ISSUE TITLE
[Request] VYSOR FULLSCREEN event implementation

### ISSUE THREAD

**Issue by vdegenne** [koush/vysor.io#428]
Could you please make a Vysor fullScreen toggle event code so one can toggle full-screen over a keyboard press (customizable in the keybindings file).
Thanks in advance.

**Comment by koush** [comment]
Added in 2.2.5.

Defaults:
```json
    "F3": "VYSOR_ENTER_FULLSCREEN",
    "F4": "VYSOR_EXIT_FULLSCREEN",
```

**Comment by vdegenne** [comment]
@koush My bad, I thought I had the last version. Thanks.
