### ISSUE TITLE
Crash after connect when no movement on screen

### ISSUE THREAD

**Issue by Panthaaaa** [koush/vysor.io#43]
When connecting to my device I see the loading animation and then the following crashes:
![vysor crash if no scrolling](https://cloud.githubusercontent.com/assets/1465893/9597677/75c50d42-5084-11e5-955f-3e1c6b96d9f6.PNG) ![vysor crash if no scrolling 2](https://cloud.githubusercontent.com/assets/1465893/9597678/75e447b6-5084-11e5-8f93-cc08c7e1578e.PNG)

This happens everytime no movement is visible on the screen. When I e.g. scroll through a list, it successfully connects.

**Comment by koush** [comment]
I believe this was fixed. Was related to the http h264 transport.

**Comment by Panthaaaa** [comment]
Which version corresponds to this fix?

**Comment by koush** [comment]
1057

**Comment by koush** [comment]
@Panthaaaa If it's not fixed, follow the instructions here for support

https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp

I think this was fixed though. Had another user report this same problem and it was fixed. Screen worked for a second then died. Was fine if scrolling.

**Comment by Panthaaaa** [comment]
Thanks for the information. If I encounter this bug again I'll report it with the necessary information.
