### ISSUE TITLE
Keybindings file is not updated on software update.

### ISSUE THREAD

**Issue by vdegenne** [koush/vysor.io#430]
> from my previous post [HERE](https://github.com/koush/vysor.io/issues/428)

I just wanted to report I tried to install `2.2.5` but only the `2.2.1` build for Linux was available. Then I installed it and on opening the software proposes to update for the latest version, which I did.  
Then it reopens and the `2.2.5` is installed.  
From here I checked the keybindings file to see if `F3` and `F4` shortcut where automatically added but it was not and I had to do manually. why ?  
Is this expected or is it something that you miss to implement or a bug ?  
Or is it because I edited my file previously so Vysor prevented to replace it automatically.

**Comment by Heretushi** [comment]
I would suspect it's to keep your edits.
I would personally not like to have my edits being overwritten, but I see the case where existing edits could be ignored and new functionality added. This would imply having to parse the files and add the functionality in there without affecting current edits. Seems feasible and a neat feature request. :)

**Comment by koush** [comment]
Correct, key bindings would be clobbered. Luckily it's very rare to have the defaults change. I think this was the first time in a few years.
