### ISSUE TITLE
Esc keybinding closes FullScreen mode

### ISSUE THREAD

**Issue by vdegenne** [koush/vysor.io#431]
**Describe the bug**
Pressing Esc key to go back while in FullScreen mode exits the mode. 

**Expected behavior**
When Pressing Esc (regardless the assigned keybind on this key) the FullScreen mode shouldn't be exited.

**Desktop (please complete the following information):**
 - OS: Linux - Fedora 31
 - Vysor Version : 2.2.5

**Comment by vdegenne** [comment]
Note: I didn't have this problem in previous versions. The problem occurred from the update.

**Comment by koush** [comment]
This did exist in previous versions (I just checked): it's an electron/OS requirement for full screened windows. AFAIK no way to change that behavior, it is to prevent a user from being stuck in full screen by providing a consistent way out.
