### ISSUE TITLE
Paste issue

### ISSUE THREAD

**Issue by timeakesmarky** [koush/vysor.io#434]
So, if I copy special characters and paste it to android (Ctrl + V) with the android keyboard as the input method, paste doesn't work, normal characters paste fine. (Even with international keyboard checked, paste doesn't work for special characters)

With Vysor as the input method, all characters paste fine.

**Comment by koush** [comment]
This is correct. International keyboard is required for special characters.

**Comment by timeakesmarky** [comment]
But international keyboard is checked and still the same issue with LatinIME.
Should I ONLY use Vysor as the input method to paste special characters? Won't it work with LatinIME?
