### ISSUE TITLE
Error 400 while logging into my account with the mac app

### ISSUE THREAD

**Issue by HozakaN** [koush/vysor.io#435]
**Describe the bug**
While clicking on login to retrieve my purchase, I get a dialog saying :
"Error retrieving auth token : Error: received status: 400

**To Reproduce**
This happens on any computer!
1. Use the chrome app
2. Connect and get a license
3. Download de mac app
4. Try to login

**Expected behavior**
The login dialog/stuff should appear

**Screenshots**
![Screenshot 2020-01-26 at 05 30 23](https://user-images.githubusercontent.com/1032452/73130730-48921e00-3ffe-11ea-8929-bee6cd3ea8cc.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 0.15.2 (19C57)
 - Vysor Version chrome app : 2.2.7, macOS app : 2.2.6

**Additional context**
After using the chrome app with success for a few years, I've downloaded vysor.app as adviced, a few years ago. I've never been able to connect the to mac os App to retrieve my purchase. Filling a bug for it only now.
To get back my purchase I'm trying to login by clicking on the login button.
I then get a dialog saying :
"Error retrieving auth token : Error: received status: 400

**Comment by koush** [comment]
Firewall or something? Did you log in first? The screenshot in the second pic indicates it is not logged in.

**Comment by HozakaN** [comment]
Let screenshot is chrome app. Right is macOS app. I can't login because when clicking on "login" I get this dialog.
I've tried on many wifi and hotspots, on two different Macbook Pro. None of them has any kind of special proxy/firewall settings.

**Comment by koush** [comment]
Can you generate a bug report for me after you get this error?

**Comment by HozakaN** [comment]
I've just done it.
Reading the logs, I've suspected having the chrome extension would mess the Google SSO system and prevent me from login into the desktop app.
Removing the chrome extension from my computer fixed the issue

**Comment by koush** [comment]
I've think I fixed this bug and will release an update soon. Another option is use Reset Vysor to clear old tokens.

**Comment by koush** [comment]
This was fixed, had to add bad token detection.

**Comment by HozakaN** [comment]
Thank you :D
