### ISSUE TITLE
Problem with Sign in with Google

### ISSUE THREAD

**Issue by fguilhon** [koush/vysor.io#437]
**Describe the bug**
I'm unable to log in with my Google Account on the application for Windows (not the Chrome extension). 

**To Reproduce**
I click "Login for offline usage and Vysor Share". 
A new windows appears. 
When I click the "Sign in with Google" nothing happens.

**Expected behavior**
It was supposed to open the browser for me to login with my account and then I would paste the code. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60481588/73474374-2cc7a880-436d-11ea-82b8-794f3cfd5594.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link:

**Vysor Bug Report**
https://gist.github.com/df4f8f53860f54d3eafe99354f93a2b8

**Comment by koush** [comment]
It seems to be having an issue opening your default browser. What is your default browser?

**Comment by fguilhon** [comment]
Thanks for your reply! The default browser on Windows was set to "Launch Windows App". I changed to "Google Chrome" and now it worked.

**Comment by lk77** [comment]
Hello,

i have the same issue, my default browser is chromium
