### ISSUE TITLE
Audio mirroring doesn't work (Xiaomi redmi note 8 pro)

### ISSUE THREAD

**Issue by spukylychee** [koush/vysor.io#438]
No matter how hard I try I cannot get the audio mirroring to work, I already checked the cast option on for Vysor 

![screenshot-1580764465022](https://user-images.githubusercontent.com/60627394/73691541-28b2c800-4698-11ea-9208-0e196d00d80e.jpg)

however my phone won't detect Vysor as a cast device

![screenshot-1580764446473](https://user-images.githubusercontent.com/60627394/73691594-43853c80-4698-11ea-83ac-115be4271045.jpg)

I have MIUI 11 and honestly since switching from my old Zenphone 3 I haven't really been able to figure out with this Xiaomi piece of dookie won't cast to anything unless it's youtube.

**Comment by koush** [comment]
What version of Android?

I'll be updating Vysor sometime soon to support the native Audio capture support in Android 10. That will remove the Google Cast requirement.

**Comment by spukylychee** [comment]
> What version of Android?
> 
> I'll be updating Vysor sometime soon to support the native Audio capture support in Android 10. That will remove the Google Cast requirement.

Android 9.

**Comment by spukylychee** [comment]
but according to some sources I should be getting android 10 soon

**Comment by koush** [comment]
It seems MIUI doesn't properly integrate the remote display framework, as cast devices should be showing up in that list. In Android 10, I'll be able to use the native audio capture. That still needs to be implemented.

**Comment by koush** [comment]
Marking this as wontfix, since it's unfortunately not possible. Story will be different once android 10 rolls around.

**Comment by spukylychee** [comment]
android 10 has been released, audio mirroring works while on USB mode, strangely wireless mode stopped working for my xiaomi device

**Comment by koush** [comment]
Ok I will take a crack at it

**Comment by koush** [comment]
See here: https://github.com/koush/vysor.io/issues/582

Use the Android 10 audio checkbox available in 3.0.97.
