### ISSUE TITLE
Cannot install Vysor for Mac (2.2.2) on macOS Catalina (10.15.2)

### ISSUE THREAD

**Issue by MediumOne** [koush/vysor.io#439]
**Describe the bug**
Installation of "Vysor for Mac" (2.2.2) fails on MacBook Pro running macOS Catalina (10.15.2) with the error - 'Vysor cannot be opened because Apple could not check it for malicious software. The software needs to be updated. Contact the developer for more information'

**To Reproduce**
1. Download Vysor for Mac from https://www.vysor.io/download/
2. Extract zip and double-click to install/open.
3. Observe the error shown in the screenshot.

**Expected behavior**
Vysor should be installed.

**Screenshots**
<img width="671" alt="Screen Shot 2020-02-05 at 2 40 52 PM" src="https://user-images.githubusercontent.com/12625980/73827589-d6071680-4825-11ea-94f0-b60f087ae327.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Vysor Version - 2.2.2

**Comment by koush** [comment]
Please control click the file to allow it to open. I'll properly sign the next release.

**Comment by koush** [comment]
The new builds are notarized. This is fixed.
