### ISSUE TITLE
Connection works but screen is shown oddish

### ISSUE THREAD

**Issue by GaboFDC** [koush/vysor.io#44]
Y just installed it.

SO: Ubuntu 14.04.3 LTS
Device: XT1040
Chromium Version 43.0.2357.130 

![screenshot from 2015-09-02 18 33 30](https://cloud.githubusercontent.com/assets/1425500/9647471/fc60ba44-51a2-11e5-9bb0-25a5f1bc5732.png)

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/3
