### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by vitich** [koush/vysor.io#441]
I tried the versions Vysor_2.2.1_amd64.snap and Vysor_2.3.0_amd64.snap but still get a black screen.

**Comment by koush** [comment]
How many graphics cards and what types? And how many monitors?

**Comment by vitich** [comment]
> How many graphics cards and what types? And how many monitors?

One card and two monitors

**Comment by koush** [comment]
Can you try the new progressive web app beta here:
https://app.vysor.io
I want to verify this is fixed.

Native apps coming soon.

**Comment by koush** [comment]
Fixed with new webassembly decoder.
