### ISSUE TITLE
Windows 10 black screen on ONE user account

### ISSUE THREAD

**Issue by kevin-lot** [koush/vysor.io#442]
**Describe the bug**
2 Windows 10 user accounts (on same PC), with one Vysor works, not with the other.

**Expected behavior**
I don't know, maybe an issue with a video codec. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version: 2.3.0
**Android (please complete the following information):**
 - Device: OnePlus 3t or Xiaomi Red Note 7
 - Vysor Bug Report Link: no bug reported

**Vysor Bug Report**
To retrieve a bug report, in the desktop application, click the bug report button to generate the report. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

**Additional context**
All accounts are locals. one account is administrator, the other WAS normal (switched to administrator).

**Comment by koush** [comment]
Wow. That is wild. Which one works, the admin or normal user?

**Comment by koush** [comment]
And what do you mean "does not work"? Does it detect the device on both?

**Comment by kevin-lot** [comment]
Both accounts detect smartphone.
The mirror view launches on both accounts too.

The mirror view works on administrator account.
The mirror view is black (without error) on other account.

Same effect with 2 phones, one is OnePlus 3t and the other is Xiamoi RedMi Note 7.

**Comment by koush** [comment]
Can you generate a bug report? There may be more logging in there that might indicate why its not working.

Does clicking on the black screen work send the clicks to the phone on the non-admin account?

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/441
