### ISSUE TITLE
Vysor on Linux: "Error installing APK:"

### ISSUE THREAD

**Issue by dtkettler** [koush/vysor.io#443]
I'm trying to run Vysor on Linux using the AppImage release from https://github.com/koush/vysor.io/releases/tag/continuous

The program starts and my device is detected.  But when I click on the green 'View' button I get the error: "Error installing APK:"  That's literally all it says.  You'd think there would be something after the colon but...there isn't.  Never does it say specifically what the error is.

So I tried installing Vysor directly on my phone from the Play store.  If I run that app on my phone I get to the point where it says "Open Vysor on your Computer" and...that's it.  Vysor is open on my computer, my device is successfully detected, but nothing happens.

I have previously successfully used my phone with the "scrcpy" program without issue so I know it should be set up with USB debugging and all that however scrcpy doesn't do audio so I thought I would give Vysor a shot but I'm kind of stuck here.  It's given me so little feedback I can't even tell where the problem is...

**Comment by koush** [comment]
Can you generate me a bugreport using the link in the desktop app?

**Comment by patggg** [comment]
I just sent bug report from the desktop app on linux. I was using vysor to view my odroid and the android reset, this never happens. I also got a message that there was a new vysor build. After reboot when trying to connect I get an APK install error. I toggled USB debugging on the device and tried several more times to connect, same issue every-time. I checked the downloads and see that there is a 2.3.1 ( I am running 2.3.0) but there is no snap. Do I need to make my own snap or is the package coming?

Oddly enough, I decided to try on my mobile and the desktop app can connect to it. The mobile is running Android 8 vs 9 on the odroid.

**Comment by patggg** [comment]
After viewing the bug report I see on APK install "...Requested internal only, but not enough space". I had been recording some video and filled my storage space. I cleaned up and it is working now. Nothing to see here :)

**Comment by MattBuck1227** [comment]
I am getting the same error message when attempting to install on Android tablets. The last one that I tried and it failed has almost 10GB of free space on it (that should be plenty of room for the SDK to install).

We are trying to roll this out for remote work and the ability to provide support to our users using tablets and need for this work.

**Comment by akshun-j** [comment]
> I'm trying to run Vysor on Linux using the AppImage release from https://github.com/koush/vysor.io/releases/tag/continuous
> 
> The program starts and my device is detected. But when I click on the green 'View' button I get the error: "Error installing APK:" That's literally all it says. You'd think there would be something after the colon but...there isn't. Never does it say specifically what the error is.
> 
> So I tried installing Vysor directly on my phone from the Play store. If I run that app on my phone I get to the point where it says "Open Vysor on your Computer" and...that's it. Vysor is open on my computer, my device is successfully detected, but nothing happens.
> 
> I have previously successfully used my phone with the "scrcpy" program without issue so I know it should be set up with USB debugging and all that however scrcpy doesn't do audio so I thought I would give Vysor a shot but I'm kind of stuck here. It's given me so little feedback I can't even tell where the problem is...

Same problem here on the latest Linux Mint.  However, I generated a bug report and then read through the log.  I noticed the error log was reporting that the version of ADB packaged in the Vysor app did not have device permissions for my phone.  I had to install ADB and package called "adb-sdk-platform-tools-common":

This package provides common files of Android SDK Platform-tools. It also
provides UDEV rules enabling adb and fastboot to work without root access to
the host machine.

After that, connection worked fine

**Comment by koush** [comment]
So, i ran into this permission bug and have more explicit instructions about the udev rules, and also added better error reporting on failures. So it won't fail silently with dumb errors like "Error installing apk".

**Comment by koush** [comment]
In the meantime you can try the new progressive web app beta here:
https://app.vysor.io

Native apps coming soon.

**Comment by koush** [comment]
New native apps were released.
