### ISSUE TITLE
Vysor Wireless Connection to Mobile Device

### ISSUE THREAD

**Issue by iamgritt** [koush/vysor.io#445]
When i try to connect via wifi by pressing the wifi icon, it creates a window that is black and then prompts that there is an error in installing APK. Then it ends there. It doesn't work.

 - OS: Windows
 - Vysor Version 2.3.0

 - Mobile OS: Android

![Screenshot_41](https://user-images.githubusercontent.com/62171264/76678913-e83f5600-6616-11ea-943c-34489e60065b.png)
![Screenshot_42](https://user-images.githubusercontent.com/62171264/76678914-e9708300-6616-11ea-9822-fa355c4c4f34.png)
![Screenshot_43](https://user-images.githubusercontent.com/62171264/76678915-e9708300-6616-11ea-8d9b-9d2e4793d840.png)

Bug Report: https://gist.github.com/88bd4d0609755142688d9c35c71a24b0

**Comment by ultrajounin** [comment]
I am having the exact same problem using Pixel 3a 64gb on Android 10

**Comment by koush** [comment]
Fix coming.

**Comment by Unisykolist** [comment]
Sam here. Version 2.2.2. Keen for the fix.

**Comment by koush** [comment]
Please test the prerelease here https://github.com/koush/vysor.io/releases/tag/v3.0.33

**Comment by d4v1dv00** [comment]
running 3.0.57, after showed wireless connected and unplug phone and not working anymore. often take a couple of try to get wireless working.
