### ISSUE TITLE
Samsung: Smart View - Not compatible with Audio Cast from Vysor?

### ISSUE THREAD

**Issue by iamgritt** [koush/vysor.io#446]
After following the instructions, I am stuck with connecting via my phone prompt message to connect to Vysor Audio Output. However, it doesn't connect. It just keeps on trying to connect and then suddenly disappears from available devices until I repeat the process.

Another scenario is when I try to connect, a message shows that Audio Output starts and then ends right after.

 - OS: Windows 10
 - Vysor Version: 2.3.0

 - Device: Samsung
 - OS: Android Latest Version

**Vysor Bug Report**
https://gist.github.com/88bd4d0609755142688d9c35c71a24b0

**Comment by Grant1235** [comment]
I'm having the same problem. Just downloaded Vysor (and paid for a lifetime license just to get the audio feature).  Connected via Wifi, device shows up, but it just thinks for a minute then disappears from the list.

I'm on Mac, running Android on my phone.  Please resolve this.  Should also make this feature free since so many people seem to be having trouble with it, and we only figure this out after paying.

**Comment by iamgritt** [comment]
> I'm having the same problem. Just downloaded Vysor (and paid for a lifetime license just to get the audio feature). Connected via Wifi, device shows up, but it just thinks for a minute then disappears from the list.
> 
> I'm on Mac, running Android on my phone. Please resolve this. Should also make this feature free since so many people seem to be having trouble with it, and we only figure this out after paying.

Does it take this long for them to reply here? Contacted Vysor support via email and to no avail did I get any feedback.

**Comment by ComradeAaditya** [comment]
They should either fix the issue immediately or remove the feature completely. But since most of the subscribers have paid for this feature, they should fix it IMMEDIATELY!

**Comment by koush** [comment]
I'm sorry, what is samsung smart view? Please try the new beta. The audio feature was completely rewritten and is more reliable. Native apps coming soon. https://github.com/koush/vysor.io/issues/456
