### ISSUE TITLE
My vysor wont unsubscribe keeps on charging me

### ISSUE THREAD

**Issue by dyc1978** [koush/vysor.io#447]
Please help me unsubscribe to vysor. I tried it and finished my 1 month subscription. I tried to click on unsubscribe but it still keeps on charging me. My email is danielyching@gmail.com i dont want to use it anymore. Pls fix your unsubcribe button.

**Comment by koush** [comment]
I'm seeing no active subs (it was cancelled). You were charged once and the second charge failed, which caused the cancellation.
