### ISSUE TITLE
Install to shared devices`

### ISSUE THREAD

**Issue by akarupp4-ford** [koush/vysor.io#449]
I'm pro user. I'm seeing my devices in remote machine (even in Android Studio @ remote machine) but not able to install apk from remote machine. Am i missing any thing here?

`adb install app-debug.apk` says
`failed to copy 'app-debug.apk' to '/data/local/tmp/app-debug.apk': couldn't read from device`

I tried accessing through android studio's device file explorer. It still opens and its showing file in the path.

**Comment by koush** [comment]
I'll look into this.

**Comment by koush** [comment]
Hello, I believe this issue was resolved in the prerelease version of Vysor, if you don't mind testing. Will need to update both the remote and local Vysor clients. Confirmed that both adb install and drag and drop apk install works.

https://github.com/koush/vysor.io/releases/tag/v3.0.33
