### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by fird01** [koush/vysor.io#45]
Black screen. Mouse and keyboard works.

Window 10
galaxy note 2 ( GT-n7100)
cm12.1
vysor version 1.0.5.2
phone is rooted

screen.html log http://pastebin.com/raw.php?i=YwBFAavS
background.html log http://pastebin.com/raw.php?i=eCURCG1B

**Comment by koush** [comment]
can you check if screenrecord works? You familiar with that tool?

**Comment by fird01** [comment]
yeah screen records works..
/ $ screenrecord test1
Unable to open 'test1': Read-only file system
/ $ cd /sdcard
/mnt/shell/emulated/0 $ screenrecord test.mp4
^C/mnt/shell/emulated/0 $

**Comment by koush** [comment]
did you check if hte file actually plays?

**Comment by koush** [comment]
It may look like it's working, but please confirm the file plays. Sometimes it records an empty file, or a file that is just a recorded black screen....

**Comment by fird01** [comment]
Yup the file plays. File is not empty.

**Comment by koush** [comment]
have google+ or hangouts? can you tag me in a private post and i can debug the problem with vysor share.

**Comment by ankushdas9** [comment]
I have the same issue sir.
Device: Micromax Unite 2
Android 5.1
ADB Driver installed | Windows 8.1
As you asked the previous user, the screen recording works on my device too. I use AZ Recorder to record pictures.
Device status: Rooted using Kingroot..

**Comment by TheWint** [comment]
I had the same issue and re-sizing the Vysor window on my computer so it fits the whole thing in the pc screen everything works fine, if i resize it and some part of the window is of the screen it just get's stuck again. I am pretty sure this is the same issue.

**Comment by koush** [comment]
Tracked this black screen issue down to CyanogenMod's media codecs.

**Comment by koush** [comment]
This black screen can also occur if running CyanogenMod. The default video encoders use h264 high or main instead of h264 baseline. Unable to fix it.

Does the SGS3 stock have kitkat or newer? Do you mind trying that and seeing if it works. Would be immensely helpful.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/50

**Comment by ankushdas9** [comment]
What about my Micromax Unite2? Running on Lollipop? The same thing with S3?

**Comment by kimusan** [comment]
I see the same problem with nexus6 running aosp build. My nexus5 works fine and so does my SGS Note4. 
Windows7 + koush universal adb driver

**Comment by bigthugs0** [comment]
i have nexus 6 with Android 6 Rooted 
it works , but sometimes it gives blankscreen but everything is working
i try unlplug the cable , kill adb and start it again , still blank screen

im linux ubuntu 15.10

**Comment by arnaud-ramey** [comment]
Hello!
Phone: Samsung Galaxu SIII (GT-I9300) with a broken screen.
OS: CyanogenMod 11 (Android 4.4) with root access
I'm trying Vysor to get the screen output on the PC, as the phone screen is broken.

However, I'm having this black screen problem in Vysor.

- "screenrecord" generates an empty 6k file.

- $ screenshot /sdcard /test.png                                                                                                                           
error: could not read framebuffer

@koush pointed out it might be a H264 incompatibility between Vysor and CM
Any advance on that?
If you need, I can supply more bug report data.
Thanks for the hard work anyway :)
Thanks!

**Comment by spupuz** [comment]
have same problem black screen with version 1.0.7.1 ubuntu 16.04 and chrome Version 52.0.2729.3 dev (64-bit) ha no problem before with version 1.0.6.7.
the windows is black and i can click with mouse but i see nothing.

**Comment by kyleduo** [comment]
Same issue, Mac + Chrome 49.0.2623.87 (64-bit) + Nexus5 6.0 rooted. Black screen but i can control the device.

**Comment by spupuz** [comment]
@kyleduo i'm not a mac expert does it has a nvidia graphic card?

**Comment by kyleduo** [comment]
Yes, it has. I've used vysor 1 or 2 month ago with older Android version and worked well, but "black screen" today. I can not figure out whether is the problem of new Android version or the new version of vysor(I updated today).

**Comment by spupuz** [comment]
can you post the driver version and a screenshot?

Il giorno lun 23 mag 2016 alle ore 10:21 kyleduo <notifications@github.com>
ha scritto:

> Yes, it has. I've used vysor 1 or 2 month ago with older Android version
> and worked well, but "black screen" today. I can not figure out whether is
> the problem of new Android version or the new version of vysor(I updated
> today).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/vysor.io/issues/45#issuecomment-220916241>
>
-- 
Alessandro Belloni

**Comment by kyleduo** [comment]
@spupuz I checked my system info panel and found this. Is this the answer.
```
NVIDIA GeForce GT 750M：

  芯片组型号：	NVIDIA GeForce GT 750M
  类型：	GPU
  总线：	PCIe
  PCIe Lane 宽度：	x8
  VRAM（总和）：	2048 MB
  供应商：	NVIDIA (0x10de)
  设备 ID：	0x0fe9
  修正版 ID：	0x00a2
  ROM 修正版：	3776
  gMux 版本：	4.0.8 [3.2.8]
```
<img width="827" alt="2016-05-23 4 34 44" src="https://cloud.githubusercontent.com/assets/7019092/15464904/59da78f0-2104-11e6-8c2a-43bb93cc448e.png">

**Comment by spupuz** [comment]
same behavior of me but i'm using Ubuntu 16.04 with chrome Version 52.0.2739.0 dev (64-bit) and  361.42 nvidia propietary 

https://goo.gl/photos/Z4LD4TJ1x5nTqgd5A

@koush any evidence?

**Comment by koush** [comment]
Thanks for the report, but this isn't the troubleshooting/support forum. More info would be helpful:
https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp

My first guess is that your graphics drivers are not completely up to date, and native client's graphics 3d is crashing.

Check if this site works:
https://gonativeclient.appspot.com/demo/cube

PLEASE put all further comments on the support forum I linked, as it is easier for me to follow up with stuff there.

**Comment by kyleduo** [comment]
@koush Cube doesn't work, could you please tell me how to get my graphics driver version?

**Comment by TimJung** [comment]
This solution worked for me when I noticed the link (https://gonativeclient.appspot.com/demo/cube ) wasn't working. 

Enable Hardware Accelerated Graphics In Chrome:
1. chrome://settings -> Show advanced settings.
2. Here, you will find an option “Use hardware acceleration when available”.
3. Just check it and restart the browser. This should solve the problem.

**Comment by koush** [comment]
@TimJung thanks so much, I'll add that to the troubleshooting guide.

**Comment by kyleduo** [comment]
The option is checked on for me but the cube does't show up.

**Comment by TimJung** [comment]
I saw another user claim it was fixed by disabling it. So yeah not really sure what's going on with it but toggling it seems to do... something. Could also be a combination of options or your issue might be specific to your specific environment.

**Comment by kyleduo** [comment]
I'll try your suggestion, but vysor just worked ok a few weeks ago and I haven't change any of these options.

**Comment by kyleduo** [comment]
I disable the hardware options but nothing changed.:(

**Comment by spupuz** [comment]
I will try to do the same on my Linux Ubuntu an let know

Il gio 26 mag 2016, 06:33 kyleduo <notifications@github.com> ha scritto:

> I disable the hardware options but nothing changed.:(
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/vysor.io/issues/45#issuecomment-221775141>
>
-- 
Alessandro Belloni

**Comment by kyleduo** [comment]
@koush I found out that pnacl component was not installed in my chrome, so the screen is black. Do you have any suggestions to installing that?

**Comment by kyleduo** [comment]
Finally I found [this website](https://support.asperasoft.com/hc/en-us/articles/216126728-Corner-case-Connect-issues-on-Chrome-45-and-higher) and known how to install manually. After copy paste these files from another mac, I solved the problem. And, to check pnacl status, visit [chrome://nacl](chrome://nacl).

**Comment by TimJung** [comment]
Impressive detective work @kyleduo

**Comment by koush** [comment]
@kyleduo That's weird. pnacl should be installed by default.  Did you see a message in the logs that it was not installed?

**Comment by kyleduo** [comment]
Chrome does can install pnacl itself, BUT this component is not in the Chrome installer. Pnacl needs to be installed after chrome installation on demands. [link](https://www.chromium.org/nativeclient/pnacl/introduction-to-portable-native-client) [link2](https://groups.google.com/forum/#!topic/native-client-discuss/HkMvnp0w7U0). I really can not understand Chrome's strategy.

**Comment by LeiYangGH** [comment]
same issue with chrome's latest version, win8.1 x64, win7 x64. Devices are LG g3, Xiaomi.com.

**Comment by koush** [comment]
Locking this conversation. See here for possible resolutions.

https://plus.google.com/110558071969009568835/posts/BGUH6yojfSf
