### ISSUE TITLE
Auto rotate issue

### ISSUE THREAD

**Issue by timeakesmarky** [koush/vysor.io#450]
Every time my phone is disconnected, the auto-rotate setting is turned on. Vysor must revert it before closing.

**Comment by crouchingtiger** [comment]
Having the same issue on 2.3.1, Google Pixel 2 XL.

**Comment by koush** [comment]
Yeah, Vysor does do that on teardown, because auto rotate is typically the default and Vysor may have rotated the screen. I'll need to think about how to deal with this.

Thanks for the report.

**Comment by jerwarren** [comment]
Maybe only change rotation settings if the user initiated a rotation via Vysor?

**Comment by koush** [comment]
@jerwarren yeah, that's the plan. Will need to do an apk update since that lives on the Android side.

**Comment by koush** [comment]
tracking
https://github.com/koush/vysor.io/issues/510

**Comment by koush** [comment]
for discussion https://github.com/koush/vysor.io/issues/510#issuecomment-629412304
