### ISSUE TITLE
broke android viewers assert !context_->is_null()

### ISSUE THREAD

**Issue by calisro** [koush/vysor.io#451]
THe latest update broke all my android TV and fireOS devices.  These include the nvidia shield and fire TV/sticks.  I get the error 

Graphics error: assert !context_->is_null()

**Comment by koush** [comment]
This issue is graphics related, and not anything to do with Vysor. Might be a second monitor or graphics card on your system not supporting webgl.
Please try out the new beta though, which does not have the webgl requriement: https://app.vysor.io

**Comment by calisro** [comment]
I've been connecting to 3 sets of these devices for years.  Then vysor upgraded and broke the connectivity to all 3.  They are 3 different vendors (Mibox S, Nvidea Sheild, and fireTV.  All broke on the Vysor upgrade.  There are no additional monitors or different graphic cards.  If it has nothing to do with Vysor, then why all of a sudden does none of the Android TV devices function when they are all different vendors?

**Comment by calisro** [comment]
https://app.vysor.io doesn't see any of my devices.  The chrome app does though (but doesn't work) so i'm dead in the water.

**Comment by koush** [comment]
Hey @calisro 
Can you confirm you clicked "connect android usb device"? the device needs to be approved for use by the vysor website first.

**Comment by koush** [comment]
![Vysor](https://user-images.githubusercontent.com/73924/79382554-85442600-7f18-11ea-804b-d1d87e56dc6c.png)
![app_vysor_io_wants_to_connect_and_Vysor](https://user-images.githubusercontent.com/73924/79382591-92611500-7f18-11ea-9335-fd24d7aac83e.png)

**Comment by calisro** [comment]
Yes I did.  Now maybe this interface works differently but previously I was able to do this.  I previously was able to drop to a linux shell and run

# adb connect 10.100.1.143
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 10.100.1.143:5555

(click authorize on the android TV the first time).

ADB would connect to the device and then I could connect from the chrome app. Does app.vysor.io ONLY connect via USB now?  The android TV devices are all wireless adb.  I noticed this and made me think...  

![Screenshot_2020-04-15_16-01-21](https://user-images.githubusercontent.com/5018276/79383059-8bdf9700-7f32-11ea-9c69-70629a7dc304.png)

**Comment by calisro** [comment]
I just tried the AppImage and that actually worked just fine.  That's good news.  I can use that instead of the chrome extension which is going away anyway.

**Comment by koush** [comment]
I see now. You're connecting to a tcp device. The new beta web app only supports usb devices (as there's no way to access tcp via web yet).
The new native app will support tcp devices (adb connect). That will be released soon as well.

**Comment by koush** [comment]
And yeah, wireless adb won't work with the web app for the same reason.

**Comment by calisro** [comment]
This is fine.  Thanks for the help and I see as well.  Makes sense.
