### ISSUE TITLE
Audio Mirroring from Fire TV

### ISSUE THREAD

**Issue by Cynthtastic** [koush/vysor.io#452]
I purchased the paid version for the sole purpose of getting Fire TV audio and video, but the audio mirroring still does not work.  When I click the headphones, I get a message stating Vysor is waiting for the audio stream and linking me to instructions that are not applicable to Fire TV; it does not have audio output settings (as far as I can determine).  I have tried wifi instead of wired connection, since another issue indicates audio mirroring only works over wifi.  Nothing helps.  Can someone please tell me how to set up audio mirroring for Fire TV in Vysor?  Thank you.

![image](https://user-images.githubusercontent.com/62821654/77838350-30936380-7141-11ea-9e74-41572137ecc6.png)

**Comment by koush** [comment]
Fire TV does not have google cast built in. If Fire TV updates to Android OS version 10, it may be possible ,but I'll need to implement a new mirroring method.
