### ISSUE TITLE
[Feature request] Change device model for adb on Vysor emulator name change from settings

### ISSUE THREAD

**Issue by oiuldashov** [koush/vysor.io#453]
Hello.

I have a feature request for Vysor.

When I am changing in Vysor settings Name of emulator
![picturemessage_kbmtwoyz fmx](https://user-images.githubusercontent.com/10095333/77952880-05417d80-72d5-11ea-8c7c-ce254e24e09c.png)
It doesn't changes in adb
![picturemessage_wbusjbfl t4h](https://user-images.githubusercontent.com/10095333/77952807-e5aa5500-72d4-11ea-8eec-063a9fa1d4d7.png)

Can you tell me is it possible to change for adb model using name from Vysor settings?
Can you add this feature?

**Comment by koush** [comment]
Sorry, that is not possible. The vysor change is cosmetic only.
