### ISSUE TITLE
Vysor Audio Output not working (Android 7.1.2)

### ISSUE THREAD

**Issue by Siress** [koush/vysor.io#455]
Screen mirror in Windows crashes after clicking on the headphone GUI in Vysor.

Initiate a screen mirror with the Windows 10 Vysor application. Can be wired or wireless.
Click on the headphone button in the Vysor GUI.

**Expected behavior**
This all happens without further action on my part, and is very repeatable => Cast app pops up, Vysor Audio Output option exists, screen mirror on Win10 loses connection to the phone, Vysor Audio Output option goes away.

I played around with this and manually selected the Vysor Audio Output option while it was on screen. Several times I got a pop-up in Win10 about 'failed to install APK'. It's in the bug report.

Any support on this topic? Seems like it's not working for a lot of users...

**Screenshots**
https://i.imgur.com/KgpGLsF.gif

**Desktop (please complete the following information):**
 - OS: Win 10 build 1809
 - Vysor Version 2.3.0

**Android (please complete the following information):**
 - Device: Moto G5 Plus
 - OS: 7.1.2
 - Vysor Bug Report Link: NA

**Vysor Bug Report**
https://gist.github.com/VysorLogs/2f648bd1d6b4d7350d406d5cabd54e28

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by iamgritt** [comment]
Still no update huh? Maybe this should be reported to the authorities.

**Comment by koush** [comment]
Lol, nah I've been working on this. Check this issue out to try the beta.

https://github.com/koush/vysor.io/issues/456
