### ISSUE TITLE
Audio gets dropped

### ISSUE THREAD

**Issue by dhust** [koush/vysor.io#456]
**Describe the bug**
After about 20 minutes of streaming the audio will stop. This happens every time I use it.

**To Reproduce**
1. Start the program
2. Click on the headphone icon
3. Choose to cast to Vysor
3. Wait 20 minutes

**Expected behavior**
The audio shouldn't stop working.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 2.3.0

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10

**Comment by koush** [comment]
Hey, I've rewritten the audio mirroring in the upcoming version. Feel free to try out https://app.vysor.io and let me know if it works any better.
Please be aware that that is a Progressive Web App, the new native apps are coming soon too.
If it works, the PWA can be installed to the desktop via Chrome via the 3 dots and then Install Vysor menu option.

Can't have the ADB server or desktop vysor running (obviously this won't be an issue with the new native apps though).

**Comment by gittac** [comment]
Yes, I have this issue also, but the time seems to be always different for
when the audio drops out.  Sometimes it's hours and sometimes it's
minutes.  I think it's my computer or wire sometimes.  I am just living
with it.  What I want to know is, why doesn't the audio work for phone call
and can you work for the microphone in my computer to the phone?

**Comment by SuriAttacker** [comment]
@koush for some reasons the new web app can't detect my mobile..... while on the desktop application it does... so I can't try out the new version. Any solution on how to fix this issue?

**Comment by koush** [comment]
@SuriAttacker Can you open a new bug, and include the javascript console log from the new web app?
