### ISSUE TITLE
License lost

### ISSUE THREAD

**Issue by fr500** [koush/vysor.io#458]
Hi

I purchased a lifetime license a long time ago.
I used to login in the Chrome App and in the desktop one just fine with that.

Now it says there is no license for my gmail account.
What's going on?

**Comment by fr500** [comment]
FWIW it works in chrome just fine. Just not on the desktop app

![imagen](https://user-images.githubusercontent.com/1721040/78620703-56f28680-7846-11ea-95d1-d4749eac5844.png)

**Comment by koush** [comment]
Will investigate.

**Comment by fr500** [comment]
Thank you

**Comment by koush** [comment]
I think this was a certificate error. Can you verify it is fixed now?

**Comment by fr500** [comment]
Yes! it works now, thanks a lot!
