### ISSUE TITLE
Request to transfer license to another Google account

### ISSUE THREAD

**Issue by littlemissred** [koush/vysor.io#459]
Hi! I would like to transfer my individual license to a different Google account, would that be possible?
Many thanks!

**Comment by koush** [comment]
Is it a lifetime or a subscription?

**Comment by littlemissred** [comment]
Dear Koushik,

It is just an annual subscription

Many thanks!


Cheers,
Dawn.

**Comment by Heretushi** [comment]
Is this done ? :o

**Comment by koush** [comment]
Subscription licenses are not transferable.
