### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by thorpj** [koush/vysor.io#46]
As mentioned by others, black screen, changing to landscape works as normal and controlling the phone works, but vysor on my PC shows a black screen.

Windows 10 Home
Samsung Galaxy S3
AICP Lollipop 5.1.1
1.0.5.2
Rooted
Using latest ADB driver from http://koush.com/post/universal-adb-driver

Vysor extension inspections:
Screen.html : http://pastebin.com/vVr5QRUY
background : http://pastebin.com/jBJJxRHw

**Comment by TheWint** [comment]
I have the same Issue but if i make my Vysor window smaller so it fits in the pc screen it works fine

**Comment by thorpj** [comment]
@TheWint I tried resizing the window. it started as a small window that fit on the screen, and it didn't seem to work for me.

**Comment by koush** [comment]
Is this CyanogenMod based ROM?

**Comment by thorpj** [comment]
@koush Yes it is, here's the XDA thread [ http://forum.xda-developers.com/galaxy-s3/development-i9305/rom-aicp-8-0-t3053000 ]

**Comment by koush** [comment]
This black screen can also occur if running CyanogenMod. The default video encoders use h264 high or main instead of h264 baseline. Unable to fix it.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/50

**Comment by thorpj** [comment]
@koush The stock firmware for my S3 goes up to Android 4.3. Sorry

**Comment by koush** [comment]
@thorpj Please test on stock firmware, not AICP.

**Comment by koush** [comment]
@thorpj https://github.com/koush/vysor.io/issues/50

**Comment by thorpj** [comment]
#koush Sorry, i can't do that.

**Comment by spupuz** [comment]
have same problem black screen with version 1.0.7.1 ubuntu 16.04 and chrome Version 52.0.2729.3 dev (64-bit) ha no problem before with version 1.0.6.7.
the windows is black and i can click with mouse but i see nothing.

**Comment by LeiYangGH** [comment]
same issue in win8.1 x64, win7 x64. android 4.x, LG g3.

**Comment by koush** [comment]
Locking this issue, please see here for possible resolutions:

https://plus.google.com/110558071969009568835/posts/BGUH6yojfSf
