### ISSUE TITLE
Vysor shows a distorted projection of the screen

### ISSUE THREAD

**Issue by timeakesmarky** [koush/vysor.io#461]
I just got a phone, Huawei P9 Lite and Vysor is showing the screen all distorted as on this image.

Tried different settings; Software, Hardware and Hardware fallback but the same issue

![image](https://user-images.githubusercontent.com/7058205/79329214-06111b00-7f35-11ea-909c-72d2a823c617.png)

**Comment by koush** [comment]
Can you try setting the resolution to 100% in vysor settings on the desktop app

**Comment by timeakesmarky** [comment]
Oh, it works.
Even 25%, 50% and 75% works. Just the "Use recommended settings" options gives the distorted screen.

Now the screen freezes sometimes. My settings are just 1Mbit.

**Comment by koush** [comment]
closing this since other settings works. the recommended settings having distortion is likely a manufacturer bug.
