### ISSUE TITLE
Fullscreen reverts to maximized.

### ISSUE THREAD

**Issue by nulref** [koush/vysor.io#462]
When I click Fullscreen Mode in the settings window, Vyzor goes into fullscreen for about 1 second then reverts back to minimized mode. Then a pop up window appears saying "Vyzor has been maximized. If You wish to enable Fullscreen Mode, it can be enabled in Settings."

Note: I have purchased a license.

1. Maximize Vyzor
2. Click on Settings
3. Check the Fullscreen Mode box
4. Vyzor goes fullscreen then reverts back to minimized

I am expecting the Vyzor app to be in fullscreen mode. That is the only feature I was interested in and why I bought the license.

 - OS: Windows 10 v1909
 - Vysor Pro v2.3.0

 - Device: FireTV
 - OS: FireOS 5.2.7.3

**Comment by koush** [comment]
Hey, this should be fixed in the upcoming version. You can try the beta at https://app.vysor.io

**Comment by Heretushi** [comment]
I'm not the original poster, but I can confirm the fullscreen functionality does work for me in Vysor 3.0.44 native downloaded app.
