### ISSUE TITLE
cancel new subscription due too many technical issues and not satisfied from the app

### ISSUE THREAD

**Issue by Bagogo2** [koush/vysor.io#465]
Hello,
I've made a comment already but there wan't a clear response to my comment but only to others.
I would like to cancel my very new subscription and get my money back.
I've wanted to support this great idea and that's why I bought a yearly subscription but it looks like it's just an idea and actually the app has a lot of bugs.
1) Even when I followed your instructions for how to fix the issue of not having audio from my phone to vysor, first it didn't work and second the all idea for me to get this app is that I don't need to use internet but for your instruction I need wifi connection.
2) Another thing is that I'm getting many times the black screen from the mirroring and the troubleshooting that you have suggested isn't working and regardless of that it doesn't make sense to always restart everything, can't it just be fixed once and for all instead of us dealing with the problem every time?  
3) The mirror quality is pretty low even when I've changed it in the settings to the highest quality and it was promised to us that if we buy the subscription then we will get the best quality of mirroring.
4) In one of your comments you suggested to enter app.vysor.io and again it needs internet but still it didn't even worked for me.
I have followed everything that you instructed but still many bugs and not satisfied from the app at all.
5) It is not possible to mirror chrome incognito window.
Hope you can understand my position too.
You may contact me privately for my personal details in order to cancel the subscription if it is not possible to fix all of this because I really intended to support you back. 
Thank you

**Comment by koush** [comment]
1/2. Please check the new natives apps. 
https://github.com/koush/vysor.io/releases/tag/v3.0.33
4. app.vysor.io is an offline web app. it continues working without internet.
5. Correct, it's an Android feature to prevent screen capture of private information. Screenshots won't work either.
