### ISSUE TITLE
Error Connecting to Android device

### ISSUE THREAD

**Issue by Kresuu** [koush/vysor.io#466]
Trying to connect my phone, it says "Error Connecting to Android Device. SecurityError: Access Denied"

**Comment by djly** [comment]
I was having the same message, I was able to get past it by trying a two things.

1. I turned off "verify apps over usb" (recommended).
2. I installed specific adb usb drivers for my device.

I'm not sure what did it, because i did them both before reattempting.

**Comment by koush** [comment]
@Kresuu You're using app.vysor.io? Please try this:

https://askubuntu.com/a/954053

**Comment by koush** [comment]
@djly I've noticed this "verify apps" issue before as well. I've not gotten a consistent repro. But usually a dialog pops up asking to verify the app install.

**Comment by djly** [comment]
@koush Prior to turning it off, i was not even prompted on the device for the approval of the usb connection.

**Comment by koush** [comment]
@djly I've seen that before as well. Usually that's resolved by simply unplugging/replugging. There could also just be a bug in Android where these modals aren't popping up when they should.

**Comment by Alaingent** [comment]
Dear, please i m a new Pro Vysor User french, and i can use Vysor easily in desktop version on my windows pc, but, i want to use it in Chrome and unfortunately it doesn't fonction and i have the same issue "access denied" !!!! even turning off adv verification, and plug and re plug in my phone several times. So please how can  i use it ???

**Comment by Kresuu** [comment]
I am using windows 10

**Comment by Alaingent** [comment]
please i haven't yet any answer to my issue, on windows 10 chrome app Vysor, with my access to android denied. How could i resolve !!!? thank you

**Comment by koush** [comment]
native apps are released. This error occurs when adb.exe is running and app.vysor.io is unable to access the device. a better error message is now shown to detect this error and direct users to download the native app.

**Comment by Alaingent** [comment]
Sorry,  but i don't understand. If i have choice on your website Vysor, to connect (if i want because it is easier to scroll between several chrome pages with vysor, neither to go out of chrome in the native app) on Chrome, you have , please, to give me a solution in order i could.

thank you in advance.
