### ISSUE TITLE
Assistance with Audio Mirror.

### ISSUE THREAD

**Issue by jfranci84** [koush/vysor.io#468]
Good day everyone,

First off I am very satisfied with the quality of the recording, the mirroring is to my expectations. What I can't figure out is the Audio Mirroring. From what I understand is that it should capture the audio when for example I'm a playing a game and decided to record it. Because that's one of the reasons why I chose Vysor was because of this feature. I would mainly use it for games because for some reason when I try my native recorder it records my mic which I don't want.

Here's what's happening, whenever I select "Toggle Audio" it brings me to this screen:

![image](https://user-images.githubusercontent.com/64579859/80687005-34c5ee80-8afc-11ea-94f0-a1b07a9bbf17.png)

Now based on your instructions it should show "Vysor Audio Output" but it doesn't show anything. I am using an Oppo F9 - Android 9 and Vysor Pro Version 3.0.41. I was wondering if there's anything else that I need to do. 

Thank you so much,
Josh

**Comment by koush** [comment]
Do you have Google Home installed? If not, can you install it and see if more devices show up in this list?

**Comment by jfranci84** [comment]
> 
> 
> Do you have Google Home installed? If not, can you install it and see if more devices show up in this list?

Thank you for your fast response. I installed Google Home and logged in as it prompted me. Do I need to have chromecast to do this? etc. Because I installed it and I landed on this page

![image](https://user-images.githubusercontent.com/64579859/80691733-3c3cc600-8b03-11ea-9432-58e843000599.png)

Not really familiar with using Google Home honestly. Though I did try to do "Toggle Audio" again. and I'm still getting a blank page

![image](https://user-images.githubusercontent.com/64579859/80691855-655d5680-8b03-11ea-8515-ccc7b2431e7e.png)

Also if there are some steps that I need to do if it is not much hassle can you possibly tell it by step or link me to some instructions as I am not that literate when it comes to these things sorry.

Thanks,
Josh

**Comment by koush** [comment]
1. Click the headsphones in the dropdown menu.
2. The list of available audio output devices should pop up
3. Click Vysor Audio output (this option will be available for a minute after clicking step 1)

**Comment by jfranci84** [comment]
Tried it just now and the Vysor Audio Output still isn't showing

![image](https://user-images.githubusercontent.com/64579859/80692521-46ab8f80-8b04-11ea-99da-fa74f8237077.png)

**Comment by koush** [comment]
Hey, just noticed you are in airplane mode in your screenshot. Can you turn that off and check again?

Audio mirroring works by emulating a chromecast device on wifi. Maybe that's why it's not showing up.
Do you have any actual chromecast devices to verify those show up?

Vysor on Android 10 will use the native android audio mirroring capabilities instead of the chromecast method.

**Comment by jfranci84** [comment]
Hi there sorry for the late reply. I turned off Airplane Mode and it still isn't showing up.

![image](https://user-images.githubusercontent.com/64579859/80942527-9a292080-8e17-11ea-9b7a-38cf453f6afd.png)

Also I don't have any actual chromecast device to test.

For the Android 10 not really sure when we'll get the update cause currently my phone has Android 9.

**Comment by koush** [comment]
See here: https://github.com/koush/vysor.io/issues/582

Use the Android 10 audio checkbox available in 3.0.97.
