### ISSUE TITLE
Can't record a video with latest Vysor

### ISSUE THREAD

**Issue by rickg-hcl** [koush/vysor.io#469]
**Describe the bug**
I attempt to start a recording, and the video icon turns red and spins, but no recording is mad.

**To Reproduce**
1. attach a device and view with vysor
2. Click the record a video icon
3. it does't start recording.

**Expected behavior**

**Screenshots**
https://gist.github.com/VysorLogs/e9546a294c3ec3f1c3fafc3ef37cdd6a

![image](https://user-images.githubusercontent.com/34261549/80716510-b9e1e100-8ac5-11ea-9159-81a2b9d8fa1e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Vysor Version [e.g. 2.2.2]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link:

**Vysor Bug Report**
To retrieve a bug report, in the desktop application, click the bug report button to generate the report. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Thanks for the report, will fix this shortly.

**Comment by koush** [comment]
This actually seems like you got into a weird bad state after first install. Can you ensure the macbook has internet access, click reload vysor, allow it to update (it will likely prompt you within a few seconds), and then try again?

**Comment by koush** [comment]
I was able to reproduce this by disabling internet access immediately after downloading the dmg, but before opening the app. App gets into a bad state. It can be resolved by just restarting it.
Have added a notice to detect this and notify the user.
