### ISSUE TITLE
context_->is_null(): High Sierra

### ISSUE THREAD

**Issue by SimoneLeoni1987** [koush/vysor.io#470]
I have this issue with the standalone app on my macbook (late 2011).

I've seen the developer closing all the other similar issues without any advice.
If he's closing even this one, I'm going to cancel my pro subscription.

Thanks

**Comment by koush** [comment]
Use the new webassembly decoder. You will need to download the prerelease version of vysor

**Comment by koush** [comment]
Here's the current prerelease. https://github.com/koush/vysor.io/releases/tag/v3.0.43

**Comment by SimoneLeoni1987** [comment]
Thanks for the quick reply!

How am I supposed to use that? Could you explain please?

**Comment by koush** [comment]
Inside settings > Image quality In the vysor window.
