### ISSUE TITLE
PWA fails Chrome Webstore license retrieval

### ISSUE THREAD

**Issue by jerwarren** [koush/vysor.io#471]
On desktop version, license is retrieved, but the PWA fails Chrome Webstore license retrieval with a CORS error.

GET request to 'https://billing.clockworkmod.com/api/v1/purchase/[gmail-address]' returns appropriate CORS headers, but on POST it does not.

Additionally it appears that no matter what Google account I'm logged into it sends over "koushd@gmail.com" when clicking the 'retrieve license' button.

**To Reproduce**
1. Log in to the Vysor PWA with an account subscribing to Pro via Chrome Webstore.
2. Click on 'retrieve license'
3. See error in inspector

**Expected behavior**
License for the Google account I'm logged into is received.

**PWA**
- Version: 3.0.41
- Browser: Microsoft Edge & Chrome

**Comment by koush** [comment]
There’s a separate button for retrieving chrome store licenses. Did you try that one?

**Comment by koush** [comment]
The email is the chrome store merchant account, it is correct. Nothing wrong there.

**Comment by jerwarren** [comment]
The text in the 'retrieve license' modal indicates that it is doing the chrome webstore flow, so I guess the only issue is it probably shouldn't do that.  It didn't occur to me that the Chrome Webstore button would do anything different than what the 'retrieve license' flow said it was doing.

**Comment by koush** [comment]
Yep, will fix.

**Comment by koush** [comment]
Fixed in 3.0.0.46
