### ISSUE TITLE
Vysor 3.0.44 won't login to retrieve pro license

### ISSUE THREAD

**Issue by cbriseno** [koush/vysor.io#472]
Today I received the 3.0.44 update, but it seems that Vysor versions 3.x.x are not able to retrieve my pro license, it opens the browser (I tried with Safari and Chrome) and generates a Google authentication code but nothing happens when I paste the code into Vysor's window and I hit log in, I had to returned to version 2.3.1 because of this issue.

**Comment by koush** [comment]
Use the issue template.
