### ISSUE TITLE
Lifetime Pass

### ISSUE THREAD

**Issue by happygoing63** [koush/vysor.io#474]
I purchased Vysor Lifetime Pass in Dec 2018, when I turn on my computer today (5/1/2020) a new version (3.0.51) of Vysor popped up.  I kept asking me to login using my Google account.  My Lifetime Pass is under my HotMail account.  When do I need to do to get this resolved?

Thanks!
John

**Comment by koush** [comment]
Vysor has never supported hotmail accounts. You are using that account to log in with google. Check your receipt.
