### ISSUE TITLE
Vysor 3.0.44 SecurityError

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#475]
**Describe the bug**
Trying to "VIEW" a phone correctly recognized by Vysor does not work. The "device" window returns a SecurityError message.

**To Reproduce**
1. Setup everything as usual (USB debbuging included)
2. Vysor detects the phone correctly.
3. Click on 'VIEW'

**Expected behavior**
Vysor should not return an error message and work.

**Screenshots**
https://imgur.com/gallery/r0MRBrf

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (no Admin rights)
 - Vysor Version : 3.0.44

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link: on demand.

**Vysor Bug Report**
On demand.

**Android Logcat**
Not familiar enough to do it again. Would need instructions.

**Additional context**
Vysor 2.3.0 does work.
Sometimes, 3.0.44 will work, but I did not find a reliable way for it to work. It really is hit or miss.

**Comment by Heretushi** [comment]
I think I might have an idea of what is causing the problem.
It works now and what I did to make it work is killing all ADB.exe process on my computer.
Seems like if ADB.EXE (from Vysor 2.3.0) is still in execution, the WebADB version used by 3.0.44 cannot work correctly.
If you can repro and confirm Koush, I will close this issue.

**Comment by koush** [comment]
Whoops that webadb status is a bug. It always says that regardless what is used.

When you say 3.0.44 cannot work, you mean the native desktop download , correct?

**Comment by Heretushi** [comment]
Yes, I did use the functionality to download the app in its own window.

**Comment by koush** [comment]
Is it reliable after killing all adb processes?

**Comment by Heretushi** [comment]
I can't get Vysor to work reliably. I'm investigating the error. 

It seems to be related to the fact that I have TWO accounts set up on my Chrome browser (1 for work, 1 personal).

(A) When I open Chrome using my WORK account, browse to "chrome://apps/" then start Vysor, it  behaves normally. It works.

However, when I use the shortcut I have on my desktop (chrome_proxy "C:\Program Files (x86)\Google\Chrome\Application"), it does not work.

(B) I discovered using the desktop shortcut opens a Chrome instance logged with my PERSONAL account.

Using (A) method makes it work again. So the error message seems to be linked to profile management in Chrome AND is unrelated to the ADB.EXE process.

But there's something fishy going on when I do get the error. It looks like the "non-working personal account" Vysor is opening a adb.exe process when I shut down all the Windows. I do have to kill it manually after having the error and before opening Vysor the correct way. Otherwise, it won't detect correctly OR will display the SecurityError message.

**Comment by koush** [comment]
Sorry, I see, this is the browser aka PWA version. And correct, adb.exe will not work side by side with the browser version. Typically there's an error that tells you to download the native app. But it's not being shown in this case. This is a bug.
I can't fix this fully (there are some workarounds), but I will fix up the error reporting.

I still recommend the actual native app over the pwa, specifically for this reason: the usb contention can't be fixed.

I'd also make sure all old Vysor Chrome apps are removed from all profiles.

I tested this by upgrading from the windows executable, and everything continued working fine.

2.x Native App -> 3.x Native App Works
2.x Native App -> 3.x PWA requires adb.exe kill (and make sure the native app is not running on other user accounts, or it will simply start up again).

**Comment by koush** [comment]
https://vysor.io/ contains the new native apps.

**Comment by Heretushi** [comment]
Oh, ok, so I understood I was using the "native app" while I was not ?

You are saying : "I still recommend the actual native app over the pwa, specifically for this reason: the usb contention can't be fixed."

To use the latest Vysor version, I would go to https://app.vysor.io/#/. Then, Chrome would prompt me to install and I selected yes. Is this not the native app ?

**Comment by koush** [comment]
> To use the latest Vysor version, I would go to https://app.vysor.io/#/. Then, Chrome would prompt me to install and I selected yes. Is this not the native app ?

It actually is not. That's a progressive web app, which supports installation on any platform, including ChromeOS.
I see where the confusion is now. I'll need to document that better.

**Comment by Heretushi** [comment]
:)

Sadly, I won't be able to use the native apps it seems. Looks my the work anti-virus is not happy with the executable and I don't have admin right.

> Scan type: Auto-Protect Scan
> Event: Risque de sécurité détecté.
> Security risk detected: WS.Reputation.1
> File: c:\Users\<user>\downloads\vysor-win-3.0.44.exe
> Location: Quarantaine

**Comment by Heretushi** [comment]
Since you cannot and will not fix the problem, I will close this issue.

Thanks for taking the time to investigate. :)

**Comment by koush** [comment]
I added a better error message to install the native app. I'm also going to rerelease the universal adb driver to fix the outdated adb binaries.
