### ISSUE TITLE
Vysor Disconnects From Phone When Phone Screen Is Turned Off

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#476]
**Describe the bug**
When I use the power button on my phone to turn off the screen, or use the triple-dot menu to access the, "Screen On/Off" option, when I go to turn my phone screen back on by selecting the Vysor app's mirroring window on my desktop Vysor displays a Mirroring Disconnected error and has to reconnect. 

When it does reconnect the error is thrown a second time, the phone is disconnected again, and the reconnection process has to run a second time before the connection is finally established permanently. And it is only for as long as I don't turn my phone screen off again when I am done.

**To Reproduce**
1. Turn phone screen off via power button on device, or, "Screen On/Off" option in the triple-dot menu of the Vysor Mirror window. Vysor App's window goes black, phone screen is fully off.
2. Click on the Vysor window to bring back up the display
3. Vysor window will show phone's lockscreen for a brief time, less than a second or so.
4. Mirroring Error will pop up in display, phone will be disconnected from OS, lose access to storage via File Explorer, the whole shebang.
5. Phone will be recognized by OS again, Vysor begins to automatically connect to recognized device given my Vysor setting, "When an Andround Device is Connected:" being set to, "Connect Automatically"
6. Steps 3-5 will repeat themselves

Phone's connection to Vysor will remain stable until I shut off the display. At which point these steps repeat themselves from step 1.

**Expected behavior**
When waking my phone display up by clicking on the Vysor Desktop app's mirroring window, I expect the connection to my device via Vysor to still be established and stable. I expect to be able to interact with my device via Vysor immediately and not wait for it to disconnect, reconnect, disconnect a second time, and reconnect a second time before I can interact with the device.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393)
 - Vysor Version: 3.0.51

**Android (please complete the following information):**
 - Device: Samsung Note 9
 - Model Number: SM-N960U
 - OS: Android 10, Samsung One UI 2.0, Android Security Patch Level April 1, 2020
 - Vysor Bug Report Link:

**Vysor Bug Report**
VysorLog Giuthub Dir: VysorLogs/4c00ad6f-ae0b-4a55-aa34-2122f527a627.txt

**Android Logcat**
Not familiar with this, but if you could explain what to do I'd be more than happy to pull whatever information this provides.

**Comment by koush** [comment]
I need the bug report link. You pasted some window text.

**Comment by koush** [comment]
Also, you can use the F1 keyboard button to toggle the screen. Let me know if that causes the session to disconnect.

Was this happening in 2.x versions?

**Comment by CCattano** [comment]
> I need the bug report link. You pasted some window text.

Ah apologies, I figured pasting the file name as it existed in the VysorLogs github repo here

![image](https://user-images.githubusercontent.com/47487276/80833466-3226d000-8bb4-11ea-85c1-9d21c41f6194.png)

would make it identifiable so I didn't have to provide a direct link to the report with my email in it for anyone to open.

Here is the direct URL

https://gist.github.com/VysorLogs/1ad758261f45176d497a84638d2c8246

**Comment by koush** [comment]
This might be a longshot, but can you try restarting your computer? Or alternatively, kill all adb.exe processes that are running, then launch Vysor.

**Comment by CCattano** [comment]
I killed adb.exe and vysor from task manager and brought everything back up and I'm not experiencing the defect behaviour anymore. Seems like it's fine now.

Any insights into why that worked? Something to do with adb.exe running for v2.X and still running when Vysor updated and relaunched itself as 3.X after the update finished?

**Comment by koush** [comment]
Yeah there might be some strange contention happening here. Do you have another Vysor running on another user account? I'd make sure the Chrome apps are uninstalled as well.

**Comment by koush** [comment]
Did you install the universal adb drivers at some point?

**Comment by CCattano** [comment]
> Do you have another Vysor running on another user account? I'd make sure the Chrome apps are uninstalled as well.

I don't believe I had any additional instances of Vysor running in any way on my machine at the time. I don't have the browser extension installed since downloading the desktop app a year or two back.

> Did you install the universal adb drivers at some point?

I installed the adb drivers a long time ago, at least over a year ago when I first put the desktop app on the machine this was happening on.

Since this isn't happening anymore after shutting down adb.exe and vysor from task manager, and relaunching vysor should I close this issue?

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/481
