### ISSUE TITLE
Vysor 3.0.44 - AbortError

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#477]
**Describe the bug**
When using Vysor 3.0.44 (PWA in Chrome), when Vysor is left idle for a couple minutes (I have not timed it yet), upon return the "AbortError" is shown. Clicking "Retry" will reconnect Vysor and resume functionnality.

**To Reproduce**
1. Connect Vysor as usual.
2. Leave Vysor idle for a couple minutes.
3. See error

**Expected behavior**
Vysor 2.3.0 (native app) handles this situation by blanking the screen totally and staying connected. 

**Screenshots**
http://imgur.com/gallery/r3a1JTN

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version : 3.0.44 PWA

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link: on demand.

**Vysor Bug Report**
On demand.

**Android Logcat**
Provide instructions if necessary.

**Additional context**
None.

**Comment by Heretushi** [comment]
UPDATED original post to mention I use the PWA in Chrome. I was mistaken previously. :)

**Comment by koush** [comment]
Thanks. I believe this is a Chrome bug or power management bug. Something is letting the tab die and kill the usb connection.

**Comment by Heretushi** [comment]
I sadly can't since it's automatically quarantined by my work anti-virus program and I don't have the admin rights on the machine. :'(

**Comment by koush** [comment]
I see, but at some point you were able to grab the older native Vysor app? How did that escape the quarantine?

**Comment by Heretushi** [comment]
Whelp, since it's a corporate AV, the policy gets updated regularly. Maybe when I was using 2.3.0 the files were not considered a nuisance and that changed and it now is ?

It does list the file as a "WS.Reputation.1" risk.

**Comment by Heretushi** [comment]
Ah! It seems that the file is not old enough to be deemed reputable. It lists that a growing number of user deem this file as "_reliable_" (_fiable_ in french means it's not bad). So maybe in a  couple of days I will be able to use it. Symantec has discovered it 2 days ago so maybe it will change in the near future.

**Comment by Heretushi** [comment]
Once I can install the program, I will probably be able to use the "in-app" auto-updates.

**Comment by Heretushi** [comment]
I tried downloading an "older" release, the 3.0.27 and I have the same issue. I'll continue to use the PWA for now and retry in a couple of days.

**Comment by Heretushi** [comment]
PLOT TWIST!
This morning, I can install the app. My corporate antivirus suddenly decided to ask me wether I wanted to install or block the app. I chose to install. ;)
However, I am unable to log in using the traditional method. :|

**Comment by Heretushi** [comment]
In the main Vysor windows (3.0.44, I can't force it to update to the latest version), I click on login, the proper Google window open up, I log, I get the auth key, I copy the key, I return to the Vysor window, input the key, click on "LOGIN" in the small window, nothing happens. :|

**Comment by Heretushi** [comment]
This issue is related to Chrome power management on PWA clients. I will close this issue and open a new one for the login issue.
