### ISSUE TITLE
Network Error displayed when I try to connect an android device

### ISSUE THREAD

**Issue by vbongarala** [koush/vysor.io#478]
Hello,

I am getting a Network Error displayed when I try to connect my android device.
I have checked with a couple of android devices and everything has the same issue.
The issue started when the vysor on my desktop was auto upgraded to the 3.0.44 today.

OS: Windows 10
Vysor version: 3.0.44
Devices tried: Samsung S10E

![image](https://user-images.githubusercontent.com/10375589/80832110-0d355b80-8bba-11ea-802a-011fcb07a828.png)

Please do let me know if you need any other details.

Thank you in advance.

**Comment by vbongarala** [comment]
When I disable usb debugging, enable it and try again, I am getting the below error:

![image](https://user-images.githubusercontent.com/10375589/80832284-5ab1c880-8bba-11ea-866b-fe912766f13e.png)

**Comment by koush** [comment]
Can you try killing all running adb processes? Seems you might be on an older adb.exe. It will be in your task manager.

**Comment by koush** [comment]
Fixed in 3.0.52. Please test.

**Comment by koush** [comment]
Fixed in 3.0.52. Please test.

**Comment by vbongarala** [comment]
Thank you very much for your prompt reply.

**Comment by AlaaZarifa** [comment]
@koush I'm having this issue and I can't find v3.0.52 on the releases page. How can I download it?
