### ISSUE TITLE
Wifi option not working anymore, settings section disappeared (and hideous colours introduced) with new version

### ISSUE THREAD

**Issue by jacklammerts** [koush/vysor.io#479]
Hello,

Just received the new update, and I can't say it's an improvement so far. 

The biggest problems are:

- With the old app I could get Vyzor working over WiFi. with the new version it just doesn't seem to find my device anymore. The only way I can get it to work is if I connect my device with an USB cable directly. Tried everything I can think of (and what was descibed on your help pages). This really sucks!
- The settings seem to have gone completely. With the old app we had the possibility to easily hide the navigation bar. Now the settings page is completely gone, and I have to edit the JSON file in the customization page by hand
- The new colour scheme is hideous. I mean, bright purple? Got a headache just looking at it for all the time it took to find the appropriate settings in the JSON file.

Is there a way to safely revert back to the old version?

Kind regards, Jack

**Comment by koush** [comment]
The settings is in the 3 dots menu. The colors can also be customized. I might change the colors to different defaults.
Old release is here, but it will constantly try to update itself. Just keep the exe and don't restart Vysor.

https://github.com/koush/vysor.io/releases/tag/2.2.2

**Comment by jacklammerts** [comment]
Hi, thank you for your very prompt reply. As for the settings, unfortunately I don't have a 3 dot menu anywhere in the app:

![image](https://user-images.githubusercontent.com/64660737/80836478-1ee82480-8bf5-11ea-8e36-d09361f976d0.png)

Any thoughts about the broken Wifi functionality?

Added a bugreport
[61c2843dc7e43c467a7088ec92e12e2c-a4e79932845c30050bded644492d4f17bdb3a7ea.zip](https://github.com/koush/vysor.io/files/4566061/61c2843dc7e43c467a7088ec92e12e2c-a4e79932845c30050bded644492d4f17bdb3a7ea.zip)

**Comment by jacklammerts** [comment]
For some extra information, I just installed the old version, and everything is fine once more. Most importantly, the WiFi functionality is up and running again!

Is there anyway I can prevent the app from auto updating?

**Comment by koush** [comment]
Clcik View. Then the 3 dots.
![Pixel_4](https://user-images.githubusercontent.com/73924/80838606-4962bf00-8bae-11ea-86d6-0bafa262e555.png)

I also changed the default colors. Reload to get the new version.

**Comment by jacklammerts** [comment]
Once again, thank you very much for the prompt reply. Just started the app again, it uipdated, and all seems to be working again. Just a small tip, removing the Wireless mode from the Windows app, and only showing it after choosing View is not very helpful if nothing happens after you click View. In the old app the option was available in the Windows app. After updating the app the settings and Wireless mode button from the Windows app were gone, and the View button did absolutely nothing. So I never had no possibility to re-choose the Wireless mode. Besides that (but you couldn't know that), I use Displayfusion on my PC, which has an option to include an extra option in the title bar to move the active window to an other monitor, so my title bar looked like this:

![image](https://user-images.githubusercontent.com/64660737/80839591-d7b16200-8bfb-11ea-95df-3ec13facdc7c.png)

where that button is completely covering the 3 dot menu indicator. So perhapfs having a settings button in the main Windows app would still be a good idea.

Thank you for the very quick responses  and fixes though! Keep up the gooed work!

**Comment by koush** [comment]
What do you mean the View button did nothing?

**Comment by koush** [comment]
It sounds like the View button was nonfunctional. How did you end up opening the window?

**Comment by jacklammerts** [comment]
I think it was a combination of the View button not opening the windows showing the phone screen, the 3 dot menu being covered by an option from another app, and the fact that the option was missing from the main Windows app since trhe update. I just noticed the location of the 3 dot menu after your screen shot, and could use the View button because I had connected my phone by USB cable at the at moment.
