### ISSUE TITLE
Chrome 45.0.2454.85 webgl not working so vysor is distorted.

### ISSUE THREAD

**Issue by kizer8** [koush/vysor.io#48]
Just starting today, I think my chrome either updated to 45.0.2454.85 OR maybe the  vysory update to 1.0.5.4 today, but vysor is distorted. This worked fine the last week or so with webgl enabled in chrome.  I don't understand why gpu is enabled, but not really.  Screenshots below.

![distorted](https://cloud.githubusercontent.com/assets/5338575/9685667/52741744-52e5-11e5-89d2-1c12a41ef7f5.jpg)
![gpu](https://cloud.githubusercontent.com/assets/5338575/9685668/5277e748-52e5-11e5-9b33-2667cc9c051b.jpg)
![webgl](https://cloud.githubusercontent.com/assets/5338575/9685669/52781880-52e5-11e5-8192-5ba50ed6e4bb.jpg)
![about](https://cloud.githubusercontent.com/assets/5338575/9685688/713a411c-52e5-11e5-8085-c4b2d7986c33.jpg)

**Comment by kizer8** [comment]
Any way to fix?

**Comment by koush** [comment]
check issue #3

**Comment by koush** [comment]
may be a chrome 45 issue though
