### ISSUE TITLE
Pro License quit working, No wifi, - ugly colors - Very Bad Timing

### ISSUE THREAD

**Issue by PopsDad** [koush/vysor.io#480]
Rebooted machine and vysor quit working properly now.  Fifi menu gone, apparently not pro version any more. I have three pro versions using same google userid. Is that handled properly? 
Lost much time, tracking down problem thinking it was on our end.

**Comment by PopsDad** [comment]
*Fifi should be WiFi.

**Comment by PopsDad** [comment]
Here is image - It shows Pro at bottom but WiFi menu not available.
![vysor-desktop](https://user-images.githubusercontent.com/30957599/80836725-5d64eb80-8bc3-11ea-8f33-c75e1480456b.PNG)

**Comment by koush** [comment]
View the device, then click the wifi button in the 3 dots menu. It's there.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/479

**Comment by PopsDad** [comment]
Thanks for describing that the WiFi functionality moved from the Windows Desktop app to the 3-dot menu on the Device App. Now I understand.
Also, thanks for updating back to blue color - much better.
Great App, we evaluated several and yours is tops.
Thanks again
