### ISSUE TITLE
Bottom Half of Notification Is Layered Behind Available Devices List Item

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#482]
**Describe the bug**
Toast notification related to Vysor client being updated is layered behind Available devices list. When trying to click on, "Reload later" in notification, available device from list is selected and opened instead.

**To Reproduce**
1. Open Vysor Dashboard
2. Make sure connected device is visible to Vysor 
3. Receive toast notification indicating Vysor has been updated
4. Try clicking, "Reload Later"
5. The device in the Available Device list is selected instead.
6. The toast notification remains open. Only way to close is to select Reload Now since Reload Later cannot be clicked on.

**Expected behavior**
Expected to select the, "Reload Later" option presented in the toast notification, and after clicking the notification would close.

**Screenshots**
![image](https://user-images.githubusercontent.com/47487276/80840769-a0bf5a00-8bc3-11ea-9c7f-bb3366469cb5.png)

Notice how hovering over the, "Reload Later" option causes my device in the Available Devices list to become highlighted. Idk much about native OS app development, but I'd call it a z-index value issue if it was happening in a web app, Idk if that's helpful or not though, lol.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393)
 - Vysor Version: 3.0.52

**Android (please complete the following information):**
 - Device: Samsung Note 9
 - Model Number: SM-N960U
 - OS: Android 10, Samsung One UI 2.0, Android Security Patch Level April 1, 2020
 - Vysor Bug Report Link:

**Vysor Bug Report**
https://gist.github.com/VysorLogs/cb209d516128e3eeb3f4db13555d82cb

**Android Logcat**
Not familiar with this, but if you could explain what to do I'd be more than happy to pull whatever information this provides.

**Comment by koush** [comment]
Oof yeah I just noticed this too. Will fix.

**Comment by koush** [comment]
Incidentally, it is a web app and likely a z-index issue.

**Comment by CCattano** [comment]
Oh gotcha. I totally forgot there's stuff out there like ReactNative and NativeScript, lol. Thanks for the help today btw. Love the app and the new update is sleek af.

**Comment by koush** [comment]
fixed in 3.0.56.
