### ISSUE TITLE
v3.0.54 Copy Paste Bug

### ISSUE THREAD

**Issue by kazhuyo** [koush/vysor.io#483]
After update to 3.0.54, Copy Paste don't work anymore, trying copy paste from computer to vysor nothing happened, using international keyboard checked seems not work anymore.

**Comment by koush** [comment]
Got this report on twitter. Will fix shortly!

**Comment by kazhuyo** [comment]
thank you, will wait for the fix...

**Comment by koush** [comment]
international keyboard should still work.

**Comment by kazhuyo** [comment]
sorry I mean, using International Keyboard for copy paste don't work too, but yes, the international keyboard still working.

**Comment by koush** [comment]
fixed in 3.0.56. hit reload.

**Comment by clubtech** [comment]
Seems like it is not working with connecting to a pixel 4 but not when connecting to a Samsung Galaxy S20. With the Samsung copy / paste of text does nothing while the same text copies over to the Pixel without issues.
International keyboard works fine on both.
