### ISSUE TITLE
Completely broken after Zoom out with Cmd -

### ISSUE THREAD

**Issue by ConorGarry** [koush/vysor.io#485]
**Describe the bug**
I just updated to 3.0.57.
I noticed new UI, blue top and bottom so thought I could zoom out with `Cmd -`
Vysor UI started to break in both device window and Vysor control panel (see attached image).
I tried to get it back by pressing `Cmd +` but it does nothing so now I'm stuck with a tiny UI and a zoomed *in* device that just flickers non-stop. 
Seems to have broken everything.

**To Reproduce**
1. Update  to 3.0.57
2. View device in Vysor.
3. Device window , press `Cmd -`, device stays same, UI start to shrink (and break).
4. View Vysor main window - also zoomed out small font, cannot zoom back in.
5. Close and restart vysor - observe panel still zoomed out.
6. View device - observer it's zoomed in and erratically flashes on and off. (attached gif).

Edit: I have tried bother `Reload Vysor` and `Reset Vysor` but neither resolve it.

**Expected behavior**
`Cmd +` should do opposite of `Cmd -` for zoom/scaling UI.
I can view my device window as before.

**Screenshots**
![Screenshot 2020-05-02 at 07 23 26](https://user-images.githubusercontent.com/6222596/80857002-9befba00-8c46-11ea-8ef0-19390e4572c9.png)

![vysor_zoom](https://user-images.githubusercontent.com/6222596/80857080-2a643b80-8c47-11ea-9723-52c818e809cf.gif)

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.4]
 - Vysor Version [3.0.57]

**Android (please complete the following information):**
 - Device: [Pixel XL]
 - OS: [Android 10]
(I do not think this is device-specific).

**Comment by koush** [comment]
Yikes. I'll need to track down how to disable UI zooming and locking the zoom. I'd suggest deleting all Vysor related files until I can resolve this sometime tomorrow. I think its stored in Users\username\Library\Application Support\Vysor.

**Comment by koush** [comment]
I have a fix for this that will reset the zoom when the window is reopened. It won't preserve it so as not to get into a bad state.

**Comment by koush** [comment]
Actually can't seem to disable it altogether anyways.

**Comment by ConorGarry** [comment]
> Yikes. I'll need to track down how to disable UI zooming and locking the zoom. I'd suggest deleting all Vysor related files until I can resolve this sometime tomorrow. I think its stored in Users\username\Library\Application Support\Vysor.

Thank you! This has got it back to a usable state 👍
