### ISSUE TITLE
With Ubuntu 18.04.4 LTS I can not start vysor:

### ISSUE THREAD

**Issue by NickZt** [koush/vysor.io#486]
With Ubuntu 18.04.4 LTS I can not start vysor:
$ vysor
using chrome runtime 1.3.6
autoUpdater feed url https://vysornuts.clockworkmod.com/update/linux_x64/2.3.1
embedded /snap/vysor/x3/resources/app/unpacked-crx found
chrome runtime id lhaagglfcbekgaiedemenlgbkbhjepnk
chrome app id gidgenkbbabolejbgbpnhbimgjbffefm
chrome app directory /snap/vysor/x3/resources/app/unpacked-crx
/snap/vysor/x3/resources/app/unpacked-crx/native/linux/audio_playback.so not found.
/snap/vysor/x3/resources/app/platform-assets/linux/audio_playback.so not found.
PPAPI path /snap/vysor/x3/resources/app/unpacked-crx/native/linux/video_decode.so;application/x-ppapi-vysor
starting
registerprotocol
starting runtime
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false". It will change to be "true" in Electron 9. For more information please check electron/electron#18397
(electron) 'setName function' is deprecated and will be removed. Please use 'name property' instead.
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
killing all windows for shutdown
chromeRuntimeWindow shutdown
windows remaining [
BrowserWindow {
setBounds: [Function],
_events: [Object: null prototype] {
blur: [Function],
focus: [Function],
show: [Array],
hide: [Function: visibilityChanged],
minimize: [Function: visibilityChanged],
maximize: [Function: visibilityChanged],
restore: [Function: visibilityChanged],
close: [Array]
},
_eventsCount: 8,
devToolsWebContents: [Getter],
_maxListeners: 1000
}
]
window-all-closed

**Comment by koush** [comment]
duplicate.

**Comment by Doctoror** [comment]
Duplicate to what? Please attach a link to the original issue.

**Comment by koush** [comment]
I think this is an old issue anyways, the app was rewritten for linux.

**Comment by Doctoror** [comment]
I see now. I was trying this Chrome app from 2018, it was not flagged out of date.
https://aur.archlinux.org/packages/vysor-git
Gonna try new one. Thanks!
