### ISSUE TITLE
With Ubuntu 18.04.4 LTS with Chromium  can not start vysor in browser

### ISSUE THREAD

**Issue by NickZt** [koush/vysor.io#487]
With Ubuntu 18.04.4 LTS with Chromium  can not start vysor in browser

**Desktop **
Ubuntu 18.04.4 LTS
Chromium
Version 81.0.4044.129 (Official Build) snap (64-bit

After start vysor shows following window:  https://prnt.sc/s9lhbt

**Comment by koush** [comment]
generate a bug report and attach it.

**Comment by NickZt** [comment]
https://gist.github.com/4458fcda4e095347f1f8ce3f150510db

**Comment by koush** [comment]
You have an adb process running. Use the appimage download or kill the adb process.

**Comment by koush** [comment]
> Error: Vysor was unable to access the Android USB device. Vysor may be mirroring this Android in another tab, or the native ADB server is running on your desktop. Downloading the Vysor desktop application is recommended.

**Comment by koush** [comment]
That message was in the log, but for some reason was not shown in the actual error window. I'll track down why.

**Comment by koush** [comment]
I reproduced this and there's a few issues here. Running adb as root creates the ~/.adb directory in the home folder with root only permissions. This causes authentication/security failures. Furthermore the `sudo apt install adb` does not seem to always set up the plug dev rules propertly.

So recap:
 * chown ~/.adb to user
 * ensure plug dev rules are correct https://askubuntu.com/a/954053
