### ISSUE TITLE
Title bar buttons placement 

### ISSUE THREAD

**Issue by AlaaZarifa** [koush/vysor.io#489]
Phone: 
-
**Xiaomi Pocophone F1** 

Issues: 
-
- The buttons on the title bar are overlapping.
- I can't drag the window/phone when pressing on the phone name!? I had to press at the far left small space in order to drag the window around.
- When I disable the Title Bar, I couldn't find a way to show open the phone settings? maybe add a keyboard shortcut to open the setting panel.
- The quality buttons have no margins and overlapping with each other inside settings window. 

Screenshots: 
-

![image](https://user-images.githubusercontent.com/18426012/80913252-f0c92880-8d4b-11ea-8f50-5958b4870d7e.png)

![image](https://user-images.githubusercontent.com/18426012/80913376-d0e63480-8d4c-11ea-8ffb-e6e7e214c08c.png)

**Comment by koush** [comment]
You using font scaling or something?

**Comment by koush** [comment]
I think i'll need to extend the title bar into a second row for smaller monitors.

**Comment by AlaaZarifa** [comment]
> You using font scaling or something?

I'm using the recommended scaling option, you're right though because when I set it to 100% they became in one line. 

 
![image](https://user-images.githubusercontent.com/18426012/80945849-7654e300-8df5-11ea-8787-2aad80528d26.png)

**Comment by nicomarmorini** [comment]
> I think i'll need to extend the title bar into a second row for smaller monitors.

In the meantime is it possibile to disable the autoupdate and keep using the old version?

**Comment by koush** [comment]
in your hosts file, black hole vysornuts.clockworkmod.com to disable auto updates.

**Comment by koush** [comment]
Fixed in the latest release. Please confirm.

**Comment by AlaaZarifa** [comment]
version 3.0.67 indeed fixed the buttons issues, but when I auto-updated to the newer versions, the issue returned back.

![image](https://user-images.githubusercontent.com/18426012/81269253-bb755100-9051-11ea-9343-3a9cc88083d3.png)

**Comment by AlaaZarifa** [comment]
I don't think you noticed the other small issues I mentioned above.

> - I can't drag the window/phone when pressing on the phone name!? I had to press at the far left small space in order to drag the window around.
> - When I disable the Title Bar, I couldn't find a way to show open the phone settings? maybe add a keyboard shortcut to open the setting panel.

**Comment by koush** [comment]
I'm not sure how i'm going to fix this since the name of hte phone is variable length. Maybe create a second row just for the icons.

You can edit the name and shorten it for now.

**Comment by koush** [comment]
![Pixel_4](https://user-images.githubusercontent.com/73924/81357805-7a992e80-9089-11ea-9803-241f928b95df.png)
reducing the spacing on the title bar.

the phone name opens the main vysor window. it's not draggable, or it wouldn't be clickable.

press F1 or refocus the window to show the title bar again. the title bar will show up for 5 seconds upon refocus. then you can get into settings.

**Comment by koush** [comment]
fixed in 3.0.74, please verify.
Button spacing is a lot closer together, and less padding for the title.

**Comment by AlaaZarifa** [comment]
Yes, so much better now.

Side note, in Windows10 it's **F2** that refocus the window, not F1. incase future potential windows users see the comments.
