### ISSUE TITLE
Vysor 3.0.44 is slow

### ISSUE THREAD

**Issue by DanteNguyen1008** [koush/vysor.io#490]
**Describe the bug**
I just upgraded to 3.0.44 this morning and it is super slow. 
- Slow in connecting to devices.
- Slow in transferring  actions from PC to devices.

**To Reproduce**
- Slow in connecting to devices.
1. Open vysor.
2. Click "View"
3. Super slow on connecting to the device

- Slow in transferring  actions from PC to devices.
1. With Vysor opened. 
2. Make any action on the Vysor app
3. The action get transfer super slowly.

**Expected behavior**
Suppose to be fast. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Vysor Version 3.0.44

**Android (please complete the following information):**
 - Device: Pixel 3, Pixel 4XL
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/a7cc99b4ae63d9dc3f015c5b905632ba

**Vysor Bug Report**
To retrieve a bug report, in the desktop application, click the bug report button to generate the report. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Are you running a custom ROM or anything like that? What is the decoder you are using in Vysor settings? I presume Native?

**Comment by DanteNguyen1008** [comment]
hm.. Seem like my ADB had forwarding enable or something. After resetting and clearing the forwarding then it started working fine again.

**Comment by koush** [comment]
Strange, thanks for following up.
