### ISSUE TITLE
Vysor 3.0.44 -- Can't Log In Vysor Pro

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#493]
**Describe the bug**
When trying to log into Vysor Pro using a Google authkey, the "LOGIN" button of the small windows where I paste the authkey does not work.

**To Reproduce**
1. In the main Vysor window, go to the "About" section and click on LOGIN (A).
2. A new browser Window open. Log into Google. Obtain authkey.
3. In the smaller "Google Sign-In" window, paste the authkey.
4. In the smaller "Google Sign-In" window, click LOGIN (B).
5. Nothing happens.

**Expected behavior**
The small "Google Sign-In" should disappear and I should be logged into Vysor Pro.

**Screenshots**
![Google-Sign-In](https://user-images.githubusercontent.com/46582434/81005696-5a186c80-8e1c-11ea-863b-2b7981bdbe9f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Vysor Version : 3.0.44

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link: On demand.

**Vysor Bug Report**
On demand.

**Android Logcat**
On demand. Would need instructions.

**Additional context**
On demand.

**Comment by koush** [comment]
Hey, sorry about this bug. I know that license issues can be the most frustrating. I'm not sure offhand what the problem is, because no error is shown (which in itself is a bug). I released 3.0.60 which will show any login errors and will allow me to diagnose this issue further. Thanks for the bug report.

**Comment by koush** [comment]
Just need to reload and should be prompted to upgrade.

**Comment by Heretushi** [comment]
I had a flash. Since I could NOT upgrade and could NOT login, whatever I was doing, I tried disconnecting my workplace VPN. To nobody's surprise, it worked. Vysor updated itself to the latest release and logged in without any issue.

I will try to logout, reconnect the VPN and try to log in to let you know if I see the error message and paste it here to help others who could be in the same situation.

**Comment by Heretushi** [comment]
So, with the VPN connected and the latest version of the native app (3.0.62), the behavior stays the same :

1. In the main Vysor window, go to the "About" section and click on LOGIN (A).
2. A new browser Window open. Log into Google. Obtain authkey.
3. In the smaller "Google Sign-In" window, paste the authkey.
4. In the smaller "Google Sign-In" window, click LOGIN (B).
5. Nothing happens.

HOWEVER, after about a minute of the little red window not being responsive, there's a new error message showing :

![image](https://user-images.githubusercontent.com/46582434/81094118-0f0c6100-8ed1-11ea-8dce-32cbdc2bb90b.png)

I don't know if this is what you expected Koush ?

**Comment by koush** [comment]
Yes, that's the error I was looking for. Thank you. Are you behind a firewall of any kind? If so, what software do you use?

**Comment by koush** [comment]
Ah just noticed your previous note that you are in fact behind a VPN. Does it work WITHOUT a VPN?

**Comment by Heretushi** [comment]
Confirmed. The VPN is the culprit. :)

So, I no longer have a bug to login and you confirmed the error message is what you expected. I'm closing this issue.

**Comment by koush** [comment]
Reopening to track this issue. This should work behind a VPN.

**Comment by koush** [comment]
Did the old version work behind a vpn?

**Comment by Heretushi** [comment]
Oh. Then yes, the old version did work behind the VPN.
But since it's a corporate VPN, rules can't be changed without my knowledge.
I could reinstall the old version to test this tomorrow.

**Comment by koush** [comment]
Ok, please try this prerelease. It might fix the issue.
https://github.com/koush/vysor.io/releases/tag/v3.0.67

**Comment by Heretushi** [comment]
Vysor was able to auto-update to 3.0.66, but installing the 3.0.67 prerelease was blocked by the corporate AV. Since I cannot use any other computer to log into the corporate VPN, it looks I will not be able to test newly released files. I can however use the auto-update feature to continue testing.

**Comment by Heretushi** [comment]
Using the 3.0.66 version, I was able to log in when connected to the VPN.
I noticed that the page displayed in Google were different. When it was not working, I had no "disclaimer" asking me if I trust Vysor with some infos. Now, I have to agree at every login attempt. Then, the page displaying the authkey is different, simpler. Anyway, it's working now EVEN when connected to the corporate VPN. :)

**Comment by Heretushi** [comment]
Koush, unless you have more needs related to this issue, I will not investigate further and you can close the issue. Thanks! :)

**Comment by koush** [comment]
@Heretushi shoot me a bug report of your current install. Just gonna check some version strings.

**Comment by Heretushi** [comment]
Vysor updated to 3.0.69 so I can't send a bug report of the 3.0.66 version.

Here is the content of the bug report, with infos redacted. :)

[first block.txt](https://github.com/koush/vysor.io/files/4588902/first.block.txt)
[second block.txt](https://github.com/koush/vysor.io/files/4588903/second.block.txt)
[third block.txt](https://github.com/koush/vysor.io/files/4588904/third.block.txt)

**Comment by svkPocket** [comment]
I still have the issue in version 3.1.4 even with or without the VPN

**Comment by B3nz01d** [comment]
I still have the issue in version 3.1.4 even with or without the VPN

**Comment by hk0i** [comment]
I get the same error, unable to log in. No VPN but my whole network is behind a local AdGuard-Home DNS, could be related? Thinking pi-hole users might have a similar issue...
