### ISSUE TITLE
Upload files to Android won't go away

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#494]
**Describe the bug**
When dragging a file over the Vysor window, an overlay displays "Upload files to Android". If I don't release my mouse over the Vysor window and not initiate/complete a file transfer, the overlay never disappear. Under the overlay, the phone remains responsive.

**To Reproduce**
1. Open Vysor as usual.
2. Select a file, drag it over Vysor.
3. Drag the file elsewhere as to not initiate a file transfer.
4. The overlay will remain there until the Vysor window is closed.

**Expected behavior**
When I stop hovering over the Vysor window, I expect the overlay to be removed.

**Screenshots**
![Vysor-upload-overlay](https://user-images.githubusercontent.com/46582434/81006479-9ef0d300-8e1d-11ea-9bab-79ac24f8c5c3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Vysor Version : 3.0.44

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Vysor Bug Report Link: On demand.

**Vysor Bug Report**
On demand.

**Android Logcat**
On demand.

**Additional context**
On demand.

**Comment by koush** [comment]
I've seen this too but have been unable to get a solid repro. Seems to happen when dragging something over it but not onto it.

**Comment by koush** [comment]
Oh, your repro steps work for me every time. Thanks! Will fix this ASAP.

**Comment by koush** [comment]
Fixed in 3.0.61.
