### ISSUE TITLE
Android Device Offline after update

### ISSUE THREAD

**Issue by PopsDad** [koush/vysor.io#497]
I have been using Pro version for a week or two.
Vysor was updated this morning.
I am unable to connect to device.  
Message: The Android is offline. This can be resolved by physically disconnecting and reconnecting to the device.
=====
I do that and there is no change.
I rebooted device - no change
I restarted the adb server - no change -
=====
I expect that after the update I should be able to connect to device and view.
I also rebooted Windows 10 computer - prior to the Vysor upgrade.
When I click on the 3 vertical dot on the device window I get: Wireless mode - Cannot read property 'adbsocketFactory" of undefined.

Vysor 3.0.62
Device: Moto g7
OS: Windows 10 Enterprise
https://gist.github.com/VysorLogs/0b40715e15234f9d992ee58487a3d792

Sir, I am working in a commercial environment where reliability is critical for us. I am in a bind now that I am unable to continue working.
 
Additionally I do not understand a few items - 
1. In the 3 dot menu it has the wireless option (which was moved from last week from the other Vysor screen), How do I know if I have wireless enabled or disabled? When I click I get the adbsocketfactory error described above.
2. After Vysor is updated what exactly is the procedure to get it working again?

![vysor-may-5-2020](https://user-images.githubusercontent.com/30957599/81062857-c343c280-8ea4-11ea-8377-50f40d00f194.PNG)

**Comment by PopsDad** [comment]
Ok, is working now - may have been a USB port or cable. (only issue was the port and cable was working before the version upgrade) - But we close for now.

**Comment by koush** [comment]
Thanks for following up.

**Comment by JosephReidNZ** [comment]
I've got the same problem when I try to connect via wireless mode. The problem has just shown up in the last few days.
