### ISSUE TITLE
Data sent to Facebook Ads platform

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#498]
**Describe the bug**
There is device and APK data being sent to Facebook's Ad platform, specifically sending APK information about Vysor to ``https://www.facebook.com/adnw_sync``. 

**To Reproduce**
1. Use a HTTP/S proxy sniffer and connect the Android device to it (not going to list directions for that here). If on Android N or later, you'll need to turn the client cert into a system cert. Also not going to explain that here.
2. Watch your logs as every 5 minutes, your phone pings Facebook's ad platform with your device / Vysor APK info.

**Expected behavior**
If you're using Facebook ads somewhere in the product, please make it clear that you are doing so. I've actually never used Vysor without a lifetime licence, so if you are indeed showing ads for free users, please disable it for lifetime user products. I don't recall seeing this in versions < 3.x

**Screenshots**
[Screenshot](https://imgur.com/ITIPbpC)

**Desktop:**
 - OS: macOS 10.15.4
 - Vysor 3.0.67

**Android:**
 - Device: Pixel 2 XL
 - OS: 8.1.x

**Comment by koush** [comment]
There are ads for free users, but not pro users. I am guessing Facebook is initializing and sending data regardless if ads are shown or not. I actually stopped using their ad platform altogether in mediation, but haven’t removed the sdk yet. Will do that.

**Comment by crouchingtiger** [comment]
I'm not surprised it's the SDK - I monitor Facebook's suites of applications to look for data / privacy breaches, this is just one of many. I assume this is the same SDK version / issue that caused [Zoom some privacy issues back in March.](https://blog.zoom.us/wordpress/2020/03/27/zoom-use-of-facebook-sdk-in-ios-client/)

**Comment by koush** [comment]
Facebook has been removed in latest apk released to store and app.

**Comment by crouchingtiger** [comment]
Can confirm, thanks for taking care of this.
