### ISSUE TITLE
Screenshot and Video do not work on MacOS

### ISSUE THREAD

**Issue by kfusco** [koush/vysor.io#499]
Attempting to take screenshot or record video from title bar does not work.

Invoke  VysorPro>
View Android device>
Select Screenshot or take video icon from Titlebar

**Expected behavior**
A screenshot or Video should be taken/recorded

Actual Behavior:
Icons are enabled (respond to tap) but nothing happens

 - OS: MacOS High Sierra 10.13.6
 - Vysor Version Pro 3.0.44

**Android (please complete the following information):**
 - Device: Zebra TC510K
 - OS: Android 7.1.2

 - Vysor Bug Report Link:
**Vysor Bug Report**
This fails to load
 'Bug Report Failed: Request Aborted'

**Comment by koush** [comment]
Update to the latest vysor. Released last night.

**Comment by kfusco** [comment]
Vysor pro 3.0.68 - both functions are working. Thanks.
