### ISSUE TITLE
Windows 10 - LG G3 - Phone not detected

### ISSUE THREAD

**Issue by klynxxx** [koush/vysor.io#5]
Tried both with Koush Universal ADB Drivers and the specific LG drivers that come with the device.
Checked that USB debugging is enabled.
Vysor (Beta) doesn't detect the phone. 

Please let me know if you need any additional info.

**Comment by reTARDIS** [comment]
Same issue here. Win10 LG G3 (D851). I'll try it on my Mac and report back.

**Comment by koush** [comment]
make sure adb is enabled and the phone is in ptp mode.

**Comment by koush** [comment]
new universal adb drivers available that work with windows 10.

using the oem drivers usually does the trick too.

https://www.youtube.com/watch?v=Ucs34BkfPB0

**Comment by glosada** [comment]
I'm having this same issue, but on windows 7.

Tried with the universal driver, lg driver, adb is on, and (was using MTP) just changed to PTP, but no luck, still not detecting my phone.

What do you suggest I should do?

Thanks

**Comment by glosada** [comment]
Don't worry, installed/reinstalled/uninstalled several drivers, until the (new) lg drivers fixed it... had to install them, then get the phone debugging off, change it to MTP, then the phone installed some new drivers and finally, back to debug, it works like charm.

**Comment by klynxxx** [comment]
Thanks @glosada. Solved it the same way. Downloaded the latest drivers from
LG for D855 and it's working now.

Regards
