### ISSUE TITLE
Custom ROMs using h264 high or main: black screen

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#50]
This results in a black screen.

The codec should be h264 baseline, but custom ROMs end up choosing something higher than what is supported. This results in an inability to decode the stream.

**Comment by ankushdas9** [comment]
Try fixing it :( Desperate to use it. I have older S duos and Galaxy S duos 2 running on 4.0 and 4.2 respectively. Will let you know what happens..  :-)

**Comment by thorpj** [comment]
@koush Would the people at CyanogenMod bother to help us?

**Comment by gaberad** [comment]
Not sure if you are still developing this, but as a work around, how about having an option where it grabs a screenshot every x milliseconds (configurable?) and displays the screenshot instead?

Similar to how adbcontrol works http://marian.schedenig.name/2014/07/03/remote-control-your-android-phone-through-adb/

**Comment by meshosk** [comment]
Any progress? Got Note 2 with CyanogenMod 11. Running rolling Debian 8, got black screen. Events from PC works, I can see them on device.

**Comment by arnaud-ramey** [comment]
Hello!
Phone: Samsung Galaxu SIII (GT-I9300) with a broken screen.
OS: CyanogenMod 11 (Android 4.4) with root access
I'm trying Vysor to get the screen output on the PC, as the phone screen is broken.

However, I'm having this black screen problem in Vysor.

- "screenrecord" generates an empty 6k file.

- $ screenshot /sdcard /test.png                                                                                                                           
error: could not read framebuffer

@koush pointed out it might be a H264 incompatibility between Vysor and CM
Any advance on that?
If you need, I can supply more bug report data.
Thanks for the hard work anyway :)

**Comment by meshosk** [comment]
Any progress?

**Comment by santiagovazquez** [comment]
Same issue here. Samsung Galaxy S4 GT-I9190, Android version 4.4.2, Chrome Version 51.0.2704.103, Vysor 1.1.2.9

**Comment by koush** [comment]
The entire rendering pipeline was changed in 1068 or so. This bug is no longer valid, and the black screen you are seeing is a different error (that has several posted solutions). Please go to the support link within the app.

**Comment by koush** [comment]
https://plus.google.com/110558071969009568835/posts/1uS4nfW7xhp
