### ISSUE TITLE
Crash when initializing MediaCodec

### ISSUE THREAD

**Issue by artyeffem** [koush/vysor.io#500]
**Describe the bug**
Connecting Vysor-3.0.67 to device usually results in "Mirroring Disconnected".

**To Reproduce**
1. Start Vysor AppImage on Ubuntu 16.04
2. Click "View" for remote device
3. Observed startup messages, then "Mirroring Disconnected" dialog

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Vysor Version 3.0.67

**Android (please complete the following information):**
 - Device: AiVision camera (KMC28)
 - OS: Android 8.1.0 (SDK 27)
 - Vysor Bug Report Link:

**Vysor Bug Report**
id 
email 
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.2.4","chrome":"80.0.3987.165"}
package.json 3.0.66
os linux
electron true
pwa false
screen 1056 1920 1080 1920
https://vysorelectron.clockworkmod.com/#/device/33163038588047
enterprise cached check failed Error: not cached
Connecting...
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in
device status device
Checking Vysor APK installation...
protocol version: vysor-io-73
Preparing Vysor on Android...
Starting Vysor on Android...
Waiting for Vysor on Android...
vysor daemon stdout:  Started
daemon password 160ed46e
Connecting to Vysor on Android...
vysor daemon stdout:  

connection established
device event {"type":"password"}
device event {"type":"displaySize","screenWidth":320,"screenHeight":480,"nav":false}
device event {"type":"encodeSize","encodeWidth":80,"encodeHeight":120}
connecting to video
id 
email 
Checking License...
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in
found plugin for application/x-ppapi-vysor
Waiting for Decoder...
NACL module initialized
decoder: software
Connecting to Vysor on Android...
vysor daemon stdout:  Killed 

**Android Logcat**
```
12-31 20:53:52.130  4807  4816 D HprofFactory: Create HprofDebugEx
12-31 20:53:52.130  4807  4816 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: AsyncServer
12-31 20:53:52.130  4807  4816 E AndroidRuntime: android.media.MediaCodec$CodecException: Error 0x80001001
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at android.media.MediaCodec.native_configure(Native Method)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at android.media.MediaCodec.configure(MediaCodec.java:1943)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at android.media.MediaCodec.configure(MediaCodec.java:1872)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.virtualdisplay.EncoderDevice.createDisplaySurface(EncoderDevice.java:79)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.virtualdisplay.EncoderDevice.registerVirtualDisplay(EncoderDevice.java:1)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.vysor.Main.writer(Main.java:12)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.vysor.Main$18.onAuthenticated(Main.java:4)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.vysor.Main$18$2.onStringAvailable(Main.java:4)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:6)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.Util.emitAllData(Util.java:2)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:12)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:26)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:28)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:1)
12-31 20:53:52.130  4807  4816 E AndroidRuntime: 	at com.koushikdutta.async.AsyncServer$8.run(AsyncServer.java:2)
12-31 20:53:52.134  4807  4816 I Process : Sending signal. PID: 4807 SIG: 9
```

**Additional context**
On one occassion, if I select the Video Resolution to "Original", I was able to complete initialization of screen.  This did not persist on next execution cycle, still trying to repeat it.

**Comment by koush** [comment]
This is very likely a firmware issue.

**Comment by koush** [comment]
you can try original quality as the setting for the decoder. but i'm not going to support random cameras. only google CTS compliant devices.

**Comment by artyeffem** [comment]
your 2.3.0 version works with this camera, so is it a backwards compatibility issue?  I would help troubleshoot, but having Vysor startup problems from local electron builds.
