### ISSUE TITLE
Automatic screen brightness mode forced to true

### ISSUE THREAD

**Issue by b4r3k** [koush/vysor.io#503]
**Describe the bug**
Using Vysor automatically enables automatic brightness mode

**To Reproduce**
1. Go to display settings (android)
2. Disable automatic brightness mode
3. Open Vysor
4. Click on "VIEW"

**Expected behavior**
Automatic brightness mode should remain unchanged

**Desktop (please complete the following information):**
 - OS: Windows 10 Family v1909
 - Vysor Version 3.0.73

**Android (please complete the following information):**
 - Device: OnePlus One
 - OS: CyanogenOS 13.1.2 (Android 6.0.1)
 - Vysor Bug Report Link: N/A

**Comment by koush** [comment]
I think I know what the problem is, thanks.

**Comment by koush** [comment]
tracking
https://github.com/koush/vysor.io/issues/510

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/510#issuecomment-629412304
