### ISSUE TITLE
Device window is at half brightness when HDR is enabled (Windows)

### ISSUE THREAD

**Issue by mathewng** [koush/vysor.io#504]
I am using Vysor Pro Version 3.0.73 and Windows 10 with GTX 1070 (no onboard graphics).

When HDR is enabled in Windows, the device window is at half brightness, it looks darker/dimmed.
When HDR is disabled, there is no issue.

This affects only the device window and not the main vysor window with the connect network device/share/view buttons.

<img width="1920" alt="screenshot" src="https://user-images.githubusercontent.com/15259279/81331601-6c243480-90d4-11ea-8534-cf393c49375d.png">

**Comment by koush** [comment]
related
https://github.com/electron/electron/issues/10732

**Comment by mathewng** [comment]
I'm not sure if it's related to the electron issue but it looks like the device window doesn't support HDR or 10bit colour. The 8-bit white (255,255,255) is actually gray in 10-bit colour.

Let me follow up with how it looks like from a camera shot.

**Comment by koush** [comment]
@mathewng can you try changing the decoder in device settings to webassembly? that uses a different rendering process (sort of), and may fix it.

**Comment by koush** [comment]
in any case, i think i have a fix, which is to force electron to use srgb which apparently opts it out of the hdr capability.

those screenshots look unusually bright to me, and both look the same. a picture would be better.

**Comment by mathewng** [comment]
![camera_video_native hardware](https://user-images.githubusercontent.com/15259279/81373503-76bfe780-912f-11ea-9ce4-03d02910783e.jpg)

using native hardware, the issue is as I reported above, white looks gray.
using native software, it looks exactly the same as native hardware.

![camera_video_web assembly mainline](https://user-images.githubusercontent.com/15259279/81373508-7c1d3200-912f-11ea-89cf-f0bd5f1cdfc2.jpg)

using web assembly mainline (I had to use mainline), white in device window looks way better now, very close to the white in the main window but white is still not white (could be due to other issue).

The phone camera is also adjusting to the lighting in the scene, so actually it looks much worse for native hardware/software enough that I wouldn't use it and looks usable for web assembly.

**Comment by mathewng** [comment]
> in any case, i think i have a fix, which is to force electron to use srgb which apparently opts it out of the hdr capability.
> 
> those screenshots look unusually bright to me, and both look the same. a picture would be better.

In Windows 10, most screen capture software captures screenshots that looks overexposed when HDR is enabled. The resulting output image format only captures values up to 255, anything more is truncated to 255. In HDR, the values can up to 1024 levels (10-bit colour)

Not entirely sure if the screen capture software or OS or the image format is the issue but I pressed the print screen key to take the screenshot.

**Comment by koush** [comment]
The actual srgb fix that disables hdr support will be out next time i roll out a full update (as opposed to the delta ones).

**Comment by koush** [comment]
Try this:
https://github.com/koush/vysor.io/releases/tag/v3.0.81

**Comment by koush** [comment]
Fixed.
