### ISSUE TITLE
Wireless screen sharing not available after upgrade

### ISSUE THREAD

**Issue by ethelredkent** [koush/vysor.io#506]
Mac Mini Catalina
Android 6.0.1 Samsung s5 phone
Android 7.1.1 Samsung Galaxy Tab A
Vysor Pro 3.0.73 
Since the upgrade the wireless  mode option is no longer shown. It worked just fine in the older versions. 
Great software BTW but the upgrades have been a major step backwards for me. 
Regards Bruce

![vysor3 0 44](https://user-images.githubusercontent.com/48071913/81341698-d30b0480-9066-11ea-9f39-3cce0ff3afe1.png)

**Comment by koush** [comment]
wireless mode is under device settings, or in the title bar of the device. i'll add it to the main window again.

**Comment by koush** [comment]
![image](https://user-images.githubusercontent.com/73924/81351316-e030ef00-9078-11ea-9333-b5ce77ce6887.png)
