### ISSUE TITLE
Window stuck off screen

### ISSUE THREAD

**Issue by happygoing63** [koush/vysor.io#507]
Dear Sir or Madam,

After the last update, my Vysor window will not open Max.  This is happening on both my laptop and desktop.  Both are using Windows 10.

Vysor Ver 3.0.67

Thanks!

**Comment by koush** [comment]
screenshot please.

**Comment by happygoing63** [comment]
![vysor (2)](https://user-images.githubusercontent.com/64649536/81409258-c9d47300-910c-11ea-9fa2-4c164f948984.png)

It will show Vysor only when I hover over the icon.  When I click the icon non of the window will expand.  This is occuring both my laptop and desktop.

Thanks!

**Comment by koush** [comment]
Did you have a second monitor or something? Seems the windows ended up off screen.

**Comment by happygoing63** [comment]
Yes I got 2 monitors
On 5/8/2020 9:48:43 AM, Koushik Dutta <notifications@github.com> wrote:
Did you have a second monitor or something? Seems the windows ended up off screen.

**Comment by CCattano** [comment]
@happygoing63 

Try this, it's what I do if a window somehow ends up going off my screen.

1. Hover the icon in the task bar, like you did in your screenshot
2. When the two vysor preview windows pop up (like in your screenshot) select the one that you cannot find, that window now has focus
3. Use Win + Left_Arrow or Win + Right_Arrow to get the window to snap to one of the sides of your monitors, bringing it back into view.

Sometimes the OS just manages to pop a app open off the screen. Or like, only a couple pixels of the border of a window are in view and the rest is off screen, etc.

The Vysor app doesn't really have control over how the OS opens it up when these things happen. 

Unless there is source code that is hooking into the window's position and doing positioning stuff, but that seems pretty unlikely for the dashboard window, I guess @koush would have to confirm.

Just seems like a spot of bad luck à la your OS but those steps above should get you taken care of.

**Comment by koush** [comment]
There is code that retains/restores window positions. Will need to make sure it’s in bounds.

**Comment by happygoing63** [comment]
Thanks!  This did the trick!!!  Greatly Appreciated!!!
On 5/8/2020 2:06:06 PM, CCattano <notifications@github.com> wrote:
@happygoing63 [https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhappygoing63&amp;data=02%7C01%7C%7C41e185d2cb0240efa80e08d7f37a7a04%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637245579657869134&amp;sdata=NtxElX5KO0D%2F%2BgmNKPgYvQw8OLiHRZ9p1aDelhQgOa0%3D&amp;reserved=0]
Try this, it's what I do if a window somehow ends up going off my screen.
* Hover the icon in the task bar, like you did in your screenshot
* When the two vysor preview windows pop up (like in your screenshot) select the one that you cannot find, that window now has focus
* Use Win + Left_Arrow or Win + Right_Arrow to get the window to snap to one of the sides of your monitors, bringing it back into view.
Sometimes the OS just manages to pop a app open off the screen. Or like, only a couple pixels of the border of a window are in view and the rest is off screen, etc.
The Vysor app doesn't really have control over how the OS opens it up when these things happen.
Unless there is source code that is hooking into the window's position and doing positioning stuff, but that seems pretty unlikely for the dashboard window, I guess @koush [https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkoush&amp;data=02%7C01%7C%7C41e185d2cb0240efa80e08d7f37a7a04%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637245579657869134&amp;sdata=L%2Bll0At4uQ%2FBxTHlNBh%2BFtN3VMjG5nB2xmD7UWrLfUE%3D&amp;reserved=0] would have to confirm.
Just seems like a spot of bad luck à la your OS but those steps above should get you taken care of.

**Comment by salus-watson** [comment]
I am experiencing this bug and the provided steps:
1. Select the running instance from the taskbar
2. Press (Window Key) + (right) or (Window Key) + (left)

Have failed to set the window within the bounds of my screen.

It may be relevant that I am using the program from an RDP session.
If I had physical access to the computer which is connected to the android device I seek to control, I would not need Vysor.

I have also tried bringing up the screen using the following method:
Press (Window Key) + (Tab) to bring up the Task View
Right click on the Vysor program
Select either "Snap to Left" or "Snap to Right"

Shown below:
![image](https://user-images.githubusercontent.com/70544400/96614419-f5ab7580-12b4-11eb-9e2a-7918d837a27a.png)

**Comment by salus-watson** [comment]
> 
> 
> I am experiencing this bug and the provided steps:
> 
>     1. Select the running instance from the taskbar
> 
>     2. Press (Window Key) + (right) or (Window Key) + (left)
> 
> 
> Have failed to set the window within the bounds of my screen.
> 
> It may be relevant that I am using the program from an RDP session.
> If I had physical access to the computer which is connected to the android device I seek to control, I would not need Vysor.
> 
> I have also tried bringing up the screen using the following method:
> Press (Window Key) + (Tab) to bring up the Task View
> Right click on the Vysor program
> Select either "Snap to Left" or "Snap to Right"
> 
> Shown below:
> ![image](https://user-images.githubusercontent.com/70544400/96614419-f5ab7580-12b4-11eb-9e2a-7918d837a27a.png)

Update:
The following brings the window back onto the current screen (and is similar to the initially proposed solution):
1. Select a window _other than_ the one that you want to get back on the screen, from the taskbar
2. Press (Window Key) + (right) or (Window Key) + (left) to put that window on one side of the screen and bring up a display of all the other available windows, including the one you want to retrieve.
3. Pick the window you are trying to retrieve and it should pop up on the other side of the screen.

**Comment by SYThomasNordmeyer** [comment]
Same issue, Win-RIGHT/LEFT does not help. Having this issue every two months when changing working environment (different monitors). Sometimes trick above works sometimes. There's also something about invisible context menu which helped half a year ago. Trying to remember this solution.

Really annoying.

**Comment by SYThomasNordmeyer** [comment]
Some of these helped https://www.javelin-tech.com/blog/2018/07/how-to-move-a-window-that-is-off-screen/ 
  Win-P
  F11
Don't know which did it finally.

**Comment by cyberpwnn** [comment]
bump. This is very annoying. None of the solutions presented fix the problem.

**Comment by koush** [comment]
Got around to handling this, fix is pending.

**Comment by koush** [comment]
4.0.33
