### ISSUE TITLE
bring vysor window to top on notifications and/or phone calls

### ISSUE THREAD

**Issue by Alaingent** [koush/vysor.io#509]
Could you please develop a small great fonction as , the "Vysor" app up to all others windows as soon as a phone call is received on the phone ?  I m a french user , sorry for my poor english, but i think it could be a good idea to have an option "always on top" BUT only for incoming phone call.

Thank you.

Alain

**Comment by Heretushi** [comment]
Suggestion : if it's feasible, you could poll multiple events and make a toggle grid of user option. You could enable pop on : phone calls, IM, etc.

**Comment by Alaingent** [comment]
Yes exactly it could be very great :) thank you a lot and if one day the chrome version of Vysor could fonction also it will be a good new. Even if now an error message more precise opened, i couldn't open because chrome indicate "installing Vysor APK" and.... nothing else. it is block. But when you are in Chrome browser, it could be useful to just have to change of tab and not, to go in the native desktop version of vysor. Please !! ;) thanks a lot (pro user i m and happy to)

**Comment by clubtech** [comment]
+1 on bringing the Vysor window to the front on a phone call event. Any possibility to implement this?

**Comment by koush** [comment]
This is a stretch goal currently, as there's a larger design consideration around mirroring notifications altogether.

**Comment by clubtech** [comment]
Just wanted to revive this request. Would it be possible to have the Vysor window pop up on top of other windows when an incoming call event is happening? This would be extremely useful for answering calls quickly using the phone's speaker without reaching out to phone.

**Comment by koush** [comment]
https://twitter.com/vysorapp/status/1304952083578150912

**Comment by koush** [comment]
It's implemented. Please open new issues as you find bugs.

**Comment by Alaingent** [comment]
dear, thanks a lot for your notification implementation. But, yes there are notifications, but when a click on the notification, the window disappear but vysor interface and android application concerned by the notification doesnt open. Please when i click on the small right down corner windows notification, vysor interface has to automatically appear on the first plan on windows in front of all others app opened, AND in Vysor program, the application of android has to open, exactly like in your twitter demo. 
Also, and only for incoming calls, please, in addition of the windows notification,  make Vysor interface go automatically on the first plan whithout even if we don't click on the notification, like "always on top" option but only when a incoming call arrive.

thank you

**Comment by Alaingent** [comment]
thank you for the moment when now, i click on a notification, the app on my android phone open, BUT the vysor app on win 10 doesn"t appear on TOP so there is no interest if not. Also, the notification "keyboard change" of Vysor is pop up 10 or 100 times per hour !! please fix it of possible.

**Comment by Heretushi** [comment]
Regarding the "keyboard change" notification : 

- It happens every time you switch apps.
- You can disable the notification spam by setting the notification as "Silent".
- It's less than ideal, I agree. But it fixes the spam.

**Comment by Alaingent** [comment]
thank you but what do you mean by "silent" ? just sound of, but notification appear ? or really this one notification doesn't appear anymore from now to the next update ? and where could i make "silent" mode please on my android or/and windows 10 ?

**Comment by Heretushi** [comment]
![image](https://user-images.githubusercontent.com/46582434/93214032-a365ba80-f732-11ea-84eb-d52e7625a710.png)

This is the Silent option I have on my Pixel 3 running Android 10.

**Comment by Alaingent** [comment]
so yes it is "just" a silent notification. but present on my desktop. why this notification  couldn't be deleted ?? 

and for the second chapter, could you make possible "put on top" when i click on a notification ?

**Comment by Heretushi** [comment]
> so yes it is "just" a silent notification. but present on my desktop. why this notification couldn't be deleted ??

On my computer, when I put the ANDROID notification on Silent, there is no more any WINDOWS notification poping-up.

> and for the second chapter, could you make possible "put on top" when i click on a notification ?
This bug entry is closed. You want to open a NEW bug report for this issue/suggestion.

**Comment by Alaingent** [comment]
when i click on a notification NO, the android app open BUT the Vysor windows app doesn't come "on the first plan" (like always on top). So i click on the notification, the notification disappear and... nothing else

**Comment by Heretushi** [comment]
Again. You are writing your comment on bug entry #509. Bug entry 509 is closed. It's still a very valid concern and you should open a new bug entry, one that is not closed. :)

**Comment by Alaingent** [comment]
but it is not me that close the 509 case. Why closed it ? the bug concern really the same point because not active with full fonction actually
