### ISSUE TITLE
Title bar controls have reduced/smaller hit regions

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#511]
**Describe the bug**
Just updated to 3.0.77 and the padding around my title bar images / options just reduced significantly, so that there's no padding around the actual image's dimensions.

**To Reproduce**
1. Put some buttons in your title bar or use the default.
2. Hover the mouse over them and notice the smaller / reduced hit region.

**Expected behavior**
Re-add the padding that existed to make it easier to press the correct button in the title bar.

**Screenshots**
[Screenshot.](https://imgur.com/2W7LuYp)

**Desktop :**
 - OS: macOS
 - Vysor 3.0.77

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: 8.1.x

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/489

**Comment by koush** [comment]
The current padding is still bigger than the buttons of the original version of vysor.

**Comment by crouchingtiger** [comment]
Ah I see - I guess for the default set of title bar buttons you needed to squeeze them in or find a reasonable average width. I only keep those 2 items in my custom titlebar so it makes it more difficult to click the correct item.

In the end I've decided to go with your key-mapping KeyboardEvent.key support, though I'm having trouble mapping with additional ``metaKey`` params currently. ``VYSOR_SCREENSHOT`` seems to open an empty browser window so it's less ideal, hence the mouse/button pressing.

**Comment by koush** [comment]
I did change the vysor screenshot and screen recording download behavior in the last update. Does it actually perform the download though? Open a separate bug.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/512

**Comment by crouchingtiger** [comment]
> I did change the vysor screenshot and screen recording download behavior in the last update. Does it actually perform the download though? Open a separate bug.

My bad, even the button does the same (opens a blank tab). I didn't click it since the latest update due to the small hit region. It does work, but it will bring my browser to front, with an empty tab. Generally speaking I don't mind that the save panel doesn't appear since I don't name my screenshots anyway (I was previously using ``adb exec-out screencap -p > ~/Desktop/`date +Screenshot_%s.png`\n`` in my Terminal). I'll open an issue.
