### ISSUE TITLE
Feature Request: Configurable Title Bar Padding

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#512]
This is gonna sound needy af, lol.

In relation to the fix for #489, could you possibly expose the padding as a configurable setting in the Customize Vysor settings for folks who don't have giant phone names or have no problem with renaming their giant phone names to reasonable names and liked having some spacing and padding between their buttons?

Maybe expose the functionality as a, "style" property that can be used along side the, "class" property already in place to specify button icons?

**Comment by koush** [comment]
I’ll see if I can do this automatically with some responsive css classes.

**Comment by koush** [comment]
It’s not just a giant phone name issue, some people also have small monitors or use for scaling.

**Comment by koush** [comment]
use the "dense" config in customize vysor
