### ISSUE TITLE
Vysor screenshots cause default browser to open a blank-tab

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#513]
**Describe the bug**
Clicking the screenshot button or action ``VYSOR_SCREENSHOT`` through a key event. The default browser will open, and download the screenshot to the default Downloads directory. 

**To Reproduce**
1. Connect a device for viewing.
2. Click on the screenshot button in the title bar.
3. Browser opens and download automatically begins/ends.
4. Opened tab remains open.

**Expected behavior**
Previous versions would bring up the default save panel dialog. I am fine without showing a save panel dialog, but would prefer using a different solution that doesn't attempt to open the Vysor webserver URL / payload that will cause the browser to launch an empty tab.

**Screenshots**
-

**Desktop:**
 - OS: macOS 10.15.4
 - Vysor 3.0.77

**Android:**
 - Device: Pixel 2 XL
 - OS: 8.1.x

**Comment by koush** [comment]
The previous v3 version had some reliability issues that I was unable to track down. Used a service worker to do the download.
This is how the v2 version was implemented. Might just create a landing page or something.

**Comment by koush** [comment]
Fixed in v3.0.79. It no longer shells out to the default browser to do the download. Reload to trigger the update check and please confirm.

**Comment by crouchingtiger** [comment]
Can confirm (3.0.80), macOS default save panel appears as before.
