### ISSUE TITLE
Can no longer save videos to my computer

### ISSUE THREAD

**Issue by ecramer** [koush/vysor.io#514]
**Describe the bug**
Screen capture videos can no longer be saved to my computer. Vysor asked me to update this morning so I reloaded and it's been happening since then. 

**To Reproduce**
1. Start recording a video
2. Stop recording a video
3. Video opens in browser
4. Right click and Save As. 

It either downloads with 0 bytes or an error dialog displays saying it can't be downloaded.

**Expected behavior**
A save dialog used to come up asking me where I wanted to save the video to. This no longer happens. I expect to be able to save the video to my computer in some fashion.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Vysor Version: 3.0.77 or 3.0.67 (I don't know which version is the correct one, I see 2 different versions within the app)

**Android (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Comment by koush** [comment]
Does the video play?

**Comment by koush** [comment]
Weirdly, it’s supposed to download the file, not play it in the browserr. Which browser?

**Comment by ecramer** [comment]
Yes the video plays in the browser. This is in Firefox.

**Comment by koush** [comment]
I think I need to add some headers. Give me a moment. https://stackoverflow.com/a/3802630

**Comment by koush** [comment]
Fixed in v3.0.78. Please reload to trigger the update. It no longer shells out to the default browser to do the download.

**Comment by koush** [comment]
Fixed in v3.0.79. It no longer shells out to the default browser to do the download. Please confirm.
