### ISSUE TITLE
Stuttering when dragging Vysor device window.

### ISSUE THREAD

**Issue by technomadic42** [koush/vysor.io#516]
When dragging the device window from one location to another on the desktop, under Windows 10 Pro x64, the window will "stutter" and fail to follow the mouse, or shake and stop moving altogether.
**Desktop (please complete the following information):**
 - OS: Windows 10 pro x64
 - Vysor Version 3.0.77 pro

**Android (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: N/A
 - Vysor Bug Report Link:
https://gist.github.com/VysorLogs/e03edfb156e175b85910e1ea2e21f7a8

**Additional context**
O/S and device information as well as logs is N/A as the device functions fine as does the display from it.  when moving the window (even with the device disconnected) the response is sluggish/shaky.

**Comment by koush** [comment]
Can you create a video of this?

**Comment by technomadic42** [comment]
I've left the office for the day, but will do so tomorrow am.
