### ISSUE TITLE
Update menu bar icon for macOS

### ISSUE THREAD

**Issue by melvinsalas** [koush/vysor.io#517]
All macOS menu bar icons are black and vectorized. It can be change to provide a better experience.

**Screenshots**
<img width="208" alt="Screen Shot 2020-05-09 at 5 55 06 PM" src="https://user-images.githubusercontent.com/708747/81487814-8702c000-921e-11ea-8438-45b23aaaddf1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Vysor Version: 3.0.44

**Comment by koush** [comment]
![Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_AppleBluetoothExtra_and_AirPortExtra_and_DisplaysExtra_and_EjectExtra_and_AppleClockExtra](https://user-images.githubusercontent.com/73924/81491466-c98ac380-9243-11ea-9e79-07681618898e.png)
![Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_AppleBluetoothExtra_and_AirPortExtra_and_DisplaysExtra_and_EjectExtra_and_AppleClockExtra](https://user-images.githubusercontent.com/73924/81491474-d1e2fe80-9243-11ea-9665-3136db2c0cd2.png)

**Comment by koush** [comment]
i dunno how to make vectors.

**Comment by melvinsalas** [comment]
I hope this can help you:

<img width="616" alt="Screen Shot 2020-05-10 at 12 05 05 AM" src="https://user-images.githubusercontent.com/708747/81492049-f940c800-9251-11ea-9dbd-d73fab8c1079.png">

[vysor.svg.zip](https://github.com/koush/vysor.io/files/4605228/vysor.svg.zip)

**Comment by koush** [comment]
Cool, thanks. Just tried it out, and it seems electron does not support svg tray icons. Will investigate further.

**Comment by melvinsalas** [comment]
I found this:

> icon (default opts.dir + IconTemplate.png) - the png icon to use for the menubar. A good size to start with is 20x20. To support retina, supply a 2x sized image (e.g. 40x40) with @2x added to the end of the name, so icon.png and icon@2x.png and Electron will automatically use your @2x version on retina screens.

[icons.zip](https://github.com/koush/vysor.io/files/4605275/icons.zip)

**Comment by koush** [comment]
I saw those docs as well, and I think they are actually incorrect on the electron tray sizes for mac. Should be 16x16 and 32x32.
![Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/73924/81493381-c0eeb900-9254-11ea-8541-de1e2d0f4fc6.png)

**Comment by koush** [comment]
i can convert your svg into the appropriate size

**Comment by koush** [comment]
![Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/73924/81493544-eb8d4180-9255-11ea-9b7a-60cd6c9ec00b.png)
![Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/73924/81493548-f47e1300-9255-11ea-8c7a-b01ec9796cff.png)

**Comment by melvinsalas** [comment]
Great!

I think looks better than the colored icon.

Thanks for take notice my recommendation

**Comment by melvinsalas** [comment]
I noticed the corners look not rounded on 16x16, then I remake the icon using AdobeXD with the minimum reference size 16x16 (and 32x32)

<img width="645" alt="Screen Shot 2020-05-10 at 3 24 07 AM" src="https://user-images.githubusercontent.com/708747/81495548-36b34e80-926e-11ea-9239-073f88735ac4.png">

And the result is more clear

<img width="506" alt="Screen Shot 2020-05-10 at 3 30 26 AM" src="https://user-images.githubusercontent.com/708747/81495596-9e699980-926e-11ea-8d48-56660cce91e1.png">

[IconTemplate.zip](https://github.com/koush/vysor.io/files/4605431/IconTemplate.zip)

**Comment by koush** [comment]
released
