### ISSUE TITLE
Feature request (low importance): Set ADB path via customizable settings

### ISSUE THREAD

**Issue by TomasVseticka24i** [koush/vysor.io#518]
When i start Android studio it also start its "own" ADB. Later when i start Vysor it works fine with already running ADB. But if i start Vysor first or close AS then Vysor start its own ADB. If those ADBs are different version then they do not like each other. When i try to pass some command it is saying something like different version and killing running process to run itself.
Please, would it be possible to add path to ADB into settings in "customize vysor" section?

**Comment by koush** [comment]
I know about this issue. I update the vysor adb to the latest as soon as possible. And in any case, the conflicting adbs end up using the latest after some negotiation. It all works itself out.
I don’t want to put in a path option that some inexperienced user will inevitably mess up.

**Comment by koush** [comment]
For reference, vysor doesn’t actually use adb for the client. It packages the binary to start adb server. It will then continue using whatever adb server is presently running.
