### ISSUE TITLE
Black Screen on LockScreen

### ISSUE THREAD

**Issue by KarlVanSnail** [koush/vysor.io#519]
Hy!

If I turn off the Screen and go to the Lockscreen my screen turn black and I cant type in my PIN Code.
Is this an Android Security Feature?

Huawei Mate 20 Pro

Kind Regards

**Comment by koush** [comment]
Uh, yeah, your screen is off. So it’s black.

**Comment by KarlVanSnail** [comment]
I can't type in my PIN Code over Vysor because Vysor don show the lockscreen

**Comment by koush** [comment]
Did you try turning your screen back on

**Comment by KarlVanSnail** [comment]
Yes of course. I see on the Phone the "Enter your PIN Screen" and on Vysor Remote its only black.
But I can click on the black screen and my phone take the numbers, but i have to be lucky to get the right positions on the Vysor Black Screen

**Comment by KarlVanSnail** [comment]
![20200511_153824](https://user-images.githubusercontent.com/6966591/81568100-9c522880-939d-11ea-8431-74d8701c8314.jpg)

**Comment by koush** [comment]
Is it just the lock screen that is black?

**Comment by KarlVanSnail** [comment]
Yes at lockscreen vysor is black

**Comment by koush** [comment]
I mean, does it work on apps outside of the lock screen? Your lock screen might be DRM protected to prevent screen capture.

**Comment by KarlVanSnail** [comment]
Yes all is working until the lock screen.
The funny thing is I can click on the black screen of vysor and I can enter the numbers, but I only can guess the positions, because the lockscreen isnt showing

**Comment by koush** [comment]
Your lock screen is DRM protected preventing screen capture. This is not a vysor bug.
