### ISSUE TITLE
Ubuntu x64 + Redmi Note 3G

### ISSUE THREAD

**Issue by sicksand** [koush/vysor.io#52]
Hi, 

Vysor detect the phone but no display in the chrome.

![selection_072](https://cloud.githubusercontent.com/assets/305408/9726416/05aa0944-5625-11e5-88a8-5b06802817f2.png)
![selection_073](https://cloud.githubusercontent.com/assets/305408/9726415/05a9c31c-5625-11e5-812f-749041de9540.png)

![selection_074](https://cloud.githubusercontent.com/assets/305408/9726447/85845214-5625-11e5-820c-ca47affbc696.png)
![selection_075](https://cloud.githubusercontent.com/assets/305408/9726445/8582f84c-5625-11e5-8d58-d7b3bda92574.png)
![selection_076](https://cloud.githubusercontent.com/assets/305408/9726446/8583e11c-5625-11e5-9a8b-7a97a1e219f4.png)

**Comment by koush** [comment]
https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp
