### ISSUE TITLE
Unlicensed - Retrieve License 

### ISSUE THREAD

**Issue by jennifersbrenner** [koush/vysor.io#521]
Purchased license on 5/8 have not been able to get Vysor to locate license.

Logging into Gmail account with same account license was purchased from and purchase email sent to.

**Comment by koush** [comment]
Can you share a transaction number please

**Comment by jennifersbrenner** [comment]
Receipt #1837-6268

**Comment by koush** [comment]
Attach a bug report. Please pay attention to the issue template.

**Comment by jennifersbrenner** [comment]
**Describe the bug**
Vysor does not see license

**To Reproduce**
Steps to reproduce the behavior:
1. Open Vysor
2. Status shows: You've used Vysor for 2 hours. An advertisement will be shown every 15 minutes while viewing an Android. Purchase Vysor Plus to remove ads and unlock all features.

![image](https://user-images.githubusercontent.com/65050448/81688944-e849af80-9427-11ea-86a0-45c8ef882372.png)


3. Click on Login - log into Gmail account.

4. See error  - unlicensed.  Already Purchased?  Retrieve License.

**Expected behavior**
Expected license to be retrieved.
![image](https://user-images.githubusercontent.com/65050448/81691519-f2b97880-942a-11ea-9dc5-977baafd05d0.png)

5.  Get No license found for account.  If this message was in error, please click Support for more help,  
![image](https://user-images.githubusercontent.com/65050448/81691548-006efe00-942b-11ea-80cb-e87a2fb13315.png)


**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Vysor Version 2.3.0


**Vysor Bug Report**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

https://gist.github.com/VysorLogs/4f92c5c5034f7d05fddae759dfd27299

**Comment by koush** [comment]
That is an unsupported version of vysor. Download the new version or use app.vysor.io if you are on a chrome book.

**Comment by koush** [comment]
In any case, you aren’t logged into chrome on that bug report or screenshot, which is why the license is not working. But that may be because chrome apps are not supported by google anymore.
