### ISSUE TITLE
Device Settings Page Header Doesn't Match Theme Settings

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#522]
This may be more of a feature request than a observed defect. It might be the case that this was never meant to be customizable.

**Describe the bug**
The header for the Device Settings page does not have the same color background as other various parts of the Vysor ecosystem that are affected by the customizable theme settings.

**To Reproduce**
1. Go to Device Settings via whatever title bar configuration is setup to trigger the VYSOR_OPEN_DEVICE_SETTINGS event.
2. Header background is Orange and not the same color as the other parts of the Vysor ecosystem that change based on theme settings

**Expected behavior**
Expected the background color of the Device Settings page header to be the color specified in the, "themeColor" property that can be configured via the, "Customize Vysor" window.

**Screenshots**
![image](https://user-images.githubusercontent.com/47487276/81592462-a1a27980-9383-11ea-8bfe-00acbbe585c6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393) (14393.rs1_release.200131-0410)
 - Vysor Version: 3.0.84

**Android (please complete the following information):**
 - Device: Samsung Note 9 (SM-N960U)
 - OS: Android 10, Samsung One UI v2.0
 - Vysor Bug Report Link: Have link, can provide if needed

**Vysor Bug Report**
Have link, can provide if needed. Is there a way to provide a piece of identifying information about the report so that you can find the private report in the VysorLogs repo so that only you can access the report containing my email address?

For example it looks like the report is located at VysorLogs/7c4efdcb-e438-4d8a-b048-ebd59dbda81c.txt and the guid in the file name differs from the guid in the github link. So people would not be able to brute force the link via the file name but hopefully you could still find the file in your private repo, and ultimately not expose my email address to the public.

**Android Logcat**
Unfamiliar with this. If you can explain what I need to do I'd be more than happy to perform those steps and relay the information this provides.

**Additional context**
N/A

**Comment by koush** [comment]
I'll add an accent color option for dialogs.

**Comment by koush** [comment]
Fixed in 3.0.86. Use accentColor.
