### ISSUE TITLE
3.0.84 Streaming to OBS Studio Broken

### ISSUE THREAD

**Issue by ozgp** [koush/vysor.io#523]
Greetings,

Version 3.0.8xx Streaming (typically to OBS Studio) no longer works.  In addition the streaming URL's are missing from the Settings so it is now impossible to verify what are the URL (if they have changed).

Device -> Settings (Missing information to display URL's)
When browsing to existing URLS they no longer stream.

https://github.com/koush/vysor.io/wiki/Vysor-and-Video-Broadcasting-(Open-Broadcast-Studio) Instructions for more information. 

Desktop (please complete the following information):

OS: Windows 10
Vysor Version 3.0.84
Android (please complete the following information):

Device: Pixel XL 2
OS: Android 10

**Comment by koush** [comment]
Fixed in 3.0.86.
