### ISSUE TITLE
Desktop Rotate Screen not working in camera app

### ISSUE THREAD

**Issue by Phillewis63** [koush/vysor.io#525]
I'm using Vysor on a Samsung S20+ Android 10 with Windows 10.  When using the camera ap the phone rotation is working properly but when I select "Rotate Screen" on the pc nothing happens.  This function works properly when using other aps.

**Comment by koush** [comment]
camera apps are locked to landscape.

**Comment by Phillewis63** [comment]
Thank you Koush.  I'm not understanding.  The camera app does rotate on the phone.

**Comment by koush** [comment]
The orientation is locked.
