### ISSUE TITLE
unable to connect to shared device

### ISSUE THREAD

**Issue by cnuppo** [koush/vysor.io#526]
**Describe the bug**
Vysor 3.0.84
when i share my phone and open copied link in chrome on another machine an error
appears "Error Connecting to Android Device TypeError: Cannot read property 'send' of undefined"
I have tried on 3 different machines with windows 10 and updated google chrome connected to internet with the same result!!! otherwise the phone connects via usb and opens with no issues.
nacl is instaled, but nacl test page freezes on loading the demo... all suggestions in vysor support 
page gave no result.
![vysor](https://user-images.githubusercontent.com/65263341/81760176-3665be00-94cf-11ea-8d07-7b4f3ca4e723.jpg)

**Comment by koush** [comment]
fixed in v3.0.85.

**Comment by JonYeeY** [comment]
I have this issue with too.
Android TV Boxes connected with ethernet.
With USB cable works, without not.
![Vysor Error](https://user-images.githubusercontent.com/53002243/87535651-1ce01e80-c698-11ea-9b0a-0ea5ecab5cac.png)
