### ISSUE TITLE
audio loop failed Error: Request failed with status code 404

### ISSUE THREAD

**Issue by ozgp** [koush/vysor.io#527]
Audio no longer shows Vysor device when sharing.. Log is showing 404 errors..

Checking License...
enterprise cache not licensed
clockwork cache licensed
found plugin for application/x-ppapi-vysor
Waiting for Decoder...
NACL module initialized
decoder: software
Connecting to Vysor on Android...
first frame received, non-baseline: false
audio loop failed Error: Request failed with status code 404
audio loop failed Error: Request failed with status code 404

**To Reproduce**
1. Go to Toggle 
2. Click on Cast (Missing Vysor Device)

**Expected behavior**
Should see Vysor Device to Share Audio

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 3.0.86

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10

**Comment by koush** [comment]
Will fix this.

**Comment by koush** [comment]
Fixed in 3.0.87.
Need to refresh some cast certificates annually.

**Comment by ozgp** [comment]
Solved :)  Thanks Koush, loving your work..
