### ISSUE TITLE
Feature request: Customizable title bar icon set

### ISSUE THREAD

**Issue by Egorand** [koush/vysor.io#528]
My title bar currently looks like this: 

![image](https://user-images.githubusercontent.com/1186186/81824890-f66cfe00-9503-11ea-9d5a-bd77c1c2a3a3.png)

I never use the "Toggle Audio" feature, however I frequently take screenshots. I'd like to swap the options so that the one I use more frequently is only one click away.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Vysor Version: 3.0.84

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10

**Comment by koush** [comment]
This exists. Use customize vysor.

**Comment by Egorand** [comment]
Cool, thanks, didn't know that's a thing!
