### ISSUE TITLE
Screenshots and video recording not working 

### ISSUE THREAD

**Issue by ecramer** [koush/vysor.io#529]
**Describe the bug**
Cannot take a video or screenshot.

**To Reproduce**
1. Click on camera or click on record

**Expected behavior**
A screenshot is taken or a video is recorded. Neither happens.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Vysor Version 3.0.87

**Android (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Comment by koush** [comment]
Bug report please.

**Comment by ecramer** [comment]
https://gist.github.com/VysorLogs/cf2928c545a3742359fc0ad86d9d0442 
I also have a video screen recording if you need it 🤷‍♀️

**Comment by koush** [comment]
Can you try a screenshot? I only see recording attempts.

**Comment by ecramer** [comment]
https://gist.github.com/VysorLogs/dfa8ec75494627edd31ceac9debab6c0
Here's a video that shows what happens on camera click. It just stays highlighted forever and then I can click it again and it toggles off. 
[Screen Recording 2020-05-13 at 9.30.47 PM.zip](https://github.com/koush/vysor.io/files/4625566/Screen.Recording.2020-05-13.at.9.30.47.PM.zip)

**Comment by koush** [comment]
Does this error persist after hitting Reload?

**Comment by koush** [comment]
Incidentally, in the second log it seems that a screenshot attempt was not made.

**Comment by koush** [comment]
The logs indicate the screen recording and screenshot was made, but the actual download didn't happen. Taking a further look.

**Comment by ecramer** [comment]
> Does this error persist after hitting Reload?

yes.

**Comment by koush** [comment]
Let me add some logging and push an update.

**Comment by koush** [comment]
3.0.90 has more logging and a potential fix. please trigger an update check with reload and get me another bug report with a screenshot attempt.

**Comment by ecramer** [comment]
Issue has been resolved 👍 3.0.90 works
