### ISSUE TITLE
Vysor: can't scroll down on touch screen

### ISSUE THREAD

**Issue by Matisachs** [koush/vysor.io#53]
Hi,
I have successfully installed Vysor on a windows 8, 64 bit PC connected to a touch screen. Everything works well however I am not able to scroll down/up nor move screens aside on the touch screen (only with the mouse).
Can you please suggest a solution for this?
Thanks.

Mati Sachs

Cardo Systems Inc.

matis@cardosystems.com

**Comment by koush** [comment]
Yeah, need to handle touch events vs mouse events.

**Comment by koush** [comment]
fixed
