### ISSUE TITLE
3.0.87 Streaming Issues (Lag etc)

### ISSUE THREAD

**Issue by ozgp** [koush/vysor.io#530]
**Describe the bug**
Network Streaming with 3.0.78 appears to be problematic / slow to start / lagging when opening up the Stream in VLC (I cannot get OBS Studio to work in this version) I am noticing a good 12-15 second lag behind what I can see outputting on the PC Vysor window 

**To Reproduce**
1. Go to Settings 
2. Copy the Streaming Line
3. Open VLC / Network Stream
4. Paste Link 

**Expected behavior**
Real Time Stream

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 3.0.87

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10
 
I am noticing a number of errors in the log

found plugin for application/x-ppapi-vysor
Waiting for Decoder...
decode called before initialization
decode called before initialization
decode called before initialization
decode called before initialization
decode called before initialization
decode called before initialization
decode called before initialization
NACL module initialized
decoder: hardware
decode called before initialization
Connecting to Vysor on Android...
first frame received, non-baseline: false

**Comment by koush** [comment]
You mean the web video stream? Lag is normal. VLC, OBS, etc, will all buffer the video.

**Comment by ozgp** [comment]
Hey Kouch,

Sorry mate but lag has changed for the worse.. You did have a slight lag in older versions for sure but this is pretty excessive (10++ seconds).. Could you please take a look.

Thanks

**Comment by koush** [comment]
You are talking about importing a  web video stream link right?

**Comment by ozgp** [comment]
Yes typically through OBS Studio as Vysor had separated Audio and Video which only a few applications can manage..  As of 3.0.9.0 the lag is back to a 3-5 seconds which is a typical buffer however OBS Studio is not happy and it is complaining it cannot cannot find the feed info.. (Which is strange as VLC can)..

08:06:07.893: [Media Source 'Vysor']: settings:
08:06:07.893: 	input:                   http://127.0.0.1:59310/flash.flv
08:06:07.893: 	input_format:            
08:06:07.893: 	speed:                   100
08:06:07.893: 	is_looping:              no
08:06:07.893: 	is_hw_decoding:          yes
08:06:07.893: 	is_clear_on_media_end:   yes
08:06:07.893: 	restart_on_activate:     yes
08:06:07.893: 	close_when_inactive:     yes
08:06:07.925: MP: Failed to find stream info for 'http://127.0.0.1:59310/flash.flv'

This brings me back to another point and I not tested this have you interlaced Audio and Video as I can see just a single feed http://127.0.0.1:59310/flash.flv however VLC is reporting it has no Audio component.

**Comment by koush** [comment]
Fixed in 3.0.93

**Comment by koush** [comment]
Was sending some packets before the flash writer was ready, causing some potential lag issues.

**Comment by ozgp** [comment]
Thanks Koush for taking the time to track this down..

**Comment by Leomhl** [comment]
I Have the same issue! Mac Mojave, phone Redmi S2. "Waiting for decoder", black screen. But, I can execute actions in the phone by vysor, but, the screen is black :/

**Comment by ZeeshanAhmadKhalil** [comment]
Its lagging for me too much, connected through USB
