### ISSUE TITLE
3.0.8.7 Vysor Tray Showing No Devices (When Connected)

### ISSUE THREAD

**Issue by ozgp** [koush/vysor.io#532]
**Describe the bug**
Vysor is connected..  However Visor in the Tray is Showing No Devices 

**To Reproduce**
Steps to reproduce the behaviour:
1. Minimise Vysor
2. Windows Tray, Right Hand Mouse Click on Vysor 
3. Popup shows no Devices Detected

**Expected behaviour**
Device should be listed :-)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 3.0.8.7

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10

**Comment by koush** [comment]
Did you use wireless mode or anything?

**Comment by ozgp** [comment]
Wireless (yes) and good spot as it shows a connected device on Wired..

**Comment by koush** [comment]
Ok, I found the issue.

**Comment by ozgp** [comment]
I knew you would.. :)
