### ISSUE TITLE
Audio problem 

### ISSUE THREAD

**Issue by Baiinca** [koush/vysor.io#534]
hi :)
so, I use windows 10 and, before vysor update (now is 3.0.91), I was able to record my audio on the program with an aux cable, but now it isn't working anymore... my cellphone is Zenfone 4 ZE554KL, and uses Android version 8.0.0
what is happening?

**Comment by koush** [comment]
Nothing changed in that regard. Reboot your phone and turn the volume or. Or check your computer recording settings.

**Comment by Baiinca** [comment]
I already tried to do everything you said, but it's not working anymore :(
can you explain to me a way to record my audio successfully, please?
