### ISSUE TITLE
Vysor does not have a privacy policy

### ISSUE THREAD

**Issue by ducalpha** [koush/vysor.io#535]
**Describe the bug**
https://www.vysor.io/ and [app](https://play.google.com/store/apps/details?id=com.koushikdutta.vysor&hl=en_US) do not have any privacy policy.

**To Reproduce**
1. Go to https://www.vysor.io/
2. Find no privacy policy links/documents.

**Additional context**
Google and laws in the US and EU require a privacy policy for apps and websites.

**Comment by koush** [comment]
https://www.vysor.io/privacy
