### ISSUE TITLE
3.0.91 - Screen Too Yellow ?

### ISSUE THREAD

**Issue by kazhuyo** [koush/vysor.io#536]
After upgrade to version 3.0.91 my vysor screen becomes more yellow, but the device normal.

[Screenshoot](https://imgur.com/nJLhytE)

How to solve this ? any new setting ?

**Comment by koush** [comment]
can you see if this happens on a different phone?

**Comment by kazhuyo** [comment]
Yep, still same issue with my note 9,
But when trying with android emulator, the problem dissapear, this happen only with device.

**Comment by kazhuyo** [comment]
view device via wireless, change device cable, still same results.

**Comment by koush** [comment]
you sure you dont use night mode or something?

**Comment by koush** [comment]
might also be related to windows hdr mode? https://github.com/koush/vysor.io/issues/504

**Comment by koush** [comment]
Try turning HDR off, and let me know. https://support.microsoft.com/en-us/help/4040263/windows-10-hdr-advanced-color-settings

**Comment by kazhuyo** [comment]
HDR Mode solve this problem, thx.

**Comment by koush** [comment]
Hdr mode should work with the most recent download of the app. Can you download it from vysor.io again and check?
