### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by ericjpeters** [koush/vysor.io#537]
For some reason, the current version of Google Authenticator is not displaying through vysor.io.  This used to work great for me, but stopped working recently. 

Basically, the app on my phone is displaying everything as expected, but the display on my desktop is just showing a blank window.

**Comment by koush** [comment]
Some apps prevent screen capture to prevent sensitive data from being leaked. This is one of them.

**Comment by frum14** [comment]
it is possible to set visible inside of settings and restart the app
