### ISSUE TITLE
Can't find screen recording

### ISSUE THREAD

**Issue by bergatron** [koush/vysor.io#538]
**Describe the bug**
I made a recording but can't find the file anywhere on my system.

**To Reproduce**
1. Open Vysor
2. Click on View next to the device
3. Click "Record screen" icon in the top bar.
4. Wonder where the screen recording is saved.

**Expected behavior**
I'm able to find the screen recording, or better yet, choose a default destination for recordings.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Vysor Pro v3.0.91

**Android (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 10
 - [Vysor Bug Report Link](https://gist.github.com/VysorLogs/13851f661d516d51d49af7ff6ca526f1)

**Vysor Bug Report**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Click record again to stop the recording, and it will show a save dialog. Your bug report doesn't show any recording attempts either. Please follow the instructions.

**Comment by koush** [comment]
Also, please verify that screenshots work (not screen recording). This will help me pinpoint any issue if there is in fact a bug.

**Comment by KohlsAdrian** [comment]
iOS 15 - iPad Pro M1 Recording not working

Screenshot working fine

**Comment by kristopher-rovertown** [comment]
Also recently started having this problem w/ recordings for iOS only. Screenshot works fine, but recordings aren't prompting me for filename or destination like it did previously and how it still does for Android.

**Comment by kristopher-rovertown** [comment]
Found a strange workaround:
1. Start the video recording for the iOS device
2. Tap the screenshot button while video recording is active
3. Cancel the screenshot
4. Tap to stop the video recording.
Result: File save prompt pops up for the screen recording as expected. Without steps 2 and 3, no file save prompt appears for the video recording.

**Comment by LeoJHarris** [comment]
That fact others and myself had to search for this suggests there's a usability issue here.

**Comment by harishmandhania** [comment]
Facing the same problem... Connected an android device to mac (m1) laptop.. cant find the video recorded, no popups for saving either...

**Comment by zaphodikus** [comment]
M1 mac Ventura - same issue no video gets saved, screenshots save just fine. iOS 17. Although this seems to be more an M1 issue? However I'm also unable to record on Windows 10 with same phone, so not sure what the commonality is beta iOS here perhaps.

**Comment by jlfreund** [comment]
Same problem for me.  This has worked before for me on same HW setup, so not sure if a MacOS upgrade broke it?

Mac: Apple M2 OS 14.4.1
Vyzor Pro 5.0.7

Screenshot works, but when stopping a video recording, there is no Save dialog (video icon stops spinning, but nothing happens).  Tried the "take a screenshot during video recording" workaround mentioned above, and that doesn't help.
