### ISSUE TITLE
Vysor Audio Output always connecting

### ISSUE THREAD

**Issue by kevin2005015** [koush/vysor.io#539]
**Describe the bug**
When I click on the headphones it redirects me to 'Share Screen', when I can see Vysor Audio Output, but when I click it always says connecting.

**To Reproduce**
1. Go to vysor
2. Click on the headphones
3. Click on 'Vysor Audio Output'
4. Always connecting

**Expected behavior**
It should connect, a few days ago it was working but now doesn't.

**Desktop:**
 - Vysor Version 
![image](https://user-images.githubusercontent.com/49949593/82383436-13d32800-9a2e-11ea-8fe9-435efc344859.png)

**Android:**
 - Device: Sony Xperia XA2
 - OS: Android 9

**Comment by koush** [comment]
Vysor audio is a pro feature. Sorry. Not sure how you even made it that far without seeing an upgrade warning.

**Comment by kevin2005015** [comment]
Ooh I didn't know that, but I can swear that I have connected it more than
1 time
