### ISSUE TITLE
Text editing keys don't work

### ISSUE THREAD

**Issue by lukehutch** [koush/vysor.io#54]
The following text editing keys don't work with Vysor:

* Home is the same as tapping on the home button (apparently by design). This is a weird choice (and easy to accidentally trigger) when remote-controlling from a PC.
* End does nothing.
* Delete does nothing.
* Ctrl+Backspace and Ctrl+Delete do not delete the previous and next word respectively.
* Ctrl + Left/Right Arrow Keys does not move to the prev/next word.
* Shift + Arrow Keys does not select text.
* Tab does not navigate between UI controls.

I believe that a lot of these things do work in Android with Bluetooth keyboards, but they don't work with Vysor. I don't actually have a Bluetooth keyboard handy to test this with though, and it's possible that I only had this working because I also set up the External Keyboard Helper Pro app. However, I'm pretty sure that it's mostly a case of the correct key codes not being sent across by Vysor, since I tested with External Keyboard Helper Pro, and it didn't fix any of these problems.

Interestingly, SwiftKey initially detects Vysor as an external keyboard, and pops up a notification in the notification bar, offering to configure external keyboard support. But then if you click on the notification, no external keyboards are listed. External Keyboard Helper Pro does not detect the Vysor connection as an external keyboard.

There may be two different things that could be done here to improve the situation:

1. Ensure that keyboard combinations like the above are properly sent over ADB.
2. Try to get the Vysor connection to be properly detected as an external keyboard, so that the input method can be automatically switched to External Keyboard Helper Pro, which improves many aspects of using external keyboards.

**Comment by koush** [comment]
Yeah, there's a boatload of key events in Javascript that I need to translate to Android KeyCode events. There's also the issue with international characters not working (as keycodes are language agnostic, they correspond to buttons, not characters). I think ultimately I need to build a custom IME like External Keyboard Helper to handle all these cases properly.

**Comment by koush** [comment]
I think most of these have been fixed. Let me know.
