### ISSUE TITLE
Wireless connection breaks after disconnecting usb cable.

### ISSUE THREAD

**Issue by xerxes3117** [koush/vysor.io#540]
**Describe the bug**
I'm trying to connect my google pixel 2 to my MacBook using the wireless mode.
The phone gets connected wireless showing message "Your device is now wirelessly connected".
However, after disconnecting the cable the connection is broken. Attaching screenshots:

**To Reproduce:**
1) connected the phone using usb
2) click on wifi icon
3) disconnect the cable once connected

**Desktop** (please complete the following information):
OS: macOS 10.15.4
Vysor Pro v3.0.93

**Screenshots**
<img width="516" alt="Screenshot 2020-05-21 at 11 37 59 AM" src="https://user-images.githubusercontent.com/24941920/82529026-b3d8a080-9b57-11ea-96f6-43911d86e000.png">
<img width="515" alt="Screenshot 2020-05-21 at 11 37 49 AM" src="https://user-images.githubusercontent.com/24941920/82529042-bdfa9f00-9b57-11ea-9d67-6fd06894b28b.png">

**Comment by koush** [comment]
You did not attach a bug report.

**Comment by xerxes3117** [comment]
@koush done. Here it is: 
[Bug report](https://gist.github.com/VysorLogs/afc6a5c55451626a786d2291ed517adb)

**Comment by koush** [comment]
Is your phone and computer on the same WiFi? Strange error in the log where it seems the network is down.

**Comment by xerxes3117** [comment]
They are on the same wifi. 
Yeah i also think there's some weird issue here. I tried to ping manually from my mac to android using `ping 192.168.1.6` on terminal. I get the error : 
**Request timeout for icmp_seq**
Can't connect from windows laptop to android too. That shows error:
**Destination host unavailable**

**Comment by koush** [comment]
Can you confirm that is your phones iPad?

**Comment by koush** [comment]
Are you on a vpn that reroutes all traffic?

**Comment by xerxes3117** [comment]
Yeah that's my android's ip on the network.
No i'm not using vpn.

**Comment by koush** [comment]
Unfortunately I don’t have an answer for you. It looks like a general network error as diagnosed by your own attempts to ping. If you solve it, let me know.
