### ISSUE TITLE
Black screen on specific device

### ISSUE THREAD

**Issue by richgb** [koush/vysor.io#541]
Hi,

Since the update to the new version, I have a black screen on one specific device.
It works fine on my Pixel 3, so it is probably not related to chrome or anything Windows side.

I've been using it for months on the previous version, but straight after the upgrade it connects, but the screen stays black.

The affected phone is a custom made device, running Android 4.4.
It doesn't have a screen, so this is essential for me to continue my development.
What information do you need from me to help debug this?

Also, is it possible to get and remain on the older previous version of Vysor?

Thank you,

Richard.

**Comment by koush** [comment]
Android 4.4 is not supported.

**Comment by koush** [comment]
The old version of Vysor is in the releases page. The 4.4 support was dropped in the update, I can't recall why I did that. I think there was a good reason, but I do not remember at the moment. Probably due to publishing on Google Play or something.

**Comment by koush** [comment]
To remain on an older verison of vysor, get the old release and black hole vysornuts.clockworkmod.com in your hosts file to prevent auto updates.

**Comment by lk77** [comment]
Hello,
is there a way to use the new app with the old apk ?
