### ISSUE TITLE
Can't Login (possibly behind a proxy)

### ISSUE THREAD

**Issue by crackjack** [koush/vysor.io#542]
**Describe the bug**
I'm a PRO User, behind a corporate proxy. I used to be able to login before, but now with the update, I can't login.

**To Reproduce**
1. Go to 'Vysor Main Screen'
2. Click on 'Login'
3. Copy the Code for login from the open browser
4. Paste the Code back in the Vysor screen
5. Hit Login, nothing happens, error appears, the login popup stays open

**Expected behavior**
I should be able to login.

**Screenshots**
<img width="1664" alt="Screen Shot 2020-05-21 at 11 49 52 AM" src="https://user-images.githubusercontent.com/191368/82577654-488fce00-9b59-11ea-9a95-c83ba7fc4d5a.png">

**Desktop (please complete the following information):**
 - OS: MacOS (Catalina)
 - Vysor Version: 3.0.93

**Comment by koush** [comment]
Can you attach a generated bug report with the error please?

**Comment by koush** [comment]
You're behind a corp proxy? Does it disallow google logins?

**Comment by crackjack** [comment]
I'm sorry that I could not reply earlier. I don't know if commenting here re-opens the issue, but I would like to give you as much as information I can about this.

Where would I find the generated bug report? I'm on MacOS Catalina.

Yes, I'm behind a Corp Proxy, it allows me to login to google. I am able to login on my google account and get the generated code for vysor as well.

These are the screenshots from developer console, this shows my request and response.

<img width="1639" alt="Screen Shot 2020-06-01 at 9 23 15 AM" src="https://user-images.githubusercontent.com/191368/83414347-53fdb780-a3eb-11ea-80b7-8d52e75f03ef.png">

<img width="1633" alt="Screen Shot 2020-06-01 at 9 24 14 AM" src="https://user-images.githubusercontent.com/191368/83414360-5a8c2f00-a3eb-11ea-91a4-bd6ad2ea1357.png">
