### ISSUE TITLE
The help links in the Mac app go to Electron, not anywhere relevant to users

### ISSUE THREAD

**Issue by espertus** [koush/vysor.io#543]
When I open the Help dropdown in the Mac app (3.0.84), all of the choices take me to Electron support, not Vysor support.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Vysor Version [e.g. 3.0.84]

**Comment by koush** [comment]
Whoops, will fix.

**Comment by koush** [comment]
Also need to fix the About page to show the proper version.

**Comment by koush** [comment]
Duplicate
