### ISSUE TITLE
Mirroring is now blurry

### ISSUE THREAD

**Issue by espertus** [koush/vysor.io#545]
**Describe the bug**

When I've used Vysor in the past, the mirrored image was crisp. I am now getting blurry images for both a Pixel 2 and Moto G6.

**Screenshots**

<img width="411" alt="pixel-mirroring" src="https://user-images.githubusercontent.com/661056/82615056-3ffdbe80-9b7e-11ea-951a-44de43fe0655.png">

<img width="583" alt="moto-mirroring" src="https://user-images.githubusercontent.com/661056/82614186-12b01100-9b7c-11ea-9f8c-64f60ebda491.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Vysor Version 3.0.84

**Android 1**

 - Device: moto g6
 - OS: Android 9
 - Vysor Bug Report Link: https://gist.github.com/c239497d11aeef8ab2c7c6a5d265074f

**Android 2**

- Device: Pixel 2
- OS: Android 10

**Additional context**

The blurry screenshot was from a laptop, not an external monitor. The above settings are with the default resolution for the Retina Display. Changing the display settings to scaled does not help. Disconnecting the external monitor does not help.

**Comment by koush** [comment]
Please ensure you are logged into the app.
