### ISSUE TITLE
Please provide vysor.apk download on smartphone

### ISSUE THREAD

**Issue by ilovz73** [koush/vysor.io#546]
I can't use vysor at write protected PC.
It maked an error on connecting smart phone while 'installing vysor.apk'.
At that time my PC alarmed 'usb should not be written'.

So I connect my phone on usb writable PC to install vysor.apk automatically.
That worked before vysor updated.

But nowadays the error occurs repeatedly.
'installing vysor.apk' and 'usb should not be written'.

Please Please send me a vysor.apk or download link.
And I need to download vysor.apk whenevet 'vysor updated'.
Thank you.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/blob/master/README.md
