### ISSUE TITLE
Vysor Share Open Server should not require authentication. Should show authentication errors.

### ISSUE THREAD

**Issue by cnuppo** [koush/vysor.io#548]
Hi, when I "share all devices" with permission ALL via windows application, then copy link and paste it to chrome on another computer it cannot connect. With normal SHARE it is working, please fix
![20200522_225901](https://user-images.githubusercontent.com/65263341/82707550-f3e97180-9c84-11ea-936d-608c5cfc5a91.jpg)

https://youtu.be/nNXgecptNq8

**Comment by koush** [comment]
Can you attach a bug report please?

**Comment by cnuppo** [comment]
HI,

Here are the logs from the chrome on remote machine and from vysor windows
app where the phone is conected.

1st is from chrome where vysor stays on connecting :
https://gist.github.com/VysorLogs/c5a7012a81278b07c3841307e02bfe0f

2nd from the windowss app:
https://gist.github.com/VysorLogs/6f5ae34aa7800f46b6cfd674c305f486


Regards

**Comment by koush** [comment]
The chrome client needs to log in. Though I suppose it should work if it’s an “open” server. Is that the case?

**Comment by cnuppo** [comment]
It is open server with any user can access option selected

**Comment by cnuppo** [comment]
At the moment there is a connected and shared phone attached with no
sensitive info so you may check
https://vysor.clockworkmod.com/server#109120302788132247345

**Comment by cnuppo** [comment]
When I share it from button "SHARE" it is working, you may also check:
https://tu3ph.app.goo.gl/?ad=0&apn=com.koushikdutta.inkwire&link=https%3A%2F%2Fvysor.clockworkmod.com%2Fredirect%2F%3FregistrationId%3Dweb%253Ahttps%253A%252F%252Fpush.n1.clockworkmod.com%252Fsend%252FzqkPDwHsl-F7yUIwSbAs%26channel%3De4fe58

**Comment by koush** [comment]
Works fine for me. As I said, the Chrome side needs to be logged into Vysor to access open servers (Share All Devices). That's why it did not work. 

Plain old Share button works without login, since the link changes every time. 

Share All: Login Required in Vysor (Chrome or desktop app)
Share Button: Login is not required.

**Comment by cnuppo** [comment]
Ok! Thanks a lot for your efforts !!!

**Comment by koush** [comment]
Authentication errors are now shown.
