### ISSUE TITLE
Is there a key combination to activate android dictation from Vysor keyboard in windows 10?

### ISSUE THREAD

**Issue by lawsonr15** [koush/vysor.io#549]

**Comment by koush** [comment]
I’ll see if I can add one.

**Comment by lawsonr15** [comment]
That would make your product perfect. I am loving vysor and tether. I don't
often post reviews on it the Android store but I'd post a review about
vysor if I could use it to dictate

**Comment by koush** [comment]
Using customize Vysor, to start Assistant:

```json
      {
        "class": "fa-microphone",
        "event": "KEYCODE_VOICE_ASSIST",
        "title": "Voice Assist"
      },
```

**Comment by koush** [comment]
There is no way to start dictation programatically.

**Comment by lawsonr15** [comment]
Thank you for investigating this. I'm finding that if I run dragondictate
on the Windows PC and dictate from that into vysor. So solved but a
different way.
