### ISSUE TITLE
Spinning wheel on 1.0.5.6

### ISSUE THREAD

**Issue by anawim** [koush/vysor.io#55]
Version 1.0.5.6 update crashed the game making the wheel always spinning while the moment before with 1.0.5.5 everyting was fine. What's happening, is there a bug in it?

**Comment by alaricljs** [comment]
Same here, 1.0.5.6 update does not work for me in the same way.  GS4 + Arch Linux.

**Comment by anawim** [comment]
it seems something is missing:

chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/util.js Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/fetch.js Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/socket.js Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gidgenkbbabolejbgbpnhbimgjbffefm/screen.js Failed to load resource: net::ERR_FILE_NOT_FOUND

In the meantime how can I go back to 1.0.5.5, and in general how can I prevent Vysor from auto updating?

**Comment by koush** [comment]
https://plus.google.com/u/0/110558071969009568835/posts/1uS4nfW7xhp

**Comment by anawim** [comment]
Hey I don't give a fuck about any g+ community and post here for a reason. I'm showing you that some files are apparently missing in this distribution and this happened on 2 PC with different versions of Chrome and all the phones that used to work no longer do. If you don't know how to fix it please provide at least a way to roll back to working 1.0.5.5

**Comment by koush** [comment]
The files are not missing. That is a benign error as a result of the uglfy-js process. All the javascript is contained in ugilfy.js.

It has been this way since the first version.

**Comment by anawim** [comment]
hey @koush, provide answers here not on g+. Everything was fine, even if slow until 1.0.5.5. With 1.0.5.6 something is definetely broken and it's not fixed in 1.0.5.7 either

**Comment by alaricljs** [comment]
And my own 2 cents, I won't be joining G+ for anything.  No I don't FB either.

**Comment by koush** [comment]
I'm handling all support issues on G+. Most of the Vysor users report stuff on there. I don't have time to duplicate effort across both G+ and Github.

This issue was reported by a user on the G+ forum and confirmed by a few others, and I mentioned in that post it has been fixed.

Eventually I'll move to something like Zendesk or maybe Reddit. In any case, there's no way I'm ever going to ask normal users to create a GIthub account for support tickets.

I'm only using Github to track feature requests and other internal development issues.

**Comment by koush** [comment]
In any case, I appreciate the bug reports, and I'm trying to do this as efficiently as possible.

**Comment by koush** [comment]
Here's the thread.
https://plus.google.com/+BillDeWitt/posts/ST6xJRz8dzW
