### ISSUE TITLE
Use ctrl key combinations in Vysor? 

### ISSUE THREAD

**Issue by lawsonr15** [koush/vysor.io#550]
Before I discovered Vysor, I did most of my work on an Android tablet with a Bluetooth physical keyboard.  One of the more useful things about using a physical keyboard with an Android tablet to do work was the ability to use ctrl +key combinations to cut and past, select all, undo, Etc. Is it possible to make the visor keyboard behave the same way?

**Comment by koush** [comment]
Shift keys are supported, but not control, alt, or command keys at the moment. I can't remember why I did not enable that. I'll reinvestigate.

**Comment by lawsonr15** [comment]
I am sure there was a good reason at the time.

I'm finding that my work using my phone tethered to my computer running
Vysor less bandwidth when I'm using the phone displayed on my computer
screen and when I use the PC Internet.

I'm also finding that I can use the PC version of DragonDictate running on
the PC and dictate into Vysor. DragonDictate is more accurate and it learns
my personal vocabulary better than Android voice to text. I can get as much
work done using my phone and Vysor as I would if I was using the PC
directly.

**Comment by lawsonr15** [comment]
I have an iClever Bluetooth keyboard connected to my phone. I am typing
this with it. The standard ctrl+ commands are working in Vysor now. Ctrl a,
c, V, z, etc. I can hold shift key down and select with the arrow keys,
Attached is photo of the back of this keyboard with model number, etc. This
keyboard has setting to define different OS' it is connected to. The ctrl
+key commands all work the same when the keyboard is set for Android and
for windows.

This keyboard can pair and connect with up to 3 devices. When it is
connected to the phone, ctrl+ key combinations work. When it is connected
to the PC, these ctrl+ combinations do not work in Vysor but I can type
with the iClever keyboard in Vysor.

Curently, optimal input is iClever keyboard on top of the laptop keyboard
to type and using the laptop mouse pad and using ctrl+ keys on the iClever.

Something is going on where the iClever mouse pad stops working on the
phone after I connect to vysor. I will investigate.

**Comment by themegabyte** [comment]
Hello,

I just want to take a moment to follow up.

Am I able to use the Control A (select All) key now, or is this still pending? 

I apologize if this has been already asked.

**Comment by cwm9cwm9** [comment]
Hi.  I'm a paying user.  This is also frustrating me.  I thought the apps weren't supporting these keys until I connected by bluetooth keyboard directly.  Please offer an option to pass through everything from the keyboard.  If necessary, you could write a keyboard driver for android.
