### ISSUE TITLE
Vysor audio randomly disconnects after a while

### ISSUE THREAD

**Issue by hohkfuyuhi** [koush/vysor.io#552]
I am very satisfied with the quality of the audio mirroring, but this issue has been bugging me for about a month now.

When using Vysor to mirror audio, I noticed that the audio will **always** drop after 10-15 minutes of using it, and I have to manually reconnect the via casting.

Is this a bug, or is there something wrong with my connection?

**Comment by koush** [comment]
I'll investigate. I use it for multiple hours with no issues. What phone?

**Comment by hohkfuyuhi** [comment]
> I'll investigate. I use it for multiple hours with no issues. What phone?

Razer Phone 2 with factory settings, no rom flashes or any sort of modifications at all. The issue is present even when casting via wireless, so I think it's probably either some sort of compatibility issue, or there's something wrong with my connection.

**Comment by rlucho** [comment]
Hi, i have the same issue, OP7 Pro (Android 10) sending to Alienware 17R5, after a few minutes the audio stops, i need to re-toggle audio and so on after a few minutes again. Please help.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/582
