### ISSUE TITLE
Vysor causes Adaptive brightness to turn on automatically

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#553]
**Describe the bug**
Using Vysor causes Adaptive brightness to turn on automatically

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.
https://gist.github.com/VysorLogs/a06cb1a85a4f6d66a172eb7643e0c9fc

**To Reproduce**
1. Make sure adaptive bightness is off. Because it's awful and you hate it.
2. Connect the phone and click View.
3. Go to settings on the phone, see that adaptive brightness is on. 
4. Curse and be mad. Turn it off.

**Expected behavior**
I expect Adaptive Brightness to stay off.

**Screenshots**
Non required.

**Desktop (please complete the following information):**
OS: Windows 10 Pro

**Vysor Version:** Native 3.0.93

**Android (please complete the following information):**
Device: Pixel 3
OS: Android 10

**Android Logcat**
Need instruction if needed.

**Additional context**
On demand.

**Comment by koush** [comment]
Tracking this issue already:

https://github.com/koush/vysor.io/issues/510
