### ISSUE TITLE
Multi-touch support

### ISSUE THREAD

**Issue by geekley** [koush/vysor.io#554]
How do I do multi-touch actions with mouse, like 2 finger zoom/pinch? Is there something like in Android emulator (where you hold CTRL and can do a multi-touch to zoom)? Can I assign it to a key, like middle-click, to initiate the action, then drag to pinch?

If not, here's what I think would be the best way to implement it:

**2-finger pinch**: Middle-click where the center of action will be. Mouse is one finger. The other is mirrored around that center. Then drag with left click to pinch using both touch points at same time. Middle-click again to exit pinch mode.

**Multi-finger touch/swipe**: Middle-click on a first point, dragging to a next point. This will just determine the direction and separation between fingers. Mouse is last finger, and previous finger follows accordingly. You can middle-drag again to add another finger. Then use left-click to touch with all fingers at the same time. Middle-click to exit multi-finger mode.

Of course, the additional fingers should have a cursor on the screen too, like in android emulator.

A setting for each of the 2 actions could make them exit automatically without needing a middle-click after performing the action (releasing the left-click).

Another setting could allow the multi-touch mode to be some key, like, for example CTRL+left-click instead of middle-click.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/wiki/Multitouch

**Comment by geekley** [comment]
Oh, so I can zoom at least. OK, thanks!
