### ISSUE TITLE
Feature Request - Toolbar for Native functionality

### ISSUE THREAD

**Issue by mikegonzalez2k** [koush/vysor.io#556]
Please add a feature to include a toolbar which can control native functions of the device.
It should be able to take screenshots that are stored on the device internally.
It should be able to toggle WiFi, Bluetooth, Location, Vibration, etc.

**Comment by koush** [comment]
You can just do that on the device through Vysor.

Screenshots and recordings are already saved internally.

**Comment by mikegonzalez2k** [comment]
Maybe I'm missing something but when I press the "Take Screenshot" option it opens the Downloads folder on my PC.  I'm looking for an option where it will store the screenshot on the device.  In the default Android location /Pictures/Screenshots.  

I want a button to call Android's screenshot command (Volume Down + Power) so that writes to the device for later viewing.

**Comment by koush** [comment]
they are stored in /sdcard/vysor
