### ISSUE TITLE
Poor image quality mirroring phone with Vysor Pro with OP8 / MBP Mojave

### ISSUE THREAD

**Issue by vysoruser** [koush/vysor.io#558]
**Describe the bug**
The image quality is blurry when mirroring the phone 

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
I expected a crisp display for resolution

**Screenshots**
![Screen Shot 2020-06-02 at 12 13 41 AM](https://user-images.githubusercontent.com/66298351/83491042-f064a000-a465-11ea-9adc-5e8818c7b1f5.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Vysor Version - Vysor > About says 3.0.87, though the app screen says Vysor Pro 3.0.95

![image](https://user-images.githubusercontent.com/66298351/83491413-91535b00-a466-11ea-9efd-91ca8f0cab98.png)

**Android (please complete the following information):**
 - Device: OnePlus 8
 - OS: Oxygen OS 10.5.7.IN21AA
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/fca10e967991773d2aa65043334f2021

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**
The Mac version of Vysor doesn't seem to say "Vysor Pro" at the top as I saw in some of the forum screenshots and does not have any setting for screen resolution. When I retrieved the license it did pop up and ask if I wanted a higher resolution and I said yes. That did improve it but as you can see it's still fuzzy.

**Comment by koush** [comment]
Can you go into Vysor Settings and ensure it is set to High?

**Comment by koush** [comment]
There's bitrate and resolution options, you can set those to 8mbit/75%.

**Comment by vysoruser** [comment]
Hi Koush, thanks-

Where would I find those settings? I'm on a mac and this is what I see:

![image](https://user-images.githubusercontent.com/66298351/83561377-94813200-a4cc-11ea-9163-d71dbfe80fc6.png)

Going into "Customize" I see: 
{
  "dense": true,
  "themeColor": "#3949AB",
  "accentColor": "#FF9800",
  "mousedown": {
    "1": "KEYCODE_HOME",
    "2": "KEYCODE_BACK"
  },
  "keydown": {
    "ArrowDown": "KEYCODE_DPAD_DOWN",
    "ArrowLeft": "KEYCODE_DPAD_LEFT",
    "ArrowRight": "KEYCODE_DPAD_RIGHT",
    "ArrowUp": "KEYCODE_DPAD_UP",
    "Backspace": "KEYCODE_DEL",
    "Delete": "KEYCODE_FORWARD_DEL",
    "Enter": "KEYCODE_ENTER",
    "Escape": "KEYCODE_BACK",
    "F1": "KEYCODE_MENU",
    "F2": "VYSOR_SHOW_TITLE_BAR",
    "F3": "VYSOR_ENTER_FULLSCREEN",
    "F4": "VYSOR_EXIT_FULLSCREEN",
    "Home": "KEYCODE_HOME",
    "Tab": "KEYCODE_TAB"
  },
  "navigationBar": {
    "buttons": [
      {
        "class": "fa-chevron-left",
        "event": "KEYCODE_BACK",
        "title": "Back"
      },
      {
        "class": "far fa-circle",
        "event": "KEYCODE_HOME",
        "title": "Home"
      },
      {
        "class": "fa-bars",
        "event": "KEYCODE_APP_SWITCH",
        "title": "Recent Tasks"
      }
    ]
  },
  "titleBar": {
    "buttonGroups": [
      {
        "buttons": [
          {
            "class": "fa-video",
            "stopClass": "fa-video-slash fa-spin",
            "stopColor": "red",
            "title": "Record Screen",
            "event": "VYSOR_RECORD_SCREEN"
          },
          {
            "class": "fa-headphones",
            "stopColor": "green",
            "title": "Toggle Audio",
            "event": "VYSOR_TOGGLE_AUDIO"
          },
          {
            "class": "fa-wifi",
            "title": "Wireless Mode",
            "event": "VYSOR_WIRELESS_MODE"
          }
        ]
      },
      {
        "menuClass": "fa-cog",
        "buttons": [
          {
            "class": "fa-camera",
            "title": "Take Screenshot",
            "event": "VYSOR_SCREENSHOT"
          },
          {
            "class": "fa-redo",
            "title": "Rotate Screen",
            "event": "VYSOR_ROTATE_SCREEN"
          },
          {
            "class": "fa-expand",
            "title": "Full Screen",
            "event": "VYSOR_ENTER_FULLSCREEN"
          },
          {
            "class": "fa-power-off",
            "title": "Screen On/Off",
            "event": "KEYCODE_POWER"
          },
          {
            "class": "fa-cog",
            "title": "Settings",
            "event": "VYSOR_OPEN_DEVICE_SETTINGS"
          }
        ]
      }
    ]
  },
  "devices": {
    "example-device-serial": {
      "themeColor": "#AA00FF",
      "keydown": {
        "F3": "KEYCODE_BACK"
      },
      "navigationBar": {
        "buttons": [
          {
            "class": "fa-circle",
            "event": "KEYCODE_HOME",
            "title": "Home"
          }
        ]
      }
    }
  }
}

**Comment by koush** [comment]
click the gear.
![Pixel_4](https://user-images.githubusercontent.com/73924/83564266-4884bc00-a4d1-11ea-9c8c-f21cf05ea987.png)


Then click settings.

**Comment by vysoruser** [comment]
Got it thanks- it was already set at that setting:

![image](https://user-images.githubusercontent.com/66298351/83570199-7cb0aa80-a4da-11ea-8a9c-8c0ce07184a2.png)

**Comment by koush** [comment]
Can you share a screenshot (ie, using the windows screenshot tool, and not the vysor screenshot tool). The vysor screenshot tool takes a pixel perfect screenshot, and not what is mirrored (which is low quality as you indicate).

**Comment by vysoruser** [comment]
Hi yes the snapshots are all taken using the Mac screenshot tool

**Comment by vysoruser** [comment]
I did actually use a Mac screenshot grab to get that. Was just hoping to get it more crisp than that. Also sorry new to Vysor, is there a way to mirror audio in the Mac s/w version? I clicked the "headphones" but that didn't seem to make any difference- I'd like the phone audio to play out through the computer system sound

**Comment by vysoruser** [comment]
Sorry just checking again- is there a way for me to route sound thru the mirror on Mac OS from android phone?

**Comment by koush** [comment]
That screenshot looks fairly crisp considering it is a video still. It won't get much better, and performance varies by device. Please open a separate bug for audio.

**Comment by vysoruser** [comment]
ok re: resolution thx will close
