### ISSUE TITLE
Black screen but move and ss normal

### ISSUE THREAD

**Issue by notertre** [koush/vysor.io#559]
![ss](https://user-images.githubusercontent.com/66309321/83513845-ce553700-a4d2-11ea-8c51-5d10006fe1ab.png)
Good day
As you can see it is black screen. When i make screenshot it is normal and i can normally drag with mouse something on phone screen .

**Comment by koush** [comment]
This is an old deprecated version of vysor as noted in your screenshot.

**Comment by koush** [comment]
Download hte new one from vysor.io/download
