### ISSUE TITLE
vysor&pixel4-failure ?

### ISSUE THREAD

**Issue by phantomr1982** [koush/vysor.io#560]
i've tried to test a pixel 4 on vysor free however it failed to connect after pressing view when authorised via touchscreen prompts...also gave me an c++ error see image.

https://gist.github.com/a094b462cdb7cd312d84b7e50e8b3a0d
https://gist.github.com/VysorLogs/feb7c17442830a85ec7d689d310c3da6/revisions

i think i submitted this right if not please advise

**Desktop
 - OS: [Windows 7]
 - Vysor Version [3.0.9.5]

**Android
 - Device: [Pixel 4]
 - OS: [Android 10]
 
![pixel4-is](https://user-images.githubusercontent.com/65123490/83782413-afe46c80-a687-11ea-8bee-b6efd2325b3a.png)
![pixel4-vysor3094](https://user-images.githubusercontent.com/65123490/83782418-b1159980-a687-11ea-9bbf-84921837c250.png)

kind regards 
phantomr1982

**Comment by koush** [comment]
Can you change the decoder to WebAssembly in Vysor Settings for that device?

**Comment by UsmanAlibutt1** [comment]
hi, how did you fixed it ? please help me to fix that issue :) thanks
