### ISSUE TITLE
I can't connect to the billing site, I want to cancel my subscription. 

### ISSUE THREAD

**Issue by justine-sudo** [koush/vysor.io#561]
I tried to go to https://billing.clockworkmod.com/ but it won't load how can i cancel my subscription?

**Comment by koush** [comment]
Works here. What Browser? are you behind a corp firewall or vpn?

**Comment by justine-sudo** [comment]
no how can i cancel my subscription now it won't letting me access the site?

**Comment by koush** [comment]
screenshot of the site when you try to open it? what is your email?
