### ISSUE TITLE
Can't rotate screen when using camera

### ISSUE THREAD

**Issue by wangkkyy** [koush/vysor.io#562]
I'm using a 3.0.87 Vysor Pro Version between a Macbook and a Oneplus 7T Pro Andoird Phone.
The screen rotates when I open an app which rotates; but I want to rotate screen on Mac when I'm using the phone camera. I clicked 'rotate screen' on Mac but it was not working.

I'm not sure is it an issue or is it just me.

**Comment by koush** [comment]
Orientation is locked in the camera app.
