### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by alex5857** [koush/vysor.io#563]
Hello! 

I just purchased the pro version of your software today to mirror my audio from my tablet. I have downloaded the proper drivers and installed the app on both my computer and tablet as well as google home.

When I toggle the headphones to cast the audio (I do see the Vysor Audio Input) I hear the chime work on my PC sound, but the cast menu never goes away and it stays saying connected until it eventually times out and disconnects. If I click anywhere off the menu it also says casting screen to Vysor has ended and disconnects. 

I am on an SM-T720 android tablet and windows 10 with the latest patch.

**Comment by alex5857** [comment]
To add - this works perfect on my phone. My tablet is on Android 9.

**Comment by Braste** [comment]
Audio does not work on my Samsung Galaxy S8 with Android 9, too. I see the Vysor audio input but the connection attempt times out.

**Comment by alex5857** [comment]
Any support coming? I would love to use this or get a refund, but as it stands now this is useless to me.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/582
