### ISSUE TITLE
Not able to use the wireless option on Vysor Pro from Android to Mac

### ISSUE THREAD

**Issue by notatechy** [koush/vysor.io#565]
Tried using the wireless feature and it shows this at first-

![Screen Shot 2020-06-09 at 2 21 02 PM](https://user-images.githubusercontent.com/66669666/84127634-25bc4f80-aa5d-11ea-9a72-e9734808be4c.png)

But when I disconnect the phone from the USB cable this shows instead-

![Screen Shot 2020-06-09 at 2 21 20 PM](https://user-images.githubusercontent.com/66669666/84127608-20f79b80-aa5d-11ea-8618-70d8b31990c8.png)

What should I do?

**Comment by RandomAnimeGamer** [comment]
I have the same problem with Vysor on Windows. It will connect to my Android device at 192.168.1.13, but when I disconnect the USB cable it immediately disconnects mirroring.

**Comment by bagintz** [comment]
Mine was working for awhile and then it also stopped, not sure what changed.

**Comment by bagintz** [comment]
@RandomAnimeGamer @notatechy  for what it is worth it appeared my usb settings on my phone moved away from PTP, once I switched back to that it works again.

**Comment by koush** [comment]
use the issue template.
