### ISSUE TITLE
Audio and other things

### ISSUE THREAD

**Issue by snoodler** [koush/vysor.io#566]
I am working on a new project and got vysor since I work on mac.

A few issues though:

I noticed a video gets recorded inside my android and would be nice to have an option that I only want to save the video in my mac. Don't want to fill up my phone's memory.

Currently the only way to record the audio is by starting an audio recording from quicktime and then I had to buy a 3.5 audio jack splitter which goes to a pair of headphones and to a USB audio input. Would be nice to have the audio recorded inside the video. It would save me a lot of time.

I don't do twitter and trying to get support is impossible in your webpage. That's why I am here.

Keep up the good work !

**Comment by koush** [comment]
I'll see about deleting the video when it completes.

Already an open feature request for recording audio streams. https://github.com/koush/vysor.io/issues/533

**Comment by koush** [comment]
Please open separate issues if you have more.
