### ISSUE TITLE
Unable to access any shared devices

### ISSUE THREAD

**Issue by ritdaw** [koush/vysor.io#567]
**Describe the bug**
I'm trying to access all shared devices between two different PC's. I'm unable to see any of the devices on either PC. Error: Connection to Vysor Share Server failed, waiting for RTC connection. I believe this is likely a connectivity issue of some description but done all the troubleshooting I can think of. 

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/8b3fc35fae69cce3d3ea56e5dd491cc6#file-ce9075bf-9cd7-4199-844c-b61c822ebe66-txt

**To Reproduce**
Login to account on both computers, visit https://app.vysor.io and wait for devices to be listed, eventually times out. Errors are not displayed with the Windows app, but devices are still not in the list. 

**Expected behaviour**
Expect to see list of available devices to view.

**Screenshots**
![image](https://user-images.githubusercontent.com/2089152/84489902-4de4c200-ac9a-11ea-8633-6f7ce4eb08e2.png)
![image](https://user-images.githubusercontent.com/2089152/84490645-5be71280-ac9b-11ea-9cab-c6e1e820a003.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version: 3.0.95

**Android (please complete the following information):**
 - Device: Any
 - OS: Any
 - Vysor Bug Report Link:

**Comment by koush** [comment]
Which browser? Chrome I presume?

**Comment by ritdaw** [comment]
> Which browser? Chrome I presume?

Yep in Chrome.

**Comment by koush** [comment]
Thanks. Do you have a log from the server side that is sharing the device?

**Comment by ritdaw** [comment]
Must admit I haven't tried it since initially reporting, so will have to try setting up again. Will give it a go Monday and provide any extra info I can.

**Comment by koush** [comment]
Resolved in 3.1.3. Please confirm.
