### ISSUE TITLE
Vysor audio stops working after a few minutes

### ISSUE THREAD

**Issue by rlucho** [koush/vysor.io#568]
Everything works perfectly but the audio i send from my phone to my laptop, it will work a few minutes then i just hear nothing from phone, so i need to toggle off and toggle on the audio to make it work again, really annoying.

**Desktop
 - OS: Windows 10 Pro
 - Vysor Pro Version 3.0.95

**Android
 - Device: OnePlus 7 Pro (GM1913)
 - OS: Android 10
 - Using usb cable

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/582

**Comment by rlucho** [comment]
Fixed?
