### ISSUE TITLE
Videos not saving

### ISSUE THREAD

**Issue by connorl-f** [koush/vysor.io#569]
When I am recording screen on windows or Mac the video is not saved.

id 
email 
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.2.5","chrome":"80.0.3987.165"}
package.json 3.0.95
runtime package.json 3.0.87
os darwin
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in
id 115296038077784914950
email connor.nathan.lee@gmail.com
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not cached
id 115296038077784914950
email connor.nathan.lee@gmail.com
enterprise server not licensed
enterprise cache not licensed
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not cached
id 115296038077784914950
email connor.nathan.lee@gmail.com
clockwork server not licensed
chromeStore server check failed Error: Use the Retrieve Chrome Web Store License button to log in with the Chrome Web Store.
enterprise cache not licensed
clockwork cache not licensed
chromeStore cached check failed Error: not cached
id 115296038077784914950
email connor.nathan.lee@gmail.com
enterprise cache not licensed
clockwork cache not licensed
chromeStore cached check failed Error: not cached
id 115296038077784914950
email connor.nathan.lee@gmail.com
enterprise server not licensed
enterprise cache not licensed
clockwork cache not licensed
chromeStore cached check failed Error: not cached
id 115296038077784914950
email connor.nathan.lee@gmail.com
clockwork server licensed
enterprise cache not licensed
clockwork cache licensed

**To Reproduce**
1. View Android device through vysor
2. Click on Record Screen
3. Icon become red and starts turning
4. Click Icon to stop
5. No video is saved

**Expected behavior**
A video should be saved in download as manual and video suggest

**Screenshots**
I have a video of the video not saving but I am unable to attach it

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4
 - Vysor Version 3.0.95 Pro

**Android (please complete the following information):**
 - Device: Allwinner a33
 - OS: KitKat 4.4.2

**Android Logcat**
I/MPEG4Writer( 6259): limits: 2147483647/0 bytes/us, bit rate: -1 bps and the estimated moov size 3072 bytes
E/MPEG4Writer( 6259): The number of recorded samples is 0
W/MPEG4Writer( 6259): 0-duration samples found: 1
W/MPEG4Writer( 6259): 0-duration samples found: 1
I/MPEG4Writer( 6259): Received total/0-length (0/0) buffers and encoded 0 frames. - video
D/MPEG4Writer( 6259): Stopping Video track
D/MPEG4Writer( 6259): Stopping Video track source
D/MPEG4Writer( 6259): Video track stopped
D/MPEG4Writer( 6259): Stopping writer thread
D/MPEG4Writer( 6259): 0 chunks are written in the last batch
D/MPEG4Writer( 6259): Writer thread stopped
E/VysorMain( 6259): input websocket
E/VysorMain( 6259): java.lang.IllegalStateException: Failed to stop the muxer
E/VysorMain( 6259): 	at android.media.MediaMuxer.nativeStop(Native Method)
E/VysorMain( 6259): 	at android.media.MediaMuxer.stop(MediaMuxer.java:226)
E/VysorMain( 6259): 	at com.koushikdutta.vysor.Mp4Writer.stop(Mp4Writer.java:2)
E/VysorMain( 6259): 	at com.koushikdutta.vysor.Main.stopRecording(Main.java:3)
E/VysorMain( 6259): 	at com.koushikdutta.vysor.Main$2.onStringAvailable(Main.java:144)
E/VysorMain( 6259): 	at com.koushikdutta.vysor.Main$19$1.onStringAvailable(Main.java:1)
E/VysorMain( 6259): 	at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:6)
E/VysorMain( 6259): 	at com.koushikdutta.async.Util.emitAllData(Util.java:2)
E/VysorMain( 6259): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:12)
E/VysorMain( 6259): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:26)
E/VysorMain( 6259): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:28)
E/VysorMain( 6259): 	at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:1)
E/VysorMain( 6259): 	at com.koushikdutta.async.AsyncServer$8.run(AsyncServer.java:2)

**Comment by connorl-f** [comment]
The Recording works fine on Samsung Galaxy s8 and opens a dialog to select a save location

**Comment by koush** [comment]
Android 4.4.2 is not supported.
