### ISSUE TITLE
Feature request: disable automatic update

### ISSUE THREAD

**Issue by anawim** [koush/vysor.io#57]
you have to provide an option to skip automatic update of buggy releases or a way to roll back to previous working version at least. Vysor is still broken after almost a week and this lack of support is not acceptable even for a beta program.

**Comment by koush** [comment]
Please send me your receipt for Vysor, and I'd be happy to give you a refund.

**Comment by koush** [comment]
Also, I'm sure you could use Google to figure out how to disable Chrome extension auto updating...

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/55
