### ISSUE TITLE
Mirror Audio Not Working Pocophone F1

### ISSUE THREAD

**Issue by v4nj03l** [koush/vysor.io#571]
Help me

Mirror audio not working after enable button on application

Always show " wireless display " in android pocophone,show connect,but it didnt  connect and suddenly disappeared 
![Screenshot_2020-06-20-22-47-53-019_com android settings](https://user-images.githubusercontent.com/67190994/85204702-67dc6f80-b340-11ea-9cf5-f8bfa8b8b700.jpg)

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/582
