### ISSUE TITLE
Cannot cancel subscription

### ISSUE THREAD

**Issue by ashtonpeck** [koush/vysor.io#576]
Hi koush,

I'm trying to cancel the subscription but when I log in there is no subscription found. I have checked my Google subscriptions and it's not there either. I can't find an invoice or anything in my emails. We are still being billed for this service and have not used it in over a year, please help us cancel this. It is billed to Helen F Bell. See attachment.
![Screen Shot 2020-06-24 at 11 02 50 am](https://user-images.githubusercontent.com/67577700/86067107-4f462500-bab7-11ea-816a-6e744da2a7bd.png)

**Comment by ashtonpeck** [comment]
![Screen Shot 2020-06-24 at 11 02 50 am](https://user-images.githubusercontent.com/67577700/86066424-71d73e80-bab5-11ea-881c-5ccd2cb7b50e.png)

**Comment by koush** [comment]
Not finding anything. I need more information than this. Email and zip code.

**Comment by ashtonpeck** [comment]
It's billed to Training Snippets, probably ashton@trainingsnippets.com.au or helen@trainingsnippets.com.au. Zip code is 3205.

**Comment by ashtonpeck** [comment]
> Not finding anything. I need more information than this. Email and zip code.

It's billed to Training Snippets, probably ashton@trainingsnippets.com.au or helen@trainingsnippets.com.au. Zip code is 3205.

**Comment by koush** [comment]
I think this is a Google Subscription. It will be called "Annual Subscription or something. A log from the Vysor app itself would help.

**Comment by ashtonpeck** [comment]
> I think this is a Google Subscription. It will be called "Annual Subscription or something. A log from the Vysor app itself would help.

It doesn't show up in any of my Google accounts or on the chrome store. Wouldn't it say Google in the credit card statement?

Vysor was installed on an old machine and I've reinstalled and tried to retrieve the license but it doesn't work either.

Is there no way to cancel this subscription from your end?  Can't billing find anything in your records matching the credit card details? It was likely purchased in September 2018. I would greatly appreciate your help with this.

**Comment by koush** [comment]
I'm not finding anything, that's why I needed a log. THose names and emails are not subscribed users or cards.

**Comment by ashtonpeck** [comment]
> I'm not finding anything, that's why I needed a log. THose names and emails are not subscribed users or cards.

We unfortunately don't have access to the log - I know you can look up a bank statement and see a direct debit from Training Snippets and cancel it from there.

As Training Snippets, we used your service IN GOOD FAITH so you should be able to help us - it appears to us that you are conducting your business fraudulently.  Interestingly there are other comments on social media about your company doing this sort of thing.

Please let me know what you are able to do for us otherwise you will give us no option other than to report you.

I look forward to hearing from you.

Regards
Ash
