### ISSUE TITLE
Auto Rotate, Adaptive brightness turns on automatically

### ISSUE THREAD

**Issue by zeeshan-atdrive** [koush/vysor.io#577]
Auto Rotate and Adaptive brightness turns on automatically every time you connect the phone to Vysor.

**Comment by LafinJack** [comment]
This happens to me too, though I use Lux so I probably don't notice the AB setting. The rotation thing has been happening so long I even created a Tasker task to force rotation to portrait when unplugging from a USB source.

**Comment by koush** [comment]
Am aware, will see what I can do. https://github.com/koush/vysor.io/issues/510
