### ISSUE TITLE
Audio recording only available on WiFi could probably work if Ethernet is connected

### ISSUE THREAD

**Issue by fr500** [koush/vysor.io#578]
**Describe the bug**
Seems the audio mirroring option checks for wifi connectivity, but shouldn't it just work with ethernet? I understand it not working with USB mirrorring, but if ethernet is connected it should work.

I'm already connecting to the device over network instead of ADB

**To Reproduce**
1. connect to device over network
2. click on audio mirroring
3. 

![imagen](https://user-images.githubusercontent.com/1721040/86299605-53ad3380-bbc6-11ea-8e02-32e7edbf04a1.png)

**Comment by koush** [comment]
This is true. Let me see if I can fix this.

**Comment by koush** [comment]
Ok will be fixed in next release.

**Comment by fr500** [comment]
Awesome, I'll test ASAP

**Comment by koush** [comment]
It's not rolled out yet.

**Comment by koush** [comment]
Will close this bug when it's released.
