### ISSUE TITLE
Waiting for decoder on Linux

### ISSUE THREAD

**Issue by sdc695** [koush/vysor.io#581]
I thought this would be easy.  I got Vysor working on my home computer and confirmed its operation as an independent application by unplugging my internet connection.  So for so good.  I then take THE SAME DISK and plug it into a machine here at work (which is where I would like to use Vysor), and start things as before, and all I get is the black screen "Waiting for decoder".

This is using the SAME disk with all its software, the only difference being the environment (a repurposed Dell machine vs. an older HP machine).  The Dell machine has an Nvidia video card if that makes a difference, and uses a two monitor setup, whereas the HP machine (less capable) has the standard on-board video.

What gives?

In both cases, I use the "Vysor-linux-3.0.84.AppImage" downloaded from github.  This has me baffled!

Thanks.

**Comment by koush** [comment]
use the issue template.

**Comment by tunjibiyi** [comment]
I have the same issue here, please how can It be resolved?

**Comment by MihaJjDa** [comment]
i have this issue too, i'll be glad to have its solution

**Comment by egaumit** [comment]
Hi All,

I am using Ubuntu and got an error to upgrade the Vysor. I upgraded Vysor but when I am trying to access the Android device it shows me 'Waiting for Decoder'. It don't move further.

Kindly help to fix this.
Also I found that there is not much information about this issue on internet, your help is needed to fix it

**Comment by koush** [comment]
You need to use the issue template, the bug report provided here was not filled out properly.
