### ISSUE TITLE
Audio Mirroring refactor

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#582]
This is a catch all to switch Audio Mirroring to Android API level 29 audio capture. The Chromecast capture method is simply too unreliable.

**Comment by rlucho** [comment]
Hi! Thanks for the reply, but how to do that? Any guide? Sorry but I'm not an expert. Thanks in advance!

**Comment by koush** [comment]
Implemented.
![Pixel_4](https://user-images.githubusercontent.com/73924/90101591-da8c1a80-dcf3-11ea-9817-a6cbbd789200.png)

**Comment by koush** [comment]
By default, Android 10 audio will be used for newly connected devices. Existing users with existing device settings will need to go into the settings and check this box.

**Comment by FerLuisxd** [comment]
This but on the free version maybe? o.o
