### ISSUE TITLE
Audio not working with Realme X2 Pro, can't find screencast.

### ISSUE THREAD

**Issue by neverender24** [koush/vysor.io#583]
**Android (please complete the following information):**
 - Device: Realme x2 pro
 - OS: android 10, realme ui

Can't mirror audio, cant find screen cast

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/582

**Comment by koush** [comment]
See here: https://github.com/koush/vysor.io/issues/582

Use the Android 10 audio checkbox available in 3.0.97.
