### ISSUE TITLE
Mirror stream ends when switching to MTP/file transfer mode.

### ISSUE THREAD

**Issue by LafinJack** [koush/vysor.io#584]
**Describe the bug**
After upgrading Windows 10 build 1909 to Windows 10 build 2004 I am not able to mirror my Pixel 2 when the USB mode is in MTP/file transfer mode. I have MTP/file transfer turned on as default USB mode in the developer options, so it always switched after I log in. This includes being able to use the mirror the lock screen and enter my pattern to log in, but once logged in get a "Mirroring Disconnected / Error: stream ended during read for minimum 4 bytes". Clicking 'Retry' gives the error "Error Connecting To Android Device / Error: Device not found (serial: [device serial number]"Manually switching to any other USB mode (tethering, MIDI, PTP, no data transfer/charge only) lets mirroring work fine.

**Attach a Vysor Bug Report Log**
https://gist.github.com/c314df3da6c4a4d717fba6f96b286b09

**To Reproduce**
1. Go to: Plugged in device on host computer.
2. Click on: Change USB mode to MTP/file transfer
3. Error appears

**Expected behavior**
I have my device set in developer settings to always switch to MTP/file transfer mode. When I unlock my phone the mirrored window momentarily loses connection (the "4 byes" error) then quickly reconnects and is functions as normal.

**Screenshots**
https://i.ibb.co/Zd3xQ2p/Vysor-mirror-error.png

**Desktop (please complete the following information):**
 - Windows 10 Version 2004 Build 19041.284
 - Vysor Pro Version 3.0.95

**Android (please complete the following information):**
 - Device: Pixel 2 Walleye
 - OS: Android 10 build QQ3A.200605.001
 - Vysor Bug Report Link: https://gist.github.com/c314df3da6c4a4d717fba6f96b286b09

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.
NA

**Additional context**
Issue only began after upgrade to Windows 10 version 2004. Have tried resetting Vysor settings, and uninstalling/reinstalling Universal USB Driver package.

**Comment by koush** [comment]
Try using the official Google drivers. This is a driver issue, not a Vysor issue.

**Comment by LafinJack** [comment]
I tried uninstalling the original USB Drivers and installed the latest Google drivers, but no change in behavior. Also notable is that no matter how high I set the graphics settings, the Google drivers showed extremely poorly.

https://i.ibb.co/HdVqZ1V/vysor2.png
https://i.ibb.co/60dGqjt/vysor3.png

**Comment by LafinJack** [comment]
Please disregard the quality problem, I had reset Vysor again and for got to log in.

**Comment by LafinJack** [comment]
Issue continues after uninstalling Clockwork USB drivers and installing Google USB drivers. Any ideas?
