### ISSUE TITLE
Unable to login into linux's desktop application

### ISSUE THREAD

**Issue by patmiche84** [koush/vysor.io#587]
**Describe the bug**
I am not able to login into the linux desktop application in order to retrieve the pro license (purchased in may)

**Attach a Vysor Bug Report Log**

https://gist.github.com/f13fa2cff4a608820c969552fe5705d2

**To Reproduce**
1. Launch the desktop application
2. Click on 'LOGIN'
3. the application tries to open an URL in the default browser.
4. See error in the browser: 
"400. That’s an error.
The server cannot process the request because it is malformed. It should not be retried. That’s all we know."

**Expected behavior**
A google page to login using my google account and getting an "authentication token" to copy into the proper field in Vysor.io app

**Desktop (please complete the following information):**
 - OS: linux Ubuntu 18.04
 - Vysor Version 3.0.84

**Comment by Luis-Medina** [comment]
I'm facing a similar issue:
<img width="799" alt="Screen Shot 2020-07-23 at 5 11 40 PM" src="https://user-images.githubusercontent.com/8743506/88342777-1263fb80-cd0e-11ea-98ef-00f3a7173e28.png">

Log: https://gist.github.com/VysorLogs/8911b9d152f0e40196b68284dd3f0778

**Comment by patmiche84** [comment]
Any news on this?
WHen will I be able to use my pro license?

**Comment by koush** [comment]
@patmiche84 Are you behind a firewall or vpn something?

**Comment by patmiche84** [comment]
no, firewall nor vpn.

**Comment by koush** [comment]
What is your default browser?

**Comment by patmiche84** [comment]
I tried on several, but mainly I use Brave, which is a fork of Google Chrome.
I tried with google chrome, firefox and opera

**Comment by koush** [comment]
Can you generate another bug report, after you attempt to log in? Leave the login windows and such open while collecting the report.

**Comment by patmiche84** [comment]
The bug report:
https://gist.github.com/3dcd8b5ca73d6cd5d24cb80ff717ae59
Hope it will help.
Patrice

**Comment by koush** [comment]
> Can you generate another bug report, after you attempt to log in? Leave the login windows and such open while collecting the report.

There is no login attempt in that bug report.

**Comment by patmiche84** [comment]
The procedure I followed:
1) open Vysor
2) try to login causing the error in the web browser
3) generate the report by clicking on "bug report"

Should I do somehing differently?

**Comment by koush** [comment]
Huh, that is correct. Odd that I'm not seeing that in the log.
And you said you tried setting your browser default to Chrome proper, before attempting login? I want to make sure that the link is being properly opened. Because your error indicates that the link is somehow being malformed.

I have tested with 18.04 + Chrome.

I will push an update that will include the link being opened in the "code entry" dialog, that you can copy/paste into a browser. Maybe the launching of the browser link itself is being intercepted and mangled somehow by your OS.

**Comment by patmiche84** [comment]
When I tried with other browsers, I copied the link into th browser.

I tried again by changing the defaut browser to chrome ... and it worked.

So setting google chrome as defaut browser solved the issue.
I will close the issue.

Sorry to have bother you with that and thank you for your help.
Patrice
