### ISSUE TITLE
AUDIO CANNOT BE MIRRORED

### ISSUE THREAD

**Issue by Karolina011096** [koush/vysor.io#588]
Hi. I bought the Pro version specifically for the extra features and now i feel it was not worth the money as it is not fully functioning, however the mirroring quality is great and what i expected. Lack of audio lets this down massively as I want to stream games WITH audio (duh).

I have a stream set up in OBS, initially having a black screen when adding a capture source which i have resolved, showing me the phone screen now.

The audio however goes through JUST the phone, and if you are to click cast to Vysor Audio Output it will simply disconnect after a few seconds. I need this audio to go through the PC into the stream, but right now it will only be picked up by the built in microphone sounding like nails on a chalkboard as somebody described.

Now, I have seen this issue in other threads however it seems to be taking a long time to fix or no solutions offered, and to advertise the program having this feature and it doesnt, is dissatisfactory. I have sat on this issue for a couple of hours now and the frustration is growing, especially for a PAID version of a program. 

I am running the latest version 3.0.95, everything else is up to date. We need a fix for this ASAP or i will be waiting for my refund.

-unhappy customer.

**Comment by ozgp** [comment]
I tell you now that Audio Mirroring does work but as Koush has repeatedly posted on some devices depending on the manufacturer chromecast casting (the API he is using) just does not work or does not work reliability.  Since you have not posted your log but instead just demanded a fix how did you intend Koush to help you?

**Comment by Karolina011096** [comment]
I dont need to post my log when clearly this is an unsolved issue which most users are still experiencing. Koush did mention a beta version with a possible fix to another user reporting the no internal audio. I dont think you read my message properly either and instead youre on for the attack so please drop that attitude when I'm simply looking for a fix so I can get on with what I want to do. Thanks.

**Comment by ozgp** [comment]
Clearly most users do not include me then..  As I said post your logs if you want Koush to help otherwise goodluck..

**Comment by koush** [comment]
See here: https://github.com/koush/vysor.io/issues/582

Use the Android 10 audio checkbox available in 3.0.97.
