### ISSUE TITLE
Vysor is showing couldn't load plugin

### ISSUE THREAD

**Issue by smohanty2020** [koush/vysor.io#590]
Trying vysor on centos 7 able to open Vysor application ( following link :https://github.com/koush/vysor.io/issues/242) but unable to open mirror image of the phone its showing unable to load plugin.

Can you please help me in getting this working.

![Capture](https://user-images.githubusercontent.com/68863318/88562860-d81c9600-d04e-11ea-82d7-9f12788e68b5.JPG)

**Comment by koush** [comment]
Please update your Vysor version. https://vysor.io
