### ISSUE TITLE
REQUEST: Allow the Vysor window to accept / receive all initial mouse-down events

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#591]
**Describe the bug**
Not so much a bug, but a small feature request. On macOS, an ``NSView`` can be overridden to accept the first mouse-down click event (by overriding ``acceptsFirstMouse``). This will remove the need to click twice to interact with the Android device - currently one click is required to make Vysor the ``keyWindow``, before you can interact with any of the elements on the screen-mirrored Android.

**To Reproduce**
1. Start a session with a device on macOS
2. Focus some other app that's running, or just click on your desktop wallpaper to focus Finder.
3. Try to click a visible button or element that you can see on the Android device, through Vysor.
4. The first click will only focus Vysor's window. You will need to click again to trigger the mouse ``NSEvent` on the intended target within the Vysor session.

**Expected behavior**
Step 3 and 4 above are combined. This also could be extended to allow (through a preference) whether you want to make the Vysor window the ``keyWindow`` at all, allowing you to interact with the Android device without losing focus in your current front-most application. This could be useful if you are say, writing out text in a document, while navigating through the Android app. A click of the Vysor titlebar could be used to force the ``keyWindow``, for those that would not want this "background" focus.

A side-note: ``NSEventMaskScrollWheel`` events are already being passed through to Vysor's session even if it's not the ``keyWindow``, as are ``NSEventMaskRightMouseDown `` events. Mouse-up/mouse-down events don't seem to be. 

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Vysor Version 3.0.95

**Android (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: 8.1.0

**Comment by koush** [comment]
Interesting. I'll see if Electron supports this.

**Comment by koush** [comment]
https://github.com/electron/electron/issues/12631

**Comment by crouchingtiger** [comment]
I don't have a Windows machine or VM atm to test the Vysor window focus behaviour, but is that what you're seeing eg. can you click straight through to elements and enable initial window focus on the first mouse click? From memory, all VNC/RD software I've used on macOS will return YES for ``acceptsFirstMouse`` on the view that contains the remote session (Parallels / VMWare Fusion). Buttons and UI (``NSControl``) elements always have this enabled by default and in the Vysor example, that means I can use the Vysor toolbar above the session window just fine, but not the elements directly visible on the Android device.

**Comment by koush** [comment]
Yes, that's the idea. Will need to push a release for this after I verify it works.

**Comment by koush** [comment]
Resolved in 3.1.3. Please confirm.

**Comment by crouchingtiger** [comment]
Excellent, can confirm it works as expected! Thank you! 🙏
