### ISSUE TITLE
Unable to retrieve Chrome Store license

### ISSUE THREAD

**Issue by abrueckn** [koush/vysor.io#592]
Hello,

I was rebilled for an annual chrome store license in December. I have not used the service since then, but need it now and I cannot get the app to recognize my Chrome store license. I have tried both the webapp version and the latest desktop version, and yes I am using the correct Google account.

I tried to use your support page but it was unhelpful and provided no email address or other place to contact.

**Comment by koush** [comment]
Please follow the instructions in the issue template.

**Comment by abrueckn** [comment]
I have. It was extremely unhelpful and offered no way to contact support, which is why I am posting here. I cannot retrieve the license that I paid for, rendering the app useless to me. Other than posting here or paying for a new license, what can I do? I am very dissatisfied at the moment.

**Comment by koush** [comment]
You need to click new issue and use the issue template, which includes steps for getting a bug report.

**Comment by abrueckn** [comment]
Ah, bug reporting from the app itself? I think I've figured it out: https://gist.github.com/VysorLogs/686fee7fe95efbc1a30fef5500f7546f

Thank you

**Comment by koush** [comment]
Please click Upgrade Pro, then click Retrieve License from **Chrome Store.**

**Comment by abrueckn** [comment]
That is exactly what I have been doing, but it doesn't work. It says "No License Found".

This is the whole reason I have been posting here looking for a solution: all of the obvious approaches have failed.
