### ISSUE TITLE
FEATURE REQUEST - Screenshot icon sits on top next to record button

### ISSUE THREAD

**Issue by fpenguin** [koush/vysor.io#596]
Take Screenshot is much more frequently used than 'record screen' in my case. 
Would it be possible to either
1) add 'Take Screenshot' icon next to record icon on top
2) add a menu for customizing icons that would sit on top of the window bar
3) add a shortcut (Cmd+Ctrl+S or something) for taking a screen capture?

Thanks!

**Comment by koush** [comment]
Yes, use Customize Vysor to set up hotkeys or customize the buttons.
