### ISSUE TITLE
Error: vysor protocol version mismatch

### ISSUE THREAD

**Issue by VortexShinoBT** [koush/vysor.io#598]
Hi support,

After the update 3.0.97, I cant seem to connect my android to vysor desktop. It keeps showing error (Vysor Protocol Version Mismatch).

Do assist.

**Comment by janseeger** [comment]
Seems to be the same issue as in #599

**Comment by crouchingtiger** [comment]
Investigated: the current Vysor-release apk available is version 3.0.96, while the latest Windows/macOS desktop binary is version 3.0.97.

I worked around it for now by doing the following:

1. Downloading ``Vysor-release.apk`` found at https://vysorelectron.clockworkmod.com//Vysor-release.apk
2. Extracting the apk with apktool (``apktool d -f -r Vysor-release.apk``)
3. Editing ``BuildConfig.smali`` to change VERSION_NAME to ``3.0.97``.
4. Save and rebuild the APK with ``apktool b -o Vysor-fixed.apk Vysor-release``
5. Self-sign the APK with ``jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore test.apk android``

Note: If you already have a debug signing-cert for Android use, use it here. If you don't, you can create one with ``keytool -genkey -v -keystore ~/.android/debug.keystore -alias android -keyalg RSA -keysize 2048 -validity 20000``

6. Uninstall the current Vysor APK from your device with ``adb uninstall com.koushikdutta.vysor``
7. Install your new APK with ``adb install Vysor-fixed.apk"
8. Relaunch Vysor on your desktop and you should be able to reconnect for now.

**Comment by VortexShinoBT** [comment]
Hi @crouchingtiger , that seems really hard to do as I have complete 0 knowledge on programming. Sad to say, so its gonna be really difficult for me unless u can provide me with a step by step guide. Thanks again

**Comment by crouchingtiger** [comment]
@VortexShinoBT It's just a temporary workaround for those that need to keep going, @koush will need to re-release matching versions once they check-in here.

**Comment by coolloop61** [comment]
Downloaded new version. same issue after .99 install!

**Comment by koush** [comment]
@coolloop61 can you try hitting reload once more to trigger the full app update?

**Comment by VortexShinoBT** [comment]
Hello @koush I am still having the same issue. Tried to reload, reset to no avail. 
Still showing the same error (Vysor protocol version mismatch).

Do assist!

**Comment by koush** [comment]
@VortexShinoBT please verify you are on 3.1.2. Click reload if you are not.

**Comment by coolloop61** [comment]
Looks like I am back in business!! Thank you so much!! It had to reload a couple of times but now I am on 3.1.2 and both my phones worked. Really boring webinars and projects without your awesome app, thanks so much!!!

**Comment by koush** [comment]
Sorry about the trouble everyone. Please let me know if there are further protocol mismatch issues.
Will leave this issue open until I get a few more confirmations.

**Comment by tymoloney** [comment]
3.1.2 has also worked for me, after having the same error earlier.

**Comment by VortexShinoBT** [comment]
@koush thank you so much! It has been resolved =)

**Comment by crouchingtiger** [comment]
Back in action with 3.1.2, thanks 👍
