### ISSUE TITLE
Error: vysor protocol version mismatch v3.0.97

### ISSUE THREAD

**Issue by TouchBoarder** [koush/vysor.io#599]
**Bug**
After Vysor got updated and restarted to version v3.0.97 I get Error: vysor protocol version mismatch

**Vysor Bug Report Log**
id 103024164705761027175
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.2.5","chrome":"80.0.3987.165"}
package.json 3.0.97
runtime package.json 3.0.84
os win32
electron true
pwa false
screen 824 1536 864 1536
https://vysorelectron.clockworkmod.com/#/device/ce0517156409988e0d
Connecting...
enterprise cache not licensed
clockwork cache licensed
device status device
Checking Vysor APK installation...
protocol version: vysor-io-74
Uninstalling older Vysor APK...
fetching apk /Vysor-release.apk
Installing Vysor APK...
apk size: 4322329
adb push finished: OKAY
apk installation result: Success

protocol version: vysor-io-74
Error: vysor protocol version mismatch

**To Reproduce**
1. Updated to v3.0.97
2. View Android Device

**Screenshots**
![image](https://user-images.githubusercontent.com/4790667/90113976-5cab2c00-dd52-11ea-8d3d-bdb7317717ea.png)

**Desktop**
 - OS: Windows 10
 - Vysor Version 3.0.97

**Android**
 - Device: Samsung SM G955F
 -- OS: Android 9

 - Device: Samsung SM T515
 -- OS: Android 9,10

 - Device: Huawei ANE LX1
 -- OS: Android 9

**Comment by koush** [comment]
Investigating now.

**Comment by koush** [comment]
Duplicate. Also fixed (hit reload, and it will prompt to update)

https://github.com/koush/vysor.io/issues/598

**Comment by waltw** [comment]
I hit reload but I am still getting this error.  I downloaded version 3.0.97 an hour ago, 

I uninstalled vysor and reinstalled.
I removed the vysor apk from android command line.
When I try and connect to my android device, I am still getting this error.

**Comment by waltw** [comment]
Since you've closed this, should I open a new case?

**Comment by waltw** [comment]
BTW I have a paid license.

**Comment by koush** [comment]
Please check the other issue!

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/598
