### ISSUE TITLE
No way to revoke a link sent across network?

### ISSUE THREAD

**Issue by Therril-83** [koush/vysor.io#6]
I tried sending a link across the office, and it works very well, but now I don't seem to be able to revoke that access any way.

**Comment by koush** [comment]
I just fixed it so it revokes when the phone is disconnected. Before it was revoking once Vysor+Chrome was exited.

**Comment by Therril-83** [comment]
that sounds great.
Must say I really dig Vysor so far, impressive work.

**Comment by koush** [comment]
unshare button implemented
