### ISSUE TITLE
Black screen issue on Micromax Nitro A311

### ISSUE THREAD

**Issue by Akshay124** [koush/vysor.io#60]
as mention by others, black screen issue on my phone.

OS : Windows 7
Mobile : Micromax Nitro A311
Android : 4.4.2
Not Rooted
ADB Downloaded from : http://koush.com/post/universal-adb-driver
Connected : USB (PTP)

Vysor extension inspections:
Screen.html
`increasing TOTAL_MEMORY to 67108864 to be compliant with the asm.js spec (and given that TOTAL_STACK=5242880)
pre-main prep time: 21 ms
init
WebSocket connection to 'ws://127.0.0.1:53516/input' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
input websocket failed, retrying. attempt 1 out of 5
input websocket opened
{"nav":true,"screenHeight":1280,"type":"displaySize","screenWidth":720}
adb client socket path
received socket Socket
notification: Your Android screen is unavailable right now. This can sometimes be resolved by rebooting your Android.`

Backgroud.html
`Vysor version 1.0.6.0
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36
gcm registration APA91bHkRKy8OUtYtldC56IQ3FXxe1gMDoZnnqwMZNYQxEvu0FxLWyLSEz_qjsUxs51uVKgfuW3ArpaTP8Oo-3dYOMY2FKlnue8p-Wb29I7F3-3DwRi9hinaD4lnEFMVi6CWf6QW6AB0ncjGJ8bhRSL4L-6mbYmtSA
protocol version: vysor-io-12
using /system/bin/app_process
got main socket Socket
set password `

Try to use it after restarting mobile but still not working.

**Comment by kchacon** [comment]
Hi, 

I have the same problem, in my PC appears this message:
"Your android screen is unavailable right now. This can sometimes be resolved by rebooting your Android"

But in my android device appears this message:
"This Android device may not support screen recording. Vysor may not work properly"

How can I enable the screen recording feature??

I hope you can help me!!

Thanks in advanced.
