### ISSUE TITLE
BUG: Updated Vysor 3.0.97 defaults to low image quality on every connection

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#600]
Since the update to the PC client version 3.0.97 (Android APK is currently 3.0.96), every time I connect to the phone the video quality is set to "low" and I have to go into setting, change the quality back to "high". This happen every time I connect to the phone and it started with today's update to version 3.0.97. 
Before today's update, Vysor used to remember the video quality settings from the previous connection to the same phone.

**Comment by koush** [comment]
Can you generate a bug report please?

**Comment by clubtech** [comment]
Here is the bug report. This is when the video settings are set to "high". The video looks very blurry, so I had to go into settings, set it to "low" and then "high" again to fix it. This happens on every connection to the phone

https://gist.github.com/75ebf4da490663ddec01c52a012ecf83

**Comment by koush** [comment]
Fixed in 3.1.2. Please confirm.

**Comment by clubtech** [comment]
Thank you for the quick fix. Confirmed it is now working as before.
