### ISSUE TITLE
Error: vysor protocol version mismatch

### ISSUE THREAD

**Issue by waltw** [koush/vysor.io#602]
73dabdca-d7b3-4e22-aaef-ceae6e98eee2.txt
id 116792073389449540326
email walt.in.ca@gmail.com
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 3.0.99
runtime package.json 3.0.99
os win32
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/background
enterprise cache not licensed
clockwork cache licensed
 8a4f8a86-95b6-4c4b-9dcf-d21b37fa2a76.txt
id 116792073389449540326
email walt.in.ca@gmail.com
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 3.0.99
runtime package.json 3.0.99
os win32
electron true
pwa false
screen 728 1366 768 1366
https://vysorelectron.clockworkmod.com/#/device/6d721c5
Connecting...
enterprise cache not licensed
clockwork cache licensed
device status device
Checking Vysor APK installation...
protocol version: vysor-io-74
Uninstalling older Vysor APK...
fetching apk /Vysor-release.apk
Installing Vysor APK...
apk size: 4322329
adb push finished: OKAY
apk installation result: 	pkg: /data/local/tmp/apk1597341321243.apk
Success

protocol version: vysor-io-74
Error: vysor protocol version mismatch
 9f2b1ddd-6588-4e0f-a6ff-aa1f36911dca.txt
id 116792073389449540326
email walt.in.ca@gmail.com
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 3.0.99
runtime package.json 3.0.99
os win32
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/
enterprise cache not licensed
clockwork cache licensed

uninstall apk from device ( adb shell pm uninstall -k "com.koushikdutta.vysor")
uninstall vysor from windows 10 PC.

Download and install Vysor from website.
Prompted to reload new version (reloaded)
About shows Vysor Pro Version 3.0.99

Click on VIEW for my device.

Window indicates uninstalling apk, then installing apk, then the error.

Android 5.1.1,  Windows 10.
[vysor.log](https://github.com/koush/vysor.io/files/5070674/vysor.log)

**Comment by waltw** [comment]
I did see issue 599, and and followed the above steps after seeing that issue "resolved".  Originally I saw the error earlier today on version 3.0.97, but it still exists on 3.0.99.

**Comment by VortexShinoBT** [comment]
Yes I am still having the same issue as earlier even with this new update.

**Comment by VortexShinoBT** [comment]
Thank you it has been solved! =)

**Comment by koush** [comment]
@waltw this is a duplicate that was just resolved. Please click reload, and make sure you are on the 3.1.2 version.

**Comment by waltw** [comment]
I have clicked reload several times, with the same result.

This time version updated to pro 3.1.2, and its working.  Thanks.

**Comment by robjed** [comment]
I am having the exact same problem. I followed the "several times" reload "fix" (which is really ridiculous, in that the software seemingly is not behaving in a deterministic way). The version on my desktop is 3.1.4 pro. It worked before the weekend, after it stopped with the same issue, but again is in this retry loop. To be honest, i would prefer that there would be no need to reinstall the apk. Instead the software that is connecting should fall back to old protocol. A warning / adjusted functionality could still happen, but it cannot be, that I cannot rely on this essential part of my workflow.

**Comment by koush** [comment]
@robjed The underlying issue is that the remote server APK gets cached depending on firewalls/proxies. I'm trying to figure out a way around it. It also packages the correct APK into the desktop installer, so something else seems to be the issue in your case.
Here's the correct link.

https://github.com/koush/app.vysor.io/raw/master/dist/Vysor-release.apk

**Comment by koush** [comment]
I've also updated the play store apk.

**Comment by koush** [comment]
I'll also update it so a protocol version mismatch (ie, the apk and desktop app being out of date) does not hard fail. In most most instances it can actually continue working just fine, however new features may not work. The error should not make it unusable.

**Comment by robjed** [comment]
Hello koush,
sorry if my post sounded upset. I really appreciate the effort! The issue with the proxy/firewall is of course of significance. The particular pc is in an company environment which is not very strictly regulated, but definitely in some degree is. If you need any loggings / environment information from me, feel free to ask.

**Comment by koush** [comment]
@robjed no worries, i know a lot of people rely on this and I issues can be frustrating. You can work around the firewall by directly installing the apk.

Alliteratively, if you click reload, it will trigger an update to 3.1.5 which will relax the desktop/android version match check.

**Comment by robjed** [comment]
Awesome, it worked! After exiting the application in the tray and restarting it, the new 3.1.5 started and the connection worked as it used to do.
@koush keep on keeping on!
