### ISSUE TITLE
Unable to View Android Device over Network on 3.1.2. (Previously worked on an older Vysor version)

### ISSUE THREAD

**Issue by KL92** [koush/vysor.io#603]
**Describe the bug**
Unable to connect to Android device over Network. This previously worked fine on the previous Vysor build. 

**Attach a Vysor Bug Report Log**
https://gist.github.com/165f170a4be7e0d6d15a97a406103aa4
[165f170a4be7e0d6d15a97a406103aa4-7e1235c581345085e46763bd9e69872ecac3d9c6.zip](https://github.com/koush/vysor.io/files/5071929/165f170a4be7e0d6d15a97a406103aa4-7e1235c581345085e46763bd9e69872ecac3d9c6.zip)

**Expected behavior**
Previously able to connect to Android device and view what is displayed.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14269074/90197040-98f98d80-de21-11ea-8c90-313b334fee2c.PNG)
![Capture1](https://user-images.githubusercontent.com/14269074/90197042-9a2aba80-de21-11ea-8e02-bf28d0a4a3bd.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Vysor Version 3.1.2

**Comment by KL92** [comment]
Is there a way to install an older vysor build and stop the auto-update to test?

**Comment by koush** [comment]
Can you install this APK? https://github.com/koush/app.vysor.io/blob/master/dist_electron/bundled/Vysor-release.apk

**Comment by koush** [comment]
Once installed, try again.

**Comment by koush** [comment]
And what version of Android is this?

**Comment by KL92** [comment]
> Can you install this APK? https://github.com/koush/app.vysor.io/blob/master/dist_electron/bundled/Vysor-release.apk

getting a page not found error

**Comment by koush** [comment]
Sorry, I mean this link: https://app.vysor.io/Vysor-release.apk

**Comment by KL92** [comment]
![Capture](https://user-images.githubusercontent.com/14269074/90200834-445c0f80-de2d-11ea-805b-95abdee93146.PNG)
![Capture2](https://user-images.githubusercontent.com/14269074/90200836-458d3c80-de2d-11ea-8ffe-d32f093ed3ba.PNG)

getting these errors now

**Comment by koush** [comment]
I have a fix coming.

**Comment by koush** [comment]
Resolved in 3.1.3. Please confirm.

**Comment by KL92** [comment]
getting these errors now on 3.1.4. Any ideas?

![image](https://user-images.githubusercontent.com/14269074/90343954-807bb400-e069-11ea-9cd4-ba46e64023b2.png)


![image](https://user-images.githubusercontent.com/14269074/90344014-e9fbc280-e069-11ea-85b8-1dd7545e4189.png)

**Comment by koush** [comment]
I will need generated bug reports after you see these errors. Leave this window open when taking the report.

**Comment by KL92** [comment]
With the window open and clicking "Bug Report" I am getting a network error. Bug Report works without having the View window open

![image](https://user-images.githubusercontent.com/14269074/90344855-883f5680-e071-11ea-8878-4e5bd285fd48.png)

**Comment by koush** [comment]
Are you behind a firewall or anything?

**Comment by KL92** [comment]
I tried temporarily disabling the firewall with the same result. Bug report is throwing the above error while the Android device is in the "View" window.

**Comment by airiar** [comment]
Hi Guys,

Same thing here. Android 4.4 , MacOs and Llatest vysor. Bug report:
https://gist.github.com/4bb5f5b226dd55a2098959bb3e283e69

**Comment by koush** [comment]
> Hi Guys,
> 
> Same thing here. Android 4.4 , MacOs and Llatest vysor. Bug report:
> https://gist.github.com/4bb5f5b226dd55a2098959bb3e283e69

android 4.4 is not supported.

**Comment by airiar** [comment]
> > Hi Guys,
> > Same thing here. Android 4.4 , MacOs and Llatest vysor. Bug report:
> > https://gist.github.com/4bb5f5b226dd55a2098959bb3e283e69
> 
> android 4.4 is not supported.

Thank you for your reply Koush. 
Our company using Vysor all around the world and we love the product. Do you think it would be possible to discuss with you how we could re-enable Android 4.4 support? It was working all the way till past weeks when Vysor was updated 
Thank you

**Comment by KL92** [comment]
Is this the same issue I am experiencing?

**Comment by koush** [comment]
The WebSocket VerifyError has been fixed and this should be resolved.

**Comment by KL92** [comment]
Verified working Thanks!!
