### ISSUE TITLE
Why does Desktop Vysor uninstalls the Vysor app in my Android device and installs a new one when I connect?

### ISSUE THREAD

**Issue by cerino-ligutom** [koush/vysor.io#604]
As the title says. I just got my self a new android phone and at the very least, I think, have the bare minimum required to run the app.

Some context that might help:

- _Developer Mode_ is enabled.
- _Install via USB_ is disabled. Xiaomi phones require us to login/register a Mi Account before being able to turn on this option.
- _Vysor Pro Version 3.1.2_ on Desktop (lifetime individual license).
- I _manually installed_ the Vysor App _Version 2.3.1_ from Play Store.
- If I press either `View` or `View wireless` button, the desktop app uninstalls the Vysor app in my phone and attempts to install a new one.

**Comment by koush** [comment]
The desktop app will install the most recent compatible APK. Sometimes play store is out of date.
