### ISSUE TITLE
(BUG) The latest update to Vysor (3.1.3) broke dimming the phone's screen

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#606]
This is a new issue that started with today's update to 3.1.3. 
When connecting to the phone, it dims the screen as intended. When disconnecting from the phone however, the screen remains dim and the sessions does not actually disconnect from the phone. 
The Vysor keyboard also remains visible after disconnecting from the phone.

Tested both on Vysor via Windows 10 and Linux. Both started to have this issue as of today with the update.
Log: https://gist.github.com/VysorLogs/6d2115977d6a9b8f0f8d105bd8d911a8

**Comment by koush** [comment]
Investigating. Thanks for the report.

**Comment by koush** [comment]
Can you detail how you are disconnecting the phone? Closing the window, or physically disconnecting?

**Comment by clubtech** [comment]
I'm connecting over wifi and simply closing the Vysor window to disconnect. This is how iv'e been using it for a long time, but today's update broke the disconnect part. The phone seems to think the PC is still connected and does not release the screen from dimming or the Vysor virtual keyboard. I have to manually kill the Vysor phone app for the keyboard to go away and manually set the screen back to "auto".

**Comment by koush** [comment]
Thanks, I'll take care of this today or tomorrow.

**Comment by koush** [comment]
Fixed in 3.1.4

**Comment by clubtech** [comment]
Confirmed fixed. Thank you again for the fast response.
