### ISSUE TITLE
Audio Mirroring does not work!

### ISSUE THREAD

**Issue by Matosque** [koush/vysor.io#611]
**Describe the bug**
Hello, I bought the Vysor Pro Option today, hoping for some decent quality mirroring. The quality and everything else works fine, the only problem is that the Audio Mirroring just does not work. I checked the Box in the Settings, it doesn't work through wi-fi or cable. When I click the Toggle Audio setting at the top, my device asks for permissions. I even have a Notification on my phone, that Vysor is mirroring the audio. It does not work though. Thank you for your help.

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/b820e75de2698e33d21c33d9c4232dce

**To Reproduce**
Connect your phone, start mirroring, enable audio mirroring on Vysor and on the Phone.

**Expected behavior**
Working sound on my Windows PC! NOT my phone!

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Vysor Version [Vysor Pro 3.1.10]

**Android (please complete the following information):**
 - Device: [Oppo Find X2 Lite]
 - OS: [Android 10]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Comment by clubtech** [comment]
I think some apps that worked with the cast workaround to mirror audio do not work with the native solution. Spotify for example works with the cast audio mirroring workaround, but does not mirror the audio when using the native audio recording solution. The same goes for Soundcloud. Seems like these apps block audio recording?
Also when using the native audio mirroring option with apps that do work, the audio plays on both the phone and the PC. I have to lower "media" volume on my phone to 0 so it will only play on the PC.

**Comment by koush** [comment]
Here's how audio capture works on Android:

_Note: The ability for an app's audio to be captured also depends on the app's targetSdkVersion._
* By default, apps that target versions up to and including to Android 9.0 do not permit playback capture. To enable it, include android:allowAudioPlaybackCapture="true" in the app's manifest.xml file.
* By default, apps that target Android 10 (API level 29) or higher allow their audio to be captured. To disable playback capture, include android:allowAudioPlaybackCapture="false" in the app's manifest.xml file.

https://developer.android.com/guide/topics/media/playback-capture

**Comment by clubtech** [comment]
Thanks.
I checked and Soundcloud and Google Chrome both target Android 11 at this time and both do not mirror their audio. I assume they are blocking it intentionally.
Spottily is targeting Android 9.

**Comment by koush** [comment]
Yeah, I don't use soundcloud, but Chrome does seem to not allow it.

**Comment by FerLuisxd** [comment]
Any alternative for this? Or miracast is the only solution now?

**Comment by koush** [comment]
@FerLuisxd the old chromecast option still works, and supports DRM audio
