### ISSUE TITLE
Vysor CLI

### ISSUE THREAD

**Issue by mondalaci** [koush/vysor.io#614]
Any way to autoconnect to the only device listed by `adb devices` upon starting up Vysor? A command line argument would work.

**Comment by geajack** [comment]
Came here to request the same thing. For example `vysor --connect` to connect to the only connected device and `vysor --connect 2dde567` to connect to a specific serial number'd device.

Please **don't** display the main window when this option is used, the whole point would be to avoid having to close it every time.

If the target device doesn't exist, Vysor should either return a non-zero exit status so it can be caught and handled in a script (use case: writing a launcher script that I can bind to a shortcut or something on Linux) or default to opening the main window, ideally showing an error message to explain that it couldn't find the device.

**Comment by koush** [comment]
This is rolling out now.
https://github.com/koush/vysor-cli

**Comment by koush** [comment]
Will need to be on the beta release.
