### ISSUE TITLE
PWA stuck at "Installing Vysor APK..."

### ISSUE THREAD

**Issue by frunkad** [koush/vysor.io#615]
**Describe the bug**
I had been using the app from Chrome Web Store until yesterday when a forced prompt required me to install via the PWA. With the PWA, on connecting the PWA uninstalls older apk and install newer one - but is stuck there. On restarting, it gets stuck at "Connecting". 

**Attach a Vysor Bug Report Log**
https://gist.github.com/948de094c6089993a687f85019378952

**To Reproduce**
1. Install PWA
2. Connect to a device that was earlier working with Chrome App
3. It gets stuck at Installing / Connecting

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/33373582/92296977-064b9a80-ef58-11ea-9266-ce07f5fc2a8b.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Vysor Version 3.1.12

**Android (please complete the following information):**
 - Device: OnePlus 3T
 - OS: Android 9
 - Vysor Bug Report Link: https://gist.github.com/948de094c6089993a687f85019378952

**Android Logcat**
-not familiar-

**Additional context**
I guess an app install trigger wasn't fired by the PWA. I tried installing the lastest app from Play Store - but it got uninstalled by the PWA.

**Comment by koush** [comment]
You should download the Linux snap or appimage.
Also, is the installation window open when you are generating the bug report? It seems to be missing information.

And what browser version?

**Comment by frunkad** [comment]
This works on the Linux snap!

And yep, the window is open when generating bug report. However, I had to send my phone for repair so can't give it another try until Tuesday :/

Browser is Chrome 85.
