### ISSUE TITLE
License cannot be retreived

### ISSUE THREAD

**Issue by felix-d-git** [koush/vysor.io#616]
When I want to login it does not work:

I am getting redirected, choose my google account and then I get this:
![grafik](https://user-images.githubusercontent.com/24978665/92313901-3f742100-efd1-11ea-88c8-a4f4f10e9fda.png)

**Comment by koush** [comment]
Doing some server migrations today. Should be resolved shortly.

**Comment by koush** [comment]
Should actually be resolved right now, let me know.

**Comment by felix-d-git** [comment]
Yes awesome!

**Comment by koush** [comment]
Great sorry for the trouble
