### ISSUE TITLE
Copy paste Japanese/Chinese characters cause error.

### ISSUE THREAD

**Issue by roamingphantom** [koush/vysor.io#617]
After copying Japanese/Chinese texts, pasting it to anywhere(both phone and desktop) turn the characters into unidentified chars.
This doesn't happen if it uses the native android paste(long click/press, and select 'paste')

1. Copy any Japanese/Chinese characters.
2. Paste with keyboard shortcut ctrl+v to anywhere
3. Characters will become unreadable.

 - OS: Windows 10
 - Vysor Version 3.1.17

 - Device: Oneplus 3T
 - OS: Android 8
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/96b1ef2bf058c601f05f6509dc91ca21

![temp43](https://user-images.githubusercontent.com/71005671/92575164-9708da00-f2ba-11ea-9709-70955b19f04c.JPG)

**Comment by koush** [comment]
Can you confirm this bug still happens? I fixed another related bug involving text encoding. https://github.com/koush/vysor.io/issues/623

**Comment by roamingphantom** [comment]
Confirmed already fixed! I have tried how I usually copy paste them, no longer showing unidentified characters now. Thank you!

**Comment by roamingphantom** [comment]
Confirmed already fixed! I have tried how I usually copy paste them, no longer showing unidentified characters now. Thank you!
