### ISSUE TITLE
Here are my issues

### ISSUE THREAD

**Issue by roeljohn** [koush/vysor.io#619]
So I'm trying to mirror my phone in nba 2k20 then I realize the audio still not working when you using recording on phone. So I decided to use OBS then realize I can't transfer the audio in obs so is just the same. 

The screen doesn't fit to on the obs maybe on my screen monitor I'm using 1920x1080 on pc

**Comment by Heretushi** [comment]
Please use the issue template. There are A LOT of missing information to be able to troubleshoot. Thanks.
