### ISSUE TITLE
i can't cancel subscription i click on that red button but nothing happens

### ISSUE THREAD

**Issue by abdlhay** [koush/vysor.io#620]
**Describe the bug**

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Vysor Version [e.g. 2.2.2]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Can you provide a screenshot of the red button?

**Comment by abdlhay** [comment]
@koush 
![Annotation 2020-09-12 191116](https://user-images.githubusercontent.com/44603158/92988861-9d23d400-f4cf-11ea-81e6-7040bf071a11.jpg)

**Comment by koush** [comment]
What happens when you click it? Can you get me the javascript console log? And another screenshot after clicking it?

**Comment by koush** [comment]
It looks like your card is inactive anyways, and the subscription is set to cancel regardless.
