### ISSUE TITLE
[NOTIFICATIONS] When using the "international keyboard" option, Vysor constantly sending an ongoing keyboard notifications to the PC

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#622]
**Describe the bug**
When the "international keyboard" option is turned on in the Vysor main window, every time an app is opened on the phone a notification is sent to the PC per the attached image. This is because there is an ongoing notification on the phone for the keyboard. If you can have Vysor ignore this specific notification that would make things a lot less disturbing.
A workaround would be to disable this notification on the phone, but it's not an ideal solution. 

No bug report to attach this is a not a bug, as Vysor seems to be configured to send ALL notification from the phone to the PC (including ongoing persistent notifications which are needed to alert of incoming calls)

**To Reproduce**
1. enable the international keyboard option in the main app.
2. Connect to a device and start opening apps that require keyboard input.

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/15256218/93008795-d7bc5980-f52d-11ea-827a-3bcebec294aa.png)

**Comment by Heretushi** [comment]
Interesting. I did not use Vysor today, I used it yesterday and I use international keyboard exclusively. Never had this issue. I do have to mute the Android Notification since it buzzes all the time if I don't.

Please provide the version of Vysor you're using. Thanks!

**Comment by clubtech** [comment]
This is for the new notifications feature that was launched today. I need to completely disable this notification on the phone to make stop pushing it to the PC every time I interact with the phone.

**Comment by Heretushi** [comment]
Understood. Thanks!

**Comment by koush** [comment]
I'll filter out ongoing notifications, thanks for the report.

**Comment by koush** [comment]
Fixed in 3.2.2 by removing ongoing notifications. I'll need to revisit ongoing notifications in the future, as the desktop UX is meant for temporary ones, depending on host OS (mac/linux).

**Comment by clubtech** [comment]
Thank you for looking into this so quickly.
One side effect from removing ongoing notifications altogether is that some ongoing notifications are actually beneficial to the user such as incoming VOIP calls (Duo, WhatsApp etc). Now they longer come in via Vysor. Would it be possible to enable ongoing notifications and just filter the keyboard one instead?

**Comment by koush** [comment]
I've fixed this by preventing Vysor from spamming those keyboard notifications.

**Comment by koush** [comment]
I'm a bit concerned that ongoing notifications (like downloads or playback) will spam the Desktop.

**Comment by clubtech** [comment]
Valid concern. Just tested it with Spottily and it only sends a notification when a song changes which is not bad actually, but maybe other users will find it annoying? It certainly didn't spam my desktop like the keyboard notification was.

**Comment by clubtech** [comment]
I know other apps that handle notifications such as Join or Microsoft's Your Phone will allow users to enable / disable notifications from specific apps. Maybe this is something you can implement in a future release.
