### ISSUE TITLE
[NOTIFICATIONS] Vysor does not display none English notifications correctly

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#623]
**Describe the bug**
When a none English notification comes in (Hebrew in case), Vysor does not display the letter correctly (See image)

Bug report:
https://gist.github.com/9db3b56ba37b76774599ebc3ef63bbd1

**To Reproduce**
1. Receive a notification that does not contact English letter.
2. It does not display properly.

**Screenshots**

![Screenshot (3)_LI](https://user-images.githubusercontent.com/15256218/93008839-6af58f00-f52e-11ea-9ed3-e691f8670f10.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 3.2.0

**Android (please complete the following information):**
 - Device: Samsung Note 20 Ultra
 - OS: Android 10

**Comment by koush** [comment]
Good bug report. I fixed this in 3.2.3.
