### ISSUE TITLE
Bad image quality in latest version (3.2.5)

### ISSUE THREAD

**Issue by TomasVseticka24i** [koush/vysor.io#626]
After last update of vysor (to 3.2.5) quality is very bad. Even on HIGH quality settings (logged in) image is very bad. It takes even 20 seconds until image is cleared out slowly. Previously image was "instantly" at high quality.
Looks like now image is highly compressed and over time it getting better quality.
Is there a way to run older version? This one is unusable ://
Attached is how screen looks like after change (left) and 20 seconds later (right)
![vysor](https://user-images.githubusercontent.com/36406911/93083403-d6f10800-f692-11ea-8e5a-ba158f07580c.png)

**Comment by koush** [comment]
Investigating.

**Comment by koush** [comment]
Use the bug report template. This does not have enough information.

**Comment by koush** [comment]
Try setting the quality to low then high to see if it triggers an update.
