### ISSUE TITLE
Resolution change on version update

### ISSUE THREAD

**Issue by okimchi** [koush/vysor.io#627]
**Describe the bug**
I was working on my Android device, counting on the resolution consistency. But to my surprise  after a certain restart of the software, the resolution was completely mixed up (I was making sure the setting were identical) and I realised an update took place behind the scene.

First, why the update is forced and not by choice?
second, why the update have anything to do with the resolution?

**Comment by koush** [comment]
There was a bug where the default resolution was incorrect and forced to 25%. This caused a lot of low resolution devices to fail altogether. The bug fix actually reverted it to the correct and original behavior.
