### ISSUE TITLE
Vysor Protocol Version Mismatch Error when attempting to connect

### ISSUE THREAD

**Issue by pmbrennan** [koush/vysor.io#629]
Windows 10, Pixel 3, Android 10

I have:

- rebooted the phone
- removed the Vysor app from the phone
- removed the Vysor app from my computer
- re-installed the Vysor app from https://www.vysor.io/
- re-start Vysor - it is reporting version 3.0.95, even though the installer was called Vysor-win-3.1.4.exe.
- attempt to connect to Android device

result - dialog:

### Error Connecting to Android Device

Error: vysor protocol version mismatch

I need Vysor to do my work, so I am currently blocked by this issue.

**Comment by koush** [comment]
Click reset Vysor. It should trigger an update to version 3.3.x

**Comment by pmbrennan** [comment]
I had previously tried that, to no avail. However, something in the workflow documented above must have triggered the right bits, because this time, hitting Reset Vysor did in fact trigger an update to the latest version. I recommend you look more closely at upgrade paths, but for now, thank you for the suggestion!
