### ISSUE TITLE
1.0.6.1 - terribly slow screen updates

### ISSUE THREAD

**Issue by alaricljs** [koush/vysor.io#63]
While keyboard input works fine, the visual refresh in the window is surprisingly slow.  It's not dropping frames and it just took ~5 minutes for it to catch up with my clearing ~8 notifications from the lock screen then opening SMS and sending a quick text.  I used Vysor for the typing in spite of the display not being in sync and that part worked.

Linux + GS4

**Comment by alaricljs** [comment]
FYI - still there with 1.0.6.2

**Comment by jebeld17** [comment]
The app tends to lag big time when running in tandem with Windows 10 on my PC. I am using an HTC One M9 Developer Edition USA as my phone with my PC running Windows 10 Pro Insider Preview w/ 8GB DDR3 RAM, AMD Phenom II X4 processor @ 3.3GHz Max, and Nvidia GeForce 440 with 2GB dedicated RAM.

**Comment by hcchengithub** [comment]
It's Vysor 1.0.6.4 now. 
It takes 5 seconds to make a screen update, reproducing steps are:
1. Android phone HTC Butterfly-2 desktop.
2. Slide desktop pages from one to another, count the time.
3. It takes 3 ~ 5 Seconds.
I tried a much short USB line (40cm), same result.
But same smart phone on another computer was much better, only 2 seconds.

Let me know if I can do any further.

**Comment by koush** [comment]
new decoder, should be fixed.

**Comment by Fuzzyma** [comment]
its NOT - still awfully slow. Cant even unlock my phone

**Comment by RHC1017** [comment]
Hello guys, is there any solution to fix the lagging problem of Vysor Pro? My Audio is mirrored accurate but the video is delayed for 5-10secs in my guess. Thanks in advance.

**Comment by reatcas** [comment]
Same here, using a Samsung SM A325M
Everything even the Vysor Interface is slow, about 1 frame per 2 seconds, is extremely slow, I had the patience to reset settings and click on low resolution but it stays the same
