### ISSUE TITLE
Connection to Vysor Share Server failed. Timeout waiting for RTC Connection.

### ISSUE THREAD

**Issue by fims** [koush/vysor.io#630]
**Describe the bug**
Shared devices can't be accessed anymore. When trying to open a Share Link the error "Connection to Vysor Share Server failed. Timeout waiting for RTC Connection." I updated yesterday from Version 2.3.1 to 3.2.8 and it wasn't working the whole day. One hour ago it was working and a connection could be established. But now it's not working again. 

**To Reproduce**
1. Click on 'Share All Devices'
2. Click on 'COPY SHARE LINK'
3. Past link in Browser. 
4. Click on 'Open Vysor'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Tried with Windows 10 and macOS Catalina 10.15.6
 - Vysor Version 3.2.12

**Comment by koush** [comment]
you did not generate a bug report. i need that.

**Comment by koush** [comment]
please click reload to update to 3.2.13 as well.

**Comment by koush** [comment]
Please ensure the both the share server and the client are at the latest version of Vysor (3.2.13 as of a few minutes ago)

**Comment by fims** [comment]
Updating to the latest Version 3.2.13 solved the problem. Thanks
