### ISSUE TITLE
Getting "Error: apk path failed (empty)"

### ISSUE THREAD

**Issue by rossodono** [koush/vysor.io#631]
**Describe the bug**
When clicking 'view' in Vysor for my Samsung Galaxy S7 I get the following message after it attempts to connect "Error Connecting to Android Device......Error: apk path failed (empty)"

I was able to connect for many days last week after first purchasing Vysor. Today Vysor was updated after it suggested to relaunch it, and now I can not connect to the phone anymore

**Attach a Vysor Bug Report Log**
Bug report was created

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Vysor
2. Vysor suggests relaunching application for the latest version. 
3. Connect Samsung Galaxy S7 phone via USB
4. Click 'View' button beside the SM G930F. It attempts to connect but produces an error
5. Click 'Wifi' button beside the SM G930F. It attempts to connect but produces an error

**Expected behaviour**
As it has done previously it should be able to connect to the phone and show its display in the separate window

**Screenshots**
<img width="525" alt="Screenshot 2020-09-16 at 09 22 31" src="https://user-images.githubusercontent.com/71375370/93312793-86e38400-f7ff-11ea-9656-7ef72890adcf.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Vysor Version: 3.2.13

**Android (please complete the following information):**
 - Device: Samsung Galaxy S7 / SM G930F
 - OS: Android version 8.0.0 / Samsung Experience version 9.0
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/8815b20ebff5cce6ceeb8325d658f5dd

**Android Logcat**
I am not familiar 

**Additional context**
This worked fine last week for many days until Vysor was updated today

**Comment by koush** [comment]
Your device is out of space.

> web apk installation result: Error: android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
