### ISSUE TITLE
Vysor greyed out and not able to click on anything except reload/close the window to continue

### ISSUE THREAD

**Issue by roamingphantom** [koush/vysor.io#632]
**Describe the bug**
If connection to the phone is interrupted, Vysor will show such error message and disable+grey out the screen.
Once connected back, this error message will disappear and screen is enabled again.
But if Vysor was reconnected while it's minimized, this grey out+disabled layer persists.

**Vysor Bug Report Log**
https://gist.github.com/VysorLogs/f16eb340992701efbf0ca806a6b1ca40

**To Reproduce**
1. Open Vysor & connect to phone
2. Minimize Vysor
3. Disconnect the phone
4. Reconnect the phone
5. Vysor will pop up and the screen is greyed+disabled
6. Can only close the window from Vysor main screen or reload the app entirely to continue

**Expected behavior**
By right should follow the behavior when window is not minimized.

**Desktop:**
 - OS: Windows 10
 - Vysor Version 3.2.14

**Android:**
 - Device: Oneplus 3T
 - OS: Android 8
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/f16eb340992701efbf0ca806a6b1ca40

**Comment by Heretushi** [comment]
Can confirm I have this same issue. I have had it this week still, can't confirm any versions other than Windows 10 Pro and Pixel 3 running up to date Android.

**Comment by koush** [comment]
fixed in upcoming release with a Vuetify update.

**Comment by ertankucukoglu** [comment]
I just got identical problem on a recent version.
- Poco X3 NFC
- Android 11 (Security update 2022-03-01)
- Vysor v4.1.104 (runtime 4.1.77)
- Windows 11
I only see device screen on my computer and record/capture that's all. I cannot use device from my PC using mouse.
