### ISSUE TITLE
"Notification on windows new feature" OK but has to be corrected

### ISSUE THREAD

**Issue by Alaingent** [koush/vysor.io#633]
To continue with the new "notification" fonction, we thank you for it, BUT 👍 
- in Windows 10 , when a notification is received, when we click on it, it disappears but not open Vysor Desktop tab. Please, like asked on my main and original request about call and other notification, make "first plan" (like "always on top" option) Vysor desktop app when we click on a notification in order to immediately answer and/or access to the android app corresponding to the notification.

- is there being possible to have all notification in "color"  (like "crono" android app or "chrome notification") able ? because vysor notification in windows 10 look always grey and not really easy to see when you work for example. If you can at least make the colored logo of each application android sending the notification it is better.

thank you in advance and good job.

**Comment by koush** [comment]
I need a video or screenshot to understand the bug here.

**Comment by Alaingent** [comment]
hello. But what kind of screenshot could i make for you just to understand that when we receive a notification on windows 10 from vysor on the left bottom corner of the screen, i click on it and the vysor interface doesn't appear in first plan (like "always on" option). When i click, yes in vysor interface it opens the good app like "sms" or "whatsapp message" BUT, we need the screen of the Vysor interface go in FIRST once click on the notification please.

**Comment by shameldiesel** [comment]
Same here. Clicking on the notification banner when it appears in windows desktop does nothing. It should bring up the vysor window. Is there a way to fix that?

![image](https://user-images.githubusercontent.com/73908705/98031425-7784be00-1de0-11eb-8c70-a95cd9ae0995.png)

**Comment by koush** [comment]
Fixed, please confirm

**Comment by Alaingent** [comment]
thank you , effectively it seems this morning to be fixed !!! it is very good option. However, PLEASE because it is not the same question but bound with, could you make possible to hide especially 2 notifications :  the first and the most important "keyboard change / Vysor" notification and "battery charging. Complete charged in 1 hour" notification. These 2 notifications appear on desktop at least 100 times per day, it is .... not possible :) i wil open a new ticket to be sure, and another, because since 1 week the pro version is VERY VERY slow, not usually speed. please control it.

thank you
