### ISSUE TITLE
Missing APK

### ISSUE THREAD

**Issue by aweFalafelApps** [koush/vysor.io#634]
https://gist.github.com/d19fafb4e37361e35c011d17d6a0120b

After updating this morning, when trying to connect to a device I get the following error:

Error: ENOENT, native/android/Vysor-release.{...}.apk not found in /Applications/Vysor.app/Contents/Resources/app.asar

**Comment by marttisavolainen** [comment]
Similar problem,

![Capture](https://user-images.githubusercontent.com/64896231/93872397-c23af280-fcd8-11ea-8cdb-c0308e04d9d9.PNG)

**Comment by aweFalafelApps** [comment]
@koush Any idea what's going on here?

**Comment by koush** [comment]
Please ensure you are connected to the internet. It's failing to fetch the server, and then falling back to the packaged apk (which has a bug). I'll fix the latter bug shortly.

**Comment by aweFalafelApps** [comment]
My connection is good, however it is somewhat of a corporate network. Would you mind sharing the url that is being used to try and download the apk?

**Comment by koush** [comment]
Yeah you can just download and install the Vysor apk here manually.

https://github.com/koush/release

**Comment by koush** [comment]
This should be fixed, please verify.

**Comment by koush** [comment]
3.3.20

**Comment by marttisavolainen** [comment]
Good morning,

I downloaded the Vysor-release.apk version 3.2.0 (not 3.2.20).

I installed it to my Android phone successfully.

I reinstalled Vysor to my laptop.

Running Vysor in the laptop and selecting View, will uninstall 3.2.0 version of Vysor in my phone and install another version to it. Error message below.

Br Martti Savolainen

[cid:image001.png@01D6924D.89888150]

**Comment by aweFalafelApps** [comment]
Back in business. Thank you Koushik! Also, and it's been happening for a while, every time I reconnect to my Pixel 3a vysor says it has to reinstall the apk. I'm happy to open another issue, but though you might want to know if you didn't already.

**Comment by koush** [comment]
@aweFalafelApps yes please open another bug with a log of that reinstall. That is very strange.
