### ISSUE TITLE
Installation Has Failed

### ISSUE THREAD

**Issue by Neperson** [koush/vysor.io#635]
Hello, I do not know anything about Programming or anything about this, but I presented this error when installing the desktop application and I need some help since I did not find another place for technical support.

When I open the installer it downloads as usual but just in the middle of it, it stops and immediately the next error pops up.

![Error](https://user-images.githubusercontent.com/66873428/93790726-5c2f6c00-fc01-11ea-8ac1-85eda6ce32dd.JPG)

I add that when the error appears it gives you the option of Open Setup Log and when you click it opens the following File

[SquirrelSetup.log](https://github.com/koush/vysor.io/files/5256609/SquirrelSetup.log)

I also tried the Vysor from the Google chrome browser but I get the following error and I don't know how to fix it...

![error2](https://user-images.githubusercontent.com/66873428/93816985-42545000-fc26-11ea-8561-2941f4c0ae0e.JPG)

note: I speak Spanish. all this I put in the google translator, sorry if it is somewhat misinformed or etc.

**Comment by koush** [comment]
Unsure, but that looks like an old version of windows. Use the issue template.

**Comment by Neperson** [comment]
Where is the issue template? i have Win7
