### ISSUE TITLE
Linux: Arch/Pacman support

### ISSUE THREAD

**Issue by guitaristtom** [koush/vysor.io#637]
I just installed Vysor by building it from [the AUR](https://aur.archlinux.org/packages/vysor-git/), and it isn't launching at all. This is the output I'm getting when I try to launch it from a terminal:

![Screenshot from 2020-09-22 16-10-15](https://user-images.githubusercontent.com/6890628/93946549-654a3700-fcee-11ea-8ecd-8d6ad693598f.png)

**Comment by koush** [comment]
I do not provide the AUR, I did build a snap and appimage.
This AUR actually seems to be hosting an extremely dated version of Vysor as well. (2.x, whereas Vysor is at 3.x right now)

**Comment by koush** [comment]
if you're savvy enough, take a look at electron-builder's supported packages and let me know if there's one I can use for Arch.

https://www.electron.build/

```
All platforms: 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir (unpacked directory).
macOS: dmg, pkg, mas, mas-dev.
Linux: AppImage, snap, debian package (deb), rpm, freebsd, pacman, p5p, apk.
Windows: nsis (Installer), nsis-web (Web installer), portable (portable app without installation), AppX (Windows Store), Squirrel.Windows.
```

**Comment by guitaristtom** [comment]
Pacman is the native package manager for Arch, if it could be compiled to work with that, then it should be real easy to update / add to AUR properly.

Also, looking at the `vysor-git` it'll say an old version because it's pulling right from the GitHub source code and compiling it (alongside ElectronChrome) and installing it. _Maybe_ that's why I'm having the issue because I'm running a fresh build of Vysor instead of a release?

**Comment by koush** [comment]
Try this prerelease pacman build.

https://github.com/koush/vysor.io/releases/tag/v3.2.19

I don't a arch VM set up yet to test it, just did a build and am crossing my fingers. I'll be able to do a proper test/build once I do full update for all the other platforms.

**Comment by guitaristtom** [comment]
I had some time tonight to test this out, and I was having issues with installing this one dependancy: `libappindicator-sharp` 

After removing that from the dependency list and installing the package, it seems to work just fine. I don't know exactly if that dependency is required since you also have `libappindicator-gtk3` in the list, but I have personally not used GTK3 or libappindicator, so I wouldn't know.

For good measure I did also test the `desktop notification` option, and it worked just fine for me for the most part. There was an issue with phone call notifications popping up three times, but I also happened to have this issue with the AppImage version of Vysor, so it's not just with this build. It could also be the way my phone deals with phone call notifications, so I'm not blaming Vysor at all.

**Comment by koush** [comment]
> I had some time tonight to test this out, and I was having issues with installing this one dependancy: `libappindicator-sharp`
> 
> After removing that from the dependency list and installing the package, it seems to work just fine. I don't know exactly if that dependency is required since you also have `libappindicator-gtk3` in the list, but I have personally not used GTK3 or libappindicator, so I wouldn't know.

Hm, I did not set up any of the dependency stuff. That's automatically done via electron-builder. Could you describe where/how you made those changes? I imagine it was to the pacman itself somehow?

**Comment by guitaristtom** [comment]
Yeah it was to the .pacman file itself. I extracted it, edited the `.PKGINFO` file and removed it.

I wonder if it's something that `electron-builder` can change or at least give an option for.

I did try and install `libappindicator-sharp` _just to see_ and it had soooo many dependencies on its own, including several Python 2 things, so it would be great if there was _some way_ to remove it.

**Comment by koush** [comment]
Yeah, unsure why there are mono bindings for libappindicator. I don't think electron has any mono code within it as far as I'm aware. The reason it has a ton of dependencies is likely because that pulls down all of mono and whatever UI binding libraries as well.

**Comment by koush** [comment]
There's now automatic aur support from the deb repo.

https://aur.archlinux.org/packages/vysor-bin

**Comment by guitaristtom** [comment]
Yay!
