### ISSUE TITLE
Audio is not working in Pro version and my screen is not captured fully

### ISSUE THREAD

**Issue by Eribelle** [koush/vysor.io#641]
Audio is not working in Pro version and my screen is not captured fully. Please see attached file

**Describe the bug**
![Screenshot 2020-09-25 170854](https://user-images.githubusercontent.com/71875596/94248971-cf164b00-ff51-11ea-97b6-8dba5f0ee0c6.png)
![Screenshot 2020-09-25 170838](https://user-images.githubusercontent.com/71875596/94248976-d0477800-ff51-11ea-910e-3e9ffedf239f.png)

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Vysor Version [e.g. 2.2.2]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by Eribelle** [comment]
I have fixed the screen size. my problem now is the audio

**Comment by knroy** [comment]
I have bought the pro license but the audio mirroring isn't working on Mac.

**Comment by Eribelle** [comment]
Why nobody from @vysor is not answering? where to contact support? This is really unacceptable.

**Comment by koush** [comment]
> Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

You did not follow the instructions.

**Comment by vysor** [comment]
Hi @Eribelle 

I am not involved in this project and I own the username @vysor

Find another way to get in touch with whoever it is.
Thanks

**Comment by koush** [comment]
Closing because the bug report template was not fully completed.
