### ISSUE TITLE
Vysor Keybord doesn't work

### ISSUE THREAD

**Issue by Ric-82** [koush/vysor.io#642]
Hi,

I can't use Vysor's v3.2.20 keyboard on Windows 10 PRO (2004) with my  Honor View 20 PCT-L29 (Android 10). The only inputs that seems to work are return, backspace and arrow keys, but nothing else. Enable/disable "Internation keyboard" on the control panel is useless.

What can I do?

**Comment by koush** [comment]
Please recreate this issue and use the issue template.
