### ISSUE TITLE
Vysor Keybord doesn't work

### ISSUE THREAD

**Issue by Ric-82** [koush/vysor.io#643]
**Describe the bug**

I can't use Vysor's v3.2.20 keyboard on Windows 10 PRO (2004) with my Honor View 20 PCT-L29 (Android 10). The only inputs that seems to work are return, backspace and arrow keys, but nothing else. Enable/disable "Internation keyboard" on the control panel is useless.

**Attach a Vysor Bug Report Log**

id 111712723147247972519
email r.r.bluestacks@gmail.com
C:\Users\ric-8\AppData\Roaming\vysor
https://vysorelectron.clockworkmod.com/#/
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 3.2.20
runtime package.json 3.1.4
os win32
electron true
pwa false
https://vysorelectron.clockworkmod.com/#/
enterprise cache not licensed
clockwork cache licensed

**To Reproduce**

1. Go to any text box.
2. Try to write something in it, using vysor keyboard.
4. Nothing happens. I can only use return, space, backspace and other non-character keys.

**Expected behavior**

Text should appear in the text box.

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO (2004)
 - Vysor Version: 3.2.20

**Android (please complete the following information):**

 - Device: Honor View 20 PCT-L29
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/da7f90d1db70311c3eac3ee8a2427057

**Comment by koush** [comment]
Did you collect this log while trying to send keystrokes? Not seeing any errors of any sort.

**Comment by Ric-82** [comment]
Hi,

Yes, I tried to send kesytroke while collecting the log but, in the meanwhile the issue has gone. I suspect it has to do with the notification system: I recall I deactivated the notification about Vysor hiding my system keyboard. When I let that notification to show up again, Vysor's keyboard worked again.

I don't know if that's only a coincidence, but I forgot to tell you.

Anyway, thank you for your time.

Riccardo
Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Koushik Dutta<mailto:notifications@github.com>
Inviato: venerdì 23 ottobre 2020 08:05
A: koush/vysor.io<mailto:vysor.io@noreply.github.com>
Cc: Ric-82<mailto:ric-82@live.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [koush/vysor.io] Vysor Keybord doesn't work (#643)


Did you collect this log while trying to send keystrokes? Not seeing any errors of any sort.

**Comment by Ric-82** [comment]
Hi,

Adding the plugin for the webcam was really a great idea, but unfortunately it does not work as expected: the Windows 10 "camera" app does not detect Vysor's webcam at all.

I tried with Skype, but when the app tries to connect with Vysor's webcam, it crash and restarts.

The only app tried so far that can detect Vysor’s webcam, is Wathsapp Desktop: in fact, if I try to change the profile photo by selecting the webcam, Whatsapp correctly shows the image from my smartphone (the image is rotated 90 degrees and a little crushed on the sides, but it works).

I hope this great feature can improve in the future.

Thank you for your efforts.

Riccardo
