### ISSUE TITLE
Sound capture problems and Refund 

### ISSUE THREAD

**Issue by Legendarymarc22** [koush/vysor.io#644]
The other day I bought the full version of vysor, I asked for a refund, the same day I bought it, and they did not answer the mail. I asked for a refund because I captured the screen of the phone on PC, my phone can't be heard on the PC. So, I want a refund, since I send the mail within 24 hours, as it says on your support website. Another solution would be to fix the app so that the vysor program also captured the audio from the PC. There is also another program that captures the audio from the PC and I can share my android screen, and it is the Samsung flow. So please, I ask for a refund, since the app did not meet my expectations.

here I attach what the help support says: https://support.vysor.io/billing/refund/

please, if you can, check the e-mail.

I hope your prompt reply, have a good day

**Comment by koush** [comment]
checking email

**Comment by Legendarymarc22** [comment]
Hello, how are you?.  Since he has not responded to me for weeks, I want to
make a request for a refund of the product I bought, since it did not work
for me !!

the order ID is: ch_1HXxeLIX57f4SV6LMb4sLH6h
The number of receipt is: #1818-0495

**Comment by koush** [comment]
Cna you verify that the sound mirroring does not work with Android 10 mirroring enabled or disabled?

**Comment by Legendarymarc22** [comment]
Yes, I have tried both ways, and my Android is 10, so please ask for a
refund !!

**Comment by koush** [comment]
refunded

**Comment by bimaangkasa** [comment]
Hello koush, how are you hope your doing good :)
I have purchased a  Vysor Annual Subscription  (less than 24 hours) and I want to have refund of service as the product did not meet my expectation especially on Audio aspect.
please Reply, Let me know how to refund. :D
Thanks before :)

**Comment by bimaangkasa** [comment]
my email is : bimaangkasa17@gmail.com
hope you can check it
