### ISSUE TITLE
no puedo logearme con mi cuenta de Gmail

### ISSUE THREAD

**Issue by RichardBrick** [koush/vysor.io#647]
Cuando intento login con mi cuenta de Gmail me sale ese error. ya he intentado el Reset y el reload y nada, por favor su ayuda.

Gracias
 
![Vysor](https://user-images.githubusercontent.com/72847084/95942186-27e64000-0da8-11eb-876c-3f9af9d65847.PNG)

**Describe the bug**

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Vysor Version [e.g. 2.2.2]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
You are likely behind a firewall or something.
