### ISSUE TITLE
Vysor subscription not retrieved when G Suite domain changed

### ISSUE THREAD

**Issue by hbibkrim** [koush/vysor.io#648]
**Describe the bug**
I paid for a Vysor subscription through my G Suite account. My G Suite domain has since changed. Vysor cannot retrieve my licence as my email address has changed (through no fault of my own).

**To Reproduce**
1. Login to Vysor through G Suite.
2. Pay for a subscription.
3. Change the G Suite domain.
4. Login to Vysor through G Suite.
5. Vysor does not retrieve the subscription.

**Expected behavior**
Vysor retrieves my subscription.

**Comment by koush** [comment]
old/new emails?
