### ISSUE TITLE
apk path failed (empty)

### ISSUE THREAD

**Issue by algadel** [koush/vysor.io#649]
**Describe the bug**
Clicking 'view', Vysor try to install apk (Samsung Galaxy Note 10.1) and:
Error Connecting to Android Device
Error: apk path failed (empty)

1. Go to https://github.com/koush/vysor.io/releases
2. Download Vysor-linux-3.1.4-AppImage
3. Chmod on it
4. run Vysor
5. View
6. Error

The tablet Android version is 4.1.2., my hope was to see my tablet screen on my PC screen. 

![Captura de tela de 2020-10-16 11-31-36](https://user-images.githubusercontent.com/72983164/96271476-52501d00-0fa3-11eb-822f-cbe6383cda7a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Vysor Version [3.1.4]

**Android (please complete the following information):**
 - Device: Samsung Galaxy Note 10.1 (GT-N8000)
 - OS: Android 4.1.2
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/440073ac1a1603ffbe99e0e349552381#file-40aaca44-952a-40c1-a9ab-1fd1cf158ecb-txt

**Android Logcat**
I am not familiar with...

**Additional context**
Works fine for my S10. After install, uninstall ADB, and remove -> download -> try again many times, i am here. I found the same error here in a issue closed, but my device is not out of space...

**Comment by koush** [comment]
4.1.2 is not supported.

**Comment by algadel** [comment]
Thanks and sorry for the misunderstood.
