### ISSUE TITLE
Can't get Vysor Share working...

### ISSUE THREAD

**Issue by Littlelies** [koush/vysor.io#65]
It works fine on my computer linked with the device using USB.
Unfortunately, I can't make it work using Vysor Share...
I see the attempt to connect, but nothing more... Both computers are running 1.0.6.2 on top of Chrome 45.0.2454.93 and 45.0.2454.99 (64-bit)... Any idea what's wrong?

http://pastebin.com/bP1X3Wbd

Thank you for your app!

**Comment by Fanch-** [comment]
Same problem here !

**Comment by koush** [comment]
this should be fixed.
