### ISSUE TITLE
toggle audio works with all sounds on my phone but not specifically with the application I want

### ISSUE THREAD

**Issue by LordLegoshi** [koush/vysor.io#650]
When I use the audio mirroring of android 10 the sounds of all my phone work perfectly with all the games and actions that I do in it, but specifically in the game that I want to transmit "Brawl Stars" the audio mirroring does not work, I have tried other games of the company supercell and the audio works perfectly. but in fact with Brawl Stars if I play music at the same time that I open the game only the music plays and the game does not. I need help

**Comment by koush** [comment]
Some apps prevent audio capture or have not opted into audio capture on Android 10.

https://developer.android.com/guide/topics/media/playback-capture
