### ISSUE TITLE
Stuck on Waiting for decoder screen

### ISSUE THREAD

**Issue by usmatrica** [koush/vysor.io#651]
**Describe the bug**
I use vysor for mac, and it just show "Waiting for Decoder..." Screen, but i can control my phone from this screen nicely

**To Reproduce**
1. Connecting android phone to mac via usb
2. Click view on available devices
3. Wait and just see the "Waiting for Decoder..." Screen

**Expected behavior**
I have tried it on 2 devices, but both resulted stuck on "Waiting for Decoder...", its control working nicely but not showing my screen on vysor

**Screenshots**
![image](https://user-images.githubusercontent.com/72307887/96404569-d279bb00-120d-11eb-9c6d-5d7ffa905e32.png)

**Desktop (please complete the following information):**
 - OS: MacOs 10.13.6
 - Vysor Version 3.1.4

**Android (please complete the following information):**
 - Device: Asus Zenfone Max Pro M1
 - OS: Android 9
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/b75139d4fc185a3d8796693ce5c51a1e

**Comment by koush** [comment]
OS seems old. There's a graphic card error in the logs too. Try this https://support.vysor.io/technical/graphics/

**Comment by koush** [comment]
Alternatively, try the WebAssembly decoder.

**Comment by K76154** [comment]
How to do this on Linux? The provided link is Windows only.

**Comment by jurijp** [comment]
All of a sudden, (perhaps over the last week to 10 days) I have been getting the same message for 12 devices (LG Phoenix OS 8.1) that I am testing... waiting for decoder.  I am running Vysor on Ubuntu 16.04. Koush could you be a bit more prescriptive in your answers ? For example what is a WebAssembly decoder. ?
How would I use it ?  My system uses a Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by koush** [comment]
> All of a sudden, (perhaps over the last week to 10 days) I have been getting the same message for 12 devices (LG Phoenix OS 8.1) that I am testing... waiting for decoder. I am running Vysor on Ubuntu 16.04. Koush could you be a bit more prescriptive in your answers ? For example what is a WebAssembly decoder. ?
> How would I use it ? My system uses a Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

In the vysor mirroring window, go to the settings area by clicking the gear. Change the "Decoder" option to WebAssembly.

**Comment by koush** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/73924/108909596-98fcf600-75d9-11eb-8455-e54d0b5c1b66.png">
