### ISSUE TITLE
Display garbled randomly

### ISSUE THREAD

**Issue by ashish-jaywant** [koush/vysor.io#652]
**Describe the bug**
While navigating across screens, the display becomes garbled and is unusable.

**To Reproduce**
Start display mirroring on one of the connected phones and try to navigate and observe the garbled screen randomly. Workaround is to select another decoder from settings and switch back to the webAssembly one.

Desktop (please complete the following information):
OS: CentOS Linux release 7.6.1810 (Core)
Vysor Version: 3.2.27

Android (please complete the following information):
Device (Multiple) : Nokia 6 (TA-1021), Google Pixel (PVT)
OS: Android 8, Android 9
Vysor Bug Report Link: https://gist.github.com/VysorLogs/2c10a1a2f45d8145e5ff1d4f2097583f

**Comment by koush** [comment]
Can you try the WebAssembly decoder?

**Comment by ashish-jaywant** [comment]
> Can you try the WebAssembly decoder?

Using that already as none of the other decoders work for my environment.

**Comment by koush** [comment]
Can you share a screenshot of this garbled display? My guess is that the issue is WebGL, and/or a bad graphics driver.

**Comment by ashish-jaywant** [comment]
@koush attaching screenshot.
![image](https://user-images.githubusercontent.com/57110376/97011775-1a9e2380-1515-11eb-8749-46e6bccccc34.png)

**Comment by koush** [comment]
Yeah, Chrome apps are deprecated by Google. If you run a multiboot system, can you verify this issue also happens on the windows boot?
I suspect this is a graphic driver issue.
