### ISSUE TITLE
[Feature Request] Add VYSOR_TOGGLE_ALWAYS_ON_TOP event

### ISSUE THREAD

**Issue by npes87184** [koush/vysor.io#653]
I would like to add a button to trigger always on top in title bar. However, it lacks this event now. Can you please add this event.

Thanks.

**Comment by koush** [comment]
added in 3.2.28

sample button entry for Customize Vysor

```json
          {
            "class": "fa-thumbtack",
            "stopColor": "green",
            "title": "Toggle Always On Top",
            "event": "VYSOR_TOGGLE_ALWAYS_ON_TOP"
          },
```

**Comment by npes87184** [comment]
Does this event still work?

I tested it on 4.1.102, it does not work?
