### ISSUE TITLE
Screen won't go horizontal on MacOS window when using camera

### ISSUE THREAD

**Issue by crossmiles8** [koush/vysor.io#655]
Hey,

I've run into an issue. The window on MacOS will go horizontal when using the phone, but the second that you turn on the camera, it stays stuck in portrait mode on the computer, even if I have the phone set to landscape. This is the only reason why I purchased this app. Phone is a Samsung Galaxy S10.

**Comment by koush** [comment]
Camera apps are orientation locked, this can't be fixed by Vysor.

**Comment by crossmiles8** [comment]
Okay, please refund thank you.

**Comment by koush** [comment]
Use a camera app that is locked at a different rotation.

**Comment by crossmiles8** [comment]
So you're saying there are other apps where I may be able to use it
horizontally? I wasn't aware. I'm just using the standard samsung camera
app.

**Comment by koush** [comment]
yeah, try another one. most are usually locked in landscape mode.
you're mirroring your phone to your computer, and then capturing the screen for your youtube video? I don't understand why you don't just record straight to the phone.

**Comment by crossmiles8** [comment]
Siiick just got it working with Filmic Pro! Thank you for your help :)

**Comment by crossmiles8** [comment]
No no I'm recording directly to my phone but I wanna be able to see what
it's filming on the rear camera. The rear cam is much nicer than the front
facing camera. So I just wanna be able to see what I'm doing essentially.
Mirroring it to the computer is working great. Working solo here, otherwise
I'd just have someone do it for me lol.
