### ISSUE TITLE
Audio mirroring does not work on phones without Android 10

### ISSUE THREAD

**Issue by hohkfuyuhi** [koush/vysor.io#656]
I have a Razer Phone 2 that does not have access to Android 10, and audio mirroring is just broken for it. Vysor will display it as "Connecting", and then it completely disappears from the list of cast devices.

Will there be any fixes for this, or will audio mirroring for older devices be completely abandoned?

**Comment by koush** [comment]
Can you generate a bug report and also collect a logcat from the android device itself (the latter is a bit more complicated).

I just checked and the legacy mirroring support still works on my Pixel 4.

**Comment by hohkfuyuhi** [comment]
Here's the link to the bug report https://gist.github.com/VysorLogs/084249a40ca3ad5e487c6dc098b2e28f

Attached is the logcat
[logcat.txt](https://github.com/koush/vysor.io/files/5457761/logcat.txt)

**Comment by ihusky02** [comment]
I have simmilar issue, I have sound in my phone, but after click toggle audio, I don`t have sound on my PC. I have screen cast but on Xiaomi it`s only screen wireless.

**Comment by koush** [comment]
I'm closing this issue as won't fix, as the Chromecast emulation will eventually be deprecated as Android 10 rolls out. It is unreliable and undocumented, and requires wifi. Most users get a new phone every couple years, and my internal analytics show that Vysor users are switching to Android 10 devices fairly quickly.
