### ISSUE TITLE
No option to quit the app without killing process [UI, snap, KDE Plasma & GNOME]

### ISSUE THREAD

**Issue by geekley** [koush/vysor.io#657]
**Description of the bug**
There is no way to exit the vysor service without killing the process manually through task manager.
Clicking or right-clicking the icon on KDE Plasma doesn't do anything or show any options.
There is no quit button inside the home window.
Closing the window won't kill the service, of course, so there should be an option to exit somehow.

**To Reproduce**
1. Open Vysor (no exit button)
2. Close window (systray icon is still there)
3. Click or right-click that icon (nothing happens)

**Expected behavior**
At least a `QUIT VYSOR` button on home window. Or better, a context menu with this option on systray icon.
Also, left-clicking systray icon should open home window (might be double-click on GNOME).

**Desktop:**
 - OS: Kubuntu 20.04 amd64; Linux 5.4.0-52-generic
 - DE: KDE Plasma 5.18.5; also happens on GNOME 3.36.3
 - Vysor Version: `snap info vysor` = 3.1.4 (x1) 79MB jailmode

**Comment by koush** [comment]
This exists.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/73924/124988606-10fd1300-dff3-11eb-8779-ba5da082fe56.png">

**Comment by koush** [comment]
Note that the snap and app image no longer exist, and there is only a deb. The deb will put a icon in the tray.
