### ISSUE TITLE
Cannot connect device on different port in adb

### ISSUE THREAD

**Issue by n33470** [koush/vysor.io#658]
I cannot connect to a device in vysor when adb is not running on the standard, default, port of 5037.

On my PC, I cannot use port 5037 for the adb server.  I have configured adb to run on port 5555 instead.   This is done by setting an environment variable `ANDROID_ADB_SERVER_PORT` to that port.  I have a device successfully connected to the PC over USB and it shows up using 'adb devices'.  I am able to successfully use Android Studio to deploy and debug apps to that device connected on port 5555.

When I start vysor, it does not find that device.  I get the message at the top of the screen saying `No android device connected....`

From a command prompt, I can run 'adb devices' and the output shows the connected device.

Is there configuration for vysor to be configured to look for devices on a specific tcp port?

I'm running Vysor Pro 3.2.29 on Windows 10.   I have the android platform_tools version 30.0.4.

**Comment by n33470** [comment]
A vysor bug report can be found here: https://gist.github.com/688935f965a270e1751dc6439c9a6c37

**Comment by koush** [comment]
At the moment it requires the default port. I will reevaluate this as a part of a feature supporting other adb addresses.
