### ISSUE TITLE
[Feature request] Make screen completely blank on phone while using Vysor

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#659]
This is a kind feature request:

Please allow an option to make the screen completely black (but not turned off) while using Vysor.
This seems to be possible like scrcpy implemented it here https://github.com/Genymobile/scrcpy/issues/175#issuecomment-473412085

The way scrcpy implemented this is that the screen is 100% blank but still responds to touch events so the digitizer and rendering is still happening, it's just not visible on the phone's screen.

This is will be great for battery life, screen burn in and privacy.

Thank you.

**Comment by dieskim** [comment]
Second this - would be great to have

**Comment by clubtech** [comment]
Bump on this.
Any chance to implement this into Vysor? scrcpy and Wormhole do this but Vysor is the superior product of both, and adding this would make it perfect.

**Comment by koush** [comment]
@clubtech I’ll need to reinvestigate, because when I checked a long time ago, screen off disabled rendering. I got around this by adding the “Dim Display” option which turns screen brightness to the lowest setting. You can use that in the meantime, and I’ll reinvestigate fully turning the screen off— it’s been like 5 years since I last tried it, and I’m sure things have changed.

**Comment by koush** [comment]
Taking a look this weekend.

**Comment by clubtech** [comment]
@koush, thank you very much for taking another look. Yes at the moment I'm using the dim display option.
It seems that both scrcpy and Wormhole (er.run) are using the same method, where the screen is completely black but the digitizer on the screen is still working (if I touch the screen I can see it clicks and swipe). 
It also looks like both have auto brightness set to auto as I can see the auto brightness slider changes on the phone with the room lighting while the screen stays completely black.

I think the link I posted for the scrcpy GitHub explains how they did it. https://github.com/Genymobile/scrcpy/issues/175#issuecomment-473412085

**Comment by clubtech** [comment]
One more thing: Both scrcpy and Wormhole have the mirrored display on the PC never time out when this blank screen option is enabled which improves usability without draining a lot more battery (as the phone screen remains black while the displayed screen does not get turned off).

**Comment by koush** [comment]
Oh great, thanks. That's actually the method I initially tried-- and that turned off screen rendering too. It seems Android no longer does that.

**Comment by koush** [comment]
@clubtech the change is live in 3.2.31.

<img width="631" alt="Pixel_4" src="https://user-images.githubusercontent.com/73924/101999438-f5669f80-3c91-11eb-8d56-a2ef3cb82587.png">

**Comment by clubtech** [comment]
Thank you so much @koush . It works!
Can you maybe have the display set to never timeout when connecting with the "Turn Off Display" option selected (and release the timeout to be whatever it was before when disconnecting from the device)?

The reason is, every time the screen will time out (my default phone setting is to turn off the screen after 30 seconds) and I wake the screen, the screen on the phone will be on again until I disconnect and reconnect Vysor again.

Alternatively you can set the display to turn off again once the device is being woken again after the default display sleep timeout.

Hopefully this makes sense.

**Comment by koush** [comment]
@clubtech if i recall, there’s already a built in android setting to do this. something about leaving screen on while connected to power. or disabing the screen timeout. Let me dig around and find it.

**Comment by koush** [comment]
![screenshot-1607818944641](https://user-images.githubusercontent.com/73924/101999888-3c569400-3c96-11eb-96b5-ea7e4c58e77d.jpg)

Yeah, here it is.

**Comment by koush** [comment]
Closing this issue, opened a new feature to track the screen awake lock.

**Comment by npes87184** [comment]
Hi, @koush 

I like this feature. However, everytime I start vysor, I need to open setting and change the display power.
Is it possible to add an event like VYSOR_TURN_OFF_DISPLAY? After that, I can add a button on title bar to trigger this?

Thanks.

**Comment by koush** [comment]
> Hi, @koush
> 
> I like this feature. However, everytime I start vysor, I need to open setting and change the display power.
> Is it possible to add an event like VYSOR_TURN_OFF_DISPLAY? After that, I can add a button on title bar to trigger this.
> 
> Thanks.

It should automatically turn off the power upon connection to Vysor, is this not happening? Is the setting not saving?

**Comment by koush** [comment]
@npes87184 
> Hi, @koush
> 
> I like this feature. However, everytime I start vysor, I need to open setting and change the display power.
> Is it possible to add an event like VYSOR_TURN_OFF_DISPLAY? After that, I can add a button on title bar to trigger this.
> 
> Thanks.

It should automatically turn off the power upon connection to Vysor, is this not happening? Is the setting not saving?

**Comment by npes87184** [comment]
Hi, @koush 

Thank you for your reply. My case is that, I will turn screen off by clicking power button. The next time, I tune on my screen by clicking power button again. The screen will be on-state.

Thanks.

**Comment by clubtech** [comment]
@koush hence why I suggested you make the screen not timeout when the "Turn Off Display" option is selected per issue #669 .

Right now, when this new option is used, the screen on the phone will timeout to whatever the timeout setting on the phone is (normally 30 seconds or 1 minute) and once the user presses the power button or Vysor wakes up the phone from sleep by hovering with mouse over Vysor, the screen will turn on the phone screen (and Vysor) and will not be blank the phone screen again.

The only way to prevent this situation is to make sure that once the "turn off display" feature works as intended is either make the screen on the phone never timeout while Vysor is connected or have Vysor blank the phone's screen every time the power button is used or Vysor is waking the phone from sleep.

Right now I have Tasker setup to recognize when Vysor is connected, change the screen timeout to 5 hours and set it back to default when Vysor disconnects and now it works as intended.

Thanks.

**Comment by koush** [comment]
I see. I thought I had code in there to blank the screen every tike the phone windows is focused (rather than a timeout). I’ll check and make sure that’s working properly.

**Comment by npes87184** [comment]
Hi, @clubtech 

> @koush hence why I suggested you make the screen not timeout when the "Turn Off Display" option is selected per issue #669 .
> 
> Right now, when this new option is used, the screen on the phone will timeout to whatever the timeout setting on the phone is (normally 30 seconds or 1 minute) and once the user presses the power button or Vysor wakes up the phone from sleep by hovering with mouse over Vysor, the screen will turn on the phone screen (and Vysor) and will not be blank the phone screen again.
> 
> The only way to prevent this situation is to make sure that once the "turn off display" feature works as intended is either make the screen on the phone never timeout while Vysor is connected or have Vysor blank the phone's screen every time the power button is used or Vysor is waking the phone from sleep.
> 
> Right now I have Tasker setup to recognize when Vysor is connected, change the screen timeout to 5 hours and set it back to default when Vysor disconnects and now it works as intended.

Very interesting thing! If possible, can you share how to detect the connection state of Vysor using tasker? I want to turn off auto-rotate screen after disconnecting phone.

Thank you for your sharing.

> 
> Thanks.

Hi, @koush 

> I see. I thought I had code in there to blank the screen every tike the phone windows is focused (rather than a timeout). I’ll check and make sure that’s working properly.

Thank you for your help!

**Comment by Yaniv-Aviran** [comment]
This feature stopped working on Android 14
