### ISSUE TITLE
Vysor automatically uninstalls and fails to connect

### ISSUE THREAD

**Issue by Mair** [koush/vysor.io#660]
**Describe the bug**
Android application fails to connect and uninstalls automatically 
"Error: apk path failed (empty)

**To Reproduce**
1. brand new phone setup
2. activated developer options
3. enabled USB Debugging
4. enabled USB debugging (Security Settings)
5. installed Vysor on windows 10
5. installed ADB drivers
6. Connect phone via USB
7. Error : apk path failed (empty)
8. App is automatically removed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor: Version latest from install

**Android (please complete the following information):**
POCO X3 
Android version 10 QKQ1.200512.002
MUI 12.0.1

**Comment by koush** [comment]
Try installing this app manually. Something seems odd about your setup in that it's not installing the apk.

https://github.com/koush/release/blob/master/Vysor-release.apk

**Comment by sidazhou** [comment]
Had same problem on Mac, manual install worked.
