### ISSUE TITLE
Multitouch support is broken

### ISSUE THREAD

**Issue by cee-dee** [koush/vysor.io#661]
Multitouch pinch gestures do not work in any app except Google Photos. Even in Google Photos multitouch events behave not as one would expect when trying to apply larges zoom ratios.

**Reproduction:**
1. Open any other application, e.g. Google Maps.
2. Set the first by holding the alt-key and clicking somewhere.
3. Release the alt key, move the mouse a bit
4. left-click and hold down the the mouse key, move the mouse to apply the pinch gesture

Result:
The map moves, no zoom happens.

**Expected behavior:**
A zoom occurs as expected due to a pinch gesture.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version 3.2.30

**Android (please complete the following information):**
 - Device: Nexus 5X
 - OS: Android 8.10

**Comment by koush** [comment]
Will investigate.

**Comment by koush** [comment]
Have confirmed this works on Photos app. Seems the bug is exclusive to some apps that detect gestures differently.

**Comment by cee-dee** [comment]
Why have you added the "can't fix" label?

I'd like to see it the other way around: is there any other app except Google Photos where it DOES work? -- for Google Maps it doesn't work, also for other apps I've tried, it didn't work...

**Comment by koush** [comment]
Because when I last investigated, it's not possible to fix. I'll need to reinvestigate to see if there's a way to synthesize touch events that gets interpreted properly.

**Comment by mmta** [comment]
@koush since the last 2 or so updates (couldn't verify exactly when since I don't know where the old windows binaries are to test them), the zoom-in/out operation starting point is way off to the top-left of where the mouse pointer is on the Win10 app. I have tested this on Google Photos as well.

Let me know if I should start another issue for this.

**Comment by koush** [comment]
@mmta yes please open another report and i’ll investigate, there were some changes to the touch code for iOS and i might have broken something.

**Comment by koush** [comment]
@mmta I found the bug and fixed it. That said, this original bug is different and still not fixed.
I confirmed multitouch worked in Google Photos.

**Comment by koush** [comment]
Found and fixed other bugs where mulitouch input was not being translated into screen coordinates.
