### ISSUE TITLE
No devices on latest desktop version

### ISSUE THREAD

**Issue by MBoberski** [koush/vysor.io#662]
**Describe the bug**
Vysor after latest update stops showing any android device connected. CHrome version have no problem with it an connect properly. No USB devices, also wifi connection not working.

![image](https://user-images.githubusercontent.com/2800036/99196608-c988f480-278d-11eb-834e-42256a0e608d.png)

**To Reproduce**
Connect device via USB
Not see it in Vysor

**Expected behavior**
Mirrod android device as before

**Desktop (please complete the following information):**
 - OS: Win10
 - Vysor Version: 3.2.30

**Android (please complete the following information):**
 - Device: Xiaomi mi 9
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/b603a3ad6d521ca81bb7b384b876dac6

**Comment by koush** [comment]
You may want to try restarting or something. It can't start the adb binary for some reason.

**Comment by koush** [comment]
No response.
