### ISSUE TITLE
Android screen mirroring disconnected after 1-2 minutes

### ISSUE THREAD

**Issue by phurinatp** [koush/vysor.io#665]
**Describe the bug**
I use Redmi 9 when I go to some application such as Setting, Bank, Chrome, etc. mirroring disconnected will appear. But if I stay at the home screen, Popup doesn't appear.

**To Reproduce**
1. Launch Vysor on desktop
2. Plug in device using usb-c cable
3. Go to some application (such as Setting, Google Chrome, Mobile Banking etc.)
4. wait around 1-2 minute
5. See Mirroring Disconnected error popup

**Expected behavior**
Mirroring disconnected popup should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/53590627/99755974-a3ad7800-2b1e-11eb-970e-19d582b870de.png)

and this is my setting.
![image](https://user-images.githubusercontent.com/53590627/99756370-93e26380-2b1f-11eb-8841-d50bdbaab235.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Vysor Version Pro 3.2.30

**Android (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 10

**Comment by koush** [comment]
attach a bug report of the disconnect.

**Comment by phurinatp** [comment]
Bug Report : https://gist.github.com/VysorLogs/8aafc5a345cd32d5c10d392263cd1228

**Comment by koush** [comment]
Does this only happen on the redmi?
The error seems really odd, it looks like the adb connection is leaking protocol data somehow.
>org.json.JSONException: Value AUTH of type java.lang.String cannot be converted to JSONObject

**Comment by phurinatp** [comment]
Not only Redmi. It's also happened on Samsung One UI 2 (Android version: 10).

**Comment by koush** [comment]
Please try a different USB port and don't use a hub.

**Comment by phurinatp** [comment]
I tried with a different USB port and with another computer. It still doesn't work.

**Comment by m2kk** [comment]
Unfortunately I'm having the same issue like the complete year. Though about my USB hub, replaced it. Having a new one now. Same issue. Seems to not (regularly?) happen on direct USB-C to USB-C connection, but keeps occurring with anything doing USB-A to USB-C. Can this be?

**Comment by koush** [comment]
Is this still happening? Have never seen it. Suspect it is a buggy adb client or server on the pc or phone.

**Comment by m2kk** [comment]
At least to me, subjectively, updating to max osx big sur11.1 and 11.2 seams to have resolved that issue. Possibly also having a new phone now. So alternatively it must have been related to my huawei p30.
I think it's the os update (had the old phone some time with 11.1)did work
