### ISSUE TITLE
Screen stays black on Onyx Boox Note Air

### ISSUE THREAD

**Issue by Konachan** [koush/vysor.io#666]
**Describe the bug**
If I connect my Onyx Boox Note Air with USB, only a black Screen is shown on my PC. Clicking in the black screen controls the device. The device uses an E-Ink Screen (I don't know if E-Ink screens use a different buffer to write to).
I also **tested Vysor on the same PC with my Phone** (Samsung Galaxy Note 8) which **works fine**.

**Attach a Vysor Bug Report Log**
~~https://gist.github.com/90549c995321bb61637c437ab44c1233~~
https://gist.github.com/VysorLogs/5b40bce40ea49b8c1190c3c640f68eea

**To Reproduce**
1. Install Vysor via the appimage
2. Connect Vysor as described in the manual (Enable USB-Debugging, Connect Device, Allow USB-Debuging for PC....)
3. Start screen casting

**Expected behavior**
Same behavior as with my phone (visible screen).

**Screenshots**
x

**Desktop:**
 - OS: Linux, Manjaro
 - Vysor Version: 3.2.30

**Android (please complete the following information):**
 - Device: Onyx Boox Note Air
 - OS: 10
 - Vysor Bug Report Link: ~~https://gist.github.com/90549c995321bb61637c437ab44c1233~~ https://gist.github.com/VysorLogs/5b40bce40ea49b8c1190c3c640f68eea
**Android Logcat**
x

**Additional context**
x

**Comment by koush** [comment]
Need a bug report that contains the error. Leave any blank windows open and such.

**Comment by Konachan** [comment]
Sorry, I might have accidentally closed the window. Here's a new one. But it doesn't look like there's a related error.
https://gist.github.com/VysorLogs/5b40bce40ea49b8c1190c3c640f68eea

**Comment by koush** [comment]
My guess is that the e-ink display is not the primary display, and that's why it's coming up black. I was hoping there was an easy bug to fix, but since I don't see anything odd the in the log, I'm going to punt on this bug. It's not a common use case.

I may revisit it in the future as multiple display devices become more common.
