### ISSUE TITLE
Send control characters in Vysor

### ISSUE THREAD

**Issue by danerwin1** [koush/vysor.io#667]
Hi, I am using emacs in Termux, an Android app that runs linux.  emacs makes extensive use of control characters, but these don't appear to be mapped by Vysor.  I have tried things like adding to the keydown table
    "ControlLeft": "KEYCODE_CTRL_LEFT",
    "ControlRight": "KEYCODE_CTRL_RIGHT",
but with no success.
Is there a way to do this?
Thanks, Dan

**Comment by koush** [comment]
I was using KeyboardEvent.key and .keyCOde rather than .code. This should be fixed in 4.0.25.
