### ISSUE TITLE
Share devices 

### ISSUE THREAD

**Issue by bas321** [koush/vysor.io#668]
**Describe the bug**

- The problem is when i click share all devices , when i open vysor on my other computer i do not see the device shared.
This worked 4 days ago but seems like it is not working anymore. Only when i use google chrome browser i can still see it.
But i don't want to use chrome browser just want to view shared with the normal program like it was doing 4 days ago.

**Attach a Vysor Bug Report Log**
id: 105511539944395586168

**To Reproduce**
1. Open vysor, connect device on pc 1
2. Press share all devices + share button next to the view button.
3. go to pc 2 and open vysor logged in on same account, can not see shared device.
4. when open chrome browser using share link i can see the device. when it ask open with vysor program? it does not do anything. please take a look at the screenshot here below.
5. i have tried reload vysor and reset vysor + reinstall vysor it was working few days ago.

**Expected behavior**
I expect it to be able to view shared devices on vysor program instead of only in chrome browser.

**Screenshots**
[https://ibb.co/QDtLmYK](url)

**Desktop (please complete the following information):**
- Windows 10
 - Vysor Version [3.2.30]

**Android (please complete the following information):**
 - Device: Umidigi A3 Pro
 - OS: Android 8.1
 - Vysor Bug Report Link: [https://gist.github.com/VysorLogs/c7374142b940ace4d44e4d6bdc938f58]

**Comment by koush** [comment]
This bug report doesn't have the relevant information in it. Did you leave the Vysor windows open when generating the bug report?
