### ISSUE TITLE
Samsung Galaxy Express (GT-I8730) (JellyBean 4.1.2): Completely defunct

### ISSUE THREAD

**Issue by 2ion** [koush/vysor.io#67]
The desktop application fails with the notification: Your Android screen is currently not available. A reboot may fix the problem – I have rebooted, switched between USB MTP/PTP modes to no avail. USB debugging is enabled.

When attempting to connect though, on the phone itself Vysor notifies that the device is connected. No idea about the Hmmm part though:

![screenshot_2015-09-30-18-45-39](https://cloud.githubusercontent.com/assets/666784/10200101/b1a403c2-67a4-11e5-8e42-e3a8d1554a74.png)

Other adb workflows work fine without problems.

Please let me know how to provide useful debug information.

What native components/dependencies are required by Vysor to work? Admittedly this phone is rooted, and almost all com.samsung.* packages are removed. It's possible that Samsung had substituted something for a Google/Android screensharing service or something.

**Comment by kchacon** [comment]
Hi 2ion,

I have the same problem, could you solve it????

I hope you can help me

Thanks in advance!

**Comment by 2ion** [comment]
No, this is still the status quo.

**Comment by tsdmgz** [comment]
Also failing on Samsung Galaxy Win (GT-i8552), also on 4.1.2 rooted.
Logcat here https://gist.github.com/tsdmgz/5fbc4e067f681016d2442dcfdd1e0649
