### ISSUE TITLE
Help Wanted: ADB Connect Failed

### ISSUE THREAD

**Issue by annielaurie2** [koush/vysor.io#671]
After setting up Vysor Enterprise on MacBook Pro to remote in and control Fire 10 tablet, was able to control when wired, and wirelessly on the same network. Now trying to control from outside the tablet Network and not recognizing the tablet. message is "ADB Connect failed: failed to resolve host 'undefined': nodename nor servname provided, or not known"

I'm hoping it's because I've missed some step that will allow wireless control from different network? Otherwise will have to cancel the subscription. Look forward to hearing a resolution, thanks!

**Comment by koush** [comment]
You can use Vysor Share to connect over different networks.
