### ISSUE TITLE
Hangs at installing APK

### ISSUE THREAD

**Issue by raffaem** [koush/vysor.io#673]
**Describe the bug**
I connected my tablet via USB. The tablet had the Android application Vysor installed from the store. I then connect to the web app from my PC. The web app uninstalled the app from my tablet, telling me it was out of date (I had just installed it). It then hangs at "Installing APK". The installation of the new APK never finishes. It freezes.

**Attach a Vysor Bug Report Log**
I don't know what "main device window" is. I suppose it is the one after the device is successfully connected

**To Reproduce**
See above

**Expected behavior**
The installation of the APK should finish. I also don't get why it tells me the current APK is out of date if I have just installed it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS] Kubuntu 20.10
 - Vysor Version [e.g. 2.2.2] Web app as of 16th December 2020

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4] Galaxy Tab S4
 - OS: [e.g. Android 10] Android 10
 - Vysor Bug Report Link: I don't know how to generate this.

**Android Logcat**
Not familiar with it

**Comment by koush** [comment]
please fill out the bug report properly. you need to generate bug report using the bug report button in the main device list.

**Comment by raffaem** [comment]
What is the "main device list"?
What is the "main device"? The PC? The Tablet?
