### ISSUE TITLE
Audio issue Vysor

### ISSUE THREAD

**Issue by DenzyL2020** [koush/vysor.io#674]
I have a problem.
When scroll down to see notifications and hold the cast button my pc doesn't show up so I can't record with microphone audio.
Any advices and problem solvers?

**Comment by koush** [comment]
I'm closing this issue as won't fix, as the Chromecast emulation will eventually be deprecated as Android 10 rolls out. It is unreliable and undocumented, and requires wifi. Most users get a new phone every couple years, and my internal analytics show that Vysor users are switching to Android 10 devices fairly quickly.

Please use the Android 10 mirroring option if you are on Android 10.
