### ISSUE TITLE
Warn users about caveats before buying pro version to avoid bad reputation

### ISSUE THREAD

**Issue by mauvilsa** [koush/vysor.io#675]
Overall I think this is a nice project, good work! However, something missing that I think it is very important is that in the web site and more importantly when buying the pro version, there is a clear message about things that don't work. I bought the pro version with several expectations, to then realize that several of the features I wanted did not work. Because of this it felt kind of a scam. Then I saw some messages in the github issues saying about not getting refunds. I haven't tried to get a refund since I will use other features that do work for me, so I don't know if there are any issues with refunds. But I strongly advice you that a clear message is given before paying so that it is transparent for the users and this project does not get a bad reputation.

A couple of things that I expected that should be mentioned:

- Video playback for some apps does not work because of DRM, i.e, Netflix https://github.com/koush/vysor.io/issues/232
- There are issues with audio, in particular for android < 10.

Regarding the audio, my particular situation is that I have only one mobile device with android 7 and I am using it as a hotspot to share internet with my laptop where I want to use Vysor. I don't have cable internet or an independent WiFi router. Even though I saw some comments that it is possible to use cast with a device being the hotspot, I did not manage to do it.

**Comment by koush** [comment]
The free version is there for people to test. The DRM playback issue is not meant to be “scammy”, and would be discovered while using the free version. There’s also a few issues that document this. In any case, I’ll add it to a caveat list.

As for audio, I do agree there needs to be a way to “try before you buy” like you can with video. Maybe I’ll do 1 minute of sampling before it cuts out.

**Comment by koush** [comment]
I understand the sentiment that it feels like I’m trying to hide somethig, but I’m not. Balancing free vs pro features is tricky, and creating trials for every pro feature can be time consuming..

**Comment by mauvilsa** [comment]
Certainly it would be nice to have a way to try before you buy for all pro features. But even with this, it is more transparent for the users to see a least of caveats. To have happy customers expectation management is important, so being transparent is always good. Also note that even if you can try before you buy, users might not notice things that will not work. With the free version I tested with youtube and assumed it would work for any video. I only realized about the DRM because I am a developer and quite used to searching for issues in github projects.

**Comment by Siress** [comment]
I completely agree with Mauvilsa. Using the free version within a limited time frame is not validation of all features for all use cases - it's simply a trial run for the immediately apparent use case, and undoubtedly omits many activities that are expected to work the same as they always have on the native device(s). Basically, there should be a warning any time this mirroring application is not actually able to mirror from a native Android device; regardless of the I/O. 

That said, I'm not upset over my purchase - just disappointed in the lack of functionality and (therefore) value. For my use cases, there's freeware now that has the same functionality as the pro version of Vysor.

**Comment by koush** [comment]
@Siress there is no way to detect if there’s DRM content on the screen as far as I know.

**Comment by koush** [comment]
@Siress what functionally is lacking? I’m open to feature requests.

**Comment by koush** [comment]
For what it’s worth, I’m about to release iOS support. It’s a major update (and a lot of work!). That may not be your use case, but value is still being added to the program, even if you’re not utilizing it.

**Comment by Siress** [comment]
> @Siress what functionally is lacking? I’m open to feature requests.

Ok, but keep in mind this is user feedback and has not basis in what is supported by any API at this time. In no particular order:
- Audio pass-through for all Android versions. Or at least back to 6.0, since that'll cover >90% of users per [sauce](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide). 
- 100% mirroring / pass-thru (all of it...yes, that too...especially that...)
- LAN autofind without USB connection.
- Do not require USB debugging as leaving it on presents a serious vulnerability on the Android device. It would be fine to use it just for the initial setup. I'd be content with a background app on the device to get around this issue if said background app is FOSS, and does not present the same or worse vulnerability.
- Better mouse support - sometimes apps are really strange about mouse clicks instead of taps... probably something in those apps, but still...anyway to mimic a finger tap on mouse click or something?
-

**Comment by koush** [comment]
gotcha. these are all things i’ve considered and investigated. but just for the record:

* audio pass through is currently supported to previous android versions via reverse engineering the chromecast APIs… it is unreliable though (and needs wifi). There are no hidden APIs to do it either. android 10 is when the official api was added.
* bypassing drm: not possible to do. it’s DRM. you can’t even screenshot it. if you could bypass it, it wouldn’t be very good DRM.
* if adb has been enabled for tcp (and the device was not rebooted), this could be done.
* don’t require adb: this is possible, and something i’ve been planning on doing actually. there are limitations but with a usb connection mirroring and control, at a minimum, can be done. some of the more advanced features that require shell permissions would need to be disabled (like screen power, wifi connection, etc).
* mouse - will investigate. there’s multitouch issues. will need to try sending different pointer event types.

**Comment by Siress** [comment]
Thanks for the response.

>     * audio pass through is currently supported to previous android versions via reverse engineering the chromecast APIs… it is unreliable though (and needs wifi). There are no hidden APIs to do it either. android 10 is when the official api was added.

I'm out of my depth, but I recall AppRadio Unchained having mirrored audio. In the early years it required a slimport connection, then miracast, but finally it was completely wireless over chromecast. Maybe there's something the dev for it can help you around.

**Comment by koush** [comment]
> 
> I'm out of my depth, but I recall AppRadio Unchained having mirrored audio. In the early years it required a slimport connection, then miracast, but finally it was completely wireless over chromecast. Maybe there's something the dev for it can help you around. Then agian, that app was difficult to setup... not something you want for a general solution. Sounds like you may have already seen the skeletons in that particular closet.

AppRadio and Vysor seem to use the same Chromecast emulation method. I imagine they need wifi, because it’s not possible to emulate a chromecast unless wifi is active and connected.

**Comment by dieskim** [comment]
I just want to come support @koush here - I have been using free and then paid for a while, its an amazing product and the price is really cheap so I dont think there is much to complain about. The free version was more than good enough for most people to see what its like, Paid is amazing for the price. Great Job!

**Comment by mauvilsa** [comment]
I hope that it is clear that I created this issue with good intentions just as a recommendation for @koush to be less likely to have unhappy customers. As I said initially I think it is a nice project, I am using it and I think the price is fair. The suggestion is so that for other people it does not happen the same as me, to have expectations that later are not met with the pro version. @dieskim wasn't it clear what the intention of the issue was?

**Comment by koush** [comment]
@mauvilsa i appreciate the feedback
@dieskim thanks for the support

I’ll be adding a different trial model that accomodates more exploration of the features.

**Comment by koush** [comment]
> I completely agree with Mauvilsa. Using the free version within a limited time frame is not validation of all features for all use cases 

Just to clarify, there is no trial period, you can use the free version indefinitely if you want. Lots of people do that.
