### ISSUE TITLE
iOS aspect-ratio (sometimes) skewed when navigation bar visible

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#677]
Firstly, iOS support was a very nice surprise when I saw it pop-up today. Very nice! This makes handling iOS devices / screenshots / videos much simpler than QuickTime, and the IO input is the first time I've ever seen this kind of thing possible in a simple process.

There's a slight bug if you enable to navigation bar on an iPhone 11 / 12 Pro Max device that only occurs sometimes: the forced aspect-ratio doesn't take into account this extra height, so you end up with an incorrectly-scaled iPhone display output. I couldn't quite figure out the pattern, as I managed to make it go away through a series of toggles and restarts however.

macOS 11.1
Vysor 4.0.7

**Comment by koush** [comment]
I'll take a look. Does it resolve itself on open/close of the window?

**Comment by koush** [comment]
Also, does it happen on Android?

**Comment by crouchingtiger** [comment]
I can't reproduce it any longer (most likely because of the device config saved somewhere). I can try wiping out the preferences if you give me a proper way to wipe everything?

Doesn't (never) occurred on my Pixel 2 / 3 XL Android devices.

**Comment by koush** [comment]
In the device settings, there's a Defaults button that wipes all internally stored configuration for that device.

**Comment by crouchingtiger** [comment]
Thanks - tried it, but looks to be working fine. Strangely, a random Bluetooth device name was listed in the instructions text rather than the name for my machine set in System Prefs > Sharing. I can add a separate issue for that if you like? This one I'll close.

**Comment by koush** [comment]
@crouchingtiger I'm aware of that bug and it has to do with it using the hostname vs computer name. Go ahead and open it so I can track.
