### ISSUE TITLE
bad image quality

### ISSUE THREAD

**Issue by mecheverry** [koush/vysor.io#68]
My connection with Vysor works fine, and I can control the device correctly with my PC mouse and keyboard.

But the image quality is not ok, for example on a 7 inch tablet I get a horrible image quality on portrait mode, and a bad quality on landscape mode.

Example: Tablet portrait (image quality very bad)
![1](https://cloud.githubusercontent.com/assets/14914666/10206541/0a5007fe-678d-11e5-9581-14861fbef9e9.jpg)

Example: Same Tablet landscape (image a little less bad but poor quality)
![2](https://cloud.githubusercontent.com/assets/14914666/10206556/29ff8390-678d-11e5-801f-a8a1d0fcafac.jpg)

If I switch to another device like a Moto G first gen, I get an OK almost perfect quality image in portrait mode and a very bad quality image on landscape mode.

Example: Moto G portrait (good image quality)
![3](https://cloud.githubusercontent.com/assets/14914666/10206587/51fd29f6-678d-11e5-94ad-88947cc9529c.jpg)

Example: same Moto G landscape (bad image quiality)
![4](https://cloud.githubusercontent.com/assets/14914666/10206603/6629f44a-678d-11e5-8134-a052fc7c6fe8.jpg)

OS: Windows 7
Vysor version: 1.0.6.2
Chrome version: 45.0.2454.101 m

**Comment by kizer8** [comment]
I get the same bad image quality when using with my G box Q android TV, I would love to figure out how to make the quality better.

**Comment by koush** [comment]
What android versions?

**Comment by kizer8** [comment]
my G box Q android TV is running 4.4.2

**Comment by mecheverry** [comment]
In my case, both moto g and tablet are Lollipop. The moto g is a 5.1 google play edition, the tablet have a 5.1.1 android version. 

Hope this information helps

**Comment by ArgusP** [comment]
Also here. Samsung Galaxy Note II stock android 4.4.2. Picture quality is better whan there is less details on the screen (maybe issue with bandwith?).

**Comment by jebeld17** [comment]
Same here. I'm running everything correctly with the official HTC drivers installed and using the official HTC USB cable that came with my device. HTC One M9.

**Comment by Slicemage** [comment]
+1

Experiencing this as well on a Nexus 7 (2012). Connection works great, but the image quality is poor, especially in landscape mode.

**Comment by badhorky** [comment]
I also have poor image quality in Landscape mode, 1st gen. Moto G, Android 5.1.1.

**Comment by spekkiomofw** [comment]
Same issue in landscape mode. Samsung Galaxy Avant. Everything up-to-date.

![screenshot 2015-11-22 at 2 41 52 am](https://cloud.githubusercontent.com/assets/15350933/11322616/bf888ba6-90c2-11e5-8d11-ccaa49a5ad05.png)

**Comment by steckdev** [comment]
Great find on this badhorky!!! THANKS! I was able to work around the issue by just keeping the app up and just unplug-replug it in! Hopefully a fix is on the way.

**Comment by macgg** [comment]
image quality is too bad on my retina Macbook Pro, no matter horizontal or vertical mobile screen

Amazon Fire phone, android 4.4.4, 720*1280.
<img width="804" alt="screen shot 2016-01-20 at 4 57 39 pm" src="https://cloud.githubusercontent.com/assets/16809241/12468331/73742528-bf97-11e5-895c-ee428b66a99c.png">

**Comment by igordeoliveirasa** [comment]
This is the best app, however I got a bad resolution too. My device is a LG Leon.

**Comment by EDJY2016** [comment]
I originally had a USB hub in between my device and PC.  When I connected direct to the PC the image improved.  Still a bit blurry but definitely better.

**Comment by jdecock2403** [comment]
Any update on this issue?  It works fine on my Samsung Galaxy Tab 4 (Android 5.1.1), but my Samsung Galaxy Tab 3 (Android 4.2.2) has poor resolution.

**Comment by jpluimers** [comment]
Same issue here. Portrait/Landscape doesn't matter. 
This is on a OnePlusTwo (latest software) and a USB connection to a Retina MacBook Air using Chrome (latest version).
Within Vysor: https://www.dropbox.com/s/si5nuczbr6pu0hm/Screenshot%202016-02-17%2019.14.31.png?raw=1
Android Screenshot: https://goo.gl/photos/sopKahBDiL4sbagk7
The odd thing is that this worked fine in the past on my then OnePlus-One: http://wiert.me/2015/08/25/cool-vysor-screen-sharing-by-koush/

**Comment by jthurston** [comment]
Samsung Galaxy Note 4 Android 4.4.2
I have the issue in landscape and portrait...really appreciate this app but cannot use to demo to customer at this point.
![vysor__beta_](https://cloud.githubusercontent.com/assets/22991/13357426/339bb72e-dc78-11e5-99de-bd88afe1a071.png)

**Comment by scorpiodawg** [comment]
I have this same issue on my Windows 10 Asus laptop (resolution of 1366x768), connected to an LG Leon LTE device. 

![vysor capture](https://cloud.githubusercontent.com/assets/2002884/13762628/62496642-e9fd-11e5-89a9-5e9374ebabb3.PNG)

When I hit the tiny screenshot button (that pulls the current screen and shows it in my browser), that image looks fine.

![vysor screenshot via browser](https://cloud.githubusercontent.com/assets/2002884/13762652/9ccbfd48-e9fd-11e5-94a4-47dbe6347ba0.PNG)

**Comment by old-days** [comment]
Bump, have the problem as well Xperia M C1905 - Android 4.3

![untitled](https://cloud.githubusercontent.com/assets/18369055/14405508/cb9d8ed2-fec2-11e5-9782-65108dd579a1.png)

**Comment by zhihuitang** [comment]
there is any plan to improve the resolution?

**Comment by amsilvestre** [comment]
Same Here. On Nexus 5 image is ok. On LG tablet, resolution is terrible.

**Comment by sgeraldes** [comment]
Why is the issue closed? There has been no resolution to this issue that I can see..

I have the same issue on devices:
- Samsung Galaxy Note 10.1
- LG G3
- Moto G, second gen
- LG Optimus

I paid for the pro version, and not getting anything out of it. There is no link, contact info, help, or any way to get support.

**Comment by koush** [comment]
![vysor](https://cloud.githubusercontent.com/assets/73924/16355599/517fb604-3a70-11e6-9ca2-00862981878b.png)

**Comment by hub2git** [comment]
Clicking the "Support" link takes us to https://plus.google.com/110558071969009568835/posts/JLuG3yqRdSH. Isn't github a better place to discuss issues?

**Comment by hub2git** [comment]
Why was this closed?

**Comment by zhihuitang** [comment]
The bad resolution is on purpose I think, you can pay for good resolution if you want.

**Comment by hub2git** [comment]
Thanks Zhuihui. You're right. After posting my question, I realized the
same thing. I'll look for a free high-res option.
