### ISSUE TITLE
iOS: Mouse and touch is getting out of sync 

### ISSUE THREAD

**Issue by bluepotionmaker** [koush/vysor.io#680]
**Describe the bug**
Macbook pro 16inch 2019 with BigSur 11.1,  iOS 14. 
Mouse pointer and touch is getting out of sync. 
Please refer to the video below. 

https://user-images.githubusercontent.com/76267121/103496082-3496a380-4e80-11eb-9351-41565101de76.mov

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/fe4e9e1b9322a07f03f3597922961423

**To Reproduce**
Just connect the device. 

**Expected behavior**
Touched where I clicked. 

**Screenshots**
video is already attached. 

**Desktop (please complete the following information):**
 - OS: Macbook Pro 16 inch 2019, Big Sur 11.1
 - Vysor Version - 4.0.9, 4.0.1

**iOS/Android (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 14.3
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/fe4e9e1b9322a07f03f3597922961423
 - 
**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - Macbook: bluetooth mouse, magic trackpad 2 is attached. 

This is from #678

**Comment by bluepotionmaker** [comment]
The above video is from vysor 4.0.9. 
This is from vysor v4.0.10 

https://user-images.githubusercontent.com/76267121/103509226-fa3ffd00-4ea5-11eb-851e-d87cb71a0f3a.mov

**Comment by koush** [comment]
Does the mouse ever behave properly, or is it out of position from the very start?

**Comment by koush** [comment]
Also, the mouse will "reset" and recalibrate if you move out of the window. It's difficult to keep it in sync, so try resetting by leaving the window, and let me know if that resolves it.

**Comment by bluepotionmaker** [comment]
From the very start and resetting does not resolve this issue.

**Comment by koush** [comment]
Can you try calibrating hte mouse as follows?

https://www.youtube.com/watch?v=-K-gNUefkxc

Find a value (probably near 100) that makes the mouse show up in the correct spot from the left edge. See video.

**Comment by bluepotionmaker** [comment]
I found 165 is the best value for me. It is still out of sync but pretty usable now. 
The problem is sending touch input is bit laggy. 
Thanks for your support always! :)


https://user-images.githubusercontent.com/76267121/103585897-4d0dc900-4f27-11eb-9b74-0b25f8487dc4.mov

**Comment by koush** [comment]
I suspect the lag is bluetooth related. Any chance you can turn your other bluetooth devices off complete and see if the lag subsides?

Afterwards, you can disable “track mouse”. That may address the lag (as it will only send mouse events on clicks).

**Comment by bluepotionmaker** [comment]
@koush  Thank you! I disabled other bluetooth devices and the lag is gone! :) If you want, you can close this issue!
Thanks again!

**Comment by koush** [comment]
Can you have one on at a time and determine if it’s the mouse or trackpad? if it turns out to be the mouse, let me know which model of mouse it is?

**Comment by jcbdev** [comment]
I have a similar issue where the offset is just totally off, no matter how I set the calibration



https://user-images.githubusercontent.com/17152092/103588594-70158a00-4ee1-11eb-983a-0c9563c7af60.mp4

**Comment by koush** [comment]
@jcbdev Can you use the instructions to calibrate properly? I am collecting the calibration values for the different iOS devices and updating accordingly. Need to slide the mouse in from the left when calibrating.

https://github.com/koush/vysor.io/issues/680#issuecomment-753842507

**Comment by koush** [comment]
@jcbdev once you have calibrated properly, provide me a bug report and the phone model.

**Comment by jcbdev** [comment]
@koush I have done. No values work.  That was set to 165 (as the @bluepotionmaker) tried but I have tried various values from 1 to 300 and none of them work.  The pointer never reaches the right of the screen, and it never tracks under the mouse.   As I move from top to bottom the "scale" is too large (moves much faster than mouse).  And from left to right in never moves enough so is underscaled.

I have 3 monitors on my setup with slightly different resolutions.  I get the same response on all three but I have used screen control apps which have similar problems before because they use the screen width/height in the offset calculations (but this is complicated by multiscreen setups).  Is it possible this is the case?

**Comment by koush** [comment]
> @koush I have done. No values work. That was set to 165 (as the @bluepotionmaker) tried but I have tried various values from 1 to 300 and none of them work. The pointer never reaches the right of the screen, and it never tracks under the mouse. As I move from top to bottom the "scale" is too large (moves much faster than mouse). And from left to right in never moves enough so is underscaled.
> 
> I have 3 monitors on my setup with slightly different resolutions. I get the same response on all three but I have used screen control apps which have similar problems before because they use the screen width/height in the offset calculations (but this is complicated by multiscreen setups). Is it possible this is the case?


@jcbdev 
Can you create a video of a working calibration (ie, it matches the position left edge of the screen), and then show the scaling issue? It sounds like there’s different X vs Y axis scaling?
When calibrating, allow the ios mouse tracker to move into the lower left of the window. Then bring the desktop mouse pointer to the middle/upper left of the ios screen window so that it matches.

**Comment by jcbdev** [comment]
Here is me trying to calibrate.

I am using an iphone 10Xs on ios 13.3.1 and mac catalina 10.15.7

I tried on single monitor setup and it makes no difference (so it's not multimonitor thats the issue)

https://user-images.githubusercontent.com/17152092/103591381-e7e6b300-4ee7-11eb-990d-0f997297fec3.mp4

**Comment by jcbdev** [comment]
Bug report https://gist.github.com/e91b05974f5aa8b035efb9dcfcfe50f2

**Comment by koush** [comment]
Thanks. It seems the 165 somewhat works for the Y value, but not for the X value. I’ll need 2 entries maybe.

**Comment by dieskim** [comment]
Another instance here - iPhone SE 2020 - 165 seems to work best, it does seem to work best at first then the misalignment increases over time and needs to be reset again, buts its much more manageable.

**Comment by PEZ** [comment]
As @koush says, there probably needs to be an X calibration as well.

But the current 165 y-only works pretty OK. At the center of the screen it is almost spot on. But it misses more the farther away from the center I click.

**Comment by koush** [comment]
I'll get an X calibration value in in the next update, sorry for the delay on this.

**Comment by berryjuice** [comment]
I have the same problem with all my iPhones (Android works fine). Have you guy noticed that at all time and on all devices the time gets set to 9:41 AM in the moment you get conncected?

**Comment by koush** [comment]
separate X and Y calibration value has been added

**Comment by ramya1890** [comment]
@koush Do you have the latest calibrated values for iPhone 7 and 7 plus?

**Comment by koush** [comment]
I do not, but feel free to provide them and I'll add them as defaults.

**Comment by ifiokjr** [comment]
For my iPhone8-Pro I found X-118 and Y-117 worked pretty well. 

Conceptually, I struggled to understand what the values represent.

**Comment by koush** [comment]
@ifiokjr 
> For my iPhone8-Pro I found X-118 and Y-117 worked pretty well.
> 
> Conceptually, I struggled to understand what the values represent.

Basically they control how far Vysor calculates/estimates the iOS mouse has moved on the device. Higher values means Vysor thinks the mouse moved further. So if your iOS mouse is moving less than your desktop mouse, increase the value.

**Comment by koush** [comment]
@ifiokjr if you don't mind, share a bug report with your screen mirroring so I can add those defaults.

**Comment by tinng81** [comment]
For iPhone XR the optimal values are 137 for both X and Y. 

I followed the calibration guide video from above [comment](https://github.com/koush/vysor.io/issues/680#issuecomment-753842507) from @koush. Essentially drag from Left edge to right for Y value and Top edge to down for X value. Hope this helps!

**Comment by koush** [comment]
> For iPhone XR the optimal values are 137 for both X and Y.
> 
> I followed the calibration guide video from above [comment](https://github.com/koush/vysor.io/issues/680#issuecomment-753842507) from @koush. Essentially drag from Left edge to right for Y value and Top edge to down for X value. Hope this helps!

@tinng81 can you share a bug report so I can add these defaults to the app?
