### ISSUE TITLE
Won't Find iOS Device

### ISSUE THREAD

**Issue by dustinchapman** [koush/vysor.io#682]
Tried resetting the phone, etc. to get it to show up on the Mac version of Vysor. Phone is connected, trusted, and charging but it won't show up on Vysor. 

Very excited to see this feature, by the way, especially if you can click on the interface with your mouse cursor. I do sales presentations of a mobile app and it's extremely helpful to be able to click with your mouse on Android. 

Is this the bug report here: https://gist.github.com/VysorLogs/306c4d2d5bdcd98fe750fc3113afa32b

**Comment by koush** [comment]
I've seen intermittent reports of this, and encountered it myself.
Try the following:
 * unplug the phon
 * quit vysor from the app tray (right click quit)
 * reconnect the phone and restart Vysor after 10 seconds
 
It seems that Mac's recognition of the iOS gets stuck somewhere in the OS. Doing this a few times seems to resolve the issue. I've noticed similar problems in QuickTime.

I'm trying to figure out how to work around this.

**Comment by dustinchapman** [comment]
That worked. Thanks! The mouse is off on the iOS screen, meaning it's not "touching" the screen where the mouse is, but it looks very cool.

**Comment by koush** [comment]
> That worked. Thanks! The mouse is off on the iOS screen, meaning it's not "touching" the screen where the mouse is, but it looks very cool.

Please open a new bug and include the phone model and a generated bug report link!

**Comment by koush** [comment]
Reopening as I seem to encounter this problem every update. May potentially have a fix for this.

**Comment by koush** [comment]
I think this is fixed in the most recent update.
