### ISSUE TITLE
Says, Android not Found, but My Android Phone Found 

### ISSUE THREAD

**Issue by gittac** [koush/vysor.io#683]
I have been using Vysor for about two years and I love it.  Plus, I am a quadriplegic, so using the voice control in my windows computer along with Vysor is my only access to my smartphone.
I am using windows 10 and I have a MOTO Z4.  Since the version of Vysor that came out Saturday, January 2, 2021 and today.  What happens is my phone is found, but it still says android not found, but everything works good.  I clicked on the red arrow, my phone came up, I unplugged my phone, phone disappeared from my PC screen, so I know it works.  Wi-fi also works fine.  There is still this pesky message android not found.  I have attached a screenshot.

![image](https://user-images.githubusercontent.com/10365703/103590301-1b5b1a80-4eb3-11eb-906e-830747a02d8f.png)

**Comment by koush** [comment]
@gittac that message is there and ALWAYS shown in case you have multiple android devices, and one of them is not found.

**Comment by koush** [comment]
ie, from this screenshot, you could also have opened a bug that said “my moto is found, but my pixel 5 isnt”. that’s why the guidance is always shown.
