### ISSUE TITLE
Android: File Drag Drop - Gallery does not refresh for images

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#685]
**Describe the bug**
When dragging and dropping a file from Mac to Android, the file is moved over as expected, but that file is not accessable on apps like Whatsapp etc just yet, it seems that the gallery does not rescan after a file is added.

**To Reproduce**
1. drag a image from Mac to Android via Vysor
2. Open via Gallary
3. Go to Whatsapp or any app and try to find that image to send
4. The image is not showing up. The first time the Vysor Album wont even show up

**Expected behavior**
Vysor should trigger a Gallery / Media refresh - 
- an example would be to use this app - https://play.google.com/store/apps/details?id=net.zhuoweizhang.scanmediaplz
https://github.com/zhuowei/scanmediaplz/blob/master/src/net/zhuoweizhang/scanmediaplz/ScanMediaPlzActivity.java
This app forces a rescan and then the photo shows up in the phone gallery

- you could most likely just let it add the file that was dragged
https://developer.android.com/reference/android/media/MediaScannerConnection

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Vysor Version 4.0.13

**iOS/Android (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 10

**Comment by dieskim** [comment]
@koush - any way you could add this fix also in the next android update?

**Comment by koush** [comment]
Yeah, been eyeing this. Should be able to do it without updating the APK too.
https://stackoverflow.com/a/43902912

**Comment by koush** [comment]
```
06-06 01:16:59.277  4958  9808 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///mnt/sdcard/vysor/poop.png flg=0x1400010 cmp=com.google.android.providers.media.module/com.android.providers.media.MediaService }
06-06 01:16:59.281  4958  9808 W ModernMediaScanner: Failed to visit /mnt/sdcard/vysor/poop.png: java.nio.file.AccessDeniedException: /mnt/sdcard/vysor/poop.png
06-06 01:16:59.275  4958  4958 W com.google.android.providers.media.module: type=1400 audit(0.0:399454): avc: denied { read } for comm=4173796E635461736B202331 name="sdcard" dev="tmpfs" ino=28976 scontext=u:r:mediaprovider_app:s0:c23,c257,c512,c768 tcontext=u:object_r:mnt_sdcard_file:s0 tclass=lnk_file permissive=0 app=com.google.android.providers.media.module
```

Weird security error.

**Comment by dieskim** [comment]
```
Dieskims-MacBook-Pro:~ dieskim$ adb shell am broadcast \ -a android.intent.action.MEDIA_SCANNER_SCAN_FILE \ -d file:///mnt/sdcard/vysor/test.png
Broadcasting: Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///mnt/sdcard/vysor/test.png flg=0x400000 }
Broadcast completed: result=0
```

**Comment by dieskim** [comment]
I just tested it on my device

1. Dragged a file called test2.png 
2. It is on the device but not showing up on galery
3. Ran

```MacBook-Pro:~ macbook$ adb shell am broadcast \ -a android.intent.action.MEDIA_SCANNER_SCAN_FILE \ -d file:///storage/emulated/0/vysor/test2.png
Broadcasting: Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/vysor/test2.png flg=0x400000 }
Broadcast completed: result=0```

**Comment by dieskim** [comment]
```
MacBook-Pro:~ macbook$ adb shell am broadcast \ -a android.intent.action.MEDIA_SCANNER_SCAN_FILE \ -d file:///storage/emulated/0/vysor/test3.png
Broadcasting: Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/vysor/test3.png flg=0x400000 }
Broadcast completed: result=0
```
this did nothing for me

**Comment by koush** [comment]
am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file:///sdcard/vysor/poop.png

This worked for me in Google Photos.

**Comment by koush** [comment]
I don't see any difference in the two you posted, but you said once works and the other doesn't?

**Comment by dieskim** [comment]
When using the path to the file like this it does not work on my device
```
file:///mnt/sdcard//vysor/test3.png
```

This works for me

```
file:///storage/emulated/0/vysor/test2.png
```

**Comment by koush** [comment]
Can you try 
```
file:///sdcard/vysor/poop.png
```

That does work for me, but I'd like to confirm.

**Comment by dieskim** [comment]
```
adb shell am broadcast \ -a android.intent.action.MEDIA_SCANNER_SCAN_FILE \ -d file:///storage/emulated/0/vysor/test6.png
```
this works but not with the path as you above - but this is my Xiaomi Mi A3

**Comment by dieskim** [comment]
Lots of stuff online about different Android versions not working with different forms of hardcoded paths - could you get the full path as returned after the `adb put` of the file and use that?

**Comment by koush** [comment]
I can just run both scan commands.

**Comment by dieskim** [comment]
I also noticed this - https://stackoverflow.com/a/54377436/5234751
I can test on my samsung dev phone tomorrow and confirm what works on that

**Comment by koush** [comment]
this should work

```typescript
  async sendFile(readable: Readable, name: string): Promise<string> {
    const isApk = name.endsWith(".apk");
    const pushPath = isApk ? "/data/local/tmp/" : "/sdcard/vysor/";

    const filename = pushPath + name;
    await Adb.push({
      socketFactory: this.socketFactory,
      readable,
      filename,
    });

    let command = `am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d "file://${filename}"`;
    debug(command);
    await Adb.shell({
      socketFactory: this.socketFactory,
      command,
    });

    const emulated = filename.replace('/sdcard', '/storage/emulated/0');
    command = `am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d "file://${emulated}"`;
    debug(command);
    Adb.shell({
      socketFactory: this.socketFactory,
      command,
    });
    return filename;
  }

```

**Comment by dieskim** [comment]
Great - will you push that to the new beta channel then I can test if for you tomorrow on multiple devices?

**Comment by dieskim** [comment]
I can confirm this does now work as expected.
Tested on:
- Xiaomi Mi A3 (Android  11) 
- Samsung Galaxy J4+ (Android  8.1.0) 
- Samsung A11 (Android 10)
Thank you for the fix.

**Comment by koush** [comment]
What desktop OS btw?

**Comment by dieskim** [comment]
All Mac OS
