### ISSUE TITLE
Allow running old version /  add option to prevent Auto Updates / Beta Testing Channel

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#686]
It would be very helpful to prevent auto updates. My version has been automatically updated several times and the new versions have some bugs. It would be nice to go back to an old version and then prevent it from auto updating. 

I tried to install an older version to be able to at least use it as it worked before, but it seems to just install the new version every time?

A beta testing channel might also be good so that we can test the new features and provide feedback before it rolls out to the public?

Thanks for all the new features and fixing bugs, its very exciting.

**Comment by crouchingtiger** [comment]
Sorry to piggyback, but a change-log would also be very helpful on the update dialog too, even if it just pulls your commit messages into a simple scrolling text area. It would give me more confidence in knowing what's about to change / improve (there's only been 1 instance where an update broke ability to use Vysor with Android, but you know, OPSEC and all that). Especially given the sensitive nature of what your software is doing (I trust you, but somebody could take over control of your accounts and push something much more sinister).

I know iOS and Android by default block recording of anything with a secure text entry field, but I've disabled that on my rooted Android device.

**Comment by hyaruixi** [comment]
added on to above, i've noticed the newer version of 4.x having an issue with showing device series number. In earlier version,  if i having multiple android devices connected to the same mac host, from the vysor device list, i can tell which one is the one I want to control by referencing their individual device series number. So i want to downgrade the version back to 3.x, but even I installed with 3.x, it still opens with auto updated 4.x

**Comment by koush** [comment]
I removed the serial numbers because I didn't think that was actually useful information. I can put it in a tooltip or something.

**Comment by hyaruixi** [comment]
> I removed the serial numbers because I didn't think that was actually useful information. I can put it in a tooltip or something.

Hi there,
The serial number is actually very useful especially we having multiple device has the same device type, for example: 'PIXEL 2', if we having more than 1 device having the same type, we rely on the serial number to identify which device is the target one to control.

If possible, can you add it back? Thanks for help.

**Comment by koush** [comment]
@dieskim @crouchingtiger 

I've been thinking about this, especially as I'm approaching a new major release. It's something I want to do before I push this new version. That said, I'm hesitant to do rollbacks to specific versions. That requires keeping all (or several) versions hosted, and results in buggy scenarios where a user changes their version to something old but never changes it back, and being stuck on that unknowingly.

I think the main request here is to insulate/mitigate users from buggy releases, and provide a way to roll back to a stable release. To that end, channels (versus versions) make sense. Less work on my part too.

So I think two channels moving forward:

Release channel. Will receive tip of the spear updates and features. It may have bugs like all new features do, but usually won't. Basically the how the current releases work.

Stable channel. Functionally, this will just be delayed behind the release channel by a couple weeks, but will be updated at my discretion. This will allow ample time for the release channel users to report bugs so I can respond and get them fixed. It will exist primarily for rollback purposes.

Let me know your thoughts.

**Comment by koush** [comment]
As an additional note, these proposed channels will only be available in the Electron/native version of the app. The progressive web app (https://app.vysor.io) will always be on the latest updates.

**Comment by koush** [comment]
> Release channel. Will receive tip of the spear updates and features. It may have bugs like all new features do, but usually won't. Basically the how the current releases work.

Within the app, I'll be calling this the "Beta" channel, so people are disinclined to use it. Don't want to explain what Stable vs Release is, since that seems confusing to me too.

**Comment by koush** [comment]
Ok, I've implemented this and am testing it now.
<img width="836" alt="Vysor" src="https://user-images.githubusercontent.com/73924/120879620-9bc49b00-c579-11eb-97f5-511bc4d81711.png">

<img width="836" alt="Vysor" src="https://user-images.githubusercontent.com/73924/120879627-a717c680-c579-11eb-9984-9ed706a0866c.png">

**Comment by koush** [comment]
Ok, this change is now live, but it does sketch me out a bit. Feedback and testing appreciated.

**Comment by dieskim** [comment]
Thanks for adding this. I'll be testing this soon and let you know if there are issues. Are there any new additions currently on beta?

**Comment by koush** [comment]
> Thanks for adding this. I'll be testing this soon and let you know if there are issues. Are there any new additions currently on beta?

The beta and stable branch are identical at the moment, but they will be diverging soon as I start pushing my pending iOS features as well as the backlog of stuff in this issue tracker.
