### ISSUE TITLE
macOS: Help menu bar items refer to Electron / Atom

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#689]
**Describe the bug**
The macOS Help menu items are the default Electron / Atom links.

**Expected behavior**
Link to Github issues / appropriate locations for Vysor.

**Screenshots**
<img width="406" alt="Bildschirmfoto 2021-01-07 um 14 17 25" src="https://user-images.githubusercontent.com/3936238/103896954-12f12280-50f3-11eb-97ac-c7ac595ce35d.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Vysor Version 4.0.18

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/543

**Comment by koush** [comment]
Need to fixup mac context menus.

**Comment by koush** [comment]
Fixed
