### ISSUE TITLE
Android: Connection Error: Unable to connect to control socket

### ISSUE THREAD

**Issue by joedelrosario** [koush/vysor.io#691]
Vysor updated to v4.0.18 then suddenly I couldn't connect anymore. 
Connection Error shows up with description "Error Connecting to Android Device Error: Unable to connect to control socket."

Appreciate help. Thanks!

Vysor Bug Report Log
------------------------
https://gist.github.com/VysorLogs/b228b41df7243a18b1fda72dfe4a38f2

Steps to Reproduce Behavior
-------------------------------
1. Run Vysor App on Desktop
2. Click on Play Device (Red Play Button)
3. See error

Expected behavior
--------------------
Normally, vysor would start the mirroring properly and bring me to my phone screen.

Screenshots
--------------
Step 1:
![image](https://user-images.githubusercontent.com/71033632/104113850-ab2c1900-5338-11eb-80ed-b3b4c5624ea6.png)
Step 2:
![image](https://user-images.githubusercontent.com/71033632/104114305-e9780700-533d-11eb-8965-a765fff7802c.png)
Step 3:
![image](https://user-images.githubusercontent.com/71033632/104113847-9fd8ed80-5338-11eb-8670-edbf77456522.png)

Desktop Information
----------------------
 - OS: Windows 10 PRO (for what its worth, it also happened on my workplace PC Windows 7 Pro)
 - Vysor Version 4.0.18

Device Information
----------------------
 - Device: Samsung Galaxy A31 (SM-A315G/DS)
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/b228b41df7243a18b1fda72dfe4a38f2

**Comment by koush** [comment]
This is the offending bit in the log:

> failed to connect control socket: did not receive adb socket client okay


It seems to indicate your adb is hung or something. Can you try restarting the PC (and might as well do the phone for good measure).

**Comment by joedelrosario** [comment]
Apologies for the late response.

I couldn't restart the pc as I'm doing something there that requires it to be on for a few weeks.

However, I'm back at work and still experiencing the same problem with my work pc. OS is Windows 7 Pro.

Kindly see attached error log.

https://gist.github.com/VysorLogs/4c11dcee988fb2f330b579bc90bba2c3

Fortunately, a restart using my phone (I forgot to restart at home) made the problem go away. I wonder what went wrong?

**Comment by koush** [comment]
@joedelrosario Phone side adb error probably. Unsure.
