### ISSUE TITLE
Electron/Squirrel Linux does not notify when full updates are available

### ISSUE THREAD

**Issue by jurijp** [koush/vysor.io#693]
The download links for the Linux version of vysor lead to
Vysor-mac-4.0.17.dmg 92.4 MB
Vysor-mac-4.0.17.zip 89.8 MB
Source code (zip)
Source code (tar.gz) 

Is there an appimage for Linux as there used to be ?
Thanks, JP

**Comment by koush** [comment]
Check the older release. The old client autoupdates. There’s only a full binary release for Mac since that added ios support.

**Comment by jurijp** [comment]
Would you please be so kind as to point to those older releases ? My client is at 2.3.0 and it appears that the most recent version is v4.0.17 so perhaps autoupdate is not working or some other issue is preventing the update. Some time ago, I paid for an upgrade but because I had a disk crash and had to rebuild my Ubuntu 16 system, every attempt I make to -re- upgrade Vysor I get a flyout that covers the various payment options that says "unable to get your Google Login.  If so open and issue on the Support Column"  selecting the flyout closes everything and does not recover. It makes no difference if I am logged into google or not
Perhaps you could shed some light on both issues. Thank you

**Comment by koush** [comment]
Here’s the latest download, and it should autoupdate to 4.x.
All the versions have autoupdate.

https://github.com/koush/vysor.io/releases/tag/v3.1.4

**Comment by koush** [comment]
There is now an apt repository (see main site)
