### ISSUE TITLE
macOS BigSur: UI bugs: Wrong icon color and size, wrong status bar behaviour.

### ISSUE THREAD

**Issue by MrMarmelade** [koush/vysor.io#695]
Vysor Pro Version 4.0.25
macOS BigSur 11.2 Beta

1) Icon color depends on the wallpaper, icon should be white with dark wallpaper and black with light wallpaper. Now it is only white. 
![Screen Shot 2021-01-18 at 17 57 55](https://user-images.githubusercontent.com/23004033/104944156-161fc480-59b7-11eb-8e67-15ba6e892aea.png)

2) App icon is too big in the dock. 
![Screen Shot 2021-01-18 at 17 58 13](https://user-images.githubusercontent.com/23004033/104944188-20da5980-59b7-11eb-823a-a6efb90f09c6.png)

3) Status bar scrolls too when user scrolling, it should't do.
![Screen Shot 2021-01-18 at 17 59 13](https://user-images.githubusercontent.com/23004033/104944260-3c456480-59b7-11eb-8f14-e4f1a9d11c1d.png)

Thanks. 🙂

**Comment by koush** [comment]
is in the beta channel. check the prerelease builds on this repository to access it.

**Comment by koush** [comment]
#3 is not fixed though

**Comment by MrMarmelade** [comment]
I tried new stable build (4.0.63) and dock icon is fine, thanks. 🙏 1. and 3. (as you saying) still not fixed.

**Comment by koush** [comment]
1. is not fixed yet. how do you change the menu bar color for me? it's always dark on Big Sur even if I change the Desktop theme to light.
3. is fixed in the beta channel (you can switch your channel in the new app)

**Comment by koush** [comment]
Figured it out. Will need to do a new full build for this.

https://discussions.apple.com/thread/252025475

**Comment by MrMarmelade** [comment]
1. It is wierd. I selected some system wallpaper with light version and every icon turns into dark, only Vysor stays in light. I use macOS Monterey, but it has same behaviour as BigSur.

**Comment by MrMarmelade** [comment]
3. Yeah it is fixed in beta channel, good job. 👍

**Comment by koush** [comment]
> 1. It is wierd. I selected some system wallpaper with light version and every icon turns into dark, only Vysor stays in light. I use macOS Monterey, but it has same behaviour as BigSur.

Yeah, I have a fix for this too.
