### ISSUE TITLE
Android : When switch to other app on mac, Android opens device control on vivo and on oneplus 8t, Ok google mic

### ISSUE THREAD

**Issue by manishpatil497** [koush/vysor.io#697]
**Describe the bug**
When I switch to other app on mac, on android phone vivo show me power off and reboot option, it happening on every command + tab on mac

**Attach a Vysor Bug Report Log**
id 
email 
/Users/manish/Library/Application Support/vysor
https://vysorelectron.clockworkmod.com/#/
process.versions {"node":"12.14.1","v8":"8.3.110.13-electron.0","uv":"1.33.1","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"80","nghttp2":"1.40.0","napi":"5","llhttp":"2.0.1","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"9.4.0","chrome":"83.0.4103.122"}
package.json 4.0.25
runtime package.json 4.0.17
os darwin
electron true
pwa false
adb tracker started
apple tracker started
https://vysorelectron.clockworkmod.com/#/
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in
not logged in, using firebase client
id 115460863440447839906
email manishpatil497@gmail.com
enterprise cache not licensed
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not cached
id 115460863440447839906
email manishpatil497@gmail.com
enterprise cache not licensed
clockwork cache not licensed
chromeStore cached check failed Error: not cached

**To Reproduce**
1. Go to 'mac vysor'
2. Launch phone/s 
3. Phone is launched, now command + tab of mac to switch to other app in mac
4. check actual phone, phone show options like power off and reboot and for oneplus 8t ok google mic turns on

**Expected behavior**
Power off and reboot or ok google should not launch

**Screenshots**
[https://drive.google.com/file/d/1rSPWXBWwSGPMq5F8EIzIDbXrfxdxgtsL/view?usp=sharing](url)

**Desktop (please complete the following information):**
 - OS: [MacOS : Mac Catalina : 10.15.6 (19G73]
 - Vysor free Version [e.g. 4.0.25]

**iOS/Android (please complete the following information):**
 - Device: [e.g. Oneplus 8T (OS : 11)]
 - OS: [e.g. Android 11]
 - Device 2 Vivo 1724
- OS: [e.g. Android 8.1]

**Comment by koush** [comment]
Thanks, will fix this.

**Comment by koush** [comment]
Fixed in 4.0.26.

**Comment by manishpatil497** [comment]
Really thank man, it's fixed in 4.0.27
