### ISSUE TITLE
Android: Please add back the device series number

### ISSUE THREAD

**Issue by hyaruixi** [koush/vysor.io#698]
**Describe the bug**
In newly updated Vysor, android device series number has been removed from UI.

The serial number is actually very useful especially we having multiple device has the same device type connected to the same mac host, for example: 'PIXEL 2', if we having more than 1 device having the same type, we rely on the serial number to identify which device is the target one to control. 

As a Vysor pro user, this tool has been a very useful tool in our day-to-day work for manage and maintain some devices which are remotely located in office. Without a series number, we having no referencing to identify which one is the target device we want to control.

**Comment by koush** [comment]
Will do

**Comment by koush** [comment]
fixed in 4.0.26

**Comment by hyaruixi** [comment]
may i know when this change will be release to production? Current prod version is  4.0.17. thanks!

**Comment by koush** [comment]
It is already out. If you click reload to trigger an update, you will see it in 4.0.29.

**Comment by hyaruixi** [comment]
> It is already out. If you click reload to trigger an update, you will see it in 4.0.29.

I actually did reload yesterday, but haven't noticed you add back the serial number as an option button under settings, that's super cool! Thanks a lot.
