### ISSUE TITLE
This is not so much an ISSUE, but a question.

### ISSUE THREAD

**Issue by gittac** [koush/vysor.io#699]
I use Vysor because I have a severe physical disability and Vysor is the only good way for me to operate everything on my smartphone. 
I am using Vysor for at least two years.  
I pay for this app because want the Vysor app to continue or I won't be able to use my smartphone. 
I'd like to be able to help family members and friends with their smartphones when needed. 
Is there a way to add another smartphone to my account or whatnot?   
DisabilityVoice.Tim@gmail.com

**Comment by koush** [comment]
Vysor’s free version allows users to share their device using Share All Devices, and then they can authorize only your account.

**Comment by gittac** [comment]
How do they authorize?  I did not find how that is done in your Manual. Maybe I'm looking at the wrong place. When I click share all devices on vysor on my computer I see an IP address.
