### ISSUE TITLE
Samsung Galaxy S6 not working

### ISSUE THREAD

**Issue by stianeklund** [koush/vysor.io#7]
Not showing up in the initial list, does show up if I click find, as MTP device with Samsung drivers, and device with serial number with ADB drivers. Doesn't work from there however. ADB debugging is enabled.

Edit: PTP mode solves the connectivity issue, but image is garbled and squished.

**Comment by PHGterence** [comment]
Similar issue with Galaxy S5

**Comment by edmckenna** [comment]
I found I needed to disable MTP by selecting PTP. Once I did that I was able to connect.

**Comment by aggietallboy** [comment]
Having similar issue on Galaxy S5 Active.
Tried installing UniversalADBDriver from @koush as well as ADB-Driver from androidxda.

In neither case does my serial number show up.

Initially I get 4 devices showing up when attaching as mtp -- select one, or all of them, and then "find device" finds just one on the next try.

Doing PTP shows up each time
![image](https://cloud.githubusercontent.com/assets/10222174/9473131/d05dbb84-4b1e-11e5-84b4-43a2c91cc6af.png)

But then just return to the find devices page once selected:
![image](https://cloud.githubusercontent.com/assets/10222174/9473155/ee1a5cae-4b1e-11e5-9a01-4b4a199b50a8.png)

**Comment by Melaylou** [comment]
Same problem with the s6 edge

**Comment by aggietallboy** [comment]
Additional steps: Uninstall Google drivers, uninstall Samsung Kies, reinstall UniversalAdbDriverSetup.

Same results.

**Comment by aggietallboy** [comment]
Screenshot of first run on MTP:
![image](https://cloud.githubusercontent.com/assets/10222174/9473444/830740d8-4b20-11e5-9e93-0cd41756c87b.png)

**Comment by koush** [comment]
try setting to PTP mode?

**Comment by stianeklund** [comment]
The issue is indeed with MTP, PTP works but the image is garbled.

**Comment by koush** [comment]
There's another fix for garbled images. It's Chrome webgl related. Check the issues list.

**Comment by vinaychandra** [comment]
PTP is also not working for me -  Galaxy S4

**Comment by jarch3r** [comment]
For me, neither MTP or PTP works. Neither had a serial number and both just returned to the Find Devices screen.

Testing another device, Nexus 7 works fine.

**Comment by DanReece** [comment]
Galaxy S4 here.  MTP shows up without serial number and goes no further when I select it.
![vysor1](https://cloud.githubusercontent.com/assets/13969509/9477457/04dfcf3c-4b38-11e5-903b-27cf42991902.PNG)
![vysor2](https://cloud.githubusercontent.com/assets/13969509/9477460/0895a3ea-4b38-11e5-8e07-ba8c32e31980.PNG)

 PTP nothing shows up when I try to find the device.

**Comment by jarch3r** [comment]
DanReece, did you wait a minute for drivers to install after switching to PTP mode?

**Comment by DanReece** [comment]
jarch3r

Yes.  When I switched to PTP mode drivers installed.  When I tried to find the device nothing showed.

I just attempted it again in PTP mode and it misidentified my device.
![vysor3](https://cloud.githubusercontent.com/assets/13969509/9477595/126afa90-4b39-11e5-8e90-ef34e756179d.PNG)

**Comment by jarch3r** [comment]
DanReece, yep that's what I see as well. We are having the same exact results now. Hopefully our consistency helps isolate the issue.

**Comment by DanReece** [comment]
That's my hope.  I tried selecting the misidentified device and found the same result.  Seems to mostly effect Galaxy and LG phones from what I've seen online.

**Comment by edmckenna** [comment]
With these new responses, I've gone back and tried everything again. Note, I have a Verizon Samsung Galaxy S5, rooted with stock 4.4.4

Originally I could only get this to work with PTP mode enabled. When I tried earlier today with MTP mode, I was stuck in the spinning loading screen. 

Trying again now, I can successfully connect in both MTP and PTP modes. I haven't changed anything since, so it might have been a fluke that MTP mode didn't work before. Although they both work, switching modes *while* connected causes the connection to drop. 
![screen shot 2015-08-25 at 4 08 39 pm](https://cloud.githubusercontent.com/assets/3429249/9478036/9517295a-4b43-11e5-898b-09ad6c58da03.png)
I've also noticed my device name is not showing up the same as the others I've seen here. Mine reads "SAMSUNG_Android from SAMSUNG" under the device name, rather than attempting to show the model number. Is it possible it has something to do with the drivers installed? I'm on OSX 10.10 with chrome v44.0.2403.157
![screen shot 2015-08-25 at 4 06 37 pm](https://cloud.githubusercontent.com/assets/3429249/9478059/af6a8630-4b43-11e5-9e22-c41f9de1df38.png)
I do get the correct model under the Vysor main window once I'm connected. 
![screen shot 2015-08-25 at 4 06 32 pm](https://cloud.githubusercontent.com/assets/3429249/9478190/4b937b48-4b44-11e5-8369-9c539cab5792.png)

**Comment by koush** [comment]
@edmckenna mtp mode disables the adb interface on some phones. not sure why. it's been a longstanding issue.

**Comment by vinaychandra** [comment]
@koush I could not find my device on the list. ADB interface is probably not disabled because 'adb devices' is showing my device. I am running the app on Debian based system. (Galaxy S4 - rooted)

**Comment by koush** [comment]
make sure youre on vysor 1040+. there was a bug with rooted devices prior to that.

**Comment by jarch3r** [comment]
Thank you for the update. I tried 1040 with no change. Rooted S6 still has one option in each mode, MTP/PTP. Neither shows a serial number or tries to open a window/display a screen.

**Comment by koush** [comment]
@jarch3r  can you take a screenshot of your device manager for me. i want to make sure your drivers are properly installed. it sounds like they are not, if your nexus device was working and the s6 isn't.

**Comment by jarch3r** [comment]
@koush http://i.imgur.com/a1qVHDh.png

**Comment by koush** [comment]
@jarch3r can you take a screenshot of your "Find Devices" popup, and then the vysor device list after you select it?
Remember to authorize usb debugging on your phone after you select it from the popup list.

**Comment by jarch3r** [comment]
@koush "Authorize usb debugging on your phone after you select it from the popup list."

How? I don't notice a request on my phone. Just the setting in Developer Options.

Hmm, Find Devices screen doesn't show up any more when I plug it in. I just hear the standard windows chime for a recognized USB device.

Properties from Devices and Printers if this helps:
MTP: http://i.imgur.com/JnSwLht.png
PTP: http://i.imgur.com/u4asJoo.png

**Comment by koush** [comment]
@jarch3r so you don't see a find devices button? just an empty list? Do you have an adb binary running already?

**Comment by DanReece** [comment]
I have updated to 1.0.4.0 and have tried both MTP and PTP with the same results I posted above.

**Comment by jarch3r** [comment]
@koush My mistake. Here are the find device screens: http://imgur.com/a/RGigR#0

**Comment by DanReece** [comment]
Those are the same screens I get when I try MTP and PTP.

**Comment by Slinkpit** [comment]
Ok i think i find a fix for that, i had the same issue MTP and PTP not shows anything, finds my phone but no more. Not sure if that is the problem but seems the PC MAC is not allowed to access to the phone ( i dont think that even makes sense but worked for me)

1. Connect the Phone to USB 
2. Be sure your ADB is enabled and PTP or MTP, i tested both and seems to work (Galasxy S6)
3. Go the pc console CMD and type "adb tcpip 5555" and you will get an "error" like this
http://imgur.com/2VKjPXA
4. Go to the phone and accept the connection

Now Vysor should work, worked for me, hope i can help

**Comment by jarch3r** [comment]
@Slinkpit Thank you very much. This worked 100%. It created a popup on my S6 asking me to accept the connection.

@koush Solution above.

**Comment by DanReece** [comment]
I tried the solution above but I get a different error.
![vysor4](https://cloud.githubusercontent.com/assets/13969509/9508784/9017d7de-4c1e-11e5-81f9-c4056959a56f.PNG)

**Comment by Slinkpit** [comment]
@DanReece That mean you dont have ADB Drivers installed

**Comment by DanReece** [comment]
I have them installed.  I just uninstalled and reinstalled them to make certain.

**Comment by jarch3r** [comment]
@DanReece navigate to the folder on your computer where adb.exe is. Run the command prompt from that folder and the command there.

To run a command prompt from a folder, hold shift in the folder and right click, then select Open Command Window Here.

**Comment by DanReece** [comment]
I do not have and adb.exe anywhere within the folder containing Universal ADB driver.

**Comment by jarch3r** [comment]
Right. I am not sure how Koush' ADB install is supposed to work, but there are other methods of obtaining the adb.exe file.

One is installing the Android SDK, pretty big. There is a thin installer somewhere on XDA too.

**Comment by koush** [comment]
I am closing this issue as @stianeklund's original problem was solved. Please open another issue if you are still having problems. Please refrain from commenting on issues unless you are _certain_ it is the same problem.

**Comment by koush** [comment]
Here's what will help me when opening an issue:

Install OEM official drivers if on windows
Enable PTP mode

Android device and OS version
Desktop OS version
Screenshot of device manager if on Windows
Screenshot of device list
Screenshot of device selector when pressing Find Devices (which appears if adb.exe is not running already)

**Comment by jayp-17** [comment]
Not working with Samsung Note 4 as well.
One thing I noticed that developer is so greedy that he is already selling pro version for money without ensuring that it was compatible with all devices.

How about you pay to all the people who hep & contribute to your work by sharing logs, screenshots, remote sharing etc.
It would be only fair I think.
Greed has no limits!

**Comment by koush** [comment]
@jayp-17 Hello, please uninstall Vysor.
