### ISSUE TITLE
Vysor not opening on computer

### ISSUE THREAD

**Issue by Tripwiregamer** [koush/vysor.io#700]
**Describe the bug**
This is not a bug with vysor not connecting
This is not a bug with vysor opening the window but not showing anything
This is a bug where the vysor application will not even open on my computer.
Every time I attempt to launch vysor, it doesn't crash, but it just doesn't show up on my computer _at all._

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
Cant.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
Cant.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
Can't.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.
Cant.

**To Reproduce**

**Expected behavior**
I expected the thing to open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Vysor Version: 3.1.4

**iOS/Android (please complete the following information):**
 - Device: Moto e6
 - OS: Android ?
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
Is it running in the taskbar maybe?
Can you see if a window is somehow stuck off screen?
Does it still fail to start even if the computer is rebooted?

**Comment by kghelios** [comment]
did anyone find a solution? I'm having the same issue.

**Comment by Caliventura** [comment]
Same error in 3 different Windows 10 computers using Vyzor 4.1.77.
I rebooted, de-install, re-install, rebooted and same issue. Vizor do not do anything after installing, no error messages, no installing windows.... Appears to be correctly installed in Program.
Any Suggestion?

**Comment by FranzNahrada** [comment]
It used to work fine, but now its gone. any solution found?
