### ISSUE TITLE
Android: Not installing """""""New""""""" apk

### ISSUE THREAD

**Issue by Tripwiregamer** [koush/vysor.io#701]
i swear to fucking god i've been trying to use your shitty fucking application so i could stream my phone screen to my comptuer screen for almost an entire fucking hour and it gets stuck at every single possible god damn roadblock fiX YOUR FUCKING PR O G R A M

**Describe the bug**
When I try to show the screen on vysor, it:
Connects
Asks for debug permissions
Uninstalls the **_PERFECTLY FINE_** apk
Gets stuck trying to install the """""""new""""""" apk.

**Attach a Vysor Bug Report Log**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Go to vysor
2. Click on the share button
3. Wait

**Expected behavior**
The application to show me my phone screen

**Screenshots**
![image](https://user-images.githubusercontent.com/45953835/105397739-0edefd80-5be7-11eb-8e6d-6534cdd5f0fa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Vysor Version 3.1.4

**iOS/Android (please complete the following information):**
 - Device: Moto e6
 - OS: Android
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
cool story! enjoy the block.
