### ISSUE TITLE
macOS: Please add an option to disable the menu bar icon

### ISSUE THREAD

**Issue by sfstpala** [koush/vysor.io#703]
The menu bar icon is not useful for me and clutters up the menu bar. Please add an option to disable it. 🙏

**Comment by koush** [comment]
You can use customize Vysor to customize all the buttons.

**Comment by sfstpala** [comment]
I can't find anything related to that in the config. I'm talking about this icon:

<img width="455" alt="Screenshot 2021-01-24 at 12 24 14" src="https://user-images.githubusercontent.com/458321/105628756-139dee80-5e3f-11eb-8c1b-9b35308c6499.png">

**Comment by koush** [comment]
Fix available in beta.
