### ISSUE TITLE
Android: Can't connect to view my device's screen

### ISSUE THREAD

**Issue by mignyap** [koush/vysor.io#704]
Hi, I got a new phone now running Android 10 and have since been unable to view my phone through my Mac laptop. I've already enabled USB debugging and tried restarting my phone and laptop. I keep getting an error message:

"Connection Error
Error Connecting to Android Device Error: Unable to connect to control socket."

 - OS: MacOS Catalina 10.15.7
 - Device: Samsung Galaxy Note 20
 - Android 10
 - Vysor Version 4.0.17
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/131a92160e11503727effa5ebeff2200

Help?

**Comment by JirkaKrivanek** [comment]
Happens to me too :( Probably no chance to get it fixed?

**Comment by koush** [comment]
@mignyap there seems to maybe be a stuck process on your android? can you restart it?

**Comment by JirkaKrivanek** [comment]
> @mignyap there seems to maybe be a stuck process on your android? can you restart it?

Yes phone restart fixed it (my presentation was lost thanks to it but next time I will know that Vysor is unstable and can easily be solved this way).

**Comment by nitinmoreojas** [comment]
Restarting android device worked for me. thanks

**Comment by sekhuat** [comment]
Restarting my android device also work for me. Thanks.

**Comment by tarikmsr** [comment]
Restarting my android device also work for me. Thanks.

**Comment by FuadFikri** [comment]
Restarting my android device also works for me. Thanks.

**Comment by Hamoda96** [comment]
Restarting my android device also works for me. Thanks a lot

**Comment by 100Hamza** [comment]
Restarting my android phone works for me.

**Comment by AhmedHamdyh** [comment]
Restarting my android phone works for me.

**Comment by Sultan757** [comment]
restarting android works in my case

**Comment by wesvh** [comment]
Restarting my android device also works for me. Thanks.

**Comment by coddev007** [comment]
Yes restart my phone work for me tnx

**Comment by Seba-Gonzale** [comment]
Reiniciar el smartphone funcionó :+1:

**Comment by Samuelpaz95** [comment]
La vieja confiable, apagar y prender el dispositivo android

**Comment by dragojs** [comment]
Late to this party, but uninstalling Vysor from the android fixed the issue for me and it's faster than restarting your device.

**Comment by theDevSoham** [comment]
Tried the uninstall and reinstall didn't work but the restart definitely worked for me

**Comment by rhonyabdullah** [comment]
Just facing this issue while plug my Oppo ColorOS 14 versions, 
1. quit vysor on mac
2. uninstall vysor on android
4. restart device
Works for me
