### ISSUE TITLE
Add recording to OBS without viewing the phone.

### ISSUE THREAD

**Issue by DevEstacion** [koush/vysor.io#705]
The current implementation requires opening the view of the phone to get the recording to work. This is extremely wasteful of resources and I think it'd be better if we can record without any view.

**Comment by koush** [comment]
I'm not going to implement this feature for a couple reasons:

It means that your phone screen can be streamed to other apps without your explicit knowledge permission. There's security/privacy issues here. Closing the Vysor window provides a guarantee that your screen is not being shared.

There's no wasted resources, besides rendering video, which is fairly low cost when using hardware renderers. The other "resources" would used anyways to stream to another app (connection, streaming, etc).

**Comment by DevEstacion** [comment]
@koush is there a way to capture the render of the window? Instead of using the Window picker from OBS and then removing the borders?

There's a latency when using the .flv stream whereas using the main view window doesnt.

**Comment by koush** [comment]
Yes, you can use the new Vysor Camera feature. You'll need to install the Vysor Camera plugin. https://twitter.com/vysorapp/status/1407051656274100230
