### ISSUE TITLE
Does Vysor have a plan to support to control iOS on Windows platform just like appium studio?

### ISSUE THREAD

**Issue by passcodex** [koush/vysor.io#707]
Hi,
just want to know, does vysor have a plan to do this, if it can be implemented that will be great.

https://user-images.githubusercontent.com/11014056/106091517-94265d00-6167-11eb-92f4-fd07a6e1ce12.mp4

**Comment by koush** [comment]
Yes, Windows support is coming.

**Comment by passcodex** [comment]
> Yes, Windows support is coming.


Hi @koush ,
I just tried using Vysor to connect to the iPhone on MacOS, however, mouse clicks and touch points cannot be synchronized, It is difficult to use the mouse to make precise touches, the following video describes the problem.
https://user-images.githubusercontent.com/11014056/106236713-62c99200-6238-11eb-81e8-3f8e65e901f6.mp4
Do I need to do additional configuration?

**Comment by koush** [comment]
With that mirroring window open, can you generate a bug report and send me the link? Also, try setting the mouse calibration in the Vysor Settings window you had open to "165" and let me know if that works.

**Comment by koush** [comment]
Basically, as noted, I've found that different iPhones have different mouse calibrations, and I do not have a complete collection of the defaults that work on each iPhone. I am fairly certain 165 will fix it for you, and I'll be able to add/confirm that in an update to fix it for all iPhone 7 models automatically.

**Comment by passcodex** [comment]
> With that mirroring window open, can you generate a bug report and send me the link? Also, try setting the mouse calibration in the Vysor Settings window you had open to "165" and let me know if that works.

**Comment by passcodex** [comment]
But still have a little problem.

**Comment by koush** [comment]
Did any calibration values work for you for the iPhone 7?

**Comment by passcodex** [comment]
> Did any calibration values work for you for the iPhone 7?

Yes, It seems that 165 is the best value,  I should ignore paying attention to the computer’s mouse pointer when I click on iPhone.

**Comment by koush** [comment]
> > Did any calibration values work for you for the iPhone 7?
> 
> Yes, It seems that 165 is the best value, I should ignore paying attention to the computer’s mouse pointer when I click on iPhone.

The computer mouse pointer should remain in sync with the iOS mouse pointer though.

**Comment by koush** [comment]
Please open a new issue with calibration values as necessary.

**Comment by magaoxxx** [comment]
Please someone help me, my mouse and keyboard is not clicking on the iphone, it's just mirroring the screen.
