### ISSUE TITLE
Windows: "Enable Android Notifications  on your desktop" question, can't dismiss

### ISSUE THREAD

**Issue by mattiasbe** [koush/vysor.io#708]
**Describe the bug**
Can't dismiss the "Would you like to enable Android Notifications onto your desktop?"
Clicking "No thanks" or ENABLE doesn't matter, nothing happens. It stays there, covering the top part.

**Attach a Vysor Bug Report Log**
[01a2fbc8-c200-44c5-bfca-fa40d3d34c40.txt](https://github.com/koush/vysor.io/files/5887563/01a2fbc8-c200-44c5-bfca-fa40d3d34c40.txt)

**To Reproduce**
1. Go to, connecting over ethernet to device (port forwarded through ssh, directly to port 5555, using 127.0.0.1:5555, works perfectly)
2. Click on: the dialogue that pops up "high quality mirror" select enable for example
3. next dialogue that appears can't be dismissed:
 Can't dismiss the "Would you like to enable Android Notifications onto your desktop?"
Clicking "No thanks" or ENABLE doesn't matter, nothing happens. It stays there, covering the top part.

**Expected behavior**
Clicking either No Thanks or Enable should dismiss that green dialogue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1568245/106146780-66491480-6177-11eb-9b8c-0ce13806e67c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Version: Pro 4.0.27

**iOS/Android (please complete the following information):**
 - Device: Custom android tablet
 - OS: Android 7.1.1

**Comment by koush** [comment]
Can you try Reset Vysor and see if the issue goes away? Wondering if some setting is stuck.

**Comment by mattiasbe** [comment]
Reset ended up the same unfortunately.
Though I accidently found a workaround:
Maximizing the window by clicking the square next to the close window 'X' in the upper right corner and then clicking it again to go back to normal size window. Then it's gone.

**Comment by koush** [comment]
Thanks, unsure what the issue is. Will investigate.

**Comment by mattiasbe** [comment]
Have it on both computers used for this. But with the simple workaround it's not a big deal anymore, before that it was quite annoying though :)
