### ISSUE TITLE
Right Mouse Click Back

### ISSUE THREAD

**Issue by Choeoqe** [koush/vysor.io#709]
Hi, I recently upgraded from a Galaxy S9 to an S20 FE. With the S9 the right mouse button would act as "back" through Vysor, but with the S20 that doesn't seem to be the case. is this device specific, or is there a setting I have missed that can enable this? Thanks!

**Comment by Choeoqe** [comment]
Literally straight after posting this it started working... I looked around settings and couldn't find anything, so I am not sure what changed!

**Comment by koush** [comment]
Can you generate a bug report link when it stops working? Do you have international keyboard enabled by chance?
