### ISSUE TITLE
Error: stream ended during read for minimum 4 bytes (Wireless Mode)

### ISSUE THREAD

**Issue by Cazpian** [koush/vysor.io#710]
**Description:**

When attempting to connect the device in Wireless Mode having already successfully connected it via USB, the above error appears multiple times and seems to indicate a general disconnection of the device from the PC. Once vysor returns a connection successful status message, the device is disconnected via USB and this again results in the error message ..

> "Mirroring Disconnected. Error: stream ended during read for minimum 4 bytes. "

**Vysor Bug Report**

I am unable to return the bug report as I am given the following error even when connected to the device via usb.

![image](https://user-images.githubusercontent.com/7291453/106273033-e4fe8a00-6229-11eb-91b1-9882309f32d5.png)

**Step to Reproduce**

Please see the following video, this also details the devices settings and the vysor settings when attempting to enter wireless mode.

[https://youtu.be/t8MGAwr7uPA](https://youtu.be/t8MGAwr7uPA)

**Expectations**
On selection of the "Wifi Mode" option I would expect for the device to attempt to connect using the wifi as its primary communication protocol, thus allowing me to disconnect the USB lead which tethers the device to the pc. My expectation is that the screen mirroring will run exactly the same as it does when connected, but without the need for a physical connection between pc and device.

**Desktop:**
 - OS: Windows 10.0.19042 Build 19042 Enterprise i7-6600u CPU 2.60Ghz, 2 Core(s) Surface Book One 16GB RAM
 - Vysor Version [3.1.4]

**Android:**
 - Device: [Xiaomi Redmi Note 8]
 - OS: [Android 10 QKQ1.200114.002 running MIUI Global 12.0.3 (QCOMIXM)
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

Please feel free to request more information and I will do my best to get this for you.

**Comment by koush** [comment]
Thanks for the bug report, could you include a generated bug report link after encountering hte error, per the instructions? I need that to investigate.

**Comment by Cazpian** [comment]
Hi, would you please be kind enough to instruct me on how I generate a bug report link for your consumption please. Clicking on the "BUG REPORT" button at the bottom of the windows client always appears to return "Bug Report Failed: Network Failure". Kind Regards

**Comment by drivetheory** [comment]
https://gist.github.com/VysorLogs/75e180fb25e566085f94d300903723a9

**Comment by koush** [comment]
> Hi, would you please be kind enough to instruct me on how I generate a bug report link for your consumption please. Clicking on the "BUG REPORT" button at the bottom of the windows client always appears to return "Bug Report Failed: Network Failure". Kind Regards

Are you behind a firewall or something? Generating the report works fine for others. That may also explain your wireless issues perhaps.

**Comment by koush** [comment]
Saw your video, it does seem that it's immediately disconnecting after connecting. This may be an adb hiccup, if you can get that bug report, there may be more information I can see in there.

**Comment by koush** [comment]
Alternatively, can you close the mirroring window and try opening it from the main device list window using the wifi button? see below.


![Uploading Screen Shot 2021-03-18 at 5.15.24 PM.png…]()

**Comment by verdyindra** [comment]
![image](https://user-images.githubusercontent.com/83101241/115942042-5a4cc480-a4d2-11eb-9f57-6b11400bfef2.png) sir got more less same problem any help for this ? im using vysor pro but get this problem

**Comment by geosidi** [comment]
Why did this get closed? I'm facing the same issue, is there a fix I've missed?

Logs can be found here ->https://gist.github.com/658e47662990f1dfbf1f7d168a51103f

**Comment by koush** [comment]
> Why did this get closed? I'm facing the same issue, is there a fix I've missed?
> 
> Logs can be found here -> https://gist.github.com/658e47662990f1dfbf1f7d168a51103f

The original issue opener did not respond. Please open a different issue, as yours does not seem to be the same bug.

**Comment by vdegenne** [comment]
I have the same on a Xiaomi phone.
