### ISSUE TITLE
Document DNS/Ports for Corporate Firewalls

### ISSUE THREAD

**Issue by setheen** [koush/vysor.io#711]
When behind paranoid corporate firewalls that limit outbound activity, the Vysor server cannot expose itself to whatever proxy infrastructure is in place.  After wiresharking healthy client/server activity, I believe a STUN server is included in the mix.  I'm guessing we'll need to whitelist traffic originated to remote IPs over UDP 3478.  

Besides TCP 443, could you please document all necessary destination ports Vysor server/client relies on?  Even better would be expected DNS targets but ports would be a great start.

**Comment by koush** [comment]
Vysor uses TURN to traverse through firewalls. The servers in question are:

```
          urls: ["turn:turn0.clockworkmod.com", "turn:n0.clockworkmod.com", "turn:n1.clockworkmod.com"],
```

**Comment by koush** [comment]
turn0.clockworkmod.com
n0.clockworkmod.com
n1.clockworkmod.com

Note that a couple of these don't resolve, they're just placeholders for the future.

**Comment by setheen** [comment]
Thank you!

**Comment by koush** [comment]
Also note that TURN does not use specific ports. They're dynamically allocated.
