### ISSUE TITLE
Colours difficult to read

### ISSUE THREAD

**Issue by jurijp** [koush/vysor.io#712]
Since I am dealing with ~ 20 separate devices with the pro version it is difficult to read the white on bright green text. Is there a way to change this ?  Here's an example.  Thanks for your time.
![image](https://user-images.githubusercontent.com/15130150/106363427-6ae80700-62f6-11eb-9988-ef6c99d2a05f.png)

**Comment by koush** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/73924/106365145-72081880-62e8-11eb-9b37-a7612715ae9b.png">

I’ll update it to tone down the green next release.
