### ISSUE TITLE
Android: When vysor is running Clipboard on PC works incorrect

### ISSUE THREAD

**Issue by GeoSaffer** [koush/vysor.io#713]
If Vysor is running and you copy paste , as many developers do, then the last entry to the clipboard gets replaced with undefined or it swaps the last 2 entries in the clipboard around.

So when you ctrl+c and ctrl+v you expecting to see the last entry to the clipboard pasted. it does not always do this.

When you close Vysor entirely the copy pasting works as expected.

Bug Report files on https://gist.github.com/VysorLogs

26730eca-b4e9-42e3-bdf2-68993235eaf0.txt

794c2f23-d3e0-4529-923b-5dbb91618c8e.txt

e64dada7-fa01-436e-8456-ced0d4cc52dd.txt

**Comment by koush** [comment]
I'm not able to reproduce this, but I think it may have been to screenshots automatically being copied to the desktop clipboard. This behavior is changed in the latest update.
