### ISSUE TITLE
Logged out and now cannot log back in.  Link in email to verify it just hangs.

### ISSUE THREAD

**Issue by DarrenRBeckett** [koush/vysor.io#714]
I logged out of Vysor and went to log back in.  It sends me a verification code to my gmail but when I click on it to verify, it just hangs.  Have tried Google sign in too with the same issue.
I am now logged out with crappy refresh rate on my display.  I use this for corporate demos. Anyone any ideas? Version 4.0.28 with a lifetime license.

**Comment by koush** [comment]
You were you using the email/password login with a gmail account?
If you tried using google sign in, where does it error out?

Screenshots would be helpful.

**Comment by koush** [comment]
Also, are you behind a corp firewall or vpn?
