### ISSUE TITLE
Paste not Working

### ISSUE THREAD

**Issue by dddcooke** [koush/vysor.io#715]
When I paste to Android that has charecters like ' or new line it will not paste.  For the ' in notepadd++ I retyped it and it pasted but nothing that has a new line to paste.

**Comment by koush** [comment]
are you using international keyboard or no?

**Comment by dddcooke** [comment]
I tried that but not sure if it's the right one or if it's setup correctly?

![image](https://user-images.githubusercontent.com/34900955/107115119-5d6fd700-6838-11eb-8ba6-0b5145a2a311.png)

**Comment by dddcooke** [comment]
I’ve updated the post any feed back would be appreciated.  thanks

**Comment by dieskim** [comment]
@dddcooke - try these steps to get Pasting working again - does it work for you?

 1. FORCE STOP the Vysor app on the phone
 2. wait a minute
 3. change the phone back to the Vysor Keyboard

**Comment by dddcooke** [comment]
I canceled my subscription after no response for 3+ weeks
