### ISSUE TITLE
Android: Error Connecting to Android Devise Error: apk path failed(empty)

### ISSUE THREAD

**Issue by toshi-ue** [koush/vysor.io#716]
**Describe the bug**
I bought an Android device for the first time and found this app so I tried to use it.
The terminal is Xiaomi Redmi Note 9S.

When you connect the device and press the button to see the device of the Mac app,
It is displayed as below and nothing works.
```bash
Error Connecting to Android Devise Error: apk path failed (empty)
```

Please teach me how to fix this problem.

**Attach a Vysor Bug Report Log**
Vysor Bug Report Link: [Vysor Logs](https://gist.github.com/VysorLogs/9fb29404bad38739a005700cff367b0e)contains the application errors and logging]

**To Reproduce**
1. Install and launch the Vysor app on Android
1. Install and launch the Vysor app on Mac
1. Connect Android device (successful recognition)
1. Click View Devise (Error occurred in MacOS app, Android Vysor app is deleted from the device)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave(10.14.6)
 - Vysor Version: 4.0.17

**iOS/Android (please complete the following information):**
 - Device: Xiaomi Redmi Note 9S
 - OS: Android 10(MIUI Global 12.0.3)
 - Vysor Bug Report Link: [Vysor Logs](https://gist.github.com/VysorLogs/9fb29404bad38739a005700cff367b0e)contains the application errors and logging]

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.
I don't know how do this.

https://user-images.githubusercontent.com/46378023/107185256-7689ab00-6a25-11eb-8ac1-a8a98a10e055.mov

**Comment by techkovery** [comment]
Same problem with all my handheld devices with android 4.3

**Comment by wwiraone** [comment]
> **Describe the bug**
> I bought an Android device for the first time and found this app so I tried to use it.
> The terminal is Xiaomi Redmi Note 9S.
> 
> When you connect the device and press the button to see the device of the Mac app,
> It is displayed as below and nothing works.
> 
> ```shell
> Error Connecting to Android Devise Error: apk path failed (empty)
> ```
> 
> Please teach me how to fix this problem.
> 
> **Attach a Vysor Bug Report Log**
> Vysor Bug Report Link: [Vysor Logs](https://gist.github.com/VysorLogs/9fb29404bad38739a005700cff367b0e)contains the application errors and logging]
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Install and launch the Vysor app on Android
> 2. Install and launch the Vysor app on Mac
> 3. Connect Android device (successful recognition)
> 4. Click View Devise (Error occurred in MacOS app, Android Vysor app is deleted from the device)
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacOS Mojave(10.14.6)
> * Vysor Version: 4.0.17
> 
> **iOS/Android (please complete the following information):**
> 
> * Device: Xiaomi Redmi Note 9S
> * OS: Android 10(MIUI Global 12.0.3)
> * Vysor Bug Report Link: [Vysor Logs](https://gist.github.com/VysorLogs/9fb29404bad38739a005700cff367b0e)contains the application errors and logging]
> 
> **Android Logcat**
> If you are familiar with adb logcat, please include the log output of any crashes to this issue.
> I don't know how do this.
> 
>  2021-02-08.15.47.50.mov

just allow "install via USB" on developer option

**Comment by cmmelia** [comment]
Adding to discussion....

I have been using Vysor for more than a year with much success. I regularly access an Amazon Fire Tablet, Assus Zen Tablet, Samsung Galaxy S7 and Samsung Galaxy S4 (Android 5.0.1) from a Windows 10 Acer laptop . I recently rooted the Samsung Galaxy S4 (Verizon SCH-I545) and successfully flashed the stang5litre ROM. Vysor sees the device, but now reports the "Error Connecting to Android Devise Error: apk path failed (empty)" message when trying to connect from the same Windows 10 device. I have uninstalled and reinstalled Vysor and ADB drivers on the laptop, and uninstalled and reinstalled Vysor on the S4 several times with corresponding reboots/restarts.

The connection attempt cycles through these messages:

Checking Vysor APK installation
Uninstalling older Vysor APK
Installing Vysor APK
Checking Vysor APK installation
Uninstalling older Vysor APK
Installing Vysor APK (legacy packaged)
Checking Vysor APK installation

Then a popup box with the "Error Connecting to Android Devise Error: apk path failed (empty): message appears with a choice to Retry or Cancel.

Bug Report following above error:

id 106094670989605304767
email hidden@gmail.com
C:\Users\chris\AppData\Roaming\vysor
https://vysorelectron.clockworkmod.com/#/android-device/hidden
process.versions {"node":"12.13.0","v8":"8.0.426.27-electron.0","uv":"1.32.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"76","nghttp2":"1.39.2","napi":"5","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"8.3.0","chrome":"80.0.3987.165"}
package.json 4.0.32
runtime package.json 3.1.4
os win32
electron true
pwa false
screen 870 1600 900 1600
https://vysorelectron.clockworkmod.com/#/android-device/hidden
Connecting...
enterprise cache not licensed
subscription found [object Object]
clockwork cache licensed
device status device
Checking Vysor APK installation...
Uninstalling older Vysor APK...
installing /native/android/Vysor-release.d01cd7d1fd038f8f12c70250f6eb45faf04b1287291881336b7153e11d6c9c2f.apk
fetching apk /native/android/Vysor-release.d01cd7d1fd038f8f12c70250f6eb45faf04b1287291881336b7153e11d6c9c2f.apk
Installing Vysor APK...
apk size: 4945497
adb push finished: OKAY
web apk installation result: 
Checking Vysor APK installation...
Uninstalling older Vysor APK...
C:\Users\chris\AppData\Local\vysor\app-3.1.4\resources\app.asar\native\android\Vysor-release.d01cd7d1fd038f8f12c70250f6eb45faf04b1287291881336b7153e11d6c9c2f.apk
Installing Vysor APK (packaged)...
C:\Users\chris\AppData\Local\vysor\app-3.1.4\resources\app.asar\Vysor-release.apk
Installing Vysor APK (legacy packaged)...
apk size: 4808368
adb push finished: OKAY
packaged apk installation result: 
Checking Vysor APK installation...
Error: apk path failed (empty) 

I hope that helps!

**Comment by koush** [comment]
Can you try manually installing this and see if the error goes away? Your custom rom may have a but that prevents side load scripts from working.

https://github.com/koush/vysorelectron.clockworkmod.com/blob/gh-pages/Vysor-release.apk

**Comment by techkovery** [comment]
Hi Koush , sorry, but link is dead.
Can you please put it again?

Thanks for your support

**Comment by koush** [comment]
https://app.vysor.io/Vysor-release.apk

**Comment by Flierbird** [comment]
Hi,
I was troubling with the same problem, but I solved it. It is the same solution which had been offered by @wwiraone. You should allow "install via USB" on developer option on your phone or tablet. See attached photo.


![install-via-USB](https://user-images.githubusercontent.com/83187960/116010730-86c72480-a629-11eb-8809-d7202080561f.jpg)
