### ISSUE TITLE
Enhancement: Mouse scroll wheel for zoom in/out on Android screen

### ISSUE THREAD

**Issue by tycarac** [koush/vysor.io#718]
Could the mouse scroll wheel be used to zoom in/out on Android screen?  The guesture is two-finger pinch zooms already on Android but can it be linked to scrolling a Windows mouse scroll wheel?

**Comment by koush** [comment]
Unfortunately there's no key event to that will request a zoom in/out.

**Comment by plaurent75** [comment]
Bluestacks has a key mapping allowing to zoom in/out with up/Down keyboard.
