### ISSUE TITLE
Unable to login to my account!

### ISSUE THREAD

**Issue by junangel12** [koush/vysor.io#719]
I got signed out of my Pro account and when i tried signing in again it is unresponsive. It takes me to google to sign in and it gives me the code to paste it to the desktop app, but when i hit the "log in" button, it does nothing. I tried uninstalling and reinstalling, turning off and on, but i keep having the same issue.

https://user-images.githubusercontent.com/78891119/107599243-4b09ea80-6bf6-11eb-9f52-adc79ab29c31.mp4

**Comment by koush** [comment]
That is a very old version of the app. Are you behind a firewall/vpn or something? It should take an incremental update to 4.x. You are on 3.x.

**Comment by junangel12** [comment]
I am so sorry. I even feel kind of dumb. I forgot i turned on a network blocker a couple of days ago because my computer's internet was kind of slow. I turned the network blocker off and you application updated. Everything is working great again. Thank you and sorry again for confusing my stupidity for a bug. Have a nice day!
