### ISSUE TITLE
NullPointerException for screenshot in landscape mode.

### ISSUE THREAD

**Issue by Gebitang** [koush/vysor.io#72]
- open a application which can change to landscape mode;
- change device to landscape mode.
- click screenshot button to open a chrome tab. such as "http://127.0.0.1:53517/screenshot.jpg?password=18bb207a"

"java.lang.NullPointerException" display.

**Comment by Gebitang** [comment]
https://plus.google.com/114372995047612156304/posts/dVDduahH2Ha

**Comment by koush** [comment]
fixed
