### ISSUE TITLE
Android: Feature Request - Provide A Setting To Disable Accidental Touch Protection When Connected To Vysor

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#721]
## Describe the situation (When _____)

I've explained the way Accidental Touch Protection (ATP) functions, the way in which I use it, and how it relates to Vysor below in the [Additional Information](#Additional-Information) section below.

When I wake my phone via Vysor to interact with it I always have to first swipe away a interaction-blocking overlay that is displayed by ATP.

## Describe the motivation (I want to _____)

If possible I'd like a setting to be added to Vysor that I could enable that would effectively, "pause" the ATP on my device connected and, "resume" it when disconnected.

## Describe the expected outcome (So I can _____)

So that at the point in time my device is connected to Vysor I will not have to swipe away the ATP screen every time I wake my device via Vysor.

Additionally when my device is disconnected from Vysor my device will continue to implement ATP and I will not have to manually enable/disable the setting every time I want to use/disconnect from Vysor.

## Screenshots

Picture of ATP screen that has to be dismissed every time I wake my phone via Vysor to interact with it

![image](https://user-images.githubusercontent.com/47487276/108390174-0376f600-71d6-11eb-8205-fb4159ffbd66.png)

## Desktop
 - **OS:** Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
 - **Vysor Version:** Vysor Pro v4.0.29 (Individual License)

## iOS/Android
 - **Device:** Samsung Note 9 (Model#: SM-N960U)
 - **OS:**
     - Android 10 (Kernel v4.9.186)
     - Samsung OneUI v2.5

## Additional Information

ATP protects your phone from accidental touch input when the device is in a dark place such as a pocket or bag.

When my phone is connected to Vysor via usb cable I leave my phone face-down on my desk. Primarily to eliminate the risk of anything being dropped on the screen which is more fragile than the back of the phone which is fully encased in a protective case. As well as so my screen is not visible and not distracting to me.

When my phone is face down the light sensor does not detect any light which triggers the ATP that I have enabled in settings. 

When ATP activates, it throws up an interaction-blocking a overlay on the device screen with a lock icon in its center. I must swipe on that lock icon to dismiss the screen. Every time I wake my phone via Vysor to interact with it I have to swipe this screen away. 

Please see the screenshot attached above in the [Screenshots](#Screenshots) section that shows what this looks like.

This setting is very convenient when my phone is actually in a dark place such as my pocket or a bag or whatever, but in this scenario it is tedious. The solution of having to constantly disable and enable this device setting whenever I want to use, and stop using Vysor is as well equally tedious.

**Comment by koush** [comment]
Understood. Will see if there's a way to do this.

**Comment by koush** [comment]
Do you know by chance the system setting that is used to enable/disable this? You may be able to determine it by using one of the following command in adb shell:

settings list system
settings list secure
settings list global

This is not a standard Android feature so I can't look at AOSP to figure this out.

**Comment by koush** [comment]
I did not get a response, so I am closing this issue.
My suggested workaround is to use the "Display Off" feature in Vysor, and disable accidental touch protection.

I'll reopen it if I get the aforementioned settings I need.
