### ISSUE TITLE
Android: Existing Feature Enhancement (Desktop Notifications) - Don't Push Silent Notifications To Desktop

### ISSUE THREAD

**Issue by CCattano** [koush/vysor.io#722]
## Describe the situation (When _____)

When I enable Desktop Notifications for my device Vysor is sending silent notifications to the desktop.

## Describe the motivation (I want to _____)

I want to not receive device notifications that are categorized as, "silent" on my Desktop from Vysor.

## Describe the expected outcome (So I can _____)

So I can take advantage of the Desktop Notifications feature and not be spammed by silent notifications that are/can be pushed at a high frequency. (Please see some high-frequency examples in the [Additional Information](#Additional-Information) section below)

## Screenshots

Screenshot showing the notifications in the, "Silent Notifications" category.

![image](https://user-images.githubusercontent.com/47487276/108396664-b3e7f880-71dc-11eb-9b14-2f85995edac4.png)

Screenshot showing how any app can be configured to have its notifications be denoted as, "silent".

![image](https://user-images.githubusercontent.com/47487276/108397988-286f6700-71de-11eb-994e-5ed8af5959dc.png)

## Desktop
 - **OS:** Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
 - **Vysor Version:** Vysor Pro v4.0.29 (Individual License)

## iOS/Android
 - **Device:** Samsung Note 9 (Model #: SM-N960U)
 - **OS:**
     - Android 10 (Kernel v4.9.186)
     - Samsung OneUI v2.5

## Additional Information

The root of the reason I'm requesting this feature change is because the current implementation of Desktop Notifications is effectively useless to me if my phone is not charged at 100%

--------------------

***Charging Phone Example:***

The first attached screenshot above has a notification coming from the app, "Settings" with a body of, "Charging (3m until full)". That notification gets pushed to my device, and therefore my desktop every 60 seconds.

This is because every time the estimation for how long my phone will take to fully charge decreases by one minute a new notification takes the place of the old notification which then gets pushed to my desktop.

On Windows the default behaviour for receiving a desktop notification is that a visible window appears in the bottom right corner of your primary monitor, and a notification sound plays through your default audio output device.

This is causing me to see distracting popups in one minute intervals accompanied by a notification sound that is louder than whatever audio might be playing at the point in time in which the notification is triggered.

Due to this frequency and no current way to have Vysor not push this charging notification that updates every 60 seconds I have to disable Desktop Notifications entirely because of the spam.

--------------------

***Pedometer Example:***

Desktop Notifications become exceptionally unusable if I am walking with my device on my person connected to Vysor wirelessly. In the first attached screenshot, there is a notification coming from the, "Samsung Health" application, who's body content is, "63 steps"

I have a standup desk and a low-profile under-desk treadmill. I'll use this to walk while I'm working for general health purposes, but every step is a new notification.

At ~100 steps-per-minute, give-or-take, I'm assaulted with ~2 notifications per second unendingly unless I disable the Desktop Notification functionality.

--------------------

***Per-App Specification Granularity:***

These notifications are categorized as silent, meaning when they occur my phone in no tangible way notifies me to the fact that the push notification was pushed.

This behaviour can be specified on any native application installed on my device. Please see the second attached screenshot where this setting can be set.

So there could be more use cases in the future where I do not want to be tangibly notified by an application when it sends a push notification.

Ideally I'd like Vysor to honor this, "silent" categorization and not push those notifications to my desktop.

**Comment by koush** [comment]
I'll need to see if silent notifications are flagged somehow so that I can also filter them from Vysor. Thanks for the report.

**Comment by koush** [comment]
I've confirmed that Silent notifications are not reported in Android 12. Will see if this is an issue on older ones.

**Comment by koush** [comment]
Unfortunately I can't download it on the android 10 emulator. I'll add some logging to see if I can get the metadata of the notifications from you directly.

**Comment by koush** [comment]
Tracking filtering:
https://github.com/koush/vysor.io/issues/850
