### ISSUE TITLE
Mac: Vysor wireless disconnect every few hours

### ISSUE THREAD

**Issue by Privaler** [koush/vysor.io#723]
**Describe the bug**

I have a physical disability and thanks to this application I can use the mobile from the computer with the mouse, without depending on help.

I have been a Vysor user for many years (more than 5 years I use it on Windows), the problem is that since I have a Mac (Mac Mini M1), every few hours my mobile phone is disconnected from Vysor and I have to ask for help to return to connect it by cable, re-enable the wireless connection and disconnect the cable again (if I always leave connected by cable, the battery of the mobile would be damaged when charging without stopping), when this happens several times a day, it is very uncomfortable for me , I depend on help from third parties.

**Attach a Vysor Bug Report Log**

https://gist.github.com/VysorLogs/f8512d3ecc4d7cce24888bf7efb17605

**Expected behavior**

Vysor is an essential application for me, without it I cannot use my mobile phone. But being connected wirelessly it disconnects every few hours, in Windows it did not happen to me. So I would like to know what the problem is.

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.1
 - Vysor Version 4.0.29

**iOS/Android (please complete the following information):**
 - Device: OnePlus 7 Pro Android 10, Pixel 2xl Android 11 and Pocophone F1 Android 10 
 It happens with all three

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Android Logcat**
If you are familiar with adb logcat, please include the log output of any crashes to this issue.

**Additional context**

**Comment by koush** [comment]
It sounds like the M1 is powering down the wifi. You may want to try connecting directly via wireless using the "connect network device" option. You only need to enable wireless mode once between reboots.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/73924/108636277-22c18d80-7439-11eb-9bff-fe144e0633ca.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/73924/108636282-28b76e80-7439-11eb-8517-e59a490484ae.png">

**Comment by koush** [comment]
That way you won't need to reconnect the phone to USB, just connect straight to wireless from the M1.

**Comment by Privaler** [comment]
Thank you very much for answering me, can you explain to me where do I get Network Address? Sorry I don't know how to do it

**Comment by koush** [comment]
It's your phone's IP address. usually found in wifi settings on your Android.

**Comment by Privaler** [comment]
Thank you very much, if I can reconnect it as you have indicated.

Do you know what the problem can be? Will you fix it in a future update of the Vysor app?

**Comment by koush** [comment]
No, because the M1 is likely putting hte wireless card to sleep. Can't be fixed without leaving computer awake.
