### ISSUE TITLE
Attempting to install 3.1.4 on Windows 7 Pro 32 bit

### ISSUE THREAD

**Issue by cscdwndrr** [koush/vysor.io#724]
at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.

![screen](https://user-images.githubusercontent.com/63620104/108809315-6f05ee00-755d-11eb-8468-e966a9ef4f65.png)
![screen2](https://user-images.githubusercontent.com/63620104/108809317-70371b00-755d-11eb-8df9-3b4190fd1a24.png)

[SquirrelSetup.log](https://github.com/koush/vysor.io/files/6027069/SquirrelSetup.log)

**Comment by koush** [comment]
32 bit is not supported, sorry.
