### ISSUE TITLE
Audio Mirror not working on Android (Samsung A50, Android 10, Vysor pro)

### ISSUE THREAD

**Issue by TimmyTucker** [koush/vysor.io#725]
Hi

 I've just bought the pro version to use with my Samsung A50 specifically so I can take phone calls on my PC. When I toggle the audio, and accept the streaming, the sound still only comes from my phone. Can you help please?

Thanks 
Tim

**Comment by TimmyTucker** [comment]
Forgot to say I'm using a Windows 10 laptop and have tried USB and wireless connection

**Comment by DCeric** [comment]
Well he closed my thread for whatever reason saying "Android Audio Mirroring is very reliable".  Well guess that solves the $60 I spent on software that doesn't give me audio for whatever reason :/.

**Comment by koush** [comment]
> Well he closed my thread for whatever reason saying "Android Audio Mirroring is very reliable". Well guess that solves the $60 I spent on software that doesn't give me audio for whatever reason :/.

it would help to use the issue template, you didn't even mention you had a bug.

**Comment by koush** [comment]
> Hi
> 
> I've just bought the pro version to use with my Samsung A50 specifically so I can take phone calls on my PC. When I toggle the audio, and accept the streaming, the sound still only comes from my phone. Can you help please?
> 
> Thanks
> Tim

Please use the issue template. You did not provide a generated bug report.
