### ISSUE TITLE
Vysor stuck on "installing vysor APK..." Web version, Huawei P30 Pro

### ISSUE THREAD

**Issue by TechNerd22** [koush/vysor.io#726]
I'm using the web version of Vysor, and I download it from the Google Play store, open the app in Chrome (I'm using a Chromebook BTW), connect my phone, but then it uninstalls the app and then freezes on "Installing Vysor APK..." How can I fix this?

My phone is a Huawei P30 Pro VOG-L04 running Android 10, no root.

**Comment by yoyomonem** [comment]
Why? What happened to your HUAWEI P30 Pro?

**Comment by yoyomonem** [comment]
Did your HUAWEI P30 Pro freeze when you plugged your HUAWEI P30 Pro to your Chrome book?

**Comment by stavrogin78** [comment]
> I'm using the web version of Vysor, and I download it from the Google Play store, open the app in Chrome (I'm using a Chromebook BTW), connect my phone, but then it uninstalls the app and then freezes on "Installing Vysor APK..." How can I fix this?
> 
> My phone is a Huawei P30 Pro VOG-L04 running Android 10, no root.

hi there! I'm having the same problem, did you solve it? cheers
