### ISSUE TITLE
Vysor stuck on "Connecting to Vyson on Android..."

### ISSUE THREAD

**Issue by MokhtarKhorshid** [koush/vysor.io#728]
I'm trying to use Vysor Pro, for the first time, to connect to my Oculus Quest 2, but it never gets a video feed. It says "Connected to Vyson on Android..." on a black background and that's it.
I've tried restarting the device, but that did not help.

Taking screenshots from the icon on the top works though. How can I resolve this?

**Comment by CCattano** [comment]
Idk if this will work, but I experience the same thing and what I do is click anywhere inside the Vysor window that has the black background that says, "Connected to Vysor on Android..." and that click input makes the loading message go away and the feed comes up.

**Comment by firoze** [comment]
I ran into this issue earlier today ("Connecting/Connected to Vysor on Android" but does not switch to the video feed, different device though) and what I ended up doing was hitting **Reset Vysor** in the toolbar in the bottom of the main window. This ended up reinstalling/refreshing both on my computer and my phone and was working normally after that.

**Comment by koush** [comment]
Follow the bug report template instructions.
