### ISSUE TITLE
Charged for Subscription, But Unable to Obtain License 

### ISSUE THREAD

**Issue by mB-PiBox** [koush/vysor.io#730]
I was charge for the monthly subscription to my debit card, but it says I don't have an active license.
Additionally there is no way to manage/cancel any subscriptions on the site.

"Subscription is incomplete. Initial payment failed. Please update your card." Appears at the top of the subscription page. However I know the card details are fine, the account is well funded, and I have a charge showing from VYSOR in my bank app.

**Comment by koush** [comment]
Sorry about this confusing error. The card was charged, but then blocked by my payment rules due to what is likely a zip code mismatch. This is done to prevent fraud. It will be refunded. I recommend verifying you have the correct code.
