### ISSUE TITLE
Android: Can't view my device (apk path failed (empty))

### ISSUE THREAD

**Issue by stooneg0mes** [koush/vysor.io#732]
The application recognizes my device, however when trying to view the device I get this error.
I installed Universal ADB Drivers & my device has usb debugger enabled.

![image](https://user-images.githubusercontent.com/53417375/109894067-8cc50880-7c6b-11eb-84c2-8964dc47c7ee.png)

**Comment by koush** [comment]
Follow the bug report template instructions.
