### ISSUE TITLE
Connect wirelessly without having to connect wired first

### ISSUE THREAD

**Issue by gdmtplays** [koush/vysor.io#733]
Hi, not sure if this is the correct are to request this but is this possible? I just wanted to be able to directly connect wirelessly without having to connect my device wired first. Overall, love this app and have been a pro user for almost 3 years now. More power to you, sir.

**Comment by koush** [comment]
Sorry, this is not possible. It may be in the future, but in a limited capacity (by using bluetooth keyboard/mouse emulation).
