### ISSUE TITLE
iOS: Vertical scrolling doesn't work

### ISSUE THREAD

**Issue by PEZ** [koush/vysor.io#734]
Thanks for Vysor. It it such a wonderful tool! Currently I can only use it with Android, because of this and because of #680, but even so I have so much use for it! ❤️ 

On to the bug report:

> Vertical scrolling is either not happening or happening a lot

1. If I try to drag, nothing happens.
2.If I use the scroll gesture on my Mac it seems to scroll like mad.

**To Reproduce**
1. Be on the iOS home screen
2. Try dragging up down
3. Try use the scroll gesture on your computer (or scroll wheel)

**Expected behavior**
For 2: The screen is dragged with your finger
For 3: The screen scrolls smoothly like it does with Android devices

**Screenshots**
I don't have the time right now. Let me know if you can't understand the repro, and I'll produce a video for you.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2
 - Vysor Version 4.0.17

**iOS/Android (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.4
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/cf69a7baa0208f973c338c163afc1b47

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - MacBook Pro 16 inch, 2019
 - No other devices connected with computer via Bluetooth
 - I have a BLE device .. but even disconnecting that one, it doesn't work (and I can't really, because that device is what my job is about 😄 )

**Additional context**
Horizontal scrolling seems to work, at least dragging. Scroll gesture is hard to tell because even a pixel of vertical scrolling then cause the vertical scroll bug I am reporting.

**Comment by koush** [comment]
Can you confirm that you enabled assistive touch? The mouse can't be used for gestures without that enabled.
