### ISSUE TITLE
Screenshots from iOS devices disappearing immediately upon close of app

### ISSUE THREAD

**Issue by wvw999** [koush/vysor.io#735]
**Describe the bug**
Screenshots taken from iOS devices will be written to the destination folder but will disappear from that folder within two minutes. Additionally, if you close Vysor, the files disappear *immediately*

Finder is unable to locate the files, they are not in the Trash or in virus protection quarantine.

Screenshots from Android devices do not appear to be affected

**To Reproduce**
1. Create screen shot for iOS device
2. Watch the destination folder where the file is created

**Expected behavior**
file will be created and stay where you put it

**Screenshots**
See attached video:
"TestShot.jpg" is an Android screenshot created at 12:06pm
"iPhoneBikeTrue.jpg" is an iPhone screenshot created at 12:09pm
At @1:06 in the video, or 12:12pm, the iPhone screen shot will disappear from Finder

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Vysor Version 4.0.17

**iOS/Android (please complete the following information):**
IPHONE X
software version 14.4
Model no MQCK2LL/A

iPad
software version 14.4
model no MP2F2LL/A

 - Vysor Bug Report Link: 
 https://gist.github.com/VysorLogs/955120a343b640b9dd2d93721984dea0

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
??

**Android Logcat**
na

**Additional context**

https://user-images.githubusercontent.com/32399152/110995078-99fa8b00-832e-11eb-98ff-b0f2d099d4cc.mp4

**Comment by koush** [comment]
oh wow, ok I'll take a look. I wonder if this is flagged as a temp file and getting nuked automatically by the system.

**Comment by koush** [comment]
I see, the download is not actually sending a completion event, which is making electron think it's a busted download and deleting the file.

**Comment by koush** [comment]
Fixed in 4.0.32

**Comment by koush** [comment]
click reload and it will automatically update.
