### ISSUE TITLE
Okay so as usual just wanted to know more about the Audio Mirroring and Win Updates

### ISSUE THREAD

**Issue by DCeric** [koush/vysor.io#737]
How to fix Audio Mirror or use other way's to make audio work and any news about future Windows Updates.

I'm currently using a budget phone so I hope that's not an issue for why its not happening.  I have looked in previous Audio Mirroring posts but from what I seen it never solved the problem.

I did hear about a possible beta fix for this issue and I'd be open for testing if it's available.

I know no dev likes to be hounded about a new version but was wondering if there is anything coming soon for Windows 10?

**Comment by koush** [comment]
Android 10 audio mirroring is very reliable. The old version uses Chromecast audio emulation and will be removed. I'm not sure what you're asking about Win 10? It's being updated continually. iOS support is coming as well.
