### ISSUE TITLE
Vysor lifetime pass

### ISSUE THREAD

**Issue by Allan4WD** [koush/vysor.io#738]
The login process no longer allows me access to the PRO version. I have used my email address that was used to purchase the product on 24 Feb 2019.

**Comment by omegavladd** [comment]
I have this same issue, tried to reach out to them via Twitter cause I saw them responding to others with this issue with no success. Even tried to email clockworkmod since vysor doesn't have any actual information for this issue on the site. :(

**Comment by koush** [comment]
Hi all, please use the bug report template when creating an issue. It's there for a reason. There's zero information in this bug report. Would be happy to help otherwise.

**Comment by koush** [comment]
The bug report template directs you to generate a bug report, which includes stuff like account information that I'd need to look up your license, etc.

**Comment by omegavladd** [comment]
I did use the bug report, 2 weeks ago as I thought it was a bug, then I started looking on your social media platforms where I noticed it was an issue and waited patiently ;)

**Comment by koush** [comment]
> I did use the bug report, 2 weeks ago as I thought it was a bug, then I started looking on your social media platforms where I noticed it was an issue and waited patiently ;)

I understand, but since this is a user account license bug, I need issues and bug reports per user, as they are generally user specific.
