### ISSUE TITLE
Not able to share the URL when running vysor from my local

### ISSUE THREAD

**Issue by ranjithswamy** [koush/vysor.io#74]
Start vysor from local : node app.js
![issue1](https://cloud.githubusercontent.com/assets/1996366/10426296/5c727a30-70fc-11e5-8f66-e11e050074bd.jpg)

After using the URL from remote machine. Im not able to connect to the device.
Am i missing something..?

**Comment by koush** [comment]
i dunno what you're trying to do. this is just the vysor website.

**Comment by ranjithswamy** [comment]
Hi Koush,

I took your code from Git. changed all the references of clockworkmod to my local and started vysor using node. 

Tried to access device with the above set-up. No luck.

Could you let us know how to get the vysor to run locally. Without control going to clockworkmod

**Comment by shashikiran797** [comment]
Even I am facing same issue. I am able to run it locally but I want to access the device from local network without going to clockworkmod. Please teach us how to do it.

**Comment by koush** [comment]
The URL doesn't actually use clockworkmod. All the peer to peer connection info is in the URL.

**Comment by shashikiran797** [comment]
Thanks for the reply, Koush. Is there any way I can share the URL within my local network?
