### ISSUE TITLE
Black Screen With Specific Device When Connecting to Chromebook

### ISSUE THREAD

**Issue by TheMinimalist187** [koush/vysor.io#742]
Hello.  I am connecting my Motorola g4 play (2021) to my Chromebook with USB debugging through vysor.io, and when it's connected, all that shows is a black screen.  I can still click the black screen to access apps on my phone, but it is hard to do anything with nothing being displayed.  Also, a java error pop-up shows when I try to view my phone screen.

**Comment by koush** [comment]
please use hte issue template.
