### ISSUE TITLE
Android: Can't connect wirelessley. (Pro-Subscription Active)

### ISSUE THREAD

**Issue by binabdilwali** [koush/vysor.io#743]
**Describe the bug**
After pressing the Wifi connect button, when I disconnect the wire the mirroring disconnects too. Check the video for a walkthrough

**Attach a Vysor Bug Report Log**

Before Disconnecting
https://gist.github.com/1d169e9f3621778cce7c95033f91c418

After Disconnecting
https://gist.github.com/1d169e9f3621778cce7c95033f91c418

**To Reproduce**
Check video

**Expected behavior**

**Screenshots**
Check this video

https://user-images.githubusercontent.com/44670449/112260717-84188e80-8c7b-11eb-85a7-fce8180c0c77.mp4

**Desktop (please complete the following information):**
 - MacOs
 - Version 4.0.17 (4.0.17)

**iOS/Android (please complete the following information):**
 - Device: Samsung Note9
 - OS: Android 10

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**

**Android Logcat**

**Additional context**

**Comment by koush** [comment]
I see the issue, you are not connected to wireless LAN. You need to be connected to the same wireless lan. Your movie and logs indicate you are only connected to 4g.
