### ISSUE TITLE
iOS: Cannot unhide keyboard

### ISSUE THREAD

**Issue by fpenguin** [koush/vysor.io#744]
**Describe the bug**
I'd like to access the international keyboard from iOS but I can't switch between languages using a PC computer, or unhide on-screen keyboard from iOS

**To Reproduce**
1. Go to settings
2. International keyboard option does not exist, unlike from Android phones.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.2.3
 - Vysor Pro 4.0.32

**iOS/Android (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: 14.4.1

**iOS Bluetooth Issues (if using Vysor for iOS, please include the following):**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth : Logitech Keyboard K811, Apple Wireless Trackpad
 - Other devices connected with iOS via Bluetooth : Apple Watch
![Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/988396/113485947-22b7a300-9465-11eb-997e-46fe71d8535b.jpg)

**Comment by koush** [comment]
This is correct behavior. iOS does not support the international keyboard. You'll need to use the built in IME until I figure out how to add support.
