### ISSUE TITLE
iOS - can't find (No iOS devices connected)

### ISSUE THREAD

**Issue by 765119** [koush/vysor.io#745]
can't detect iOS device

mac version -  macos catalina (10.15.5)

ios - iphone 11 (14.0.1)

**Comment by yoyomonem** [comment]
?!
    Den tisdag 6 april 2021 23:12:45 CEST, Kiran ***@***.***> skrev:  
 
 


can't detect iOS device

mac version - macos catalina (10.15.5)

ios - iphone 11 (14.0.1)

**Comment by 765119** [comment]
I'm connecting ios device through USB but it says no ios devices connected (attached pic for reference)
![Screen Shot 2021-04-07 at 1 54 42 PM](https://user-images.githubusercontent.com/73659561/113919216-f70c2400-97a8-11eb-8287-a4aa20d65262.png)

**Comment by GhostWireless** [comment]
I use Vysor frequently for my work and purchased a Macbook Pro and iPhone X to run for my client, only to have this error no matter what I do.

Any input would be GREATLY appreciated.

**Comment by 765119** [comment]
seems most of us facing same issue, do you guys support iOS?

**Comment by GhostWireless** [comment]
Any drivers or anything additional suggested to connect?

**Comment by 765119** [comment]
@yoyomonem

**Comment by koush** [comment]
Hi, can you try locking the phone, and then connecting it, and then unlocking it while connected? Then click "Reload Vysor"? I've noticed this issue on occasion, and it seems macOS loses track that the phone is connected and authorized.

**Comment by GhostWireless** [comment]
It never establishes a connection in the first place. This specifically is an iPhone X. I have tried all trouble shooting and have done reinstalls to ensure this issue but nothing I do will register the device via Vysor.

**Comment by 765119** [comment]
@koush  tried couple of times with same steps before posting this issue but no luck

**Comment by koush** [comment]
> It never establishes a connection in the first place. This specifically is an iPhone X. I have tried all trouble shooting and have done reinstalls to ensure this issue but nothing I do will register the device via Vysor.

If you open QuickTime, and go to Movie Recording in the menu, does your phone show up as an input device? Are you using the provided Apple cable (and not a third party charge only cable)?

**Comment by 765119** [comment]
I can see my phone on QuickTime but not on vysor

**Comment by koush** [comment]
> I can see my phone on QuickTime but not on vysor

Leave QuickTime open. Then, click quit vysor (from the application menu) and restart it, and let me know if it shows up.

**Comment by 765119** [comment]
<img width="997" alt="Screen Shot 2021-04-12 at 1 47 51 PM" src="https://user-images.githubusercontent.com/73659561/114445532-ce63a000-9b95-11eb-8ce5-63a887956a10.png">

i did quit vysor and re-opened it.

**Comment by 765119** [comment]
<img width="984" alt="Screen Shot 2021-04-12 at 1 50 34 PM" src="https://user-images.githubusercontent.com/73659561/114445773-1682c280-9b96-11eb-8c6a-68e06cdf0670.png">

i did quit vysor and re-opened it

**Comment by koush** [comment]
@765119 oh I noticed you're on Catalina, have you tried this on Big Sur yet?

**Comment by 765119** [comment]
have upgraded catalina recently never tried on Big sur

**Comment by 765119** [comment]
will update to Big sur and let you know

**Comment by 765119** [comment]
same issue on Big Sur
![Uploading Screen Shot 2021-04-12 at 3.48.47 PM.png…]()

**Comment by koush** [comment]
Can you attach a bug report. There's a bug report button in the main vysor window.

**Comment by stanleylhs** [comment]
I have exactly the same issue, can mirror device in QuickTime, but not shown in Vysor.

iPhone 6S iOS 12, MacOS Mojave 10.14.6

Is my device combo support, if so I will submit a bug report.

**Comment by koush** [comment]
> I have exactly the same issue, can mirror device in QuickTime, but not shown in Vysor.
> 
> iPhone 6S iOS 12, MacOS Mojave 10.14.6
> 
> Is my device combo supported? If so I will submit a bug report.

iPhone 6s is not supported. There seems to be issues prior to iPhone 8. Need to investigate.

**Comment by 765119** [comment]
I posted the versions when i created the ticket, any ETA to fix this issue, is it working for anyone?
mac version - macos catalina (10.15.5) OR Big Sur
ios - iphone 11 (14.0.1)

**Comment by koush** [comment]
> I posted the versions when i created the ticket, any ETA to fix this issue, is it working for anyone?
> mac version - macos catalina (10.15.5) OR Big Sur
> ios - iphone 11 (14.0.1)

I was responding to another commenter. iPhone 11 is supported. I need a generated bug report of the failure please.

**Comment by 765119** [comment]
my Vysor is updated and it's working now :)
