### ISSUE TITLE
Login to support.vysor.io to download invoices not working

### ISSUE THREAD

**Issue by BenjaminZaiser** [koush/vysor.io#746]
**Describe the bug**
I really like your Vysor app but the administration interface support.vysor.io to download invoices for our internal billing is not working as expected - I cannot login!

**To Reproduce**
1. open https://support.vysor.io (tried it with Firefox, Chrome, Edge, and even Internet Explorer; without Incognito Mode)
2. click on login
3. login with Google
4. Sorry, your browser doesn't support 3rd party cookies and that's it. I'm pretty sure, that my browser *does* support 3rd party cookies.

**Expected behavior**
I'm logged in successfully.

How can I login to download the invoices?

Thanks
Ben

**Comment by koush** [comment]
try billing.vysor.io for enterprise
and billing.clockworkmod.com for individual

if it says cookies are not supported, I don't know what the issue is. is your javascript enabled? this seems like a browser issue. maybe try another pc to verify?

**Comment by joh-ff** [comment]
umm hi i use vysor and it is not connecting to my phone

**Comment by yoyomonem** [comment]
?!
