### ISSUE TITLE
Feature Request: Screen Capture to Clipboard

### ISSUE THREAD

**Issue by ChrisWoodard** [koush/vysor.io#747]
Any chance of adding a new icon to the device window allowing you to get a screen capture saved to the clipboard?  Nice simple way of sharing a screen shot with Teams chat etc. or adding to a document.  I know you can capture a screen shot to file but this is a bit long winded in some scenarios.

Thanks, top app by the way us it daily.

**Comment by koush** [comment]
when you say screen capture or screen shot? screen capture may be too large to fit in a clipboard.

**Comment by ChrisWoodard** [comment]
At the moment I am having to revert back to Android Studio: Log Cat -> Screen Capture -> Copy to Clipboard for such a feature.  It would be wonderful to have this functionality built into Vysor.  I must admit it's been many years since I have developed anything for MS Windows so I don't know how involved this would be.

Thanks.

**Comment by koush** [comment]
I see, yeah screen capture in Android Studio is screenshot. I can add this.

**Comment by koush** [comment]
4.0.33

**Comment by koush** [comment]
Is automatically copied to the clipboard.

**Comment by ChrisWoodard** [comment]
Wow that was quick, nice one ;-)
What are the chances of getting a separate Navigation Bar button for copying to the clipboard rather than having to press the 'Take Screenshot' button and then cancelling?

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/752?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE4MjU0NTYyMzE6NzM5MjQ%3D
