### ISSUE TITLE
Automatic update fails on Xiaomi phones using MIUI 12

### ISSUE THREAD

**Issue by morokon31** [koush/vysor.io#748]
I connect a Xiaomi MIUI12 device through adb, and tries to connect through Vyzor from my MacBookPro
Even if I enabled 'Install through USB' in the Settings of the device, the first install on the handset raises the following popup :
![Screenshot_2021-04-11-14-42-38-844_com miui securitycenter](https://user-images.githubusercontent.com/29874046/114317093-6b5e0480-9ad4-11eb-9d9f-3f9c72566c8a.jpg)

I can accomodate with this popup for first install, because then the device is physically accessible.
But when in the future there is a new apk release, vyzor will first uninstall older release, then tries to install the new release
This raises the same popup, even if I checked the 'remember my choice' on first install.
This is an issue because on update, my handset is not physically accessible.
So I'm in a deadlock situation : vyzor is not installed anymore, installing it requires to click on the handset screen, which requires vyzor ... 

I assume the main bug is coming from MIUI which does not remembre my choice => I'm on the way to post a bug report to Xiaomi

As a workaround, would it be possible to modify the update procedure of vyzor apk : installing newer version on top on older one could be an option (avoid to uninstall first)

**Comment by koush** [comment]
I think there's a option in settings to disable apk install check/prompt over usb? if you find it, can you take a screenshot so I can add this to the support wiki?

**Comment by morokon31** [comment]
There is an option called 'Install via USB' and subtitled 'Allow installing apps via USB' in the developper options (see attached screenshot)
 

But is does not behave as expected : 
	- checking this settings allows to install apps via USB, with the confirmation popup to click on.
	- unchecking this settings forbids to install apps via USB : non confirmation is then asked

And there is no option to disable apk install check/prompt over usb ... 

I found a dirty workaround : while launching vyzor on a target, I inspect logcat output on that target, waiting for a message indicating the presence of the confirmation popup.
Then I emulate clicks at appropriate positions ... 

#!/system/bin/sh
echo "Waiting for stupid popup ... "
logcat -c
logcat | grep --line-buffered 'ActivityTaskManager: START .* cmp=com.miui.securitycenter/com.miui.permcenter.install.AdbInstallActivity' | ( read a 
echo "Popup appeared, clicking on it ..."
sleep 0.1
input keyevent KEYCODE_TAB                                                                     
sleep 0.1
input keyevent KEYCODE_ENTER  
sleep 0.1
input keyevent KEYCODE_TAB                                                                     
sleep 0.1
input keyevent KEYCODE_ENTER  
sleep 0.1
exit
)

Regards,
Matthias

**Comment by koush** [comment]
Can you try this?

https://stackoverflow.com/a/50716426

There's another verification option apparently?
