### ISSUE TITLE
resolution in "Customize Vysor"

### ISSUE THREAD

**Issue by joachim97** [koush/vysor.io#750]
Is it possible to set the resolution for a specific device in customize vysor ? I would like to permanently set the original resolution.
I refer to #211 solution. Section "devices entry".

**Comment by koush** [comment]
No, that has to be done through the settings UI, but that setting is device specific.

**Comment by joachim97** [comment]
You can add this option in the next version. For me, in the original quality, the image looks much better and it would be easier if I could set it up once and for all.

**Comment by koush** [comment]
If you set it, the setting gets saved permanently. I won't be adding this to customize vysor.

**Comment by joachim97** [comment]
It is my problem that I have to set up anew every time I connect. And it cannot be set permanently.

**Comment by koush** [comment]
Ok, I misunderstood. It should be saving the resolution. You are clicking "Save" right? Can you share a generated bug report as per the issue template instructions?

**Comment by koush** [comment]
To be clear, "Customize Vysor" should NOT be necessary to keep the resolution saved-- that happens automatically once you set it for a device.

**Comment by joachim97** [comment]
Yes. To save the resolution, I click "SAVE" every time. And every time the resolution restarts.

I cannot create a report because I get "bug report failed: Network Error" every time. And I have internet connection all the time. To generate a report, click "BUG REPORT" on the bottom bar of the VYSOR main menu.

**Comment by koush** [comment]
Ok let me fix up the bug report. I think it's generating something too large.

**Comment by joachim97** [comment]
Vysor updated itself for me. The only plus of this update is that I can generate an error report. https://gist.github.com/72f32f21f341b8cf48576c668d6a0fcd
Unfortunately, in the new version, I cannot connect to my device. Every time it uninstalls and reinstall the Vysor app on your phone. And then he throws an error "Error Connecting to Android Device Error. Unable to connect to control socket."
Uninstalling and wiping app data on your phone does nothing.

**Comment by koush** [comment]
I figured out why the resolution is saving. There will be an update for this sometime this coming week.

**Comment by koush** [comment]
Resolution saving should be fixed in 4.0.40. Please confirm. If there is still an issue, please send a new bug report.

**Comment by joachim97** [comment]
This Problem is not resolved...
