### ISSUE TITLE
Vysor keyboard is set to off every time the device is connected

### ISSUE THREAD

**Issue by priyadi** [koush/vysor.io#751]
If I connect the phone to the computer, Vysor connects, but the Vysor keyboard is then set to off. I have to go to settings to enable it to use it. And it is annoying to do it every time I plug it in.

It used to work before, but I don't know if it is caused by a specific Vysor update or Android update.

My device is Samsung Galaxy Note 10+

**Comment by koush** [comment]
Did you click save in the settings? Is it being unchecked in the UI somehow?

**Comment by priyadi** [comment]
There is no "save" button in Android's setting. Enabling "Vysor" in the "keyboard list and default" section will enable it immediately, and "vysor" will appear as one of the keyboard options to use.

But if I start connecting vysor to the device, then it will disable the vysor keyboard that was previously enabled.

**Comment by koush** [comment]
<img width="629" alt="Screen Shot 2021-04-20 at 10 54 11 AM" src="https://user-images.githubusercontent.com/73924/115442385-cb386780-a1c6-11eb-8ba2-461db6a52e6c.png">

**Comment by priyadi** [comment]
sorry, I did not realize that "vysor keyboard" is related to vysor's "international keyboard". yes, it fixed the problem.
