### ISSUE TITLE
Vysor Screenshot function clearing clipboard when taking a screenshot

### ISSUE THREAD

**Issue by npfister13** [koush/vysor.io#752]
It appears that whenever you take a screenshot, the clipboard is now cleared or replaced with a blank line. This causes issues when it comes to rapidly taking screenshots with similar names but adding suffixes. It requires having to re-copy the name of the screenshot every time after taking said screenshot.

**Comment by koush** [comment]
The new screenshot feature also copies the screenshot into the clipboard for pasting. I'll fix this to add a button to either download or copy to clipboard.

**Comment by koush** [comment]
Fix coming in next update.
