### ISSUE TITLE
Cant go Wireless on Android (Samsung S10)

### ISSUE THREAD

**Issue by Margreiv** [koush/vysor.io#753]
Howdy, folks.

Im trying to go wireless on vysor but my screen is stuck on connecting to the device.

USB works fine, but whenever i click on the View Wireless button, i hear the windows sound of a usb device disconecting the screen goes black and this message appears: 
![1](https://user-images.githubusercontent.com/82854988/115327451-5c76f200-a165-11eb-9bd2-d47ffab695f4.png)

Eventually, after like 3 minutes, the screen goes back to the USB mirroring (and if i unplug it, the mirroring ends)

Now if i click on settings and on wireless mode on this black screen, the following message appear
![2](https://user-images.githubusercontent.com/82854988/115327737-d313ef80-a165-11eb-8390-143f4707d217.png)

Is there any chance you guys can help me out? Im looking for a solution to wireless mirroring for OBS, Vysor seemed like a simple solution with resonable pricing. But i need the wireless function to work!

**Comment by koush** [comment]
Will take a look please include a generated bug report per the instructions. And use the bug report template. This is an extremely weird error.

**Comment by Margreiv** [comment]
I will edit the mainpost with the correct template. Quick question tho, Does my Desktop need to be connected on wireless too? Hes on ethernet and my phone is on wireless, could that be it?

**Comment by koush** [comment]
please open a new issue with the correct template.
