### ISSUE TITLE
Android: Cant go Wireless on Samsung S10, but USB is fine.

### ISSUE THREAD

**Issue by Margreiv** [koush/vysor.io#754]
**Describe the bug**
Whenever i click on the View Wireless Option, i hear the windows sound of USB device disconnected, following by a black screen with the message, connecting to <IP ADRESS> which it gets stuck on for 2 minutes. After that it switches to USB mode. Then if i click on Wireless Mode (on the mirrored screen), an error appear saying cannot read property, enable wireless mode of null.

My computer is wired to the internet, while my mobile uses Wi-Fi.

**Attach a Vysor Bug Report Log**
https://gist.github.com/0cf03f75c4009c43dcbb8b777928ca22 (This is the stuck connecting window bug report)
https://gist.github.com/cc085c4d2f78ee6f193b1891b1c82a93 (This is the Wireless Mode of Null bug report)

**To Reproduce**
1. Click View Wireless Button on Main Screen
2. Mirrored Screen opens trying to Connect, see error.
3. On the mirrored screeen, go to the navigation bar and click Wireless Mode

**Expected behavior**
I expected to just click on go wireless, connect to the device and be able to mirror its screen.

**Screenshots**
![1](https://user-images.githubusercontent.com/82854988/115453465-0ef69580-a1f6-11eb-93a6-13424fa709f2.png)
![2](https://user-images.githubusercontent.com/82854988/115453480-128a1c80-a1f6-11eb-85ba-d5c5ea253357.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro 20H2]
 - Vysor Version [Pro 4.0.35]

**iOS/Android (please complete the following information):**
 - Device: [Samsung Galaxy S10]
 - OS: [e.g. Android 11]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Additional context**
I'm not sure if its the root cause, but my computer is connected to the internet through a ethernet cable, while the cellphone is on Wi-Fi. I use a google Wi-Fi hub and apparently everything is working on my end.

**Comment by Margreiv** [comment]
Its been a week and i had no answer on this, so i just canceled the sub.

**Comment by koush** [comment]
Sorry, was busy with other bugs. According to your logs, your device is failing to switch to wireless mode:

> provider failed, trying next Error: Device not found (serial: 192.168.86.31:5555)

**Comment by koush** [comment]
Alternatively, your wireless and wired networks are not allowing cross traffic or something.
