### ISSUE TITLE
How to disable notifications on MAC OS

### ISSUE THREAD

**Issue by DavidFaermanPendo** [koush/vysor.io#756]
I love Vysor i bought the lifetime license some time ago and i always recommend it...
BUT for some reason i started to get notifications every second of the battery and other stuff, how i make it stop showing me the notifications on mac? it is driving me crazy, and i was not able to find a disable vysor notifications on mac.
Thanks!!!!!

**Comment by koush** [comment]
<img width="573" alt="Screen Shot 2021-04-22 at 1 37 56 AM" src="https://user-images.githubusercontent.com/73924/115683519-66d2f080-a30b-11eb-8937-83f013f18f09.png">
