### ISSUE TITLE
Black screen on new update

### ISSUE THREAD

**Issue by patggg** [koush/vysor.io#758]
After Vysor pro update to 4.0.36 today the mirrored screen is black. Have tried reload vysor, reset vysor from main window. Changing decoder to any value does not help. WebAssembly connects and mouse events are sent to the device (as seen through connected monitor). Native hardware and software options result in Waiting for Decoder... that never finishes.  Force H264 gives java.lang.Exception Encoder Error in popup, regardless of decoder setting. Vysor running on Kubuntu 20.0.2 LTS connecting to Android 9 device.

**Comment by koush** [comment]
Can you generate a bug report and attach it?

**Comment by koush** [comment]
Might also wanna just try restarting the phone/computer too. Just to start from a sane state.

**Comment by koush** [comment]
There's also other useful stuff in there.

**Comment by patggg** [comment]
Ran updates on main computer and rebooted
Bug report generated
Vysor running from snap install, native app
Connecting to a ODriod N2 via ADB/USB

Still black screen

**Comment by patggg** [comment]
Been getting this every launch, does not matter if I click yes or no.
![image](https://user-images.githubusercontent.com/61442626/116308951-c565f780-a76d-11eb-89e8-834c498364af.png)

**Comment by koush** [comment]
You need to paste a link to the bug report here. Please open a new issue and use the issue template. Follow the instructions.
