### ISSUE TITLE
Android: Black Screen

### ISSUE THREAD

**Issue by patggg** [koush/vysor.io#759]
**Describe the bug**
Black screen on launch

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/efa265ccdce2e0dafb2b93aa597db8b5

**To Reproduce**
1. Launch Vysor
2. Click View Device icon

**Expected behavior**
Instead of black screen I expected a view of the android device.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Vysor Version 4 0.36

**iOS/Android (please complete the following information):**
 - Device: Odroid N2
 - OS: Android 9
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Android Logcat**
Logcat output when lauching to black screen is attached.

**Additional context**
Did full reboot of Linux host and android device
Snap install of Vysor
Device has been working with Vysor since Oct 2019
Issue began today after Vysor update

[vysor_launch_logcat.txt](https://github.com/koush/vysor.io/files/6388257/vysor_launch_logcat.txt)

**Comment by koush** [comment]
Thanks for the report. I can confirm there aren't any errors in your logs. I am unsure why this would be happening, because nothing has changed with regards to rendering in the last update. I did add a setting to change the background color, but that seems unlikely to be the problem. Just to be sure, I reverted that change, and you can check 4.0.37.

Let me know if the problem still exists in 4.0.37 or not.

**Comment by koush** [comment]
Also, please let me know if you're on multiple monitors, and have an iGPU.

**Comment by patggg** [comment]
Ok, I know where the problem originates. I have an app called "Internet speed meter lite". It runs in the Android notification bar. It uses the notification system to update the speed values to the android display. In vysor the default setting is to enable "Desktop Notifications", thus in default mode I get one message per second on my linux desktop. I find that just slightly annoying so I turned it off in vysor. When It is turned off the mirrored android screen goes black. Did not make the connection yesterday, sorry.

The specific combination that causes the issue is Desktop Notifications off using WebAssembly Decoder.

Another logcat attached. 
[decoder_switch_logcat.txt](https://github.com/koush/vysor.io/files/6391619/decoder_switch_logcat.txt)

I am using Native Software Decoder now without issue.

**Comment by koush** [comment]
Wait, when you turn notifications OFF the screen goes black?

**Comment by koush** [comment]
I'll download that app and check.

**Comment by koush** [comment]
Not seeing this on my end. Will add some logging.

**Comment by koush** [comment]
alright after you update to 4.0.45 a new bug would be appreciated. Or just close this issue if you have uninstalled that app.

**Comment by patggg** [comment]
It is not really app related. With or without the app, WebAssembly decoder gives a black screen. Native Software works fine and I am fine as long as one decoder works. If I switch to WebAssembly I get the attached logcat output. If the attached is helpful then use it as you can, but no matter to me either way.

[logcat.txt](https://github.com/koush/vysor.io/files/6525894/logcat.txt)

**Comment by koush** [comment]
Oh I see, you figured out it was WebAssembly. Good to know. Yeah, that might happen if your device is using a non-baseline h264 profile, but that doesn't seem to be the case... oh well. The WebAssembly is a fallback decoder on the native app anyways.
