### ISSUE TITLE
Four tiny screens w/o color

### ISSUE THREAD

**Issue by elpollitodiablo** [koush/vysor.io#76]
**Motorola Moto X (2013) @ Android 5.1** and **OS X 10.10.5** running **Chrome 48.0.2533.0 canary (64-bit)**

![bildschirmfoto 2015-10-13 um 14 16 30](https://cloud.githubusercontent.com/assets/11333690/10454599/01fa676a-71b6-11e5-968c-c7a3ff7ed988.png)

It is usable though. Vysor will transfer input to my phone, but frankly *this* won't be of any use :)

**Comment by amm038** [comment]
What was the resolution for this issue ? I am having same issue with vysor version 1.0.6.7
