### ISSUE TITLE
Connection error: browser has no local resources

### ISSUE THREAD

**Issue by voland66** [koush/vysor.io#760]
**Describe the bug**
Recently, I has been unable connect vysor to any of my android devices. I am only using vysor occasionally, so I am not sure when the problem started. 
I am running Linux machines and thus use PWA (I do not see linux specific versions to download). The first step seems to work, vysor requests USB authorization on the phone. It then starts installing the app, the I briefly see an "uninstalling" message and finally I have an error:
"Connection Error. Error connecting to Android Device Error: browser has no local resources".

**Attach a Vysor Bug Report Log**
Here is the link to the log: https://gist.github.com/VysorLogs/911b76229a9d018d4a70f4b536db755f
And I am attaching the text file with the log

**To Reproduce**
Attempt to connect to an android device using PWA on linux

**Expected behavior**
vysor apk is installed and connection established.

**Desktop (please complete the following information):**
 - OS: Linux, Fedora 33 & 34, Chrome (latest versions at the time of use).
 - Vysor Version 4.0.37

**iOS/Android (please complete the following information):**
 - Device: Samsung Galaxy A32 5G, Oneplus 6T, Moto E4
 - OS: [e.g. Android 9, 10, 11
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/911b76229a9d018d4a70f4b536db755f

[vysor-log.log](https://github.com/koush/vysor.io/files/6395659/vysor-log.log)

**Comment by koush** [comment]
This should be fixed in 4.0.38. Please verify.

**Comment by voland66** [comment]
Thank you, it works.
