### ISSUE TITLE
momentum scrolling

### ISSUE THREAD

**Issue by tmotrix** [koush/vysor.io#761]
Hi,

apologies if this has been answered elsewhere, I am a bit of a noob.

I am trying to automate the control of my android via my 2012 MacPro running High Sierra.  Vysor is an amazing tool but I have not been able to get it to momentum scroll via automated workflow.  I am using Keyboard maestro and have also tried Automator.  the scroll wheel action works but its very jerky, no glide at all.

the glide scroll works fine form my track pad, but I would love to be able to run a macro to smoothly scroll .

many thanks in advance and again apologies if this is very obvious.  I am an artist by trade...

@tmotrix

**Comment by koush** [comment]
This is not possible. Vysor sends the scroll event to Android, and Android will do what it wants with it.
