### ISSUE TITLE
Vysor pro lifetime license not recognized

### ISSUE THREAD

**Issue by nandini123-tech** [koush/vysor.io#764]
I have purchased annual pro license in April 2021.Vysor 4.0.38 license is not recognized. and i didn't retrieve my annual  pro license. please provide assistance to get this resolved. Thank you

**Comment by koush** [comment]
https://gist.github.com/VysorLogs/bc75431f99163fdd0d1cf91351deacf5

**Comment by koush** [comment]
This should be resolved. Please click Retrieve license again.

**Comment by nandini123-tech** [comment]
Thanks for your support to resolve this issue.
