### ISSUE TITLE
My purchase went through but I haven't Received my subscription

### ISSUE THREAD

**Issue by HrHd** [koush/vysor.io#765]
![emailprob](https://user-images.githubusercontent.com/18619241/117527396-608e7680-af91-11eb-8ae0-185a94dee293.PNG)
![vysor](https://user-images.githubusercontent.com/18619241/117527403-7c921800-af91-11eb-9db8-a332a09a1d32.PNG)

**Comment by koush** [comment]
Please include a bug report as per the issue template instructions.

**Comment by koush** [comment]
This will have your purchasing email, login email on the app, etc. Can't do much with just this information.

**Comment by koush** [comment]
Responded to email.
