### ISSUE TITLE
Android: Connection Error: displayPower is not defined

### ISSUE THREAD

**Issue by xin2014** [koush/vysor.io#766]
Can't connection when change the device settings to "Dim Display" in Display Power

![image](https://user-images.githubusercontent.com/7124907/118243349-eb5efc00-b4d0-11eb-8e8d-32a2b3fd7003.png)

![image](https://user-images.githubusercontent.com/7124907/118243283-daae8600-b4d0-11eb-97d2-0096aee3822d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Vysor Version 4.0.40

**iOS/Android (please complete the following information):**
 - Device: XiaoMi 11
 - OS: MIUI 12.5 Android 11

**Comment by eeevp** [comment]
I have the same issue with Nokia 6.1 Android 10. Also, the "Turn off display" option will cause the same problem.
My current workaround is to change the display setting to "Normal" so you can connect. 
You could change it back to other settings after you connected.
If you forgot to change it back to "normal" or face this bug the first time, you could change the setting by doing quickly as follows.
1. Press the retry on "Connection Error". Each time you press it will buy you a few seconds to open and adjust the setting.
2. In the setting panel, changed the display power to "Normal Display Power"
3. Retry again should now connect your phone.

**Desktop (please complete the following information):**

- OS: Windows
- Vysor Version 4.0.40

**iOS/Android (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 10

**Comment by clubtech** [comment]
Same error message for me with today's Vysor update and Galaxy S21 Ultra.
Log: https://gist.github.com/VysorLogs/f04d4a80bf91eb1d77c5b0e623c19297

**Comment by koush** [comment]
One moment, will fix it.

**Comment by koush** [comment]
Fixed in 4.0.41. Sorry about that, really appreciate the quick bug report here.
