### ISSUE TITLE
Vysor Audio Mirroring (not windows 10) stopped working since the last update

### ISSUE THREAD

**Issue by JaumeVera** [koush/vysor.io#767]
**Describe the bug**
Since the last update the "Vysor Screen Mirroring" doesn't appear when trying to mirror the audio. It worked fine before the update.

**To Reproduce**
1. Go to Settings.
2. Disable "Use Android 10 Audio Mirroring".
3. Connect a device by USB.
4. Press the Headsed icon in vysor to mirror audio.
5. The "Vysor Audio Mirroring" option to connect on will not appear in devices to connect.

**Expected behavior**

**Screenshots**
Screenshot with the Mirroring option to connect not appearing
https://imgur.com/zIhjHae

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Pro Version 4.0.41
 - Using Android SDK ADB binary

**iOS/Android (please complete the following information):**
 - Device: Xiaomi Redmi 5 Plus
 - OS: Android 8.1.0
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/5b03050b9652423880035076900a445a

**Comment by koush** [comment]
Thanks for this report. Some certificates I use to spoof a Chromecast expired (they expire every year) and I need to regenerate them and put out an update. Working on this now.

**Comment by koush** [comment]
fixed with update.
