### ISSUE TITLE
{Feature Request} Wireless mirroring using the web app

### ISSUE THREAD

**Issue by clubtech** [koush/vysor.io#768]
Any chance to support wireless ADB (and hence wireless Vysor) through app.vysor.io or is there a limitation of the browser to talk to the device via adb over wireless connection?
I think this was possible in the old Chrome store app (though the image quality was pretty terrible through the old app).

**Comment by koush** [comment]
It's possible, but for various technical, security, and UX reasons, I don't want to implement it. It's a big hack.
The old chrome apps supported TCP, and that stuff was all removed.
