### ISSUE TITLE
Screenshot jpg file messed up in Android 12 public preview

### ISSUE THREAD

**Issue by hatt62** [koush/vysor.io#769]
**Describe the bug**
Did a screenshot with Vysor on my Pixel 5 Device connected via USB-C / WiFi. I'm not able to open the generated jpeg-File with any image processing software. Works fine with Android 11.

 - OS: macOS
 - Vysor Version Pro 4.0.42

 - Device: Pixel 5
 - OS: Android 12 open preview

**Comment by koush** [comment]
Yup, just noticed that too. Will investigate.

**Comment by koush** [comment]
Looks like some internal API changes. Have a fix and will update shortly.

**Comment by koush** [comment]
Fixing up some other android 12 stuff... clipboard also broke. Gonna do a thorough pass and try to get everything in one update.

**Comment by hatt62** [comment]
Works perfect now. Thank you very much!
