### ISSUE TITLE
Problem showing devices screen on Ubuntu

### ISSUE THREAD

**Issue by ghost** [koush/vysor.io#77]
When I share screen to other computers there is no problem, but I cannot see it properly on my laptop (see attached screenshot). I attached Samsungs tablet and I see black and white preview, smaller and multiplicated. Additionally, touches (done from computer) work properly, so when I click with mouse at the bottom black part I get proper touch event on the device.

![screenshot](https://cloud.githubusercontent.com/assets/11553501/10509587/480a0548-732e-11e5-9069-90907bbc10bb.png)

**Comment by koush** [comment]
legacy issue, new decoder now
