### ISSUE TITLE
Vysor share endpoint of vysor.clockworkmod.com not listening

### ISSUE THREAD

**Issue by setheen** [koush/vysor.io#779]
The Vysor desktop app yields this share endpoint: https://vysor.clockworkmod.com/server#109631954117590984290
That server is not accepting connections:
`telnet vysor.clockworkmod.com 443` - Time's out

FWIW, this has never worked great for me so I always use this older style url to access devices but even this isn't working:
https://app.vysor.io/#/farm-device/109631954117590984290/DUO1926000851

Could the billing info for my user account be messed up in your firebase backend?  
1. purchased lifetime license
2. purchased enterprise license to try it out
3. removed enterprise license
4. logged out/back in to both chrome client and desktop server
5. connection errors/timeouts

**Comment by koush** [comment]
You must be running a really old client, because that share endpoint is super old that has not been used in a year at least. You didn't include a bug report either, so I'm closing due to that being the case. Please reopen once you have downloaded a 4.0.47 client.

**Comment by koush** [comment]
Current endpoints look like this:

https://vysor.io/server#123457890

**Comment by koush** [comment]
Incidentally, a bunch of changes to address Vysor share bugs have gone in since your old client. Honestly surprised they even still worked for that long. Last weekend was when I updated with a breaking change for all clients.
