### ISSUE TITLE
Screenshot functionality needs Cache-Breaker in URL

### ISSUE THREAD

**Issue by Panthaaaa** [koush/vysor.io#78]
When using the Screenshot functionality there is one issue whith copy&paste: Altough the image shown changes everytime, the copied image always stays the same. This seems to be the result of some Browser caching (see https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url).
If the images wouldn't be chached, the copy&paste would work correctly.

**Comment by koush** [comment]
ahh good point

**Comment by koush** [comment]
fixed in next version

**Comment by Panthaaaa** [comment]
👍
Thank you very much!
