### ISSUE TITLE
Screenshot keyboard shortcut no longer working with newest update

### ISSUE THREAD

**Issue by npfister13** [koush/vysor.io#780]
With the newest update adding functionality to save and image or copy it to clipboard with a popup, keyboard shortcuts to take a screenshot are no longer working.

Reproducible, just have the screenshot function assigned to a keyboard shortcut (in my case, F4). Clicking the screenshot icon works fine.

**Comment by koush** [comment]
Will investigate thanks

**Comment by koush** [comment]
Found and fixed in upcoming version.
