### ISSUE TITLE
Android: game sound not coming in obs streaming

### ISSUE THREAD

**Issue by pprasanth** [koush/vysor.io#781]
**Describe the bug**
While playing the game, game sound is not coming in obs streaming. I have enabled audio motoring and in vysor adb I'm getting the game sound. But while streaming using obs game sound not coming.

I'm using pro account for the stream in MAC BOOK PRO

**Comment by pprasanth** [comment]
I have found the solution for this issue, MAC doesn't have default desktop audio capture so need to use iShowU app and setup configuration in MAC to enable this feature.

Download link:- https://support.shinywhitebox.com/hc/en-us/articles/204161459-Installing-iShowU-Audio-Capture-Mojave-and-earlier-

Setup video:- https://www.youtube.com/watch?v=y5O6ypLAH88

Hope this will help others. Thanks.

**Comment by koush** [comment]
I'll fix this ops stream to mux in the audio as well. But currently you are correct, people are playing the audio back and capturing it.
