### ISSUE TITLE
Android: FEATURE REQUEST - Copy from Android Device Addition 

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#782]
**Describe the bug**
If you select text on the Android device then - hit COMMAND + C (Mac) / Control + C (PC) it does not copy the text on the phone - you have to do the normal android copy

**To Reproduce**
1.  Select text on Android Device
2. hit COMMAND + C (Mac) / Control + C (PC)
3. hit COMMAND + V (Mac) / Control + V (PC)
4. no text was copied

**Expected behavior**
hit COMMAND + C (Mac) / Control + C (Windows) - it would copy the text on Android and be able to Paste on your Mac / PC

**Current Fix Workaround**
By simply adding key binding = "Tab": "KEYCODE_COPY"
I was able to get copy working from the android device.
Now if I hit the TAB button it will copy from the Android Device

**Suggested Fix**
Bind COMMAND + C (Mac) / Control + C (PC) to Android's "KEYCODE_COPY"

**Comment by koush** [comment]
This should be doable with the existing APIs.

**Comment by dieskim** [comment]
I can confirm this does now work as expected.
Tested on:
- Xiaomi Mi A3 (Android  11) 
- Samsung Galaxy J4+ (Android  8.1.0) 
- Samsung A11 (Android 10)
Thank you for the fix.
