### ISSUE TITLE
Android: FEATURE REQUEST - Paste to Android Device - Set Text to Clipboard then run KEYCODE_PASTE

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#783]
**Describe the bug**
If you select text on your Mac/PC and then select a space on the Android device and hit COMMAND + V (Mac) / Control + V (PC) will send the text to Android and Paste the text - but this text is sent as text input. This is prone to failure in my testing where at times some of the text will not output and get missing.

My suggestion is to 
1. When on the Android Device and hitting COMMAND + V (Mac) / Control + V (PC) - grab the text from the Mac / PC Clipboard
2. Set the text to the Android Clipboard
3. Paste from the Android Clipboard via KEYCODE_PASTE

**To Reproduce**
1.  Select text on Mac / PC and Copy via COMMAND + C (Mac) / Control + C (PC)
3. Select a space on the Android Device
4. Hit COMMAND + V (Mac) / Control + V (PC)
4. text is pasted but output as input - not added to clipboard on android"

**Comment by koush** [comment]
I can't recall why it wasn't implemented this way, but I think I had a good reason at the time (lack of API access perhaps). I'll reinvestigate because it's been like 5 years.

**Comment by dieskim** [comment]
Great - I did notice that if you look at scrcpy they are already doing what we are talking about so you could see what they are doing for sure

https://github.com/Genymobile/scrcpy/blob/72081a241b85edc64569ece05d2178018e4913ca/README.md#input-control

and you can see what they are doing here:
https://github.com/Genymobile/scrcpy/blob/498ad23e9804cd7d7bb56bb1cd0d26b88e1830b9/server/src/main/java/com/genymobile/scrcpy/Controller.java#L265

**Comment by dieskim** [comment]
I can confirm this does now work as expected.
Tested on:
- Xiaomi Mi A3 (Android  11) 
- Samsung Galaxy J4+ (Android  8.1.0) 
- Samsung A11 (Android 10)
Thank you for the fix.

**Comment by boynet** [comment]
@dieskim hi I am having similar bug, where can I find the fix? I dont see any commit in the last 16 days

**Comment by dieskim** [comment]
@boynet you can switch to the latest release
https://github.com/koush/vysor.io/releases
and then switch to the new beta channel via advanced > beta 

or wait a few days for these fixes to go live when @koush releases them

**Comment by koush** [comment]
I’ve temporarily disabled new users to the beta channel because I encountered a severe error on windows. I think it’s resolved, but wanted to do further testing before I enable it again.
