### ISSUE TITLE
Cannot purchase lifetyme license

### ISSUE THREAD

**Issue by Nhedro** [koush/vysor.io#785]
When I go to the pc application and click on any of the buttons associated to lifetime subscription, and then selectr paypal or credit cards, it does not react nor moves forward not even an error appears.

How is it supposed for me to buy vysor Pro?

![image](https://user-images.githubusercontent.com/11742636/119891207-a1deca00-bf30-11eb-8fc3-40589ec760ce.png)

**Comment by koush** [comment]
Investigating.

**Comment by koush** [comment]
Hi, I am not able to reproduce this error, can you generate a bug report per the instructions in the bug report template? That will have the app logs I need.

**Comment by Nhedro** [comment]
I believe the link is this one:
https://gist.github.com/f9055132978f35c1e7e29f7b2f34ea71

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by koush** [comment]
Did you generate this bug report after encountering the error? I'm not seeing anything of note in it.

**Comment by koush** [comment]
There's a chance that it may not be able to open your default browser for some reason? Can you set your default browser to edge or chrome?
The purchase process opens up in an external browser window.

**Comment by Nhedro** [comment]
I do not encounter na error message, but when i click paypal or credit card nothing happens.

I created a new bug report
https://gist.github.com/90da9550e695c07bb764c54d73cb9158

This time i tried using diferente web browsers (Edge, chrome, Firefox even IE)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by koush** [comment]
Can you go to https://app.vysor.io in your browser, and try to purchase from there? Please ensure you log in with the same email account as the desktop app, and purchase. The desktop app will also be licensed.

**Comment by Nhedro** [comment]
I was able to buy it, and now i can use it on web browers, but the desktop app is not being able to retrieve the license.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Nhedro** [comment]
Ok, I was able to to put it working. I had to logout and do the log in again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Pedro ***@***.***>
Sent: Sunday, May 30, 2021 2:37 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [koush/vysor.io] Cannot purchase lifetyme license (#785)

I was able to buy it, and now i can use it on web browers, but the desktop app is not being able to retrieve the license.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Nhedro** [comment]
Ok, I was able to to put it working. I had to logout and do the log in again.

Thank you for the help

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Pedro ***@***.***>
Sent: Sunday, May 30, 2021 2:37 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [koush/vysor.io] Cannot purchase lifetyme license (#785)

I was able to buy it, and now i can use it on web browers, but the desktop app is not being able to retrieve the license.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by avadhbsd** [comment]
No I know, I purchased the Lifetime on work 40USD that worked. 

My guess is @koush is using dark ux to drive more sales of the high ticket plan. As the popup to make th payment does not shows for the low ticket plan (if you are not willing to allow people to buy low ticket plans then why have them in the first place?)

I selected Life time and I was able to make it.
