### ISSUE TITLE
Connect to a different display ID, to control Samsung DEX

### ISSUE THREAD

**Issue by priyadi** [koush/vysor.io#789]
Samsung DEX uses a different display ID from the device's main display. It would be nice if Vysor can switch to another display ID to control DEX from my computer.

For now, I'm using scrcpy to accomplish this:

```
scrcpy --display 2 --bit-rate 32M --window-title 'DexOnLinux' --turn-screen-off --stay-awake
```

More information about controlling DEX from Linux: https://kmyers.me/blog/android/dexonlinux-dexonchromeos-how-to-no-root/

**Comment by koush** [comment]
Vysor actually already supports different display ID's under the hood. Was using it to prototype app per window stuff. Let me see I can expose it in the next release via some command line option.

**Comment by koush** [comment]
Will be rolling this out soon.

<img width="2113" alt="sdk_gphone_x86_and_sdk_gphone_x86" src="https://user-images.githubusercontent.com/73924/122989292-7b595680-d357-11eb-8671-330800652fa5.png">

**Comment by koush** [comment]
is in the beta channel now

**Comment by dieskim** [comment]
I was just messing around with the as a test for @koush 
I was able to get a Samsung Galaxy S9 connected via Dex to a TV. 
To connect the Samsung to the TV via HDMI I had to then use Vysor wirelessly and not via USB.
Vysor would then show the different displays and you could connect to them, but on wireless mode it would only connect to 1 display at a time. 
I could then disconnect the USB-C > HDMI and connect back to the Mac and connect to both displays, but since the second display was no longer connected it would just show up as black (blank)

@priyadi - is there a way to connect the phone to both the MAC / PC and a HDMI monitor at the same time?

**Comment by priyadi** [comment]
> I was just messing around with the as a test for @koush
> I was able to get a Samsung Galaxy S9 connected via Dex to a TV.
> To connect the Samsung to the TV via HDMI I had to then use Vysor wirelessly and not via USB.
> Vysor would then show the different displays and you could connect to them, but on wireless mode it would only connect to 1 display at a time.
> I could then disconnect the USB-C > HDMI and connect back to the Mac and connect to both displays, but since the second display was no longer connected it would just show up as black (blank)
> 
> @priyadi - is there a way to connect the phone to both the MAC / PC and a HDMI monitor at the same time?
> 
> @koush - maybe this is another thing to fix so that you can connect to both displays wirelessly?

unfortunately, as far I can tell, we need the HDMI attached. I'm using a dummy HDMI dongle for that. and yes, at the moment we are in the same position. I can only connect to it wirelessly. I don't how it is possible to connect to it using USB. And like you, I'd love to be able to connect using USB.

**Comment by dieskim** [comment]
@priyadi - yeah I was messing around with a bunch of dongles and stuff so far and no luck so far 
- maybe wireless DEX or something like that might be possible

**Comment by koush** [comment]
> Vysor would then show the different displays and you could connect to them, but on wireless mode it would only connect to 1 display at a time.

This may be a bug in Vysor, but I do not have a good way of testing, as the only multi display device I have is an emulator. I thought I ran into this bug a couple times while building the feature but never saw it again after I was done.

**Comment by koush** [comment]
I tracked down the bug where multiple displays (or even single displays in some circumstances) might not connect properly. Will release a new beta shortly.
