### ISSUE TITLE
Possibly altering touch events causes apps to crash

### ISSUE THREAD

**Issue by MarcoPolo** [koush/vysor.io#79]
Specifically react-native apps that listen on touch events down and move.

See react-native's issue for more info: https://github.com/facebook/react-native/issues/3678

Repro:
start any react native app (even the starter one)
drag on the screen with vysor
app crashes.

**Comment by koush** [comment]
Hm, yeah I wouldn't be surprised if react cant handle synthetic touch events, or I am not properly synthesizing said events. That said, I am using code similar to the "input" command to send events, so if that works, Vysor should work. I'll look into it further when I have time.

**Comment by dmmiller** [comment]
Just looked at this from the ReactNative side.  Two things are causing issues.  The first is that sometimes we seem to get a MOVE MotionEvent before we get the DOWN MotionEvent.  The second issue is that sometimes we get a MOVE after the DOWN but the MOVE's downTime value in the MotionEvent does not actually match the downTime that the initial DOWN's downTime came in.  Internally, we use downTime to track which touches are together.

**Comment by koush** [comment]
@dmmiller thanks, will fix this.

**Comment by dmmiller** [comment]
@koush Awesome!  Thanks for getting on this :)  I think it will make users of both React Native and Vysor happier

**Comment by koush** [comment]
I may have fixed this. Is there an easy way to test this with some sample React app this happens on?

**Comment by dmmiller** [comment]
I was able to repro this pretty easily just using the UIExplorer app.  Just push and hold on a scroll view and then move around.  Hopefully no crashes.  Or if you have an easy way to distribute to me, I can also check it.

**Comment by koush** [comment]
APK or is it on Google Play?

**Comment by dmmiller** [comment]
Oh, you need to go through the react native setup to get it running.  If it is easy for you to give me a new build, I can try it out.

**Comment by koush** [comment]
@dmmiller if you want to just share your device to me using Vysor share with the react app running, I can test the build that way.

you can email me at koush at koushikdutta dot com

**Comment by koush** [comment]
otherwise i'll need to give you a chrome zip, i'll do that too. sec.

**Comment by koush** [comment]
@dmmiller http://download.clockworkmod.com/test/vysor-dmmiller.zip
load unpacked chrome extension. make sure you disable the normal vysor app first.

**Comment by koush** [comment]
The changes I made in this test APK:

I was translating the input events directly from the browser to input events on the mouse. It used to be a stateless 1:1 translation. Now, I keep track if the mouse is up or down, and only send mouse move and mouse up events if it is down. I am also tracking the initial down time, and sending that for all future related mouse events in that gesture.

**Comment by koush** [comment]
should be fixed, sending timestamps now
