### ISSUE TITLE
Android: Stuck at Waiting for Decoder...

### ISSUE THREAD

**Issue by patggg** [koush/vysor.io#790]
**Describe the bug**
Immediately after update to 4.0.55 I cannot get any decoder to work.
Native Software was working immediately before the update, the others not so much (we discussed this a few updates ago).

**To Reproduce**
1. Attempt to view device

**Expected behavior**
I would see the device

**Desktop**
 - OS: Kubuntu 20.04.2 LTS
 - Vysor Version 4.0.55

**Android**
 - Device: Odroid N2
 - OS: Android 8
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/b14b0bbe245f5420af254c98d35ff77c

**Android Logcat**
attached
[20210605-logcat.txt](https://github.com/koush/vysor.io/files/6602164/20210605-logcat.txt)

**Comment by koush** [comment]
Do you have multiple monitors? This looks like a webgl bug. Did you follow the instructions here?

https://support.vysor.io/technical/graphics

Does this site work for you?

https://get.webgl.org

**Comment by koush** [comment]
Oh you're on Ubuntu, disregard the first link. Please confirm the webgl test page works though.

**Comment by koush** [comment]
Confirmed there was no WebGL regression on Ubuntu here. In your logs, the plugin itself seems to be loading, but the graphics card init fails (webgl as mentioned).

**Comment by patggg** [comment]
https://get.webgl.org/ works

https://www.cortona3d.com/en/webgl-compatibility-test-page works

Is that what you are wanting to confirm?

**Comment by koush** [comment]
@patggg do you have multiple graphics cards? Like a integrated intel gpu and also a discrete card?

**Comment by koush** [comment]
@patggg I finally managed to hit this bug. Are you using the snap or AppImage?

**Comment by jsjrobotics** [comment]
@koush I have this bug and am using the AppImage

**Comment by koush** [comment]
Can you try the prerelease appimage?

https://github.com/koush/vysor.io/releases

The WebCodec decoder should work in the prerelease too.

**Comment by jsjrobotics** [comment]
Using the prelease image, and after restarting my computer I was receiving the same message. I killed Vysor from the terminal, reopened it, and tried a second time. When I clicked on the device screen it connected successfully. The bug is not reproducing.

Thanks

**Comment by koush** [comment]
@jsjrobotics Ok, I'll leave this bug open, because I'm not sure what the fix was. Let me know if the issue persists on the prerelease. The prerelease also gives you access to the Beta channel (click advanced in the device list) that has initial iOS mirroring support on Linux.
