### ISSUE TITLE
AndroidTV: Can't access the control buttons in the Play store

### ISSUE THREAD

**Issue by TheReptile** [koush/vysor.io#791]
**Describe the bug**
When I'm using the Play store on my Nvidia Shield, the control buttons don't work. So it's not possible to search, or access your own profile.

**To Reproduce**
1. Go to Apps
2. Click on 'Get more apps'
3. Try to click on any control in the top right.
4. Nothing happens

**Expected behavior**
Expected behavior would be to be able to access your own profile or be able to search.

**Screenshots**

![image](https://user-images.githubusercontent.com/22954131/120900009-e35b2d80-c632-11eb-9b68-8b04c55e76e3.png)

It's not possible to click on anything in the red box in the screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Vysor Version 4.0.55

**Android (please complete the following information):**
 - Device: Nvidia Shield TV 2017
 - OS: Android 9 (Nvidia Shield TV 8.2.3)
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/ed1052c57653ec8d351e63ca8de1651a

**Comment by koush** [comment]
HI, I have a Shield.
This is not possible because the Shield itself doesn't support touch events, so a lot of UI elements often don't support clicks. Use the arrow buttons in this case. This isn't something Vysor can fix, but an issue with the underlying app not being built for touch.
