### ISSUE TITLE
iOS: Camera access was denied

### ISSUE THREAD

**Issue by guanzhangrtk** [koush/vysor.io#792]
**Describe the bug**
Trying to pair an iPad Pro with MacBook Pro and got the following error after "Connecting via Bluetooth":

![image](https://user-images.githubusercontent.com/44019025/120912701-8449f700-c6cc-11eb-90e1-8f6861117126.png)

I can see the Assistive Touch dot briefly on the iPad so I know it connected to Bluetooth successfully, however the camera issue is blocking operation of the app. I've looked on the iPad to see if anything was requesting camera access and didn't find any.

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - Vysor Version 4.0.17

**iOS (please complete the following information):**
 - Device: iPad Pro
 - OS: 14.5.1
 - Vysor Bug Report Link: N/A

**iOS Bluetooth Issues:**
 - Mac/Computer Model: MacBookPro8,2
 - Other devices connected with computer via Bluetooth: Bluetooth keyboard
 - Other devices connected with iOS via Bluetooth: None

**Comment by koush** [comment]
You need to enable camera access on the Mac side, you should have been prompted. But if you were not, you can enable it in Settings.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/73924/120913612-1a3e3d00-c64d-11eb-9494-8276c889a263.png">

**Comment by guanzhangrtk** [comment]
Thanks for the quick response! Due to the way I install Big Sur (on unsupported Macs), I'll need to [manually grant camera permission to the app](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-grant-special-permissions-to-apps-ie-camera-access-to-zoom) and I'll need to know the Bundle ID, is the following sufficient or am I still missing something? Because now it seems that I can control it but I do not actually see the screen.

![image](https://user-images.githubusercontent.com/44019025/120914326-77cb9b80-c6d8-11eb-87fc-bb6e5cc59b31.png)

![image](https://user-images.githubusercontent.com/44019025/120914321-6f736080-c6d8-11eb-9f20-9f1ccafcdc30.png)

Appreciate the help!

**Comment by koush** [comment]
is the iPad screen on at that point? Sometimes when the iPad is off it hangs at "waiting for decoder" because the iPad isn't sending anything. Also, generate a bug report while it's hung, and give me that link.

**Comment by koush** [comment]
My primary dev machine is a hackintosh and I don't have issues. The permission request shows up fine too.

**Comment by koush** [comment]
The bundle id is com.electron.vysor but the VysorCapture binary doesn't use that. There's no bundle id.
