### ISSUE TITLE
Android: Vysor window turns completely blue

### ISSUE THREAD

**Issue by oss96** [koush/vysor.io#793]
**Describe the bug**
When I start a session with a phone, the window of the device sometimes turns blue. 

The main window of Vysor itself, sometimes also turns blue.

When this "turning blue" happens, I can't interact with the window.

**To Reproduce**
1. start vysor
2. start a session
3. sometimes it happens immediately, sometimes it takes a few minutes

**Expected behavior**
The Program shouldn't turn blue.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/45469086/120991323-cc772100-c781-11eb-9fe2-e49a7c2a03d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Vysor Version 4.0.60

**Android (please complete the following information):**
 - Device: confidential
 - OS: Android 10 and Android 7.1.2
 - Vysor Bug Report Link: Bug Report: https://gist.github.com/VysorLogs/bcbdee550412da852baee0bad19d8c8f

**Android Logcat**
Didn't find any crashes in the log

**Additional context**
This happened only after I updated to the Version 4.0.60. I'm not sure, what the previous version was.

**Comment by koush** [comment]
Hi, I've rolled back this bad update already. If you exit Vysor (from the notification tray) and reopen it you should be back on 4.0.59. Seems to only be occurring on Windows. Please confirm,.

**Comment by koush** [comment]
I believe I've tracked down the underlying issue that was causing this and will resolve that tomorrow after some more extensive testing.

**Comment by oss96** [comment]
Yes it got rolled back. 
Thank you for the quick response 👍

**Comment by danielcodingpilot** [comment]
I am experience the same issue with Vysor 4.1.92 on Linux and Android - any ideas?
