### ISSUE TITLE
Android: Stuck on "installing new APK" in chrome after upgrade

### ISSUE THREAD

**Issue by vthielen** [koush/vysor.io#794]
**Describe the bug**
browser (chrome) soft doesn't manage to install new APK after upgrade: stuck on "Installing Vysor APK..."

**Attach a Vysor Bug Report Log**
https://gist.github.com/eedf41ef9674d6b31c88119f89987f6a

**To Reproduce**
- turn on PTP on the phone
- accept upgrade invitation in browser 
- Browser soft removes old APK version without problem
- then gets stuck at  "Installing Vysor APK..."
- After installing APK manually from play store and trying again, it is removed again, because its an old version, and it gets stuck again trying to install the new one: "Installing Vysor APK..." 

**Expected behavior**
Browser should be able to upgrade (maybe one of the setttings on my phone is wrong?) or Play store should have the latest version of the APK, so I can upgrade it manually.
![InstallingVysorAPK](https://user-images.githubusercontent.com/9841335/120991816-47d8d280-c782-11eb-9e3e-44d45491a5ff.gif)

**Screenshots**

**Desktop (please complete the following information):**
 - PC soft: Windows 7, using chrome browser 91.0.4472.77
 - Vysor Version: web version

**Android (please complete the following information):**
 - Device: Moto G6 Play
 - OS: Android 9
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**Additional context**
This happens every time there is an upgrade, so I try not to accept them, but after a while it upgrades anyway, and gets stuck again.
After a few days the play store version is upgraded as well and I can install manually, but I have to download it every day to check.

**Comment by koush** [comment]
I think there's a setting that allows side loading apps? Or disables verification of apps? Can you check that in Android settings and let me know?

**Comment by vthielen** [comment]
I turned of the setting "verify apps over USB" but that didn't help.

**Comment by koush** [comment]
Here's the APK if you need to manually install it. https://github.com/koush/release/raw/master/Vysor/release/Vysor-release.apk

**Comment by vthielen** [comment]
Ok, now it works, thank you very much for your help
Will that link always have the latest version?

**Comment by koush** [comment]
Yes

**Comment by vthielen** [comment]
Hallo,

Sorry to disturb you, but I have the same problem again: the app updated
again on PC and, even after installing from the link that you sent me, it
removes it, and gets stuck trying to install it's own APK.
Is there a place where I can get the latest APK?

Thanks,

Bart

**Comment by koush** [comment]
https://app.vysor.io/Vysor-release.apk

**Comment by koush** [comment]
The APK link was old, I"ve updated the link to always point to the latest apk.
