### ISSUE TITLE
Android: How do we run both Vysor voice and Discord voice in device same time?

### ISSUE THREAD

**Issue by pprasanth** [koush/vysor.io#795]
**Describe the bug**
I was trying to use Discord while already running Vysor for Audio mirroring. But if I do raise then Vysor not taking voice to adb in system.

I did install Discord on my Android devices and enabled over draw permission to it and after that Vysor voice mirror stopped working.

Is it possible to use both?

**Comment by koush** [comment]
Unfortunately I don’t think it’s possible to both. Vysor captures the audio output, not the microphone input.
