### ISSUE TITLE
Windows: Cant return from enlarge mode

### ISSUE THREAD

**Issue by FranzNahrada** [koush/vysor.io#799]
https://gist.github.com/18d0e7f3ec3b3063e8cb69dda86a1ddf

I opened a Video on telegram, enlarged the vysor window with the toggle fullscreen button on topright of the window between hide and close - and could not return to the original size. Neither escape nor anything else worked but quitting the app.

**Comment by koush** [comment]
Will take a look thanks

**Comment by koush** [comment]
Found the problem
