### ISSUE TITLE
Detected But does noting !

### ISSUE THREAD

**Issue by kaushikb1996** [koush/vysor.io#8]
Hey, koushik 

I have tried to use the Vysor Beta by installing it in my chrome and i my device gets detected when i press find devices and it show my device, but when i select it noting happens, if I am not wrong according to you the chrome app should install a android app on my device but noting really happens ! hope you sort the issue

By the way,

I am using Samsung Galaxy Ace Plus -GT-S7500 running CM11 and i have installed the drivers and ADB !  

![capture](https://cloud.githubusercontent.com/assets/5248406/9469516/150d3b88-4b65-11e5-8990-8e9e2e9cf77e.PNG)

**Comment by edmckenna** [comment]
I've found that I need to disable MTP and enable PTP in order to get it to connect successfully.

**Comment by kaushikb1996** [comment]
Tried it still the same result and this time it says my device is S3 !
![capture](https://cloud.githubusercontent.com/assets/5248406/9469499/00f6b296-4b65-11e5-8070-d0af8fdc1ce3.PNG)

**Comment by Micketymike** [comment]
Having the same problem on my Motorola Droid Max Running android 4.4.4 on my Windows 7 PC.

**Comment by koush** [comment]
please enable adb and ptp mode.

**Comment by kaushikb1996** [comment]
@koush Hey still having the same issue as I have reported earlier with ADB enabled and PTP mode, please look into to this and even I am on 4.4.4 .

**Comment by anawim** [comment]
With work win7 laptop autoconnect never worked for me; I always have to find the device each time no matter if PTP is on or off.

**Comment by koush** [comment]
@anawim autoconnect only works if a native adb binary is running. i'll hide that checkbox so it is not misleading.

**Comment by anawim** [comment]
I see, so you mean adb must be already running in a shell? Why cannot be started by Vysor after it has cheked an adb android device is connected? About things to hide and show I would have appreciated to know with a message that right and middle mouse click have a function.

**Comment by kaushikb1996** [comment]
@koush I don't know if you have understood my issue in the right way, here is the issue

My device gets detected on find devices and I click on the device and then the search bar disappears and there is nothing else which is happening (Please look into the above ScreenShots).

I have ADB Enabled and On PTP Mode but still not able to use it !

**Comment by V3r0x** [comment]
click on build number to enable developer mode (lights up) (google how for your phone), then there enable USB Debugging in the dev settings (important). Then switch to PTP instead of MTP maybe. when connecting to PC.

**Comment by koush** [comment]
let me know if this has been fixed.

**Comment by kaushikb1996** [comment]
@koush Now my device doesn't even get detected, before it atleast used to
