### ISSUE TITLE
IDEA: Seamless notifications

### ISSUE THREAD

**Issue by jebeld17** [koush/vysor.io#80]
I would love to have seamless and integrated notifications from my phone to my PC while it's plugged in, taking advantage of the Action Center in Windows 10 and/or a built-in Vysor solution. It shouldn't be difficult to make something like this possible, all it would take is an Accessibility Service along with Notification Access for Vysor once installed on the host(phone) end.

**Comment by jrmgx** [comment]
see mightytext.net that do exactly this with chrome
