### ISSUE TITLE
Android: Serious picture delay

### ISSUE THREAD

**Issue by hh770718** [koush/vysor.io#800]
It can be used normally on June 6th. After Vysor is updated on June 7th, the screen will be delayed due to serious delays. Clicking on the screen will speed up the display and cannot be used normally.

**Comment by dverbroekkenexnl** [comment]
I also noticed a strange behaviour where the screen in vysor app would not update, but the physical device does.
Using mousewheel inside the app window updated the screen.
I tried the webassemble and webcodec as the other ones dont seem to work at all.
Both webX give the same behaviour.
Seems like the screenupdate command has been altered so it only updates when you are active in the window ?

**Comment by dverbroekkenexnl** [comment]
yeah it became very wonky, showing a different screen in the app compared to the phone and also rebooting/crashing android.
Currently not usable anymore :\

**Comment by koush** [comment]
Hi, please reopen the issue and use the issue template, because this has none of the information necessary for me to investigate the problem.
