### ISSUE TITLE
Android: Enabling unintended ACCELEROMETER_ROTATION

### ISSUE THREAD

**Issue by kent5823** [koush/vysor.io#801]
Enabling unintended ACCELEROMETER_ROTATION

ACCELEROMETER_ROTATION is enabled when the screen is closed after executing view Device.

Maybe app set ACCELEROMETER_ROTATION to 1 below
https://developer.android.com/guide/components/activities/activity-lifecycle?hl=en#alc

 - OS: Win10
 - Vysor Version: ![image](https://user-images.githubusercontent.com/6229916/121395673-a32ae080-c98d-11eb-83a5-475c453afa85.png)

**Android (please complete the following information):**
 - Device: [Xperia XZ3 SOV39]
 - OS: [Android 10]
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/1a9fb663681867590a4cd141c9b7f4b4

**Comment by koush** [comment]
Duplicate, will try to get to it. https://github.com/koush/vysor.io/issues/510

**Comment by kent5823** [comment]
I'm sorry
