### ISSUE TITLE
Vysor is supported with Android 7.1.2?

### ISSUE THREAD

**Issue by Maparicio2021** [koush/vysor.io#805]
**Describe the bug**
I have android 7.1.2 and I cannot connect to Vysor in my Windows 10 PC.

**Attach a Vysor Bug Report Log**
https://gist.github.com/938c6472252357f3794dd9e6ae218e84

**To Reproduce**
Connect one phone with Android 7.1.2 via USB to the PC and press "View device" in the Vysor screen. Communication is not possible. 
It says something like: "uninstalling older apk and installing new one" but after that a message is shown: "Error connecting to Android Device error: apk path failed (empty)"

**Expected behavior**
I expected to see my mobile phone on my PC screen, as it happens with my personal phone with Android 10.

**Screenshots**
![image](https://user-images.githubusercontent.com/85703540/121578753-4bdb4d80-ca2b-11eb-82c2-07b6f6d83f07.png)

**Desktop (please complete the following information):**

 - Vysor Version: 3.1.4

**Android (please complete the following information):**
 - Device: Hytera PTC760
 - OS: Android 7.1.2
 - Vysor Bug Report Link: https://gist.github.com/938c6472252357f3794dd9e6ae218e84

**Comment by koush** [comment]
Hi can you recollect that bug report while leaving that error Window open

**Comment by Maparicio2021** [comment]
Hi,
I think I did it right this time…
https://gist.github.com/cdf5d6ca222696ae2f4511481208b88f

Thanks!
Best regards,

María APARICIO
Systems Engineer
Delivery Projects

***@***.***D75E9A.E6634940]

Teltronic
P.I. Malpica c/F Oeste
50016, Zaragoza, Spain
Tel: +34 976 465656 – Ext. 144
Mobile: +34 689195069
www.teltronic.es<http://www.teltronic.es/>

De: Koushik Dutta ***@***.***>
Enviado el: jueves, 10 de junio de 2021 22:51
Para: koush/vysor.io ***@***.***>
CC: María Aparicio Blasco ***@***.***>; Author ***@***.***>
Asunto: Re: [koush/vysor.io] Vysor is supported with Android 7.1.2? (#805)


Hi can you recollect that bug report while leaving that error Window open

**Comment by koush** [comment]
> packaged apk installation result: Failure [INSTALL_FAILED_USER_RESTRICTED]

You may need to enable apps over adb/usb in your Android settings. Or disable app verification over side load.

**Comment by Maparicio2021** [comment]
Sorry, but it didn’t work…
I have the same error…

I have enabled apps over adb/usb and the results are the same.

And I cannot find “app verification over side load” in my Android terminal. Could you please help me to find that option?
Thanks,
BR,

María APARICIO
Systems Engineer
Delivery Projects

***@***.***D75EFC.1FD792B0]

Teltronic
P.I. Malpica c/F Oeste
50016, Zaragoza, Spain
Tel: +34 976 465656 – Ext. 144
Mobile: +34 689195069
www.teltronic.es<http://www.teltronic.es/>

De: Koushik Dutta ***@***.***>
Enviado el: viernes, 11 de junio de 2021 19:33
Para: koush/vysor.io ***@***.***>
CC: María Aparicio Blasco ***@***.***>; Author ***@***.***>
Asunto: Re: [koush/vysor.io] Vysor is supported with Android 7.1.2? (#805)


packaged apk installation result: Failure [INSTALL_FAILED_USER_RESTRICTED]

You may need to enable apps over adb/usb in your Android settings. Or disable app verification over side load.

**Comment by koush** [comment]
See here.

https://stackoverflow.com/questions/47239251/install-failed-user-restricted-android-studio-using-redmi-4-device
