### ISSUE TITLE
Android: Paste to Device causes Vysor to Crash

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#807]
**Describe the bug**
Pasting onto the Android Device with COMMAND + V causes vysor to crash and needs to be reconnected
- the text does seem to be moved to the device clipboard, as after reconnecting I am able to paste on the android device via the normal android paste function (hold and select paste)

**Attach a Vysor Bug Report Log**
1. sent via twitter

**To Reproduce**
1. copy text on Mac
2. Paste on Device via COMMAND + V

**Expected behavior**
Text should paste not cause vysor to crash

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Vysor Version - Beta Channel - 4.1.2

**Android (please complete the following information):**
 - Device: Samsung Galaxy A02s
 - OS: Android 10

**Comment by dieskim** [comment]
This phone is running a weird Samsung One UI Core Version = 2.5
I could update this phone to Android 11 and it would most likely fix it but I can wait to see if you could fix this bug

**Comment by koush** [comment]
I'll need a logical to diagnose the problem

**Comment by koush** [comment]
feel free to DM it to me via twitter

**Comment by dieskim** [comment]
[samsung-a02s.log](https://github.com/koush/vysor.io/files/6645587/samsung-a02s.log)
here is the logcat
