### ISSUE TITLE
Using Vysor at Amazon: feature to turn off telemetry?

### ISSUE THREAD

**Issue by wzijden** [koush/vysor.io#808]
Hi,

I work for Amazon AWS and want to use Vysor enterprise version internally to demo an app we have in development.

However, Vysor got rejected by our Security Review because apparently "it does send personal/sign-in, hardware, geolocation, and other metadata that Amazon would not want getting out."

Is this true, and if so, would it be possible to add a feature for turning off telemetry?

Thanks,

Wim

**Comment by koush** [comment]
Vysor has personal sign in only for licensing. This can not be removed for obvious reasons.
It also uses Google analytics, although that is anonymized. I could add a setting to disable that.

**Comment by wzijden** [comment]
Hi, I will ask our Security engineer if a setting to disable Google Analytics would be sufficient to allowlist Vysor for internal use at Amazon.

**Comment by wzijden** [comment]
Hi, unfortunately they cannot guarantee that this would be sufficient, but it would certainly help.

**Comment by koush** [comment]
I just double checked the analytics, here's what's sent via the desktop application:

email (when logged in for license check)
browser user agent and IP

The android application does not send anything at all.

This is no different from visiting any webpage. In fact, Vysor does run as a progressive web app, if you don't want to do a desktop application installation: https://app.vysor.io
This is the recommended way to not run afoul of corporate security policies.

**Comment by koush** [comment]
When a bug report is generated, it does sent a lot more information (specifically, the logcat and device information). That, however, is user initiated.

**Comment by koush** [comment]
Alright, I've fixed it so the collection event no longer sends the page title (which is the device name). It anonymizes it.

<img width="385" alt="Screen Shot 2021-06-21 at 10 44 34 AM" src="https://user-images.githubusercontent.com/73924/122805280-bedf9200-d27d-11eb-9e07-8c13f8c8afbb.png">

**Comment by koush** [comment]
This change is now in the prerelease/beta builds. No device information is collected at all. Standard browser information (ie, your desktop resolution and whatever) are still sent. But nothing pertaining to the device is collected.

If you'd like to open another issue regarding the *browser* telemetry (which persists), go ahead.

**Comment by wzijden** [comment]
Hi koush,

Is this change in production already? I don't see a commit that relates to this.

**Comment by koush** [comment]
It is, commit is not in this repository. Private repo.
