### ISSUE TITLE
Linux / Debian: 4.1.2 Native and AppImage won't run

### ISSUE THREAD

**Issue by dverbroekkenexnl** [koush/vysor.io#809]
**Describe the bug**
Both the installed native (.deb) and the appimage wont run.
No GUI output, CLI output is similar.

**Attach a Vysor Bug Report Log**
As Vysor wont start, there is no Vysor log
GUI start shows nothing, CLI provides some output

**To Reproduce**
Download .deb or .appimage

**Expected behavior**
Start of the application

**Screenshots**
See CLI output

**Desktop (please complete the following information):**
 - OS: MX Linux / Debian 9
 - Vysor Version 4.1.2

**Additional context**

$ uname -a
Linux TXS-TECH35 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+mx17+1 (2019-11-17) x86_64 GNU/Linux

$ cat /etc/debian_version 
9.13

AppImage output : 

$ ./Vysor-linux-4.1.2.AppImage 
[24883:0611/094406.432928:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Vysor-oSH4FL/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

$ ./Vysor-linux-4.1.2.AppImage --no-sandbox
{
  node: '14.16.0',
  v8: '9.1.269.28-electron.0',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '89',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1',
  icu: '68.1',
  unicode: '13.0',
  electron: '13.1.1',
  chrome: '91.0.4472.77'
}
nativeTheme NativeTheme {
  shouldUseDarkColors: [Getter],
  themeSource: [Getter/Setter],
  shouldUseHighContrastColors: [Getter],
  shouldUseInvertedColorScheme: [Getter]
}
NODE_ENV undefined
IS_TEST undefined
IS_PROD undefined
IS_DEV undefined
WEBPACK_DEV_SERVER_URL undefined
USE_OFFLINE undefined
/tmp/.mount_Vysor-3L70gd/resources/app.asar.unpacked/native/linux/video_decode.so
PPAPI path /tmp/.mount_Vysor-3L70gd/resources/app.asar.unpacked/native/linux/video_decode.so;application/x-ppapi-vysor
https://vysorelectron.clockworkmod.com

Native output :

$ which vysor 
/usr/bin/vysor

$ vysor 
{
  node: '14.16.0',
  v8: '9.1.269.28-electron.0',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '89',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1',
  icu: '68.1',
  unicode: '13.0',
  electron: '13.1.1',
  chrome: '91.0.4472.77'
}
nativeTheme NativeTheme {
  shouldUseDarkColors: [Getter],
  themeSource: [Getter/Setter],
  shouldUseHighContrastColors: [Getter],
  shouldUseInvertedColorScheme: [Getter]
}
NODE_ENV undefined
IS_TEST undefined
IS_PROD undefined
IS_DEV undefined
WEBPACK_DEV_SERVER_URL undefined
USE_OFFLINE undefined
/opt/Vysor/resources/app.asar.unpacked/native/linux/video_decode.so
PPAPI path /opt/Vysor/resources/app.asar.unpacked/native/linux/video_decode.so;application/x-ppapi-vysor
https://vysorelectron.clockworkmod.com

**Comment by koush** [comment]
Thanks, given that I'm considering removing the AppImage support in favor of Debian only, can you send me the log output from that as well? I think the launch above is only for the AppImage.

**Comment by koush** [comment]
Er never mind I see it now.

**Comment by koush** [comment]
There is an official apt repo now.
https://www.vysor.io/download/linux
