### ISSUE TITLE
Android: Exclude "Cable charging" push notification

### ISSUE THREAD

**Issue by SeriousM** [koush/vysor.io#810]
**Describe the bug**
When using vysor the push notification for "Cable charging" is popping up all the time.

Can I somehow define a regex to filter out some of the notifications I don't want to see?

**Expected behavior**

Avoid sending this notification to win10 notifications.

Sadly I can't disable the notification on the device and win10 is unable to filter them as I would like.
This is probably connected with the issue #722.

**Screenshots**

Win10 notification
![image](https://user-images.githubusercontent.com/462013/121860733-7104e000-ccf9-11eb-8646-ff7f086b50b7.png)

Android notification
![image](https://user-images.githubusercontent.com/462013/121860837-8a0d9100-ccf9-11eb-8297-a77644619787.png)

Long-Hold on the charging notification
![image](https://user-images.githubusercontent.com/462013/121860879-91cd3580-ccf9-11eb-95ad-5d311c4c52b5.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Vysor Version 4.0.17

**Android (please complete the following information):**
 - Device: Samsung Galaxy A41
 - OS: Android 10

**Additional context**

I'm a very happy premium user so far :)

**Comment by koush** [comment]
Tracking filtering:
https://github.com/koush/vysor.io/issues/850
