### ISSUE TITLE
Vysor Android On-Screen-Keyboard Option - What is it?

### ISSUE THREAD

**Issue by omgitsgela** [koush/vysor.io#814]
I am trying to determine what the Vysor Keyboard is when I go into Language and Input on the controlled Android device. It comes up as an on-screen-keyboard option, and you seem to be able to set it as a default keyboard. I don't understand what this feature does?

I checked the Wiki/user manual content, but could not find a section describing this and how it works.

I have noticed one piece of its behavior. Everytime I connect my phone to the computer, the default on screen keyboard changes to Samsung. I've noticed if I go in manually and change it to Vysor, that no on screen keyboard appears at all, which is great. But I have to do this setting every time to get the keyboard not to appear. Is this part of this feature, and am I using this wrong?

**Comment by koush** [comment]
Hi, sorry about the confusion, I'm planning on really scrubbing the documentation soon so this will be more apparent.

International Keyboard is a setting in Vysor. It serves two purposes:
 * international keyboards can type non-english characters
 * it hides the keyboard while mirroring in vysor

You can enable it permanently in settings for Vysor, so you don't need to enable it every time.

<img width="547" alt="sdk_gphone_x86" src="https://user-images.githubusercontent.com/73924/122989793-15210380-d358-11eb-94d9-f86dddbefce2.png">
