### ISSUE TITLE
iOS: Blank Screen That Says: Connecting to Vysor on iOS

### ISSUE THREAD

**Issue by tomhankshd** [koush/vysor.io#816]
When I try to connect my iPhone 11 to Vysor on Mac, I just get a black screen that says "Connecting to Vysor on iOS"![Screen Shot 2021-06-23 at 1 15 06 PM](https://user-images.githubusercontent.com/86373732/123141277-39e3ac80-d426-11eb-93e3-a97e852b0f8e.png)If i'm in an app on my phone and click the home button in Vysor, it will take me back to the home screen on my [phone.](url)

https://gist.github.com/6a53b17a0ef68f41490e3dc4bbdcad52

**To Reproduce**
1. Open Vysor on Mac
2. Click on iOS Device
3. See error

**Expected behavior**
I expect Vysor to emulate my phone screen.

**Screenshots**

![Screen Shot 2021-06-23 at 1 15 06 PM](https://user-images.githubusercontent.com/86373732/123141277-39e3ac80-d426-11eb-93e3-a97e852b0f8e.png)**Desktop (please complete the following information):**

 - OS: [e.g. MacOS]
 - Vysor Version [e.g. 2.2.2]

**iOS (please complete the following information):**
 - Device: [e.g. iPhone 12 Pro]
 - OS: [e.g. iOS 14.1]
 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

**iOS Bluetooth Issues:**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**

**Comment by koush** [comment]
Thanks for the report, let me look through the log.

**Comment by tomhankshd** [comment]
I also can't use my keyboard on my phone while the screen is sharing.

**Comment by koush** [comment]
Should be fixed in stable channel.

**Comment by gutisalex** [comment]
its not fixed for me, nor on stable, neither on beta...

**Comment by koush** [comment]
> its not fixed for me, nor on stable, neither on beta...

There’s another unrelated bug where media services gets stuck. May just need to restart your phone. Or reset media services in the iOS developer settings.

**Comment by gutisalex** [comment]
Restart of the phone fixed it...
