### ISSUE TITLE
Feature request: Option to remove status bar icon

### ISSUE THREAD

**Issue by ernestp** [koush/vysor.io#817]
**Describe the bug**
Currently icon in status bar always present.
For me it is looks like an Instagram icon.
I'm in fight with distractions and this icon creates cognitive dissonance.
After all I never used this icon.

**Expected behavior**
Option to hide status bar icon.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Vysor Version 4.0.62

**Comment by koush** [comment]
<img width="755" alt="Vysor" src="https://user-images.githubusercontent.com/73924/123187975-13d30200-d450-11eb-8048-d7977c08d0c9.png">

fixed in beta channel.

**Comment by koush** [comment]
Here's a link to the prerelease build that will let you access the beta channel.
https://github.com/koush/vysor.io/releases/tag/v4.1.7

**Comment by ernestp** [comment]
Thanks @koush, this works for me, you can close issue (or wait till release)
