### ISSUE TITLE
iOS: Vysor on Mac not Recognizing iOS Device

### ISSUE THREAD

**Issue by nguyenpaul** [koush/vysor.io#818]
**Describe the bug**
Vysor on Mac not Recognizing iOS Device

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/60142933166c3b4a96311436818a41de

id 
email 
/Users/paul_nguyen/Library/Application Support/vysor
app://./index.html#/
process.versions {"node":"12.14.1","v8":"8.3.110.13-electron.0","uv":"1.33.1","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"80","nghttp2":"1.40.0","napi":"5","llhttp":"2.0.1","http_parser":"2.8.0","openssl":"1.1.0","icu":"65.1","unicode":"12.1","electron":"9.4.0","chrome":"83.0.4103.122"}
package.json 4.0.17
runtime package.json 4.0.17
os darwin
electron true
pwa false
adb tracker started
apple tracker started
app://./index.html#/
enterprise cached check failed Error: not cached
clockwork cached check failed Error: not cached
chromeStore cached check failed Error: not logged in

**To Reproduce**
1. Star Vysor
2. Connect iOS Device and Trust It
3. Check Apple Itunes to confirm Device is Visible on Mac
4. Check Vysor App and Don't see iOS Device 

**Expected behavior**
Expecting to be able to connect to iOS Device from Visor

**Screenshots**
Available if needed

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Vysor Version 4.0.17

**iOS (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 12.2
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/60142933166c3b4a96311436818a41de

**iOS Bluetooth Issues:**
 - Mac/Computer Model
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**

**Comment by koush** [comment]
Hi, are you behind a corporate firewall or something? It seems that you're not updated to the latest version of the app, but are running on an internal/offline version.

**Comment by Gaudynou** [comment]
i have an iphone 11. and not able anymore to see the screen.  works fine with samsung. but my iphone only show a black screen 
bug report : https://gist.github.com/67fb3caab0bae9800eaa4ba4d1bbfed6OS: 
Device: iPhone 11
OS: iOS 14.6
Vysor Version 4.0.62

**Comment by koush** [comment]
Can you try the beta channel on the prerelease build? I believe this is fixed.

https://github.com/koush/vysor.io/releases/tag/v4.1.7

**Comment by koush** [comment]
Here's how to activate it. https://twitter.com/vysorapp/status/1407051094245662723

**Comment by Gaudynou** [comment]
Not working for me  Still got the same message : Connecting to Vysor on iOS...

**Comment by koush** [comment]
Can you generate a bug report with the beta app?

**Comment by Gaudynou** [comment]
Here it is :

https://gist.github.com/345f2acdd50bee677b3a795a0d5769e7


From: Koushik Dutta ***@***.***>
Date: Wednesday, June 30, 2021 at 15:51
To: koush/vysor.io ***@***.***>
Cc: Gaudynou ***@***.***>, Comment ***@***.***>
Subject: Re: [koush/vysor.io] iOS: Vysor on Mac not Recognizing iOS Device (#818)

Can you generate a bug report with the beta app?

**Comment by nguyenpaul** [comment]
I was able to get iOS Device to Mirror on a Mac M1 using https://github.com/koush/vysor.io/releases/tag/v4.1.7.  When will this version be GA?

**Comment by koush** [comment]
@nguyenpaul I just published an update that should fix device detection and mirroring on the stable channel.

**Comment by nguyenpaul** [comment]
I just downloaded Vysor-mac-4.1.29.dmg and installed it.  UI shows it is version 4.0.63.  It connection to iOS device seems to work thought.

**Comment by koush** [comment]
Yeah, the version is misleading and the "real" version numbers are shown in the beta channel.

You can switch to the beta channel from within the app you just downloaded.

**Comment by koush** [comment]
<img width="800" alt="Vysor" src="https://user-images.githubusercontent.com/73924/124988333-b82d7a80-dff2-11eb-84ce-071483a12179.png">

**Comment by koush** [comment]
<img width="800" alt="Vysor" src="https://user-images.githubusercontent.com/73924/124988401-cb404a80-dff2-11eb-8b9e-069f1d7f1c5a.png">

**Comment by nguyenpaul** [comment]
Looks good now.  Thanks.
