### ISSUE TITLE
Device temporarily freezes upon unlock

### ISSUE THREAD

**Issue by jebeld17** [koush/vysor.io#82]
My device screen temporarily freezes at it's current state when I attempt to unlock my device from the PC-end after receiving a notification if the screen was asleep. It doesn't stay frozen for long, as my lock screen reloads and/or goes back to it's original state, and I try again.

Maybe this has something to do with a loss of translation that Mouse movement + Click and hold = Touch movement (Such as a swipe upwards)? Maybe going out of frame on the PC while scrolling upwards to unlock the device can accidentally fool the device into thinking my finger is still on the screen, but stopped in place?

**Comment by koush** [comment]
the rendering freezes or the swipe fails?

**Comment by koush** [comment]
legacy issue i think, there's a new rendering pipeline
