### ISSUE TITLE
Android: java.lang.Exception: Encoder Error

### ISSUE THREAD

**Issue by wakeup44** [koush/vysor.io#822]
Unable to connect to the device.[log.txt](https://github.com/koush/vysor.io/files/6752674/log.txt)
Bug Report Log
https://gist.github.com/8a7abb50ae55d27f93af34da6fb3ac7e

To Reproduce
Just try to connect

![image](https://user-images.githubusercontent.com/36727688/124232261-b99e0500-db11-11eb-9f02-3838905bebe1.png)

**Desktop (please complete the following information):**
 - OS: Windows 1909 (OS Build 18363.1556)
 - Vysor Pro Version 4.0.62

**Android (please complete the following information):**
 - Device: NXP i.MX 8M Mini
 - OS: Android 11 RQ2A.210305.006

**Android Logcat**
[log.txt](https://github.com/koush/vysor.io/files/6752674/log.txt)

**Comment by koush** [comment]
Can you try other quality resolutions? Like low and medium and see if one of those works? It's failing on encoder configure, which means the high resolutions may not work. May also want to try setting the resolution to 25%.

**Comment by wakeup44** [comment]
I am running native OLED screen resolution. It was working on previous Android 9 version.
I can switch from DSI MIPI to HDMI output and try to change resolution, but prefer to have OLED attached. It is not possible to have both.
Is there any other way?

**Comment by koush** [comment]
When I say resolution, I mean the resolution within Vysor's desktop application.  
<img width="604" alt="image" src="https://user-images.githubusercontent.com/73924/124297158-9ffbbe00-db0f-11eb-8a01-0ce5be4ac011.png">

**Comment by wakeup44** [comment]
It works for resolutions 50% and below.
Thank you!

**Comment by rain2310** [comment]
Hi , im having the same problem , i already lower my resolution . can you help me ?
