### ISSUE TITLE
Vysor Version 4.1.27 won't load

### ISSUE THREAD

**Issue by stemplar48** [koush/vysor.io#824]
Version 4.1.27 won't load

Unable to attach a log because when Vysor launches all that loads is a blue window. No text or buttons.

Open Vysor after version update

The GUI never loads

![image](https://user-images.githubusercontent.com/86919110/124388066-a96b5e80-dca6-11eb-8733-606fabe2d1af.png)

Desktop:
 - OS: Microsoft Windows 10 Pro (version 10.0.19043; build 19043)
 - Vysor Version 4.1.27

Android:
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Vysor Bug Report Link: Unable to attach a log because when Vysor launches all that loads is a blue window. No text or buttons.

**Comment by koush** [comment]
You switched to the beta channel I am guessing?

**Comment by koush** [comment]
Was this a fresh download or an update to the app? Did you switch to the beta channel at some point?

**Comment by koush** [comment]
I would try uninstalling, and clearing this folder too, then reinstall:

`C:\Users\YOURUSERNAME\AppData\Roaming\vysor`

Let me know if that resolves it. Bit concerned about this bug.

**Comment by koush** [comment]
You'll want to redownload vysor, I had to roll back the update due to major performance issue which this may be related to.
See here:

https://github.com/koush/vysor.io/issues/825

**Comment by stemplar48** [comment]
I updated fresh. I uninstalled cleared out C:\Users\******\AppData\Roaming\vysor and reinstalled. It wouldn't load at all after that. I tried uninstalling, clearing out the folder again and installed the previous version 4.1.26 and it still doesn't load.

**Comment by koush** [comment]
Can you also try clearing out 

`C:\Users\YOURUSERNAME\AppData\Local\vysor`

And make sure you're installing this version of Vysor:

https://github.com/koush/vysor.io/releases/tag/v3.1.4

**Comment by stemplar48** [comment]
That worked, thanks. I'll stick with v3.1.4.

**Comment by koush** [comment]
Hi, since these steps worked for you, could you do me a huge favor and verify the issue was with the build (versus some broken installation that you fixed by deleting files)?

Install this and let me know if Vysor fails to load again:
https://github.com/koush/vysor.io/releases/tag/v4.1.27

You can refollow the previous steps to get back into a working state. At some point I am going to have to cut a new release, and I don't want to cause your app to stop working again.

**Comment by koush** [comment]
To clarify, you won't be able to stay on 3.1.4 once I reenable the update, as your app will be automatically updated again.

**Comment by koush** [comment]
Since you're the only user to report this, I'll be resuming the rollout. The 3.1.4 build will no longer be available, sorry.

**Comment by stemplar48** [comment]
Yeah it was the build.

**Comment by koush** [comment]
Ok I put out a new build
