### ISSUE TITLE
High CPU usage & extremely slow (unusable)

### ISSUE THREAD

**Issue by woods333** [koush/vysor.io#825]
Hi hope you can advise: been using vysor for months no issues, really fast and response (multiple phones open at once)

BUT this morning windows asked to approve network access to vysor, I clicked "cancel" and ever since then its High CPU usage & extremely slow to the point it's unusable...?

I don't know how this has caused this issue? should i re-download vysor?

**Comment by woods333** [comment]
confirmed something to do with vysor - vysor closed, pc fast like normal...??

**Comment by koush** [comment]
Hi, can you try this download and see if it returns to normal performance:

https://github.com/koush/vysor.io/releases/tag/v3.1.4

This is an older version, so it will prompt to auto update. If it does, do not accept the update.

**Comment by woods333** [comment]
Thanks for fast reply! And so I downloaded that version and it's done the trick! (still says version 4.0.62 in the about section) but main thing is it's back to fast speed I had before, thanks!

**Comment by koush** [comment]
Thanks for the bug report. I've rolled back the major update until I can figure out what is going on.

**Comment by koush** [comment]
@woods333 could you tell me a little bit about your computer?

CPU
Graphics Card

Are you running Windows in a VM?

**Comment by koush** [comment]
Since you're the only user to report this, I'll be resuming the rollout. The 3.1.4 build will no longer be available, sorry.

**Comment by woods333** [comment]
Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz   3.60 GHz Windows 10 Pro

**Comment by koush** [comment]
Some other people reported a similar issue. This can be fixed in one of two ways:

1) Use the native hardware decoder + fallback (which is now the default)
2) Switch to the beta channel and use either of the WebCodec decoders.

**Comment by woods333** [comment]
Hi sorry same thing happened today after update?
RAM - 32GB
Graphics Card | 4GB NVIDIA GEFORCE GTX 1650 SUPER - HDMI



</body>
</html>

**Comment by woods333** [comment]
Ok cool will try those steps too thanks

**Comment by koush** [comment]
Ok please let me know after you've tried them whether it worked, so I can confirm this issue is fixed.

**Comment by woods333** [comment]
native hardware decoder + fallback fixes speed issue but the 'phones' screen is dull / light grey now? 

and none of these issues happen once I use version 3.1.4 (happy to use this version anyway) thanks

**Comment by koush** [comment]
Try WebCodec software in Beta please.

**Comment by woods333** [comment]
Yes that has worked too :) But why does WebCodec have to be used at all or whats wrong with what worked on version 3.1.4 ?

**Comment by koush** [comment]
> Yes that has worked too :) But why does WebCodec have to be used at all or whats wrong with what worked on version 3.1.4 ?

Did WebCodec fix the "grey" screen bug?

**Comment by woods333** [comment]
Yes it did, same quality as before any kind of issue
