### ISSUE TITLE
iOS: screen recording feature not working

### ISSUE THREAD

**Issue by ahowse1** [koush/vysor.io#828]
The recording icon turns red and spins as if recording, but no recorded file appears on the desktop after recording is stopped as support instructions state it will. Video is either saved somewhere else, or the recording feature is not working at all.

Vysor Pro 4.0.62

Macbook Air M1 2020
MacOS Big Sur 11.4

iOS 14.6
iPhone Xs

**Comment by koush** [comment]
Should be fixed now in stable channel.
