### ISSUE TITLE
iOS: connectivity issue

### ISSUE THREAD

**Issue by ahowse1** [koush/vysor.io#829]
Cannot connect iphone via bluetooth with Vysor Pro on either iMac with Catalina 10.15.7 or with Macbook Air (M1/2020) running Big Sur 11.4. Bluetooth connects to mac devices fine, but Vysor will not recognize bluetooth connections and will only connect via lightning cable to iPhone (Xs, 14.6).

During connection process, Vysor window says it is connecting to the device via bluetooth and shows iPhone bluetooth NIC address. Even after connecting, I pull the lightning cable and connection is lost. Vysor window should not say it's connecting via bluetooth when it clearly is connecting via the cable.

https://gist.github.com/f493234b365ecc5bcc44e863f5e0e652

**Comment by koush** [comment]
Vysor emulates a bluetooth keyboard and mouse to connect to iOS. Video is through the cable.
