### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by KinsleyThomasWong** [koush/vysor.io#83]
I have been using vysor.io for the last three months without any problem. Only last week until now, I am having problem that I cannot use it: it's black screen on my monitor. I cannot see what going on for my phone. Please help, KinsleyThomasWong@gmail.com
![2](https://cloud.githubusercontent.com/assets/11549609/10901235/0581758c-81a0-11e5-86dd-680425ea6af5.JPG)
![1](https://cloud.githubusercontent.com/assets/11549609/10901237/0b4beaba-81a0-11e5-9044-141fa1a3747b.JPG)
![3](https://cloud.githubusercontent.com/assets/11549609/10901239/104da51c-81a0-11e5-80c9-f6216d4b70c6.JPG)
![4](https://cloud.githubusercontent.com/assets/11549609/10901241/151e15c2-81a0-11e5-8b9b-502962037af1.JPG)

**Comment by stealthgyro** [comment]
If it's any help tracking the issue. Mine seems to work fine and the only time I get a black screen, but the input still works is when I launch Amazon Prime Now.

**Comment by KinsleyThomasWong** [comment]
Thank you Chris,
the problem was with chrome browser. I got it all fixed now :-) Kinsley

**Comment by Jspoor** [comment]
what problem did you have and how did you solve it?

**Comment by koush** [comment]
new update fxes this. please use hte proper support forum for bug reports. this is for feature tracking.

**Comment by Jspoor** [comment]
Where is the proper forum for bugs?

**Comment by spupuz** [comment]
have same problem with version 1.0.7.1 ubuntu 16.04 and chrome Version 52.0.2729.3 dev (64-bit) ha no problem before with version 1.0.6.7

**Comment by swetabh007** [comment]
I am also facing the same issue? What is this issue? And how you fixed it? @KinsleyThomasWong
