### ISSUE TITLE
Android: Something Is Wrong with the recent update

### ISSUE THREAD

**Issue by chandrucrypto** [koush/vysor.io#831]
**Describe the bug**
Vysor is stuck or takes too much time to load after updating to the latest version.

**To Reproduce**
1. Connect the Android device which was already connected before and Vysor app is successfully installed on it.
2. Notice the Vysor checks whether app is installed on the device and loading takes too much time here.
3. Then device is mirrored, but unfortunately, the Vysor completely lags here.

**Expected behavior**
It is supposed to damn smooth before.

**Screenshots**
Please find the video of the bug
https://user-images.githubusercontent.com/73110189/124719234-8fd74a80-df24-11eb-92af-aa7de7fedebd.mp4

**Desktop (please complete the following information):**
 - OS: MacOs
 - Vysor Version : 4.0.62

**Android (please complete the following information):**
 - OnePlus 3
 - OS: [e.g. Android 10]

**Comment by koush** [comment]
Can you generate a bug report so I can see which codec you are using?

**Comment by koush** [comment]
Ok video shows this is not codec related. One sec.

**Comment by koush** [comment]
What type of Mac is this? Can you try rebooting?

**Comment by SimonBKarl** [comment]
Lag when connected is happening to me too. Worked fine right before the update.
Connecting itself isn't taking noticeably longer.

Android 10, Poco F1, connected via Windows 10 (v4.0.62)

**Comment by chandrucrypto** [comment]
This is my Mac configuration 

![CleanShot 2021-07-07 at 16 22 07](https://user-images.githubusercontent.com/73110189/124747414-85767a00-df3f-11eb-8ebe-b1f4fc52d525.png)

And, I verified with 3 to 4 people.. Everyone facing the same issue..

**Comment by garganshu** [comment]
I am facing lag too.
Screen recording is not working smoothly after the update.

Device - Realme narzo 20, Android 11
Connected - MacOS Big Sur 11.4

**Comment by lovesonfrank** [comment]
<img width="513" alt="Screenshot 2021-07-07 at 5 22 03 PM" src="https://user-images.githubusercontent.com/82561809/124754476-e6a24b80-df47-11eb-9b2c-982cb4a2d3ca.png">

I am facing the same problem.

**Comment by koush** [comment]
Hi, please redownlaod vysor to resolve the issue. I have rolled back the update.
http://vysornuts.clockworkmod.com/download/mac

**Comment by koush** [comment]
Can someone please provide a generated bug report per the instructions?

**Comment by chandrucrypto** [comment]
@koush Please find the Bug report https://gist.github.com/VysorLogs/ecf53f05d3b20ceb1acb5502a46bebd3

**Comment by chandrucrypto** [comment]
Looks like Vysor got auto updated and now works fine..

**Comment by lovesonfrank** [comment]
https://gist.github.com/VysorLogs/308db7ced898159f105fd0fe14a10af6

**Comment by koush** [comment]
Can you please redownload what I think is the buggy version to confirm the issue?

https://github.com/koush/vysor.io/releases/tag/v4.1.29

You can simply roll back afterwards.

**Comment by koush** [comment]
After downloading the buggy version, please include a new bug report. Both of you provided bug reports after rolling back, so I didn't get the information I needed :)

**Comment by garganshu** [comment]
Bug report - https://gist.github.com/VysorLogs/e153b75ef235f7e22dc872102fef8420
Vysor pro version - 4.0.62

**Comment by koush** [comment]
> Bug report - https://gist.github.com/VysorLogs/e153b75ef235f7e22dc872102fef8420
> Vysor pro version - 4.0.62

@garganshu I think you're reporting a different bug regarding screen recording. Please open a separate issue.

**Comment by koush** [comment]
@chandrucrypto  @lovesonfrank Can you please download what I think is the buggy version:
https://github.com/koush/vysor.io/releases/tag/v4.1.29

And then confirm the connecting lag issue on this version and provide a bug report.

**Comment by koush** [comment]
@SimonBKarl can you provide a bug report with the laggy version installed?

**Comment by SimonBKarl** [comment]
Will try in the morning. I don't have access to the machine until then.

**Comment by chandrucrypto** [comment]
@koush Yeah sure.. Doing in sometime

**Comment by chandrucrypto** [comment]
@koush 4.1.29 works fine too https://gist.github.com/VysorLogs/0640996339accb5e9fe13bce30bfa724

**Comment by chandrucrypto** [comment]
I am super confused now that how come all the version starts working fine..

**Comment by koush** [comment]
> I am super confused now that how come all the version starts working fine..

me too. I wonder if the update just went poorly and something was left in a conflicted state. Were you running vysor when you upgraded, or did you launch and get prompted to upgrade?

**Comment by koush** [comment]
> I am super confused now that how come all the version starts working fine..

@chandrucrypto 

Do you have signal or something? Would love to chat to get a bit more information about what you were doing at the time to understand this issue. 206-552-8017.

**Comment by koush** [comment]
@chandrucrypto or join this discord https://discord.gg/xR8DpZe7

**Comment by koush** [comment]
I've reenabled the update to see if further issues come in. I think this may just be a matter of needing to click "Reload" on the app. Might be a stuck adb daemon or something.

**Comment by SimonBKarl** [comment]
https://gist.github.com/e8161df2017af91be0cdee763676fdd9

**Comment by marcrdz911** [comment]
vysor just update itself to vysor pro version 4.0.62 just after it it got real laggy, was working just fine before the update.

**Comment by koush** [comment]
@marcrdz911 can you click reload vysor. That should fix it.

**Comment by yuriyart** [comment]
updated yesterday and when I open 9 windows/devices(androids) performance so laggy. how to downgrade to previous?

**Comment by koush** [comment]
@yuriyart switch to hte beta channel or change your decoder to Native Hardware

**Comment by yuriyart** [comment]
Thank you Koush, it did improve

    On Friday, July 9, 2021, 11:47:34 AM PDT, Koushik Dutta ***@***.***> wrote:  
 
 


@yuriyart switch to hte beta channel or change your decoder to Native Hardware

**Comment by koush** [comment]
Fixed by making webcodec the default.

**Comment by yuriyart** [comment]
Hi Koush,Is it a way to keep the version not updated?I installed it old and was fine, as soon it updated and reloaded I got a white screen saying "Vysor failed to start...."Not happy








    On Friday, July 9, 2021, 12:16:36 PM PDT, Yuriy B Art Gallery ***@***.***> wrote:  
 
  Thank you Koush, it did improve

    On Friday, July 9, 2021, 11:47:34 AM PDT, Koushik Dutta ***@***.***> wrote:  
 
 


@yuriyart switch to hte beta channel or change your decoder to Native Hardware

**Comment by koush** [comment]
@yuriyart what desktop OS? If windows, try this https://github.com/koush/vysor.io/releases/tag/v4.1.47

**Comment by koush** [comment]
@yuriyart let me know if that fixes it.

**Comment by yuriyart** [comment]
so not sure what happened, after i logged in so far is working, will let you know if anything changed tomorrow.

    On Tuesday, July 13, 2021, 9:31:21 PM PDT, Koushik Dutta ***@***.***> wrote:  
 
 


@yuriyart what desktop OS? If windows, try this https://github.com/koush/vysor.io/releases/tag/v4.1.47

**Comment by yuriyart** [comment]
Hi Koushik,Is there is a reason why I was removed from TestFlight? How I can renew that?My apple id ***@***.***

    On Tuesday, July 13, 2021, 09:31:28 PM PDT, Koushik Dutta ***@***.***> wrote:  
 
 


@yuriyart let me know if that fixes it.
