### ISSUE TITLE
Android: Vysor 4.1.29 crashes during startup

### ISSUE THREAD

**Issue by MisterEd51** [koush/vysor.io#832]
**Describe the bug**
Vysor 4.0.29 worked fine
Updated to Vysor 4.1.29
Program crashes during startup
Had to reinstall Vysor 4.0.29 for it to work again

Desktop
OS: Windows 10 21H1 (Build 19043.1083)
Vysor Version: 4.1.29 (upgraded from 4.0.29)

Samsung S21 5G
OS: Android 11

Vysor Pro Subscription

**Vysor 4.0.29**
![Vysor 4 0 29](https://user-images.githubusercontent.com/87117536/124885411-d8c8e680-df98-11eb-9dc4-b13cacc61e52.jpg)

**Vysor 4.1.29**
![Vysor 4 1 29](https://user-images.githubusercontent.com/87117536/124885262-b59e3700-df98-11eb-8e0e-2c704447f652.jpg)

**Comment by koush** [comment]
Can you join discord so I can collect a bit more information?
https://discord.gg/xR8DpZe7

**Comment by MisterEd51** [comment]
I started with Vyzor 4.0.29 with a paid subscription
I upgraded to Vyzor 4.1.29 with Vysor-win-4.1.29.exe
Vyzor now crashes
I was told by koush on Discord to reset Ryzor 
Vyzor 4.1.29 still crashes
I used my only other install file Vysor-win-3.1.4.exe
Now it says I am back to Ryzor 3.1.4 free version
I tried to retrieve my license but it says I have none
However if I go to app.vysor.io and log in it says I do have a subscription
How do I get Vyzor to recognize my subscription and get me back to Vyzor 4.0.29
