### ISSUE TITLE
Andriod: 

### ISSUE THREAD

**Issue by Jacolene83** [koush/vysor.io#834]
**Describe the bug**
Not able to open up the phone mirror screen, even though I am connected and debugging is enabled. The mirror screen does open up, but if I click on it, it is not coming to the front. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vysor Pro Version 4.0.63

**Android (please complete the following information):**
 - Device: Huawei Y7 Pro 
 - OS: Android 8.1.0
 - Vysor Bug Report Link: https://gist.github.com/36d15cb96f74acc9f5befe7f864d0ee0

**Comment by koush** [comment]
Can you provide a screenshot? Is the window off screen or something?
