### ISSUE TITLE
iOS: Stuck on connecting with black screen!

### ISSUE THREAD

**Issue by China3x** [koush/vysor.io#835]
**Describe the bug**
Keep saying connecting to Vysor on iOS, but black screen.

**Attach a Vysor Bug Report Log**
https://gist.github.com/VysorLogs/72e9bc6e2994b5fec7a72a21e67c3ef5

**To Reproduce**
1. Go to 'connect, press connect iOS'.
2. Click on 'iPhone'.
3. Bluetooth and light cable connected, waiting to show the screen of the phone (iPhone 11).
4. See error (just keep saying connecting, but nothing happens).

**Expected behavior**
See the screen of my iPhone.

**Screenshots**
Just black background with the message connecting.

**Desktop (please complete the following information):**
 - OS: [ macOS Big Sur 11.4 ]
 - Vysor Pro Version [4.1.39] runtime 4.1.29

**iOS (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS 14.6]
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/72e9bc6e2994b5fec7a72a21e67c3ef5

**iOS Bluetooth Issues:**
 - Mac/Computer Model MacBook Air M1, 2021
 - Other devices connected with computer via Bluetooth
 - Other devices connected with iOS via Bluetooth

**Additional context**
Everything is connecting, but nothing showing, I've changed to Beta, also to native hardware.
Nothing works.

**Comment by koush** [comment]
Did it work previously, or is this a new issue?
can you try the beta channe; and set the decoder to webcodec software?

**Comment by China3x** [comment]
> Did it work previously, or is this a new issue?
> can you try the beta channel and set the decoder to webcodec software?

It worked first time before I buy the Pro, after I bought it didn't work anymore.
I've tried to change to all setups, nothing works.

**Comment by koush** [comment]
I suspect this is stuck Media Services on iOS. You can reset Media Services in IOS Settings developer menu, or simply restart the phone.

**Comment by China3x** [comment]
> I suspect this is stuck Media Services on iOS. You can reset Media Services in IOS Settings developer menu, or simply restart the phone.

solved thanks
