### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by Suncho1** [koush/vysor.io#836]
the app is deliting himself from the phone evrytime i connect it with the comp with usb :D idk why is happening i tried to reinstall them but didnt work

**Comment by koush** [comment]
You're behind a firewall or something is preventing the app install on your phone. You can install it manually here.

https://app.vysor.io/Vysor-release.apk

**Comment by Suncho1** [comment]
Got deleted again

На пн, 12.07.2021 г., 1:17 ч. Koushik Dutta ***@***.***>
написа:
