### ISSUE TITLE
Android: Desktop NOTIFICATION "Keyboard change" stop please !

### ISSUE THREAD

**Issue by Alaingent** [koush/vysor.io#838]
PLEASE , in "notifications on desktop" option  (very cool option that totally fonction now with link by clicking on) :  could you make possible to hide especially 2 notifications :  the first and the most important "keyboard change / Vysor" notification and "battery charging. Complete charged in 1 hour" notification. These 2 notifications appear on desktop at least 100 times per day, it is .... not possible :)

**Comment by koush** [comment]
Tracking filtering:
https://github.com/koush/vysor.io/issues/850
