### ISSUE TITLE
Android: SLOW speed since 5 days

### ISSUE THREAD

**Issue by Alaingent** [koush/vysor.io#839]
Pro user, i m disappointed because since approximatively 5 days, there is a speed problem. Normally on my desktop with USB cable connection, with 1,5Mb speed and "50%" quality all is very quick and pleasant. BUT since 5 days i have to put "25%" of quality if not, it is not possible to use Vysor (too slow). Could you verify ? because at office there is no change on network or my computer. 

thank you.

**Comment by koush** [comment]
Please set the decoder to WebCodec to resolve this.

**Comment by koush** [comment]
What video card?

**Comment by Alaingent** [comment]
i already try all the new version of codec, and no, this do nothing better. My computer is HP pavilion X2 with Pentium N3510 core and Intel HD Graphics from 2014 year. from 2 years, it was ok.

**Comment by contactjoshbell** [comment]
Similar problems here related to the latest update to 4.1. Running a Mac Mini (late 2014) Big Sur 11.4, 3ghz Dual Core i7. Intel Iris 1536 MB graphics card. 500KBPS and 50% res. Two different phones both have issues. Galaxy A10 (SM-A105M) runs webcodec, but noticeable drop in res and performance - better res and performance with "native software/hardware options (like @Alaingent said, 25% res helps with speed, but not practical for viewing). Galaxy A10 (SM-107M) gives me a black screen on all webcodec/webassembly options - only "native hardware/software" works). Force H264 has no effect. Previously was on webassembly for both devices with no res or performance issues.

**Comment by koush** [comment]
> Similar problems here related to the latest update to 4.1. Running a Mac Mini (late 2014) Big Sur 11.4, 3ghz Dual Core i7. Intel Iris 1536 MB graphics card. 500KBPS and 50% res. Two different phones both have issues. Galaxy A10 (SM-A105M) runs webcodec, but noticeable drop in res and performance - better res and performance with "native software/hardware options (like @Alaingent said, 25% res helps with speed, but not practical for viewing). Galaxy A10 (SM-107M) gives me a black screen on all webcodec/webassembly options - only "native hardware/software" works). Force H264 has no effect. Previously was on webassembly for both devices with no res or performance issues.

Can you generate a bug report please.

**Comment by koush** [comment]
@ringthembells generate a bug report for me please.

**Comment by koush** [comment]
Can you try this prerelease build? https://github.com/koush/vysor.io/releases/tag/v4.1.45

**Comment by ringthembells** [comment]
> @ringthembells
> 
> Oh if this is Mac, I've had a couple users tell me they were able to reinstall the app or restart the computer and everything worked. Unsure why. #831

Seems like restarting the Mac worked and res and speed are both good now - no problems with webcodec now. I'll let you know if it starts lagging again.

**Comment by koush** [comment]
@ringthembells Can you generate a bug report of your successful mirroring session so I can check some things?

**Comment by koush** [comment]
@Alaingent Please try restarting your computer like this other user did.

**Comment by ringthembells** [comment]
https://gist.github.com/12530d73337ebe302e395d78ac56cc59

Here you go. I usually have several vysor windows open but was only able to generate a bug report with one device open (received error 500 with multiple vysor windows open).

**Comment by ringthembells** [comment]
@koush one other thing. i bumped up to the beta version to try and fix some other copy/paste related issues - so that why i'm in beta in this bug report. the speed/res problems were solved by the restart, i believe.

**Comment by Alaingent** [comment]
for the moment all is still very slow...

**Comment by koush** [comment]
> for the moment all is still very slow...

You restarted and tried the prerelease build?

**Comment by Alaingent** [comment]
i will test this release i didn't see it before.

**Comment by Alaingent** [comment]
i try to uninstall last release and install yours Vysor-win-4.1.45.exe
but with this single file when i click on it there is nothing happen, the program doesn't launch

**Comment by koush** [comment]
@Alaingent sorry, there was a bug in that build that prevented startup. Please try this one:
https://github.com/koush/vysor.io/releases/tag/v4.1.46

You may need to kill Vysor in the task manager too.

**Comment by Alaingent** [comment]
i install it the release 4.1.46 and ... exactly the same, very slow. ten days ago, all was ok, but what is happened ?

**Comment by koush** [comment]
I'm not sure, you never included a bug report. Please do that.

**Comment by Alaingent** [comment]
https://gist.github.com/fcc2ff4f5773dfb398ea61c997ea7975 

is it that ?

**Comment by koush** [comment]
Go into Vysor settings, click defaults to see if it fixes it. Then generate another bug report.

**Comment by Alaingent** [comment]
ok so, yes it is better and very fast BUT like free version with 25% graphic detail.... because default put "recommended..." and 1mb

so, no for my pro version, it is not good to obtain a bad quality. Fast but bad. From 2 years ago to now, i always had 50% quality (better) and 1,5mb fast quality. sorry.

**Comment by koush** [comment]
> ok so, yes it is better and very fast BUT like free version with 25% graphic detail.... because default put "recommended..." and 1mb
> 
> so, no for my pro version, it is not good to obtain a bad quality. Fast but bad. From 2 years ago to now, i always had 50% quality (better) and 1,5mb fast quality. sorry.

If you change it to 50% is it still slow?

**Comment by Alaingent** [comment]
yes if i put 50% it is still slow here is the bug report "new version"  https://gist.github.com/9cfd3de5a5db086b755c014c6c9c8d12

**Comment by koush** [comment]
Please test this 

https://github.com/koush/vysor.io/releases/tag/v4.1.47

**Comment by Alaingent** [comment]
i try the new one. It is better but not yet on the "past level". But we pogress !

**Comment by koush** [comment]
> i try the new one. It is better but not yet on the "past level". But we pogress !

Generate a bug report of the new one while mirroring please.
