### ISSUE TITLE
H.264 AVC licensing

### ISSUE THREAD

**Issue by eligrey** [koush/vysor.io#84]
I noticed that you include an H.264 decoder directly in your CRX. Are you paying the MPEG-LA AVC patent portfolio license?

See <https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Patent_licensing> for more information.

**Comment by eligrey** [comment]
Is that a yes?

**Comment by eligrey** [comment]
@koush Is that a yes?

**Comment by eligrey** [comment]
@koush Seems like that was a "no"? https://plus.google.com/u/0/110558071969009568835/posts/717zTopZSWf

**Comment by pmarreck** [comment]
Well, _that_ came back to bite you in the ass, didn't it? :dizzy_face: 

Next time a dev warns you of something, best to not simply just ignore it

**Comment by koush** [comment]
Didn't read this issue, as I just bulk closed everything that day that did not look relevant. In any case, based on the timing on when I closed this issue (May 11th, and he had left a comment here too that is now deleted), and when I received the MPEG-LA notice, I do not think it is far fetched to say he's the one that notified the MPEG-LA.

In any case, I switched to Chrome 48's pepper decoder.

**Comment by eligrey** [comment]
@koush I actually use Vysor, so I wouldn't want it taken down either. I hope it comes back soon :)
