### ISSUE TITLE
Something Wrong with recent update v2

### ISSUE THREAD

**Issue by marcrdz911** [koush/vysor.io#840]
I report a problem last week with having to change the settings after an update, now again, visor updated and i had to change now from 6mbit to 4 mbit speed so it is not laggy. i had it in 8mbit with no problem before the first update. 

 - Device: Mate 20 pro
 - OS:  Android 10

Vysor Pro Version 4.1.42 runtime 4.1.29

 - Vysor Bug Report Link: [instructions follow, you must attach a bug report that contains the application errors and logging]

https://gist.github.com/22919341660b1febba76cd42616037f9

**Comment by koush** [comment]
Can you try using web codec hardware as the decoder?

**Comment by koush** [comment]
Can you try this prerelease build? https://github.com/koush/vysor.io/releases/tag/v4.1.45

**Comment by koush** [comment]
https://github.com/koush/vysor.io/releases/tag/v4.1.46

**Comment by coolloop61** [comment]
I had a lot of failed versions coming through this morning but this 4.1.46 build finally worked for me! Thanks, your program is imperative to my content creation!! ! Thank you!

**Comment by koush** [comment]
> I had a lot of failed versions coming through this morning but this 4.1.46 build finally worked for me! Thanks, your program is imperative to my content creation!! ! Thank you!

@coolloop61 
Can you describe your issue (I assume similar to this one), and desktop operating system? And which version specifically fixed it?

**Comment by coolloop61** [comment]
The latest from the website about an hour ago would load in safe mode and ask me to reset or reload but then nothing would happen. I tried 4.1.29(Safe mode) and 4.1.45(wouldn't show anything) 

then I noticed this thread and grabbed 4.1.46 and popped right up
![vysor](https://user-images.githubusercontent.com/69646433/125502620-a511a1a7-9bd1-45ee-99b8-b90c6e7c411e.png)

**Comment by coolloop61** [comment]
The latest from the website about an hour ago would load in safe mode and ask me to reset or reload but then nothing would happen. I tried 4.1.29(Safe mode) and 4.1.45(wouldn't show anything)

then I noticed this thread and grabbed 4.1.46 and popped right up

![vysor2](https://user-images.githubusercontent.com/69646433/125502729-7e7f19a9-920f-4849-930d-83afeaabf670.png)

**Comment by koush** [comment]
> The latest from the website about an hour ago would load in safe mode and ask me to reset or reload but then nothing would happen. I tried 4.1.29(Safe mode) and 4.1.45(wouldn't show anything)
> 
> then I noticed this thread and grabbed 4.1.46 and popped right up
> 
> ![vysor2](https://user-images.githubusercontent.com/69646433/125502729-7e7f19a9-920f-4849-930d-83afeaabf670.png)

Can you generate a bug report for me? I need to verify the issue I think it is.

**Comment by coolloop61** [comment]
I can try to later. Gotta catch up on projects. Good luck with it!!

**Comment by koush** [comment]
it's just one button. 
<img width="800" alt="Vysor" src="https://user-images.githubusercontent.com/73924/125509433-daa34c9b-2f6c-4077-b498-59d5e614510d.png">
