### ISSUE TITLE
New version crashing launched on Glass EE2

### ISSUE THREAD

**Issue by sbolka1** [koush/vysor.io#841]
Hi, the updated ADB from a couple weeks ago creates a crash loop in the Google Glass Enterprise Edition 2 product.  After connecting Vysor to the EE2 device and the adb is updated an crash error starts looping in the EE2 launcher.  Device become completely unresponsive and only solution is to uninstall the Vysor ADB via command line.  Confirmed this on Chrome, MacOS and Windows versions of the Vysor app.

**Comment by koush** [comment]
Thanks for the report, please recreate it with the bug report template properly filled out.

**Comment by koush** [comment]
You're missing basic things like the logcat, etc.
