### ISSUE TITLE
Android: Recent update showing green lines display

### ISSUE THREAD

**Issue by chandrucrypto** [koush/vysor.io#842]
**Describe the bug**
After updating to the lates version started getting green lines.. This had started happening right from today mornig..

![CleanShot 2021-07-13 at 16 19 07](https://user-images.githubusercontent.com/73110189/125439695-6a05aca9-cb7d-40e2-bc87-310768c4af72.png)

I tried switching the versions, beta to stable and vice versa channels, and nothing worked.. Please find the possible bug reports on the version changes..

https://gist.github.com/VysorLogs/13fdf3630304e5abd6bdb62fd6979ed9
https://gist.github.com/f96a360a06f48942510c104b8c9cb655
https://gist.github.com/VysorLogs/f888912bdce9272c5ae7e2af88ff0f89

**Comment by koush** [comment]
Restart one at a time to determine which it may be.

**Comment by koush** [comment]
Seems to be a Chrome graphics bug. User resolved by using webcodec software.
