### ISSUE TITLE
Lagging after update

### ISSUE THREAD

**Issue by Up2HighHell** [koush/vysor.io#844]
Lagging from the update this afternoon is making the software unusable. Bug report below. Please advise.

https://gist.github.com/dc27a9e4614f5708a2fd6da9b0a420c9

**Comment by koush** [comment]
I need a bug report with the device screen mirroring open.

**Comment by koush** [comment]
I advise you to use the issue template.

**Comment by koush** [comment]
Try this and report back. https://github.com/koush/vysor.io/releases/tag/v4.1.47

**Comment by Up2HighHell** [comment]
I dont know how to use the link you sent. I click the v4.1.47 button but it doesn't do anything.

**Comment by koush** [comment]
https://github.com/koush/vysor.io/releases/download/v4.1.47/Vysor-win-4.1.47.exe

Install this

**Comment by Up2HighHell** [comment]
Thank you that seems to have fixed the lagging issue. What's the difference between what I had previously and what I just downloaded?

**Comment by koush** [comment]
@Up2HighHell 

There were two different possible fixes, but I'm unsure which one it is. Can you also try installing this and letting me know if it gets laggy again. Once I can confirm what change fixed it, I'll roll out it out so it doesn't break again in a future update.

https://github.com/koush/vysor.io/releases/download/v4.1.49/Vysor-win-4.1.49.exe

**Comment by Up2HighHell** [comment]
That one caused it to start lagging again. I went back to the previous one and now it doesn't lag.

**Comment by koush** [comment]
Thanks for confirming the issue, I'll roll out a proper fix shortly.
