### ISSUE TITLE
Android: Two different tablets but Vysor thinks they are the same?

### ISSUE THREAD

**Issue by haggie333** [koush/vysor.io#846]
Hello, firstly I really like your product it has helped my efficiency hugely. So thanks for creating it.

I have an issue let me describe it as best I can. 

I have two tablets.
TABLET 1
TABLET 2

I connect TABLET 1 to vysor and it is recognised in the main screen as TABLET 1 after I rename it. 
I connect TABLET 2 to vysor but it does not show up in the main screen only TABLET 1 shows.
I disconnect TABLET 1 and TABLET 1 still shows in the main screen but when I open it, it is TABLET 2 that I am controlling.

Vysor is not managing to separate my two devices and thinks TABLET 2 is TABLET 1.

Thanks.

**Comment by koush** [comment]
I bet they have the same serial number due to a manufacturer defect. I have seen this on occasion. That's how Vysor identifies devices uniquely. If that's the case there's nothing that can be done.
You can plug them in individually and inspect the serial number in Vysor.

**Comment by koush** [comment]
ADB will report them as 1 device, so Vysor will see it as 1 device.

**Comment by koush** [comment]
Also, is there a reason you did not use the bug report template? I could have verified this if you had filled it out and included a bug report log.

**Comment by haggie333** [comment]
> I bet they have the same serial number due to a manufacturer defect. I have seen this on occasion. That's how Vysor identifies devices uniquely. If that's the case there's nothing that can be done.
> You can plug them in individually and inspect the serial number in Vysor.

Yes I have just tested four tablets of the same make (TELCAST T30s) and they all have the same serial number. 

The reason I did not use the bug report templet is because tbh I'm not very techy and not sure what I'm doing. But I have tested it now and if as you say there is nothing that can be done I will need to find some tablets/devices which work with Vysor. 

Thanks!

**Comment by koush** [comment]
There's an off chance that a manufacturer update may fix it, but unlikely.
