### ISSUE TITLE
Android: Unable to type after using paste(CTRL+V)

### ISSUE THREAD

**Issue by roamingphantom** [koush/vysor.io#847]
**To Reproduce**
1. Copy something in android/your desktop.
2. Go to your android and paste the text to any textbox/field/such using CTRL+V.
3. Try to type anything. 
4. Any keys will not work/recognized except for backspace and enter. Even by pressing backspace/enter, you still can't type anything.
5. To type again, you need refocus your cursor/click somewhere.

**Expected behavior**
Able to continue to type after pasting some text.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Android:**
 - Device: OnePlus 3T
 - OS: Android 8.0 (H2OS OP3T_H2_BETA_31)
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/554e6dfc6d1a132f33915c74bf82d755

**Comment by koush** [comment]
Your bug report did not have the device window open, so it didn't have any useful information.

I did reproduce the issue however. Can you confirm that you are using international keyboard?

**Comment by koush** [comment]
Fixed in beta
