### ISSUE TITLE
Vysor needs Notification Filtering settings

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#850]
Regex or something to filter out notifications.

**Comment by koush** [comment]
New settings in Customize Vysor will give you access to filtering notifications by title or text.

Here's the default value. Users may need to reset Vysor customizations to see it (or add it themselves).

```json
  "notifications": {
    "blocklist": [
      "Vysor is hiding your keyboard"
    ]
  },
```

**Comment by SeriousM** [comment]
Is it also possible to use regex here? Some texts contain variable content...

**Comment by koush** [comment]
Yes it tests it as a regex
