### ISSUE TITLE
Android: Not screen mirroring

### ISSUE THREAD

**Issue by mystgroup** [koush/vysor.io#851]
**To Reproduce**
1. Open up program
2. Press the "play" button
3. Error message says it can not find electron.asar file

**Expected behavior**
Screen mirroring

**Screenshots**
![Vysor](https://user-images.githubusercontent.com/87481959/125792118-a5b0a7ec-5cd0-4181-b03b-24bcae200ce2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Android (please complete the following information):**
 - Device: Samsung Galaxy Tab 2
 - OS: Android 4.0

**Comment by mystgroup** [comment]
Why did you close the ticket? It is still a problem

**Comment by koush** [comment]
You did not attach a bug report.

**Comment by koush** [comment]
It’s the very first step.

**Comment by mystgroup** [comment]
Ok. Can we reopen it so I can attach the bug report?

**Comment by koush** [comment]
Oh android 4.0 is not supported.

**Comment by mystgroup** [comment]
Ahh that makes sense. Ok thank you

**Comment by mystgroup** [comment]
So I have some updated information. I apologize for all the trouble. The version on the table is actually Android 9.

Here is the bug report:
https://gist.github.com/VysorLogs/d017137f05085db854f5d8b495755958

Again, I apologize for not having accurate information.

**Comment by koush** [comment]
You are out of room on your device. Can you make some space? You can also try clearing /data/local/tmp manually if you know how to do that.

**Comment by koush** [comment]
> Caused by: java.io.IOException: Requested internal only, but not enough space
