### ISSUE TITLE
Moirée on png-screenshot 

### ISSUE THREAD

**Issue by hatt62** [koush/vysor.io#852]
Since I upgraded to Android 12 beta 3 today, I got a weird moirée pattern in my *.png file after doing a screenshot when opening it in Photoshop. Didn't notice this effect in the macOS preview app with the same file. Screenshot file where moirée occurs has been attached. Effect occurs since beta 3.
![screen](https://user-images.githubusercontent.com/84533662/125812063-eacba921-c9c1-45c1-9bc4-a4f2324f29c5.png)

**Comment by koush** [comment]
I don’t see anything? You may need to screenshot the screenshot for me to see the rendering issue.

**Comment by hatt62** [comment]
Ah, o.k. See this one here:
<img width="1308" alt="Bildschirmfoto 2021-07-15 um 17 29 50" src="https://user-images.githubusercontent.com/84533662/125815107-8d96832d-a7b0-4b3b-b8b2-76746452bad6.png">

**Comment by hatt62** [comment]
Strange, it appears in Photoshop and Pixelmator, but not in browser or macOS preview.

**Comment by koush** [comment]
Can you get me some rgb (or yuv values since this is a png) of that blue pattern? Does it vary? Is there alpha variance maybe?

**Comment by hatt62** [comment]
Did a screenshot yesterday, RGB values from blue solid background are R=1, G=80 and B=147. Using the app RGB Color Wallpaper. Hex code of chosen color is #005093.  Didn't get what you mean with alpha variance ...

**Comment by koush** [comment]
Is there an alpha/transparency channel on that image?

**Comment by koush** [comment]
Confirmed your image does have an alpha channel. I think I understand the issue now.

**Comment by hatt62** [comment]
Great! Just working out my last pages (last 15 from 370) for an android user manual I'm publishing in germany. Your great tool helped me a lot to get all the screenshots for the book done. Would be nice if we could solve the problem for further editions ;-)
