### ISSUE TITLE
Feature Req: Add Shortcut to Change Orientation.

### ISSUE THREAD

**Issue by badhorky** [koush/vysor.io#86]
I would like to be able to change the orientation, portrait <-> landscape, from Vysor, ie. without touching the device itself, but from a vysor menu (like F2) in the Chrome App.

**Comment by GENHEN** [comment]
This already exists right? It is a little rotate button on the right side of the screen as soon as you click on vysor

**Comment by badhorky** [comment]
True, I somehow missed that.
