### ISSUE TITLE
reset all phone window sizes!

### ISSUE THREAD

**Issue by woods333** [koush/vysor.io#860]
After the (10th / lost count) auto update in a week, latest one has reset all phone window sizes so now have to resize them all again... please make sure this does not happen in any update.

**Comment by koush** [comment]
Are you on the beta channel? The stable channel has gotten

**Comment by koush** [comment]
I think you’re on the beta channel probably. Go back to stable.

**Comment by woods333** [comment]
What does that mean? I just downloaded the software, I don't get this developer language aha?
