### ISSUE TITLE
No audio mirroring when making call

### ISSUE THREAD

**Issue by opsva** [koush/vysor.io#861]
Audio mirroring works ok when using youtube for example.
But when making a call audio doesn't get mirrored.

samsung A01 Core (SM-A013M)
Android 10
vysor 4.1.54 on windows 10.

**Comment by koush** [comment]
Correct, phone audio can not be captured since it is sensitive communication.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/73924/126194602-8333914a-f671-4164-9f7d-2f273323dad6.png">

https://android-developers.googleblog.com/2019/07/capturing-audio-in-android-q.html

**Comment by opsva** [comment]
thanks , does that mean that i can explicitly allow for audio call to be mirrored?

**Comment by koush** [comment]
no
