### ISSUE TITLE
iOS: Beta Channel and Stable channel getting blank screen when trying to connect

### ISSUE THREAD

**Issue by psAppscrip** [koush/vysor.io#862]
**
[fbcad58185b253ab9fc4d4de7c0ed362-283017c536b2640a5c9724d9493c38e72b89ad2f.zip](https://github.com/koush/vysor.io/files/6845232/fbcad58185b253ab9fc4d4de7c0ed362-283017c536b2640a5c9724d9493c38e72b89ad2f.zip)
Vysor Bug Report attached**

**To Reproduce**
1. open vysor
2. Click on connect iOS Device
3. a black screen opens and I get error messaeg
4. See error message as attached jpeg
![2021-07-19_22h04_11](https://user-images.githubusercontent.com/87683727/126255847-2033ed95-0231-4137-b685-f4314ed31652.jpg)

**Expected behavior**
View the iOS phone screen mirrored

**Screenshots**
added

**Desktop (please complete the following information):**
 - OS: windows 11

**iOS (please complete the following information):**
 - Device: iPhone XR
 - OS: 14.6
 - Vysor Bug Report Link: added as zip

**Comment by koush** [comment]
You need to sign up to get access to the iOS app.

**Comment by psAppscrip** [comment]
I am signed in, I have a chrome pro license. I did the same thing on the stable app as well as Beta one.

**Comment by koush** [comment]
It's in beta, you use the form to get access to the beta. I have not given you access yet.
