### ISSUE TITLE
Heavy lag

### ISSUE THREAD

**Issue by blscha** [koush/vysor.io#863]
New update lags really bad. Please link a few rollbacks one of the recent updates was working fine. I need this for work and i don't have time to trouble shoot thanks

https://gist.github.com/e7f19cc4fc3cc73148e3e1d0ddc3234e

**Comment by koush** [comment]
There's no old version.

What GPU do you have? Your logs say intel? Can you try setting your image quality to medium or high instead of max?

**Comment by blscha** [comment]
I tried different quality settings and it didn't make a difference. What do
you mean theres no rollbac? the other version works fine.

I plugged it into my other computer that has a version that hasn't updated
and it works fine. Used the same cable same device.

**Comment by koush** [comment]
What graphics card do you have?

**Comment by blscha** [comment]
Its a Intel(R) UHD Graphics

**Comment by koush** [comment]
Please try using webcodec software as your decoder.

**Comment by blscha** [comment]
I think it worked! I'll use it later and let you know if it starts bugging
again thanks
