### ISSUE TITLE
Android: Latest update gives a blocker error

### ISSUE THREAD

**Issue by florinfmi** [koush/vysor.io#865]
Hi,
Since the latest update, I get the following error:
![image](https://user-images.githubusercontent.com/38680886/126363805-da930ecd-c0fb-4201-ac78-f09d9bcd35e2.png)

Bug report: https://gist.github.com/144fe39689c4caa9e08dce446a0a803c

Thanks!

**Comment by koush** [comment]
Can you reload the app (using the button in the main device list), encounter this bug, and generate another bug report. Leave this window open when generating the report.

**Comment by koush** [comment]
You may also want to just try reinstalling the app. Maybe the update did not fully apply. Weird error.

**Comment by siam-backend-developer** [comment]
hello koush 
please solve this problem ctrl+v it's not working in 6.0 android
