### ISSUE TITLE
Android: Not mirroring screen

### ISSUE THREAD

**Issue by pinkydesai** [koush/vysor.io#866]
**To Reproduce**
1. Open Vysor app
2. Press the "play" button
3. Error message says "Invalid package /Applications/Vysor.app/Contents/Resources/electron.asar"
Expected behavior
Screen mirroring
**Expected behavior**
App should mirror the Android device.

**Screenshots**
<img width="499" alt="Screen Shot 2021-07-20 at 1 11 46 PM" src="https://user-images.githubusercontent.com/21109523/126378113-31b992ee-25f7-4d6b-97b7-1f089964651b.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4

**Android (please complete the following information):**
 - Device: Pixel3
 - OS: Android 12 Beta 2
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/0bdaf145b61532c1a44209f3f7510b7d
 
**Additional context**

**Comment by koush** [comment]
You need to update vysor. https://www.vysor.io/download/?return=https%3A%2F%2Fwww.vysor.io%2F

**Comment by pinkydesai** [comment]
Updated the Vysor, still same error - https://gist.github.com/VysorLogs/ba6cd3e4bc44d430646629a29dcaa519

**Comment by koush** [comment]
When you create the bug report, are you leaving the window with the error open? I don't seem to be getting everything I need from the log. Can you generate another?

**Comment by pinkydesai** [comment]
I uninstalled and reinstalled app, no difference. I reloaded app from the main screen, got error, kept window open, then generated the bug report. I have Vysor Pro License.

**Comment by koush** [comment]
Thanks for confirming. I wonder if something in the update process got stuck (adb daemon possibly). Can you reset and reboot the Mac?

<img width="739" alt="Vysor" src="https://user-images.githubusercontent.com/73924/126381803-02958210-868f-41d9-9566-e5326e823a74.png">

**Comment by koush** [comment]
A stuck process would also explain why the logs seem truncated too.

**Comment by pinkydesai** [comment]
I reset Vysor, rerboot Mac but same bug report - https://gist.github.com/VysorLogs/298b3acb861284a7732e7fecc0537512

**Comment by koush** [comment]
Normally this would be in teh log, but what is the last thing it shows as status text as you try to mirror? Is it trying to install the APK?

**Comment by pinkydesai** [comment]
yes it tried installing APK and then error - 

https://user-images.githubusercontent.com/21109523/126388998-0d9b7206-a5a8-4e6f-867b-3417ac046a77.mov

**Comment by koush** [comment]
Thanks. Can you switch to the beta channel real quick and try this? (and do another video)

**Comment by koush** [comment]
Beta channel is in the bottom menu near reset.

**Comment by koush** [comment]
This looks like the service worker is failing, which is why the cached apk is failing to install. Are you behind a VPN or anything?

**Comment by pinkydesai** [comment]
yes I'm behind firewall. attached video for beta channel

https://user-images.githubusercontent.com/21109523/126390412-daf307b6-ffe3-4e07-8cfe-0e63f3a68285.mov

**Comment by koush** [comment]
Ok, cool. that's probably the issue. Can you check some things:

Does this page load for you in Safari with your firewall?
https://beta.vysor.io/vysor-service-worker.js

Does Vysor work in offline mode launched with:
```
USE_OFFLINE=true open /Applications/Vysor.app
```

Also, can you turn off the firewall and see if Vysor starts? Wondering if some content is being blocked.

**Comment by pinkydesai** [comment]
I can load this in safari - https://beta.vysor.io/vysor-service-worker.js

Vysor starts in off-line mode but same error - connection error when pressing "play"

**Comment by koush** [comment]
Ok, install this via side load:
http://electron.vysor.io/Vysor-release.apk

And then go back to the stable channel. You should be able to start up. Will need to look into this some more.

**Comment by koush** [comment]
Did the sideload work?

**Comment by pinkydesai** [comment]
yes. sideload  worked
