### ISSUE TITLE
how to solve the vysor error when i try to mirror the phone

### ISSUE THREAD

**Issue by vitor78952** [koush/vysor.io#867]
Microsoft C++ Runtime libary
Assertion failed
Program:...p-1.9.3.crx-unpacked\native\win32\video_decode.dll
File:video_decode.cc
Line:336
Expression: result= =PP_ok
for information on how program can cause an assertion failure,see the visual C++documentation on asserts
(Press Retry to debu the apllication- JIT must be enabled) como resolver esse erro

**Comment by koush** [comment]
you're using an extremely old version. Please redownload it from https://vysor.io
