### ISSUE TITLE
Android: Vysor not selecting images in Google My Business App

### ISSUE THREAD

**Issue by muvera** [koush/vysor.io#869]
![snap1](https://user-images.githubusercontent.com/6589491/126570186-8684d7f3-6ce9-494b-a0b5-98448ce59b16.jpg)
![snap2](https://user-images.githubusercontent.com/6589491/126570189-9f14cd96-2ec9-4cd2-b0ab-a1837eaa1fb7.jpg)
![snap3](https://user-images.githubusercontent.com/6589491/126570194-ad96eb89-2015-4e14-9ab8-329969f255ac.jpg)
![snap4](https://user-images.githubusercontent.com/6589491/126570195-0ce91382-b722-480b-bc29-749eda734514.jpg)
![snap5](https://user-images.githubusercontent.com/6589491/126570199-5732a10f-478b-4748-8c1b-c8198d1a5991.jpg)
![snap6](https://user-images.githubusercontent.com/6589491/126570200-2c9b59f6-e304-4a7e-b07d-ca1743b81d2d.jpg)

**Comment by muvera** [comment]
Vysor works great on all apps but it won't select images on the Google My Business App images. FYI the Google My Business app will only select if I use my fingers. Oops. (bump)

**Comment by muvera** [comment]
I found a way to work around this issue. Press the TAB key on the keyboard and the first image will actually be selected.

**Comment by koush** [comment]
Unfortunately this is an issue with the Google app, they are probably doing something custom and breaking stuff as a result.
