### ISSUE TITLE
Feature Req: Improved Keyboard/Shortcut Navigation.

### ISSUE THREAD

**Issue by badhorky** [koush/vysor.io#87]
I would like to be able to navigate Android using keyboard shortcuts (e.g. alt+tab: switch between apps).

This would enable quicker/more efficient navigation and give a desktop-like experience, when using Vysor.

**Comment by badhorky** [comment]
Also, it would be nice to be able to send control characters, e.g. when using bash+screen through some ssh app.

**Comment by henti** [comment]
Additionally, Ctrl-Enter to send carriage return (CR) as opposed to new line feed (LF)

**Comment by koush** [comment]
Custom key bindings implemented

https://github.com/koush/vysor.io/issues/211
