### ISSUE TITLE
Android: Stuck at Waiting for Decoder...

### ISSUE THREAD

**Issue by patggg** [koush/vysor.io#871]
**To Reproduce**
1. Launch Vysor

**Expected behavior**
The device screen displays

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.2

**Android (please complete the following information):**
 - Device: ODroid N2
 - OS: Android 9
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/4dfb4710bcdc6f5bf1591b42c901e56d

**Additional context**
No decoder works in the current version. Previously was using Native Software with success.
logcat attached

**Comment by patggg** [comment]
[adb_logcat.txt](https://github.com/koush/vysor.io/files/6859889/adb_logcat.txt)

**Comment by koush** [comment]
You're using a very old vysor version. There's a new apt repo that has automatic updates. Please download that:
https://vysor.io/download
