### ISSUE TITLE
Security issue: When unselecting Share all devices, anyone in the white can still access the any shared/connected device

### ISSUE THREAD

**Issue by GeoSaffer** [koush/vysor.io#874]
When unselecting Share all devices, anyone in the white can still access the any shared/connected device.

The only way to prevent them from accessing it is to remove the email address or add a character after the email address in the white list

**Comment by koush** [comment]
Thanks, rolling this fix out in an upcoming release. Server shutdown issue.

**Comment by koush** [comment]
Released in beta channel, if you want to confirm the fix. Will roll out to stable sometime shortly.
