### ISSUE TITLE
Lost access to account

### ISSUE THREAD

**Issue by grholl** [koush/vysor.io#875]
Hi there. 

Messaging here because you are not responding to my emails at support@vysor.io. There is a bug in your user account service that is preventing me from accessing my account. I am currently paying for services that I cannot use. 

Please respond to my email. I will continue to file these bug reports until you do. 

Thanks!

Gabe Rholl

**Comment by koush** [comment]
email that you need to cancel?

**Comment by grholl** [comment]
Hi @koush -- thanks for your reply. I did try emailing both billing@vysor.io as well as support@vysor.io and haven't received a response from either account. I've also tried sending a DM to the @vysorapp Twitter account and haven't received a response there either. I'd really just like to leave the paid tier as my need for this (client demo of mobile app in 2019) has lapsed.

**Comment by koush** [comment]
Canceled the sub from penrodsoftware.
