### ISSUE TITLE
Slow since andriod 10 update

### ISSUE THREAD

**Issue by Therepup** [koush/vysor.io#877]
https://gist.github.com/06bf5c005a26b3f5450fb48e1be768ae

Im use vysor daily and never dailed until a few days ago Im not sure but I think it got trigger by the android 10 update. Since then vysor is being unusable because its so slow I attached the bug report maybe you can tell me what to do.
https://youtu.be/pM4Ebn-yS2Q
zte 2050

**Comment by koush** [comment]
Can you try changing your decoder to WebCodec software?

**Comment by Therepup** [comment]
Nothing happend everything is still slow

**Comment by koush** [comment]
Can you please reopen this with a proper bug report. I'm missing a ton of information, like your computer and GPU, etc.
