### ISSUE TITLE
Extremely slow latest vysor build

### ISSUE THREAD

**Issue by vfigit** [koush/vysor.io#882]
**Issue**
For the past week or so
(1) Android tablet screen sharing takes several minutes to initialise and connect then 
(2) lags heavily in response, so i move the tablet screen and the change shows up as choppy roughly 10 seconds later, in some cases more than 30"

**Laptop & Desktop OS** 
Dell Inspiron 5370 Core i7 8th gen 8GB RAM
Windows 10 Pro version 20H2 build 19042.1110

**Android Device & OS** 
Samsung A6 SM-T585
T585XXS6CTJ5/T585OXX6CSL1/T585XXS6CTC3

**Vysor Bug Report Link**
https://gist.github.com/8b82119179d5f014469b87b2c4d0d436 

Also tried on Samsung Galaxy Tab S7+ 5G (SMT976B) with latest OS build and the experience is the same

Also tried WebCodec Hardware + Fallback and WebAssembly as well as laptop/tablet restarts but nothing worked.
All other codec options tried as well with no result

**Comment by koush** [comment]
What GPU do you have in that laptop?

**Comment by koush** [comment]
I just updated teh stable channel, can you verify this issue still exists? I thought I had fixed this.

**Comment by vfigit** [comment]
Looks like AMD Radeon 530.

Looks like the update worked, since now both tablets look great, thank you!
