### ISSUE TITLE
Ho do I copy and paste from desktop

### ISSUE THREAD

**Issue by kylegsp** [koush/vysor.io#883]
Hey, I am wanting to know if there is a way to copy text from my laptop to the phone on vysor? or is this not pssible?

**Comment by koush** [comment]
CTRL-C CTRL-V

**Comment by kylegsp** [comment]
> CTRL-C CTRL-V

Doesnt seem to work. I'm trying to copy from google sheets to Instagram

**Comment by kylegsp** [comment]
> CTRL-C CTRL-V

Ok definitely seems only related to Instagram. Weird.
Will copy and paste to text or word but not IG
