### ISSUE TITLE
Android: Continuous notification ding sound when connected with Vysor 

### ISSUE THREAD

**Issue by bhushan-avoma** [koush/vysor.io#885]
Urgent :
Please add settings to to mute the Desktop notification sound when android device connected 
its extremely annoying that though i am paid customer but not able to use vysor when i want to do presentation in meetings

I did not found any way to reach with technical support team over email so logged issue here

**Comment by koush** [comment]
Vysor is not making that sound, your desktop OS is. You can also just disable the notifications for a device.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/73924/127728769-430df820-2aed-4d51-8c57-22dd0691b3d2.png">

**Comment by koush** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/73924/127728776-87c88b77-4790-4659-ac49-abffed178ab7.png">
