### ISSUE TITLE
add volume control buttons, up, down, mute, to bottom control bar?

### ISSUE THREAD

**Issue by reptilian-research** [koush/vysor.io#886]
i was able to add volume up/down/mute buttons to the TitleBar.
(note: the KEYCODE_VOLUME_MUTE does not seem to work)

the buttons are quite small on the top bar, and easy to mis-click with settings-cog or Fullscreen.

is it possible to add a volume up/down/mute to the bottom bar?
(my pro account is jimmerce@gmail.com)

**Comment by koush** [comment]
Yes, use Customize Vysor https://github.com/koush/vysor.io/issues/211
