### ISSUE TITLE
Can't login to Vysor Pro

### ISSUE THREAD

**Issue by titopandub** [koush/vysor.io#888]
**To Reproduce**
1. Open Vysor
2. Click on Login
3. Click on Sign in with Google
4. Choose my Google Account
5. Get error after waiting several seconds (Operation has timeout)

**Expected behavior**
Should be logged in with my Google Account. This is only happen in Windows. In Linux it worked.

**Screenshots**
![Screenshot 2021-08-03 180244](https://user-images.githubusercontent.com/1729667/128005036-64df2a60-2430-445f-85d3-0524009fa6ec.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Android (please complete the following information):**
 - Device: ODroid N2+
 - OS: Android 9
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**

**Comment by koush** [comment]
Given that it only happened in Windows it may be a firewall issue or something. Please check that. Unfortunately I can't help you with this since this is an upstream connection issue with Firebase/Google login.

**Comment by titopandub** [comment]
Maybe, because when I register with email and try to log in, it works. I think you could close this issue. I will stop the Pro on my google account and start with this email.

Thank you.
