### ISSUE TITLE
iOS: Connection Error - Error Connecting to iOS Device TypeError: Cannot read property 'replaceAll' of undefined.

### ISSUE THREAD

**Issue by rkrmpg** [koush/vysor.io#891]
Vysor Pro Version 4.1.75 (Runtime 4.1.62)
Windows 10

iPhone 11
iOS version: 14.7.1
"Connect Vysor" app version 1.0 (1)

"AppleMobileDeviceSupport" drivers for Windows installed.
iPhone connected to computer using Lightning cable.

iPhone:
Opened "Connect Vysor" app and pressed the Screen Broadcast round icon.
Pressed "Start Broadcast"

Windows:
After the broadcasting starts pressed the "View Device" icon under iOS Devices on the Windows Vysor app.
New "iOS Device" window opens.
Pop-up box with error.
![Vysor4 1 75_error](https://user-images.githubusercontent.com/17733842/128246805-9c3fae68-49f2-4ec4-a18c-236045d0ac14.jpg)

Restarted Windows as well as restarted iPhone with the same result.

Previous version installed I did not receive an error. 
Sorry, unsure what the previous version was.
I was prompted today for the update.

Log file: https://gist.github.com/VysorLogs/7087a8499879341fe6515d9fce459e38

**Comment by koush** [comment]
Will take a look. I remember seeing this, and thought I fixed it, but can't remember what the issue was.

**Comment by koush** [comment]
Confirmed hte issue is occurring on the beta channel but not the stable channel. Investigating further. You can switch ot the stable channel in the meantime, but I Recommend windows + iOS users stay on the beta channel (so I can get feedback on bugs like this).

Beta channel will also have iOS control soon.

**Comment by koush** [comment]
Fix confirmed in beta channel. If you're interested in the Windows + iOS control beta, let me know. You'll need to get a $7-$20 IoT dongle though (not something I sell, just a third party microcontroller that plugs into the PC). One of the headaches of Windows having an insane bluetooth stack.

**Comment by rkrmpg** [comment]
I have used the Nordic nRF52840 and Adafruit nRF518222 on an occasional basis for work. Have not used it a while as I have not had the need for BLE testing with some hardware the company I work for develops.
I would be happy to be part of a Windows + iOS control beta.

Thanks for all the the work you have done in the early days of Android with cyanogen, rom manager and now with Vysor. Vysor is much better than Mirroring360.

**Comment by koush** [comment]
Oh great the Nordic will work perfect, and I presume you know how for flash it via the CLI too?

**Comment by rkrmpg** [comment]
All seems to be working OK with version 4.1.79 Runtime 4.1.62. Not receiving the same message as before.
BLE dongles I had seems to have gone missing.

**Comment by ermiscognitoiq** [comment]
> Fix released/confirmed in beta channel. If you're interested in the Windows + iOS control beta, let me know. You'll need to get a $7-$20 IoT dongle though. It's not something I sell, just a third party microcontroller that plugs into the PC. One of the headaches of Windows having an insane bluetooth stack.

Can you share the link where to buy this dongle please? Thanks

**Comment by rkrmpg** [comment]
> 
> Can you share the link where to buy this dongle please? Thanks

https://github.com/koush/vysor.io/wiki/Vysor-Dongle
