### ISSUE TITLE
Billing - Unable to get invoice / email recipient of Vysor Annual Subscription

### ISSUE THREAD

**Issue by gschwienbacher** [koush/vysor.io#892]
Hi @koush,
in July 2021 we (our company) got billed 2 "Vysor Annual Subscriptions" (USD 10 each to the same company credit card) 

![credit_card](https://user-images.githubusercontent.com/22803490/128309535-518e83d9-4abb-48c6-90e0-fb195cba0135.png)

and were only able to match one of them to an actual employee of us (email: vm.fluidtime@gmail.com) - see invoice and invoice-#:

<img width="538" alt="invoice_vlad" src="https://user-images.githubusercontent.com/22803490/128309559-dd4c3bef-e940-4db2-af5d-b056281592e2.png">
For this user we were able to get the invoice and also the affected user.

For the **other remaining "Vysor Annual Subscription"** deducted from our company credit card on July 21st or July 22nd **we are not able to find out the affected user** and therefore we can not get the **invoice**. Maybe it's a former employee who left the company.

Please help us find out **which account/email** generated the 2nd payment of the "Vysor Annual Subscription" and send us/me the **invoice**. (Out company uses the @fluidtime.com suffix, so maybe it is an account w/ this suffix...) The credit card used is the same in both cases - you'll find it on the billing of the above listed payment - the last 4 digits are 7210. If you need additional information please let us know.

**Thanks for your help!**

**Comment by koush** [comment]
Can you paste the invoice number please

**Comment by koush** [comment]
I found a matthias.karan@fluidtime.com, but that was billed in April

**Comment by koush** [comment]
And fluidtimegregor@gmail.com

**Comment by gschwienbacher** [comment]
> Can you paste the invoice number please
Hi @koush, thanks for your reply, unfortunately this is the only information we got, so we are not able to state the invoice number:
![credit_card](https://user-images.githubusercontent.com/22803490/128309535-518e83d9-4abb-48c6-90e0-fb195cba0135.png)

Matthias Karan is also an employee of us and we checked w/ him, but his subscription should have been cancelled.

The one w/  fluidtimegregor@gmail.com  sounds very interesting, we'll check that, b/c we had a former employee named gregor.

Thanks in the meantime!

**Comment by gschwienbacher** [comment]
> And [fluidtimegregor@gmail.com](mailto:fluidtimegregor@gmail.com)

Could we have a screenshot of this invoice? What is the invoice date of this payment? It really seems that this is the invoice we are looking for!

**Comment by koush** [comment]
What is your email? I'll send it.

**Comment by gschwienbacher** [comment]
> What is your email? I'll send it.

you can send it on support@fluidtime.com and cc to office@fluidtime.com 
(For reference you can check our company homepage: https://www.fluidtime.com/en/)
Thank you very much for your help!

**Comment by gschwienbacher** [comment]
@koush  thank you very much for your help. That's exactly what we needed! We'll close this issue!
