### ISSUE TITLE
Corrupted view

### ISSUE THREAD

**Issue by omahena** [koush/vysor.io#894]
Vysor displays a corrupted image when connected to iPhone 5s. Also any interaction with the screen has no effect. 

To get the video working I tried various Decoders and they all pretty much yield the same result or a black screen. 

WebAssembly - Vysor displays a notification that a video issue has been detected and offers two fixes and none of them work - just a black screen can be seen.

Native SW - black screen
Native HW - corrupted screen as in snapshot.
Native HW + Fallback - corrupted screen as in snapshot 
Webcodec SW - corrupted screen but with bottom part a shade of green
Webcoded HW - corrupted screen as in snapshot
Webcoded HW + Fallback - corrupted screen as in snapshot

[Log](https://gist.github.com/VysorLogs/79316b0a5d6e993dd4587c21c4118917)

![image](https://user-images.githubusercontent.com/7646213/128666579-741b2508-4c1f-48e9-b6d2-3957c589f1e5.png)

Is there some other setting that I can try to tweak to get Vysor working?

I am no expert but the issue feels like the feeds I see where the video resolution does not fit the expectations / requirements of the codec.

**Comment by koush** [comment]
I'm actually shocked it even works on the iPhone 5s. What Mac model is this?

**Comment by omahena** [comment]
Hehe... Uhm... Oh... you know... The Mac mini (Late 2012). :P Sporting a 2,5 GHz Dual-Core Intel Core i5, 16GB of RAM and MacOS 10.15.7.

Honestly, it is not that bad. It may be almost 10 years old but it is good enough to run XCode. Sure, it is not... ideal. And if I had a few grand to "throw away" to marginally improve on what I am trying to do on it, I would certainly make the investment. Clearly I wouldn't choose it as a primary development platform. For that I use an AMD Ryzen 9 5950X based system. It's a lot faster that the Mac mini... And I'd rather have XCode on my Windows... But... Apple doesn't think that is cool. So when buying top of the line hardware for all platforms you target is not an option - one makes compromises.

All hardware dates aside... It would seem there is enough CPU power in the Mac Mini to decode a video stream. And yes, the iPhone 5S might have a bit of a tight video encoding budget. But with a HW accelerated codec... It might just work. I am not expecting a 120Hz refresh rate. Just enough to interact with the remote system. The speed at which the half of the screen Vysor currently works for is fast enough for me. The app I am debugging still runs absolutely smoothly even with Vysor active and no slowdown is noticeable.

I'll understand if you don't think it is possible to make Vysor work on an iPhone 5S. Such an old device is not your primary target. So if it is a small tweak - I'd appreciate your effort. But if it's a lot of work we can just close this issue. :)

**Comment by koush** [comment]
Yeah, unfortunately I'm not going to support devices that far back. I think the target is iPhone 8+. Thanks for the report.
