### ISSUE TITLE
can't use vysor on a Mac with Android devices anymore

### ISSUE THREAD

**Issue by janb3c** [koush/vysor.io#895]
Since some weeks I can't use vysor anymore when trying to launch the phone. After pushing the "play" button I get this error message:
<img width="771" alt="Bildschirmfoto_2021-08-09_um_11_12_48" src="https://user-images.githubusercontent.com/88656661/128686413-6a12e549-bc1c-4338-b39c-e441cf15d91d.png">

Other team mates have the same issue. I tried different versions off vysor. thanks for your help.
Kind regards
Jan

**Comment by koush** [comment]
Can you generate a bug report please?

**Comment by janb3c** [comment]
this isn't possible. I get a 500 status:
<img width="656" alt="Bildschirmfoto 2021-08-09 um 19 36 25" src="https://user-images.githubusercontent.com/88656661/128749388-5547c91b-84e9-4837-b489-0baab89b7265.png">

**Comment by koush** [comment]
You can disable the logcat (which may be large or have unprintable characters, causing a GitHub error). That should fix it.

**Comment by koush** [comment]
Also, if you don't mind, please join the discord server and I can help you in chat. https://discord.gg/xR8DpZe7

I've been trying to track this issue down, and I think it's environment related. Maybe another adb running or adb mismatch or something.

**Comment by janb3c** [comment]
tried but invite is now invalid

**Comment by koush** [comment]
Sorry, here's the updated link. https://discord.com/invite/tz5qk3wyR2

**Comment by koush** [comment]
this should be fixed, please confirm.
