### ISSUE TITLE
Feature Enhancement: Sync Toggle Audio depend on Phone

### ISSUE THREAD

**Issue by idkodkak** [koush/vysor.io#897]
For now when adjusting the sound from phone. there is still the same at the output. This problem is very messy for me.

**Comment by koush** [comment]
I dont understand what you're asking for.

**Comment by idkodkak** [comment]
When I mute sound on Phone, the sound mirror doesn't occur the same. And also I can't separate the soundtrack and sound effects in-game I record. Because the Toggle Audio is not the same I set it at my phone app.

**Comment by idkodkak** [comment]
> I dont understand what you're asking for.

When I mute sound on Phone, the sound mirror doesn't occur the same. And also I can't separate the soundtrack and sound effects in-game I record. Because the Toggle Audio is not the same I set it at my phone app.

So I want to adjust the volume and select any sound on Phone and everything can occur the same thing at the output.

**Comment by idkodkak** [comment]
Or have something I can do myself?

**Comment by koush** [comment]
The audio controls on the phone do not affect the computer. You need to use the computer audio controls to mute and control audio. This can't be fixed.

**Comment by idkodkak** [comment]
sad to hear that
