### ISSUE TITLE
Can no longer connect wirelesly 

### ISSUE THREAD

**Issue by GeoSaffer** [koush/vysor.io#898]
When clicking on the wireless connect button vysor window says Connecting to undefined and then stops working. this use to work before the last update..

https://gist.github.com/VysorLogs/f119321b770576aa3e61d3cdca05f16d

**Comment by GeoSaffer** [comment]
![image](https://user-images.githubusercontent.com/10066102/128784711-4de86e5d-f875-417b-a6a9-6073bca68fc1.png)

**Comment by GeoSaffer** [comment]
![image](https://user-images.githubusercontent.com/10066102/128784829-29f89da2-0ea4-4b56-b757-6d038ffceee1.png)

**Comment by GeoSaffer** [comment]
![image](https://user-images.githubusercontent.com/10066102/128784857-4b817800-d4b4-49da-971c-f0ea4b6399d0.png)

**Comment by koush** [comment]
you did not generate a proper bug report or fill out the bug report template.

**Comment by GeoSaffer** [comment]
Id did include the gist link created with the bug report.

**Comment by GeoSaffer** [comment]
it was generated by vysor app
