### ISSUE TITLE
Window resizing is wonky

### ISSUE THREAD

**Issue by The-MAZZTer** [koush/vysor.io#9]
When you resize the client window, it normally fixes itself to the proper aspect ratio. However, if that fixed size would be bigger than the desktop size it doesn't quite work right. Easiest example is maximizing the window when the device is in portrait mode.

Also when the device rotates the window may not resize back to how I want it to be. Not sure if you're doing it already but remembering separate window sizes for portrait/landscape would help here.

Possibly a separate maximize mechanism that would properly choose the optimal largest window size, as well.

**Comment by JasonM77** [comment]
Going into full screen mode on a Mac is also wonky - portrait view is stretched to the full screen width and I only get to see the top third of the phone screen.

**Comment by The-MAZZTer** [comment]
I more recently noticed if you get disconnected and it reconnects, your window will resize back to the default size. I would expect that the current window size is preserved if possible (eg if the device was in a different orientation the window would still require a resize).

**Comment by anawim** [comment]
windows sizing as a whole should be reconsidered. I don't like the default and there is no way to change it once for all. Aspect ratio in my case is OK when re-sizing. Handling of rotation is not optimal as portion of the android device screen may render outside of the monitor.

**Comment by koush** [comment]
should be less wonky now.
