### ISSUE TITLE
[Feature request] Shortcut to device

### ISSUE THREAD

**Issue by S0und** [koush/vysor.io#90]
I use Vysor mostly at work. My phone is next to my monitor in a dock, so if i have to do anything on my phone, i use rather the mouse and the keyboard, then removing it from the dock.

So do you have any plans to 'save a device to a shortcut' so when i click on it, it's immediately opens Vysor and connects to the particular device.

I know, the struggle is real, because now, i have to do 4 mouse clicks vs. 1.

**Comment by koush** [comment]
uhh yeah i can maybe make vysor handle specific urls, but you'll need to shortcut/bookmark them yourself. i can't add more icons to the app dock, etc. only one per chrome app.

**Comment by koush** [comment]
Vysor reconnects automatically. Can just leave the disconnected window open. I'm going to close this as "won't fix" as it's a decent amount of work, and not enough people requesting it. Feature creep.

**Comment by leaskovski** [comment]
If you ever look through the backlog of closed feature requests, this one would be a +1 for me, but the work around of leaving the window open gets me by for the moment.
