### ISSUE TITLE
Android: Audio Mirroring on Shared Devices does not work

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#901]
**To Reproduce**
1. Connect to Vysor Device from Remote Vysor Shared Server / Shared Device link
2. Open Youtube on Device
3. Toggle Audio Mirroring 
4. Audio does not Mirror to Controlling Remote Mac

**Expected behavior**
Audio should mirror to Controlling Mac. When using Vysor Audio Mirroring on Local Host Mac the Audio Mirrors just fine.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Android (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 10

**Comment by amacado** [comment]
Same/Similar problem here. I can see the Vysor Audio Output, but it won't connect.

![image](https://user-images.githubusercontent.com/8781699/129805205-06cf1da5-e529-4e1e-baf1-594bd813f6bf.png)

**Desktop**
OS: Windows 10 using Vysor Pro 4.1.92 

**Android/Mobile**
Device: Sony G3121 
OS: Android 8.0.0

**Comment by guitaristtom** [comment]
Mine isn't even showing the Vysor Audio Output in the Cast menu

**Comment by koush** [comment]
I confirmed this works on Android 10 audio. It may not work with the older cast audio implementation. That is also no longer supported, as it is an unofficial API and Android 10 has been out for 3 years.

**Comment by dieskim** [comment]
Hi,

I just tried this once again on my devices and it does not work.

Device: Samsung Galaxy A12
Software Version: Android 11 - One UI Core Version 3.1

To Reproduce
Steps to reproduce the behavior:

1. Connect to Vysor Device from Remote Vysor Shared Server / Shared Device link
2. Open Youtube on Device
3. Toggle Audio Mirroring
4. Audio does not Mirror to Controlling Remote Mac
