### ISSUE TITLE
Vysor Bug - Connecting to multiple Share Servers - device names not saving correctly

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#902]
**To Reproduce**
1. Connect to Two or More Share Servers
2. Try to Save Names of Devices
3. Open devices and notice that names dont match across devices
4. Notice saving names of devices on different share servers also dont work correctly

Notice in the screenshot below how device name in the list is Mi A3 but on device it is IT2

<img width="460" alt="Share Devices Names" src="https://user-images.githubusercontent.com/9603625/129305602-c804fa8b-3b6b-4c32-b632-b4b130ea9570.png">

**Comment by dieskim** [comment]
@koush any way you can get this fixed? Trying to use vysor more with others remotely but its hard when the device labels dont work. Thanks

**Comment by koush** [comment]
fixed
