### ISSUE TITLE
Vysor Bug - Can not share devices from multiple Host Macs using same Vysor Account

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#903]
**To Reproduce**
1. Open Vysor on Mac 1
2. Open Vysor on Mac 2 and click Share All Devices
2. Copy Link
3. Open Link on Mac  1 and Connect to Devices
4. Open Vysor on Remote Mac 3 and Click Share Devices
5. Copy Link
6. Notice that the link from Mac 2 / Mac 3 are the same - so you cant access devices from multiple computers 

**Expected behavior**
Should be able to share devices from Multiple Host Macs to Remote Macs.

This works fine when using multiple accounts but not when using the same account - if using multiple Macs Multiple Licenses (one per Mac) would of course be the best setup - but for some testing where a user might have devices on multiple hosts (Macs) this seems to not work currently

**Comment by koush** [comment]
This is by design. The Share all button creates a per account persistent url.
