### ISSUE TITLE
after update can't see the UI to launch mirror, it only stays in the tray

### ISSUE THREAD

**Issue by marcrdz911** [koush/vysor.io#904]
there should be an option to choose when to upgrade, version 3.1.4 was a lot better

**Comment by marcrdz911** [comment]
windows 7... cant see the version now of vysor because it does not show the window...it only stays in the windows notification area as an icon, right click works, shows option exit, open, and device. if i click open it does not open the window.

**Comment by koush** [comment]
Try restarting pc please.

**Comment by koush** [comment]
incomplete issue template.
