### ISSUE TITLE
Incognito tabs in Chrome | Black Screen Issue

### ISSUE THREAD

**Issue by SiriusED** [koush/vysor.io#905]
Hi, The issue desc:
I installed the app (Version 4.1.58), then launched it on my PC (Windows 10 Pro\20H2, Build: 19042.1110) and Chrome (Version 92.0.4515.131 (Official Build) (64-bit)) then ran it and opened Chrome on my Android phone, All was fine until I opened new chrome tab as **Incognito**, after tab opened I couldn't see the actual tab, instead I have been seeing an black screen. Same issue in some other apps that requires log-in and when I go to the log-in page I see fully black screen. I just wanna know is that bug or its normal behavior of the Vysor app?

**Comment by koush** [comment]
This is normal behavior. Banking apps, DRM apps, authenticator, etc, all disable screen capture to prevent leaking of private/sensitive information.

**Comment by SiriusED** [comment]
Ty for fast answer
