### ISSUE TITLE
Android: Vysor and ADB Connection Issues

### ISSUE THREAD

**Issue by aaronxiong1991** [koush/vysor.io#910]
**To Reproduce**
1. I connected the android device to the laptop with a micro-USB cable
2. Execute command "adb devices" in command prompt. The result shows the device is connected
![image](https://user-images.githubusercontent.com/31665658/130131598-629d039c-b597-445e-9f2d-a7f8212595ca.png)
3. Then I launch Vysor and try to view the device, it successfully mirroring the Android device
4. However, the adb connection between the android device and the laptop is disconnected. I need to execute command "adb devices" to reconnect, but then the Vysor stops mirroring since it is disconnected after executing the command.
![image](https://user-images.githubusercontent.com/31665658/130132291-5bea9376-d667-40d4-96b2-c5f482202eaf.png)

**Expected behavior**
I could have both connections(windows-android device, vysor-android device) happen at the same time before.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Android (please complete the following information):**
 - Device: N/A
 - OS: Android 6

**Comment by koush** [comment]
You are running an out of date adb on your Windows. I suggest updating to the latest.
Alternatively, point Vysor to your windows directory that contains adb using this option:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/73924/130665582-20479fd5-39d7-4617-8220-07bff580fed1.png">

**Comment by aaronxiong1991** [comment]
Hi Koush, I have updated the Vysor to point to the windows directory that contains adb, which resolves my adb connection conflict issue. Thank you for your repley.
However, I wonder how to get the latest adb install properly to resolve this issue as well? Because I do try to use option from the Vysor UI?
![image](https://user-images.githubusercontent.com/31665658/130799837-dc4704ec-8fc6-4119-8a31-669655e05281.png)
Actually, my the vysor I am using in my C drive currently is from my colleague, not really from installation.
