### ISSUE TITLE
Android: No audio

### ISSUE THREAD

**Issue by jacklongford** [koush/vysor.io#913]
Hello,

I have paid for a premium subscription and can't get audio to play on my Macbook from Nvidia Shield. I have toggled the 'Use Android 10 audio mirroring' option in settings but this does not work. Could you please let me know how to fix this?

Thanks

**Desktop (please complete the following information):**
 - OS: Mac

**Android (please complete the following information):**
 - Device: Nvidia Shield

**Comment by koush** [comment]
incomplete issue template.
