### ISSUE TITLE
Android: Sound/audio not working

### ISSUE THREAD

**Issue by jacklongford** [koush/vysor.io#914]
**You must attach a Vysor Bug Report Link**
I don't know how to trigger the bug because sound is not playing on my Macbook throughout any point of using the app.

**To Reproduce**
Not sure how to describe the steps as the sound just doesn't play on my Macbook. 

**Expected behavior**
Sound to play on Mmy acbook from Nvidia Shield

**Screenshots**
No screenshots applicable

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6

**Android (please complete the following information):**
 - Device: Nvidia Shield
 - OS: Shield Android TV SW Version 8.2.2
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**
I have tried toggling the 'Use Android 10 audio mirroring' option but it still doesn't do anything.

**Comment by koush** [comment]
> You must attach a Vysor Bug Report Link
> I don't know how to trigger the bug because sound is not playing on my Macbook throughout any point of using the app.

Yeah, so you create a bug report after you click the headphones button

**Comment by jacklongford** [comment]
@koush Thanks for your reply! I followed your instructions, here's the link - https://gist.github.com/VysorLogs/536ae7c6b81669805f50f30465739975

**Comment by koush** [comment]
Ok, I see the problem now. Shield is a chrome cast device, so it does not allow chrome casting audio to other devices. Once Android 10 becomes available on shield, audio mirroring will be supported on Shield. I think this is due sometime this year.
