### ISSUE TITLE
Android: No devices recognised since update

### ISSUE THREAD

**Issue by Andy123INS** [koush/vysor.io#917]
Vysor Bug Report Link
https://gist.github.com/VysorLogs/10cc125ea1adc3991c67e11dc529020c

Steps to reproduce the behaviour:
1. Upgrade to Vysor Pro 4.1.97

**Additional context**
Now WIFI or plugged in Android device aren't recognised (tested with Samsung Tab A 2019 & Samsung Tab A7 both on Android 11)
All the normal steps to resolve haven't worked such as different Adb drivers, restarting machine and tablets, uninstalling/reinstalling Vysor and Adb drivers or using a different cable. 

Vysor seems to be trigging a software restriction policies which it wasn't doing before this latest update. 
\AppData\Roaming\vysor\adb.exe

**Comment by Andy123INS** [comment]
Hi Koushik,

Thanks for the replies, our firewall settings haven’t changed and adding specific rules for adb.exe doesn’t fix the issue either.

However, if you manually start the adb server it all works.
This is happening on 3 of 5 machines all of which are running the latest build, those with the old build work perfectly.

For now I’ve created a bat file for users but this isn’t a long term fix.

***@***.***

Regards
Andrew Terry
Customer Support Team Leader
123 Insight Limited

Tel: 01489 860851<tel:01489860851> - Option 2
Web: www.123insight.com<http://www.123insight.com/>

[A close up of a logo    Description automatically generated]<https://twitter.com/123insight>
[A close up of a sign    Description automatically generated]<https://www.linkedin.com/company/123-insight-limited/>
[A close up of a sign    Description automatically generated]<https://www.youtube.com/user/123insightsoftware>
[logos]

The information in this e-mail is confidential and may be legally privileged.  It is intended solely for the addressee.  Access to this e-mail by anyone else is unauthorised.  Although we have taken every reasonable precaution to ensure that any attachment to this e-mail has been checked for viruses we advise you to carry out your own virus check before opening any attachment as 123 Insight Limited cannot accept liability for any damage sustained as a result of any software viruses. 123 Insight Limited is registered in England and Wales, company registration number 4624870, registered Address 10 Mill Court, The Sawmills, Durley, Southampton, Hampshire, SO32 2EJ.

**Comment by APHD-SPG** [comment]
When trying to restart the adb.exe, I am getting an error:  adb.exe kill-server
This program is blocked by group policy. For more information, contact your system administrator.

Any information I can give my Systems Admin to help troubleshoot? The previous versions have never had a problem.   Version 4.1.98

**Comment by Andy123INS** [comment]
> When trying to restart the adb.exe, I am getting an error: adb.exe kill-server
> This program is blocked by group policy. For more information, contact your system administrator.
> 
> Any information I can give my Systems Admin to help troubleshoot? The previous versions have never had a problem. Version 4.1.98

**Comment by Andy123INS** [comment]
From CMD try running 
CD %USERPROFILE%\AppData\Local\vysor\app-4.1.77\resources\app.asar.unpacked\native\win32
then
adb.exe start-server

**Comment by APHD-SPG** [comment]
Thanks.  Unfortunately that doesn't exist.  My app is in %USERPROFILE%\AppData\Roaming\vysor\ and the app directory does not exist.

**Comment by koush** [comment]
I think I know a change that may have caused this. Will take a look.

I made a change to copy the exe to a non installation directory before running it. For some reason this does not work.

**Comment by Andy123INS** [comment]
@APHD-SPG  In that case I suspect you're using the browser app, this uses a different ADB server (WebUSB)

If you can download the Windows App and install the universal ADB drivers

**Comment by Andy123INS** [comment]
@APHD-SPG, oh where does task manager show Vysor running from 

![image](https://user-images.githubusercontent.com/89639746/131541858-8c824e4e-5008-43af-babb-61aa4554014f.png)

**Comment by koush** [comment]
Please check v4.1.99 update. Click reload vysor to get updated.

**Comment by APHD-SPG** [comment]
@koush Awesome!  4.1.99 worked!
