### ISSUE TITLE
IDEA:Typing on PC and then transport to phone, is it available?

### ISSUE THREAD

**Issue by dustbird** [koush/vysor.io#92]
Fist of all, please let me say thanks to the Vysor's developer. It's really convenient for my daily life.

But there is a problem, when I use keyboard on PC to type Chinese characters,I must to click the right word on word-choose bar instead of using press number key if the right word isn't the first.

I know this problem is due to Chinese input. But I thought if Vysor can use Chinese input on PC to type characters and then transport characters to phone's input box when I typing(just like AirDroid), it can solve many typing problem. Of course, not only Chinese characters, but also Japanese characters, French character and so on, will get faster typing feeling.

If you want to know more details about this advice, please send a e-mail to me. My e-mail address is 'blbrd@outlook.com'. I do really hope to receive from you!!~

I'm not good at English, hope that you can understand my meaning...haha...

A fans of Vysor~

**Comment by koush** [comment]
fixed with international keyboard
