### ISSUE TITLE
CPU Lockup on Kubuntu

### ISSUE THREAD

**Issue by patggg** [koush/vysor.io#923]
1. Leave Vysor open for undetermined amount of time
2. Return to find computer is completely locked up
3. Android is unresponsive

**Expected behavior**
System does not crash

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.3 LTS

**Android (please complete the following information):**
 - Device: ODroid N2
 - OS: Android 9
 - Vysor Bug Report Link: Cannot obtain logcat as device is non-responsive after the event, report after fresh reboot : https://gist.github.com/VysorLogs/37ce305434cd22e7aa4cf5e224693dc6

**Additional context**
Syslog excerpt attached for CPU lockup event
[syslog.txt](https://github.com/koush/vysor.io/files/7080257/syslog.txt)

**Comment by patggg** [comment]
Happened again while actively using Vysor this time.
Sep  1 14:10:43 kernel: [156359.652870] watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [vysorapp:3248899]
....
Sep  1 14:10:43 kernel: [156359.652922] CPU: 2 PID: 3248899 Comm: vysorapp Tainted: P         C OE     5.4.0-81-generic #91-Ubuntu

**Comment by patggg** [comment]
In this event the Andriod device is still running. Seems to originate in the desktop code.

**Comment by koush** [comment]
Try the non-GPU options for rendering . This likely is a bug in your system.
