### ISSUE TITLE
Andriod Pro License not recognized.

### ISSUE THREAD

**Issue by toddmeagher** [koush/vysor.io#925]
I have paid for Pro user corp@gher.com but continue to get this error.

![vysor](https://user-images.githubusercontent.com/7864223/131551583-c3ee887e-8f23-4f7e-bdbf-dde7139ef2dc.jpeg)

**Comment by koush** [comment]
Try logging out and logging back in. Also if you're behind a corp firewall or vpn, may want to try retrieving the license with your VPN off.

Let me know if either of these resolves the situation. If not, please generate a bug report while this window open and provide the link here.
