### ISSUE TITLE
After using and uninstalling Vysor my phone won't connect normally to any PC via any USB cable

### ISSUE THREAD

**Issue by IvanKonst** [koush/vysor.io#928]
Please don't close the issue again. I can't fill the bug report link because it won't be relevant to the issue.

**To Reproduce**
1. Install Vysor.
2. Use it. 
3. Uninstall it after a while.
4. Try to connect the phone to the PC to transfer files with USB.

**Expected behavior**
The phone connects to the PC and shows me all the files in it.

**Desktop (please complete the following information):**
 - Windows 10

**Android (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: Android 8
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**
![bugreport](https://user-images.githubusercontent.com/33325917/132349382-96e1c59b-e051-4c3f-9351-236140c80c21.png)
It seems that it leaves some kind of residue files that prevent the phone to connect to the PC. It happens on 2 different phones that have used Vysor before and now they are both not able to connect to any PC via any cable. USB debugging is enabled on both phones. The other phone is Xiaomi Redmi note 2

**Comment by koush** [comment]
Vysor does not install any drivers, but it does suggest installing the manufacturer drivers.

**Comment by koush** [comment]
This is not a Vysor issue.

**Comment by koush** [comment]
Please don't create this issue again.
