### ISSUE TITLE
Android: Feature:  Record Screen should also capture audio during recording.

### ISSUE THREAD

**Issue by mikegonzalez2k** [koush/vysor.io#931]
I wasn't sure where to put Feature Requests.  It would be nice if while you are Recording the Screen you could also capture Audio to the MP4.  This would be a great improvement when demoing an app.  Showing a recording of your app opening a video and playing it with the full audio in the movie.  Please add this to future iterations of Vysor.  Maybe make an option, if you have the Capture Audio Toggled, it will also be captured within Record Screen.

**Comment by koush** [comment]
yup https://github.com/koush/vysor.io/issues/533
