### ISSUE TITLE
Mac: ADB not running after assigning Pro license to Vysor

### ISSUE THREAD

**Issue by iambac777** [koush/vysor.io#932]
I assigned my Pro license to a newly downloaded Vysor version on my Mac running Big Sur (Vysor Pro version 2.1.2).  I tried connecting 3 different Android's which were discovered but only ever showed a crash screen.  NOTE:  These Androids all viewed successfully with the ad supported free version.  

I restarted the Mac and now I see a status of: " ADB not running.  Click Find Devices to Get started" yet I see no "find Devices" option anywhere.  Thanks for the help

NOTE I have tried both reload Vysor and Reset Vysor

**Comment by koush** [comment]
> Vysor Pro version 2.1.2

Not sure where you even found that, that is YEARS old. Please redownload.

**Comment by iambac777** [comment]
hmmm....I definitely downloaded from Vysor.io/download.  Redownloading now 4.1.77. Thanks
