### ISSUE TITLE
Device not found error and devices disappear from panel

### ISSUE THREAD

**Issue by linuxlad** [koush/vysor.io#938]
There are a couple of issues. The first is that when I try to connect to one of the devices from the system tray, I receive the following error message: "Error Connecting to Android Device: Device not found", so I have to use the "**Connect Network or Shared Device**" button. See screenshot.

The 2nd issue is that after connecting both devices using that button and they have been added to the panel and I close Vysor to the tray, after a few minutes, they both disappear from the Vysor panel. See screenshot.

![Vysor](https://user-images.githubusercontent.com/61941051/133349891-73f4d47d-a72b-4d81-979e-ea81b1ccec58.png)

**Comment by koush** [comment]
missing logcat
