### ISSUE TITLE
iOS: Mirroring Disconnected Offset Out of Range with version 4.1.77

### ISSUE THREAD

**Issue by jjcaballero** [koush/vysor.io#940]
**To Reproduce**
Vysor version: Vysor-4.1.99(Runtime-4.1.77)
Right after opening the device, the offset warning is popped up:
` offset is out of range. It must be 0>= and <=4 but received 8. Device screen will not be displayed/mirrored.`
This is the same error reported in https://github.com/koush/vysor.io/issues/856 which was fixed in latest release.
I am using the 4.1.77 which I think it is the latest one 

**Expected behavior**
The device screen should be visible

**Screenshots**
Check https://github.com/koush/vysor.io/issues/856

**Desktop (please complete the following information):**
 - OS: MacBook Pro (15-inch, 2019)

**iOS (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.6
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/64052b0c34da923e89de9bfdeff77816

**Comment by akashthakkar09** [comment]
any luck? We are facing this issue even after upgrading the new version of vysor but it's still an open problem.

**Comment by jjcaballero** [comment]
I don't see this error anymore. There have been a bunch of changes on the server, thus I can't figure out which one was the one that made it work. Changes:

- Just reinstall Vysor
- SW upgrade of Catalina 2021.006
- SW upgrade of Monterrey
- Vysor version:
     - Now: 4.1.102 (Runtime 4.1.77)
     - Before: 4.1.99 (Runtime-4.1.77)

As this happened all of a sudden and others are facing it too, it would be great to learn from Vysor admins and know further about this problem.
