### ISSUE TITLE
Recurring Payment Refund in_1JSwxyIX57f4SV6L0pOjJqYn

### ISSUE THREAD

**Issue by joedelrosario** [koush/vysor.io#941]
Good day!

I would like to request a refund on this particular invoice (in_1JSwxyIX57f4SV6L0pOjJqYn).
I have not used Vysor ever since the pandemic forced me to work from home.
On August 28, I was emailed that I have a pending payment. 
The payment method I use is a payroll account that receives money on the 10th and 25th of the month that I empty almost immediately.

Therefore my subscription should have been automatically cancelled on the 3rd and therefore my payroll account should not have been charged money. Not to mention the fact that I also manually cancelled my subscription before that on the 28th Aug.

![image](https://user-images.githubusercontent.com/71033632/133623931-a7c7da74-dd4d-4ba6-ba88-0d22335e1c82.png)

Unfortunately, I neglected to empty my payroll on the 10th and Vysor charged me on the 14th. This should not have happened and I would like my money back and cancel the annual recurring payments.

Kindly reply on how we should proceed.

Thank you.

**Comment by joedelrosario** [comment]
Up

**Comment by koush** [comment]
![Uploading image.png…]()

**Comment by koush** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/73924/133897482-92e6e1c4-b900-4266-ad69-90a1174fa2a8.png">

**Comment by joedelrosario** [comment]
Dear Koush,

Good day!

Thank you for your response and for accepting my refund request.

Unfortunately, several days have passed and the money still hasn't been credited to my bank account.
May I know the lead time for the transaction?
If it has already been debited on your end, may I know the 23-digit Acquirer's Reference No (ARN) of the transaction so that the bank itself would be the one to handle the issue.

Regards,

Jomar R. del Rosario


________________________________

**Comment by joedelrosario** [comment]
Koush,

Good day!

Thank you for your response and for accepting my refund request.

Unfortunately, several days have passed and the money still hasn't been credited to my bank account.
May I know the lead time for the transaction?
If it has already been debited on your end, may I know the 23-digit Acquirer's Reference No (ARN) of the transaction so that the bank itself would be the one to handle the issue.

Regards.

**Comment by joedelrosario** [comment]
Up
