### ISSUE TITLE
Recurring Payment Refund in_1JSwxyIX57f4SV6L0pOjJqYn #941 - Cont'd

### ISSUE THREAD

**Issue by joedelrosario** [koush/vysor.io#948]
Dear Koush,

Good day!

Thank you for your response and for accepting my refund request.

Unfortunately, several days have passed and the money still hasn't been credited to my bank account.
May I know the lead time for the transaction?
If it has already been debited on your end, may I know the 23-digit Acquirer's Reference No (ARN) of the transaction so that the bank itself would be the one to handle the issue.

Regards

**Comment by koush** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/73924/134819680-b4c737a3-1708-4422-b3fd-7136f5d6adcf.png">

**Comment by koush** [comment]
Sorry, I don't have that info from my card merchant.

**Comment by joedelrosario** [comment]
I understand.
Also, the refund had posted anyway yesterday - ten full days after you started the refund so all is well.
Thank you for your time.

Regards.
