### ISSUE TITLE
Fill Display - presentation mode

### ISSUE THREAD

**Issue by wbarnes4393** [koush/vysor.io#95]
When going full screen, it only fills part of the screen anchored to the left.  This would be terrific as presentation app if I could make it fill the PC screen, thereby filling the projector screen the PC is attached to (in the classroom).  Would gladly pay for such a feature.  There are existing apps that do this via wifi, but the USB connection seems much stronger, fast, and private....

**Comment by koush** [comment]
This is fixed, must use the fullscreen button
