### ISSUE TITLE
Drag and drop an APK file from Windows to an Android device is not working

### ISSUE THREAD

**Issue by pswisher** [koush/vysor.io#950]
I can drag and drop most other files from my windows laptop to my Samsung device mirrored on that laptop. I drag the file, such as an image or video, and I am asked how I want to open the file. After my selection, I can open the file. 

However, if I drag and drop an APK, an information bubble displays this text: 'Drag and drop to transfer selected files to Android', with an OK button. Note that as my finger is on the left-mouse button, I cannot click OK. The message goes away. When I let go of the mouse to 'drop' the file, nothing happens. 

Copy paste does not seem to do anything. 

I saw a message about switching the device's keyboard to Vysor, but I do not know how / where to do that. 

I assume there is some permission on the phone that needs to be enabled to allow dropping of the APK to the phone, but I am not sure what permission that is. 

Thank you.

![image](https://user-images.githubusercontent.com/91615553/135287590-1e15a080-04cb-4d63-85f9-9c9dd70df4da.png)

**Comment by sperezm97** [comment]
hello @koush , could check this? it also happens on MacOs

**Comment by coleboillat** [comment]
At least for me, Vysor would just automatically install the app - so check the apps folder and see if it's there!

**Comment by koush** [comment]
The drag and drop doesn't drag it into the file manager like your screenshot makes you think. it goes into your Vysor folder on your sd card.

apk are installed automatically, there's no feedback, it's silent. same way Vysor is installed via the desktop app. granting permissions is unnecessary.
