### ISSUE TITLE
Chrome browser error "failed to execute decode on video decoder" !!

### ISSUE THREAD

**Issue by Alaingent** [koush/vysor.io#951]
Dear,

since yesterday afternoon only, i have a new issue from browser version  of Vysor, and i couldn't use it anymore.

Message appear when i click on "Connect" :

Screen Capture below : 

![erreur Vysor 290921](https://user-images.githubusercontent.com/64490221/135405674-a17d9083-f216-4948-b7b1-070451f18125.png)

Also if my image doesn't work : "Mirroring disconnect . Invalid state error Failed to execute 'decode' on 'video decoder' . Cannot call 'decode' on a unconfigured codec.

Please help me it is urgent because i use a lot Vysor all day !

thank you.

Alain

**Comment by mogli91** [comment]
We were facing the same issue and couldn't tie it to a particular hardware or browser version (for some it worked, for some it did not work). What solved it for us was changing the decoder manually like so:

Vysor (browser or desktop app) > Settings > Image Quality > Decoder

This was initially set to "Native Hardware" (not exactly sure anymore) initially and it failed. When we set it to "WebAssembly" it worked.

**Comment by Alaingent** [comment]
thanks a lot, i don't know why it is changed because i do nothing, BUT it seems to be ok now ! have a nice week end.

**Comment by wolflcy28** [comment]
> We were facing the same issue and couldn't tie it to a particular hardware or browser version (for some it worked, for some it did not work). What solved it for us was changing the decoder manually like so:
> 
> Vysor (browser or desktop app) > Settings > Image Quality > Decoder
> 
> This was initially set to "Native Hardware" (not exactly sure anymore) initially and it failed. When we set it to "WebAssembly" it worked.

Sorry, may I ask how could I click on the "Setting" with the "mirroring disconnected" pop-ed up? I could not find another setting button on the main app interface. Thank you.

**Comment by Alaingent** [comment]
yes exactly, only by changing with "webassembly" thank you.
