### ISSUE TITLE
vysor screen black

### ISSUE THREAD

**Issue by reddy5258** [koush/vysor.io#957]
bugreport
https://gist.github.com/bfd087dfb97b215c0535d65acf63fd07

getting below error as in attached screenshot while connecting vysor to pixel devices,
and unable to connect device 

please let me know how to resolve this error

**Comment by reddy5258** [comment]
bugreport at below link
https://gist.github.com/bfd087dfb97b215c0535d65acf63fd07

**Comment by koush** [comment]
use a different decoder.
