### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by vsyorerror** [koush/vysor.io#969]
https://gist.github.com/7b974e943572b2cd4ca813cad774e84d

1. Go to - Android Device
2. Click on  Samsung Android - New window opens and mirrored screen shows 
3. Mirroring disconnected - Invalid state error - failed to excute 

**Expected behavior**
I would expect the phone to be mirrored or for for vysor to ask permission on the android deceive 

**Screenshots**
![image](https://user-images.githubusercontent.com/93200535/138881929-b5522951-e739-477c-9cdb-f408293663d7.png)

**Comment by koush** [comment]
use a different decoder, webcodec doesn't work on your pc.
