### ISSUE TITLE
Screen does not working

### ISSUE THREAD

**Issue by ramonphonorato** [koush/vysor.io#97]
I'm trying to connect my phone but i always get this screen, not matter what. How can i fix it ?

Vendor : Motorola 
Model : Moto E Dual TV XT1025 
Android : 5.1

![image](https://cloud.githubusercontent.com/assets/7904444/11530632/6e04c06a-98dd-11e5-8aa6-e7d27ffe05da.png)

**Comment by chajang** [comment]
In my case, my MAC or PC must connecting to the Internet to let the app work.

**Comment by Jspoor** [comment]
same situation here.
running adb over network. Device is correctly discovered, but get above sad face and "your android screen is unavailable"

**Comment by koush** [comment]
Please use the support link in the app. This is not the right place to post issues.

**Comment by koush** [comment]
You also need to attach logs.

**Comment by ramonphonorato** [comment]
Ok Koush, let me do it, thanks.
