### ISSUE TITLE
Android: Unable to connect to control socket

### ISSUE THREAD

**Issue by betoflakes** [koush/vysor.io#972]
**To Reproduce**
1. Connect phone
2. Click on View Device

**Expected behavior**
View my device.

**Screenshots**

![Captura de Pantalla 2021-10-28 a la(s) 14 18 17](https://user-images.githubusercontent.com/1946702/139329654-bbe1ae70-1451-4615-9b40-225c0d88595b.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12

**Android (please complete the following information):**
 - Device: Huawei P30
 - OS: Android 11
 - Vysor Bug Report Link: https://gist.github.com/1636cf52d3d85c43d6a0ddda44e06db5
 
**Additional context**
 - Pro Lifetime License

**Comment by koush** [comment]
your device adb server is crashed in the log. probably need to reboot the phone.

**Comment by yuhezhong** [comment]
same
