### ISSUE TITLE
Android: Short Description of Issue

### ISSUE THREAD

**Issue by alnospam64** [koush/vysor.io#973]
Apologies to ask this question here but I cannot an answer:
I need to purchase a lifetime license for work and need to instruct the purchasing department.
They will buy the license and transfer it to me.

Are there any instructions on how to transfer a lifetime license to someone else?
Thanks

**Comment by koush** [comment]
if you buy a lifetime license, you can create a transfer code at billing.clockworkmod.com

**Comment by alnospam64** [comment]
Hi,
One of our buyers bought a lifetime on Nov 10
![image](https://user-images.githubusercontent.com/84664107/143070384-5b948905-4369-4e60-bb26-474013a26b88.png)

When I sign in into billing.clockworkmod.com and enter the transfer code it says "No Orders Found"
If I try from the app in windows it says "No License Found"

What shall we do?
