### ISSUE TITLE
Please add an M1 version of Vysor

### ISSUE THREAD

**Issue by 343max** [koush/vysor.io#974]
Apple is moving with a high pace away from x86, so I would really love to see a even faster Apple Silicon version of Vysor.

**Comment by koush** [comment]
will do

**Comment by clubtech** [comment]
+1 on this request

**Comment by Brock-Gibson** [comment]
+1 on this request as well.

**Comment by macx** [comment]
@koush Any updates on this?

**Comment by koush** [comment]
Check the prereleases!

**Comment by koush** [comment]
The m1 prerelease requires usage of the beta channel within Vysor.

**Comment by macx** [comment]
@koush 🤔 I'm already in the beta channel, Version 4.2.0.

**Comment by koush** [comment]
You need to download the prerelease dmg too. https://github.com/koush/vysor.io/releases/tag/v4.2.0

**Comment by koush** [comment]
@macx any issues?

**Comment by macx** [comment]
@koush Nope, everything is fine. Issue could be closed after the release.

**Comment by koush** [comment]
done
