### ISSUE TITLE
Launch vysor with Device SN on command line

### ISSUE THREAD

**Issue by AnyOfYou** [koush/vysor.io#975]
How to launch vysor with Device SN directly on command line?
Like use `vysor -s SN` to enter device's vysor screen directly.

Sorry to report here, I know there is [vysor-cli](https://github.com/koush/vysor-cli), I have tried to it, but [it does't work](https://github.com/koush/vysor-cli/issues/1), and got no response.

**Comment by koush** [comment]
underlying issue is fixed.
