### ISSUE TITLE
Android: vysor unable to connect to control socket

### ISSUE THREAD

**Issue by j00nie** [koush/vysor.io#976]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
Help me to fix the issue. Thank you so much

**Screenshots**
![image](https://user-images.githubusercontent.com/88373167/140269181-ac2b7613-c243-480f-9c78-42adec6e5a9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Android (please complete the following information):**
 - Device: Huawei P30
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/5d495e7ecbf22afa4decec183ea85430

**Additional context**
none

**Comment by j00nie** [comment]
its working now

**Comment by spam-min** [comment]
@j00nie how did you get it to work again? I was on the paid plan which just ended. I used to be able to connect seamlessly but now on the free plan, am getting this error.
