### ISSUE TITLE
Android: Native app does not open in Win10

### ISSUE THREAD

**Issue by Thisisallnewtome** [koush/vysor.io#980]
Using a Win10 machine, application has been installed from the website, but when I doubleclick on the icon, it does not open the menu.  I can plug in a phone and right click on the application in the status bar, and open the phone, but I cannot open the main native application to login or do anything else in the account.

**Comment by koush** [comment]
Try the following:
restart pc

if that doesnt work, try deleting:

C:\Users\YOURUSERNAME\AppData\Vysor
reinstall vysor

**Comment by koush** [comment]
Also, does the vysor app pop up if you right click the status area and click Open Vysor?

**Comment by Thisisallnewtome** [comment]
Thanks for the prompt help.  I tried the restart initially, but that did not work, this time it did, however I think the first time I uninstalled before I restarted, then installed instead of leaving it alone like this past time.  It seems to function now.

**Comment by Thisisallnewtome** [comment]
This issue is happening again.  It only opened properly the one time, and ever since it will not open.  The software still works and is in the tray, but I cannot use the controls I have paid for.

**Comment by koush** [comment]
Right click the tray and click open. Does that work?
