### ISSUE TITLE
Not Working with Realme U1

### ISSUE THREAD

**Issue by mohitsingh90** [koush/vysor.io#981]
Hi,
I tried Vysor app on Mac with my android phone (Realme U1). And this is stuck "Connecting to android". On another android phone this is working.

**Comment by yogeshseralia1mg** [comment]
It's happening for me as well. @mohitsingh90 could you find some alternative ways?

**Comment by mohitsingh90** [comment]
> It's happening for me as well. @mohitsingh90 could you find some alternative ways?

Vysor app for android is not supported by many android phones. You can try on another phone.
