### ISSUE TITLE
Android: Image corruption with Blue Archive

### ISSUE THREAD

**Issue by Renari** [koush/vysor.io#984]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Install Blue Archive: [https://play.google.com/store/apps/details?id=com.nexon.bluearchive&hl=en_US&gl=US](https://play.google.com/store/apps/details?id=com.nexon.bluearchive&hl=en_US&gl=US)
2. Attempt to play the game, strange artifacts will show up both on the device and in Vysor.

**Expected behavior**
Artifacts not happening every few seconds.

**Screenshots**
Here's two videos showing the issue. (seizure warning)
https://drive.google.com/file/d/1Y6qUO6wW9hdNoXkH2ALvYc_UQ2tb5JLO/view?usp=sharing
https://drive.google.com/file/d/1kP0qu7XYKhp0tchirLHxoQq588FR6TDC/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10

**Android (please complete the following information):**
 - Device: ROG Phone 3
 - OS: Android 11
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]
When I try to submit a bug report I get this error: 
![image](https://user-images.githubusercontent.com/1839179/142071400-91eeec83-6c9f-474f-8af1-a7cc0225b02f.png)

**Additional context**
Playing the game without Vysor doesn't cause the issue. I've also tried using scrcpy and the issue is replicated there.

**Comment by koush** [comment]
This is likely a manufacturer defect in their rendering pipeline. May be worth checking on another phone?

**Comment by Renari** [comment]
I was able to replicate the issue on a Galaxy S10 as well.

**Comment by koush** [comment]
Does it happen on any other games? Could also be a software quirk. There's nothing that can be changed here for Vysor. You could try using android's built in screen recording and I bet it would still happen in that.

**Comment by Renari** [comment]
You are correct using the built in record functionality on both the ROG Phone 3 and the Galaxy S10 produced the same issue.

**Comment by koush** [comment]
Ok, sorry this is happening but I can't do anything about it, given it repros in multiple other scenarios that do not involve Vysor.

**Comment by Renari** [comment]
I'll try to contact the devs but based on past experiences I don't think the customer service team is going to be to open to bug reports and are likely going to tell me that my phone is the issue.

Thanks for your time.
