### ISSUE TITLE
iOS: Copy/paste

### ISSUE THREAD

**Issue by cajunjoel** [koush/vysor.io#986]
**To Reproduce**
1. On an iOS device (in my case, an iPad Pro)
2. Open an app, any app that uses text. For example, Notes.
3. Select some text by double-clicking a word, sentence, or paragraph.
4. Click on COPY to copy to the clipboard
5. Switch to a Desktop App on my desktop computer (in this case, a Macbook)
6. On the Desktop, try to paste, the wrong content appears

**Expected behavior**
I expect the content that was copied in Vysor on my iOS device would be pasted on the desktop, but the contents of the clipboard aren't being transferred.

**Screenshots**
Going to skip this for now.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.1

**iOS (please complete the following information):**
 - Device: iPad Pro 10.5 Inch
 - OS: iOS 14.8.1
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/43338a6559abcd7dfedb04021e7f1107

**iOS Bluetooth Issues (optional):**
N/A

**Additional context**
The bug reports has an error at the top:

`Error: ENOENT: no such file or directory, open '/Users/richardjm/Library/Application Support/vysor/vysor-localstorage.json`

I reinstalled Vysor, cleared the "Application Support/vysor/" folder and the file wasn't recreated. Suspicious!

**Comment by koush** [comment]
iOS has native airdrop/continuity copy paste, so there's no Vysor copy paste on iOS. it would interfere with the native support
