### ISSUE TITLE
Android: adb reverse failed:FAIL

### ISSUE THREAD

**Issue by 6bartol6** [koush/vysor.io#989]
Hello:
I´m trying to toggle audio but it told me 
**adb reverse failed:FAIL**

If I try to make a bug report it says:

**Bug report Failed : Request failed with status code 500**

Previusly I Disable the button _Use Android 10 Audio Mirroring._

Regards 
Jorge

**Comment by Oxydose** [comment]
This is happening to me too what do i do

???????????

**Comment by Oxydose** [comment]
@koush do you know how to fix this
