### ISSUE TITLE
Documentation on remote screen sharing security

### ISSUE THREAD

**Issue by marcmerlin** [koush/vysor.io#99]
First: awesome software, thank you :)

I however couldn't find anything relating to remote screen sharing security
1) is it encrypted?
2) does it transit through your servers?
3) what security is there to prevent someone else eavesdropping/taking over my session?
4) can you do sharing between 2 machines on the same LAN without transiting over your server and the internet?

Note, it's ok if the answers are "it's insecure", I just wanted to know :)

**Comment by koush** [comment]
Remote screen sharing is done with webrtc which is peer to peer encrypted.
It chooses the best possible path. On a local LAN, it will use only the LAN. Otherwise it uses my TURN/STUN servers.
