### ISSUE TITLE
Screen flashes and bouncs up and down in full screen mode when switch desktop app

### ISSUE THREAD

**Issue by npes87184** [koush/vysor.io#990]
**Bug Reposrt Link**
https://gist.github.com/VysorLogs/f450c5140cea3dedb3069def24692742

**To Reproduce**
1. Enter full screen mode
2. Switch app in desktop

**Expected behavior**
It should not flash.

**Screenshots**

https://user-images.githubusercontent.com/5494432/144697818-18db086f-2603-4220-8f9b-5bc39fc6a150.mp4

**Desktop (please complete the following information):**

Linux yclin-B360N-WIFI 5.4.0-90-generic #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thank you.

**Comment by koush** [comment]
Something in Ubuntu is triggering a resize and reporting incorrect window bounds in the process, and Vysor is trying to recenter the stream. Not sure I can fix this, but obviously it is not ideal. Doesn't happen on other OS.
