### ISSUE TITLE
Unable to login vai Google or Apple login

### ISSUE THREAD

**Issue by zide-repsrv** [koush/vysor.io#993]
Vysor Bug Report Link : https://gist.github.com/ed906e18df40201c29774932ecc0491d

**To Reproduce**
1. Open Vysor for Windows (not sure if this defect exists on other operating systems)
2. If app is currently logged into Vysor profile, log out.
3. Click 'Login' within Vysor app -- The default browser opens with the page with the user options for logging in (i.e., email, Google, Apple) and Vysor app opens Vysor Sign In pop for login code.
4. In the browser, select either 'Sign in with Google' or 'Sign in with Apple'.
5. At this point, the browser displays a blank screen.  It appears a redirect is failing because a resource is not responding when requested.  

The request for https://vysor-1026.firebaseapp.com/__/auth/handler.js fails to return a response which appears to be the reason the login process isn't continuing.  The same thing happens when attempting to log in with Apple.   This has been recreated with Chrome and Firefox.  I am unsure if this might be caused by security software (I don't have privileges to disable it).  However, the software is not showing any blocked events.  

**Expected behavior**
When clicking on 'Sign in with Google' or 'Sign in with Apple' it is expected that the user is taken to either Google or Apple to complete the login process.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (build 19042.1288)
 - Chrome: 96.0.4664.45
 - Firefox: 94.0.1
 - Vysor: 4.1.102 (Runtime 4.1.77)

**Android (please complete the following information):**
 - Device: Zebra Tablet ET56DE
 - OS: Android 8.1
 - Vysor Bug Report Link: https://gist.github.com/ed906e18df40201c29774932ecc0491d

**Comment by koush** [comment]
I can confirm this issue does not occur for me, I suspect its your security software or network. The login service is provided by Firebase, which is a good hosted service.

**Comment by koush** [comment]
Worth trying off network.

**Comment by zide-repsrv** [comment]
Thanks for confirming.  I had a feeling it might be due to security software or network rules but didn't have a way to check outside of the network.   I will close the ticket.
