### ISSUE TITLE
Android: Can't see device screen on M1 mac

### ISSUE THREAD

**Issue by erawhctim** [koush/vysor.io#995]
**To Reproduce**
1. Install Vysor
2. Log in
3. Plug in device
4. Attempt to view phone screen

**Expected behavior**
I can't see the screen at all; no new window pops up when clicking the play button in Vysor, or the device name in the menu bar drop-down menu.
I've used Vysor on my old machine with this same device, no problem (so I know ADB/etc. are set up correctly)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Monterrey 12.0.1 (M1 Max chip)
 - Vysor Pro v4.1.102 (runtime 4.1.77)

**Android (please complete the following information):**
 - Device: Samsung S9 (SM-G960U1)
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/3d3e019d3543349b890d1ab6937e8183

**Additional context**
N/A

**Comment by koush** [comment]
Can you try native software and webassembly decoders? 
I'll double check on my M1 right now too.

**Comment by koush** [comment]
No issues on my M1 here. Can you try clicking reset vysor, maybe something is in a bad state.

**Comment by erawhctim** [comment]
> No issues on my M1 here

Cool, good to know! I'll double check and reset/re-install.

**Comment by erawhctim** [comment]
> Can you try native software and webassembly decoders
How are those configured? I can't find anything related to decoders in the Wiki, or in my device's debugging settings 🤔 My apologies if I'm missing something obvious...

**Comment by erawhctim** [comment]
nvm - working now.

Uninstalling the vysor APK on the device and resetting in the Vysor desktop app did the trick. Thanks!
