### ISSUE TITLE
Android issue: When I try to connect remotely I get this

### ISSUE THREAD

**Issue by joazz1** [koush/vysor.io#997]
Hi

When I use the vysor link to connect to an android phone it stays stuck on preparing vysor on android message

<script src="https://gist.github.com/VysorLogs/fb118223ed2b4bf58bbbd08c2b5f8e56.js"></script>

It only works if I am sharing the same wifi, but would like to access from work for instance. I have a pro account.

Also I downloaded the bug report but dont know how to send it?

**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**

**Expected behavior**
A short description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 11.4.10]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 10]
 - Vysor Bug Report Link: [instructions above, you must attach a bug report that contains the application errors and logging]

**Additional context**

**Comment by joazz1** [comment]
I didnt get an answer and I paid for the app, does this mean I get a refund?

**Comment by koush** [comment]
no this means you didn't fill out the bug report properly so I closed it
